### ISSUE TITLE
Broken link on Embedded App page

### ISSUE THREAD

**Issue by chrispappas** [Shopify/polaris-react-archive#10]
# Issue summary

The link within the smaller text blurb:

> This component only works within embedded apps. Read the EASDK getting started guide for more details on how to use the EASDK with Polaris.

refers to the wrong location.

## Expected behavior

The link should probably refer to the same link as the larger text above https://help.shopify.com/api/sdks/shopify-apps/embedded-app-sdk/getting-started

## Actual behavior

Navigates you to https://github.com/Shopify/polaris/blob/master/documentation/Embedded%20apps.md

## Steps to Reproduce the Problem

1. Click the link
2. Get to a 404 page on github

## Specifications

- Polaris version: N/A
- React version: N/A
- Browser: All
- Device: All
- Operating System: All

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by lemonmade** [comment]
Thanks for the issue @chrispappas. We've added this to our internal issue tracker and this should be resolved in our next release. I'll close this issue when the fix is live.
