### ISSUE TITLE
Update 'Icons' guidance

### ISSUE THREAD

**Issue by zecarlostorre** [Shopify/polaris-react-archive#10024]

**Comment by zecarlostorre** [comment]
I have all the visual assets done[ here.](https://www.figma.com/file/vO0wToyBpYjeIwr8doAAWT/Uplift-polaris.shopify.com?type=design&node-id=622-529&mode=design) and I added the icon section to [our master doc](https://docs.google.com/document/d/13LrzMI5SMzDZ3Wm117Yz4olE7PzBCFQh2_B5C07WQlE/edit#heading=h.vtf4dfs9t5ua).

**Comment by chloerice** [comment]
This was shipped https://polaris.shopify.com/design/icons
