### ISSUE TITLE
Fix flakey chromatic visual regression tests

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#10038]
For some reason, stories with `Popover` and/or `Tooltip` are indeterminately changing every time chromatic regression tests are run. Examples:

* https://shopify.chromatic.com/build?appId=5d559397bae39100201eedc1&number=19008 
* https://shopify.chromatic.com/build?appId=5d559397bae39100201eedc1&number=19170

We should figure out why this is happening and fix it

**Comment by jesstelford** [comment]
A couple hypotheses:

1. **Caused by layout shift**
    - Chromatic is taking the screenshot, then layout shift is occurring.
    - This could happen due to timeouts in the rendering pipeline forcing Chromatic to take the screenshot before the entire component has finished rendering. Eg; the VMs running the browser is under higher than normal load, so rendering takes longer, etc.
2. **Caused by inconsistent JS positional calculations**
    - The Popover relies on performing JS-based layout calculations _after_ initial render/mount.
    - These calculations could be taking variable amounts of time, so the screenshot is sometimes taken before, and sometimes taken after the full positional calculation is completed.
    - Alternatively, it could be the results of the calculations themselves being inconsistent. Perhaps due to timing with mounting and other browser layout tasks (see #1 above), or something to do with the order of rendering the components in the story.
3. **Caused by async font loading**
    - We load the Google font CSS in a blocking way before stories are rendered.
    - But that CSS triggers a non-blocking/async load of the Inter font from Google's CDN (browsers can decide the priority of loading fonts, and it defaults to "low" afaict)
    - So the screenshot might sometimes be taken when the font has fully loaded and rendered, then other times be taken when the font hasn't yet loaded (which would affect component layout and sizing, etc)
    - Possible fix here: https://github.com/Shopify/polaris/pull/9993

**Comment by sophschneider** [comment]
I was able to replicate a layout shift in storybook:

1. go to a flakey story (anything with an open `Tooltip` or `Popover`, e.g. [LegacyCard with separate header](https://storybook.polaris.shopify.com/?path=/story/all-components-legacycard--with-separate-header&globals=polarisSummerEditions2023:true)
2. Empty cache and hard reload
3. remount component on story to see layout shift

Interestingly, subsequent refreshes don't cause a layout shift, only the first after an empty cache

https://github.com/Shopify/polaris/assets/20652326/5ddb8ddd-f9ed-4a24-a3a8-451369aab19f

**Comment by sophschneider** [comment]
seems to be flakey calculations in `PositionedOverlay`

with the same window size and process followed from [above](https://github.com/Shopify/polaris/issues/10038#issuecomment-1677579586)

|Before remount|After remount|
|-|-|
|![Image](https://github.com/Shopify/polaris/assets/20652326/ce6c32e6-acd0-4184-bd55-5de410db973e)|![Image](https://github.com/Shopify/polaris/assets/20652326/7f64da3a-0e0f-408b-a8df-b4424dc62b40)|

As you can see, the `left` px value is changing/calculating differently

**Comment by sophschneider** [comment]
It looks like the [`activatorRect`](https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/PositionedOverlay/PositionedOverlay.tsx#L265) is the value changing. When I console log the bounding box for the activator when replicating the issue, I get changing `x`, `left`, and `width` values

![Image](https://github.com/Shopify/polaris/assets/20652326/98a66565-f0e2-48a9-83ac-8a08471f324c)

**Comment by sophschneider** [comment]
I've determined this is a font loading issue.

Since the width is being incorrectly calculated, I put a `debugger` after the first bounding box calculation. At that point, the font is smaller than the final render causing a different bounding box calculation

|First bounding box calculation|Correct bounding box calculation|
|-|-|
|![Image](https://github.com/Shopify/polaris/assets/20652326/286d7298-a899-4c85-8633-6669a72ee5a5)|![Image](https://github.com/Shopify/polaris/assets/20652326/ddb488db-3f3a-4376-81df-c8a6371153d6)|


I tried pulling https://github.com/Shopify/polaris/pull/9993 but it didn't fix the issue

**Comment by sophschneider** [comment]
While preloading inter was good for our stories to be in the proper font, the issue was actually that our base branch didn't have the new baselines accepted. I opened a draft PR of [next](https://github.com/Shopify/polaris/pull/10060) then accepted the new snapshots as the baseline
