### ISSUE TITLE
Analysis: 100% of dependency updates in this repository can be merged.

### ISSUE THREAD

**Issue by supalarry** [Shopify/polaris-react-archive#10097]
Hey there :wave:<br><br>Our bot, Adaptly, found that 5 out of 5 currently open dependency update PRs can be merged.<br>That's 100% right there:<details><summary>View Safe to Merge PRs</summary>1. [Bump fastify from 4.5.3 to 4.15.0](https://github.com/Shopify/polaris/pull/8750)<br>2. [Bump webpack from 5.72.0 to 5.76.0](https://github.com/Shopify/polaris/pull/8667)<br>3. [Bump decode-uri-component from 0.2.0 to 0.2.2](https://github.com/Shopify/polaris/pull/7832)<br>4. [Bump deep-object-diff from 1.1.7 to 1.1.9](https://github.com/Shopify/polaris/pull/7734)<br>5. [Bump loader-utils from 1.4.0 to 1.4.2](https://github.com/Shopify/polaris/pull/7725)<br></details><br><img width='370' alt='feels' src='https://i.imgur.com/ceikuMr.png'><h3>:mag_right: &nbsp; How does Adaptly know this?</h3>It analyses changelogs of dependencies updated in a PR.<br>If no breaking changes are found in the changelogs, PR is marked as good to merge.<h3>:sparkles: Try Adaptly yourself</h3>Feel free to [try Adaptly](https://github.com/apps/adaptly-bot) on your repositories and finally<br>merge dependency update PRs. Let us know if you have any questions.<br><br>Best of luck with your projects,<br>Lauris<br>lauris@adaptly.dev

**Comment by supalarry** [comment]
@alex-page Adaptly saw that you have merged dependency update PRs, so this might be useful to you.

**Comment by sam-b-rose** [comment]
Hi @supalarry! Thanks for bumping this. I've merged all the PRs regarding dependency updates referenced in this PR 👍
