### ISSUE TITLE
Docs reference 1.0.2 CSS file now 1.1.1 is out

### ISSUE THREAD

**Issue by buggy** [Shopify/polaris-react-archive#101]
# Issue summary

The docs include the wrong Polaris version of the CSS file.

## Expected behavior

I expect it to use using https://sdks.shopifycdn.com/polaris/1.1.1/polaris.css now that it's released

## Actual behavior

It still says https://sdks.shopifycdn.com/polaris/1.0.2/polaris.css

## Steps to Reproduce the Problem

1. Go to https://polaris.shopify.com/components/get-started
1. Search for https://sdks.shopifycdn.com/polaris/1.0.2/polaris.css

**Comment by lemonmade** [comment]
Thanks Rich, should be fixed now.
