### ISSUE TITLE
[Storybook] Use Inter font in Storybook snapshots

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#10104]
in https://github.com/Shopify/polaris/pull/10102, we changed chromatic snapshots to use system font instead of Inter to avoid async font loading flakiness (see https://github.com/Shopify/polaris/issues/10038 for context).

A preferred method would be to not render the stories until the font is ready as outlined in [Solution B on the chromatic docs](https://www.chromatic.com/docs/resource-loading#solution-b-check-fonts-have-loaded-in-a-loader). However, when implementing this method in this PR (https://github.com/Shopify/polaris/pull/9993), the story still seemed to be rendering the system font first (https://github.com/Shopify/polaris/pull/10089). 

We implemented the [system font workaround](https://github.com/Shopify/polaris/pull/10102) so that we could use storybook to test our consolidation work with non flaky regression tests. But once consolidation work is done, we should try and get solution B working so we can have more accurate snapshot tests

**Comment by alex-page** [comment]
@gwyneplaine @sophschneider @sam-b-rose have we seen any regressions to this yet??? 🤞

**Comment by gwyneplaine** [comment]
@alex-page I've been intermittently browsing PRs for the last couple of days, and have noticed no obvious regressions. 
We would previously have seen snapshot changes that were unrelated to the changes in the PR's in question. 
As far as I can see this has not happened 🤞

**Comment by gwyneplaine** [comment]
I take that back, we can see an example of weird font rendering behaviour in this [snapshot](https://shopify.chromatic.com/test?appId=5d559397bae39100201eedc1&id=65728478e13418eca1352ce1) from this [PR](https://github.com/Shopify/polaris/pull/11295) from @aaronccasanova (tagging you in case I'm wrong and this is expected behaviour)

**Comment by sam-b-rose** [comment]
Looking at the Chromatic builds, I don't see any flakiness with the font. Though, also fine to ship #11308 just to be extra sure.

**Comment by gwyneplaine** [comment]
> Looking at the Chromatic builds, I don't see any flakiness with the font. Though, also fine to ship #11308 just to be extra sure.

Fonts aren't loaded at all before the snapshot happens in this [baseline example](https://shopify.chromatic.com/test?appId=5d559397bae39100201eedc1&id=65728478e13418eca1352ce1) 
![Screenshot 2023-12-11 at 11 45 56 am](https://github.com/Shopify/polaris/assets/12119389/baec0ebd-6bea-43e6-ba86-066a12e8453a)

I think that's a verifiable indication that our previous fix isn't working as intended, but I might be missing something 🤞

**Comment by sam-b-rose** [comment]
> Fonts aren't loaded at all before the snapshot happens

I see. I am so use to seeing most sites use `font-display: swap` I assumed this wasn't font loading related 😓 

Good catch, agreed this looks like we aren't fully loading the font prior snapshot. Let's merge in your PR to see if that addresses the issue 👍

**Comment by lgriffee** [comment]
I think this issue can be closed with the merging of #11347. Please re-open if I am mistaken about this!
