### ISSUE TITLE
[Icon]: Update all filled icons

### ISSUE THREAD

**Issue by zecarlostorre** [Shopify/polaris-react-archive#10109]
### Why are you proposing this update?

Update icon drawings, so they behave consistently.

### Icon name

All filled icons

### What type of icon set?

Major (20x20)

### Icon SVG code

<svg>...</svg>

### Are there any other important details?

![Image](https://github.com/Shopify/polaris/assets/55551051/5f5e0da7-1786-437e-a70c-b850591b0505)

**Comment by elizabethmcguane** [comment]
When we get to this: a note specific to the store activity log icon, from CSS (also a note on localization — @jeffkraemer2 is owning that part)



![Image](https://github.com/Shopify/polaris/assets/40369590/ddcf4562-fa6f-435b-8fbd-453a9c181c45)

**Comment by zecarlostorre** [comment]
Icons have been created, the full list of icons being updated was captured in[ this issue.](https://github.com/orgs/Shopify/projects/2250/views/121?type=beta&filterQuery=label%3AIcon&pane=issue&itemId=43469673)
