### ISSUE TITLE
[Buttons] Make sure button have sufficient click target

### ISSUE THREAD

**Issue by yesenia-perezcruz** [Shopify/polaris-react-archive#10128]
We've received some merchant feedback that the smaller Uplift buttons are harder to click. I think this has less to do with the size and more to do about the space around it, especially Button Group.

![Image](https://github.com/Shopify/polaris/assets/47306956/2f66b6e3-3018-479f-8835-c773600bb193)

Logging this so a designer can have a lot to see if there's any places where Buttons don't have sufficient padding.

**Comment by heyjoethomas** [comment]
Looking at the most common `ButtonGroup` instances in the admin, I see they all have 8px of space between buttons. Not sure adding more space between buttons would really solve much as click target sizes would remain the same.

**Comment by yesenia-perezcruz** [comment]
@heyjoethomas I'm wondering if this feedback was initial change aversion to the buttons getting smaller. I haven't heard it being an issue recently.

**Comment by heyjoethomas** [comment]
> @heyjoethomas I'm wondering if this feedback was initial change aversion to the buttons getting smaller. I haven't heard it being an issue recently.

That is my best guess. The buttons did get a bit smaller for uplift. Basic buttons went from 36px tall -> 28px tall. So my guess is that just threw people off.

**Comment by yurm04** [comment]
Want to make sure before i close: is there any action to be taken to address this issue?

**Comment by heyjoethomas** [comment]
I don't think so no. The buttons were obviously designed intentionally and
the spacing between buttons around the admin is consistent. I think this is
just reaction from the design change.
