### ISSUE TITLE
`IndexFilter` Filter pills popover won't close when clicking on another portal

### ISSUE THREAD

**Issue by sam-b-rose** [Shopify/polaris-react-archive#10155]
## Issue

The IndexTable filter pills popover doesn't close when click outside on the Settings dialog or on another filter.

Related to [this line of code](https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx#L273).

**Comment by sam-b-rose** [comment]
Closed by https://github.com/Shopify/web/pull/101994

**Comment by adventuretocode** [comment]
@samrose3  I am using the polaris with react but  index filter with index table search feature is not working.
