### ISSUE TITLE
Create a <Card> component that can be used in a `.md` file

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#10150]
Create a primitive JSX Card component to be used across the site and for markdown content like in this figma example [`Voice and Tone` ](https://www.figma.com/file/vO0wToyBpYjeIwr8doAAWT/Uplift-polaris.shopify.com?type=design&node-id=37%3A25215&mode=design&t=Z6KugRKI8PLcmyHr-1)

If it were possible it'd be ideal to use the polaris-react `Card`, but we're not able to support dark mode for that card. We should build a similar lightweight card component that's able to wrap any sort of children

![Image](https://github.com/Shopify/polaris/assets/4642404/3a88f527-ad58-4e20-a3a1-0254db34c24e)

#### [Background card](https://www.figma.com/file/vO0wToyBpYjeIwr8doAAWT/Uplift-polaris.shopify.com?type=design&node-id=50%3A24886&mode=design&t=kQj4os2WflWtJs5B-1)

![Image](https://github.com/Shopify/polaris/assets/4642404/28b46a7f-801a-4cbc-806c-b059d7d1f8a3)

#### [Media card (vertical and horizontal)](https://www.figma.com/file/vO0wToyBpYjeIwr8doAAWT/Uplift-polaris.shopify.com?type=design&node-id=50%3A4050&mode=design&t=kQj4os2WflWtJs5B-1)

![Image](https://github.com/Shopify/polaris/assets/4642404/dd7e1f6b-7eb9-44bd-aae8-1c0647211adc)

#### [Do / Dont card](https://www.figma.com/file/vO0wToyBpYjeIwr8doAAWT/Uplift-polaris.shopify.com?type=design&node-id=53%3A27059&mode=design&t=kQj4os2WflWtJs5B-1)

![Image](https://github.com/Shopify/polaris/assets/4642404/81d6c1a7-d21c-4ae0-833f-41978b6729d6)

```

**Comment by yurm04** [comment]
@tjonx for the card backgrounds do y’all have an idea of darkmode ?

![Image](https://github.com/Shopify/polaris/assets/4642404/4017cb1c-4342-4023-b792-644a8ae5892b)

If we want to use these cards we probably wont be able to use the polaris-react card since it does not have darkmode

**Comment by gwyneplaine** [comment]
@yurm04 @jesstelford  given the above screenshots, we'll also need a `Bleed` comopnent in polaris.shopify.com 
I'll create a separate issue for this, and submit a separate PR 👍
