### ISSUE TITLE
Is the TextField component suitable for entities with too many fields?

### ISSUE THREAD

**Issue by Zardw** [Shopify/polaris-react-archive#10179]
I found out that it uses TextField component to replace input element, and it has a value and function of change to save value, If a entity has many fields, like screenshot, so would it need a lot of values and functions to keep them? Will it be too complicated compared to html? :(
![image](https://github.com/Shopify/polaris/assets/117419340/3b5b9950-c842-4a7b-98f0-1b7acdbeb125)
![image](https://github.com/Shopify/polaris/assets/117419340/546d485b-8830-4ba4-bfc3-4aa231cb5705)

**Comment by Zardw** [comment]
Someone can reply?

**Comment by bytecode1024** [comment]
I will try something like this:


      const [widget, setWidget] = useState({
        id: "",
        name: ""
        // ... other key/value entries
      });
      
      const updateWidget = (key, value) => setWidget({
        ...widget,
        [key]: value
      });
      
      const handleChange = (key) => (newValue) => {
        updateWidget(key, newValue);
      };
      
      return {
        for (let key in widget) {
          <TextField
            label={key}
            value={widget[key]}
            onChange={handleChange(key)}
            autoComplete="off"
          />
        }
      };

**Comment by Zardw** [comment]
@bytecode1024 thanks, it gives me a new thought, but if TextField is different input elements, like number, email, date, select..
how to output these elements ?

**Comment by bytecode1024** [comment]
I will change my point of view.

I will perhaps use an entry object for each widget key and use a component for the entries list and a component for the entry:

    entry object = {
	    key: "id",
	    label: "Id",
	    type: "text",
	    value: "",
	    // other attributes
    };

Entry component in a file:

    // ... some imports
    export function Entry({entry, onChange}) {
	    function handleChange() {
		    if (onChange) {
			    onChange(entry);
		    }
	    }
    
	    return (
		    <TextField
			    label={entry.label}
			    value={entry.value}
			    type={entry.type}
			    onChange={handleChange}
			    autoComplete="off"
		    />		
	    );
    }

List entries component in another file:

    // ... some imports
    export function EntriesList({entries}) {
	    function handleChange(entry) {
		    setEntries((prevEntries) => prenvEntries.map((item) => item.key !== entry.key ? item : {...item, value: entry.value}));
	    }
    
	    return (
		    {entries.map((entry) => <Entry key={entry.key} entry={entry} onChange={handleChange}/>}
	    );
    }


In another component:

    ...
    const [entries, setEntries] = useState([]);
    ...
     <EntriesList entries={entries}/>
    ...

And somewhere the initialization of the entries array.

Hope it helps...
