### ISSUE TITLE
[Styles] Consolidate se23 styles in `polaris-react/src/styles`

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#10193]
in `_common.scss` we can remove `$se23ShadowBevelOptOut` but not `$se23` since a lot of our consuming repos still use the classname and we don't want to affect their styles.

We should also add a comment above the `$se23` definition telling consumers to not use and the date that it will be officially deprecated. Lets also add a calendar event or something for the day we will deprecate, and create clean up comms to consumer on the date they should finish their cleanup by

Sources:
* se23 class name used in many consuming repos internally: https://grokt.shopify.io/results?q=Polaris-Summer-Editions-2023
* shadow bevel class name only in polaris: https://grokt.shopify.io/results?q=Polaris-SE23-Shadow-Bevel-Opt-Out

Tasks:
- [x] remove `$se23ShadowBevelOptOut`
- [x] keep `$se23`
- [x] determine deprecation date for `$se23`
- [x] add comment above `$se23` definition with warning not to use and deprecation date
- [ ] add deprecation date in our calendar

**Comment by laurkim** [comment]
Blocked by #10189.

**Comment by sophschneider** [comment]
Added an issue description for keeping the se23 classname for v12
