### ISSUE TITLE
[Utilities] Consolidate se23 logic and styles

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#10192]
See for [this issue ](https://github.com/Shopify/polaris/issues/10193) context, we need to keep the `classNamePolarisSummerEditions2023`, remove `classNamePolarisSummerEditions2023ShadowBevelOptOut`

```[tasklist]
### Tasks
- [x] `polaris-react/src/utilities/features/context.ts`
```

**Comment by laurkim** [comment]
Blocked by #10189.
