### ISSUE TITLE
Border on Empty State

### ISSUE THREAD

**Issue by alexdover** [Shopify/polaris-react-archive#102]
# Issue summary

I have just updated polaris and there now appears to be a thin border on the top of the empty state component. This seems to be new and I'm not sure it required?

## Expected behavior

No border on the top of empty state

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Polaris version: 1.1.1
- React version:
- Browser:
- Device:
- Operating System:

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by lemonmade** [comment]
Hey @alexdover, sorry, this was something that slipped in to the current version that we meant to take out. Will be gone as of the next release.

**Comment by dfmcphee** [comment]
This has been resolved.
