### ISSUE TITLE
[Navigation] First item is cut off in xs screen sizes

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#10218]
First item is cut off as seen by the focus ring. I also think the arrow is also cut off

![Image](https://github.com/Shopify/polaris/assets/20652326/75dabab3-20d7-426d-9553-23d08200f950)

**Comment by sophschneider** [comment]
I was able to replicate this in storybook for xs and sm screen sizes

![Image](https://github.com/Shopify/polaris/assets/20652326/b500adf7-6fc6-4b68-96d7-c4902ee36ddc)

**Comment by lgriffee** [comment]
Shipped with v12.7.0 release
