### ISSUE TITLE
`postcss-calc` build error using polaris > v11.4 and ubuntu 22.04

### ISSUE THREAD

**Issue by freemer** [Shopify/polaris-react-archive#10223]
## Issue summary

Unable to build in ubnuntu 22.04 with `react-scripts` and > polaris  v11.4

## Expected behavior

Able to build successfully 

## Actual behavior

Attempting to build in `ubuntu-latest` (22.04) in github actions results in the follow error:
```
Failed to compile.

static/css/main.ffd9159c.css from Css Minimizer plugin
postcss-calc:: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: auto + var(--pc-choice-space-0) + var(--pc-choice-space-0)
^..^ webpack://./node_modules/@shopify/polaris/build/esm/styles.css:1687:2591
```

Works fine locally on MacOS.

**Comment by ascherkus** [comment]
FYI I'm also still seeing this on both my local mac development environment as well as our debian linux CI builder, so doubtful it's OS specific.

Here's what my mac and our linux CI runner use:
```
node v16.18.0
@shopify/polaris 12.10.0
postcss 8.4.4
postcss-calc 8.2.4
postcss-flexbugs-fixes 5.0.2
postcss-loader 6.2.1
postcss-normalize 10.0.1
postcss-preset-env 7.0.1
```

I've tried fiddling with different, newer verisons of postcss but I'm still seeing it.

**Comment by ascherkus** [comment]
I poked around a bit more and for context I'm using an ejected create-react-app, which uses postcss-preset-env

I was able to fix the warning by upgrading postcss-preset-env from 7.0.1 to the latest version 9.3.0

**Comment by dgoemans** [comment]
Same issue here, manually adding the _postcss-preset-env_ package in my _package.json_ (version 9.5.2) fixed this. Note that on Windows, i see them as warnings but when building on CI (Linux), there's a notice that they will be treated as errors. So not OS specific, but only fails in CI for me because of the CI detection.
