### ISSUE TITLE
Feature Request: helpText for ChoiceList component

### ISSUE THREAD

**Issue by cgenevier** [Shopify/polaris-react-archive#103]
# Issue summary

Radio buttons and checkboxes both allow for a "helpText" attribute but the ChoiceList component doesn't allow you to specify helpText for the choices. 

## Expected behavior

ChoiceList should allow you to specify helpText for each of your choices, in this fashion:

```
<ChoiceList
  title="Company name"
  choices={[
    {
      label: 'Hidden',
      value: 'hidden',
      helpText: 'This is the hidden option'
    },
    {
      label: 'Optional',
      value: 'optional',
      helpText: 'This is the optional option'
    },
    {
      label: 'Required',
      value: 'required',
      helpText: 'This is the required option'
    },
  ]}
  selected={['hidden']}
/>

## Specifications

- Polaris version: 1.0.3
- React version: 15.5.4
- Browser: All
- Device: All
- Operating System: All

**Comment by lemonmade** [comment]
Thanks for the issue, @cgenevier. I've added this to our internal project board for discussion. Do you have a more realistic example/ use case that prompted this issue? Do you think `helpText` on each choice is needed, or would `helpText` on `ChoiceList` as a whole be enough?

**Comment by cgenevier** [comment]
Yes, I'm reworking an app I built to use Polaris and I need helpText on
each of the radio buttons vs on the ChoiceList itself.

One of the settings it applies to is a "Display Type" option setting. There
are 3 options (ex: "Custom page", "Post-purchase", etc) and they need a
sentence or so of additional explanation beneath each to help the store
owner understand which will best suite their needs.

In the meantime, I've solved it by just using 3 RadioButtons with some text
above them for a title, but it definitely seems like the ChoiceList would
be the optimal option.

Thanks!


On Jun 21, 2017 2:19 PM, "Chris Sauvé" <notifications@github.com> wrote:

Thanks for the issue, @cgenevier <https://github.com/cgenevier>. I've added
this to our internal project board for discussion. Do you have a more
realistic example/ use case that prompted this issue? Do you think helpText
on each choice is needed, or would helpText on ChoiceList as a whole be
enough?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Shopify/polaris/issues/103#issuecomment-310163205>, or mute
the thread
