### ISSUE TITLE
IndexFilter "cancel", "save as" and "clear all" buttons not showing

### ISSUE THREAD

**Issue by mcabrejos24** [Shopify/polaris-react-archive#10383]
## Issue summary

IndexFilter cancel and clear all buttons now showing.

## Expected behavior

The buttons should show "cancel", "clear all" and "save as"

## Actual behavior

The buttons are there but they don't show "cancel" when opening the filters or "clear all" when applying filters.

Same thing with saving views. The "Save as" button is there when the logic is added to save views but the button is empty with a blue background. No title is shown and there is no way to add thee titles for this either.

![Screen Shot 2023-09-08 at 1 39 28 PM](https://github.com/Shopify/polaris/assets/25379372/38a8fa57-b1b4-41f4-a2e8-d66137362f5f)

## Steps to reproduce the problem

1. Add the IndexFilters component to an IndexTable.
2. add cancelAction logic to the IndexFilters component
3. open the filters and you will see no "cancel" button appears to the right of the search bar
4. hover over where it should be and you will see that it actually is there but the content doesn't show "cancel"
5. add filters and you will see no "clear all" button appears to the right
6. add primaryAction functionality
7. a blue button appears to the right of where the "cancel" button should be but doesn't say "save as" or "save"

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: ^11.16.0
- Browser: Google Chrome and Brave
- Device: 2016 Mac Book Pro
- Operating System: macOS Monterey version 12.5.1

**Comment by briancsinger** [comment]
+1

**Comment by subburaja** [comment]
I am facing same problem, checked everything else to be right. Any answers?

**Comment by remy727** [comment]
Same issue. Any update on this?

**Comment by remy727** [comment]
I am having the same issue.
Here is the package versions:
```json
{
    "@shopify/polaris": "^12.6.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
}
```

**Comment by gwyneplaine** [comment]
@remy727  @mcabrejos24 I'm unable to replicate this issue in the latest version of Polaris `v12.11.1` nor in `v12.6.0` as specified in @remy727's post above

Here's a [minimal sandbox reproduction](https://codesandbox.io/p/sandbox/shopify-polaris-react-typescript-playground-forked-lh45tn?file=%2Fsrc%2Findex.tsx%3A143%2C32) of the case according to the steps outlined in the original post using `@shopify/polaris v12.6.0` 

Please: 
1. Verify if this is still happening for you in either `12.6.0` or `12.11.1`
2. Provide a reproduction in codesandbox (using the linked sandbox above as a base if you'd like)

**Comment by lgriffee** [comment]
Going to close this issue. Feel free to re-open and respond with the information requested above if the issue persists.

**Comment by yash-gupta-9098** [comment]
Hello everyone,  

https://codesandbox.io/p/sandbox/filter-7vzxhr?file=%2Fsrc%2FApp.tsx

I got the same issue,  can you  please suggest me any solution for this?   
I have attached  "Code sand box" URL for better understanding. 

"dependencies": {
    "loader-utils": "3.2.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-scripts": "5.0.1",
    "react-redux": "9.1.0",
    "@shopify/polaris": "12.22.1",
    "@shopify/polaris-icons": "8.8.0"
  }

**Comment by squadkin** [comment]
Still happning this issue and here are the versions I'm using:

"@shopify/polaris": "^12.27.0",
"@shopify/polaris-icons": "^7.13.0",
"@shopify/polaris-viz": "^10.3.2",
"react-i18next": "^14.0.0",
"react-player": "^2.15.1",
"react-quill": "^2.0.0",
"react-router-dom": "^6.21.1",
"react-table": "^7.8.0",

**Comment by paul-barilla-1** [comment]
This is still happening to me as well

**Comment by borisflesch** [comment]
Hi, reviving this quite old issue as many of us faced the same problem.

On my end, I've been able to resolve it by ensuring that Polaris' locales are correctly loaded in my project.

In my `PolarisProvider.jsx` file (where the Polaris Provider gets loaded), I added the following import, and ensured it is used in the Provider component:
```js
import enTranslations from '@shopify/polaris/locales/en.json';

// ...

<AppProvider i18n={enTranslations}>
      {children}
</AppProvider>
```

Source: https://www.npmjs.com/package/@shopify/polaris#usage
