### ISSUE TITLE
Banners not rounding off on the top (Polaris 12 beta)

### ISSUE THREAD

**Issue by macwilko** [Shopify/polaris-react-archive#10426]
I've noticed some banners don't seem to apply the border radius correctly on the top part (see the yellow warning banner).

If I change the route, it seems to work, but initial load seems to not work.

For context I'm using Remix template.

<img width="2416" alt="image" src="https://github.com/Shopify/polaris/assets/19474610/72709374-7b01-448f-ba7a-5774e8168b81">

**Comment by macwilko** [comment]
Ok so I believe this isn't an issue per-say with Polaris 12 beta, but a combination of Polaris 11 styles briefly being applied before loading 12 styles (I raised an issue here #10468 about this).

I believe a consequence of this is banners are displaying incorrectly.

I managed to snap shot the load, and you can see:

<img width="2192" alt="Xnapper-2023-09-14-11 31 58" src="https://github.com/Shopify/polaris/assets/19474610/27663204-c129-459c-8f99-083e9867b853">

I believe the banner might have some ::before or ::after styling, which is being carried over, causing the visual problem.

I have the Polaris 12 package:

<img width="1152" alt="Xnapper-2023-09-14-11 35 38" src="https://github.com/Shopify/polaris/assets/19474610/146f5bef-8e9e-4278-a74d-30fe20812f52">

**Comment by BaggioGiacomo** [comment]
Same problem here!

**Desktop version:**
<img width="1440" alt="image" src="https://github.com/Shopify/polaris/assets/58849430/fa264c46-377f-40ad-b318-62081eb9b4bb">

**Mobile version:**
<img width="377" alt="image" src="https://github.com/Shopify/polaris/assets/58849430/24f38f67-a69c-4824-9c0e-0dfe119c4f88">

**Comment by macwilko** [comment]
@BaggioGiacomo nice work on that pricing page, looks good!
