### ISSUE TITLE
Global nav status badge designs

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#10457]
The nav menu support status badges next to nav items. We need designs for what those badges should look like in the updated nav menu.

If possible, let's pull in the polaris-react `Badge` component. If that becomes cumbersome or doesn't fit well, build a lighter weight version with similar styling. A lightweight version of `Badge` only needs to be a pill with text in it (no icon)

[Current styles for the badges can be found here](https://github.com/Shopify/polaris/blob/next/polaris.shopify.com/src/components/StatusBadge/StatusBadge.module.scss)

<img width="321" alt="Screenshot 2023-09-13 at 4 04 55 PM" src="https://github.com/Shopify/polaris/assets/4642404/208ee48a-8464-4023-ae2a-334232618db6">

<img width="297" alt="Screenshot 2023-09-13 at 4 04 47 PM" src="https://github.com/Shopify/polaris/assets/4642404/0d78ebce-f4b1-45e0-a814-6019cf4f49a4">

**Comment by laurkim** [comment]
Chatted with @yurm04 and given the timeline and the need to also support dark mode, I'm going to revert #10562
