### ISSUE TITLE
[polaris.shopify.com] `What's new` page layout

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#10459]
[New layout for the `/whats-new` page](https://www.figma.com/file/vO0wToyBpYjeIwr8doAAWT/Uplift-polaris.shopify.com?type=design&node-id=52%3A25228&mode=design&t=kQj4os2WflWtJs5B-1)

File can be found in `/content/whats-new/index.md`

Posts populated from the `/content/whats-new/` directory. 

[Rendered by the `pages/[...slug].tsx` `catchAllTemplate`](https://github.com/Shopify/polaris/blob/next/polaris.shopify.com/pages/%5B...slug%5D.tsx#L86)

![Image](https://github.com/Shopify/polaris/assets/4642404/8eaf10a8-d1f7-44f9-89d9-afd03535e29e)

**Comment by yurm04** [comment]
@zecarlostorre @tjonx we don't currently have author, date, or read time data. We can add this as frontmatter data, but we will have to add them manually to all existing posts and new posts going forward

**Comment by yurm04** [comment]
to get the top featured card, add a `featured: true` to the frontmatter of whatever article .md file you want to be featured

**Comment by tjonx** [comment]
> @zecarlostorre @tjonx we don't currently have author, date, or read time data. We can add this as frontmatter data, but we will have to add them manually to all existing posts and new posts going forward

We won't need them. We'll have to update the Figma mocks for those. Also, date isn't necessary, it's not super useful and it might even show we don't post often.
