### ISSUE TITLE
Polaris 11 styles briefly flashing before loading Polaris 12

### ISSUE THREAD

**Issue by macwilko** [Shopify/polaris-react-archive#10468]
Dear Shopify team,

I have a small issue (I assume because I'm using Polaris 12 beta).

I noticed some jank caused by Polaris 11 styles briefly loading before switching over to 12.

Is there something specific I need to do to load only the 12 styles and never see the 11 styles flash?

**Comment by nullndr** [comment]
Same here, kinda annoying
