### ISSUE TITLE
Update `Table of Contents` component styling

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#10463]
[Figma](https://www.figma.com/file/vO0wToyBpYjeIwr8doAAWT/Uplift-polaris.shopify.com?type=design&node-id=53%3A2996&mode=design&t=kQj4os2WflWtJs5B-1)

All functionality/behaviour should remain the same for the Table of Contents component.

Styling updates
- [x] Container around the TOC
- [x] Active state for the current location

![Image](https://github.com/Shopify/polaris/assets/4642404/40a5eb70-dbc5-42bc-8450-b5292fd0691b)
![Image](https://github.com/Shopify/polaris/assets/4642404/e60b740d-2221-4cde-8bc8-531ece0bd670)

**Comment by yurm04** [comment]
There is an existing bug/edge case/weirdness on prod in the TOC component. 

The TOC does not have its own scroll container. For very long pages, the TOC does not scroll to follow the actual page position. It also get cut off at the bottom of the page. Is there a way we can gracefully handle these scenarios?

https://github.com/Shopify/polaris/assets/4642404/6f1d978c-1b65-4f9e-afa3-f4e11cb76c19

**Comment by laurkim** [comment]
> There is an existing bug/edge case/weirdness on prod in the TOC component.
> 
> The TOC does not have its own scroll container. For very long pages, the TOC does not scroll to follow the actual page position. It also get cut off at the bottom of the page. Is there a way we can gracefully handle these scenarios?

Chatted with @yurm04 about this offline and the explored solutions to this ended up not providing much of a visual improvement so we are tabling that for now and hoping with refactoring of page content, TOC content being cut off for pages with a large number of sections/subsections will not be an issue.
