### ISSUE TITLE
[UI KIT] Add link variant to Select

### ISSUE THREAD

**Issue by heyjoethomas** [Shopify/polaris-react-archive#10470]
Add secondary link to Select like we have for Text Input

![Image](https://github.com/Shopify/polaris/assets/5749440/e4d4cc74-dea5-4c32-ba6a-fbc8cfcf6f92)

**Comment by Eianaftyio** [comment]
--p-color-bg-surface-magic-active

**Comment by heyjoethomas** [comment]
keep open
