### ISSUE TITLE
Modal now generates React warning using a function component as activator

### ISSUE THREAD

**Issue by gavin-hinchley** [Shopify/polaris-react-archive#10493]
## Issue summary

Attempting to use functional components as an `activator` for `Modal` with Polaris` 11.13.0+ `results in
`Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?` 

Appears to have been introduced with https://github.com/Shopify/polaris/pull/10086
Could be related to https://github.com/Shopify/polaris/issues/10337

## Expected behavior

Functional components should continue to work without React errors or warnings.

## Actual behavior

`Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`
![image](https://github.com/Shopify/polaris/assets/91741879/0990378b-064c-4546-84b9-5e2644c82700)

## Steps to reproduce the problem

1. Copy the `Default` [ModalExample](https://polaris.shopify.com/components/overlays/modal) from the Modal Polaris documentation.
1. Attempt to use the ModalExample in a unit test or browser.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: `11.19.0 `
- Browser: Chrome  116.0.5845.140
- Device: Mac
- Operating System: MacOS

**Comment by Roguehp98** [comment]
I believe this error still persists. It can be demonstrated by using the example from [docs](https://polaris.shopify.com/components/overlays/modal?example=modal-with-primary-and-secondary-actions)
