### ISSUE TITLE
Using react node as type for `badge` property in `Tab` component.

### ISSUE THREAD

**Issue by Baoyuan-Xing** [Shopify/polaris-react-archive#10497]
## Feature request summary

Using react node as type for `badge` property in Tab component.

Currently `badge` property is strictly with string type in Tab component, which limits its capacity of display meaningful information of the tab, eg: status, or logo or icons of the content inside of the tabs.  
Another property `icon` can display in place of a view name but it would remove the tab name, instead of appending to it.

We are proposing to support react node as type for badge component. it could be used in multiple use cases listed below 

## Rationale

More flexible type for badge can make the tab more clear and functional. We have following use cases as examples: 

Use cases:

1. platform tabs with status badge
2. platform tabs with its logo

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s :+1: upvotes to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by pt8o** [comment]
I would extend this to `<Badge>` as a component in general. Recently worked on [a feature on `web`](https://github.com/Shopify/web/pull/103668) where we wanted to show a loading spinner in the badge while the contents were being fetched but were unable to, so we're now just using "..." as a raw string.
