### ISSUE TITLE
[ButtonGroup segmented] Shadow/border regression

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#10587]
I noticed in the [storybook regression tests](https://shopify.chromatic.com/test?appId=5d559397bae39100201eedc1&id=6509f95d4f3050672c787a41) that pressed segmented buttons no longer have a dark right side border from this change.

This change came from `main` so it should be fixed in `main` then rebased to `next`

|Before|After|
|-|-|
|<img width="223" alt="Screenshot 2023-09-19 at 3 44 45 PM" src="https://github.com/Shopify/polaris/assets/20652326/78b51661-0b77-4121-a28c-8e4c4ac71f88">|<img width="224" alt="Screenshot 2023-09-19 at 3 44 58 PM" src="https://github.com/Shopify/polaris/assets/20652326/a8bad7ae-7534-41a0-9e71-394e1d644b5b">|

**Comment by aveline** [comment]
Explored some solutions and determined that a proper solution is more involved. Will need to reprioritize after v12.

**Comment by lgriffee** [comment]
Re-opening this issue until 

- https://github.com/Shopify/polaris/pull/11351 

is shipped to prod.
