### ISSUE TITLE
Remove `copy` button from `DoDont` header

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#10591]
The `DoDont` component has a `copy` button in the header that should not be there. I think the `copy` buttons are being added by the mdx renderer, not within the `DoDont` component itself

![Image](https://github.com/Shopify/polaris/assets/4642404/45c87ee5-775c-4d62-b569-0bce3272f790)

![Image](https://github.com/Shopify/polaris/assets/4642404/339fcc9c-28e6-4d23-b59a-f92d5305a678)

**Comment by gwyneplaine** [comment]
@yurm04  finding it hard to replicate this locally on the latest from `main`, has this been resolved? 
If not, what page can I see this occurring on?

**Comment by yurm04** [comment]
@gwyneplaine This looks to be resolved! i think i made this issue before the new `DirectiveCard` was introduced which automatically adds in the `Do`/`Dont` title as a `p` instead of an `h3`. 

Thanks for looking into this 🙏 going to close this
