### ISSUE TITLE
Hard navigate to `/components/*` pages results in hydration error

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#10629]
A hard navigate or hard refresh to any `/components` page gives you a hydration error. Not sure when this broke. Usually I've seen these errors as a result of markdown issues with html vs. mdx in the markdow, html/react tags that are nested incorrectly, etc., but the error is not super helpful

https://github.com/Shopify/polaris/assets/4642404/ee2b2368-f9fb-4ea0-9531-7db0e8fe79ac

**Comment by kyledurand** [comment]
I've been seeing this for a while now. I think it happens both on main and next branches

**Comment by kyledurand** [comment]
I spent a chunk of time Friday looking into this and it's very difficult to reproduce. Seems like the issue is stemming from nested paragraphs but couldn't find the source. You might be on to something with Lede / frontmatter changes though

**Comment by laurkim** [comment]
Was able to reproduce a couple of the hydration errors locally by:
- navigating to `/components/actions/button` page which triggers an error from the deprecated `connectedDisclosure` with warning StatusBadge on props table
- navigating to `/components/deprecated/legacy-card` page and then navigating to `/components/layout-and-structure/card` from link in StatusBanner which triggers an error from nested paragraph elements in `<Lede>` component

Closing this issue as [#10644](https://github.com/Shopify/polaris/pull/10644) resolved hydration errors and after we dug into potential accessibility issues, @yurm04 opened #10645 as a follow up 👍
