### ISSUE TITLE
`/sandbox` `FrameContext` error

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#10628]
This may be the same issue as https://github.com/Shopify/polaris/issues/10400 but this is a different error so I wasn't sure. 

![Image](https://github.com/Shopify/polaris/assets/4642404/c9014559-4c03-45df-aaf5-56eb0d0ff72e)

Possibly related: the `/sandbox` has the same error

![Image](https://github.com/Shopify/polaris/assets/4642404/14721136-9c4a-4603-ad9a-2c1948af577d)

**Comment by kyledurand** [comment]
@yurm04 can you try pulling the latest from the next branch and test this again? I can't reproduce on http://localhost:3000/patterns/app-settings-layout

![image](https://screenshot.click/22-06-ea479-mse2r.png)

**Comment by yurm04** [comment]
@kyledurand looks like this was resolved! thanks for looking into it 🙏

**Comment by yurm04** [comment]
Sorry, reopening this as the `/sandbox` error is still there. @kyledurand are you able to reproduce this in the sandbox with the lastest on `next`?



![Image](https://github.com/Shopify/polaris/assets/4642404/12a62d14-b4e7-4075-87db-11f52e5eea30)

**Comment by gwyneplaine** [comment]
@yurm04 can't seem to replicate the issue on latest `next` with a fresh build and cleared `.cache` and `.next` folder 

Can you see if you can replicate the issue after running a fresh `yarn build`, and deleting `.cache` and `.next` folders

![Image](https://github.com/Shopify/polaris/assets/12119389/8abe5173-ce0c-41ec-8320-8fa969d33b41)

**Comment by yurm04** [comment]
@gwyneplaine after running the build and getting the latest from next I'm not seeing this error anymore 🙏 sorry I didn't think to build again, and thank you for digging into this!
