### ISSUE TITLE
[Markdown] transfer Card layout pages

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#10697]
[Doc](https://docs.google.com/document/d/13LrzMI5SMzDZ3Wm117Yz4olE7PzBCFQh2_B5C07WQlE/edit#heading=h.gfe7lmbx5ooo)

**Comment by johanstromqvist** [comment]
This content is incomplete, so please hold off transfer until I've signalled in this issue. Any pattern guidelines are lower priority than the foundations and token usage guidelines, so please aim to transfer those first.

**Comment by alex-page** [comment]
Is this still happening? the vault project is done but this issue is still open.

**Comment by johanstromqvist** [comment]
Yes, on it. EOD unless I run into something unforeseen.

**Comment by johanstromqvist** [comment]
2 hours of troubleshooting dev environment. Will try again tomorrow after my issues hopefully been resolved.

**Comment by johanstromqvist** [comment]
Deferred slightly again due to other projects. I _could_ ask someone else to finish the task, but I'd prefer to go through the contribution flow myself.

**Comment by johanstromqvist** [comment]
Handing this over to @sam-b-rose! Thanks tons, Sam! <4

Resources
1. All content + alt texts: [google doc](https://docs.google.com/document/d/13LrzMI5SMzDZ3Wm117Yz4olE7PzBCFQh2_B5C07WQlE/edit#heading=h.gfe7lmbx5ooo)
2. Image assets: [google drive](https://drive.google.com/drive/folders/1SswpPz422EGwGux49J_sTeijQOdRLdYK)
3. Preview of layout: [Figma](https://www.figma.com/file/vO0wToyBpYjeIwr8doAAWT/Uplift-polaris.shopify.com?type=design&node-id=1831%3A163508&mode=design&t=OuBeCGTEMEAEJW9h-1)
