### ISSUE TITLE
[Markdown] transfer Depth pages

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#10695]
[Doc](https://docs.google.com/document/d/13LrzMI5SMzDZ3Wm117Yz4olE7PzBCFQh2_B5C07WQlE/edit#heading=h.oszf9ugznmfr)

**Comment by gwyneplaine** [comment]
@tjonx  @zecarlostorre  @yurm04  scaffolded out based the `Depth` pages based on doc, waiting on assets to complete the PR

**Comment by zecarlostorre** [comment]
Thanks @gwyneplaine!

I just put all the assets in [here](https://drive.google.com/drive/folders/1hePP-bxDzjHlgdvhBV9nF3cu88wCQ_kf?usp=drive_link)

[Here's a visual mock of the pages](https://www.figma.com/file/vO0wToyBpYjeIwr8doAAWT/Uplift-polaris.shopify.com?type=design&node-id=872-21918&mode=design), in case that's helpful.

Hit me up if you have any troubles.

**Comment by gwyneplaine** [comment]
@zecarlostorre  `depth-overview-3`, `depth-overview-4`, `depth-overview-9`, `depth-overview-10` and `depth-creating-4` were all exported with rounded corners, can I get these re-exported with straight edges please? I don't have Figma edit access so this is not something I can do unfortunately 🙏

**Comment by zecarlostorre** [comment]
@gwyneplaine apologies for messing that up 😓
I just updated the assets in the [google drive folder](https://drive.google.com/drive/folders/1hePP-bxDzjHlgdvhBV9nF3cu88wCQ_kf).

**Comment by gwyneplaine** [comment]
No stress, thanks @zecarlostorre  🙏 
#10706 is now merged in. 

#10830 is waiting on shadow-token assets to be finalised. Once those are ready I can move forward with that work 🙏
