### ISSUE TITLE
[Markdown] transfer Motion pages

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#10696]
[Doc](https://docs.google.com/document/d/13LrzMI5SMzDZ3Wm117Yz4olE7PzBCFQh2_B5C07WQlE/edit#heading=h.c2a853pqa0bx)

**Comment by zecarlostorre** [comment]
I'm almost done with this. I still have some animation to make, but if anywant wants to take a stab at scafolding this page with place holders.

The animations I have so far are in [here.](https://drive.google.com/drive/folders/1t1L5yaAsuOaC9C1QsGL4OHhsfCeFHsgb)
