### ISSUE TITLE
[Markdown] Transfer Design Principles

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#10691]
Edit: Content has been modified for the `Design principles` page.

New name for the page (title and nav): `Pro design language`

Updated content is in this section of the [Google Doc](https://docs.google.com/document/d/13LrzMI5SMzDZ3Wm117Yz4olE7PzBCFQh2_B5C07WQlE/edit)

[Figma mockup](https://www.figma.com/file/vO0wToyBpYjeIwr8doAAWT/Uplift-polaris.shopify.com?type=design&node-id=529-3880&mode=design&t=BdL7gcZ4aUm8GDZq-4) has been updated.

Images and videos have also been updated: [Google drive
](https://drive.google.com/drive/folders/1zWYVuV3FnbNNtJeQSHxwZRWzGKl9wu3k)

**Comment by sam-b-rose** [comment]
@tjonx @yurm04 is good to move to done? ✅

**Comment by tjonx** [comment]
> @tjonx @yurm04 is good to move to done? ✅

The content has changed, so I updated the initial issue with the new structure/content
