### ISSUE TITLE
[DatePicker] Fix timezone issue when selecting date on Date Picker pattern

### ISSUE THREAD

**Issue by sam-b-rose** [Shopify/polaris-react-archive#10769]
The DatePicker example in the [Polaris doc](https://polaris.shopify.com/patterns/date-picking/single-date) gives the date prior to the one selected. 

The Shopify Polaris code example has a timezone bug that currently appears for the UK (GMT+1/BST).

See video.

The error with this Shopify example cannot be seen in the US or Canada as these are UTC- timezones. This timezone bug shows up for UTC+ locales like the UK and Europe.

The date picker sets the date at midnight in the local timezone, so for me that's midnight BST (GMT+1), the equivalent of UTC+1.
The code then converts the date to UTC with selectedDate.toISOString() which will end up as maybe 4am that same day for GMT- timezones and appear fine.

However, for those of us in the UK, midnight BST is currently 11pm UTC (the previous day) when converted, so the date becomes one day earlier.

https://github.com/Shopify/polaris/assets/11774595/fb918bc6-ed58-4b3f-b1c2-a804a478856d

**Comment by khanakia** [comment]
@sam-b-rose were you able to solve the issue ?
