### ISSUE TITLE
Grid component is deprecated & in Alpha at the same time according to the documentation

### ISSUE THREAD

**Issue by emilisense** [Shopify/polaris-react-archive#10783]
## Issue summary

Hi everyone,

According to the documentation, the Grid component is in the Alpha stage as stated here: https://polaris.shopify.com/components/layout-and-structure/grid

At the same time, when you use the component, this message shows in the console:
`Deprecation: <Grid /> is deprecated. This component will be removed in a future major version of Polaris. Use <Columns /> instead or a combination of <Columns />, <Inline />, and <AlphaStack />`

The component that is advised to be used ( `<Columns />` ) does not exist according to the documentation.

What is the exact case here? Is the component deprecated or it is still in Alpha after all? Should I be concerned regarding the message shown in the console? 
## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 10.35.0
- Browser: Google Chrome 117.0.5938.92
- Device: Macbook Pro
- Operating System: Sonoma 14

**Comment by kyledurand** [comment]
It was only deprecated for a few minor versions I think. We thought we could get away with just using the columns component but ended up removing the deprecated status in [v10.44](https://github.com/Shopify/polaris/pull/8938). 

If you can upgrade to that you won't see the log error.

**Comment by emilisense** [comment]
That answers my question, thanks±
