### ISSUE TITLE
[Button] Fix regressions

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#10897]
1. Update loading state

Expected | Actual
--|--
![Image](https://github.com/Shopify/polaris/assets/8629173/ffe96d7e-bd13-4f86-b0de-87e4629244af) | ![Image](https://github.com/Shopify/polaris/assets/8629173/82f359ab-c36b-4157-8f98-9eee3ef4744b)

2. Update split button spacing (https://github.com/Shopify/polaris/pull/10910)

Expected | Actual
--|--
![Image](https://github.com/Shopify/polaris/assets/8629173/96fb0ebc-a8bd-4c16-9b3e-6d6f1508f79f) | ![Image](https://github.com/Shopify/polaris/assets/8629173/d9c09c38-88e5-4365-8e88-5b959190ee1a)

3. Update disabled state of plain monochrome buttons - should use `text-disabled`

Expected | Actual
--|--
![Image](https://github.com/Shopify/polaris/assets/8629173/bf45a963-f689-47b5-935d-0fa94f72c5f7) | ![Image](https://github.com/Shopify/polaris/assets/8629173/e35c0fdb-20a5-482d-a1b9-e2fa25c525e6)

4. Update font-weight of tertiary buttons - should use font-weight `medium` (550)

Expected | Actual
--|--
<img width="811" alt="Screenshot 2023-10-05 at 8 57 26 AM" src="https://github.com/Shopify/polaris/assets/8629173/efc99dc1-5b24-46be-969a-20a869a95030"> | <img width="474" alt="Screenshot 2023-10-05 at 8 56 20 AM" src="https://github.com/Shopify/polaris/assets/8629173/466ccbf5-a744-4d79-91ec-7543101517c2">

**Comment by gazjones00** [comment]
Hey @sarahill, I've got a PR open to fix point 2 and 4! Hope this helps 🎉

fix(button): disabled state on monochrome variant - https://github.com/Shopify/polaris/pull/10934
fix(button): remove conflicting tertiary styles - https://github.com/Shopify/polaris/pull/10935

**Comment by kyledurand** [comment]
I think these have all been addressed. Feel free to reopen if we missed something @sarahill
