### ISSUE TITLE
Text field with "Number" type doesn't allow decimals

### ISSUE THREAD

**Issue by cgenevier** [Shopify/polaris-react-archive#109]
# Issue summary

The "number" type text field doesn't allow decimals. 

## Expected behavior

The number type should allow for decimals to accommodate currency. Ex: "2.53". 

## Actual behavior

The decimal and everything beyond is stripped from the input when the text field type is set to "number". 

I suggest either allowing for floats in the number field or else creating a new field type to accommodate floats / currency.

## Steps to Reproduce the Problem

1. Create a TextField component and set type="number"
2. Try to enter a number with a decimal (such as a currency).

## Specifications

- Polaris version: 1.0.3
- React version: 15.5.4
- Browser: All
- Device: All
- Operating System: All

**Comment by cgenevier** [comment]
And to add to the above, changing step="0.01" doesn't help. It seems that the minimum value for that attribute is 1.

**Comment by lemonmade** [comment]
Can you post code that exhibits this issue? I'm able to get a decimal-friendly text field, including one with a custom, non-integer steps, using code like this:

```js
<TextField
  label="Store name"
  type="number"
  value={2.53}
  step={0.5}
/>
```

**Comment by cgenevier** [comment]
Sorry about the delay replying here, this ended up being 100% my bad. I had a parseInt() in the onChange of the textfield that was converting the value to an integer.

**Comment by hadassaplotnik** [comment]
This was my bad too! Thanks for posting it.

**Comment by panth-thakkar-shipsy** [comment]
This thing is not working in safari browser. Textfield with type number does not accept decimals in safari browser. In rest all browsers it seem to work fine.

**Comment by yamlakkassahun** [comment]
i was facing this issue and the work round i found is using this package react-number-format
<NumericFormat
            size='small'
            fullWidth
            customInput={TextField}
          />

**Comment by danieloi** [comment]
I came here looking for a solution for Mui so I figured I'd drop the fix I found here.

For me, HTML validation was throwing for decimals till I used this prop for the TextField:

```javascript
 slotProps={{
            input: {
              inputProps: {
                step: 0.01,
              },
            },
          }}
```
