### ISSUE TITLE
[polaris.shopify.com] Fix cropped images

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#10908]
> Images are cropped and forced into a 16:9 viewbox when they’re larger (like 4:3 or 1:1)

@tjonx 

[Visual example]

**Comment by kyledurand** [comment]
I think I have context on this and can take it on tomorrow. I suspected something like this might come up

**Comment by tjonx** [comment]
Looks like some of the fixes caused visual regressions and broken layouts in Safari? https://github.com/Shopify/polaris/issues/10937
