### ISSUE TITLE
[polaris.shopify.com] New design guidance pages with video will open the video in a video player on mobile

### ISSUE THREAD

**Issue by tjonx** [Shopify/polaris-react-archive#10936]
## Issue summary

Videos that are autoplaying in the new design guidance pages open in a standalone video player on mobile devices (notably iOS)

## Steps to reproduce the problem

1. Open the "Pro design language" page in Safari on an iPhone
2. Page will change to a video player for the first video on the page
3. Close the video player
4. Page will change to a video player (again) for the second video on the page, etc.

## Specifications

- Browser: Safari
- Device: iPhone
- Operating System: iOS 17.0.3

## Potential solution

Disable autoplay on videos. This is also an accessibility issue.

**Comment by electron97** [comment]
Hey @tjonx ,
I have raised a PR to fix this issue. Could you please take a look whenever you get a chance?
Thanks!
