### ISSUE TITLE
Visual bug in safari with box borders/shadows

### ISSUE THREAD

**Issue by raquelbreternitz** [Shopify/polaris-react-archive#10985]
In Safari, on Mac, all the card border shading looks overly heavy in the corners, and overall the borders look offset by a pixel. Example:

![Screenshot 2023-10-13 at 12 31 15 PM](https://github.com/Shopify/polaris/assets/13204374/8e6441c0-460b-446e-960b-31a001fe31ea)

**Comment by kyledurand** [comment]
Hey Raquel! Looks like this is happening when Safari is zoomed a bit. Adding a video for some context. Thanks for raising this. Hope you're well!

https://github.com/Shopify/polaris/assets/6844391/5f4f1f8e-f999-49f4-92a3-3f562c365fca

**Comment by raquelbreternitz** [comment]
Oh my gosh you're right 🤦🏻I didn't even realize I was zoomed! Here it is zoomed in quite a bit as well, seems the border-radius goes away on the cards.

![Screenshot 2023-10-13 at 4 37 57 PM](https://github.com/Shopify/polaris/assets/13204374/2920f5bc-3dd4-4eb6-af80-27fd7e8e45e4)


Also hi Kyle! thanks for responding, it's nice to hear from you!
