### ISSUE TITLE
Require action icon

### ISSUE THREAD

**Issue by lntn2022** [Shopify/polaris-react-archive#10997]
## Feature request summary

In need a new icon that will represent "Payment pending" in the Orders Task Card. In working with Operate team @travis-eh @jeffkraemer2 we decided a new icon was necessary.

## Rationale

This icon will represent a filtered list of orders that required an action before they can receive their payout. I have 2 proposals.
1. Hand with joy sparks
2. Hand with money symbol

Joy sparks are a bit more abstract versus the money symbol.
![Screenshot 2023-10-16 at 12 51 13 PM](https://github.com/Shopify/polaris/assets/97758241/4a1adeee-69e8-4f8d-bd31-a631127f524d)
![Admin-home](https://github.com/Shopify/polaris/assets/97758241/12a75b23-7bd1-4a1c-9d4d-df839adfe510)
[Figma icon](https://www.figma.com/file/2HrCq3M47Pva0ogIwJWMZX/Improve-clarity-of-Markets-Pro-payouts?type=design&node-id=2048%3A58681&mode=design&t=eIh4Z9VYuItg0VHH-1)
[Figma admin page](https://www.figma.com/file/2HrCq3M47Pva0ogIwJWMZX/Improve-clarity-of-Markets-Pro-payouts?type=design&node-id=1080%3A192098&mode=design&t=eIh4Z9VYuItg0VHH-1)

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s :+1: upvotes to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by heyjoethomas** [comment]
Thanks for reaching out. The "3 orders that require action" row seems to be better suited for some sort of status icon rather than what is shown. The icon here doesn't really help communicate the actual state. I also think it is to similar to the icon right below it which actually may cause some confusion. 

The `RiskMinor` icon and corresponding status seem to best fit how you are defining "Action Required".

**Comment by lntn2022** [comment]
@heyjoethomas great suggestion. I think it works. I will propose this back to the team and see what they say.

**Comment by lntn2022** [comment]
![Screenshot 2023-10-23 at 11 36 03 AM](https://github.com/Shopify/polaris/assets/97758241/9ec29da6-f60b-41a4-8523-1aebcd13cf30)

**Comment by lntn2022** [comment]
@heyjoethomas Upon[ slack convo](https://shopify.slack.com/archives/C05S4106SQG/p1698084768623459) happening after I closed this ticket, I have a new proposal to bring forward. 

With collaboration with the Operate team, we are leveraging the existing Payouts icon with a slash across. From your early feedback this icon will help communicate the actual state. 

![Screenshot 2023-10-26 at 1 26 13 PM](https://github.com/Shopify/polaris/assets/97758241/912af3e5-074a-4c79-8df9-f8149e0f2ca7)

![Screenshot 2023-10-26 at 1 33 02 PM](https://github.com/Shopify/polaris/assets/97758241/4eea24b3-e6bd-40bd-867f-c7e9e153e685)

![Admin-home](https://github.com/Shopify/polaris/assets/97758241/496fa3d1-ef28-4ac1-b78e-1ebf2668c7fb)

**Comment by meko-deng** [comment]
This should be done, closing
