### ISSUE TITLE
Cannot select options in choice-list

### ISSUE THREAD

**Issue by Geczy** [Shopify/polaris-react-archive#11]
# Issue summary

Cannot select options in choice-list

## Expected behavior

Options become selected

## Actual behavior

Options are not selected

## Steps to Reproduce the Problem

1. Visit https://polaris.shopify.com/components/forms/choice-list#navigation
2. Click an option in the example
3. Option is not selected

**Comment by lemonmade** [comment]
Hey @Geczy, thanks for the issue. We made a conscious decision with v1 to only allow the components to update in response to the props set above them. We are going to be building in smarter examples, though, so keep an eye on the styleguide over the next week or two for improvements on this!
