### ISSUE TITLE
Missing components from Sketch

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris-react-archive#110]
Hi,

I can see some components included in the Sketch file that are not exposed in Polaris (I'm thinking of the various spinners, progress bar...

All of those are actually quite useful. Are there short terms plans to include them into the framework?

Thanks! :)

**Comment by alyseadlard** [comment]
Hey @bakura10! This is one of the items on our to-do list. We'll be working to get these loading components into Polaris soon but are not able to give a solid date for when that'll be. These comments help us prioritize items in that to-do list, so thank you for posting!

**Comment by dfmcphee** [comment]
Spinners, skeleton content and progress bars are now included in the component library.
