### ISSUE TITLE
InlineStack's "align" property can NOT config for mobile like "blockAlign"

### ISSUE THREAD

**Issue by mcjambi** [Shopify/polaris-react-archive#11009]
Funny, blockAlign can config for small screen, but Align is not.

**Comment by sam-b-rose** [comment]
Thanks for bringing this up @mcjambi 

@jesstelford has been working on making all props on `Box` responsive. We will also add this to the list of props to discuss making responsive as well. Right now, it is a bit of a mix as we have only been making them responsive as needed.

Related: #10890
