### ISSUE TITLE
[Icon] Update TwitterMinor icon to use X logo

### ISSUE THREAD

**Issue by heyjoethomas** [Shopify/polaris-react-archive#11013]
## Issue summary

Twitter branding needs to be updated to new X branding in `TwitterMinor` icon

**Comment by zecarlostorre** [comment]
Icon has been created, and added to the list of icons being updated and captured in[ this issue.](https://github.com/orgs/Shopify/projects/2250/views/121?type=beta&filterQuery=label%3AIcon&pane=issue&itemId=43469673)
