### ISSUE TITLE
How to run the polaris migrating-from-v11-to-v12

### ISSUE THREAD

**Issue by adventuretocode** [Shopify/polaris-react-archive#11011]
https://polaris.shopify.com/version-guides/migrating-from-v11-to-v12
 

## Specifications
what was the command need to run the migration

`npx @shopify/polaris-migrator react-update-component-prop --componentName Badge --fromProp statusAndProgressLabelOverride --toProp toneAndProgressLabelOverride "**/*.{js,jsx}"
Error: No migration found for react-update-component-prop

` 

- Are you using the React components? (Y/N): Y 
- Polaris version number: V12
- Browser: Chrome 
- Device: HP
- Operating System: Ubuntu

**Comment by sam-b-rose** [comment]
Hi @adventuretocode!

Looks like the `react-update-component-prop` migration was [added in version](https://github.com/Shopify/polaris/blob/main/polaris-migrator/CHANGELOG.md#0250) `0.25.0` of the `@shopify/polaris-migrator`.

I've had issues in the past where `npx` will cache the package and not use the latest version. Can you try the following command?

```shell
npx @shopify/polaris-migrator@ react-update-component-prop --componentName Badge --fromProp statusAndProgressLabelOverride --toProp toneAndProgressLabelOverride "**/*.{js,jsx}"
```

**Comment by adventuretocode** [comment]
@sam-b-rose  Thanks lot but i think in cli command show the version upgrade notice that was great feature...
 as the other Shopify NPM tools.
 
 I done the migration manually
