### ISSUE TITLE
Suggestion in Polaris Text field is buggy

### ISSUE THREAD

**Issue by Rafi993** [Shopify/polaris-react-archive#11041]
## Issue summary

* When you click on the middle of the text after pressing `Tab` in a input with suggestions, it renders the clicked text like a suggestion

## Expected behavior

* Nothing should happen when you click in the middle of the text
* Also pressing `tab` should accept the suggestion

## Actual behavior

https://codesandbox.io/s/sad-swirles-twk9r2

<img width="734" alt="Screenshot 2023-10-26 at 9 48 13 PM" src="https://github.com/Shopify/polaris/assets/8092120/f374d272-bda0-459c-a6ba-1e41ba298a89">

## Steps to reproduce the problem

1. Type a long text and wait for the suggestion
2. Press tab 
3. Now click in the middle of the suggestion

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: Polaris V12
- Browser: Chrome
- Device: M1 mac book pro
- Operating System: Mac OS Ventura

**Comment by Rafi993** [comment]
Pressing Ctrl / Cmd + A when the suggestion is shown also causes similar issue

**Comment by Rafi993** [comment]
Similarly if you show a suggestion but focus out of the input the suggestion color becomes dark (like the entered value)

**Comment by Rafi993** [comment]
Suggestion color in multi-line field is also broken

**Comment by yurm04** [comment]
Hey @Rafi993 👋 thanks for reaching out. The codesandbox link you provided isn't loading for me, it may have expired. Could you post another updated example and a video of how to replicate this issue please? Please include the browser, device, and operating system you're seeing this issue on as well.

This info will be a big help in debugging, thank you!

**Comment by Rafi993** [comment]
> Hey @Rafi993 👋 thanks for reaching out. The codesandbox link you provided isn't loading for me, it may have expired. Could you post another updated example and a video of how to replicate this issue please? Please include the browser, device, and operating system you're seeing this issue on as well.
> 
> This info will be a big help in debugging, thank you!

The link still works for me even without login

**Comment by Rafi993** [comment]
I have updated device and OS but I do suspect this bug is there across all devices

**Comment by aaronccasanova** [comment]
@yurm04 Codesandbox is being a bit flaky. It loaded once for me and then stopped working again. However, I noticed it's identical to our [Text field with with inline suggestion](https://polaris.shopify.com/components/selection-and-input/text-field?example=text-field-with-inline-suggestion) example. I can boot this up locally and try to repro.
