### ISSUE TITLE
Content authoring abstraction

### ISSUE THREAD

**Issue by gwyneplaine** [Shopify/polaris-react-archive#11044]
## Why 
At the moment authoring design content is difficult and error prone.
We want to land at an abstraction that makes this process **fast** and **easy** for content authors. 

@tjonx and @zecarlostorre have provided strong and good design boundaries for how content can be [laid out](https://www.figma.com/file/vO0wToyBpYjeIwr8doAAWT/Uplift-polaris.shopify.com?type=design&node-id=1804-32995&mode=design&t=TIOTeGhOE6DsGZEk-4) 

Our goal is to implement an abstraction that allows content authors to lean into these strong design boundaries while: 
a) Not having to worry about layout implementation and browser behaviour 
b) Not having to learn and memorise too much magic incantations 
c) Not have to unlearn learned behaviour from the underlying technology (Markdown) 

## What 
The present solution that we've arrived at is an abstraction on top of the browsers [grid](https://developer.mozilla.org/en-US/docs/Web/CSS/grid) spec, specifically `[grid-template-areas](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-areas)` and their ability to allow users to declare semantic areas where elements can be laid out. 

```
<LayoutSection card>
  <Text>
  </Text>

  <Small>
  </Small>

  <Medium>
  </Medium>
  
  <Large>
  </Large>
  
  <ExtraLarge>
  </ExtraLarge>
</LayoutSection>

<LayoutSection>
  <Text>
  </Text>

  <Small variant="do">
  </Small>

  <Small variant="dont">
  </Small>
</LayoutSection>
```

============

**Comment by alex-page** [comment]
Is this still being explored?

**Comment by sam-b-rose** [comment]
The initiative has slowed but I'd like to come to some opinion on how we author content. The linked PR #11046 has a good base of what is discussed here.

I'll update the PR to not include changes to `Grid.Cell` and we can review and quickly decide if this is the direction we want to establish for layout in MDX content.
