### ISSUE TITLE
Update icon designs, remove Major and Minor suffix, and update icon names

### ISSUE THREAD

**Issue by zecarlostorre** [Shopify/polaris-react-archive#11088]
### Why are you proposing this update?

A few reasons:
- Some icons in the nav have an odd visual shift between filled and outline, so we reduced it as much as possible.
- A few metaphors being used weren't right, so we updated it.
- Lastly, we took the opportunity to clean up/improve a couple icons that needed it.

### Icon name

See description above

### What type of icon set?

Major (20x20)

### Icon SVG code

[Icons Update.zip](https://github.com/Shopify/polaris/files/13243684/Icons.Update.zip)

### Release strategy

- [x] https://github.com/Shopify/polaris-internal/issues/1177
- [x] Migrate and update web deps
  - [x] `@shopify/app-bridge-host` (NA)
  - [x] `@shopify/app-kit-internal` https://github.com/Shopify/app-kit/pull/624
  - [x] `@shopify/flow-app` https://github.com/Shopify/flow-app/pull/3113
  - [x] `@shopify/magic-ui` https://github.com/Shopify/magic-ui/pull/202
  - [x] `@shopify/online-store-ui` https://github.com/Shopify/online-store-ui/pull/4382
- [x] https://github.com/Shopify/web/pull/114592
- [x] Update [store activity icon](https://github.com/Shopify/polaris-internal/issues/1196#issuecomment-1843091677)

## Post Release

- [ ] Share post detailing icon release stats
  - [ ] Reduction is total icons in the system
  - [ ] Smaller library bundle size
  - [ ] Reduced number of icons used in the admin
  - [ ] Any other metrics worth mentioning?

### Icon updates

- [x] Removed Major and Minor icon sizing. All icons are the same size.
- [x] Updated icon designs (see SVG zip)
- [x] Added icons `ShippingLabelIcon`, `ShippingLabelFilledIcon`, `BillIcon`, `BillFilledIcon`, `ActivityLogIcon`, `ActivityLogFilledIcon`, `InstagramIcon`, `TipsIcon`
- [x] Removed icons `ReportFilledMinor`, `ReportMinor`, `ListMajor`, `ListFilledMajor`
- [x] Removed `version` and `set` from icon `.yml` files
- [x] Updated default icon color to `#4A4A4A`
- [x] Renamed many icons and replaced `Major` and `Minor` suffixes with `Icon`

**Comment by zecarlostorre** [comment]
@alex-page & @sam-b-rose - during this week I had a few icon requests, I have the designs ready - could we include them in this batch of work?

**Comment by alex-page** [comment]
@zecarlostorre Yeah we can. Just batch them together in a zip.

**Comment by zecarlostorre** [comment]
@alex-page Amazing! 🙌

I'm going to add 2 zips and explain what's in it:

**Name updates**
`Toggle`: Update to `ToggleOff` (because we're now adding a `ToggleOn`)

**Updates & fixes**
`SocialTwitter`: Updated, the logo was flipped 🤦‍♂️
`Globe`: Updated the design of the continents
`Markets`: Updated the design of the continents 
`Send`: Reduced icon's visual weight.

**New:** 
`GlobeFilled`
`ToggleOn`
`ClipboardCheckedFilled`

**Localised globes:** 
I think this should be it's own ticket, so I seperate those in a different ZIP, but I thought of asking the question here to confirm.
We want to have the Globe icons reflect the market a merchant is in. I thought the logic to get this working was something we had already for currency, since we had icon variants for the main currencies for a while, but when I checked my store, which is in euro, I still see the dollar icon. So maybe my assumption was incorrect.

Let me know what you think would take to get this working.
In any case, I created all the Globe variants I think we need, we could add them as part of this update, and figure out the logic to have it work later.


**SVGs:**
[Icon updates and fixes.zip](https://github.com/Shopify/polaris/files/13476047/Icon.updates.and.fixes.zip)
[Localised Globes.zip](https://github.com/Shopify/polaris/files/13476083/Localised.Globes.zip)

**Comment by alex-page** [comment]
> We want to have the Globe icons reflect the market a merchant is in. I thought the logic to get this working was something we had already for currency, since we had icon variants for the main currencies for a while, but when I checked my store, which is in euro, I still see the dollar icon. So maybe my assumption was incorrect.
>
> Let me know what you think would take to get this working.

This should be possible. I haven't changed any part of the UI based on geolocation before but the first step is to have the icons be a part of the library so we can replace the icons based on where the user is based.

**Comment by alex-page** [comment]
Icons v8.0.0 has shipped. Going to start implementing this in products across Shopify now.

**Comment by lgriffee** [comment]
@alex-page @zecarlostorre  Thought I would post the stats I have for the Icon work here in case you want to use it in your post. I wasn't sure how best to represent some of these wins so I never ended up creating a mockup on my end (wasn't sure what you wanted to show visually versus write about in the post). 
- Reduced icons library SVG size by 383.75kb
- Removed +78kb of SVG files
- Removed 19 duplicate hardcoded icons in web
- Fixed icons rendering differently in spin, vite and webpack builds. And caused folks to deploy icons that looked right and then would be broken in production builds.
- Reduced odd visual shifts between filled and outline icons
- Updated and improved metaphor for certain instances
- Cleaned up/improved several icons
