### ISSUE TITLE
cancel (x) button doesn't do anything in IndexTable

### ISSUE THREAD

**Issue by scraper095** [Shopify/polaris-react-archive#11090]
## Issue summary
After filtering, clicking on (x) button in IndexTable search doesn't do anything
![image](https://github.com/Shopify/polaris/assets/147501351/849b9095-a9bd-4380-bd61-84c9ac96eace)

## Expected behavior
Removing the text in the search bar

## Actual behavior
Click doesn't do anything

## Steps to reproduce the problem

1. Create an IndexTable
2. Write anything in the search bar
3. Click (x)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 12.0.0
- Browser: Google Chrome
- Device: PC
- Operating System: Mac

**Comment by kyledurand** [comment]
I think you need to reset the query string manually buy using the `onQueryClear` prop, which is documented [here](https://polaris.shopify.com/components/selection-and-input/filters#props)

https://github.com/Shopify/polaris/blob/23055adcfa97decbfbc51924bd121d1dae76ac6f/polaris-react/src/components/IndexFilters/IndexFilters.stories.tsx#L370

If we have a broken example somewhere can you link to it?

**Comment by scraper095** [comment]
> I think you need to reset the query string manually buy using the `onQueryClear` prop, which is documented [here](https://polaris.shopify.com/components/selection-and-input/filters#props)
> 
> https://github.com/Shopify/polaris/blob/23055adcfa97decbfbc51924bd121d1dae76ac6f/polaris-react/src/components/IndexFilters/IndexFilters.stories.tsx#L370
> 
> If we have a broken example somewhere can you link to it?

Thanks, it works.
I used the example of `IndexFilters` [here](https://polaris.shopify.com/components/selection-and-input/index-filters), where onQueryClear is empty for.

**Comment by kyledurand** [comment]
Thanks @scraper095 I'll fix that up
