### ISSUE TITLE
[Badge] Updates

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#11097]
```[tasklist]
### Tasks
- [ ] Font-weight should be medium, currently displaying as regular weight
- [ ] "New" badge weight should be "semibold", currently displaying as "medium"
```

**Comment by bernardojoaogarcia** [comment]
@alex-page might be worth pushing this into `Build`

**Comment by bernardojoaogarcia** [comment]
@sarahill Is the 2nd task item necessary? Medium font for all badges might be more adequate for the time being until we figure out the `New` badge.

**Comment by sarahill** [comment]
@bernardojoaogarcia This was the distinction we had originally with Uplift but I know you've been looking into the `new` badge more. It may not be a distinction we need. If that's the case, I don't think there would be any differentiation and I would question if we need that variant at all. I think an outcome of your exploration was the recommendation to dig more into "Feature awareness" as a pattern so maybe we just leave the `new` variant as is for now and revisit it. Thoughts?

**Comment by alex-page** [comment]
I will leave this in the backlog as we are going to create a new project which this will be a part of.

**Comment by sarahill** [comment]
Closing as these issues will be addressed in a separate issue.
