### ISSUE TITLE
[Button] Update button examples in storybook and polaris.shopify.com

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#11098]
```[tasklist]
### Tasks
- [x] polaris.shopify.com missing examples for “icon”, “iconOnly”
- [x] Storybook using outdated prop names for examples “Destructive” vs. “Critical”
```

**Comment by yurm04** [comment]
@sarahill I don't see any `destructive` prop values in the storybook stories for button. Is this task already resolved or was the issue somewhere else?

**Comment by sarahill** [comment]
> @sarahill I don't see any `destructive` prop values in the storybook stories for button. Is this task already resolved or was the issue somewhere else?

Ah yea someone must have updated it. We can mark that as resolved!

**Comment by lgriffee** [comment]
Closing with the release of:
- https://github.com/Shopify/polaris/pull/11454
-  https://github.com/Shopify/web/pull/115164
