### ISSUE TITLE
[Icon Search] Icon search not working 

### ISSUE THREAD

**Issue by blanklob** [Shopify/polaris-react-archive#11110]
## Issue summary

Icon search not working

https://github.com/Shopify/polaris/assets/63895927/f1558e83-fcb4-4170-90b9-17e4b6dcc3b1

## Expected behavior

Its should only show icons that I searched for.

## Actual behavior

Its just seems to not working or making requests either.

## Steps to reproduce the problem

1. First step
1. Second step

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
 System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M2
    Memory: 183.98 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh

- Browsers:
    Chrome: 118.0.5993.117
    Safari: 16.5.2
  - npmPackages:
    @shopify/polaris: 12.1.1 => 12.1.1 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
```

**Comment by alex-page** [comment]
This should be resolved now. Thanks @blanklob. Some major changes happening to icons soon and some code went out too early and broke it.
