### ISSUE TITLE
Icon list does not show in this page.

### ISSUE THREAD

**Issue by zenaul** [Shopify/polaris-react-archive#11137]
### Icon list does not show in this page.

<img width="1869" alt="image" src="https://github.com/Shopify/polaris/assets/10365575/f6bc3430-d997-4ec7-a096-dc10ac2fcdd8">

### Icon name

All

### What type of icon set?

Major (20x20)

### Icon description

Icon does not show 

### Icon keywords

All

### Icon SVG code

```shell
<svg>...</svg>
```

**Comment by alex-page** [comment]
Taking a look! Thanks @zenaul

**Comment by alex-page** [comment]
Fixed by https://github.com/Shopify/polaris/commit/14ea36ae0170dada74d1b157ac272f913c13c0cf should be live soon.
