### ISSUE TITLE
Card component not automatically applying small screen styles

### ISSUE THREAD

**Issue by ouellettejordan** [Shopify/polaris-react-archive#11142]
## Issue summary

Cards using the `Card` component still applying border radius at small screen size. This is being missed by developers and resulting regarded ui quality and is especially important for mobile native web views.

## Expected behavior

Cards using `Card` component should automatically remove the corner radius at small screen size. The old `LegacyCard` component did this and we should have carried over that behaviour to the newer `Card` component.

**Comment by dGoligorsky** [comment]
Related to this ticket on `mobile`: https://github.com/Shopify/mobile/issues/24942

**Comment by dGoligorsky** [comment]
Looking at the Card in the Polaris docs and the sandbox, it seems to respect the square corners on small viewports...
![card_corners](https://github.com/Shopify/polaris/assets/5823560/5dc9ec68-f67b-4423-94fe-03535a899806)

But it's not working in production on responsive web or mobile webviews.
![card_mweb_responsive](https://github.com/Shopify/polaris/assets/5823560/6deb3469-87ce-47cf-8dfa-69be3cc10bb2)

Digging into the code as best as I can understand it, it seems like the [`Card` component](https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/Card/Card.tsx) does indeed have the support for square corners below a given breakpoint. However, I believe it doesn't have a default setting, which I think means that consumers need to _actively_ specify this breakpoint behavior, and they're not (see this Languages settings page as an example where there's not a prop passed to `Card` for a `roundedAbove` property.
