### ISSUE TITLE
Artefacts appearing around primary buttons on hover

### ISSUE THREAD

**Issue by kellyjepsen** [Shopify/polaris-react-archive#11162]
## Issue summary

When hovering over many of the primary buttons on web (Chrome, MacOS) strange visual artefacts appear (see below).

![Screenshot 2023-11-09 at 8 08 53 AM](https://github.com/Shopify/polaris/assets/13091811/0f28813e-c3c6-41c9-b09f-2dc28bd92f00)
![Screenshot 2023-11-09 at 8 23 48 AM](https://github.com/Shopify/polaris/assets/13091811/5081915b-706c-4612-aaf0-4542c316c229)
![Screenshot 2023-11-09 at 8 23 57 AM](https://github.com/Shopify/polaris/assets/13091811/e74d03cc-d723-4fee-a47b-daa041a742d6)

## Expected behavior

I would expect these artefacts to not appear 😅 

## Actual behavior

A strange blur/pixellated spikes appear around the edges of the primary buttons when I hover them. The more I hover, the more prominent they become. They don't disappear until page refresh. Happens on most (but not all) primary buttons as far as I can tell.

## Steps to reproduce the problem

1. Using Google Chrome (version: 119.0.6045.123) and MacOS (version: 14.1 (23B74))
2. Opening my test store https://admin.shopify.com/store/black-black-shirts
3. Go to any page with a primary button (e.g. /products, /orders)
4. Hover mouse over the primary button multiple times and the artefacts appear

## Specifications

- Polaris version number: Production
- Browser: Chrome (version: 119.0.6045.123)
- Device: MacBook Pro M1
- Operating System: MacOS (version: 14.1 (23B74))

**Comment by lgriffee** [comment]
Re-opening this issue until 

- https://github.com/Shopify/polaris/pull/11351 

is shipped to prod.
