### ISSUE TITLE
[ResourceItem] shortcutActions do not appear on mouseover 

### ISSUE THREAD

**Issue by chrislarabee** [Shopify/polaris-react-archive#11183]
## Issue summary

Supplying the values to the shortcutActions property on ResourceItem does not result in any shortcutAction buttons appearing on the resource item once rendered. 

I checked for any other issues with ResourceItem and only saw people noting that the shortcutAction buttons weren't positioned correctly, rather than that they didn't appear at all. Perhaps removing them entirely is the short term solution for now?

## Expected behavior

For each shortcutAction supplied in the array, one button would previously appear when the item was hovered. Each shortcutAction could act as a link to a url or have a customizable onAction function.

## Actual behavior

No shortcutActions appear on hover. This is also the case in the [documentation for ResourceItem](https://polaris.shopify.com/components/lists/resource-item?example=resource-item-with-shortcut-actions), that's supposed to demo the shortcutAction functionality actually. 

## Steps to reproduce the problem

Simply create a ResourceList and provide a ResourceItem with the shortcutActions configured to the renderItem prop (see sandbox below for very simple example).

## Reduced test case

Sandbox [here](https://codesandbox.io/s/shopify-polaris-react-typescript-playground-forked-kn23yp?file=/src/index.tsx)

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number: 12.1.1
- Browser: I've checked Chrome and Firefox so far.
- Device: PC
- Operating System: Ubuntu in WSL

```bash
  System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz
    Memory: 3.45 GB / 11.68 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.2.2 - ~/.nvm/versions/node/v20.9.0/bin/npm
  npmPackages:
    @shopify/polaris: ^12.1.1 => 12.1.1 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
```

**Comment by nicklozon** [comment]
On 12.11.1, still an issue.

This example is also broken (Edit: you already mentioned that): https://polaris.shopify.com/components/lists/resource-list?example=resource-list-with-item-shortcut-actions

**Comment by mbaumbach** [comment]
@nicklozon @chrislarabee These actions will only show up on a large enough window in the browser. If you always want them available even on small screen sizes, you'll need to also add the `persistActions` prop. The documentation site doesn't have a big enough iframe to render the large screen size and show the actions, which is a bit confusing.

**Comment by chrislarabee** [comment]
@mbaumbach Ahhhh, that clarifies things, thank you!
