### ISSUE TITLE
Improve overlapping transparent borders

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris-react-archive#11190]
![Image](https://github.com/Shopify/polaris/assets/6844391/3f4d4fe7-8c67-4de1-96a6-d858a8b5bddd)

Something on Buttons or ButtonGroup as well

![image](https://github.com/Shopify/polaris/assets/6844391/e0cbb9bb-7115-4f34-8a3f-305bbc07e87c)

**Comment by sarahill** [comment]
Related to https://github.com/Shopify/polaris-internal/issues/1095

**Comment by sam-b-rose** [comment]
I've added the content of this issue to https://github.com/Shopify/polaris-internal/issues/1095

Going to close this one out for now
