### ISSUE TITLE
[polaris.shopify.com] Props table feedback

### ISSUE THREAD

**Issue by aliasgerbk** [Shopify/polaris-react-archive#11192]
The tone attribute seems to have been changed to status. Please make the update. Spend nearly an hour trying to figure that out until I saw the definition of the Badge component in the code.

**Comment by kyledurand** [comment]
Are you on an older version of Polaris? In v12 we changed status to tone which is correctly documented. Unfortunately we can't offer versioned documentation at this time. It's something we're thinking about adding in the future.

**Comment by aliasgerbk** [comment]
Understood- thanks for the update.
