### ISSUE TITLE
Simplify primary and default button shadows

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris-react-archive#11191]
![Image](https://github.com/Shopify/polaris/assets/6844391/4c746b61-1aaf-4fca-b42a-c8befa063e50)

In some drastic cases it's causing severe render issues:

https://github.com/Shopify/polaris/issues/11162

![Image](https://github.com/Shopify/polaris/assets/6844391/128642b7-c292-4b72-b407-05e7279f7e0d)

**Comment by sam-b-rose** [comment]
@kyledurand prototyped a [heavily simplified primary button](https://codesandbox.io/p/sandbox/cool-feather-2krw5l?file=%2Fstyles.css%3A1%2C1) with two less box shadows, no pseudo elements, two less DOM elements.

I've incorporated his amazing work into a larger [Button code cleanup here](https://github.com/Shopify/polaris/pull/11212/files)

Should be ready for design review soon @heyjoethomas

**Comment by tjonx** [comment]
FYI, we shouldn't change the look of the buttons, only the way they are built in code to avoid having visual artifacts.

**Comment by heyjoethomas** [comment]
> FYI, we shouldn't change the look of the buttons, only the way they are built in code to avoid having visual artifacts.

We are trying to do that but the two are connected. The visual design is what facilitated the code to be what it is, which is causing the bugs. So we have to look at the whole thing. But we are trying to change as little as possible.

**Comment by sam-b-rose** [comment]
I haven't completed the refactor, but here is an the current draft of fixing the button bevel:

https://5d559397bae39100201eedc1-qxznwvmphg.chromatic.com/?path=/story/all-components-button--all

**Comment by tjonx** [comment]
Side note, there's a neat css trick that I used in the past that tends to fix some rendering issues. Adding `transform: translate3d(0,0,0);` forces the gpu to rerender the element, usually fixing some visual artifacts (the fuzzies/pixels we're seeing in some of our buttons today).

| With `transform: translate3d(0,0,0)` | Without | 
| --- | --- |
| ![image](https://github.com/Shopify/polaris/assets/67433661/67e169a2-885d-4da3-92d6-202961f17fd5) |  ![image](https://github.com/Shopify/polaris/assets/67433661/af3152e9-3e16-437f-a6e6-3313a9219746) |

**Comment by heyjoethomas** [comment]
Took that simple button and applied it consistently across all the primary buttons. Coming together nicely. 

![Image](https://github.com/Shopify/polaris/assets/5749440/bcfb91ac-ba6f-4fbc-bf12-cc8c83912abc)

**Comment by alex-page** [comment]
@sam-b-rose should we close this PR for https://github.com/Shopify/polaris/pull/11212 now?

**Comment by sam-b-rose** [comment]
> should we close this PR for https://github.com/Shopify/polaris/pull/11212 now?

No,  this is the related issue. This will get closed once we merge int #11212 👍

**Comment by lgriffee** [comment]
Re-opening this issue until 

- https://github.com/Shopify/polaris/pull/11351 

is shipped to prod.

**Comment by lgriffee** [comment]
Re-opening this issue until 

- https://github.com/Shopify/polaris/pull/11351 

is shipped to prod.
