### ISSUE TITLE
[IndexTable] MWeb + Mobile Webviews have large gap above first row.

### ISSUE THREAD

**Issue by ssetem** [Shopify/polaris-react-archive#11200]
## Issue summary

We are seeing an unwanted gap above the first IndexTable row in MobileWeb + Webviews. 

<img width="200" alt="Screenshot 2023-11-21 at 10 09 00" src="https://github.com/Shopify/polaris/assets/703938/5b9ac67b-717c-4ac9-87fb-06cf03d16dbf">
<img width="200" alt="Screenshot 2023-11-21 at 10 02 24" src="https://github.com/Shopify/polaris/assets/703938/d35721eb-2b01-4fd7-a2cd-fdb948a27481">
<img width="200" alt="Screenshot 2023-11-21 at 10 02 16" src="https://github.com/Shopify/polaris/assets/703938/6db168ca-ac6f-4890-9374-17bbbd6d5ab0">
<img width="200" alt="Screenshot 2023-11-21 at 09 48 45" src="https://github.com/Shopify/polaris/assets/703938/7726cf4b-680d-41af-94c5-d15f6b104971">
<img width="200" alt="Screenshot 2023-11-21 at 09 48 32" src="https://github.com/Shopify/polaris/assets/703938/cf5fd90e-8c63-406a-85ba-223c9892d901">
<img width="200" alt="Screenshot 2023-11-21 at 09 58 24" src="https://github.com/Shopify/polaris/assets/703938/15cce94c-e4ce-47d0-860f-92b8beca034d">

## Expected behavior

There should not be any gap above the first row.

## Actual behavior

There is a gap above the first row on MWeb + Webviews

## Steps to reproduce the problem

1. Load Admin in Chrome
2. Set Viewport to a MobileViewport
3. Visit these areas in Admin Web
  - Orders > Orders
  - Orders > Drafts
  - Content > Files
  - Products > Products
  - Products > Collections
  - Products > Transfers
  - Products > Purchase Orders

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 12.1.1
- Browser: Chrome, Safari, Mobile Safari
- Device: Desktop, iOS, Android
- Operating System: mac

**Comment by dGoligorsky** [comment]
Seems that the spacing is due to the Height of the `indexFiltersWrapper` to account for the sticky index table header.
It should probably have a conditional, like if `indexFilterSticky` then make the height 97px. Otherwise, height can be auto.
https://screenshot.click/21-27-wv7l8-zvl4e.mp4

**Comment by sophschneider** [comment]
I also noticed on mobile when the search is expanded the sticky bar is erroneously transparent 

![Image](https://github.com/Shopify/polaris/assets/20652326/c02d76f0-18a8-4f2a-935c-ceff683b4c2d)

**Comment by sophschneider** [comment]
Another issue, the padding on the filter bar on mobile doesn't align with the search bar on mobile. Not sure if we want these to be aligned or not



![Image](https://github.com/Shopify/polaris/assets/20652326/e49ff054-174d-496e-aa41-52defb206f77)

**Comment by dGoligorsky** [comment]
> Another issue, the padding on the filter bar on mobile doesn't align with the search bar on mobile. Not sure if we want these to be aligned or not

Nice catch!
It seems like the filter bar padding is 8px when a filter is actually selected. That would match the 8px padding that exists on the search bar.
So I think just need to cut the padding from 16px to 8px when no filter is selected.

![image](https://github.com/Shopify/polaris/assets/5823560/58a3ebdd-2d97-4dc7-bf22-0d4b554405fe)
![image](https://github.com/Shopify/polaris/assets/5823560/bc2932a3-e080-44bd-bec1-ccce74225b2b)

**Comment by sophschneider** [comment]
In [my PR](https://github.com/Shopify/polaris/pull/11211) I fixed all the issues above

|Before|After|
|-|-|
|<img width="200" alt="Screenshot 2023-11-23 at 3 22 32 PM" src="https://github.com/Shopify/polaris/assets/20652326/fdb1999d-b777-4f52-9701-6c09b4c8f8cc">|<img width="200" alt="Screenshot 2023-11-23 at 3 22 40 PM" src="https://github.com/Shopify/polaris/assets/20652326/f6a96711-bc51-4998-a950-2474233b30da">|

|Before|After|
|-|-|
|<img width="200" alt="Screenshot 2023-11-23 at 3 10 31 PM" src="https://github.com/Shopify/polaris/assets/20652326/0461dfab-a6a3-49ef-a9e6-3274a276874a">|<img width="200" alt="Screenshot 2023-11-23 at 3 59 09 PM" src="https://github.com/Shopify/polaris/assets/20652326/25d96af1-ee5c-4d7e-a29e-778b13ba5273">|

|Before|After|
|-|-|
|<img width="380" alt="Screenshot 2023-11-23 at 4 00 35 PM" src="https://github.com/Shopify/polaris/assets/20652326/c3d8470a-2e2f-472e-8c05-a60b0d22bd50">|<img width="375" alt="Screenshot 2023-11-23 at 4 01 12 PM" src="https://github.com/Shopify/polaris/assets/20652326/b4608321-c9d3-45b6-badb-7e3a62baea8d">|
