### ISSUE TITLE
[Icon]: New icon: Checklist for Test Drive

### ISSUE THREAD

**Issue by torben-nielsen** [Shopify/polaris-react-archive#11214]
### How will these icons be used?

We'll be using them in the Organizations Settings section, for the Test Drive feature. 

Here's how it should look: 
![img](https://screenshot.click/22-05-x8fdw-ps4s9.png)

I believe we need a fill version and outline version. 

### Icon name

Test Drive Checklist

### What type of icon set?

Unsure

### Icon description

Used on Settings nav

### Icon keywords

settings, test drive

### Icon author

Janna Moreau

### Icon Figma link

https://www.figma.com/file/WScC5YXq0Ox4ZiCAaPq8KW/Feature-Previews?type=design&node-id=1208%3A138544&mode=design&t=RTlh62cfPDJEvixX-1

### Icon SVG code

```shell
<svg>...</svg>
```

### Are there any other important details?

Not that I know of, but cc @boyutf @jannamoreau16

**Comment by zecarlostorre** [comment]
`ClipboardCheckedFilled` will be added as part of [this batch of work.](https://github.com/orgs/Shopify/projects/8713/views/27?pane=issue&itemId=43805054)

It was already added to the Figma library, and should be available shortly (in the next Library update)

**Comment by boyutf** [comment]
Hi, 
What we are looking for is a `CheckListFilledMajor`, currently we only have an unfilled version:
https://unpkg.com/browse/@shopify/polaris-icons@7.9.0/dist/svg/ChecklistMajor.svg
see [figma](https://www.figma.com/file/WScC5YXq0Ox4ZiCAaPq8KW/Feature-Previews?type=design&node-id=1208-138544&mode=design&t=xmMdZ5x6XB7oG4lg-0):


![Image](https://github.com/Shopify/polaris/assets/20749400/16839c80-7a39-40ea-a2ea-23f11bb0dd56)

**Comment by alex-page** [comment]
Hey sorry for the confusion. I am going to reopen this issue and close it when the icons release goes out and you can use this icon.

**Comment by torben-nielsen** [comment]
@alex-page is there a more definitive ETA for that yet?

**Comment by alex-page** [comment]
It will probably be early January. If this is a problem please let me know.

**Comment by torben-nielsen** [comment]
@alex-page - following up on this so we don't forget!

**Comment by alex-page** [comment]
I am trying to ship icon name alignment this week. That work will unblock icon releases. Thanks for your patience.

**Comment by alex-page** [comment]
This is shipped
