### ISSUE TITLE
Upgrading Polaris And React to Latest in Shopify App Development

### ISSUE THREAD

**Issue by dineshdahal** [Shopify/polaris-react-archive#11229]
**I tried upgrading polaris as polaris version is still 10.49.1 in shopify app develpemnt frontend cli for php. But it shows error. The error is as such::**

'Log files:
C:\Users\DELL\AppData\Local\npm-cache\_logs\2023-11-24T08_21_32_517Z-debug-0.log

# npm resolution error report

While resolving: shopify-frontend-template-react@1.0.0
Found: react@17.0.2
node_modules/react
  react@"^17.0.2" from shopify-frontend-template-react@1.0.0
  web/frontend
    shopify-frontend-template-react@1.0.0
    node_modules/shopify-frontend-template-react
      workspace web\frontend from the root project

Could not resolve dependency:
peer react@"^18.0.0" from @shopify/polaris@12.1.1
node_modules/@shopify/polaris
  @shopify/polaris@"*" from shopify-frontend-template-react@1.0.0
  web/frontend
    shopify-frontend-template-react@1.0.0
    node_modules/shopify-frontend-template-react
      workspace web\frontend from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

**I tried upgrading react as well but it created other problems as well. So, is there anything I can do? I am new to Polaris and not too deep into React either. **

**Comment by iamphonghg** [comment]
Polaris v12 requires react 18
