### ISSUE TITLE
[Button] Does not have proper types for its defined parameters

### ISSUE THREAD

**Issue by SMAKSS** [Shopify/polaris-react-archive#11234]
## Issue summary

When using `<Button>` component parameters like `onClick`, `onBlur`, and `onFocus`. If you try to catch the default `SynteticEvent` in your handler, it will throw a warning like below:

<img width="758" alt="Screenshot 2023-11-27 at 00 53 07" src="https://github.com/Shopify/polaris/assets/32557358/728d7c22-1b78-4df2-8eb6-4b7654240178">

Which is saying that they won't return any parameters for the handlers. This is accurate because they do not have any defined types for it. (Unlike, `onKeyPress`, `onKeyUp`, etc.)

<img width="737" alt="Screenshot 2023-11-27 at 00 55 11" src="https://github.com/Shopify/polaris/assets/32557358/bbf5e750-78cf-4313-a200-7a0d5aa53a24">

## Expected behavior

As they are already returning a `SynteticBaseEvent`, it should be properly added to these `<Button>` parameters.

Here is the event:
<img width="1194" alt="Screenshot 2023-11-27 at 00 58 18" src="https://github.com/Shopify/polaris/assets/32557358/a0c97665-2b5f-4416-ad83-3a9939f1aa90">

## Steps to reproduce the problem
You may need to use Typescript in your project and then follow these steps:

1. Create a `<Button>` component.
2. Add one of these parameters: `onClick`, `onBlur`, `onFocus`.
3. Write a handler that accepts a single parameter (You can name it whatever you like; I will call it `event`).
4. Pass it to one of the parameters you created before (It can be via the inline arrow function or the arrow function stored in a variable)
5. Typescript will throw a warning about passing too few arguments, which means these properties won't pass any arguments to the handler.

Here is an example:
```js
const handleButton = (event: SyntheticEvent<HTMLButtonElement, MouseEvent>) => {
  const {currentTarget} = event
  console.log(currentTarget.id)
}

<Button
   id="click_me_button"
   onClick={handleButton}
 >Click me!</Button>  
```
It will throw this warning in Typescript:

> Type '(event: SyntheticEvent<HTMLButtonElement, MouseEvent>) => void' is not assignable to type '() => unknown'.
  Target signature provides too few arguments. Expected 1 or more, but got 0. ts(2322)
  
> types.d.ts(65, 5): The expected type comes from property 'onClick' which is declared here on type 'IntrinsicAttributes & ButtonProps'

Which refers to declared types in `BaseButton` interface which is as follows:

```js
export interface BaseButton {
   // Other parameters
   
   /** Callback when clicked */
   onClick?(): unknown;
   /** Callback when button becomes focused */
   onFocus?(): void;
   /** Callback when focus leaves button */
   onBlur?(): void;
   /** Callback when a keypress event is registered on the button */
   onKeyPress?(event: React.KeyboardEvent<HTMLButtonElement>): void;
   
   // Rest of parameters  
}
```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 12.1.1
- Browser: Chrome (Version 119.0.6045.159 (Official Build) (x86_64))
- Device: MacBook Pro
- Operating System: Sonoma(14.1.1)

**Comment by SMAKSS** [comment]
Well, it's been weeks since I put this, but it still has yet to get triaged, and this problem still exists within the code base.

**Comment by aaronccasanova** [comment]
Hey @smakss, the omitted synthetic events are an intentional API design decision ([see more here](https://github.com/Shopify/polaris/issues/521)).

cc @alex-page @sam-b-rose After reviewing the [Button API design types](https://github.com/Shopify/ui-api-design/blob/f8287d746435edc2760f830bb0ea099cf1db3a49/components/Button/Button.ts#L37), I'm assuming we intend to continue this convention. Do you two have any additional insights?

**Comment by alex-page** [comment]
Yep for now this is intentional. It's definitely a pain point that we are aware of.
