### ISSUE TITLE
[Button] Increase gap in primary button with prefix icon

### ISSUE THREAD

**Issue by annaofthewoods** [Shopify/polaris-react-archive#11241]
## Primary button with prefix icon

The gap between the label and prefix icon is too tight in the primary button. This becomes problematic when using icons that fill the entire 14px key lines. Increasing the gap to 2px, similar to default button, would alleviate the issue.

Example:

In Audiences app we plan to use the logo icons in the primary button to denote you will need to leave the platform. Here are some examples compared to other icon fill sizes.

![Button spacing](https://github.com/Shopify/polaris/assets/18662293/6442a611-e3fe-4eb1-beb5-124e7696e32a)

**Comment by yurm04** [comment]
Is this work meant for the UI Kit or for our react components, or both?

**Comment by heyjoethomas** [comment]
This seems like a Figma bug. In Storybook I see 2px between icons and labels. Will publish a fix and close this issue out.
