### ISSUE TITLE
Index Table scrollbar appears over pagination when not overflowing

### ISSUE THREAD

**Issue by job-lee** [Shopify/polaris-react-archive#11248]
## Issue summary

On Firefox, when "Always show scrollbars" is enabled in Windows Settings > Accessibility > Visual Effects on Windows 11, the scrollbar appears over pagination bar.

This issue also appears in Firefox on Windows 10 (without enabling always show scrollbars).

## Expected behavior

Scrollbar should be hidden if table is not overflowing.

## Actual behavior

An empty scrollbar appears over the pagination arrows and bar.

![image](https://github.com/Shopify/polaris/assets/6374528/2414768f-2e7f-4d1b-b6a9-df01970ff4bf)

## Steps to reproduce the problem

1. On Windows 10, go to next step. In Windows 11, enable "Always show scrollbars" in **Accessibility > Visual Effects**. 
2. In Firefox, open https://polaris.shopify.com/components/tables/index-table?example=index-table-with-pagination
3. Ensure the window is wide enough so that the table contents in the example don't overflow. 

## Possible Solution
Add `overflow: hidden` on `.Polaris-IndexTable__ScrollBarContainer .Polaris-IndexTable--scrollBarContainerHidden`

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 12
- Browser: Firefox 112
- Operating System: Windows 11 and Windows 10

**Comment by remy727** [comment]
This issue still exists on the latest Polaris version: `12.21.0`
Temporary solution:
```css
.Polaris-IndexTable__ScrollBarContainer.Polaris-IndexTable--scrollBarContainerHidden {
  overflow: hidden;
}
```
