### ISSUE TITLE
[Icon]: New icon <Reward>

### ISSUE THREAD

**Issue by zecarlostorre** [Shopify/polaris-react-archive#11259]
### How will these icons be used?

![Image](https://github.com/Shopify/polaris/assets/55551051/f06a4d7c-e3f8-4504-abfb-17ce85a82ae1)

### Icon name

Reward

### What type of icon set?

Major (20x20)

### Icon description

Used to represent the concept of a reward, prize or loyalty.

[Reward.svg.zip](https://github.com/Shopify/polaris/files/13504431/Reward.svg.zip)

### Icon keywords

rewards, loyalty, incentive, bonus, perks, benefits, appreciation, prize, recognition

### Icon author

José Torre

### Icon Figma link

https://www.figma.com/file/fVIazfJNe3AOJTJmBKgTO9/Polaris-Gen-3-Icons?type=design&node-id=23340-40&mode=design&t=dGBwhRfSWsqGo3dq-4

### Icon SVG code

Attached it above.

**Comment by alex-page** [comment]
Closed by https://github.com/Shopify/polaris/pull/11138/commits/83016e5198baca0bc2df4a3090ed9b0277a9b8fd

**Comment by alex-page** [comment]
Reopened the issue to make it clear this is a part of https://github.com/Shopify/polaris/pull/11138
