### ISSUE TITLE
Props section are not clear

### ISSUE THREAD

**Issue by DaoDucDao** [Shopify/polaris-react-archive#11253]
For some reasons, you just can't put a full description to the props explanation. Maybe you're just lazy.
For example, in Card Props component explanation. You tell me that I can change the background of the card:
![image](https://github.com/Shopify/polaris/assets/91740381/309e0844-9c40-4232-a554-65db23361c84)
But you don't even give me how to, what kind of string to put in, or anything. Oh yea, you did put in the 'ColorBackgroundAlias'. But I can't find it anywhere on google or even in your website. So basically I have to stick only to that color. 
I even tried to go in to the "color" section that you put in the framework. But I can't even figure it out how to use those color or install those into my project. 
If my manager didn't ask me to build our project with your framework. I wouldn't even bother get into it. It wastes a lot of time to find a way to work around those things that are you poor executed. 
Try to learn from Mui or PrimeFace, they are much more user friendly!

**Comment by alex-page** [comment]
@DaoDucDao please read our [CODE_OF_CONDUCT.md](https://github.com/Shopify/polaris/blob/main/.github/CODE_OF_CONDUCT.md) you have not followed:
- "Using welcoming and inclusive language"
- "Showing empathy towards other community members"

**I am going to close this issue.** "We as contributors and maintainers pledge to making participation in our project and our community a harassment-free experience for everyone". If you wish to make a new issue following the code of conduct that would be fine.

See this a final warning. I am not against removing people from our community if they do not follow the code of conduct.
