### ISSUE TITLE
[polaris.shopify.com] Feedback (on /design/depth)

### ISSUE THREAD

**Issue by jessebc** [Shopify/polaris-react-archive#11314]
Some sort of rendering bug in Safari

<img width="958" alt="Screenshot 2023-12-11 at 9 47 06 AM" src="https://github.com/Shopify/polaris/assets/1591075/8eebe18f-bf01-4f76-93d1-f3c899b43e53">

**Comment by tjonx** [comment]
Hey Jesse! 😃 

We recently published an update to the documentation site which should resolve this layout issue.
