### ISSUE TITLE
Icon color token needs to be updated for the Toast component's error state

### ISSUE THREAD

**Issue by bernardojoaogarcia** [Shopify/polaris-react-archive#11337]
<img width="234" alt="Screenshot 2023-12-13 at 5 23 43 PM" src="https://github.com/Shopify/polaris/assets/107587671/525f1b14-b8ef-4066-9e9c-fc5b3ddaa684">

Change the icon color token

**Comment by bernardojoaogarcia** [comment]
Solution: Use token: `text-critical-on-bg-fill`

**Comment by alex-page** [comment]
I am going to fix this up. Thanks @bernardojoaogarcia

**Comment by alex-page** [comment]
This is shipped to shopify/web
