### ISSUE TITLE
Cleanup build filename code added temporarily for backwards compat

### ISSUE THREAD

**Issue by jesstelford** [Shopify/polaris-react-archive#11348]
_Originally posted by @sam-b-rose in https://github.com/Shopify/polaris/pull/11340#pullrequestreview-1782223514_:

> Do we need to support backwards compatibility with the filename? I would think that is something consumers shouldn't rely on being static.
>
> It is certainly reasonable to support this backwards compatibility, but it does add extra overhead and clutter to out build process. We could remove this in the next major, though just wanted to examine if it is really something we'd consider a breaking change.

**Comment by BPScott** [comment]
With the Vite in admin stuff, I'm reasonably sure it no longer bothers to look for esnext code in packages (@vsumner can confirm if that's the case now and/or if it is slated to return)

If that's never coming back  then perhaps there's a world where polaris stops bothering to create the esnext bundle entirely?

**Comment by jesstelford** [comment]
Love it!
