### ISSUE TITLE
How to use Polaris Token to Component

### ISSUE THREAD

**Issue by nafeeur10** [Shopify/polaris-react-archive#11371]
https://polaris.shopify.com/tokens/color

It would be best to use these Polaris-Token for regular components. But didn't find any documentation for this. 

For example:
```
<Card>
      <Text as="h2" variant="bodyMd">
            Content inside a card
      </Text>
</Card>
```

In the card, I don't like the default shadow. Want to use this shadow token `--p-shadow-100`. Does anyone know how to use it?

**Comment by uduma-sonia** [comment]
I know its coming late and you've probably found a solution, but to use tokens you have to download the [shopify-token](https://www.npmjs.com/package/@shopify/polaris-tokens) package.
