### ISSUE TITLE
[Icon]: Update icon DragHandle

### ISSUE THREAD

**Issue by Rusty-UX** [Shopify/polaris-react-archive#11372]
### New DragHandle Icon
Design by @Rusty-UX and @heyjoethomas 

The existing drag handle icon is designed to have visual weight and harmony amongst other icons. We've received feedback from @CynthiaSavard that it appears as decorative or as informational, when really it's UI control. Because it's a UI control, it should be presented as such.

### Approach
New drag handle has tighter spacing, sizing, and mass to make it feel more like a native UI control. We’ve also adjusted the alignment and even though it’s slightly smaller it has better edge clarity rendering on 1x than the current icon.

### Render Tests
![Icons - 2x](https://github.com/Shopify/polaris/assets/4304867/d487ee5c-ce0a-4cd9-9696-0278235e2613)
![Icons - 1x](https://github.com/Shopify/polaris/assets/4304867/9227afe6-cf10-4262-be1f-46aa8fe76cf0)
<img width="721" alt="Render-Test" src="https://github.com/Shopify/polaris/assets/4304867/0ee0639a-42ae-4b2b-87f4-6fafe7e7bdf4">

### Icon name

DragHandle

### What type of icon set?

Major (20x20)

### Icon Figma link

https://www.figma.com/file/CqnyPihLh00JfkpjuDQjQq/Untitled?type=design&node-id=1%3A13359&mode=design&t=vkh6ej4oen6qwIfN-1

### Icon SVG code

```shell
<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M6.75 3.75C6.33579 3.75 6 4.08579 6 4.5V5.5C6 5.91421 6.33579 6.25 6.75 6.25H7.75C8.16421 6.25 8.5 5.91421 8.5 5.5V4.5C8.5 4.08579 8.16421 3.75 7.75 3.75H6.75Z" fill="#8A8A8A"/>
<path d="M6.75 8.75C6.33579 8.75 6 9.08579 6 9.5V10.5C6 10.9142 6.33579 11.25 6.75 11.25H7.75C8.16421 11.25 8.5 10.9142 8.5 10.5V9.5C8.5 9.08579 8.16421 8.75 7.75 8.75H6.75Z" fill="#8A8A8A"/>
<path d="M6 14.5C6 14.0858 6.33579 13.75 6.75 13.75H7.75C8.16421 13.75 8.5 14.0858 8.5 14.5V15.5C8.5 15.9142 8.16421 16.25 7.75 16.25H6.75C6.33579 16.25 6 15.9142 6 15.5V14.5Z" fill="#8A8A8A"/>
<path d="M12.25 3.75C11.8358 3.75 11.5 4.08579 11.5 4.5V5.5C11.5 5.91421 11.8358 6.25 12.25 6.25H13.25C13.6642 6.25 14 5.91421 14 5.5V4.5C14 4.08579 13.6642 3.75 13.25 3.75H12.25Z" fill="#8A8A8A"/>
<path d="M11.5 9.5C11.5 9.08579 11.8358 8.75 12.25 8.75H13.25C13.6642 8.75 14 9.08579 14 9.5V10.5C14 10.9142 13.6642 11.25 13.25 11.25H12.25C11.8358 11.25 11.5 10.9142 11.5 10.5V9.5Z" fill="#8A8A8A"/>
<path d="M12.25 13.75C11.8358 13.75 11.5 14.0858 11.5 14.5V15.5C11.5 15.9142 11.8358 16.25 12.25 16.25H13.25C13.6642 16.25 14 15.9142 14 15.5V14.5C14 14.0858 13.6642 13.75 13.25 13.75H12.25Z" fill="#8A8A8A"/>
</svg>
```

**Comment by isabelxklee** [comment]
hey @Rusty-UX! i'm interested in working on this. 👀 do you mind assigning this issue to me? also i just requested access to the figma icon link from my email, isabelxklee@gmail.com!

**Comment by Rusty-UX** [comment]
Awesome! Thanks so much @isabelxklee - Will follow up with you asap, just need to do a round of review with @CynthiaSavard first!

**Comment by isabelxklee** [comment]
@Rusty-UX awesome, sounds good!

**Comment by Rusty-UX** [comment]
Ok @isabelxklee this one is ready to go. Let me know if you need anything else - granted access to figma.
Is it possible to share a tophatting link once you have something ready?

**Comment by isabelxklee** [comment]
@Rusty-UX perfect! i'll work on this, this week. and yes, will share a tophat link when i'm ready. :-)

**Comment by isabelxklee** [comment]
~~@Rusty-UX heyo! i updated the icon in [this PR](https://github.com/Shopify/polaris/pull/11447), but i can't figure out how to create a link for tophatting. 🤔~~

UPDATE: this issue should be closed since @alex-page has updated this icon in [this commit](https://github.com/Shopify/polaris/commit/f31e4979c7d1399e655883a9594a74f18799e4cb)!
