### ISSUE TITLE
[Icon]: New icon <icon-name>

### ISSUE THREAD

**Issue by nickagin** [Shopify/polaris-react-archive#11393]
### How will these icons be used?

We're updating the existing SFN app icons for release as part of our winter editions... scope of these changes are a redesign to bring it into compliance with our new [1P App Icon System Guidelines](https://www.figma.com/file/JvrrjmEDs7wtwfQjM4VWjH/1P-App-Icon-System?type=design&node-id=10%3A12891&mode=design&t=be2XMU5w91iu2p2o-1).

Proposed new icon [figma file available here](https://www.figma.com/file/hXCo3LfufIxbKvLWD49Wu4/SFN-Logo-Refresh?type=design&node-id=419%3A12587&mode=design&t=uzfUnaFu4kAguk9g-1).

![Service-overview](https://github.com/Shopify/polaris/assets/10213409/6dcfddb3-9a4f-4406-b06a-f9bf5debbb83)

### Icon name

SFN

### What type of icon set?

Unsure

### Icon description

Concept: Used to represent SFN application
Wayfinding: Used to help direct merchants to SFN application.

### Icon keywords

shopify fulfillment network, sfn, fulfillment network

### Icon author

Nick Agin

### Icon Figma link

https://www.figma.com/file/hXCo3LfufIxbKvLWD49Wu4/SFN-Logo-Refresh?type=design&node-id=419%3A12587&mode=design&t=uzfUnaFu4kAguk9g-1

### Icon SVG code

```shell
<svg>...</svg>
```

**Comment by heyjoethomas** [comment]
App icons are not housed in the Polaris repo. @chloerice do you remember where these need to go to get into the nav?

**Comment by chloerice** [comment]
Hey @nickagin 👋🏽 1P and 3P app navigation icons are updated through the Partner Dashboard in the App Setup section once you navigate to the app's detail page from the Apps section. I'll DM you a link (wasn't sure if you wanted this icon live yet, otherwise I would've just done it for you 😅)
