### ISSUE TITLE
[Icon]: New icon <blank>

### ISSUE THREAD

**Issue by laurenip** [Shopify/polaris-react-archive#11398]
### How will these icons be used?

We'd like to use a placeholder icon in cases where CCS merchants can customize their nav items, but forget to select an icon (or make a mistake in the code). Currently we're just displaying a blank square but would like something more concrete that doesn't look like a loading skeleton.
![image (3)](https://github.com/Shopify/polaris/assets/25166454/99ba57e9-543c-4a29-a588-b46861212c81)

### Icon name

Blank

### What type of icon set?

Major (20x20)

### Icon description

Used to represent the spot where an actual icon would appear.

### Icon keywords

blank, placeholder

### Icon author

José Torre (?)

### Icon Figma link

https://www.figma.com/file/hL9XRyHGqU8wUtLdOgs0vI/Archived-%E2%80%93-Polaris-Guidance?type=design&node-id=6228%3A129801&mode=design&t=XUnHDtrRtx1ETWvS-1

### Icon SVG code

```shell
<svg>...</svg>
```

### Are there any other important details?

I've linked the old Blank icon from an old 'Polaris Guidance' library. From what I understand this was mostly for use as an internal placeholder, but José suggested that the team might be able to come up with something a bit nicer to be used in the admin ([see thread here](https://shopify.slack.com/archives/C4Y8N30KD/p1704228475498999)).

**Comment by zecarlostorre** [comment]
Icon is designed, will be available in Figma this week.
<img width="299" alt="Screenshot 2024-01-10 at 18 04 43" src="https://github.com/Shopify/polaris/assets/55551051/5a5048f4-8add-4713-bfde-4c816c9ec444">

Closing this issue, because I added included it in [this issue.](https://github.com/Shopify/polaris/issues/11427)
