### ISSUE TITLE
Disabled option for other form elements

### ISSUE THREAD

**Issue by LeoAref** [Shopify/polaris-react-archive#114]
Now we have *disabled* option for `TextField` and `Select` elements, but other elements like `Checkbox` and `ChoiceList` doesn't have it

I have many use cases that I need to disable/enable programmatically a choice in `ChoiceList`, the same goes for `Checkbox`, `RadioButton`, ...

**Comment by LeoAref** [comment]
I can help with PR implementing that

**Comment by lemonmade** [comment]
Thanks for the issue, @LeoAref. `Checkbox` and `RadioButton` actually do support `disabled`, we just have not documented them:

https://github.com/Shopify/polaris/blob/master/src/components/Checkbox/Checkbox.tsx#L20
https://github.com/Shopify/polaris/blob/master/src/components/RadioButton/RadioButton.tsx#L14

`ChoiceList` does not currently support `disabled` choices, but this will be part of the next version.

I've added an issue to our internal tracker to update the missing documentation, and will close this issue once we release a version with the fix.

**Comment by LeoAref** [comment]
@lemonmade Thanks, waiting for the new release 🙂
