### ISSUE TITLE
Support Node v18

### ISSUE THREAD

**Issue by blanklob** [Shopify/polaris-react-archive#11415]
## Feature request summary

Support Node 18 most dev envs right now have standarized Node 18.

```bash

01:44:52.187 | npm WARN EBADENGINE   package: '@shopify/polaris@12.6.0',
-- | --
01:44:52.187 | npm WARN EBADENGINE   required: { node: '^16.17.0 \|\| >=18.12.0' },
01:44:52.187 | npm WARN EBADENGINE   current: { node: 'v18.0.0', npm: '8.6.0' }
01:44:52.187 | npm WARN EBADENGINE }
01:44:52.187 | npm WARN EBADENGINE Unsupported engine {
01:44:52.187 | npm WARN EBADENGINE   package: '@shopify/polaris-icons@7.13.0',
01:44:52.188 | npm WARN EBADENGINE   required: { node: '^16.17.0 \|\| >=18.12.0' },
01:44:52.188 | npm WARN EBADENGINE   current: { node: 'v18.0.0', npm: '8.6.0' }
01:44:52.188 | npm WARN EBADENGINE }
01:44:52.190 | npm WARN EBADENGINE Unsupported engine {
01:44:52.192 | npm WARN EBADENGINE   package: '@shopify/polaris-tokens@8.4.0',
01:44:52.192 | npm WARN EBADENGINE   required: { node: '^16.17.0 \|\| >=18.12.0' },
01:44:52.192 | npm WARN EBADENGINE   current: { node: 'v18.0.0', npm: '8.6.0' }
01:44:52.192 | npm WARN EBADENGINE }


```

## Rationale

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s :+1: upvotes to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by aaronccasanova** [comment]
We currently support [Node.js `^16.17.0` or `>=18.12.0`](https://github.com/Shopify/polaris/blob/2bcc7bda594c4339f140d829b0e46a1daf3d33e5/documentation/Nodejs%20support.md#where-do-we-put-nodejs-versions). I'm reading the referenced warning logs as your current Node.js doesn't meet the minimum requirement of `>=18.12.0`. Are you able to expand more on your issue?

**Comment by blanklob** [comment]
Oh never mind i read the logs wrong thanks for the answer, Im closing this ticket.
