### ISSUE TITLE
[Icon]: 5 new icons <PersonExit> <CursorBanner> <CursorOptions> <Blank> <BlankFilled> + 3 icon updates <Envelope> <Domain> <DragHandle>

### ISSUE THREAD

**Issue by zecarlostorre** [Shopify/polaris-react-archive#11427]
### How will these icons be used?

⭐️NEW - The first 3 will be used in settings pages, the other two will be used as a placeholder for navigation items.

💅 POLISH - These icons had inconsistencies/problems that needed to be fixed.

### Icon name

See above

### What type of icon set?

Major (20x20)

### Icon description

`PersonExit` Represents the concept of opting out, or exiting.
Keywords: Opt-out, User, Logout, Exit, Sign out, Leave, Disconnect

`CursorBanner` Represents a cookie/permissions banner
Keywords: Cursor, Cookie, Permissions, Banner, Consent, Agreement

`CursorOptions` Represents the act of selecting options
Keywords: Selection, Options, Choices, Settings, Preferences

`Blank` Represents the absence of an icon
Keywords: Empty, Undefined, Null

`BlankFilled` Represents the absence of an icon
Keywords: Empty, Undefined, Null

### Icon keywords

I added that above too.

**Comment by zecarlostorre** [comment]
@alex-page @lgriffee I made this issue to group some icon updates and additions that made their way to my desk.

let me know if we can include these in the big icon update, and if you need anything from me.

SVGs below. I separated them in two forders, so it's easier to know which ones are new, and which ones are updates over existing icons.
[Icons.zip](https://github.com/Shopify/polaris/files/13891278/Icons.zip)

**Comment by alex-page** [comment]
@zecarlostorre these have been added with this commit https://github.com/Shopify/polaris/pull/11138/commits/f31e4979c7d1399e655883a9594a74f18799e4cb

**Comment by zecarlostorre** [comment]
Thank you @alex-page. Absolute legend!

**Comment by alex-page** [comment]
This is shipped
