### ISSUE TITLE
[polaris.shopify.com] Feedback (on /components/deprecated/navigation)

### ISSUE THREAD

**Issue by cosmasemerah** [Shopify/polaris-react-archive#11459]
The navigation component is showing deprecated 

https://polaris.shopify.com/components/navigation 
redirects to 
https://polaris.shopify.com/components/deprecated/navigation

**Comment by alex-page** [comment]
@cosmasemerah this is intentional please take a look at this issue for context https://github.com/Shopify/polaris/issues/11460
