### ISSUE TITLE
[Modal] Where can I find documentation for Polaris Modals?

### ISSUE THREAD

**Issue by ShawnChenXHC** [Shopify/polaris-react-archive#11458]
## Issue summary

* I am building with Shopify Polaris components, and I wanted to read documentation for the `Modal` component

## Expected behavior

* I can find documentation on Polaris `Modal`: what props it uses, examples, things to watch out for, etc.
* Specifically, I would like to see this content and others like it on polaris.shopify.com: 
  * https://github.com/Shopify/polaris/blob/main/polaris.shopify.com/pages/examples/modal-default.tsx
  * https://github.com/Shopify/polaris/blob/main/polaris.shopify.com/pages/examples/modal-large.tsx

## Actual behavior

* I am re-directed to https://polaris.shopify.com/components/deprecated/modal, where the only message is "Use the App Bridge Modal API instead"

## Steps to reproduce the problem

1. Go to https://polaris.shopify.com/
2. Look for Modal documentation
3. See that no documentation exists

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 11 and up
- Browser: Any
- Device: Any
- Operating System: Any

**Comment by kyledurand** [comment]
Can we move these concerns to the more general issue [here](https://github.com/Shopify/polaris/issues/11460)?

There are many benefits to using app bridge over Polaris for Frame related components (Modal, Toast, Loading etc...)

Please reply in that issue and let us know how we can better help with this transition
