### ISSUE TITLE
Uneven outside margin in ActionList

### ISSUE THREAD

**Issue by ouellettejordan** [Shopify/polaris-react-archive#11484]

**Comment by alex-page** [comment]
@ouellettejordan can you add a screenshot of the issue and what it should look like so we can fix this quickly?

**Comment by ouellettejordan** [comment]
@alex-page oops, I accidentally created two issues for this. The [real issues](https://github.com/Shopify/polaris-internal/issues/1439) has screenshots and more details included. I'll close this issue in favour of the other one.
