### ISSUE TITLE
Add subtitle to the PageSkeleton component

### ISSUE THREAD

**Issue by ryanrphillips** [Shopify/polaris-react-archive#11494]
## Feature request summary

The Page component has title and subtitle props and we have quite a few cases where these are static values. However, the PageSkeleton component only supports the title prop, causing the page to jump when the subtitle loads in as part of the Page component.

## Rationale

The primary reason for adding this is to achieve better parity with the Page component and prevent the page from jumping.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s :+1: upvotes to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by alex-page** [comment]
@ryanrphillips that sounds logical to me. If you wanted to contribute this please do.
