### ISSUE TITLE
[polaris.shopify.com] Feedback (on /tokens/shadow)

### ISSUE THREAD

**Issue by bravilordesign** [Shopify/polaris-react-archive#11517]
Hey, I know I'm not part of your organisation, but I'm working on our own design system and thus looking at other design systems on how its documented. And I've noticed that at on some pages, including the tokens page, only light mode values are displayed. Is this because dark mode isn't supported for your client facing platform? Or is this not documented yet? 

Also, I'm curious to see how shadows are handled for dark mode (since the contrast between shadow and surface is less)

Cheers!

**Comment by heyjoethomas** [comment]
We do not support dark mode across the admin. There are a couple pieces or dark UI but Polaris as a whole only ships in 1 color mode.
