### ISSUE TITLE
Polaris for Vue.JS

### ISSUE THREAD

**Issue by cbolard** [Shopify/polaris-react-archive#11553]
## Feature request summary

It would be so great to have a version for Vue 3 as many devs do not use React. Please.

## Rationale

I have to re-design a project and find your design system perfect. 
I was planing to launch a shopify extension also with this project.
Getting a vue version could definetely bring a lot of indie devs.

**Comment by heyjoethomas** [comment]
Polaris is not a generic open sourced library. We are specifically built for the Shopify Admin which is a React application. So we won't be rebuilding and maintaining a library in a different language.

**Comment by juzser** [comment]
@cbolard You can try our Polaris Vue version here: https://github.com/ownego/polaris-vue
That's following Shopify Polaris v12, the core is based on Shopify version, so 99% matched. 
The doc is also similar. 

Vue is awesome!
