### ISSUE TITLE
Receiving is broken

### ISSUE THREAD

**Issue by raquelbreternitz** [Shopify/polaris-react-archive#11608]
### Summary

![Screenshot 2024-02-15 at 2 14 22 PM](https://github.com/Shopify/polaris/assets/13204374/b574c951-1930-471f-8985-85594d649013)

### Expected behavior

Normal sized cells / product name wrapping correctly

### Actual behavior

You can see ^

### Steps to reproduce

Go to purchase order or transfer > click receive items

### Browser

Safari

### Device
MacBook

**Comment by alex-page** [comment]
I tried to replicate this in Chrome and Safari and I couldn't :(

![Screenshot 2024-02-16 at 1 08 59 pm](https://github.com/Shopify/polaris/assets/19199063/5e2d8a07-c1c5-45ce-88d7-67084bb597c4)

**Comment by raquelbreternitz** [comment]
> I tried to replicate this in Chrome and Safari and I couldn't :(

Weird, I also tried to replicate and now it's fine. I must have hit some weird render bug for a fleeting moment. Thanks Alex!
