### ISSUE TITLE
IndexTable footer misplaced when selecting rows

### ISSUE THREAD

**Issue by lukecharle** [Shopify/polaris-react-archive#11623]
### Summary

When you select/check rows, the footer which shows the count selected isn't inside the table

<img width="1093" alt="Screenshot 2024-02-19 at 21 42 17" src="https://github.com/Shopify/polaris/assets/115987937/f8f33162-0740-4e1d-931b-0f47bb890260">

### Expected behavior

Footer to be inside table

### Actual behavior

Footer is at the bottom of the page

### Are you using React components?

Yes

### Polaris version number

12.0.0

**Comment by heyjoethomas** [comment]
Hey @lukecharle I am not seeing this when using the `IndexTable` in my own store. The footer properly sticks to the bottom of the table. I would make sure you are using the latest version of Polaris as a fix might have already shipped for this. 

<img width="1129" alt="Screenshot 2024-02-23 at 12 04 24 PM" src="https://github.com/Shopify/polaris/assets/5749440/4b98600c-6df0-4229-8d18-a0e984166e17">
