### ISSUE TITLE
Frame causes sidebar overlap on apps

### ISSUE THREAD

**Issue by mmapplebeck** [Shopify/polaris-react-archive#11694]
### Summary

A [recent PR](https://github.com/Shopify/polaris/pull/11628) that changed margin to padding on `Frame` styling caused a regression in Admin. Before, `Frame` components with the `sidebar` prop properly made room for the universal sidebar on app pages. Now, the `Frame` does not make room for the universal sidebar on app pages, even though the `sidebar` prop is set `true`.

### Expected behavior

Frame with sidebar should make room for the universal sidebar. See example below with padding changed to margin (undoing the change in the offending PR):

https://screenshot.click/06-40-xofhg-ionqi.png

### Actual behavior

Frame with sidebar does not make room for the universal sidebar:

https://screenshot.click/06-45-1tp2k-khcid.png

### Steps to reproduce

1. Open Admin 
2. Open universal sidebar by either:
  - Opening the Persistent Guide by clicking on a CTA in a Home Guide
  - Opening Sidekick
3. Go to an app page (e.g. Point of Sale, Email, etc.)
4. Verify that the `Frame` padding used to offset for the sidebar is not respected

### Are you using React components?

None

**Comment by alex-page** [comment]
@mmapplebeck are you able to contribute a fix?

**Comment by mmapplebeck** [comment]
> @mmapplebeck are you able to contribute a fix?

Yeah let me see if I can get a fix in
