### ISSUE TITLE
 Update onClick Prop TypeScript Definition to Include Event Argument in BaseButton Interface

### ISSUE THREAD

**Issue by daviareias** [Shopify/polaris-react-archive#11701]
### Summary

In the current Polaris version, the TypeScript definition for the onClick prop in the BaseButton interface does not specify that it passes the React event argument to the callback function (onClick?(): unknown;). This is misleading as the actual behavior does include passing the React event. The request is to update the TypeScript definition to accurately reflect the behavior, enhancing developer experience and type safety.

### Expected behavior

The onClick TypeScript definition should explicitly include the event argument to inform developers that the callback will receive the React event. This change will align the documentation with the actual behavior and improve type checking and developer expectations when using the Button component.

### Actual behavior

The TypeScript definition suggests that the onClick callback does not receive any arguments, which does not match the actual implementation where the React event is passed to the callback. This discrepancy can lead to confusion and improper use of the onClick prop in TypeScript projects.

#### Example where this might lead to confusion

``` typescript
const [text,setText] = useState("");
const handleClick = (newText="") => setText(newText);

<BlockStack gap="100">
<Text as="p">Your text here:</Text>
<Text as="p" fontWeight="bold" tone="success">{text}</Text>
  <Button onClick={()=>handleClick("A piece of text that gets easily written in a click")}>
     Add text in a click
 </Button>
  <Button 
  // This will pass an object instead of a string and throw an error in React
  // we'll get no warning because the type in Polaris is incorrectly set to  onClick?(): unknown;
  onClick={handleClick}
    >Clear text</Button>
</BlockStack>
```

#### Sugested Change:
Update the onClick prop definition in src/types.d.ts within the BaseButton interface to:

``` typescript
/** Callback when clicked, receives the click event */
onClick?(event: React.MouseEvent<HTMLButtonElement, MouseEvent>): void;
```

### Steps to reproduce

  [polaris sandbox reproduction](https://polaris.shopify.com/sandbox/preview?code=N4Igxg9gJgpiBc4IDsDOAXABAbXTAHugDSozoAqB6AupgLyYCupAyugIZ4AUAOiHwEoA3D2SQ0WABbtkUADYwAwnICWYANb1MXZDADulQnT6D6APkykKVHfsPpho0QB4AQhHyYAtu3wB1FSh0SWMQAFYABgiAB3w%20TGj2KCgVZABzUMiIvjMXVzkIDTZ2DUw09mjQgEYonJd7THZUUOicgE0IRgAnTDxCTEkYLph4ZwB6e1zkZwamlviAMxR0PxgVNMl0UIAjCDkoePQUGFDURjAwGFRUHOA%209ABfccnRTEw3RnQj5EwUZTV1HRgFwBHQzNJZAp-hpeCAAIIJFQwS6-Ba9Ki9aRYNJkVCYGBNFRyACemD0XRUXxgP1SjUwYFUGkEDymbzZcOS6P6tPY9MZ6le41cn2%20rPewq%20KEwr0wYzGmHIkhUeL0RLkCSaeJkv22ACtkVhUhgCVBUXSMBT0o1ZJiuhA9Nb8V07T1aQAlAlgdAyuVkmAAcjk6pxWGQEDJ7C6yFSaUw22R7GYMExyfQxOiydpAAU9pHlZh86lIM6DSTLGReuHfshoeoAPwg%20BMZDqMN6ZAiH7V2tAiHyJT8h4yt5mZQEnr3IUilBTIUFIocDSzsbufBmEBEEDBGBeOCIefsBTwakgB5AA)

   1. Create a TypeScript project using Polaris most recent version.
   2. Implement a Button component with an onClick prop.
   3. Notice the TypeScript definition suggests no arguments should be passed to the callback, contrary to the actual behavior.

### Are you using React components?

Yes

### Polaris version number

12.11.0

### Browser

Not applicable

### Device

Not applicable

**Comment by pklitscher** [comment]
+1 
We have some buttons where it's necessary to use `stopPropagation()`. To make our code "type safe" we have had to hack around it and make the event optional. However, it would be good to reliably know if this event is being passed or not. We tell the compiler it is. But if it were suddenly removed, we wouldn't know unless we check every time. This would degrade user experience.

**Comment by daviareias** [comment]
Here's an easy workaround until they decide to fix this, it should work with any framework.

You just have to find your global d.ts declaration files, in nextJS it used to be additional.d.ts, not sure about remix, in vite is vite.env.d.ts:

```typescript
import { MouseEvent } from "react";

declare module "@shopify/polaris/build/ts/src/components/Button/Button" {
    export interface ButtonProps {
        onClick?(event: MouseEvent<HTMLButtonElement, MouseEvent>): void;
    }
}
```
