### ISSUE TITLE
[Icon] Change 'TeamIcon' name to 'GroupIcon'

### ISSUE THREAD

**Issue by heyjoethomas** [Shopify/polaris-react-archive#11715]
### Summary

The team icon needs a more generic name to be used in the new Segments experience.

### Actual behavior

Wrap animated gifs/videos in a details tag:
<details>
  <summary>Summary of your gif(s)</summary>
  <img src="..." alt="Description of what the gif shows">
</details>

### Steps to reproduce

[Link to sandbox]()
1. 
2.
3.

### Are you using React components?

None

**Comment by alex-page** [comment]
@heyjoethomas we need to align name changes with checkout.
