### ISSUE TITLE
Paginated Index Table Bulk Actions Selects All Rows by Default

### ISSUE THREAD

**Issue by thelaughing-man** [Shopify/polaris-react-archive#11786]
### Summary

Using an IndexTable with bulk actions and pagination, the default behavior is to select all rows instead of the current page's rows. The documentation does not discuss select all options. There is a SelectionType listed under handleSelectionChange from useIndexResourceState but no reference on how to use it. How does one make the default behavior of select all on a paginated index table only select the current page's rows?

### Expected behavior

When clicking the select all button on a paginated index table, it should only select the current page's rows. The text already shows up to select all rows in the table so it is implying you've only selected the current page. Or document how to use the SelectionType to change the default behavior. 

### Actual behavior

Clicking the checkbox selects all items in the list and says click here to select all.

![image](https://github.com/Shopify/polaris/assets/3099641/c901b601-c684-49c1-9e7a-925a3888cdaa)

### Steps to reproduce

Any paginated indextable with bulk actions. 

### Are you using React components?

Yes

### Polaris version number

5.10.2

### Browser

Chrome 122.0.6261.113

### Device

Dell Laptop

**Comment by dizzyjaguar** [comment]
any update on this? I'm also facing this
