### ISSUE TITLE
[IndexFilters] Filter popover does not close when clicked outside of when the Index is within a Modal

### ISSUE THREAD

**Issue by brandon-yetman** [Shopify/polaris-react-archive#11850]
### Summary

If the index table / filters component is wrapped by a modal (e.g. my use-case, and index table in the Settings section of Admin, which afaict is a modal component), the popover does not close when clicked outside of. In contrast, the Sort popover does close when clicked outside of.

cc @Shopify/polaris-eng 

### Expected behavior

Filter popover should close when clicked outside of.

### Actual behavior
<details>
  <summary>Video recording</summary>

https://github.com/Shopify/polaris/assets/51451780/7002ed27-dbe3-41f5-baa1-8029f4c0628a

  <img src="..." alt="Description of what the gif shows">
</details>

### Steps to reproduce

[Link to sandbox](https://codesandbox.io/p/sandbox/eager-dew-25k74k?file=%2FApp.tsx%3A334%2C16&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluisnly200063b6lqoof97yn%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluisnly200023b6lup339k6t%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluisnly200033b6lgdqwspat%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluisnly200053b6lqi9ja9ct%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluisnly200023b6lup339k6t%2522%253A%257B%2522id%2522%253A%2522cluisnly200023b6lup339k6t%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clukinjza00023b6jtw3jhgyi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A334%252C%2522startColumn%2522%253A16%252C%2522endLineNumber%2522%253A334%252C%2522endColumn%2522%253A16%257D%255D%252C%2522filepath%2522%253A%2522%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clukinjza00023b6jtw3jhgyi%2522%257D%252C%2522cluisnly200053b6lqi9ja9ct%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluisnly200043b6lcznwr3pf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cluisnly200053b6lqi9ja9ct%2522%252C%2522activeTabId%2522%253A%2522cluisnly200043b6lcznwr3pf%2522%257D%252C%2522cluisnly200033b6lgdqwspat%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cluisnly200033b6lgdqwspat%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
1.  Add any filter
2. Try to click anywhere else to close the filter popover

### Are you using React components?

Yes

### Polaris version number

latest

### Browser

Chrome

### Device

Macbook

**Comment by alex-page** [comment]
@brandon-yetman are you able to contribute a fix?

**Comment by brandon-yetman** [comment]
@alex-page I'm happy to try when I have some bandwidth, but between a tight project deadline and upcoming vacation I probably won't have time to dive into it for ~a month

**Comment by sophschneider** [comment]
@brandon-yetman I think if you set the prop `closeOnChildOverlayClick={true}` on `IndexFilters`, it'll work https://codesandbox.io/p/sandbox/eager-dew-25k74k?file=%2FApp.tsx%3A360%2C30

**Comment by brandon-yetman** [comment]
Solved by Sophie's suggested fix :)
