### ISSUE TITLE
[EmptyStateExampleEmptyStateDefault]

### ISSUE THREAD

**Issue by teophilus** [Shopify/polaris-react-archive#11856]
### Summary

Empty State Image is opacity is set to 0 and never gets set to 1

### Expected behavior

Empty state image opacity should be set to 1

### Actual behavior

Wrap animated gifs/videos in a details tag:
<details>
  <summary>Summary of your gif(s)</summary>
  <img src="..." alt="Description of what the gif shows">
</details>

### Steps to reproduce

[Link to sandbox]()
1. 
2.
3.

### Are you using React components?

None

### Polaris version number

12.26.1

### Browser

Chrome

### Device

MacOS

**Comment by laurkim** [comment]
Thanks for creating an issue @teophilus!

Do you mind providing a sandbox for the issue you're running into with opacity? EmptyState image starts at `opacity: 0` and transitions to `opacity: 1` once the image is [loaded](https://github.com/Shopify/polaris/blob/e2909baa94462c0f408964c213a92e1eadc50203/polaris-react/src/components/EmptyState/EmptyState.tsx#L57).

**Comment by teophilus** [comment]
sure, it's not working on the docs page:
https://polaris.shopify.com/components/layout-and-structure/empty-state

**Comment by laurkim** [comment]
Thanks, I'll update on upcoming fixes soon 👍

**Comment by laurkim** [comment]
Hey @teophilus thanks for flagging the opacity issue. A fix has been merged and the docs page will be fixed in the next release 👍
