### ISSUE TITLE
Getting useLayoutEffect errors in SSR in Remix with the Remix Shopify App Template

### ISSUE THREAD

**Issue by muchisx** [Shopify/polaris-react-archive#11862]
https://github.com/Shopify/polaris/blob/a89e61478fb7c5f588021e542101aba8a3898ec8/polaris-react/src/components/IndexTable/IndexTable.tsx#L7-L8

I checked the line here 👆🏻, Maybe better to go back to use `useIsomorphicLayoutEffect ` being required everywhere ?

![image](https://github.com/Shopify/polaris/assets/34131801/bbc8d47e-b167-4bcb-8ab7-27d46eac57ce)

**Comment by oliversd** [comment]
Same problem here updated to last version using IndexTable with Remix.

 "@shopify/polaris": "^13.0.0",

Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded
into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the
intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client.
 See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
09:50:55 │ remix      │     at IndexTableBase

**Comment by kyledurand** [comment]
cc @jesstelford it looks like it might have been you that changed from `useIsomorphicLayoutEffect` to `useLayoutEffect` here. Do you have a bit of time to investigate?

**Comment by saifulapm** [comment]
Any update on this ?

**Comment by jesstelford** [comment]
Thanks for the report folks, the error messages & prior investigation made it much easier to track down!

- [Minimal reproduction showing the warning](https://stackblitz.com/edit/remix-run-remix-pgkhtu?file=app%2Froutes%2F_index.tsx)
- [Appears to have been introduced by this change](https://github.com/Shopify/polaris/pull/11617/files#diff-f6cb4e5d74c6a93ab30c612e372af0addc595731b01607a4fd90cb5406cef263L440-R434)

**Comment by jesstelford** [comment]
I've got a fix open in #11950 👍

**Comment by jesstelford** [comment]
The fix will be shipped in the following release: https://github.com/Shopify/polaris/pull/11997

**Comment by Himanshu029** [comment]
Hi @all team member 

Same issue i'm facing after update shopify version.
Any body help me how can i resolve this issue.

![Image](https://github.com/user-attachments/assets/dbf79eb9-2a86-4461-bc94-5f7623f2d863)


Please give me solution on this mail id [himanshu.jangir@ascuretech.com](mail:himanshu.jangir@ascuretech.com)

**Comment by huykon** [comment]
I have same issue warning in `"@shopify/polaris": "^12.0.0"`

**Comment by yongyi520** [comment]
> I have same issue warning in `"@shopify/polaris": "^12.0.0"`

I also have the same issue

**Comment by yamarkz** [comment]
> I have same issue warning in "@shopify/polaris": "^12.0.0"
> 
> I also have the same issue

I also have the same issue

**Comment by ClaudiuCeia** [comment]
It will continue happening until you bump polaris to at least `v13.4.0`. It requires node v20 so make sure you then update your Dockerfile too (if you're using the Shopify app template):

```
- FROM node:18-alpine
+ FROM node:20-alpine
```

**Comment by Obihan98** [comment]
> It will continue happening until you bump polaris to at least `v13.4.0`. It requires node v20 so make sure you then update your Dockerfile too (if you're using the Shopify app template):
> 
> ```
> - FROM node:18-alpine
> + FROM node:20-alpine
> ```

This one worked for me, thank you for your help!
