### ISSUE TITLE
[Bug: IndexTable] Small click area where it's still possible to check disabled table rows

### ISSUE THREAD

**Issue by stefanlegg** [Shopify/polaris-react-archive#11895]
### Summary

The div that wraps checkboxes has a small clickable area that still triggers selection when row are disabled.

### Expected behavior

Disabled rows should not be selectable at all

### Actual behavior

![toggle.gif](https://github.com/Shopify/polaris/assets/510085/38f5f97c-2b43-482e-917e-5ccde704c83d)

### Steps to reproduce

[Link to sandbox](https://codesandbox.io/p/sandbox/broken-currying-xxmz4k?file=%2Findex.html&module=App.tsx)
1. Click very close to the edge of the disabled checkbox
2. Observe that you can still toggle the checked state

### Are you using React components?

Yes

**Comment by jesstelford** [comment]
Thanks for the report @stefanlegg!

I've submitted a fix in #11897

Here's a sandbox with the fix included: https://codesandbox.io/p/sandbox/gallant-lederberg-62fw8j - let me know if that's working for you 👍
