### ISSUE TITLE
Button Component Hover State Persistence on Mobile When Disabled

### ISSUE THREAD

**Issue by philippeaka** [Shopify/polaris-react-archive#12002]
### Summary

We have identified an issue with the Button component. On mobile devices the hover state classes are not consistently removed when the button is disabled. This creates an unintended visual effect, potentially confusing users about the button's functionality

### Expected behavior

When the button is disabled, all hover state classes should be removed immediately, ensuring the button correctly reflects its disabled status without any hover state styling.

### Actual behavior

This is the actual behavior on mobile devices

https://github.com/Shopify/polaris/assets/89400776/b9e1855c-b074-41aa-a5c6-9ea261ada7f4

Code : 

```javascript
  const [loading, setLoading] = useState(false);
  <Button
      disabled={loading}
      loading={loading}
      onClick={() => setLoading(!loading)}
      variant="primary"
    >
      Add product
  </Button>
```

### Steps to reproduce

Link to sandbox : [sandbox](https://codesandbox.io/p/sandbox/crazy-sun-vpszf9?file=%2FApp.tsx%3A5%2C52&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clw6erqno00063b6ix9uueiwv%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clw6erqno00023b6i3iucvezo%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clw6erqno00033b6i347btfkj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clw6erqno00053b6iom18mtbq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clw6erqno00023b6i3iucvezo%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw6erqno00013b6is1bw1oxa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clw6fz6g400023b6iwutj3nfz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A52%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A52%257D%255D%252C%2522filepath%2522%253A%2522%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clw6erqno00023b6i3iucvezo%2522%252C%2522activeTabId%2522%253A%2522clw6fz6g400023b6iwutj3nfz%2522%257D%252C%2522clw6erqno00053b6iom18mtbq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw6erqno00043b6in7859r5a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clw6erqno00053b6iom18mtbq%2522%252C%2522activeTabId%2522%253A%2522clw6erqno00043b6in7859r5a%2522%257D%252C%2522clw6erqno00033b6i347btfkj%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clw6erqno00033b6i347btfkj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

 1. Access the link on a mobile device 
 2. Click on the button 

### Are you using React components?

Yes

### Device

iPhone 15 Pro

**Comment by liliangrong** [comment]
I encountered the same issue
