### ISSUE TITLE
Migrate from Legacy Stack to InlineStack

### ISSUE THREAD

**Issue by mhlozek** [Shopify/polaris-react-archive#12001]
### Summary

I would like to migrate from Legacy Stack / Stack Item to InlineStack, but I don't know how to migrate StackItem with `fill` prop.

There are no "Items" in InlineStack. Should I use a div element with inline style flex-grow: 1 instead?

### Are you using React components?

None

**Comment by nullndr** [comment]
The way I am doing this is using two `<InlineStack/>`:

```jsx
<InlineStack align="space-between">
  <div>Foo</div>  
  <InlineStack align="end" gap="200">
    <div>Bar</div>
    <div>Foobar</div>
  </InlineStack>
</InlineStack>
```
