### ISSUE TITLE
IndexTable loading prop broken, always loading

### ISSUE THREAD

**Issue by FrankHeijden** [Shopify/polaris-react-archive#12174]
Hey, I think this PR did something that broke the loading state on IndexTable's. For me, v13.1.2 works nicely with the loading state, but with v13.2.0-v13.4.0 the loading state seems to be always present, no matter if the loading prop is even being specified.

_Originally posted by @FrankHeijden in https://github.com/Shopify/polaris/issues/11805#issuecomment-2138031753_

**Comment by FrankHeijden** [comment]
@yurm04

**Comment by mrmarufpro** [comment]
![Image](https://github.com/user-attachments/assets/48e7d1a9-fc35-43f7-a27f-c9b5174bf239)

Still existing on version 

```json 
{
  "@shopify/polaris": "13.9.5"
} 
```

@yurm04
