### ISSUE TITLE
Drag and drop inside of app bridge v4 max modal

### ISSUE THREAD

**Issue by TarikVelic** [Shopify/polaris-react-archive#12193]
### Summary

Drag and drop does not work for me, not a single package inside the app bridge modal.

https://d.pr/v/1XpGNL

And because we are chasing BFS, we need to have this inside of max modal

### Expected behavior

I can understand that styled components don't work, but this drag-and-drop functionality is really irreplaceable for me. Also, I tried to use prop 'src' with the route, but the 'src' URL doesn't seem to fetch API data inside of it.

### Actual behavior

///

### Steps to reproduce

1.  add app bridge modal
2. put component inside of app bridge v4 modal
3. thats it

### Are you using React components?

Yes

### Polaris version number

12.00

### Browser

Chrome

### Device

Laptop

**Comment by noelgoodday** [comment]
Cross posted in AppBridge GitHub: [https://github.com/Shopify/shopify-app-bridge/issues/364](https://github.com/Shopify/shopify-app-bridge/issues/364)

**Comment by TarikVelic** [comment]
I saw that, I was hoping I might get a quick answer if I ask here too lol, because I can't find a solution for this problem anywhere right now

**Comment by V-SpringT** [comment]
@TarikVelic Have you solved this problem?

**Comment by TarikVelic** [comment]
@@V-SpringT nope, as you can see shopify doesnt do anything to fix this 5month old issue :)
