### ISSUE TITLE
Popover Activator not aligned in an InlineStack

### ISSUE THREAD

**Issue by svintit** [Shopify/polaris-react-archive#12484]
### Summary

https://codesandbox.io/p/sandbox/async-sound-77wcy4?file=%2FApp.tsx%3A8%2C11

The icon in the popover is not vertically aligned correctly when the button variant is not primary or secondary (any button variant with no background).

<img width="697" alt="image" src="https://github.com/user-attachments/assets/89e7ef44-8451-4f17-8616-674319c68b54">

### Expected behavior

Should be vertically aligned. 

### Actual behavior

Not aligned

### Steps to reproduce

https://codesandbox.io/p/sandbox/async-sound-77wcy4?file=%2FApp.tsx%3A8%2C11

### Are you using React components?

Yes

### Polaris version number

13.21.1

### Browser

Chrome

**Comment by svintit** [comment]
@Shopify/polaris-eng

**Comment by sophschneider** [comment]
this is intentional on [storybook](https://storybook.polaris.shopify.com/?path=/story/all-components-button--all)

are you able to use the `plain` variant?

**Comment by svintit** [comment]
> this is intentional on [storybook](https://storybook.polaris.shopify.com/?path=/story/all-components-button--all)
> 
> are you able to use the `plain` variant?

Hey! `plain` would also work, but it doesn't work, same issue 😓 

https://codesandbox.io/p/sandbox/async-sound-77wcy4?file=%2FApp.tsx%3A32%2C22

**Comment by sophschneider** [comment]
oops yeah sorry! If you wrap either `plain` or `tertiary` in a flex wrapper like `InlineStack` it should be aligned as a workaround. This is a known issue
