### ISSUE TITLE
Icons on Orders index have inconsistent alignment.

### ISSUE THREAD

**Issue by hellicarusprime** [Shopify/polaris-react-archive#12527]
### Summary

The icons used to show additional information about an order e.g. customer notes, fraud risk etc are misaligned when multiple are present on multiple orders.

<img width="59" alt="image" src="https://github.com/user-attachments/assets/aa2e2356-0d67-4eb4-a228-84e2a8f74e4d">

### Actual behavior

Wrap animated gifs/videos in a details tag:
<details>
  <summary>Summary of your gif(s)</summary>
  <img src="..." alt="Description of what the gif shows">
</details>

### Steps to reproduce

Visit an orders index with multiple icons on multiple orders.

### Are you using React components?

None

### Browser

Chrome Version 127.0.6533.72

### Device

MacBook Pro

**Comment by alex-page** [comment]
This is an implementation issue with how the icon is used in the index table. Polaris can't fix this.
