### ISSUE TITLE
Update `ActionListItemDescriptor.content` to type `React.ReactNode`

### ISSUE THREAD

**Issue by duprasa** [Shopify/polaris-react-archive#12580]
### Summary

Updating the `ActionListItemDescriptor.content` (used in the [Action List](https://polaris.shopify.com/components/lists/action-list?example=action-list-in-a-popover)) to be more dynamic would allow to support custom emoji and other small inline images that help visually describe a list item.

![Image](https://github.com/user-attachments/assets/66e7b385-596b-4044-8cea-787548ede449)

### Option 1: using `prefix` (not viable)

Polaris currently supports `prefix` which seems like the right prop to use, however this has 2 major limitations that doesn't make it a viable option in most cases:
- It is rendered beside the help text
- Its width is fixed which make the spacing between the icon and text inconsistent unless using compatible icons.

```
    // prefix method
    {
        content: '•••• 4444 (using prefix)',
        prefix:<Image src="https://static-00.iconduck.com/assets.00/mastercard-icon-2048x1225-3kb6axel.png" height="20"/>,
        helpText: (
          <BlockStack gap="100">
            <InlineStack gap="200">
            </InlineStack>
              <Text as="span">Selected at checkout</Text>
          </BlockStack>
        )
     },
```

This make it not an option for my case.

### Option 2: using `helpText` (viable, but hacky)

With some digging however I found this workaround that we can use `helpText` to render the entire item. This is incredibly powerful and allows me to do what I want. This does however feel a bit like a hack. We also need to pass in an empty string to content.

```
    // Hacky helpText method
    {
        content: '',
        helpText: (
          <BlockStack gap="100">
            <InlineStack gap="200">
              <Image src="https://static-00.iconduck.com/assets.00/mastercard-icon-2048x1225-3kb6axel.png" height="20"/>
              <Text variant="bodyMd" tone="base" as="span">
                •••• 5555 (using hack)
              </Text>
            </InlineStack>
              <Text as="span">Selected at checkout</Text>
          </BlockStack>
        )
     }
```

[Here is a sandbox](https://polaris.shopify.com/sandbox?code=N4Igxg9gJgpiBcIAETIDsDOAXJBLLMAthkgLxIDaAOmiigPT1IAOATjAGa4AeShMWABbQadJMFFi66AmizwkAckBEBKuVIALFo1IAFAFcMuNAHMW7LtwCUigDSSp5zj3gAeAJKEAhiZhIMrGCkVCCCWFjMGPCM2F5YuGAAtAAMyQB0CRBoUPpgANZpkIT0XhgYAhhpqfTe2DCBXqxQiZloiQBMyRoAHNwAjO3tAKyJAMx5AEYAbF7cMAA2acymIUiCMLgmYcEgnSH0AHz2tI5rC8wAKjDc8noOp64AQvMQ%2BQDKWF75SCZezDt9VIhA73U5IDxoebGGAfL55H5-HadZLA0EPejuSHQ2H5EEnMFiVxXG5IUo7DDMLxoYFvBYwMAEKCknBgdb5CD6LCuejErB4gng%2BjPV55HF5fmnKyggC%2BxzEjCQAAk4QBPM7zS7XHD8IQifHiNEoGQwOQKRR2Q3qzU3BS6S0oJ4vd6fb6-f4hQEokASgUQqFoGEu%2BFupFA732qQeby%2BfyBHZhCJRGKfeJJVIZdA5fKFCDFUrlLCVaq1AgNJotdAdLq9AbDMaTGZzRbLEyrdabbYhPYgQ4Rwm8pAAN0auCpWB2E2gKoAslBVlgsjAJ6UYKsySEKVTUfqBSg1OohoehnpDMYzII4VKdwTubyfTeMViA2L776B%2BuQJvqd7afN6YzmVQNk8g5LkeS1V9IyFJ1RSDSCUCvKRpUkABdABuGhMLQVwAEEGVwLIABlcGwSQvniLIACUID-HZ%2BDQfR8CIEJJCY4hSGANiMGQk5DhAaUgA) illustrating the shortcomings of `prefix` and highlighting the versatility of `helpText`

### Option 3: proposal `content` with ReactNode type.

Here we can add any content to the `content` prop which doesn't require workaround or compromise. It also makes the prop type consistent with `helpText` 

```
    // suggested approach
    {
        content: (
          <>
            <Image src="https://static-00.iconduck.com/assets.00/mastercard-icon-2048x1225-3kb6axel.png" height="20"/>
            •••• 5555 (using hack)
          </>
        ),
        helpText: "Selected at checkout"
     },
```

**Comment by alex-page** [comment]
We have no plans of making `ActionListDescriptor.content` a React child. Reasons for this are:
- The `content` has wrapping and truncation logic added to it. This would break allowing React children.
- The `suffix` and `prefix` props are already flexible and allow react children

The most I would recommend is:
- Removing the opinionated width from `prefix` and `suffix`. I think we would need to do this carefully though to ensure we don't regress the wrapping and truncation features of content.
