### ISSUE TITLE
"Add filter" in Filters component button text not overridable

### ISSUE THREAD

**Issue by csm-genov** [Shopify/polaris-react-archive#12758]
### Summary

I was unable to find a way to override the "Add filters +" button text in the <Filters> Polaris component.

Could this be added as a prop or is there some workaround that I cannot find? 

### Expected behavior

This should be an adjustable value

### Actual behavior

Wrap animated gifs/videos in a details tag:
<details>
  <summary>Summary of your gif(s)</summary>
  <img src="..." alt="Description of what the gif shows">
</details>

### Steps to reproduce

[Link to sandbox]()
1. 
2.
3.

### Are you using React components?

Yes

**Comment by chloerice** [comment]
Hey @csm-genov! 👋🏽  Can you share context on why you need to customize this button text? We're making changes to this component, so any color you can add about your use case would be helpful to understand the current gap.

**Comment by csm-genov** [comment]
Hi @chloerice , 
In our specific case, it is required due to the fact that we offer admin side translation to our customers and we would like this text to be translated in the supported languages along with the rest of the text in our app.

**Comment by chloerice** [comment]
> Hi [@chloerice](https://github.com/chloerice) , In our specific case, it is required due to the fact that we offer admin side translation to our customers and we would like this text to be translated in the supported languages along with the rest of the text in our app.

Ahh okay! Polaris components are already localized, you can [dynamically ensure the correct translations are passed](https://polaris.shopify.com/components/utilities/app-provider#using-translations) into the Polaris `AppProvider` using `shopify/react-i18n`.
