### ISSUE TITLE
ResourceList.Item doesn't change page on click with URL

### ISSUE THREAD

**Issue by sdn90** [Shopify/polaris-react-archive#14]
# Issue summary
Clicking on ResourceList.Item doesn't change the URL.

## Expected behavior
Clicking on ResourceList.Item should go to the `url` prop

## Actual behavior
Nothing

## Specifications

- Polaris version: 1.0.1
- React version: 15.4.2

This is where it is in the code:
https://github.com/Shopify/polaris/blob/master/src/components/ResourceList/Item.tsx#L188-L193

Looks like `containerMarkup` needs to be added as a child of `UnstyledLink`

**Comment by sdn90** [comment]
Actually just realized you guys are having the `<a>` positioned absolute.

Problem is that the class `.Link` doesn't define a width.
https://github.com/Shopify/polaris/blob/master/src/components/ResourceList/ResourceList.scss#L274-L281

**Comment by ry5n** [comment]
Thanks @sdn90 for catching this. Currently our setup is a bit unusual—active development is happening on an internal repo in the short term. I’ve verified this and created an issue on that repo. You should see a fix land in the next release. Until then I’ll keep you posted!
