### ISSUE TITLE
License type & file missing

### ISSUE THREAD

**Issue by d2s** [Shopify/polaris-react-archive#15]
# Issue summary

- License file missing from the root of the project.
- License type missing from the `package.json` file.

### `LICENSE.md`

When there is a `LICENSE.md` file on the root of the repository, GitHub will show the type of license for users and search engines. It will also help 3rd party tools like to figure out the type of license via [The Licenses API](https://developer.github.com/v3/licenses/) of GitHub.

GitHub repository's license is displayed on the top right corner of the info bar:
![screenshot from 2017-04-23 14-46-59 github repository license is displayed on the top right corner of the info bar](https://cloud.githubusercontent.com/assets/135053/25313252/df73d84e-2833-11e7-9414-5f6724141b5a.png)

More details from GitHub's User Documentation: [Licensing a repository](https://help.github.com/articles/licensing-a-repository/)

### `package.json`

It would also make sense to add right license type to the `package.json` file. This is important, because it will allow tools to automatically validate whether license is compatible with requirements or not.
```js
  "license": "MIT",
```

More detailed description about `"license":` [structure](https://docs.npmjs.com/files/package.json#license) (and accepted [license types](https://spdx.org/licenses/)).

## Actual behavior

License file is not found from the Git repository, so the UI of GitHub is not displaying it for the potential users.
![screenshot from 2017-04-23 14-50-14 github license file missing](https://cloud.githubusercontent.com/assets/135053/25313272/34eec824-2834-11e7-9b1d-1c99356ee414.png)

Missing license from the `package.json` file makes it difficult to automatically verify the license type:
```js
  "license": "SEE LICENSE IN README.md",
```

## Steps to Reproduce the Problem

1. Open the GitHub repository on the address: https://github.com/Shopify/polaris
2. Look at the information displayed on the top right corner of the info bar.
3. Look at the `package.json` file, and see what `"license":` type is there.

## Specifications

- Polaris version: v1.0.1
- React version:
- Browser:
- Device:
- Operating System:

**Comment by lemonmade** [comment]
Thanks for the issue, @d2s. I've merged a fix in our internal version of Polaris, and you should see the fix live tonight in version 1.0.2.
