### ISSUE TITLE
Documentation around visuals(colors, typography, etc) for offline browsing

### ISSUE THREAD

**Issue by ismnoiet** [Shopify/polaris-react-archive#16]
I have one question, but before that let me thank the team behind this **awesome** project, it is really a **piece of art** and should get more stars here in Github.

For my question I wonder if there is a place where I can clone the documentation around visuals(colors, typography, etc) for offline browsing something like a ``gh-pages`` or similar.

Thanks for your time.

**Comment by cargix1** [comment]
We were just thinking exactly the same as we have a long flight back to London this evening after Unite. Would have loved to read through offline and smash the codes out when I land :)

**Comment by lemonmade** [comment]
Hey @ismnoiet, what docs are you looking to have for offline purposes? The component documentation is all in READMEs that should be available as part of the NPM package. They are also available by cloning the Github repo, if you aren't using the NPM package. If you are looking for the documentation around visuals (colors, typography, etc), we currently have those in a private repo but hope to make them public in the future.

**Comment by ismnoiet** [comment]
Hey @lemonmade, yeah am looking for the documentation around visuals, so i can play with it locally(like babel repl).
Hopefully you open source it in the near future.

Thanks again for the project.

**Comment by kaelig** [comment]
We are looking at opening the GraphQL API to the public, which means all the documentation & component examples would be available for offline consumption (e.g. by a tool that'd download everything locally as JSON, and then consume and display that data in a custom UI). We'll let you know when something is ready!

**Comment by ismnoiet** [comment]
Thank you @kaelig for the great work.

**Comment by kaelig** [comment]
@ismnoiet the GraphQL API is now available at https://polaris.shopify.com/api, and you can read documentation on how to use it over at https://polaris.shopify.com/resources/graphql-api

If you build anything using the API, we'd love to hear about it!

We are considering transforming polaris.shopify.com into a progressive web app, but I'll close this issue as it's not on our roadmap for the foreseeable future.
