### ISSUE TITLE
No app examples in Sketch file

### ISSUE THREAD

**Issue by lukepxu** [Shopify/polaris-react-archive#17]
The "Examples - Apps & Channels" page in the provided Sketch file (WebUIkit.sketch) doesn't show any examples of Apps: https://cl.ly/0B3u0z0G3K3J.

**Comment by ry5n** [comment]
Good catch @lukepxu. We’ll be tackling this soon. Look for some initial app example screens in the next release.

**Comment by lemonmade** [comment]
Should be fixed in the latest release of the Sketch UI Kit.

**Comment by ry5n** [comment]
I should note that we’d like to add more app examples in the future—let us know if there’s anything in particular you’re missing.

**Comment by lukees** [comment]
Thanks @lemonmade @ry5n !

I'd love to know how apps handle internal navigation. Currently, we can use breadcrumbs in the header, but these examples seem to insinuate that we can we can now use sub navigation items in the Shopify sidebar. However, the example apps show "Sample Channel" selection in the sidebar, making me think that apps don't actuality have that functionality available to them.

I'll make a new issue for this.
