### ISSUE TITLE
Feature Request: Add a "base_url" config to EmbeddedApp

### ISSUE THREAD

**Issue by mikeyhew** [Shopify/polaris-react-archive#178]
I have an app that I'm working on that is located at `/embedded` instead of at `/`. With `forceRedirect` set to `true`, the easdk redirects to `my_shop_domain.myshopify.com/admin/apps/blahblahsomeapp/embedded` when it should really go to `my_shop_domain.myshopify.com/admin/apps/blahblahsomeapp`. Can someone at Shopify please add a `base_url` config to `EmbeddedApp` so that it removes the `/embedded` part (or whatever you set `base_url` to) from the url before redirecting?

If you were accepting pull requests, I would do it myself...

**Comment by trish-ta** [comment]
Hi Mikey,

The `forceRedirect` is meant to direct the user back inside Shopify admin with the current app's page loaded inside the iframe. It is not meant to direct the user back to the app's base url. The current workflow ensures that the user returns to the current page they were attempting to access.

Can you clarify why a user who is accessing your app at `my_shop_domain.myshopify.com/admin/apps/blahblahsomeapp/embedded` should be redirected to`_shop_domain.myshopify.com/admin/apps/blahblahsomeapp/`?

**Comment by mikeyhew** [comment]
@trish-ta What I mean is when the user accesses `my_app_domain.com/embedded`, they should be redirected to `my_shop_domain.myshopify.com/admin/apps/blahblahsomeapp/`

**Comment by gf3** [comment]
hi @mikeyhew, thanks for the suggestion. in the mean time something like the following should help for  now:

``` js
/**
 * Detect if your application is embedded and build the corresponding redirect
 * URL if necessary. Returns `undefined` if a redirect isn't necessary.
 *
 * @param {String} path - The URL path to use
 * @param {String} search - The URL search to use
 * @param {String} [basePath] - Optional base path to remove from the redirect URL
 *
 * @returns {(String|undefined)} - The redirection URL to be used
 */
function buildRedirectUrl(path, search, basePath) {
  if (window !== window.parent) {
    return;
  }

  let p = path;
  let origin = 'https://myshopify.com';
  const originMatch = search.match(/&shop=(\w+\.myshopify\.\w{2,3})/);

  if (originMatch) {
    origin = `https://${originMatch[1]}`;
  }

  if (basePath) {
    p = path.replace(new RegExp(`^${basePath}`), '');
  }

  return `${origin}/admin/apps${p}${search}`;
}

// Example usage
const url = buildRedirectUrl(window.location.path, window.location.search, '/embedded');

if (url) {
  window.location.assign(url);
}
```

**Comment by mikeyhew** [comment]
Thanks @gf3, that looks like a good interim solution.

**Comment by mikeyhew** [comment]
I was working on an embedded app today, and found out that, although you can set the app url to `my-app.com/embedded`, the Embedded App SDK will still use `my-app.com/` as the base url when loading pages other than the home page to the app. To illustrate visually, this is what I thought was the case:

Url in Shopify Admin | App url in iframe
---  | ---
`/admin/apps/my-app/` | `/embedded`
`/admin/apps/my-app/widgets` | `/embedded/widgets`
`/admin/apps/my-app/extras` | `/embedded/extras`

and this is what is actually the case:

Url in Shopify Admin | App url in iframe
---  | ---
`/admin/apps/my-app/` | `/embedded`
`/admin/apps/my-app/widgets` | `/widgets`
`/admin/apps/my-app/extras` | `/extras`

The whole reason for this feature request was so that you could put the React app at `/embedded/*` instead of `/*`, to avoid potential issues with conflicting routes while keeping `/embedded` out of the url displayed in the browser's address bar. I've realized since then that those issues may be more imaginary than I originally thought; and since the behaviour that I wanted isn't actually possible given the way the Embedded App SDK works, I am going to close this issue and host my apps at `/` like a normal human being.
