### ISSUE TITLE
Missing @shopify/polaris dependency when developing in TypeScript.

### ISSUE THREAD

**Issue by buggy** [Shopify/polaris-react-archive#19]
# Issue summary

Missing NPM dependency when developing in TypeScript.

## Expected behavior

After installing Polaris using

```sh
npm install @shopify/polaris --save
```

I expect to be able to compile applications using the TypeScript compiler.

## Actual behavior

When running `tsc` the following error is produced:

<details>
node_modules/@shopify/polaris/types/components/Icon/Icon.d.ts(2,27): error TS2307: Cannot find module '@shopify/images'.
</details>

## Steps to Reproduce the Problem

1. Create a new React app using TypeScript. Verify that it compiles ok
1. Install Polaris using `npm install @shopify/polaris --save`
1. Add some code that uses Polaris (I have a sample at https://github.com/buggy/polaris-demo)
1. Attempt to compile the application using `tsc`. You'll now see the error.

This can be fixed by running `npm install @shopify/images --save` to add the missing dependency.

## Specifications

- Polaris version: 1.0.1
- React version: 15.5.4
- Browser: Firefox 53.0
- Device: Mac
- Operating System: 10.12.4

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by lemonmade** [comment]
Thanks for this issue as well, @buggy. This one will also be fixed in 1.0.2.
