### ISSUE TITLE
Documentation example input field is not working as expected

### ISSUE THREAD

**Issue by paulxuca** [Shopify/polaris-react-archive#2]
# Issue summary

Example input field does not preserve input value
## Expected behavior
 
If I type in "Dog", it should say Dog, not g (since only last input is preserved.)

## Actual behavior

I type in "Dog", and only g is displayed.

## Steps to Reproduce the Problem

1. Go to: https://polaris.shopify.com/components/titles-and-text/display-text#examples (Or any exmple with an input field)
2. Type in "Dog"
3. Observe only g is displayed.

## Specifications

- Polaris version: 1.0.1

**Comment by reggi** [comment]
It seems that the input field to alter the children doesn't work correctly (only puts in one letter at a time), but if you click into the component itself it does work.

![xx](https://cloud.githubusercontent.com/assets/296798/25252660/f315503e-25eb-11e7-9872-52ae44a9c2f3.gif)

**Comment by reggi** [comment]
This works for the [heading](https://polaris.shopify.com/components/titles-and-text/heading#navigation) component though.

![working](https://cloud.githubusercontent.com/assets/296798/25252881/a9718eb0-25ec-11e7-8a7d-91745373eadf.gif)

**Comment by lemonmade** [comment]
Thanks for the issue, @paulxuca. We actually have a PR open to fix this on a few pages (it affects any component that has a pascal case name with more than one capital letter — I'll leave it to the reader to guess how we managed to create a bug like that 😄). We'll close this issue once we've fixed it up.

**Comment by paulxuca** [comment]
Thanks for both the replication examples above and your quick response! Looking forward to changes in this project! :D

**Comment by sarcos** [comment]
@reggi may I ask how do you create those .gif ? thx

**Comment by reggi** [comment]
@sarcos https://itunes.apple.com/us/app/giphy-capture-the-gif-maker/id668208984?mt=12
