### ISSUE TITLE
Is there a list of empty state illustrations we can use?

### ISSUE THREAD

**Issue by alekseyg** [Shopify/polaris-react-archive#201]
In the documentation for the EmptyState component, there is an example illustration used, but no documentation on whether that is example is free for app developers to use or not. Also, in the Illustrations -> Partner resources section, it says there are 4 that we are free to use, but only 1 is displayed. Given the great variety in Shopify itself, it would be nice to know if app developers can make use of that great variety, along with a list we could easily preview and copy URLs from or save to our own servers, or explicit documentation stating that we are not allowed to use them and must create our own.

**Comment by cargix1** [comment]
Totally agree. It would be really helpful to have access to the illustrations :)

**Comment by alekseyg** [comment]
Also, the one illustration listed in the Illustrations -> Partner resources section is more of a preview than an image you can download and use: it is padded with a solid background instead of being just the image with a transparent background, and it is low resolution. Basically, even the listed one is useless, and there is no actual useful list of images we can use.

**Comment by kaelig** [comment]
Thank you for raising this!

Apologies, we forgot to keep the `Illustrations.zip` file in every new release. You'll now find this file over here: https://github.com/Shopify/polaris/releases/

You may use those images in the context of your Shopify apps, however you may not modify them and/or resell them. Hope this helps!

**Comment by coler-j** [comment]
@kaelig is there a list of these images already hosted on a CDN?

**Comment by xyyolab** [comment]
Hope we can get a list of images like this one.
https://cdn.shopify.com/s/assets/admin/checkout/settings-customizecart-705f57c725ac05be5a34ec20c05b94298cb8afd10aac7bd9c7ad02030f48cfa0.svg

**Comment by arobbins** [comment]
I'm not seeing the `Illustrations.zip` file either.

**Comment by benkissi** [comment]
Anyone still looking for illustrations can check here https://undraw.co/. You can edit the colors to match what you want

**Comment by madsenmm** [comment]
For anyone looking for this, I've created for this case:
https://www.vectorizemyshopify.com/
