### ISSUE TITLE
Stacks are broken using latest dependencies

### ISSUE THREAD

**Issue by chaddjohnson** [Shopify/polaris-react-archive#206]
# Issue summary

## Expected behavior

Stacks should show with their badge items.

## Actual behavior

Stacks do not show using latest dependencies; not sure what dependency is causing the problem. If I `rm yarn.lock` from the [webpack example](https://github.com/Shopify/polaris/tree/master/examples/webpack) and run `yarn install`, then Stacks do not show. Here is a screenshot:

<img width="1192" alt="screen shot 2017-10-24 at 12 25 24 pm" src="https://user-images.githubusercontent.com/676134/31958176-8a7d642c-b8b6-11e7-9717-872eed5c8dcf.png">

If, however, I run `yarn install` without removing `yarn.lock`, then, the Stacks and their Badge items do show.

## Steps to reproduce the problem

1. Clone [this fork](https://github.com/chaddjohnson/polaris).
1. Run `cd examples/webpack`.
1. Run `rm yarn.lock`.
1. Run `yarn install`.
1. Run `yarn start`.
1. Visit `http://localhost:8080`.

You will see that no stack shows below the text `A stack with badges should show here, but it doesn't:`.

## Specifications

- Polaris version: I tried with v1.0.1 (as in example) as well as 1.8.0 (and updated the CSS file to use 1.8.0).
- React version: ^15.4.2 and ^16.0.0.
- Browser: Chrome 61.0.3163.100 (Official Build) (64-bit)
- Device: 2015 MacBook
- Operating System: macOS High Sierra 10.13

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 This repo is for reporting issues and feature requests only

**Comment by dfmcphee** [comment]
Thanks for the issue @chaddjohnson. We just released v1.8.2 that should resolve this.

**Comment by chaddjohnson** [comment]
Wow! Fast. Thank you :)
