### ISSUE TITLE
ChoiceList component deselects radio options

### ISSUE THREAD

**Issue by tim-phillips** [Shopify/polaris-react-archive#217]
# Issue summary

The `ChoiceList` component deselects radio options when programmatically setting the `selected` prop back to the first option. This only happens when I change the prop in code (like with `this.setState({ selected: value })`. When the user interacts with the radio buttons, the component works as usual. 

## Expected behavior

The component should select the first option when I set the `selected` prop appropriately. 

## Actual behavior

When `option2` is selected in a radio button `ChoiceList`, I execute `this.setState({ selected: 'option1' })`, the radio button is deselected and the first option is not selected. 

## Steps to reproduce the problem

1. Create the following component:
```javascript
import React, { Component } from 'react'
import {
  ChoiceList
} from '@shopify/polaris'

export default class ChoiceListTest extends Component {
  state = {
    selected: 'option2'
  }

  handleChange = (newValue) => {
    this.setState({ selected: newValue })
  }

  componentDidMount = () => {
    window.setTimeout(() => this.setState({ selected: 'option1' }), 500)
  }

  render () {
    return (
      <ChoiceList
        id='type'
        choices={[
          {
            label: 'Option 1',
            value: 'option1'
          },
          {
            label: 'Option 2',
            value: 'option2'
          }
        ]}
        onChange={this.handleChange}
        selected={this.state.selected}
      />
    )
  }
}
```
2. Render
3. Watch the radio button deselect after a half second delay. The first option is not selected even though `this.setState({ selected: 'option1' })` was called. 

## Specifications

- Polaris version: 1.8.3
- React version: 16.0.0
- Browser: Chrome 62
- Device: Mac
- Operating System: macOS 10.13.1

**Comment by chloerice** [comment]
Hey @babenzele! Everything looks good with your code except for one quick fix that's needed.

The selected prop expects an array of strings (choice values), and when invoked your handleChange can also expect an array of string values as its parameter. With that fixed your implementation works as expected. Here's what that looks like with example code updated:

```jsx
import React, { Component } from 'react'
import {
  ChoiceList
} from '@shopify/polaris'

export default class ChoiceListTest extends Component {
  state = {
    selected: ['option2']
  }

  handleChange = (selected) => {
    this.setState({selected})
  }

  componentDidMount = () => {
    window.setTimeout(() => this.setState({selected: ['option1']}), 500)
  }

  render() {
    return (
      <ChoiceList
        name="type"
        choices={[
          {
            label: 'Option 1',
            value: 'option1'
          },
          {
            label: 'Option 2',
            value: 'option2'
          }
        ]}
        onChange={this.handleChange}
        selected={this.state.selected}
      />
    )
  }
}
```

**Comment by babenzele** [comment]
Thanks @chloerice, that did the trick!

Thanks for the `name` tip, I was expecting `onChange` to pass `id` like some of the other form components and was getting `null`.

I took your example and reversed things a bit so I could keep the state as a string since I'm only expecting one choice. But I get that the array is necessary since `ChoiceList` follows the `allowMultiple` convention even when it is not specified or it is set to `false`.

<details>
  <summary>Just in case anyone also wants to do things this way (click to show).</summary>
  <p>

```javascript
import React, { Component } from 'react'
import {
  ChoiceList
} from '@shopify/polaris'

export default class ChoiceListTest extends Component {
  state = {
    options: 'option2'
  }

  handleChange = (selected, name) => {
    this.setState({[name]: selected[0]})
  }

  componentDidMount = () => {
    window.setTimeout(() => this.setState({options: 'option1'}), 500)
  }

  render () {
    return (
      <ChoiceList
        name='options'
        choices={[
          {
            label: 'Option 1',
            value: 'option1'
          },
          {
            label: 'Option 2',
            value: 'option2'
          }
        ]}
        onChange={this.handleChange}
        selected={[this.state.options]}
      />
    )
  }
}
```
  </p>
</details>
