### ISSUE TITLE
Two card example are the completely same thing.

### ISSUE THREAD

**Issue by hoppergee** [Shopify/polaris-react-archive#218]
# Card examples issue on website
The Polaris Card examples :
- Card with call to action in the heading
- Card with an action menu in the heading

These two examples on [card example page](https://polaris.shopify.com/components/structure/card#navigation) are the completely same thing!

**Comment by chloerice** [comment]
Good catch @wokenqingtian! I'll add this to our internal to-dos for the next upcoming milestone.
