### ISSUE TITLE
Improved resource list component

### ISSUE THREAD

**Issue by dfmcphee** [Shopify/polaris-react-archive#227]
The new resource will support selection, sorting, bulk actions, and an improved API.

This is a preview of what it will look like:

## Large screen
<img width="1281" alt="screen shot 2017-11-21 at 10 28 30 am" src="https://user-images.githubusercontent.com/478990/33080758-dc30f54e-cea6-11e7-8700-268987015167.png">

## Small screen
<img width="319" alt="screen shot 2017-11-21 at 10 28 53 am" src="https://user-images.githubusercontent.com/478990/33080759-dc3c2766-cea6-11e7-89e8-7b5f526985ee.png">

Related issues: #147, #65

**Comment by USvER** [comment]
Any updates?

**Comment by babenzele** [comment]
https://github.com/Shopify/polaris/issues/254#issuecomment-359893991

**Comment by USvER** [comment]
Thanks!

**Comment by Anveio** [comment]
That looks great. And are those icons for exceptions? I didn't even realize how much I wanted those until now! I think my users will appreciate a more powerful ResourceList component and I can't wait for the release. 😁

**Comment by ry5n** [comment]
This is getting close to final, and I’m happy to say [documentation is now available for the new version](https://polaris-v2.shopify.com/components/lists/resource-list). 

We’d love to get additional input on APIs and features. Let us know in this thread.

**Comment by sdn90** [comment]
Will you guys be adding column headers or is that something the user will need to implement themselves?

Example from product page in Shopify admin:
<img width="916" alt="screen shot 2018-04-19 at 4 33 05 pm" src="https://user-images.githubusercontent.com/2491713/39023453-91dfb0fc-43ef-11e8-9dde-8361c99682ba.png">

**Comment by ry5n** [comment]
We’ve done our best to design resource lists so they can work well at all screen sizes. At some minimum width, content in columns is going to have to wrap and re-arrange. For this reason we opted to not include column headers at all.

Most of the indexes in the Shopify admin today are still using our older table-based approach, and we’ll be converting these one at a time to use the new component.

Not having headers comes with some tradeoffs, but we think for indexes this is the right choice. To display data for analysis, there is a new DataTable component.

To learn more about creating list items to fit your content, check out the v2 docs: https://polaris-v2.shopify.com/components/lists/resource-list#study-custom-item

Let us know how that goes. We’re happy to help you with the specifics for your case.

**Comment by ry5n** [comment]
With the [Polaris 2.0 release candidate](https://github.com/Shopify/polaris/releases/tag/v2.0.0-rc.1) now available, I’m happy to call the resource list component officially improved 🎉
