### ISSUE TITLE
Graphik Regular font mistakenly included in Sketch UI kit

### ISSUE THREAD

**Issue by adamnel** [Shopify/polaris-react-archive#23]
# Issue summary

Sketch UI kit sometimes uses Graphik Regular font rather than SFUI, causing missing font error for those without the font installed.

## Expected behavior

SFUI font installation should resolve all missing font issues.

## Actual behavior

Graphik regular used inconsistently in some places where SFUI appears to be preferred.

## Steps to Reproduce the Problem

1. Disable Graphik Regular font if installed.
2. Open Sketch UI kit

## To correct

1. Install Font Finder sketch plugin
2. Run plugin on "Examples - Core" page of Sketch file
3. Replace incorrect font

**Comment by allylane** [comment]
Thanks for raising this @adamnel.
References to Graphik will be removed for our next release.
