### ISSUE TITLE
Customize Colors

### ISSUE THREAD

**Issue by paragjagdale** [Shopify/polaris-react-archive#26]
# Issue summary

While the Shopify Polaris color theme is great, how do we go about creating a customized color theme without losing the ability to merge in updates into our codebase and / sketch file? 
A bigger question is, does Polaris encourage changing the color theme based on branding, or are we, as developers/designers on our own if we do choose to change colors to match?

## Expected behavior

The Sketch Web.UIKit.sketch file should have used shared styles to make colors customizable so that app developers can customize the colors to fit branding while keeping the structure in place. This is possible in the CSS, however it is not in the Sketch file.

## Actual behavior

Sketch Web.UIKit.sketch hard codes colors into every symbol, thus it is hard to start using if we wanted customized branding.

## Specifications
N/A

**Comment by Geczy** [comment]
Would also like to know Shopify's recommendations on how to modify colors in a React application

**Comment by allylane** [comment]
Thanks for reaching out @paragjagdale.

One of the goals of Polaris is to unify all of the product design work that's being done on Shopify, both internally and by our partners. We recommend using the colors that have been supplied as part of Polaris for any of the work you're producing on Shopify.

You can find out more about our color palette and how to use it here:
https://polaris.shopify.com/visuals/colors

Thanks,

Alistair

**Comment by paragjagdale** [comment]
@allylane I think I found the cause of the misunderstanding. I was equating Polaris to something like Bootstrap or Google Material Design Lite, which could be used to create the whole admin for an app, which is where company branding would matter more. However, Polaris is just what should be used INSIDE of Shopify alone using the embedded app API.  Is that a correct assessment? If so, I recommend making this point clear somewhere in the documentation if others were also confused. Thanks.

**Comment by allylane** [comment]
That's right @paragjagdale. Thanks for the recommendation. I'll take it back to the team.

**Comment by benbonnet** [comment]
that is, the licence does not bound polaris to a strict use within the shopify ecosystem; right ?

**Comment by cstffx** [comment]
if I want to use Polaris outside of Shopify apps will I need to change colors, borders and fonts?
