### ISSUE TITLE
Multiline Text Field - Newline Docs page 

### ISSUE THREAD

**Issue by timarney** [Shopify/polaris-react-archive#264]
# Issue summary

After presses "ENTER" in the Multiline text field on the docs page the field autofills with \\n etc... 

## Expected behavior

Normal Text Area behavior

**Note: I tested the Component in an embedded app and it worked fine.** 

## Actual behavior

![txt](https://user-images.githubusercontent.com/62242/35647037-4a663e04-069f-11e8-8f8f-3f177d24f8d2.gif)

## Steps to reproduce the problem

1. Visit https://polaris.shopify.com/components/forms/text-field#navigation
1. Select Multiline text field from the drop down 
1. Enter some characters or just press "ENTER"

## Specifications

- Browser: Chrome

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 This repo is for reporting issues and feature requests only

**Comment by ry5n** [comment]
We recently shipped some updates to the demos on the Polaris site, and this should now be fixed 🎉 

Please let us know if you still see the issue
