### ISSUE TITLE
[2.0] Disable item count text in resource list

### ISSUE THREAD

**Issue by danizord** [Shopify/polaris-react-archive#269]
# Issue summary
I'm using Polaris 2.0 beta6 because I need `onAction` on resource list items and it is not available in 1.X.

It works fine, however it is displaying a "Showing X items" text on top of the resource list and I'd like to remove it. Is it possible?

## Expected behavior
A way to disable this behavior, like a `showItemCount` prop or something.

## Actual behavior
Item count is displayed for all resource lists.

## Specifications

- Polaris version: 2.0-beta6

**Comment by ry5n** [comment]
I’d like to have a way to turn off the header. We’re still working on the new version of resource list and I’ll add this to our queue.

**Comment by dfmcphee** [comment]
Thanks for the issue @danizord. The `ResourceList` now defaults to not showing the header unless you pass the `showHeader` prop.

https://polaris-v2.shopify.com/components/lists-and-tables/resource-list
