### ISSUE TITLE
TypeError: this.props.onClose is not a function - Popover PopoverOverlay

### ISSUE THREAD

**Issue by 8bitmatt** [Shopify/polaris-react-archive#27]
# Issue summary

An error is thrown if you do not define the onClose prop for the Popover component.

## Expected behavior

No error should be thrown, or the documentation should include a "required" properties column.
None of the examples used the onClose prop, that's why it was an unexpected error. In actual usage I imagine most people will be defining onClose.

## Actual behavior

The error happens when clicking on the invisible PopoverOverlay element.

```
TypeError: this.props.onClose is not a function
at Popover.handleClose
at PopoverOverlay.handleClick
```

The problem is here:
https://github.com/Shopify/polaris/blob/master/src/components/Popover/Popover.tsx#L101

`handleClose` gets called when PopoverOverlay closes and it's always assuming `this.props.onClose` is defined.

## Steps to Reproduce the Problem

1. A Popover must be open
2. Click anywhere outside of the Popover (this click is registered on the PopoverOverlay element)
3. Error is thrown (unless you defined the onClose prop)

## Specifications

- Polaris version: 1.0.2
- React version: 15.5.0

**Comment by marcysutton** [comment]
This also occurs in the date-picker component, which uses the popover.

**Comment by lemonmade** [comment]
Fixed in the live version of the style guide.
