### ISSUE TITLE
Version 2.0 Release Date?

### ISSUE THREAD

**Issue by fliptoo** [Shopify/polaris-react-archive#273]
# Issue summary
We would like to know is there any targeted release date for Version 2.0?

**Comment by dfmcphee** [comment]
Hey @fliptoo. We are hoping to have v2 out in early March. We do have the beta currently available if you want to start using it and giving feedback today though.

**Comment by superwhykz** [comment]
Does table support added in beta?

**Comment by fliptoo** [comment]
thanks

**Comment by chloerice** [comment]
> (@superwhykz) Does table support added in beta?

Coming this week!
