### ISSUE TITLE
[2.0] Can't compile styles

### ISSUE THREAD

**Issue by USvER** [Shopify/polaris-react-archive#274]
# Issue summary

I'm getting `Sass::SyntaxError` on `styles.scss`
> File to import not found or unreadable: styles/components.

Wich is caused by `@import 'styles/components';`
Beacuse there is no `components` in the styles folder.

## Specifications
- Polaris version: v2.0.0-beta.7
- React version: 16.2.0

**Comment by dfmcphee** [comment]
Can you provide some more details here @USvER? I just tried on beta 7 and was able to successfully compile the styles. What type of project are you importing the styles into? Looking in my project I see a `components` folder in `node_modules/@shopify/polaris/styles`.

**Comment by dfmcphee** [comment]
I'm going to close this since it appears to be working in the latest betas. Feel free to re-open with more information if you are still having issues compiling.
