### ISSUE TITLE
Run https://polaris.shopify.com/components/get-started locally?

### ISSUE THREAD

**Issue by martingordon** [Shopify/polaris-react-archive#277]
# Issue summary

I'm looking to use Polaris as the foundation for our component library. The functionality you've built for your Component Library is really useful and using Markdown lowers the barrier significantly for our design and product teams to contribute.

If there's no way to run it locally, do you have any guidance on how to render the Markdown files as React/HTML?

## Expected behavior

`yarn dev` or `yarn build` produces an index.html file that I can open to see https://polaris.shopify.com/components/get-started

## Actual behavior

No easy to find way to view the entire library of components locally.

## Steps to reproduce the problem

1. Clone repo
2. Run `yarn dev` and see a blank Playground file.
3. Run `yarn build` and see various build directories but no `index.html`.

## Specifications

- Polaris version: Both `master` and 1.12.0
- Browser: Chrome
- Device: MacBook Pro
- Operating System: macOS 10.13

**Comment by kaelig** [comment]
Hey @martingordon, thanks for the kind feedback. The site running polaris.shopify.com is private for the moment.

If you're looking for a good static site generator for your component library, I'd encourage you to look into https://docs.catalog.style/ and https://www.gatsbyjs.org/, two open-source initiatives that are great inspirations for how we build our own style guide.

Hope this helps, and feel free to share your findings here as well!
