### ISSUE TITLE
Breadcrumb actions/component values

### ISSUE THREAD

**Issue by dylan** [Shopify/polaris-react-archive#278]
# Issue summary

It would be fantastic if breadcrumbs could trigger actions, or accept components as values.

## Expected behavior

For example, right now I'm using a pushState oriented router in a react app that uses Polaris, and I cannot use breadcrumbs in a page in their current state because it modifies the location directly rather than history.push/pop/replacing the state.

**Comment by nwtn** [comment]
Thanks for your suggestion! We’ll add this to our backlog and keep it in mind as we build out our roadmaps. I’ll leave this issue open for the time-being so we can update it when we’re able to share more concrete plans.

**Comment by Hughp135** [comment]
Would be nice to be able to trigger actions, although you can use breadcrumbs to navigate with react-router-dom but using a custom link component, e.g.

```
const CustomLinkComponent = ({ children, url, ...rest }) => {
  return (
    <Link
      to={url}
      {...rest}
    >
      {children}
    </Link>
  );
};
```
```
<AppProvider linkComponent={CustomLinkComponent} />
```

**Comment by cbolton97** [comment]
As of [v2.6.1](https://github.com/Shopify/polaris/releases/tag/v2.6.1), Breadcrumbs can now be of the type `CallbackAction`. You may find [this documentation](https://polaris.shopify.com/components/structure/page/breadcrumbs/CallbackAction) helpful when implementing. 

Thanks for the issue!
