### ISSUE TITLE
Border clipped on focussed multiline text field

### ISSUE THREAD

**Issue by andrewpye** [Shopify/polaris-react-archive#279]
# Issue summary
A [fix for overflow issues](https://github.com/Shopify/polaris/compare/v1.11.0...v1.12.0#diff-fe2f1e44970e03819c2e6e326e4cd329R22) when using the TextField component inside a Scrollable has made it so that the indigo border gets clipped when a multiline TextField has focus.

## Expected behavior
Indigo border when multiline TextField is focussed is consistent with other Polaris controls, i.e. like this:
![image](https://user-images.githubusercontent.com/5737342/37457008-6f89bfbe-2849-11e8-889b-270d99d47f37.png)

## Actual behavior
Indigo border on focussed control is clipped:
![image](https://user-images.githubusercontent.com/5737342/37456912-27503e76-2849-11e8-9321-14b52c872a9e.png)

## Steps to reproduce the problem

1. Add a multiline TextField to an app.
2. Focus that TextField component.

## Specifications

- Polaris version: 1.12.0, 1.12.1, 1.12.2
- React version: 16.0.0
- Browser: Chrome Canary (67.0.3370.0)
- Device: Macbook Pro
- Operating System: macOS Sierra 10.12.6

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 This repo is for reporting issues and feature requests only

**Comment by tmlayton** [comment]
@andrewpye thanks for opening this issue. We have an issue open internally and will be fixing with the next release.

**Comment by andrewpye** [comment]
That's great, thanks @tmlayton!

**Comment by tmlayton** [comment]
My mistake – not the next release, but soon.

**Comment by dfmcphee** [comment]
This should be fixed in the latest version.
