### ISSUE TITLE
V2 Color Picker Issue

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris-react-archive#282]
# Issue summary

Render a Color Picker

<div class="Polaris-FormLayout__Item">
                      <div>
                        <div class="Polaris-ColorPicker" id="status-color">
                          <div class="Polaris-ColorPicker__MainColor">
                            <div class="Polaris-ColorPicker__ColorLayer" style="background-color: rgb(0, 255, 0);"></div>
                            <div class="Polaris-ColorPicker__Slidable">
                              <div class="Polaris-ColorPicker__Dragger" style="transform: translate3d(0px, 0px, 0px);"></div>
                            </div>
                          </div>
                          <div class="Polaris-ColorPicker__HuePicker">
                            <div class="Polaris-ColorPicker__Slidable">
                              <div class="Polaris-ColorPicker__Dragger" style="transform: translate3d(0px, 0px, 0px);"></div>
                            </div>
                          </div>
                        </div>

## Expected behavior

Expect mouse events dragging colours controls around to work. Slider, clicks on the palette. 

## Actual behavior

No mouse events work with the control. Cannot change colour using this control.

See this Codepen for a demo: https://codepen.io/resistorsoftware/pen/QmgwRg

## Steps to reproduce the problem

Pasted HTML into Codepen as well, same behaviour. What is the secret to activating this control?

https://codepen.io/resistorsoftware/pen/QmgwRg

## Specifications

- Polaris version: V2 Beta 4
- React version: not used
- Browser: Chrome
- Device: Mac
- Operating System: MacOS

**Comment by chloerice** [comment]
Hi @resistorsoftware, sorry for any confusion! If you are using only the CDN version of a component, you will need to add your own event handlers to the markup and wire them up with your own JavaScript. The HTML and CSS provided does not come with JavaScript.

Copying functions from the source code of the component and sub-components would be a good basis for building out your vanilla JavaScript event handling. You'll need to start by stripping out the TypeScript and the React methods, like setState. Then use jQuery or DOM methods to access and update the elements by class instead.  We highly recommend using the React components directly though, especially for very complex components like the color picker.

**Comment by resistorsoftware** [comment]
I wired up an event handler for the "change" event and nothing happens. Again, no mouse movement whatsoever... I understand I need to wire up an event handler for change, but this component has no functionality whatsoever without REACT? That makes it kinda useless... 

Ok.. well.. whatever... this one should be flagged as special case then... since it clearly is not just a simple one as per all the other components I have used.

**Comment by resistorsoftware** [comment]
I get it now. Was silly of me to imagine this component working as just some HTML.. there is so much custom JS going on behind the scenes... I will just use HTML5 color component for now, and re-visit this component if I ever decide to touch React. Thanks!

**Comment by chloerice** [comment]
As this is a React library, all JavaScript is written in React for consumption of the package through NodeJS. We autogenerate the HTML markup to be used with the CDN styles to give folks a starting point for implementing the components without React if they prefer. 

I do think we can to do a better job of clarifying that beyond [the introduction to the library](https://polaris.shopify.com/components/get-started) in the style guide. I'll make an issue on our internal project board 😊.

**Comment by resistorsoftware** [comment]
I agree. Most components I have used work with no JS. It is only the ones that intrinsically require JS where it would be nice if Shopify made special notes. We should be free to wire up Polaris as we see fit, and for convenience, a brief explanation of the needed event handlers, etc would be super. Having to reverse engineer the React implementation is possible as you point out, but not fun.

**Comment by chloerice** [comment]
You can always use the [color picker that HTML5 provides](https://www.w3schools.com/jsref/dom_obj_color.asp) via`<input type="color" />`.
