### ISSUE TITLE
v2 components searchable in v1 docs

### ISSUE THREAD

**Issue by diagramatics** [Shopify/polaris-react-archive#284]
# Issue summary

I found a bug. I tried to search for a file upload (#48) to then find out that the search box shows the drop zone. I can click on it, but it takes me nowhere:

![image](https://user-images.githubusercontent.com/5153378/37939166-12de3df4-31ad-11e8-9f87-446e415d41a1.png)

This might be quite nitpicky, and you'll probably need two instances of Algolia to separate it properly (?)

## Expected behavior

The v2 components (like the drop zone) shouldn't show up in the v1 docs search.

## Actual behavior

It does.

![image](https://user-images.githubusercontent.com/5153378/37939261-96e08e0e-31ad-11e8-92bb-a43b5a060dda.png)

## Steps to reproduce the problem

1. Go to the v1 docs site
1. Search for "drop zone". It will show up as the first result.
1. Click on it and you'll be taken to the page with the loading state.

## Specifications

- Polaris version: v1.12.4 specified on the docs

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 This repo is for reporting issues and feature requests only

**Comment by kaelig** [comment]
Hey @diagramatics, thank you for pointing this out (and for the detailed issue).

The v2 docs were accidentally published to polaris.shopify.com a few days ago, and it looks like the crawler managed to index those new components… I've just removed the v2 components from the index and all should be back to normal.

**Comment by diagramatics** [comment]
Ah that makes sense, thanks for the quick response. I'm assuming Algolia is implemented with the same instance across v1 and v2 docs, because I can't find the drop zone in the v2 docs anymore then?

Not that it's an issue on my end, but more of an FYI.

**Comment by kaelig** [comment]
That is correct, both instances share the same search index.

**Comment by diagramatics** [comment]
That explains it. I won't fuss about it then, thanks!
