### ISSUE TITLE
Missing "Edit" icon

### ISSUE THREAD

**Issue by meecrobe** [Shopify/polaris-react-archive#285]
# Request
I didn't find an 'Edit' icon in icons folder. Could you please add it?
<img width="33" alt="screen shot 2018-03-27 at 10 25 58" src="https://user-images.githubusercontent.com/8003440/37952686-51b57352-31a9-11e8-9028-cc95012143f8.png">

## Specifications

- Polaris version: 1.12.4

**Comment by ry5n** [comment]
We’re working on a better way to distribute icons. For now, I’ll attach the latest icon here. This has been optimized, so you should be able to use it as is.

[Download edit.svg.zip](https://github.com/Shopify/polaris/files/1858295/edit.svg.zip)

To use this with the `Icon` component, you can use [the solution discussed in #211](https://github.com/Shopify/polaris/issues/211#issuecomment-344295070).

Please re-open this issue if you have any more questions. Thanks!

**Comment by kaelig** [comment]
Polaris icons are now all available via a new npm package called `@shopify/polaris-icons`. Find them alongside usage instructions at https://polaris-icons.shopify.com 💟
