### ISSUE TITLE
Memory leak in Provider/Page actions in embedded apps

### ISSUE THREAD

**Issue by mbaumbach** [Shopify/polaris-react-archive#290]
# Issue summary

The `onAction` function for page actions is triggering for unmounted/modified page actions. This is only happening using the embedded app form of the new `Provider` component.

## Expected behavior

Clicking the page action should only trigger the current `onAction` defined for that action.

## Actual behavior

As you modify the primary or secondary actions on a `Page` component, clicking the action will cause all previously defined actions that were in the same position to trigger as well.

## Steps to reproduce the problem

You must be using this as an embedded app, it works fine with the non-embedded form of the `Provider`. The following component should reproduce the issue. If you observe the console in your dev tools, you'll notice the "Clicking" console log be exponentially output as you click the action. In addition to that, it's also causing the same number of re-renders. Eventually, clicking an action causes the browser to be overwhelmed with re-renders.

```
import React, { Component } from 'react';
import { Provider, Page } from '@shopify/polaris';

export default class EmbeddedContainer extends Component {
  state = {
    page: true
  }

  onClick = () => {
    console.log("Clicking");
    this.setState(state => ({
      page: !state.page
    }));
  }

  render() {
    const { page } = this.state;
    const pageNum = page ? '1' : '2';
    return (
      <Provider
            apiKey={apiKeyHere}
            shopOrigin={`https://storefront-here.myshopify.com`}
            i18n={{}}
            forceRedirect>
            <Page
                title={`Page ${pageNum}`}
                primaryAction={{
                    content: `Save ${pageNum}`,
                    onAction: this.onClick
                }}>
                Page {pageNum}
            </Page>
        </Provider>
    );
  }
}
```

Attached is a GIF of the problem:

![Polaris Bug](https://media.giphy.com/media/5YpC148pyjBjC5AZLv/giphy.gif)

This does **not** happen on 2.0.0-beta.13, so I assume it may have something to do with the `withProvider` HOC now being used in the `Page` component.

## Specifications

- Polaris version: 2.0.0-beta.14 (Does not happen on 2.0.0-beta.13)
- React version: 16.3.1 (Also happens on 16.2.0)
- Browser: Chrome 65.0.3325.181
- Device: MacBook Pro
- Operating System: Mac OS 10.13.4

**Comment by dfmcphee** [comment]
Thanks for the issue @mbaumbach. Can you try removing the empty object from the `i18n` prop and see if you have the same issue?

My guess is that because that object is defined in the prop itself within the render function it will cause it to re-render. Really these object should be static and not reassigned at runtime.

**Comment by mbaumbach** [comment]
@dfmcphee Good catch, that fixed it. 👍 I originally had that in there due to an exception that the ResourceList was throwing shortly after the Provider was introduced in the beta. Glad it was a simple fix, feel free to close if you have no plans to make changes.

**Comment by ry5n** [comment]
Please let us know if you run into this again, or something related. Thanks again for flagging it.
