### ISSUE TITLE
Color Picker bug if not visible at Init

### ISSUE THREAD

**Issue by bluedge** [Shopify/polaris-react-archive#291]
If your page loads with your color picker hidden the mouse event on the color picker will not work. A simple display: none; is used in the css. 
If you load the page showing the color picker everything will work as expected.

A typical use case: You show the color picker only after a user click on a button to toggle the color picker in view. ie. Shopify theme customizer color picker.

Version: @shopify/polaris": 1.13.1

**Comment by ry5n** [comment]
Thanks for asking about this @bluedge. Are you using the Polaris CSS and static markup, or the React version?

**Comment by bluedge** [comment]
Using Polaris CSS with React

**Comment by ry5n** [comment]
OK, thanks. I’ll open an issue in our internal tracker.

**Comment by ry5n** [comment]
@bluedge Any chance you could include a gif, or additional explanation for this? I’d like to investigate further but I’m not sure I understand exactly what’s going wrong.
