### ISSUE TITLE
Add spinner for button component

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris-react-archive#30]
Hi !

We often need (especially in modal that lead to a deletion or for long running tasks) to have a button with a spinner. This is currently the case for instance in the admin when importing large number of products.

Of course there is the app bar feature, but it's often a better experience, especially on delete, to simply show a spinner on the button when clicking on it instead of immediately closing the modal, as some unexpected error could happen during the deletion.

In the button component, adding a "loading" or "spinning" property would be an awesome addition ;).

If you need further details about use cases, do not hesitate to ask me :).

**Comment by lemonmade** [comment]
Thanks for the issue, @bakura10. I've added it to our internal issue tracker to discuss, and I'll post back here when I can give you more details on our plans for this.

**Comment by dfmcphee** [comment]
This was added in 1.6.0
