### ISSUE TITLE
Add forwarding refs to WithProvider wrapper component. (2.0.0-beta.17)

### ISSUE THREAD

**Issue by hasan-aa** [Shopify/polaris-react-archive#301]
# Issue summary
When using refs to access methods of polaris components, a ref to `WithProvider` component is obtained instead of the wrapped component. 

Specifically, I'm trying to access the `open` method of `DropZone` component, but can only obtain a ref to the `WithProvider` component.

## Expected behavior
``` 
<DropZone ref={(ref)=>this.dropZoneRef = ref} />
```
Given above code in the render method of a component, I expect `this.dropZoneRef`  to reference to a `DropZone` instance.

Or, to remove the need for the ref, a property to open the file picker may be considered? 

## Actual behavior
`this.dropZoneRef` is referencing to an instance of `WithProvider`.

## Steps to reproduce the problem

1. Render the `DropZone` component inside a react component and obtain a ref to it. 

## Specifications

- Polaris version: 2.0.0-beta.17
- React version: 16.3.1

**Comment by Hasan-a-ayar** [comment]
@vinay30 definitely!
By the way, I had to use the following function as a workaround for now. 
```javascript  
openFilePicker() {
  //Temporary workaround...
  document.querySelector('.Polaris-DropZone input').click();
}
```

**Comment by dfmcphee** [comment]
Thanks for the opening the issue @Hasan-a-ayar. We opted to go the prop and callback approach for this so that you don't need the ref or instance method.

As of `v2.0.0-rc.1` you can use the `openFileDialog` and `onFileDialogClose` props on drop zone to do this.
