### ISSUE TITLE
Typescript EASDK - Page Breadcrumbs prop only accepts LinkAction[]

### ISSUE THREAD

**Issue by sdn90** [Shopify/polaris-react-archive#306]
# Issue summary

I'm using 2.0.0.beta-18 but took a look at a few 1.x.x releases and the type hasn't changed. 

## Expected behavior

From what I've gathered reading https://github.com/Shopify/polaris/issues/116#issuecomment-334229120 and other issues, 1.7.0 introduced handling for the following to be added to breadcrumbs:
```typescript
interface {
  onAction: () => void,
  target: "app" | "new" | "shopify" | "parent" 
}
```

I'm assuming this is supposed to be referencing EASDKAction?

https://github.com/Shopify/polaris/blob/5de1c3c9872dd4d423f19ed4abcf2d42e98f3e18/src/types.ts#L47-L52

## Actual behavior
```
Type '{ children: Element; title: string; breadcrumbs: { url: string; target: string; }[]; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<Props, ComponentState, never>> & Readonl...'.
  Type '{ children: Element; title: string; breadcrumbs: { url: string; target: string; }[]; }' is not assignable to type 'Readonly<Props>'.
    Types of property 'breadcrumbs' are incompatible.
      Type '{ url: string; target: string; }[]' is not assignable to type 'LinkAction[] | undefined'.
        Type '{ url: string; target: string; }[]' is not assignable to type 'LinkAction[]'.
          Type '{ url: string; target: string; }' is not assignable to type 'LinkAction'.
            Property 'target' does not exist on type 'LinkAction'.
```

## Steps to reproduce the problem

```jsx
<AppProvider apiKey={API_KEY} shopOrigin={SHOP_ORIGIN}>
  <Page
    title="Title"
    breadcrumbs={[{ url: "/products/123", target: "app" }]}
  />
</AppProvider>
```
## Specifications

- Polaris version: 2.0.0.beta-18
- React version: 16.0.36

**Comment by AndrewMusgrave** [comment]
Hi @sdn90, thanks for bringing this up. Target has be added to the breadcrumb prop on page!

**Comment by ry5n** [comment]
With the latest release, this should now be available. Please let us know if you have any further issues with it.
