### ISSUE TITLE
Example Webpack bug

### ISSUE THREAD

**Issue by shenst1** [Shopify/polaris-react-archive#308]
I expect that when I pull down the example webpack application, it would run. Instead I am getting a javascript error. 
```bundle.js:295 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `App`.```

I got this by running
`yarn install` and `yarn start` and then checking the console in the browser.

**Comment by chloerice** [comment]
Hi @shenst1, closing as this was fixed with the release of v2.0.0.
