### ISSUE TITLE
what do you guys use to generate the style guide?

### ISSUE THREAD

**Issue by chrisdrackett** [Shopify/polaris-react-archive#31]
Sorry that this issue isn't directly related to this codebase, but I'm really impressed with the style guide and I'm curious how you guys are building that.

**Comment by lemonmade** [comment]
Thanks for the kind words! We'll hopefully release the app for the style guide as an open source project eventually, though it's currently a bit of a mess.

Basically, we parse the markdown files for components and for other design/ content pages. Those files have YAML front-matter that's used to construct the basic structure of the site. The rest of the content is parsed into a few small model objects (for example, we parse out the component's name, its examples, its props, and the rest of its description content into an object). The styleguide is then simply a React app that loads those objects via GraphQL. The only other piece that's meaningfully strange is the parts where we have "components" described in markdown files. For those, we denote the component that should be used using an HTML comment in markdown, parse that out, render the right component with that content to a string that's included in the initial HTML payload, then rehydrate it on the client as you typically would for a React app.

There's lots more there (the examples section relies on some pretty crazy regular expressions to figure out what props are changing as you edit code), but hopefully that gives you a reasonable idea.

**Comment by dlewand691** [comment]
Please! This would be great to see how you built things. I'm using this as a "best practice" example for my team to follow. Thank you for the inspiration!
