### ISSUE TITLE
Documentation on Componants > Navigation > Link doesn't load.

### ISSUE THREAD

**Issue by next-door-nate** [Shopify/polaris-react-archive#32]
# Issue summary

When navigating to the page https://polaris.shopify.com/components/navigation/link (either through the link on the pagination page or by going directly to it) the page content doesn't load.

## Expected behavior

It should load the documentation.

## Actual behavior

It doesn't load the documentation,  it remains stuck in the loading state.

## Steps to Reproduce the Problem

1. Navigate to the page https://polaris.shopify.com/components/navigation/link

## Specifications

- Polaris version: 1.0.2
- React version: I don't know. 15 something something
- Browser: Chrome 57.0.2987.133 (64-bit)
- Device: Macbook Pro
- Operating System: MacOS

**Comment by lemonmade** [comment]
Thanks for the issue, @Natewich. We'll be getting that documentation up ASAP.

**Comment by ry5n** [comment]
Documentation for the Link component [is now up](https://polaris.shopify.com/components/navigation/link). 🎉
