### ISSUE TITLE
Possible typo in the Color Combinations section

### ISSUE THREAD

**Issue by kylegach** [Shopify/polaris-react-archive#33]
# Issue summary
See below. I would’ve submitted a PR, but 1) you’re not accepting those yet and 2) I couldn’t find the source of the text to edit.

## Expected behavior
In the ‘Do’ column, based on the code sample below it, it seems like it should say:

> Use any light background color with its corresponding _dark_ color for an action

## Actual behavior
It currently says:

> Use any light background color with its corresponding primary color for an action

## Steps to Reproduce the Problem
1. https://polaris.shopify.com/visuals/colors#color-combinations
2. Scroll down a bit

**Comment by kylegach** [comment]
Btw, you have a seriously beautiful and seeming very, very useful design system here. Nice work!

**Comment by ry5n** [comment]
Thanks for the props. And thanks for this catch—I think you’re right. I’ll open an issue in our internal tracker to fix this up. You should see it in a future version of the style guide.
