### ISSUE TITLE
Application for rendering components

### ISSUE THREAD

**Issue by FauzanKhan** [Shopify/polaris-react-archive#338]
Are there any plans for open sourcing the [app](https://polaris.shopify.com/components/get-started) used for showcasing Polaris components?

It can prove to be a great alternative to [storybook](http://storybook.org/) and [styleguidist](https://github.com/styleguidist/react-styleguidist) with its intuitive UI. We'd definitely appreciate it and would be happy to contribute to it if it gets open sourced.

**Comment by solonaarmstrong** [comment]
We are in the process of discussing what will be open sourced and we will let you know if the style guide becomes an open source repository.

**Comment by imgntn** [comment]
i'm also looking for any resources on integration Polaris w/ Storybook, if anyone sees  anything around!

**Comment by imgntn** [comment]
this is working for me so far:

```
import {
    AppProvider,
    Button,
} from '@shopify/polaris';

import '@shopify/polaris/styles.css';


const AppProviderDecorator = (storyFn) => (
    <AppProvider
    apiKey='narf'
    shopOrigin='https://narf.myshopify.com'
  >
    { storyFn() }
  </AppProvider>
);

addDecorator(AppProviderDecorator);
```

and then all the components below should be wrapper in their own app provider.  not sure whether this is recommended but it seems okay in my early tests
