### ISSUE TITLE
Web.UIKit.sketch Typestyle 02 Subheading weight is wrong

### ISSUE THREAD

**Issue by humso** [Shopify/polaris-react-archive#34]
# Issue summary

On the Web.UIKit.sketch the typestyle 02 Subheading is using semibold but the weight reads bold.

## Specifications

- Polaris version: v1.0.2

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by lemonmade** [comment]
Thanks for the issue, @humso. We've added this to our internal issue tracker, and I'll close this once we ship a fix in the next release.

**Comment by jessebc** [comment]
Fixed in Abstract Master.
