### ISSUE TITLE
Unknown 'micro' type scale mentioned in documentation

### ISSUE THREAD

**Issue by bouk** [Shopify/polaris-react-archive#35]
Hi,

The type scale 'micro' is mentioned under https://polaris.shopify.com/visuals/typography#emphasis-styles, but that doesn't seem to be on the type scale. I assume this was defined in a previous version and left in accidentally 

![image](https://cloud.githubusercontent.com/assets/97820/25490956/77b7ce5c-2b3c-11e7-97f0-08c1902a5a43.png)

**Comment by lemonmade** [comment]
Thanks for the issue, @bouk. That should read "Caption" instead of "Micro", as `Caption` is the component that represents that text style. I've added it to our internal issue tracker and I'll close this issue once it's resolved.

**Comment by dfmcphee** [comment]
This is now resolved.
