### ISSUE TITLE
z-index not working properly

### ISSUE THREAD

**Issue by dlhck** [Shopify/polaris-react-archive#37]
# Issue summary

Some components like Badges, or the ResourceList in focused state overlap other elements. Tried to add z-index to the components, but not working at all. 

<img width="1072" alt="bildschirmfoto 2017-04-27 um 19 37 42" src="https://cloud.githubusercontent.com/assets/24294584/25496483/75722f8a-2b81-11e7-82e1-bd7ce7a5914c.png">

- Polaris version: 1.0.2
- React version: 15.5.4
- Browser: Chrome 
- Device: Macbook Pro 2015 Retina 
- Operating System: macOS Sierra 10.12.4

**Comment by lemonmade** [comment]
Hey @davidhoeck, what component is it that's being overlaid on the page there? It looks like maybe a Popover but I can't tell for sure. If it is, we may have some issues with the logic our Popover uses to calculate the right z-index for itself.

**Comment by davidhoeck** [comment]
Hi @lemonmade ... It's a "custom component" .. just a div with a class, wrapping a ResourceList! I set the z-index of this class to 9999 ... didn't change the problem at all.

**Comment by lemonmade** [comment]
Our approach to z-index is a little unusual in that each component creates its own stacking order internally, and it assumes that somewhere higher in the application a stacking order will be set that causes overlays to be positioned above application content.

It's a little tricky to diagnose without seeing the actual markup, but what we've typically been doing is having some sort of "Frame" component that wraps the entire application. It sets itself to be relatively positioned, and then sets the z-index for each of the children to create a kind of application-wide stacking order. So, with markup like this:

```js
<div className="App">
  <div className="Overlay" />
  <div className="Main"
    {/* rest of application here */}
  </div>
</div>
```

We would have some CSS to force all application content to be below the overlay layer like this:

```css
.App {
  position: relative;
}

.Overlay {
  position: absolute;
  z-index: 20;
}

.Main {
  position: relative;
  z-index: 10;
}
```

Hopefully that helps. For now I'm going to close this issue though, as I don't think there's anything actionable on our end to address this (happy to reopen if I am misunderstanding, though!)

**Comment by davidhoeck** [comment]
@lemonmade will try that .. thanks for helping me!!

**Comment by davidhoeck** [comment]
@lemonmade  working! thx!
