### ISSUE TITLE
Chart Type is blank

### ISSUE THREAD

**Issue by goodnightjj** [Shopify/polaris-react-archive#39]
# Issue summary

Chart Type is blank.

## Expected behavior

There is content about it.

## Actual behavior

Chart Type is listed on sidenav of polaris.shopify.com/visuals/data-visualizations but there's content.

## Steps to Reproduce the Problem

1. Go to polaris.shopify.com/visuals/data-visualizations
2. Select Chart Type on the sidenav
3. Nothing happens

## Specifications

- Polaris version:
- React version:
- Browser: Chrome
- Device: Macbook
- Operating System: OSX

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by lemonmade** [comment]
Thanks for the issue, @goodnightjj. You are absolutely correct, not quite sure how that happened! I've added this to our internal issue tracker and will close this one once we ship the fix.
