### ISSUE TITLE
Documentation: Color Palette

### ISSUE THREAD

**Issue by fighella** [Shopify/polaris-react-archive#41]
# Issue summary

In the Color Palette in the documentation, "Title Bar" does not have a Sass representation.

Should it?

https://polaris.shopify.com/visuals/colors

**Comment by ry5n** [comment]
Thanks for catching this—it’s an issue with the styleguide site so I’ve opened an issue on our styleguide repo to address it. I’ll keep you posted and will close this issue once we’ve resolved it.

One thing to note is that these colors are only intended for the top bar component in Polaris apps. If you’re building a Shopify app or channel using the EASDK the top bar is provided by the admin itself.
