### ISSUE TITLE
The No symbol used in error states is incorrect

### ISSUE THREAD

**Issue by heyneff** [Shopify/polaris-react-archive#42]
# Issue summary
The symbol should be rotated 90°.

## Expected behavior
The No symbol or prohibition sign has a diagonal line running from top left to bottom right.
<img width="152" alt="iso 3864-1 prohibition sign" src="https://cloud.githubusercontent.com/assets/3827051/25558983/bbd81622-2ce6-11e7-8cec-96905d75a652.png">
https://en.wikipedia.org/wiki/No_symbol

## Actual behavior
The symbols in Web.UIKit.sketch **Components** page on the **🖥 Feedback indicators - Banners** 
and **📱 Feedback indicators - Banners** artboards have diagonal lines running from top right to bottom left.
<img width="160" alt="polaris no symbol" src="https://cloud.githubusercontent.com/assets/3827051/25558988/eca53b18-2ce6-11e7-9dc6-31d56acf7131.png">

**Comment by AdamWhitcroft** [comment]
TIL. Thanks for picking up on this! Updated, as per https://share.abstractapp.com/0a8f916e-c54c-42d5-a1cc-ab9d6f78d042

**Comment by heyneff** [comment]
👍 The guidelines and UI Kit Sketch file are amazing. Keep up the good work.

**Comment by lemonmade** [comment]
Fixed in version 1.0.3.
