### ISSUE TITLE
CSS only embedded app SDK usage

### ISSUE THREAD

**Issue by coler-j** [Shopify/polaris-react-archive#43]
# Issue summary

It is unclear whether embedded apps will continue to use the SDKs ShopifyApp.Bar from the javascript API (and it's breadcrumbs and primary/secondary buttons), or whether the app bar will disappear in the new version in favor of the new Polaris page header navigation style (without the app bar).

Will the app bar be disappearing with the release of Polaris? Or will _javascript_ instantiated components (breadcrumbs, titles, etc.) be rendered with Polaris style when using the javascript API going forward?

## Expected behavior

The javascript initialized app bar gets styled to match Polaris page header styling.

## Actual behavior

It is unclear whether a CSS only embedded app should use the ShopifyApp.Bar or should use html/CSS for the Polaris Page Header Elements and not use the ShopifyApp.Bar.

## Steps to Reproduce the Problem

1. Have a CSS only embedded app
2. Use the Shopify embedded app SDK
3. Wonder what page header navigation system you are supposed to use.

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by lemonmade** [comment]
Hey @coler-j. Regardless of whether you are using the CSS-only or React builds, apps will update to present their title/ actions/ breadcrumbs on the page, instead of in the title bar as they currently are. Both the existing EASDK and the embedded React components distributed through Polaris use the same APIs to set the header in the main admin page, and in either case the new designs for that header will be turned on for apps on May 23.

I'll leave a note to make this more clear in our documentation.

**Comment by JoshHighland** [comment]
@lemonmade what's the new date for this? May 23 has come and gone.

**Comment by lemonmade** [comment]
Hey @JoshHighland, sorry for the delay. Should be in the first half of June.

**Comment by coler-j** [comment]
Hi, it appears that this wasn't true. There is still an app bar on my embedded apps not using the react components. Instead of the embedded js methods converting to the page property components as described by @lemonmade above. Is this how it is going to be then? For css only apps, do we need to use the css/html of the page components manually and discard using the embedded app sdk js methods?

**Comment by lemonmade** [comment]
We are still working through some iteration on the embedded app bar. From an app's perspective, it shouldn't change anything either way: if you are using the React components, continue using them as-is. If you are using CSS-only and the EASDK, omit everything from `.Polaris-Page__Header` on down in the page component, and instead communicate that information via the relevant methods in the EASDK.
