### ISSUE TITLE
[Popover] Vertical padding larger than horizontal

### ISSUE THREAD

**Issue by mbaumbach** [Shopify/polaris-react-archive#4503]
## Issue summary

The vertical padding (top and bottom) seems to be a bit larger than the horizontal (left and right) padding on the `Popover` now.

## Expected behavior

I expected the padding surrounding the content of the `Popover` to be consistent on all edges. If this is intended spacing, feel free to close this issue.

## Actual behavior

When the `Popover` comes up, a visible difference in padding between top/bottom vs left/right from the edge of the action list item appears to be a bug. See screenshot:

![image](https://user-images.githubusercontent.com/48250/135513936-d9ea3338-2697-4277-bfd2-ffde2ec124c9.png)

## Steps to reproduce the problem

1. Create a `Popover` with an `ActionList`
1. Open the `Popover`
1. Hover over an `ActionList` item.

## Reduced test case

This is visible on Polaris example for "Popover with action list" here: https://polaris.shopify.com/components/overlays/popover

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 7.0.0
- Browser: Chrome Version 94.0.4606.61 (Official Build) (x86_64)
- Device: MacBook Pro
- Operating System: macOS Big Sur 11.6

**Comment by alex-page** [comment]
@mbaumbach this appears to be fixed. Let me know if you can still replicate this issue.

**Comment by mbaumbach** [comment]
Looks fixed to me in 9.7.0, thanks @alex-page!
