### ISSUE TITLE
IndexTable Scroll Bar Removal

### ISSUE THREAD

**Issue by Menna-Alsherif** [Shopify/polaris-react-archive#4504]
## Issue summary

I want to remove the scroll bar from the indexTable.

## Steps to reproduce the problem

1. First step
1. Second step

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

**Comment by alex-page** [comment]
Hey @Menna-Alsherif thanks for opening this issue. We are developing the `IndexTable` right now and I will pass this feedback onto the team. I am going to close this issue as it is a feature request.

Was there an experience you were making where the scroll bar inhibited what you wanted to make?
