### ISSUE TITLE
Navigation: SubNavigationItems don't have selected property / url is required

### ISSUE THREAD

**Issue by Xilver** [Shopify/polaris-react-archive#4512]
## Issue summary

In the Navigation component, main navigation items have the possibility to have `url` optional, while having an `onClick` handler. We can't use routing in our app, so this is perfect for conditionally rendering our pages. However, in sub navigation items, the `url` property is required. Furthermore, the `selected` property does not exist in sub navigation items.

## Expected behavior

Sub navigation items should work the same as main navigation items, where `url` is optional, and with a `selected` property

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 7.0.0
- Browser: all
- Device: all
- Operating System: all

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

**Comment by slince** [comment]
+1

**Comment by alex-page** [comment]
@Xilver I don't see any problems with this suggestion. I don't have context on why this was implemented in this way originally. If you want to make a pull request please do. I am going to close this as it's a feature request.

**Comment by Michael-Gibbons** [comment]
@alex-page With the new release of the nodeJS express boiler which uses `react-router-dom`, this becomes an issue. SubNavigationItems are basically unusable because we need to handle client side routing with react router, but since the url property is required it breaks. imo bug tag isn't unreasonable

**Comment by Michael-Gibbons** [comment]
Also @alex-page I believe the mandatory url used to be the case for main navigation items as well but it was updated to the current functionality and subnavigation was just never updated
