### ISSUE TITLE
Topbar: Always show navigation toggle

### ISSUE THREAD

**Issue by mateusvahl** [Shopify/polaris-react-archive#4513]
## Feature request summary

I would like to have the option to always display the navigation toggle(hamburger menu), main reason for this is for saving the layout spacing, which becomes really important when you have super long tables.

<img width="957" alt="navigation toggle" src="https://user-images.githubusercontent.com/4995440/137381875-324788cb-ae9a-4a4e-a7d4-ac6f6daf9872.png">

Thanks!

**Comment by mateusvahl** [comment]
Related to that: I couldn't really find a way of replicate Shopify top bar `logo` section:

<img width="1398" alt="Shopify topbar" src="https://user-images.githubusercontent.com/4995440/137764382-a1a3c949-7077-4a7a-8e84-e68530b674d2.png">

**Comment by alex-page** [comment]
Hey @mateusvahl to change the icon you can add an icon to the `<Frame>` component. As of now we are not going to make the navigation flexible. It is built into our product and is very opinionated for that reason.

Let me know if you are having an issues with the replacing the logo.
