### ISSUE TITLE
wish "selectedResources" could be initialize

### ISSUE THREAD

**Issue by tomclues** [Shopify/polaris-react-archive#4514]
## Feature request summary

"selectedResources" could be initialize. for example, when I open the indexTable which is could show the items that has been selected, then I could change the selected items. 

## Rationale
Program source code: utilities/use-index-resource-state.ts  :40 line
`  const [selectedResources, setSelectedResources] = useState(
    initSelectedResources,
  );`.    
need to Initialize the array with the data I requested back
thanks very much :)

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

**Comment by alex-page** [comment]
Hey @quanscheng we are working on some big changes for `IndexTable`. If you would like to see this change I would love to review a pull request. I will keep this in mind as we work on the component. I am going to close this issue for now but feel free to reopen it.
