### ISSUE TITLE
Why TextField is not updated with setState

### ISSUE THREAD

**Issue by alexserranosv** [Shopify/polaris-react-archive#4516]
I am using React, Polaris and Node, to develop an app for shopify

When I try to dynamically update the value of the first TextField using this.state with data obtained with axios this does not work, if I get the title, I send it as a parameter for the component, the value is not rendered, but if it is sent to the JSX of the component.

`import React, { Component, Fragment, useState, useRef } from "react";
import { Heading, Button } from "@shopify/polaris";
import axios from 'axios';
import { TextFieldTitulo } from './TextFieldTitulo';
 `

`state = {
        title: '',
    }`

    async componentDidMount() {
        await this.getShops();
    }

    getShops = async () => {
        const queryString = window.location.search;
        const urlParams = new URLSearchParams(queryString);
        const key = urlParams.get('key');

        let URI = 'http://localhost:8081/api/aplicativo/' + key;
        const res = await axios.get(URI);
        this.setState({
            title: res.data.titulo
        })
    }`

`<TextFieldTitulo value={this.state.title} />`

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

**Comment by vanduc1102** [comment]
Hi @XanderXS , you are using `TextFieldTitulo` , not `TextField` from Polaris,

Could you redo your code in with https://codesandbox.io/s/up70v?module=App.js ?

**Comment by alex-page** [comment]
Closing this issue as it looks like a typo with the import and component usage. Thanks @vanduc1102 for jumping in with a reply :legend:
