### ISSUE TITLE
Add an inset box-shadow to the color picker to make it easier to see the draggers on Slidable components.

### ISSUE THREAD

**Issue by utkarshsaxena93** [Shopify/polaris-react-archive#4517]
## Feature request summary
We should add an inset box-shadow to the color picker. This will make it so it's easier to see the controls, as currently the transparency (alpha) picker doesn't look great when on a white background as the controls fade into the background.

## Rationale

Expected:

<img width="561" alt="Screen Shot 2021-10-19 at 10 04 34 AM" src="https://user-images.githubusercontent.com/1416436/137926387-38429b32-51f1-4984-8f33-4184ff6c3acb.png"/>

Actual:

<img width="292" alt="Screen Shot 2021-10-19 at 10 04 44 AM" src="https://user-images.githubusercontent.com/1416436/137926358-e9db8c8d-26f6-4bad-bea3-b895acc97856.png">

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).
