### ISSUE TITLE
Allow disabled color for Icon component

### ISSUE THREAD

**Issue by utkarshsaxena93** [Shopify/polaris-react-archive#4518]
## Feature request summary
`Icon` component does not accept `disabled` as a value for `color`. This should be allowed as we have the appropriate variable for the `disabled` color: `--p-icon-disabled`
`<Icon source={PlusMinor} color={ 'disabled'} />`
## Rationale
This will allow us to set the correct color for the icon.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by alex-page** [comment]
@utkarshsaxena93 is this still needed? I would like to see a lot more flexibility for color and it's relation to icons. I am going to close this but feel free to reopen this and make a PR if you need it urgently.
