### ISSUE TITLE
[Layout foundations] Audit layouts within components

### ISSUE THREAD

**Issue by yesenia-perezcruz** [Shopify/polaris-react-archive#4526]
[Collection of product team needs](https://docs.google.com/document/d/1mLqyvRrHXIWE_w2dxgqf6HXpeblW6-Nb75D1cWKO4DM/edit)

Today, our only view is a "Page.
![Screen Shot 2021-10-21 at 11 06 08 AM](https://user-images.githubusercontent.com/47306956/138471523-e30a3788-3615-43cf-89b9-46ea591ed5cd.png)" 

Issues we're seeing with no layout and structure primitives:

- Form fields span the full-width of a Card instead of matching the size of the expected input
- No easy way to display extensions alongside core admin or launch full-screen

**Comment by zecarlostorre** [comment]
We had this issue already in the board, @adrianefong I think this is inline with what you're looking at, so I changed the issue title and assigned it to you.

**Comment by laurkim** [comment]
Closing because we're tracking the work in issue #6901
