### ISSUE TITLE
Get indexes on mainline

### ISSUE THREAD

**Issue by yesenia-perezcruz** [Shopify/polaris-react-archive#4531]
There are currently 6 versions of Indexes in the admin which makes it impossible to roll out an improvement that teams can get for free. (i.e. An improvement to filters could not be rolled out globally)

**Comment by alex-page** [comment]
This work has begun.

- [x] Added a CODEOWNERS file to make sure shopify/web IndexTable does not get new features added
- [ ] [Index filter and search updates](https://vault.shopify.io/projects/24858) will include replacing the forked IndexTable with the Polaris one

**Comment by alex-page** [comment]
@mrcthms closing this issue. Thank you for this work!
