### ISSUE TITLE
[MediaCard] Extraneous space when card has no actions

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris-react-archive#4534]
## Issue summary

In vertical view (smaller viewports), MediaCard without `primaryAction` or `secondaryAction` has extra space at the bottom.

## Expected behavior (no extraneous space between description and bottom)

![1jxxq csb app_ (4)](https://user-images.githubusercontent.com/85783/138160135-d2405950-1efa-4dda-aad4-0ecff792ffaa.png)

## Actual behavior (extraneous space between description and bottom)

![1jxxq csb app_ (3)](https://user-images.githubusercontent.com/85783/138160141-053032ab-03ea-4d12-961a-64520ebfef4f.png)

## Reduced test case

```tsx
      <MediaCard
        title="Turn your side-project into a business"
        description={`In this course, you’ll learn how the Kular family turned their mom’s recipe book into a global business.`}
      >
        <VideoThumbnail
          videoLength={80}
          thumbnailUrl="https://burst.shopifycdn.com/photos/business-woman-smiling-in-office.jpg?width=1850"
        />
      </MediaCard>
```

https://codesandbox.io/s/determined-flower-1jxxq?file=/App.js

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 7.0.0

**Comment by emilycritter** [comment]
First time participating in Hacktoberfest and am picking up this issue 🎉
