### ISSUE TITLE
Interactive patterns

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#4536]
So much of Admin revolves around interactive tasks — Navigating, Creating, Reading, Updating and Deleting things. Right now, every team is implementing their own version of this without guidance. Sometimes it results in an index view, sometimes an autocomplete. Merchants never know what to expect.

The admin DL should provide consistent patterns for this. As an example, anywhere where you can Delete a list item, there should be a consistent pattern in place.

- [ ] Delete patterns for pages, cards, modals, lists...
- [ ] Create patterns for pages, cards, modals, lists...
- [ ] Update patterns for pages, cards, modals, lists...
- [ ] Navigation patterns for pages, cards, modals, lists...
- [ ] Interactive patterns for links, buttons, form elements...

**Comment by sarahill** [comment]
What's the difference between this issue and this issue https://github.com/Shopify/polaris-react/issues/4521?

**Comment by alex-page** [comment]
Crikey. Moving this over.
