### ISSUE TITLE
Decrease baseline sizing and spacing in admin

### ISSUE THREAD

**Issue by yesenia-perezcruz** [Shopify/polaris-react-archive#4539]
Default sizing (of text and space) in the admin feels too large and airy
![Screen Shot 2021-10-25 at 10 43 35 AM](https://user-images.githubusercontent.com/47306956/138717186-1c08b20a-faeb-4f37-9d4a-0ff1b45a54d6.png)

it also does not scale well on low quality monitors where you need to command - several times for the UI to be usable. 
![Screen Shot 2021-10-25 at 10 40 06 AM](https://user-images.githubusercontent.com/47306956/138717355-ac3244bd-0972-4a63-abb2-0029970759ee.png)
![Screen Shot 2021-10-25 at 10 46 06 AM](https://user-images.githubusercontent.com/47306956/138717743-56739731-5052-45b3-8c22-07106b190840.png)

- [x] #4543
![Screen Shot 2021-10-25 at 10 43 35 AM](https://user-images.githubusercontent.com/47306956/138717964-0267066b-4058-49e1-b3d5-bafb3c126511.png)

- [ ] What can we do to adjust the size and scale so that it works better (scales better) for low quality monitors?

**Comment by alex-page** [comment]
- The base font-size is set to font-size: 62.5%; which turns into 10px. This causes poor scaling and a bunch of odd rem values. [This PR](https://github.com/Shopify/polaris-react/pull/1590) shipped to fix the issue then got reverted.
- We could use the clamp property in CSS to [better style the font-sizes responsively](https://moderncss.dev/generating-font-size-css-rules-and-creating-a-fluid-type-scale/). There are also techniques to scale font-sizes based off browser width. 
- Our breakpoints in polaris-react and shopify/web could use some love and centralisation

**Comment by ouellettejordan** [comment]
There seems to be some bespoke spacing issues on both the Analytics page and Finances pages. Their headers sit higher than all the other pages...

<img width="1952" alt="Screen Shot 2021-10-27 at 1 26 13 PM" src="https://user-images.githubusercontent.com/12194323/139117636-09de7b5f-9bc4-479f-ba53-671b9803f750.png">

**Comment by alex-page** [comment]
@ouellettejordan is this maybe because the buttons don't exist on those pages? I wonder if the height of the area changes without them, moving the title text. This shouldn't be the case but just a quick thought/observation.

**Comment by ouellettejordan** [comment]
Possibly. But needs to be fixed regardless.

**Comment by sarahill** [comment]
Closing in favor of https://github.com/Shopify/web/issues/52575

We are still investigating other Density improvements and will open another issue for those.
