### ISSUE TITLE
Link styling

### ISSUE THREAD

**Issue by jjgali** [Shopify/polaris-react-archive#4548]
## Issue summary

In an effort to up-level the quality of the admin and in particular its [interaction patterns](https://github.com/Shopify/polaris-react/issues/4536), we want to reconsider styling and hierarchy of links (and some buttons). Questions to ask include:
- Should we use external link icons? If so, when?
- Should we allow variations in link styles? Why or why not?
- Should links and plain buttons have distinct styling?
- When is it appropriate to use a link vs a button?

If you can think of any others, please add them to this description!

**Comment by alex-page** [comment]
We should ship the simplest solution and break things.

**Comment by jjgali** [comment]
This issue is a bit big, and progress is getting bogged down. Will close this issue and begin addressing more digestible facets of link styling. To start with, we'll be tackling removing the external link icon: https://github.com/Shopify/polaris-react/issues/4547
