### ISSUE TITLE
[IndexTable] Condensed cells warning

### ISSUE THREAD

**Issue by amireynoso** [Shopify/polaris-react-archive#4567]
## Issue summary

When using an `<IndexTable.Cell />` in the context of a `condensed` `<IndexTable />`, a DOM validation warning gets triggered ("`<td>` cannot appear as a child of `<li>`"). This is because both `<IndexTable />` and `<IndexTable.Row />` change their markup to be an unordered list, and the cell component remains unchanged.

This leaves it up to the consumer to make the call, based on the condition used to set `condensed`, whether to render `<IndexTable.Cell />`.

## Expected behavior
`<IndexTable.Cell />` should be aware of the `condensed` prop and change its markup accordingly.

## Actual behavior
`<IndexTable.Cell />` does not change its markup based on the `condensed` prop. However, `<IndexTable/>` and `<IndexTable.Row />` do.

## Steps to reproduce the problem

Create an `<IndexTable />` with rows and cells. Pass the `condensed` prop to `<IndexTable />`.

## Reduced test case

- [Standalone view](https://jydtg.csb.app/) (see the console warnings)
- [Code](https://codesandbox.io/s/condensed-index-table-jydtg?file=/App.js)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 7.2.0
- Browser: Chrome
- Device: MacBook Pro
- Operating System: macOS 12.0.1

**Comment by grahamsutton** [comment]
I am also getting this issue in Polaris 12.0.1. It happens by assigning the `condensed` prop to `true`, which logs the warning `Warning: validateDOMNesting(...): <td> cannot appear as a child of <li>.`

I removed all content from my `IndexTable.Cell` components and the issue still persists. This confirms to me that it's coming from the Polaris library and not any custom content I defined.

**Comment by daviareias** [comment]
I get it as well, it seems that condensed props leads to bad DOM nesting

**Comment by tajbowness** [comment]
Hello, this is still an issue.

**Comment by meecrobe** [comment]
Still an issue in `13.9.4`
