### ISSUE TITLE
Add `dismissOnAction` property to ToastProps

### ISSUE THREAD

**Issue by cphelefu** [Shopify/polaris-react-archive#4577]
## Feature request summary
Toast trigger onDismiss after the set duration; but sometimes you would also like the action to trigger onDismiss. Thus you need a property to make this possible.
* Note: This property is also important and need for making `useImperativeToast` in Web admin be able to dismiss a toast.

## Rationale

* To be able to dismiss the Toast when an action is clicked without adding another `useState` properly.
* This is needed for the useImperativeToast in web admin.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by yurm04** [comment]
Thanks for the request, @cphelefu. We’re not actively working on this right now, but we’d love for it to make its way into the system. Please feel free to contribute and open a PR!
