### ISSUE TITLE
Move layout-width() function values to tokens

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#4609]

**Comment by lgriffee** [comment]
### Audit Findings 
I conducted a [quick audit of all `layout-width()` instances](https://docs.google.com/spreadsheets/d/1ea8P4vp9njh96yYcVp9_DXr3GpdP6E0LSk6aCE7zHY8/edit?usp=sharing) in polaris-react and web. 

Below is a brief summary of those findings:
#### Layout-width()
| Name                                            | Value                                                                                  | \# polaris-react Instances | \# web Instances      |
| ----------------------------------------------- | -------------------------------------------------------------------------------------- | -------------------------- | --------------------- |
| layout-width(primary, min)                      | rem(480px)                                                                             | 2 results / 2 files        | 0                     |
| layout-width(primary, max)                      | rem(662px)                                                                             | 5 results / 5 files        | 0                     |
| layout-width(secondary, min)                    | rem(240px)                                                                             | 2 results / 2 files        | 0                     |
| layout-width(secondary, max)                    | rem(320px)                                                                             | 3 results / 3 files        | 0                     |
| layout-width(one-half-width, base)              | rem(450px)                                                                             | 1 result / 1 file          | 0                     |
| layout-width(one-third-width, base)             | rem(240px)                                                                             | 1 result / 1 file          | 0                     |
| layout-width(nav, base)                         | rem(240px !default)                           | 0                          | 0                     |
| layout-width(page-with-nav, base)               | rem(769px)                                                                             | 0                          | 0                     |
| layout-width(page-content, not-condensed)       | rem(680px)                                                                             | 1 result / 1 file          | 0                     |
| layout-width(page-content, partially-condensed) | rem(450px)                                                                             | 1 result / 1 file          | 0                     |
| layout-width(inner-spacing, base)               | spacing()                                                                              | 0                          | 0                     |
| layout-width(outer-spacing, min)                | spacing(loose)                                                                         | 1 result / 1 file          | 0                     |
| layout-width(outer-spacing, max)                | spacing(extra-loose)                                                                   | 1 result / 1 file          | 0                     |

_Notes_
- In the usage of these values some are added together, multiplied by 2, and used inside em() - see [spreadsheet](https://docs.google.com/spreadsheets/d/1ea8P4vp9njh96yYcVp9_DXr3GpdP6E0LSk6aCE7zHY8/edit?usp=sharing) for more details

#### Other Layout functions (in _layout.scss file)
| Name                                            | Value                                                                                  | \# polaris-react Instances | \# web Instances      |
| ----------------------------------------------- | -------------------------------------------------------------------------------------- | -------------------------- | --------------------- |
| top-bar-height()                                | rem(56px)                                                                              | 15 results / 8 files       | 18 results / 18 files |
| mobile-nav-width()                              | calc(100vw - #{rem(32px) + spacing() \* 2}) | 2 results / 2 files        | 3 results / 3 files   |
| nav-min-window-corrected()                      | rem(769px)                                                                             | 19 results / 5 files       | 23 results / 23 files |
### Proposed Token Values 
Based on the values currently being used in the repo, here are some possible token names:
| Value (px) | Value (rem) | Token Name (Placeholder - Not Proposed) | Token Name     |
| ---------- | ----------- | --------------------------------------- | -------------- |
| 240px      | 15rem       | \--p-layout-240                         | \--p-layout-?? |
| 320px      | 20rem       | \--p-layout-320                         | \--p-layout-?? |
| 450px      | 28.125rem   | \--p-layout-450                         | \--p-layout-?? |
| 480px      | 30rem       | \--p-layout-480                         | \--p-layout-?? |
| 662px      | 41.375rem   | \--p-layout-662                         | \--p-layout-?? |
| 680px      | 42.5rem     | \--p-layout-680                         | \--p-layout-?? |
| 769px      | 48.063rem   | \--p-layout-769                         | \--p-layout-?? |

How these tokens would replace the current values: 
#### Layout-width()
| Old Function                                    | Value                                                                                  | Replacement Token (w/ Placeholder names) |
| ----------------------------------------------- | -------------------------------------------------------------------------------------- | ------------------------------------- |
| layout-width(primary, min)                      | rem(480px)                                                                             | \--p-layout-480                       |
| layout-width(primary, max)                      | rem(662px)                                                                             | \--p-layout-662                       |
| layout-width(secondary, min)                    | rem(240px)                                                                             | \--p-layout-240                       |
| layout-width(secondary, max)                    | rem(320px)                                                                             | \--p-layout-320                       |
| layout-width(one-half-width, base)              | rem(450px)                                                                             | \--p-layout-450                       |
| layout-width(one-third-width, base)             | rem(240px)                                                                             | \--p-layout-240                       |
| layout-width(nav, base)                         | rem($navigation-width)<br>$navigation-width: 240px !default;                           | \--p-layout-240                       |
| layout-width(page-with-nav, base)               | rem(769px)                                                                             | \--p-layout-769                       |
| layout-width(page-content, not-condensed)       | rem(680px)                                                                             | \--p-layout-680                       |
| layout-width(page-content, partially-condensed) | rem(450px)                                                                             | \--p-layout-450                       |
| layout-width(inner-spacing, base)               | spacing()                                                                              | Replace with spacing token            |
| layout-width(outer-spacing, min)                | spacing(loose)                                                                         | Replace with spacing token            |
| layout-width(outer-spacing, max)                | spacing(extra-loose)                                                                   | Replace with spacing token            |

#### Other Layout functions (in _layout.scss file)
| Old Function                                    | Value                                                                                  | Replacement Token (w/ Placeholder names) |
| ----------------------------------------------- | -------------------------------------------------------------------------------------- | ------------------------------------- |
| top-bar-height()                                | rem(56px)                                                                              | Replace with spacing token            |
| mobile-nav-width()                              | calc(100vw - #{rem($dismiss-icon-size) + spacing() \* 2})<br>$dismiss-icon-size: 32px; | ??                                    |
| nav-min-window-corrected()                      | rem(769px)                                                                             | \--p-layout-769                       |

### Questions
- What naming conventions and values should we move forward with? 
- Should naming follow a similar logic to what we choose for spacing?
- How will the work to replace rem() and em() effect this work?
- Do we need to take into account/address any calc()s being made (adding or multiplying values)?

**Comment by BPScott** [comment]
Lots of layout width values are used within _breakpoints.scss, and in calls to `breakpoint-*()`, where they are used for the construction of media queries. You can't use custom properties in media queries as media queries sit "above" the html structure of a page.

It'd be worth considering that when creating these tokens, as I suspect many of these values would only only been used in the creation of media queries. At which point there's no value in creating a custom property token for them as you wouldn't be able to use them in the act of constructing the media query.

**Comment by aaronccasanova** [comment]
Ben makes a good point. A majority of the `layout-width` instances are used to construct breakpoints and thus can't simply be converted to tokens. We may be able to leverage the [postcss-custom-media](https://github.com/postcss/postcss-custom-media) plugin and generate the `@custom-media` queries from our json tokens in addition to the standard `--p-layout-width-x` tokens. Though, to be honest, I'm not sure how much value that option adds over continuing to use the existing `layout-width()` sass function.

**Comment by BPScott** [comment]
My thoughts on https://github.com/Shopify/polaris-react/pull/4861#issuecomment-1005176633 seem related.

Relaying on postcss plugins for this doesn't seem like a good idea because they won't help any of the apps that use `breakpoint()` / the mixins that rely upon it. Saying that every app that wants to use polaris's breakpoints helpers must add a postcss plugin because we rely upon a not-yet-standard features seems like a bad idea.

**Comment by sam-b-rose** [comment]
Closing this issue for now, and we can revisit this challenge later if needed. It doesn't fall into the scope of a simple token replacement, and the other solution is reliant on the pending [custom media](https://drafts.csswg.org/mediaqueries-5/#custom-mq) spec.
