### ISSUE TITLE
Consolidate shadow css custom properties and functions into tokens

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#4614]

**Comment by lgriffee** [comment]
### Audit Findings 
I conducted a [quick audit of all shadow functions, tokens, custom properties, and one off values](https://docs.google.com/spreadsheets/d/1dGGTVZQulbQzf0EjUcxOD4Pzop3IQXbiV7N5TJzCf9U/edit?usp=sharing) in `polaris-react` and `web`. 

Below is a brief summary of those findings:
#### Functions
| Name                    | Value                                                                     | \# polaris-react Instances | \# web Instances      |
| ----------------------- | ------------------------------------------------------------------------- | -------------------------- | --------------------- |
| shadow(faint)           | 0 1px 0 0 rgba(22, 29, 37, 0.05)                                          | 0                          | 8 results / 4 files   |
| shadow() / shadow(base) | 0 0 0 1px rgba(63, 63, 68, 0.05), 0 1px 3px 0 rgba(63, 63, 68, 0.15)      | 3 results / 2 files        | 34 results / 31 files |
| shadow(deep)            | 0 0 0 1px rgba(6, 44, 82, 0.1), 0 2px 16px rgba(33, 43, 54, 0.08)         | 0                          | 9 results / 9 files   |
| shadow(layer)           | 0 31px 41px 0 rgba(32, 42, 53, 0.2), 0 2px 16px 0 rgba(32, 42, 54, 0.08) | 0                          | 5 results / 5 files   |
| shadow(transparent)     | 0 0 0 0 transparent                                                       | 0                          | 7 results / 5 files   |

#### Legacy Tokens
| Name                    | Value                                                                     | \# polaris-react Instances | \# web Instances      |
| ----------------------- | ------------------------------------------------------------------------- | -------------------------- | --------------------- |
| \--p-card-shadow                 | 0px 0px 5px rgba(23, 24, 24, 0.05), 0px 1px 2px rgba(0, 0, 0, 0.15)       | 3 results / 3 files  | 21 results / 21 files |
| \--p-popover-shadow              | \-1px 0px 20px rgba(23, 24, 24, 0.05), 0px 1px 5px rgba(0, 0, 0, 0.15) | 5 results / 5 files  | 3 results / 3 files   |
| \--p-modal-shadow                | 0px 26px 80px rgba(0, 0, 0, 0.2) , 0px 0px 1px rgba(0, 0, 0, 0.2)              | 4 results / 4 files  | 5 results / 5 files   |
| \--p-top-bar-shadow              | 0 2px 2px -1px rgba(0, 0, 0, 0.15)                                                                                     | 2 results / 2 files  | 1 result / 1 file     |
| \--p-button-drop-shadow          | 0 1px 0 rgba(0, 0, 0, 0.05)                                                                                                                                                | 11 results / 4 files | 9 results / 9 files   |
| \--p-button-inner-shadow         | inset 0 -1px 0 rgba(0, 0, 0, 0.2)                                                                                                                                          | 6 results / 2 files  | 0                     |
| \--p-button-pressed-inner-shadow | inset 0 1px 0 rgba(0, 0, 0, 0.15)                                                                                                                                          | 2 results / 2 files  | 1 result / 1 file     |

#### Custom Properties (polaris-react only)
| Name                    | Value    |
| -------- | ----------|
| \--pc-banner-border                       | var(--p-banner-border-default)<br>inset 0 0.1rem 0 0 var(--p-border-neutral-subdued), inset 0 0 0 0.1rem var(--p-border-neutral-subdued) |
| $partial-button-filled-pressed-box-shadow | inset 0 0 0 0 transparent                                                                                                                |
| $shadow                                   | 0 2px 4px rgba(0, 0, 0, 0.1)                                                                                                             |
| $shadow-top                               | inset 0 $shadow-size $shadow-size (-1 \* $shadow-size) var(--p-hint-from-direct-light)                                                   |
| $shadow-bottom                            | inset 0 (-1 \* $shadow-size) $shadow-size (-1 \* $shadow-size) var(--p-hint-from-direct-light)                                           |

#### One Off Values (polaris-react only)
| Component/File                   | Value                                                                     |
| ------------------- | --------------------------------------------------------------------------------------------------------- |
| Badge               | 0 -102px 0 -100px currentColor inset                                                                      |
| Badge               | 0 0 0 100px currentColor inset                                                                            |
| Banner              | 0 -2px 0 0 rgba(var(--pc-banner-rgb-text), 0.75) inset                                                    |
| Banner              | 0 -2px 0 0 rgba(var(--pc-banner-rgb-text), 0) inset                                                       |
| Banner              | 0 -2px 0 0 rgba(var(--pc-banner-rgb-text), 0.25) inset                                                    |
| Button              | 0 0 0 border-width('base') currentColor                                                                   |
| Button              | 0 0 0 1px currentColor                                                                                    |
| IndexTable          | 1px 1px 0 0 var(--p-divider), 1px 0 1px 1px rgba(63, 63, 68, 0.05),<br>1px 0 3px 0 rgba(63, 63, 68, 0.15) |
| KeyboardKey         | 0 0 0 1px var(--p-border-subdued)                                                                         |
| SingleThumb         | 0 0 0 0 var(--p-focused)                                                                                  |
| SingleThumb         | 0 0 0 2px var(--p-focused)                                                                                |
| TextStyle           | inset 0 0 0 1px var(--p-border-subdued)                                                                   |
| \_focus-ring        | 0 0 0 $negative-offset var(--p-focused)                                                                   |
| \_focus-ring        | 0 0 0 $stroke var(--p-focused)                                                                            |
| \_buttons           | border-width('base') solid var(--p-border-critical)                                                       |
| Index Table | drop-shadow(1px 0 0 var(--p-divider))                                                                            |
| Index Table | drop-shadow(0 -1px 0 var(--p-divider))                                                                           |
| Index Table| drop-shadow(-1px 0 0 var(--p-divider))                                                                         |

### Proposed Changes
#### Functions
- ?? See Questions ??
#### Legacy Tokens
- ?? See Questions ??
#### Custom Properties
- Convert any `$*` custom component properties into `--pc-*`
#### One Off Values
- ?? See Questions ??

### Questions
- The `box-shadow` property are made up of quite a few values that could result in a lot of permutations (inset | offset-x | offset-y | blur-radius | spread-radius | color) which sets of values are valuable enough to be global tokens?
- Should we be moving one off shadow values into component custom properties? Try to capture them in global tokens? Or leave them alone?

**Comment by johanstromqvist** [comment]
Oof... this feels a lot like the 23 variations of light blue buttons that made design systems a thing.

Thinking out loud, hope to be helpful.

### Scope
I imagine a couple of tiers of token quality:
- **Covered** – Functions are replaced and stray values are either removed or tokenized. We don't mind an uneven scale and permutations.
- **Clean** – Token scale is coherent and values correspond to product existing needs
- **Designed** – Token scale is derived from design patterns that are based on a spatial vision.

Is it reasonable to only aim for "Covered"? That might help us meet our goals right now, while keeping further refactoring needs visible. Aiming for "Clean" could lead to undesired compromises while potentially obscuring the refactoring needs.

A spatial vision is clearly out of scope right now, but if we value it we should get in on the road map. Any clean up and sophisticated decision making around naming and scale could be deferred to this project.

### One off values
Potentially hard and risky to make big sweeping decisions here. Do we know why they exist? Are there any patterns to why? My gut says that there might be a couple of categories:
  - **Sloppy work** – values are one-off, but shouldn't be. Prompt teams to fix them. Maybe provide support?
  - **Purposeful** – values are one-off for good reasons. Let them?
  - **Recurring** – multiple one-off values that imply an unmet need. Consolidate and tokenize?

**Comment by aaronccasanova** [comment]
My vote is moving away from shadow aliases in favor of a shadow scale. I don't have strong opinions on the token prefix (e.g. `--p-shadows`, `--p-depth`, `--p-elevation`, etc.) but do think we should have opinions for inset and outset tokens. A "simple" solution may be to:
- Add ~20 outset shadow tokens
- Add ~20 inset shadow tokens
- Update each alias token with the closest matching shadow token

Example token scales
<details>
  <summary>Outset shadow tokens:</summary>
  <ul>
<li><strong>--p-shadows-0: </strong>none</li>
<li><strong>--p-shadows-1: </strong>0px 2px 1px -1px rgba(0,0,0,0.2)</li>
<li><strong>--p-shadows-2: </strong>0px 2px 1px -1px rgba(0,0,0,0.2)</li>
<li><strong>--p-shadows-3: </strong>0px 2px 1px -1px rgba(0,0,0,0.2)</li>
<li><strong>--p-shadows-4: </strong>0px 2px 1px -1px rgba(0,0,0,0.2)</li>
<li><strong>--p-shadows-5: </strong>0px 2px 1px -1px rgba(0,0,0,0.2)</li>
<li><strong>etc: </strong>...</li>
  </ul>
</details>
<details>
  <summary>Inset shadow tokens:</summary>
  <ul>
<li><strong>--p-shadows-inset-0: </strong>none</li>
<li><strong>--p-shadows-inset-1: </strong>0px 2px 1px -1px inset rgba(0,0,0,0.2)</li>
<li><strong>--p-shadows-inset-2: </strong>0px 2px 1px -1px inset rgba(0,0,0,0.2)</li>
<li><strong>--p-shadows-inset-3: </strong>0px 2px 1px -1px inset rgba(0,0,0,0.2)</li>
<li><strong>--p-shadows-inset-4: </strong>0px 2px 1px -1px inset rgba(0,0,0,0.2)</li>
<li><strong>--p-shadows-inset-5: </strong>0px 2px 1px -1px inset rgba(0,0,0,0.2)</li>
<li><strong>etc: </strong>...</li>
  </ul>
</details>
<details>
  <summary>Visual aid:</summary>
  <img src="https://user-images.githubusercontent.com/32409546/145290654-53cd70a0-33cb-4848-b390-935154d0614e.png" />
</details>

@lgriffee , @laurkim , and I briefly discussed another concern on how to address existing instances of `box-shadow` with custom colors. Our tentative solution is to set a custom property for `box-shadow` colors that can be optionally overridden globally or locally on a given CSS rule (open to other suggestions).

The above would look something like:
```css
:root {
  --p-shadows-color: rgba(0, 0, 0, 0.2);
  --p-shadows-1: 1px 1px var(--p-shadows-color);
  --p-shadows-...
}

.default-shadow-color {
  box-shadow: var(--p-shadows-1);
}

.custom-shadow-color {
  --p-shadows-color: rgba(var(--custom-color), 0.2);
  box-shadow: var(--p-shadows-1);
}
```

**Comment by alex-page** [comment]
Can we exclude the color values from the shadow? We want to be able to give flexibility to builders.

**Comment by aaronccasanova** [comment]
My only concern with that is `box-shadow` will default to the `color` property. Which could lead to undesired inheritance issues. Also, `box-shadow` is not a shorthand. So there would be no way to set `color` and `box-shadow` color to different values.

**Comment by lgriffee** [comment]
This is super helpful feedback everyone! Thank you! 
- @aaronccasanova your proposed scale really helps to give shape/clarity to the goal state we are moving towards 💎  
- @johanstromqvist I love your quality/scope tiers and feel like this is a great road map for how we get to our goal state 🏆

Should we check in quickly about scope before moving forward? 

I do agree with @johanstromqvist that aiming for "Covered" might be our best option for getting rid of `shadow()` this week before a majority of the team leaves for the end of the year:  

> That might help us meet our goals right now, while keeping further refactoring needs visible. Aiming for "Clean" could lead to undesired compromises while potentially obscuring the refactoring needs.
> 
> A spatial vision is clearly out of scope right now, but if we value it we should get in on the road map. Any clean up and sophisticated decision making around naming and scale could be deferred to this project.

This would mean for this first pass that: 

> Functions are replaced and stray values are either removed or tokenized. We don't mind an uneven scale and permutations.

I would propose we do the following based on that: 
- Functions are replaced with renamed tokens in a new token file (values are not changed)
- Legacy tokens are put into the new token file and renamed (values are not changed)
- Any `$*` custom component properties are converted into `--pc-*`
- One off values are left alone for now

We could try to enter into the "Clean" phase with @aaronccasanova's suggestions but I have a feeling that would take longer than this week to work with our designers on the team to come to a consensus on these new scale values?

> Aiming for "Clean" could lead to undesired compromises while potentially obscuring the refactoring needs.

@alex-page What do you think? I know you mentioned the goal of trying to remove functions by the end of the week.

**Comment by alex-page** [comment]
Sounds great @lgriffee. Happy to iterate in PR's if any feedback comes up.
