### ISSUE TITLE
Add theme switcher to storybook

### ISSUE THREAD

**Issue by aaronccasanova** [Shopify/polaris-react-archive#4637]
## Feature request summary

Update our storybook implementation to include a theme switcher that additionally changes the storybook UI. There are a few addons that make this very straight forward:
- [Storybook Dark Mode](https://storybook.js.org/addons/storybook-dark-mode)
- [Theme Switcher](https://storybook.js.org/addons/storybook-addon-themes)

#### Example from the `Storybook Dark Mode` addon:
![Storybook theme switcher](https://raw.githubusercontent.com/hipstersmoothie/storybook-dark-mode/HEAD/example.gif)

## Rationale

We currently have [theme switching](https://github.com/Shopify/polaris-react/blob/2667666d25f5795fbc28e553d5c34f5843979590/.storybook/preview.js#L57-L69) implemented in our storybook config, but it does not update the storybook UI. While the lack of color scheme changes in the storybook UI is not blocking us from  shipping features the experience for creating themed components could be improved.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by alex-page** [comment]
Going to close this one with the recent discussion around dark mode. I think it's a nice feature but the UI will likely stay white.
