### ISSUE TITLE
FormLayout.Item custom widths

### ISSUE THREAD

**Issue by ugur-shopify** [Shopify/polaris-react-archive#4639]
## Feature request summary

The existing `FormLayout` component can currently be used to group form controls onto the same row. However, all the form controls that are grouped in the same row can currently only be in equal width.

We would like to extend the functionality of the `FormLayout` to support form controls that have custom widths.

## Rationale

Our UX team is revising the form control widths in many parts of the Admin, and they are introducing a new paradigm where the inputs can have variable sizes (33%, 50%, 66%, 100%).

#### Example 1

![image](https://user-images.githubusercontent.com/84520558/141531038-5b4306e9-8d63-4132-b55d-53a7ed36f8b8.png)

#### Example 2

![image](https://user-images.githubusercontent.com/84520558/141532197-32edc5f8-31e9-4547-863a-5beec94bfc42.png)

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by yurm04** [comment]
Thanks for this request, @ugur-shopify. We're currently experimenting with new layout components, this request seems to be related to this work. We aren't able to implement this specific request at this time, but please look out for our layout updates in the near future as they may address this issue
