### ISSUE TITLE
Extend Layout.AnnotatedSection to always remain in one-column

### ISSUE THREAD

**Issue by ugur-shopify** [Shopify/polaris-react-archive#4640]
## Feature request summary

Currently, `Layout.AnnotatedSection` displays its contents in a two-column layout, where the `title` and the `subtitle` are on the left, and the `children` on the right. And on smaller viewports, it adopts one-column layout, where `title`, `subtitle` and `children` all stack on top of each other.

We would like to pass an optional prop (e.g `column`) to `Layout.AnnotatedSection` so that it always remains in one-column layout on every viewport size.

## Rationale

The proposed change would be an alternative version of the `Layout.AnnotatedSection` as found in Admin Settings currently.

#### Current example

![image](https://user-images.githubusercontent.com/84520558/141536784-76572d08-d2f9-417f-85f6-2ca3f301889f.png)

#### Proposed example

![image](https://user-images.githubusercontent.com/84520558/141536481-369b389e-740e-41c3-8ec0-48b2ab394249.png)

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by yurm04** [comment]
Thanks, @ugur-shopify for this request! The `Layout.AnnotatedSection` component is going to be [deprecated in an upcoming release](https://github.com/Shopify/polaris/pull/6483). There are some suggestions for how to compose this layout using existing Polaris components in the linked PR
