### ISSUE TITLE
index table bug on the first column

### ISSUE THREAD

**Issue by issamwahbi** [Shopify/polaris-react-archive#4646]
Hello, 
I follow the index table polaris official documentation and I add exactly the same code provided. 
When displaying the index table in my app, the first column seems to have a kind of white background : https://codesandbox.io/s/z8mgx?file=/src/index.tsx

after debuging the css a little bit, it seems that there is a border-spacing with border-collapse which causes the problem.

**Comment by edwardoverthere** [comment]
That was an existing bug with `IndexTable` that has since been fixed. Upgrade polaris 👍🏼

**Comment by issamwahbi** [comment]
Yes work perfectly after the upgrade. Thank you
