### ISSUE TITLE
Memory Leak in Popover's PositionedOverlay

### ISSUE THREAD

**Issue by snesjhon** [Shopify/polaris-react-archive#4652]
## Issue summary

Using a `Popover` with an TextField `activator` there is a memory leak when toggling a TextField's `suffix` or `prefix` prop. Specifically toggling between ReactNode sources.

## Expected behavior

I should be able to toggle `suffix/prefix` prop without having a memory leak

## Actual behavior

* While investigating [this issue](https://github.com/Shopify/commerce-algorithms/issues/561) I noticed that we were toggling from having a suffix to not having a suffix, and that was throwing a memory leak. 
* I want to show the suffix/prefix only when the Popover is closed. So I pass down the state which handles the Popover visibility. Using this I am able to toggle between having a suffix and not. This works as intended, but I get the memory leak after opening and closing the Popover a few times.
* I narrowed down the cause to having a TextField as the `activator` prop, that uses a `suffix` or `prefix`. If I remove the suffix/prefix, then the memory leak goes away.

<details>
<summary>Memory Leak + Image</summary>

![image](https://user-images.githubusercontent.com/5641734/142057495-70834153-ab04-406a-b9b1-611573683d81.png)

```
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    at PositionedOverlay
```

</details>

## Steps to reproduce the problem

1. Using the codesandbox
2. Click the `connectedRight` button three times. 

https://screenshot.click/16-23-n30up-6m3tx.mp4

## Reduced test case

* https://codesandbox.io/s/distracted-browser-91zkm?file=/App.js:825-844

## Specifications

- Using Spin

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
  System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (32) x64 Intel(R) Xeon(R) CPU @ 2.80GHz
    Memory: 1.27 GB / 125.90 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  npmPackages:
    @shopify/polaris: 7.3.0-rc.1 => 7.3.0-rc.1 
    react: ~17.0.2 => 17.0.2 
    react-dom: ~17.0.2 => 17.0.2 

```

**Comment by fatbattk** [comment]
FWIW here's another test case that triggers this warning. Modified from [example](https://polaris.shopify.com/components/overlays/popover#navigation).
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in PositionedOverlay (created by PopoverOverlay)
```

https://codesandbox.io/s/nice-panka-2qrg8?file=/App.js:238-281
1) Click `Import`.
1) See console.
1) If no error, repeat clicking alternative items till error shows.
