### ISSUE TITLE
Remove color() sass function

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#4656]
We need to deprecate the `color()` function from our public sass API. It is already no longer used in `polaris-react` (once #4655 is merged). Let's remove this function altogether. 

Breaking change, stage for `v8.0.0-major`

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).
