### ISSUE TITLE
Sectioned action list example doesn't render due to missing import of `EditMinor`

### ISSUE THREAD

**Issue by jory-graham** [Shopify/polaris-react-archive#4678]
## Issue summary

If you select the Sectioned action list example on the [Action list](https://polaris.shopify.com/components/actions/action-list) page, it doesn't actually render the example. If you click through to [Edit in Sandbox](https://codesandbox.io/s/i9wlu?module=App.js&file=/App.js), you'll see a ReferenceError because `EditMinor` hasn't been imported.

![](https://screenshot.click/18-25-qq80b-g1bcr.png)

Fixing the import gets the example to render properly, but I can't suss out how to make the appropriate edit on that README.md page to fix it

![](https://screenshot.click/18-26-adr8r-rr0l4.png)

## Steps to reproduce the problem

1. [Browse here](https://codesandbox.io/s/i9wlu?module=App.js&file=/App.js)

## Reduced test case

[Same link as above, the one provided in the docs](https://codesandbox.io/s/i9wlu?module=App.js&file=/App.js)

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by m4thieulavoie** [comment]
I'm happy to look into it 👀

**Comment by m4thieulavoie** [comment]
@jory-graham that should now be fixed 🎉
