### ISSUE TITLE
Remove inline text and background color from AppProvider

### ISSUE THREAD

**Issue by aaronccasanova** [Shopify/polaris-react-archive#4708]

**Comment by aaronccasanova** [comment]
## Overview

The `AppProvider` now [inlines Polaris tokens  for `background-color` and `color` as well as sets the custom `color-scheme` attribute](https://github.com/Shopify/polaris-react/blob/4a4dfc584320c21fcafa7c210c34159f82b6e420/src/components/AppProvider/AppProvider.tsx#L98-L107)  on the `body` tag. Note: This was applied to maintain backward compatibility with the `ThemeProvider`, which has since been removed in the `v8` branch.

## Investigation

Upon further investigation, these additions to the `AppProvider` seem like the appropriate home for this logic. It is common for applications to set themed custom properties on the `body` and I think continuing to include this baseline in our `AppProvider` will reduce unnecessary boilerplate, simplify the getting started process, and avoid miss configurations.

## Possible solutions

With the above in mind, there are still two issues that I see:
1. How can the consumer opt out of this behavior
2. How do you apply the baseline body styles if your not using the `AppProvider`

> 1. How can the consumer opt out of this behavior

One possible solution could be adding a `disableBodyStyles` prop to the `AppProvider`

```tsx
const App = () => (
  <AppProvider colorScheme="dark" disableBodyStyles />
)
```

This approach is by far the simplest and would serve as a quick/stop gap solution until we have a bigger problem to solve.
(Remember we are only setting two styles and one attribute)

> 2. How do you apply the baseline body styles if your not using the `AppProvider`

I have handled this in the past with a dedicated component for applying these types of global styles. The following is heavily inspired by the [`MUI CssBaseline` component](https://github.com/mui-org/material-ui/blob/3914e13d6ac9677f7b57e550b62d3b5f8f830391/packages/mui-material/src/CssBaseline/CssBaseline.js#L18-L20).

```tsx
const App = () => (
  <CustomProperties colorScheme="dark">
    <CssBaseline />
    /* App Content */
  </CustomProperties>
)
```

The benefit of this approach is we can still include the `CssBaseline` component in the `AppProvider`, enabled by default with a `disable` prop, and the logic is encapsulated.

## Conclusion

With all that said, I'm unconvinced we need to take any action until we really start focusing on support for extended color-schemes (e.g. dark, dim, high contrast, etc.).

**Comment by BPScott** [comment]
> How do you apply the baseline body styles if your not using the AppProvider

If you don't use the AppProvider then almost all components will refuse to render as most of them rely on the AppProvider for providing a context that lets them render their translation strings. Not having an AppProvider in your tree somewhere renders the components basically unusable.

**Comment by aaronccasanova** [comment]
Roger that! So there is even less incentive to create a dedicated `CssBaseline` component at this time 👍
