### ISSUE TITLE
Audit `--p-` tokens created in components to see if they can use tokens

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#4732]
When users see a `--p-` custom property they should have confidence it is from our tokens library. There is confusion however in components where new `--p-` custom properties are created.

To address this we should document the custom properties created in components and see if they can be replaced with tokens. If they can't we should align on a naming strategy that clearly seperates tokens from components.

**Comment by aveline** [comment]
How about `--p-` prefix for custom properties from the tokens library and `--p-c-` for custom properties at the component level?

Ex. `--space-1` is a spacing token and `--p-c-item-min-height` would be a custom property at the component level, locally scoped to that component.

I don't feel too strongly about `--p-c` if anyone has a better idea. @kyledurand @lgriffee @aaronccasanova @laurkim @alex-page thoughts?

**Comment by kyledurand** [comment]
I've just started doing `--pc-<property>`. Saves me typing

Starting a PR [here](https://github.com/Shopify/polaris-react/pull/4753) for z-index work

**Comment by alex-page** [comment]
Lets go with `--pc-` for less characters. I also imagine if autocompleting exists it will exit faster with `pc`. Keeping this open for the audit if necessary.

**Comment by aaronccasanova** [comment]
+1 for `--pc-`
- It is clear it is part of the `polaris-react` ecosystem.
- It is a simple adaptation of the existing naming convention.
- It gives us high confidence there won't be naming collisions with downstream custom properties.
- The upgrade path is straight forward.

**Comment by laurkim** [comment]
`--pc-` sounds good to me as well.

I'll be easier to narrow down searches for component custom properties and like @alex-page mentioned, autocomplete will exit faster.

**Comment by BPScott** [comment]
A thought: What comes after the `--pc-`? It is possible for a custom property in one component to bleed into another, should there be a rule for saying you put the component name in the property - -`--pc-badge-BLAH`, `--pc-banner-BLAH` etc

**Comment by aaronccasanova** [comment]
@BPScott Makes a good point. The `--pc-` prefix doesn't prevent inheritance issues with nested `polaris-react` components.

> It gives us high confidence there won't be naming collisions with downstream custom properties.

My original comment only considered avoiding conflicts with consumer's custom properties.

`--pc-<component>-` Would cover both edge cases 👍

**Comment by alex-page** [comment]
I am fine with `--pc-<component>`. I do want to reduce the total times we create or use these values. If the tokens exist and the components are simple it should be very rare need.
