### ISSUE TITLE
[Admin UI Kit] Add "Finance" icon 

### ISSUE THREAD

**Issue by lucasmrich** [Shopify/polaris-react-archive#4736]
## `Finance` icon

The `Finance` icon currently appears in the `Finances` link of the `Navigation` component in production, but is not available in the `Admin: Icons` library in figma.

> Icons are used to visually communicate core parts of the product and available actions. They can act as way-finding tools to help merchants more easily understand where they are in the product, and common interaction patterns that are available.

![](https://screenshot.click/25-25-r0xb2-iawfp.png)

## Related components

After adding this icon I plan to add new variants to the `Navigation` component for the `Finances` section's active links.

## Figma branch

https://www.figma.com/file/mMHFt3kEDNjLMZWowi6gnt/branch/vGn62eB707LiZsV93vgtvn/Admin%3A-Icons

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

**Comment by lucasmrich** [comment]
Merged to main by @sarahill
