### ISSUE TITLE
Fix the KitchenSink page on v8.0.0-major

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#4741]
- [x] Fixed rendering of the page with https://github.com/Shopify/polaris-react/pull/4744
- [x] contextual save bar, and topbar are stuck to the top of the page instead of rendering where they should be

**Comment by kyledurand** [comment]
Another problem with kitchen sink on v8 is that the contextual save bar, and topbar I believe, are now stuck to the top of the page instead of rendering where they should be. Probably due to my changes. I can look into it next week
