### ISSUE TITLE
Iterate on easing token values and implementation

### ISSUE THREAD

**Issue by lgriffee** [Shopify/polaris-react-archive#4746]
Follow up to the work done in #4595

**Comment by johanstromqvist** [comment]
- [x] Phase 1: #4772
- [ ] Phase 2: Raise the ceiling. Develop easing functions custom to the Admin.
- [ ] Phase 3: Ship aliases that solve pattern problems, e.g. `default`, `accelerate`, `constant`

**Phase 1**
Use [CSS default values](https://www.w3.org/TR/css-easing-1/#cubic-bezier-easing-functions).

| Name | Equivalent to |
| ----------- | ----------- |
| ease | cubic-bezier(0.25, 0.1, 0.25, 1) |
| ease-in | cubic-bezier(0.42, 0, 1, 1) |
| ease-out | cubic-bezier(0, 0, 0.58, 1) |
| ease-in-out | cubic-bezier(0.42, 0, 0.58, 1) |
| linear | cubic-bezier(0, 0, 1, 1) |

It's a short term win to replace the old values with something safe and proven. 

**Phase 2**
The value of easing curves custom made for the Admin is to solve domain specific problems and/or add character that aligns with our brand. We currently don't have that context. To ship such easing curves we would first need to shape an opinion by auditing use cases and branding opportunities.

**Comment by alex-page** [comment]
This should be super understandable to our developers and designers. What happens to the old values? Do you need to tophat or test the motion approaches where these don't line up @johanstromqvist?

**Comment by johanstromqvist** [comment]
Great questions! I need some Eng support to fully answer these questions.

Here's my understanding of the current situation:
- Based on @lgriffee's [audit](https://github.com/Shopify/polaris-react/issues/4595#issuecomment-976669846) we had the following functions:
  - `easing(base)`
  - `easing(in)`
  - `easing(out)`
  - `easing(excite)`
  - `easing(overshoot)`
  - `easing(anticipate)`
  - plus `--p-ease-in` and `--p-ease`
- My assumption is that [this PR](https://github.com/Shopify/polaris-react/blob/v8.0.0-major/src/tokens/_motion.ts) does the following:
  - `easing(base)` and `--p-ease` has been replaced by `ease` – ✅ Safe!
  - `easing(in)`  and `--p-ease-in` has been replaced by `ease-in` – ✅ Safe!
  - `easing(out)` has been replaced by `ease-out` – ✅ Safe!
  - `easing(excite)` has been replaced by `ease-excite` – ✅ Safe!
  - The status of `easing(overshoot)` and `easing(anticipate)` is unclear to me ⚠️
- My assumption regarding "Phase 1" outlined above:
  - Adding `ease-in-out` and `linear` is easy and safe. ✅
  - `easing(excite)`, `easing(overshoot)` and `easing(anticipate)` could be replaced by `ease`, but we need to audit how they are used to assess any damage. ⚠️

In most cases, the expect the damage to be minor, but I don't know what the protocol is for this type of refactoring. Are there any best practices how to hunt down usage and test changes? Could we perhaps 1) ship boldly, 2) see what breaks, 3) fix what broke?

**Comment by lgriffee** [comment]
I think your assumptions are correct @johanstromqvist ! To expand on each in more detail I've outlined each one below: 

***

#### `--p-ease` has replaced `easing(base)` in name but the value is the same as `easing(base)`
_✅ Can be easily replaced by CSS default value!_

Even though the value says `ease` in the token file it will be outputted as `--p-ease` so the token still has the same name
   - **Before PR**
     - `--p-ease` = `cubic-bezier(0.4, 0.22, 0.28, 1)`
     - `easing(base)` = `cubic-bezier: (0.25, 0.1, 0.25, 1)`
   - **After PR**
     - `--p-ease` = `cubic-bezier: (0.25, 0.1, 0.25, 1)`

We kept `cubic-bezier: (0.25, 0.1, 0.25, 1)` instead of `cubic-bezier(0.4, 0.22, 0.28, 1)` since you updated it the most recently for that motion issue in the admin

***

#### `--p-ease-in` has replaced `easing(in)` in name but the value is the same as `easing(in)`
_✅ Can be easily replaced by CSS default value!_

Even though the value says `ease-in` in the token file it will be outputted as `--p-ease-in` so the token still has the same name
   - **Before PR**
     - `--p-ease-in` = `cubic-bezier(0.5, 0.1, 1, 1)`
     - `easing(in)` = `cubic-bezier(0.36, 0, 1, 1)`
   - **After PR**
     - `--p-ease-in` = `cubic-bezier(0.36, 0, 1, 1)`

We kept `cubic-bezier(0.36, 0, 1, 1)` instead of `cubic-bezier(0.5, 0.1, 1, 1)` since `cubic-bezier(0.5, 0.1, 1, 1)` was only used in documentation files and not in our repos while `cubic-bezier(0.36, 0, 1, 1)` was being used. 

***
#### Adding `ease-in-out` and `linear` is easy and safe. 
_✅ Since they currently don't exist that makes sense to me!_
***

#### `easing(overshoot)` and `easing(anticipate)` were removed and not replaced by token values 
_✅ Don't need to be replaced by anything!_

Neither of these values were being used in `polaris-react` or `web` so we were able to rip them out completely 

***
#### `ease-excite-` only has 2 instances in `web` that we need to replace and then can be removed. 
_✅ Should be easy to replace!_

Since there are only 2 instances it shouldn't take us long to quickly test and replace these hopefully!

**Comment by johanstromqvist** [comment]
Thank you @lgriffee – great news! This will make next steps way easier!

As far as I can tell, the only steps we'd need to take to complete Phase 1 would be
1. Add the missing tokens `ease-in-out` and `linear`
2. Update the cubic bezier values of `ease-in` and `ease-out`
3. Manually handle the two instances of `ease-excite`

That should leave us with the CSS standard proposal of Phase 1.

Would it make sense to break out Phase 1 as its own issue and get it done in the near term, while the Phase 2 and 3 stays in the backlog?

**Comment by lgriffee** [comment]
Breaking out Phase 1 into it's own issue makes sense to me!

**Comment by johanstromqvist** [comment]
Regarding the two instances of `ease-excite`
![image](https://user-images.githubusercontent.com/38329124/144277173-eea2d554-0a3b-48f0-8e80-0520c0a3170f.png)

I think we can safely replace them with `ease`. It might even improve the animations.

1. The first one is only 100ms long (6 frames) which typically doesn't afford any complexity, such as the overshooting end part of `ease-excite`. I haven't checked what `transform` it is, but my best guess is that the curve is either indistinguishable or even noisy. 
2. Putting an overshoot on a color makes little sense to me. Changing it to `ease` will however make the animation seem a tad slower, so if we want to be super tidy we could replace `duration(slow)` with `duration-200`.

**Comment by alex-page** [comment]
I am closing this issue for now. We will go through the token values for motion intentionally in the future. Look forward to going through this issue then.
