### ISSUE TITLE
Page component titleMetadata doesn't easily match title style

### ISSUE THREAD

**Issue by toyelowo** [Shopify/polaris-react-archive#4747]
## Issue summary

Polaris `Page` component, currently doesn't provide a mixin for the header `titleMetadata`, this means that if a `title` and `titleMetadata` prop is passed in, the styles won't match unless we copy the Polaris `Header-Title` style. 

## Expected behavior

There should be an available `mixin` so we can make the `titleMetada` have similar styles to the `title`

## Actual behavior

Since there is no `mixin` we have to manually add the styles to the `titleMetada` to get it to match the `title`. 

## Steps to reproduce the problem

1. First step
1. Second step

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by AndrewMusgrave** [comment]
Adding on - a more viable option would be allow page to accept `ReactNode` for the title prop & automatically include text styles (or expose a mixin)
