### ISSUE TITLE
[Modal] Allow ComplexAction to receive `submit` for form submission

### ISSUE THREAD

**Issue by kydecker** [Shopify/polaris-react-archive#4749]
## Issue summary

There doesn't appear to be a way to use the `primaryAction` prop on a Modal to submit a form. The Polaris `Button` includes a `submit` prop for form submission; Buttons passed in as objects (`ComplexAction`) do not include the ability to set `submit`.

## Expected behavior

`ComplexAction`—like `Button`—should accept `submit` so that the default styling and positioning of Modal buttons can be maintained.

## Actual behavior

Instead of supplying a `primaryAction`, it's necessary to use `ButtonGroup` and `Button` within the contents of `Modal`. Writing custom markup means that buttons are aligned left and do not include a dividing border with the contents of the modal, creating inconsistency.

**Comment by rajashravan** [comment]
wondering if this has been addressed
