### ISSUE TITLE
Audit use of external link icon in the admin

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#4756]

**Comment by jjgali** [comment]
I performed an audit of the admin to see where we most often use the external link icon. Fairly consistently, we use the icon at the bottom of a page with a link to learn more about a particular area of the admin. 
<img width="254" alt="Screen Shot 2021-12-01 at 11 42 11 AM" src="https://user-images.githubusercontent.com/77791660/144285691-dffcfe11-e266-4496-86a1-4f9a7bbf13f5.png">

The icon is used for other links that open in a new tab (mostly for the Help Center), but not in a consistent manner. For example, on the home page, there are several links that open in a new tab which don't have the external link icon. 

As explored in https://github.com/Shopify/polaris-react/issues/4547, there's consensus that the icon can cause more confusion than clarity. 

The proposed action is to remove the external link icon while still abiding by best practices set forth in our documentation. Namely, we should use external links only when opening a page in the same tab might disrupt the merchant’s workflow (for example, a help center article). Also, use the appropriate props and labels so screen readers can recognize whether a link will open in a new tab.

**Comment by sarahill** [comment]
Closing in favor of https://github.com/Shopify/polaris/issues/5382
