### ISSUE TITLE
Remove `em()` function from public sass

### ISSUE THREAD

**Issue by aveline** [Shopify/polaris-react-archive#4777]
Hardcode `em` values as an interim step

**Comment by aveline** [comment]
This is a tricky one and I'm not sure the best way to move forward. This is closed tied with https://github.com/Shopify/polaris-react/issues/4609 as layout widths are often used to calculate and set breakpoints. I think layout widths should remain as `rem` units and it gets a bit messy when we start mixings the `em` and `rem` units to make these calculations. The `em()` function allowed for those calculations. I wonder if it would make sense to take a similar approach as [pxtorem](https://www.npmjs.com/package/postcss-pxtorem) for breakpoints except with `em`s?

**Comment by kyledurand** [comment]
> I wonder if it would make sense to take a similar approach as pxtorem for breakpoints except with ems?

👍  I'm experimenting with a postcss plugin [here](https://github.com/Shopify/polaris-react/pull/4861)

**Comment by aveline** [comment]
Resolved with https://github.com/Shopify/polaris-react/pull/4937
