### ISSUE TITLE
Feature request: add a file upload form component

### ISSUE THREAD

**Issue by robbiebow** [Shopify/polaris-react-archive#48]
# Issue summary

Would like a file form element component

## Expected behavior

Be able to add a file upload field to a form using a Polaris React component 

## Actual behavior

There's nothing in the documentation at https://polaris.shopify.com/components/ to explain how to add a file upload field to a form using Polaris components.

**Comment by hogshouse** [comment]
Yes, would be nice!

**Comment by lemonmade** [comment]
Thanks for the issue, @robbiebow. We are working on a FileUpload component, and it should be part of a release sometime in the next few weeks. I'll update this issue once we have made some progress on this.

**Comment by iannounce-devs** [comment]
Marvellous news, @lemonmade - looking forward to seeing it :)

**Comment by resistorsoftware** [comment]
+1

**Comment by medisoft** [comment]
+1

**Comment by robbiebow** [comment]
@lemonmade any advance on this?

**Comment by lemonmade** [comment]
We are still looking through exactly what API we will expose for this, but it is in progress.

**Comment by celsowhite** [comment]
+1

**Comment by rkbhochalya** [comment]
@lemonmade any update on this?

**Comment by zsavicreative** [comment]
still nothing?

**Comment by rkbhochalya** [comment]
@lemonmade we really need this. Please consider adding it sooner rather than later.

**Comment by tmlayton** [comment]
Hi @zsavicreative and @rkbhochalya, this is actively being worked on so hopefully it will be complete sooner than later.

**Comment by zsavicreative** [comment]
@tmlayton Appreciated. I'd offer my time, but the truth is I'm a nub still learning the ropes. However I'm confident of there being countless master minds floating around here that would be more then happy to lend a helping hand if time or being too busy is the case.

**Comment by mattchidley** [comment]
@lemonmade any update on this new component?

**Comment by tmlayton** [comment]
Hi @mattchidley, we are currently going through design iterations and targeting v2.0.0 as the release which contains this component.

**Comment by b0123498765** [comment]
@tmlayton thanks for the update, do you have a set release date for v2.0.0?

**Comment by tmlayton** [comment]
👋 @b0123498765 we are looking to have a prerelease for v2.0.0 out in January

**Comment by b0123498765** [comment]
HI @tmlayton - any update on this component?

**Comment by rkbhochalya** [comment]
@tmlayton looks like you have removed it from v2.0 milestone 😞  We really need this component for our app. Do you have a new ETA?

**Comment by tmlayton** [comment]
Thanks for the follow up @b0123498765 and @rkbhochalya. We had removed this from the v2.0 milestone because it wasn't looking like we'd be done in time. Although we've been making good progress so I just re-added it.

**Comment by resistorsoftware** [comment]
So an HTML File Uploader component takes at least 240+ days for a commercial entity with full-time staff and talent to design, test and deliver in React. That should put to rest forever the efficiency of React!

**Comment by dfmcphee** [comment]
We have a new `Drop zone` component which can handle drag and drop file uploads available in the v2.0.0 beta.

You can find the docs and examples for it here on the beta style guide: https://polaris-v2.shopify.com/components/actions/drop-zone
