### ISSUE TITLE
[Tag] Allow arbitrary children

### ISSUE THREAD

**Issue by jbalsas** [Shopify/polaris-react-archive#4819]
## Feature request summary

The `<Tag>` component should allow receiving arbitrary content as `children`

## Rationale

In some cases, we might want to add some additional content to a `<Tag>` like for example an icon or a link.  Here's an example of a current design where we'd like to be able to do this in `admin`

![a tag with an icon and a link](https://user-images.githubusercontent.com/905006/145489942-1305aa1d-e558-47d8-b78d-741fc40b7307.png)

## Current State

In essence, it would be neat if we could use `<Tag>` as in this [example](https://codesandbox.io/s/cocky-jang-2kjn6):

```jsx
<Tag onRemove={() => {}}>
  <Stack alignment="center" spacing="extraTight">
    <Icon size="extraSmall" source={WandMajor} />
    <UnstyledLink url="#url">This is a URL</UnstyledLink>
  </Stack>
</Tag>
```

This currently works, but it has **2 main caveats:**
- It will fail TS checks 🤓 
- The `ariaLabel` content will read something like `[Object object]` because we're assuming `children` is always a string (the tag value). 

## Proposal

I think this could be done in different ways:

#### Allow arbitrary content in `<Tag>`
- Make the `children` prop accept `Element`
- Add an extra `tagDescription` (or a better name) that:
  - Is used when `children` is of type `Element`
  - Can be used to override `ariaLabel` when `children` is a string and we want a different message

This would provide the more versatility to the tag at the cost of less consistency (can't predict how it will get used) and some worse DX (devs might need to style their content).

#### Allow restricted variations in `<Tag>`
- Add an `icon` prop so we can add icons (on the left?) to the tag
- One of:
  - Add a `url` prop so we could make the tags link somewhere
  - Allow `onClick` prop at the same time of the `onRemove` so devs can manually trigger an action when clicking the tag on removable tags

This would provide a better DX for that common case (not that it's so common now) at the price of bigger complexity as the number of props and its combinations will start to grow.

**I'd personally suggest we allow any content first. That way we don't have to keep adding this for new use cases and developers can self-serve. Then, if we detect some use case becomes very common, we can bake it in.**

![wasthattoomuch](https://user-images.githubusercontent.com/905006/145490979-7cb9b1c8-d24a-4a63-92c9-b690513c5cce.gif)

**Comment by yurm04** [comment]
Hey @jbalsas thanks for this request! We have an open discussion around a comprehensive component API strategy related to allowing arbitrary children. Would love to hear your thoughts on this if you wouldn't mind sharing over [in the discussion](https://github.com/Shopify/polaris/discussions/7005) ❤️ 

I'm going to close this issue for now since we will be approaching a solution to this problem across all components soon
