### ISSUE TITLE
Iterate on `border-radius` token values and implementation

### ISSUE THREAD

**Issue by lgriffee** [Shopify/polaris-react-archive#4826]
**Non breaking changes**
- [x] https://github.com/Shopify/polaris/pull/8305
- [x] https://github.com/Shopify/polaris/pull/8306
- [x] https://github.com/Shopify/polaris/pull/8307

**shopify/web**
- [x] https://github.com/Shopify/web/pull/83713
- [x] https://github.com/Shopify/web/pull/83712
- [x] Version bump with non breaking changes

**Breaking change in v11**
- [x] https://github.com/Shopify/polaris/pull/8304
- [x] #8374

**Comment by alex-page** [comment]
I am closing this issue for now. We will go through the border-radius values for motion intentionally in the future. Look forward to going through this issue then.

**Comment by alex-page** [comment]
@lgriffee when we ship these changes in web lets close this out.

**Comment by alex-page** [comment]
It's active yooo
