### ISSUE TITLE
[Icon] Some of the doc examples for <Icon /> do not update correctly

### ISSUE THREAD

**Issue by chanonroy** [Shopify/polaris-react-archive#4842]
## Issue summary

https://user-images.githubusercontent.com/16366896/146364840-86fd46fb-3849-4895-b386-bf044f767bb7.mp4

Two of the examples on the docs for the [Icon component](https://polaris.shopify.com/components/images-and-icons/icon) do not update the rendered example.

## Expected behavior

Clicking on the dropdown should update the rendered preview and code sample.

## Steps to reproduce the problem

https://screenshot.click/16-32-btvr1-50u8y.mp4

1. Visit the [Icon](https://polaris.shopify.com/components/images-and-icons/icon) page on Polaris
2. Click on `Colored Icon` or `Icon with backdrop` from the examples dropdown
3. These examples do not update
4. Click on `User provided icon` and the example _does update_.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser: Chrome
- Device: Macbook Pro
- Operating System: MacOS

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

**Comment by chanonroy** [comment]
It looks like using React fragments (specifically the short hand syntax) causes issues with polaris-styleguide as seen by the fix in #4843. The Icon component is the only component that examples with this pattern.

With that being said, it may be wise to create a linter or some sort to prevent this from happening in the future.
