### ISSUE TITLE
UI Kit libraries are hard to find

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#4845]
Over the past few months, we've started to get some feedback that the UI Kit libraries in Figma are hard to find. Folks know they exist but will either not know the names or will connect the wrong libraries.

A few things that may be causing and/or contributing to this issue:
- Vault info on connecting Figma libraries out of date and hard to find
- We recently removed "Polaris" from the name of our kits in an attempt to clarify that the components and styles are largely Admin specific
- There are 2 UI Kit projects, one public for the Figma community and one internal, with the same/similar names
- There are 5 separate libraries that need to be connected for components, type, color, shadows, and icons
- related to https://github.com/Shopify/polaris-react/issues/4846

We need to do a bit more digging to understand the problem and how best we can solve it.
- [ ] Reach out to teams / individuals to understand pain points
- [x] https://github.com/Shopify/polaris-react/issues/4867

**Comment by heyjoethomas** [comment]
@sarahill I can attest to this. I had no clue where to find these in Figma when I came onboard.

**Comment by sarahill** [comment]
> @sarahill I can attest to this. I had no clue where to find these in Figma when I came onboard.

@heyjoethomas Yea, it's a bit of a mess atm. When you were looking for the kits, what were you expecting to find them under? Any keywords or whatnot that you were looking for. Also anything else you saw or noticed while looking that made it harder/confusing.

**Comment by sarahill** [comment]
@heyjoethomas has released updates to the kits that solve this problem. Can revisit if needed

**Comment by heyjoethomas** [comment]
Closing this with latest refactor and consolidation of styles library.
