### ISSUE TITLE
There's no UI Kit release process

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#4846]
There's no currently no UI Kit release process. Some of the pain points:
- Figma community kits don't get regular updates
- Kit updates don't align with `polaris-react` releases
- No announcements for kit updates
- Little to no education and training for kits and changes/updates to the kits

Todo:
- [ ] Audit UI Kit to see how aligned it is with `polaris-react`

**Comment by heyjoethomas** [comment]
@sarahill Have we done and audit recently to see if/where the UI Kit is out of alignment with the repo? Understanding how far misaligned we are is probably a good place to start.

**Comment by sarahill** [comment]
We haven't done a full audit of the kit recently. That's a good call 👍
