### ISSUE TITLE
[IndexTable] Safari performance issue on selecting checkboxes

### ISSUE THREAD

**Issue by dpanov** [Shopify/polaris-react-archive#4858]
## Issue summary

When using Safari and there are more items in `<IndexTable />`, interacting with the table (e.g. clicking the bulk select checkbox or any individual row checkbox) causes the CPU usage to go through the roof and makes the table unresponsive and slow.

In Chrome and Firefox, the table is working just fine.

## Expected behavior

When using Safari on macOS, Interacting with the table shouldn't cause the CPU usage to jump so high and the table should be responsive and not laggy.

## Actual behavior
When using Safari, Interacting with the table causes the CPU usage to jump super high (100-200%) and the table is unresponsive and laggy.

<details>
  <summary>Behavior in Safari</summary>
https://user-images.githubusercontent.com/1931510/147056448-0056d1a4-4507-4c7a-9217-4f7bfaf68a8f.mp4
</details>

<details>
  <summary>Behavior in Chrome</summary>
https://user-images.githubusercontent.com/1931510/147057598-c9e84c65-4e22-453f-9ada-ca225ebacef3.mp4
</details>

## Steps to reproduce the problem

1. Add 50 items in an `<IndexTable />`
1. Open the table with Safari
1. Click on any of the checkboxes inside the table

## Reduced test case

[CodeSandbox test case](https://g4cs6.csb.app)

The code in this sandbox is exactly the same as in the [IndexTable documentation](https://polaris.shopify.com/components/lists-and-tables/index-table), but with more items added.

## Specifications
```bash
  System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 69.86 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.dev/yarn/1.22.17/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0.2
    Safari: 15.2
  npmPackages:
    @shopify/polaris: ~7.5.0 => 7.5.0
    react: ~17.0.2 => 17.0.2
    react-dom: ~17.0.2 => 17.0.2
```

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).
