### ISSUE TITLE
I'm still getting this error, even after using the new path:

### ISSUE THREAD

**Issue by nitesh7039** [Shopify/polaris-react-archive#4862]
I'm still getting this error, even after using the new path:
![image](https://user-images.githubusercontent.com/26302517/106634185-34291f80-6588-11eb-8d5e-7b22d26e2b10.png)
Any idea?

_Originally posted by @aqoraan in https://github.com/Shopify/polaris-react/issues/3134#issuecomment-771785794_

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

**Comment by kyledurand** [comment]
Take a look at [unpkg](https://unpkg.com/browse/@shopify/polaris@7.5.0/build/esm/styles.css) to see where the compiled css lives now. You have to reach into `build/esm` to grab the stylesheet. Looks like this was mentioned in the issue you linked to https://github.com/Shopify/polaris-react/issues/3134#issuecomment-935635527
