### ISSUE TITLE
Add `isLoading` or similar to `SettingToggle`

### ISSUE THREAD

**Issue by vfonic** [Shopify/polaris-react-archive#4863]
`SettingToggle` should be usable when it's used for non-instant functionality.

Here are some use-cases:

* app enable/disable - calling backend, maybe adding ScriptTag to merchant's store on toggle
* any other action that's calling backend (making network call, non-instant)
* when on initial load the component first needs to load data from backend to know whether `SettingToggle` is `enabled` or not

Adding `isLoading` to `SettingToggle` provides a better user experience for this component. The user knows they clicked on the button and they immediately get some feedback back. On top of that, the user cannot click on the button multiple times. This can be especially bad in cases where the button sends "toggle" request to backend. Imagine this scenario:

1. User clicks "Toggle app enabled" - the app sends the call to backend: `/apps/toggle-enabled`
2. No visible changes occur
3. Impatient user clicks "Toggle app enabled" again - the app sends the call to backend: `/apps/toggle-enabled`
4. First request toggles the app enabled
5. Second request toggles the app disabled

This is how I use `SettingToggle` in my app:

```jsx
    <Layout>
      <Layout.AnnotatedSection
        title="Enable app"
        description="You won't see any changes in your store until you enable the app."
      >
        <Layout.Section>
          {isLoading ? (
            <Card sectioned>
              <SkeletonBodyText />
            </Card>
          ) : (
            <SettingToggle
              action={{
                content: contentStatus,
                onAction: handleToggle,
              }}
              enabled={active}
            >
              The app is <TextStyle variation="strong">{textStatus}</TextStyle>.
            </SettingToggle>
          )}
        </Layout.Section>
      </Layout.AnnotatedSection>
    </Layout>
```

Maybe some of this layout can be integrated within the `SettingToggle` component? At least the action button should provide the `disabled`/`isLoading` functionality.

UNRELATED NOTE:

> 🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities.

=> This link, part of the Feature request template, leads to 404 page.

**Comment by yurm04** [comment]
Thanks for the request, @vfonic . We’re not actively working on this right now, but we’d love for it to make its way into the system. Please feel free to contribute and open a PR!

If you're not able to open a PR one suggestion that might work for you is to replicate the `SettingToggle` component by composing `Button`, `Card`, and managing the state for loading. Here's a [quick Codesandbox demo](https://codesandbox.io/s/laughing-mcnulty-8npibc?file=/App.js) of how I would recreate `SettingToggle` using existing Polaris components. **Please note:** my example was quick, but does not account for required accessibility roles and support. If you end up composing your own custom setting toggle component, please consult the [`SettingToggle`](https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/SettingToggle/SettingToggle.tsx) code to see what accessibility features we include.

I’ll close this issue for now, but we encourage everyone who wants this feature to add a 👍 to the original issue report. We’ll take your collective interest into account when we look at what to work on next. 💜

**Comment by yurm04** [comment]
btw, thank you for calling out the broken link!
