### ISSUE TITLE
Create migration guidance for `polaris-tokens` package

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#4883]
transitive dependencies (global-nav and online-store-ui)
```
grep '@shopify/polaris-tokens' node_modules/**/package.json
```

**Comment by BPScott** [comment]
Running `grep '@shopify/polaris-tokens' node_modules/**/package.json` in web's codebase shows packages that use tokens within web or its dependencies.

grokt may be handy for curating  list of repos across the org: [A search for references to @shopify/polaris-tokens in package.json files](https://grokt.shopifycloud.com/results?q=%22%40shopify%2Fpolaris-tokens%22+file%3Apackage.json). There's probably something you can do with ServiceDB announcements to raise an issue in multiple repositories at the same time
