### ISSUE TITLE
Release Polaris v8

### ISSUE THREAD

**Issue by aveline** [Shopify/polaris-react-archive#4896]
**Goal release date:** 25th of January

### Release v8
- [x] Reach out to caching platform team
- [ ] Document steps for release of `shopify/web` and `shopify/shopify` so they happen in sync
- [x] Get in touch with web ATC to inform them of the release
- [x] https://github.com/Shopify/polaris-react/pull/4820

### Upgrade Polaris in 1st party packages
- [x] https://github.com/Shopify/global-nav/pull/969
- [x] https://github.com/Shopify/flow-app/pull/1376
- [x] [@shopify/online-store-ui](https://github.com/Shopify/online-store-ui/blob/master/package.json)
- [x] [@shopify/app-bridge-host](https://github.com/Shopify/app-bridge/blob/main/packages/app-bridge-host/package.json)
- [x] [@shopify/realtime-react-ui](https://github.com/Shopify/realtime/blob/master/package/packages/realtime-react-ui/package.json)
- [x] [@shopify/realtime-react](https://github.com/Shopify/realtime/blob/master/package/packages/realtime-react/package.json)
- [x] [@shopify/flow-components](https://github.com/Shopify/flow-components/blob/master/package.json) (being deprecated, [this is the pr to remove it from web](https://github.com/Shopify/web/pull/56702))

### 🚀 Simultaneous deploy
- [x] https://github.com/Shopify/web/pull/54909
- [x] https://github.com/Shopify/shopify/pull/328052

**Comment by BPScott** [comment]
flow-components is going to be deprecated and removed from web in the next few weeks. I'd suggest wrangling that as your final item in the hopes that @dmcvittie and team can just remove so you don't need to do anything

**Comment by dmcvittie** [comment]
We should have a PR up for `flow-components` removal from `web` by EOW next week.

**Comment by kyledurand** [comment]
Closing this now 🎉 thanks everyone!

**Comment by alex-page** [comment]
![63g0rr](https://user-images.githubusercontent.com/19199063/151887721-361a23fc-ecf4-4ae9-b6ff-55f4896c8ef5.jpg)
