### ISSUE TITLE
Investigate possibility of adding global css util for `@mixin visually-hidden`

### ISSUE THREAD

**Issue by lgriffee** [Shopify/polaris-react-archive#4922]

**Comment by aaronccasanova** [comment]
This issue is being deprioritized to a v9.X.X follow up task. Note: We may be able to close this issue as there has been various discussions around the validity of this utility and that it is sensible to keep in our private SCSS API.

**Comment by alex-page** [comment]
Going to close this for now. We can go through removing the remaning scss functions and mixins in another project.
