### ISSUE TITLE
Replace `icon-size()` with tokens

### ISSUE THREAD

**Issue by lgriffee** [Shopify/polaris-react-archive#4923]

**Comment by aaronccasanova** [comment]
**Quick wins for `icon-size()` that should be pushed to v9.0.0**

- Replace `icon-size()` with `--p-icon-size-medium` token

> Note: There is an existing `--p-icon-size` token in `legacy-tokens.json`

- Replace the existing `--p-icon-size` token (and three usages) with `--p-icon-size-small`
