### ISSUE TITLE
Investigate usage to see if we consolidate/remove `@mixin recolor-icon`

### ISSUE THREAD

**Issue by lgriffee** [Shopify/polaris-react-archive#4924]

**Comment by aaronccasanova** [comment]
This issue is being deprioritized to a v9.X.X follow up task. Note: We may be able to close this issue as there are a high number of usages (97) and not an elegant alternative for it's behavior (e.g. a global class).

**Comment by alex-page** [comment]
Going to close this for now. We can go through removing the remaning scss functions and mixins in another project.
