### ISSUE TITLE
Investigate usage to see if we consolidate/remove `shared/_interaction-state.scss`

### ISSUE THREAD

**Issue by lgriffee** [Shopify/polaris-react-archive#4925]

**Comment by lgriffee** [comment]
**Quick wins for `shared/_interaction-state.scss` that should be pushed to v9.0.0** 
- #4988 

**Things that should remain in follow up v9.x.x**
- Leaving `@mixin list-selected-indicator` and `shared/_interaction-state.scss`

**Comment by alex-page** [comment]
Going to close this for now. We can go through removing the remaning scss functions and mixins in another project.
