### ISSUE TITLE
Investigate usage to see if we consolidate/remove `shared/_printing.scss`

### ISSUE THREAD

**Issue by lgriffee** [Shopify/polaris-react-archive#4929]

**Comment by lgriffee** [comment]
**Quick wins for `shared/_printing.scss` that should be pushed to v9.0.0** 
- #4985 
- #4986 

**Things that should remain in follow up v9.x.x**
- Leaving `@mixin hidden-when-printing` and `shared/_printing.scss`

**Comment by aaronccasanova** [comment]
Update: `@mixin hidden-when-printing` and `shared/_printing.scss` was removed in PR #4995 and will be included in the v9.0.0 release.
