### ISSUE TITLE
Replace `shared/_skeleton.scss` with react component

### ISSUE THREAD

**Issue by lgriffee** [Shopify/polaris-react-archive#4931]
Replace shared/_skeleton.scss with react component if effort is minimal, otherwise wait add to loading project.

**Comment by lgriffee** [comment]
**Quick wins for `shared/_skeleton.scss` that should be pushed to v9.0.0** 
- #4983 
- #4984 

**Things that should remain in follow up v9.x.x**
- Leaving `thumbnail-size()` and `@mixin skeleton-content` for follow up work to replace `shared/_skeleton.scss` with a react component

**Comment by alex-page** [comment]
Going to close this for now. We can go through removing the remaning scss functions and mixins in another project.
