### ISSUE TITLE
[Autocomplete] Snapping to items in scrollable list when clicked

### ISSUE THREAD

**Issue by michaelnesen** [Shopify/polaris-react-archive#4957]
## Issue summary

When selecting items from a long list on the Polaris [Autocomplete](https://polaris.shopify.com/components/forms/autocomplete) component. If you have enough items to have to scroll, it seems to "snap" to items when selected, making it hard to track where you are in the list.

## Expected behavior
I would expect the autocomplete to not snap to items when scrolling through a list and clicking on items. I want to know where I’m at in the list, it shouldn’t be hard to track where I am after clicking on an option. 

## Actual behavior

https://user-images.githubusercontent.com/90475364/151001608-9993fb81-1540-4b13-9f06-fe058d7267da.mp4

## Steps to reproduce the problem

Click on a autocomplete that has many options (where you have to scroll) and select/deselect a few, you will notice it snaps to items when clicked.

## Reduced test case
https://codesandbox.io/s/romantic-moon-te0fq?file=/App.js

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number: Latest
- Browser: Any
- Device: Macbook Pro
- Operating System: Mac OS

**Comment by laurkim** [comment]
Thanks for creating this issue!
Closing this issue as this bug was resolved in the [v9.4.0 release](https://github.com/Shopify/polaris/releases/tag/v9.4.0) of Polaris:
> Updated Listbox scroll UX to behave natively when navigating options with keyboard instead of scrolling the active option to the top of the visible list (https://github.com/Shopify/polaris/pull/5303)
