### ISSUE TITLE
Port deprecated SCSS functions and mixins to https://github.com/Shopify/web

### ISSUE THREAD

**Issue by aveline** [Shopify/polaris-react-archive#4966]
Add [legacy functions and mixins](https://github.com/Shopify/polaris-react/blob/v9.0.0-major/documentation/guides/legacy-polaris-v8-public-api.scss) to [web](/Shopify/web)

**Comment by sam-b-rose** [comment]
Work being done in https://github.com/Shopify/web/pull/57993

**Comment by sam-b-rose** [comment]
Fixed by https://github.com/Shopify/web/pull/57993
