### ISSUE TITLE
Data tables dark header divider line

### ISSUE THREAD

**Issue by vernalkick** [Shopify/polaris-react-archive#4972]
Data tables have a dark divider line that seems out of place with the rest of the design and is inconsistent with how other tables are rendered in Polaris.

<img width="714" alt="Screen Shot 2022-01-27 at 11 28 13 AM" src="https://user-images.githubusercontent.com/1269855/151401127-b7133c21-9c15-4956-8f35-3b74a88823c5.png">

[You can view it in action here](https://polaris.shopify.com/components/lists-and-tables/data-table)

---

Here's an index table for comparison

<img width="758" alt="Screen Shot 2022-01-27 at 11 29 36 AM" src="https://user-images.githubusercontent.com/1269855/151401405-9627c5b4-0cee-449b-8b34-79b2985793ba.png">

I would expect the divider line to match the color of the other divider lines in the table.

Thank you ✨

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).
