### ISSUE TITLE
Text Field not working properly on Safari

### ISSUE THREAD

**Issue by panth-thakkar-shipsy** [Shopify/polaris-react-archive#4976]
## Issue Summary

I have been using TextField component of Polaris. It works fine on chrome browser but doesn't work properly on Safari. 
`  <TextField
            label="Weight (Kgs)"
            type="number"
            value={consignments[consignmentIndex].pieces_detail[
              pieceIndex
            ].weight.toString()}
            onChange={useCallback((e) => {
              const update = [...consignments];
              update[consignmentIndex].pieces_detail[pieceIndex].weight = e;
              setConsignments(update);
            }, [])}
          />`
          Above code accepts decimal numbers as input in chrome browser. But it doesn't allow in safari. In safari it says invalid value. Kindly look into this.

## Expected behavior

It should have same behaviour across all the browsers. Should accept decimal values.

## Actual behavior

Accepting decimal values in all browsers except Safari.

## Steps to reproduce the problem
Have provided code , you can use that to verify.

**Comment by williamoconnorme** [comment]
This safari bug also impacts the Shopify Admin Taxes and Duties view when setting a tax override with a decimal point.

**Comment by yurm04** [comment]
Hey @panth-thakkar-shipsy and @williamoconnorme can one of you link a codesandbox to reproduce this issue?
