### ISSUE TITLE
Clean up `!important` usage throughout Polaris

### ISSUE THREAD

**Issue by aaronccasanova** [Shopify/polaris-react-archive#4998]
Throughout the process of removing SCSS mixins and replacing tokens we have come across a number of questionable usages of `!important`. I suggest we time box a day or so to investigate `!important` usage across `Polaris`, clean up any low hanging fruit, and determine next steps for any remaining `!important`s.

**Comment by BPScott** [comment]
https://github.com/Shopify/polaris-react/pull/4995#discussion_r797130188 offers up some context on the `!important`s that came from inlining the hidden when printing mixins.
