### ISSUE TITLE
Toggling of "sectioned" prop of layout breaks styling

### ISSUE THREAD

**Issue by paulxuca** [Shopify/polaris-react-archive#5]
Steps to reproduce:

1) Go to: https://polaris.shopify.com/components/structure/layout#navigation
2) Set `sectioned` to false, then true
3) Observe below styling issue:

![](http://i.imgur.com/0BnXGSN.png)

**Comment by lemonmade** [comment]
Hey @paulxuca, thanks for creating the issue. I've added an issue to our internal issue tracker for this, and I'll update you here when it gets fixed.
