### ISSUE TITLE
Description List example: "There is an error in your code"

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris-react-archive#50]
# Issue summary

## Steps to Reproduce the Problem

1. Go to https://polaris.shopify.com/components/tables-and-lists/description-list
1. In the example section, click "HTML"

## Expected behavior

```html
<dl class="Polaris-DescriptionList"><dt class="Polaris-DescriptionList__Term">Logistics</dt>
  <dd class="Polaris-DescriptionList__Description">The management of products or other resources as they travel between a point of origin and a destination.</dd><dt class="Polaris-DescriptionList__Term">Sole proprietorship</dt>
  <dd class="Polaris-DescriptionList__Description">A business structure where a single individual both owns and runs the company.</dd><dt class="Polaris-DescriptionList__Term">Discount code</dt>
  <dd class="Polaris-DescriptionList__Description">A series of numbers and/or letters that an online shopper may enter at checkout to get a discount or special offer.</dd>
</dl>
```

Note that navigating away to another component, and then back to the Description List component shows this expected code.

## Actual behavior

```html
<pre class="error">There is an error in your code.</pre>
```

<img width="894" alt="screenshot 2017-05-07 01 00 20" src="https://cloud.githubusercontent.com/assets/85783/25778074/48f3fdc0-32c1-11e7-88f6-cae7011879bf.png">

## Specifications

- Polaris version: latest documentation
- Browser: Chrome
- Operating System: macOS

**Comment by lemonmade** [comment]
Thanks for the issue, @kaelig. We have a fix for this that should ship early this week — I'll close this issue once it has gone live.

**Comment by lemonmade** [comment]
Fixed in the live version of the style guide.

**Comment by kaelig** [comment]
Merci Chris!
