### ISSUE TITLE
Bug: RoutePropagator and ResourceItem

### ISSUE THREAD

**Issue by EvaDenys99** [Shopify/polaris-react-archive#5014]
## Issue summary
When going to a page via ResourceItem, the default return button of the browser needs to be clicked a few times in order to return to previous page. These ResourceItems each have their own URL to go to the detail page.

<img width="396" alt="Screenshot 2022-02-03 at 10 27 35" src="https://user-images.githubusercontent.com/44461075/152315746-cba45dc8-77ec-4796-9a23-716895023742.png">

We are using the Route Propegator from app-bridge-react like this, see screenshots:

<img width="739" alt="Screenshot 2022-02-03 at 11 20 35" src="https://user-images.githubusercontent.com/44461075/152323999-b8417438-1426-49fe-a99f-99ff70b0f53a.png">
----------------------------------------------------------------------------------------------------------------------------

<img width="617" alt="Screenshot 2022-02-03 at 11 20 47" src="https://user-images.githubusercontent.com/44461075/152324037-525a8fa9-ac38-4034-b4ed-4a2ca4f6a53b.png">

We upgraded al our packages etc but it still is not fixed.

## Expected behavior
When using the default browser return button on a page the browser should still return to the previous page. While using the URL of the ResourceItem.

## Actual behavior
You need to click the browser return button 3 à 4 times in order to return to previous page. To fix this issue you need to use the Link component from `react-router-dom` instead of the URL prop on the ResourceItem.

<img width="546" alt="Screenshot 2022-02-03 at 10 28 41" src="https://user-images.githubusercontent.com/44461075/152315917-68f008d3-d56d-4292-ac2e-0d0d161f87af.png">

## Steps to reproduce the problem

1. Make an app
2. Use the ResourceList  and a ResourceListItem with URL
3. Return using the default browser arrows

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 8.0.0
- Browser: Chrome 
- Device: iMac
- Operating System: OS

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 703.34 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: 91.0
    Safari: 14.0
  npmPackages:
    @shopify/polaris: ^8.0.0 => 8.0.0 
    react: 16.14.0 => 16.14.0 
    react-dom: 16.14.0 => 16.14.0 

```

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

**Comment by yurm04** [comment]
Hey @EvaDenys99 👋 Thanks for reaching out. Do you have an example app, codebase or codesandbox that you can link as an example? This will help with triaging.

At first glance, this might be more relevant in the AppBridge. Have you tried reaching out there?
