### ISSUE TITLE
Export tokens as a part of polaris-react NPM package

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#5095]

**Comment by kyledurand** [comment]
Wondering what the value is to export tokens as JSON. If we do the work in converting tokens to custom properties why not export them as a css file? 

I know we did this in the past for mobile but I was under the impression the mobile teams weren't using the imports anymore.

**Comment by martenbjork** [comment]
A strong use case is tooling. Let's say that I'm building "token autocomplete for VSCode". Having the tokens as JSON makes it much easier.

**Comment by alex-page** [comment]
I would like to see the tokens package support multiple file types `css` `json` mobile formats. The most important thing today is to unlock the `polaris-styleguide` to use the values and keep them up to date.

I am also worried about exporting them from `polaris-react` as removing them is a breaking change. Maybe there is a tacky approach to start.

We need to get mobile back on tokens. Hopefully getting them out of scss and putting them in one place helps with that journey.
