### ISSUE TITLE
Feature request: add the ability to pass previously selected products/collections to the Resource Picker

### ISSUE THREAD

**Issue by grandelc** [Shopify/polaris-react-archive#51]
# Issue summary

Would like the ability to be able to optionally pass previously selected products/collections when using the Resource Picker.

## Expected behavior

Passing the products/collections will show them as already selected in the list when reopening the Resource Picker.

## Specifications

- Polaris version: 1.0.2

**Comment by babenzele** [comment]
I was excited to add this to the Polaris library with a PR, but `ResourcePicker` is calling the easdk via `window.postMessage()`.

https://github.com/Shopify/polaris/blob/aa9e5d49b4a900aa50f59b482d30c38c26eda22a/src/embedded/easdk/components/ResourcePicker.ts#L36

Is this something that the Shopify team is interested in or planning on pursuing? We're designing around this in our embedded app.

**Comment by gf3** [comment]
hi @babenzele—we don't have a timeline for when it'll be implemented but it is definitely on our radar and something we'd like to address in a future update

**Comment by ry5n** [comment]
Like @gf3 mentioned, this is on our radar for EASDK and Polaris. We treat all feature requests as part of our backlog.

I’ll close this issue for now, but **we encourage everyone who wants this feature to add a 👍** to the original issue report. We’ll take your collective interest into account when we look at what to work on next.

💜
