### ISSUE TITLE
[TextField] Multiline TextField height bug when commas are typed

### ISSUE THREAD

**Issue by julianozapiet** [Shopify/polaris-react-archive#5125]
## Issue summary

When typing in a TextField component with `multiline={true}` prop, it will increase the height of the `textarea` by 24px for each 10 commas typed in the text. The `textarea` then becomes disproportionally big for the text it contains.

## Expected behavior

The height of the `textarea` should increase only with the number of lines.

## Actual behavior

The height increases by 24px for every 10 commas present in the text.

## Steps to reproduce the problem

1. Place a multiline TextField component
2. Type whatever text into it, as long as it contains commas

## Reduced test case

I've created an example at [CodeSandbox](https://codesandbox.io/s/shopify-polaris-react-typescript-playground-forked-nqr2h?file=/src/index.tsx)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: ^6.6.0
- Browser: Chromium (98.0.1108.43)

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

**Comment by yurm04** [comment]
Hey @julianozapiet 👋 thanks for reaching out. We appreciate you bringing this to our attention. I'm adding the `Help Wanted` label to this as the team likely won't be able to prioritize this right now. If you're able to contribute a fix yourself, we would definitely appreciate it. Let me know how we can support you in this if you do end up creating a PR
