### ISSUE TITLE
[IndexTable] Scrollbar is lost when new resources are shown after removing all resources

### ISSUE THREAD

**Issue by carlfranciscastillo** [Shopify/polaris-react-archive#5144]
## Issue summary

After removing all the resources in an `IndexTable` where a scrollbar is perfectly working, adding new resources will cause the scrollbar to completely disappear even if the content should be scrollable.
## Expected behavior

The scrollbar should still be visible if the content inside the `IndexTable` is scrollable.
## Actual behavior

<details>
      <summary>Loss of scrollbar after resources are removed and added back</summary>
      <img src="https://media.giphy.com/media/wNAOixZJjSev54wMKa/giphy.gif" alt="Loss of scrollbar in indextable demo">
 </details>
 
## Steps to reproduce the problem

1. Remove all resources in scrollable `IndexTable`
1. Add a resource in the `IndexTable` which should be scrollable

## Reduced test case

I've created an example at [CodeSandbox](https://codesandbox.io/s/determined-shtern-wzbtm?file=/App.js)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 8.0.0
- Browser: Google Chrome Version 98.0.4758.82 (Official Build) (64-bit)
- Device: Lenovo ThinkPad T15 2i
- Operating System: Windows 10 Pro 64-bit (10.0, Build 19042)

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).
