### ISSUE TITLE
[Combobox] Add support for inline autocompletion

### ISSUE THREAD

**Issue by chloerice** [Shopify/polaris-react-archive#5151]
- [ ] Fix #5148
- [ ] Implement auto-selection and typeahead

**Comment by dleroux** [comment]
Hi @chloerice , as part of the prototype for combobox I had implemented typeahead, which was implemented on the textfield so it can be used with combobox or without:

https://github.com/Shopify/polaris-react/pull/2334/files#diff-0476232e85245a025ae1fd330da91aae821feefc18fdd5f95d6f0a1e935c5292R377
