### ISSUE TITLE
Autocomplete and other controls (eg TextField) are lagging inside ResourceList

### ISSUE THREAD

**Issue by dsounded** [Shopify/polaris-react-archive#5169]
## Issue summary
Text fields and **autocomplete** lag on typing inside `ResourceItem`

## Expected behavior
It should work smoothly (the same way `DataTable` does for such cases)

## Actual behavior
It freezes browser completely after trying to work with Autocomplete

## Steps to reproduce the problem

1. Create an appropriate collection
1. Set `renderItem` for `ResourceList` to render custom component which utilize logic of displaying the item with some autocomplete and other text fields (which essentially changes the item's state)
2. It freezes

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 6.5.0 (but tried to upgrade or find to look up for such things in changelog - no luck)
- Browser: Mozilla firefox 95.0
- Device: Macbook Pro
- Operating System: macOS

**Comment by yurm04** [comment]
hey @dsounded 👋 thanks for reaching out. Can you provide a link to a codesandbox and/or a video with the issue your experiencing? This will help us with triaging. Thank you!
