### ISSUE TITLE
Hi @sgtpsibin

### ISSUE THREAD

**Issue by JefrenDakik** [Shopify/polaris-react-archive#5171]
Hi @sgtpsibin 

It sounds like the one piece you're missing is passing a `linkComponent` prop into AppProvider to allow you to override our links, so that instead of rendering a plain `<a>` tag it renders a react-router `Link`. See the 'with linkComponent` example on https://polaris.shopify.com/components/structure/app-provider for more details.

[You can see an example of this in our polaris-icons app](https://github.com/Shopify/polaris-icons/blob/master/packages/app-icon-explorer/src/components/AppFrame/AppFrame.tsx). That was built with gatsby (and thus reach-router) but the principle would remain the same.

_Originally posted by @BPScott in https://github.com/Shopify/polaris-react/issues/1999#issuecomment-523449781_

This Does not work with Next link Component. It still create a link with <a> tag.

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).
