### ISSUE TITLE
Dark theme and Toast not working on Polaris 9.0

### ISSUE THREAD

**Issue by mcjambi** [Shopify/polaris-react-archive#5212]
My Polaris has stop working on ver9.0, include Darktheme and Toast.
```
  const theme = {
    colors: {
      surface: '#FFFFFF',
      onsurface: '#212B36',
    },
    colorScheme: "dark",
    logo: {
      width: 120,
      topBarSource: isDarkTheme === "dark" ? Logo_dark : Logo_light,
      url: '/',
      accessibilityLabel: 'nBee',
    },
  };



  return (
      <Router basename={baseHref}>
            <AppProvider theme={theme} i18n={viTranslations} linkComponent={NtsLink}>
     ...........
```
Please giving me advice! How to fixed it?

**Comment by alex-page** [comment]
Hey @mcjambi please take a read of our [migration guide](https://github.com/Shopify/polaris-react/blob/main/documentation/guides/migrating-from-v8-to-v9.md#from-themeprovider-to-customproperties) for "from ThemeProvider to CustomProperties". If you have any questions feel free to ask.

**Comment by sam-b-rose** [comment]
@mcjambi, you can statically generate the CSS custom properties for your custom theme overrides using [this step here](https://github.com/Shopify/polaris-react/blob/main/documentation/guides/migrating-from-v8-to-v9.md#replacing-custom-properties-from-theme-overrides). Add your theme object to the `theme.js` file, run `npm run build` in the StackBlitz console, then use the `.scss` output to apply the custom CSS vars to your project 🎨

**Comment by kyledurand** [comment]
Going to close this but please re-open if you feel the issue hasn't been addressed
