### ISSUE TITLE
[IndexTable] Error in translation for key 'Polaris.IndexProvider.selected'.

### ISSUE THREAD

**Issue by 0xBeycan** [Shopify/polaris-react-archive#5215]
Hi, when I try to use the IndexTable component, I get the following error.

`Error in translation for key 'Polaris.IndexProvider.selected'. No replacement found for key 'selectedItemsCount'. The following replacements were passed: '{}'`

![image](https://user-images.githubusercontent.com/50718965/155587514-c46d7823-1021-4782-8138-4287a80a037d.png)

![image](https://user-images.githubusercontent.com/50718965/155587539-43798c18-d3d6-4bcd-98c1-0b56b80dddcb.png)

**Comment by ChaseRun** [comment]
I am also experiencing this error when I try to test the `Index table without checkboxes` example in the [docs](https://polaris.shopify.com/components/lists-and-tables/index-table), and in the [IndexTable Component README](https://github.com/Shopify/polaris-react/tree/main/src/components/IndexTable#index-table-without-checkboxes). 

The docs say that `selectedItemsCount` is not required so I'm not sure why this is happening. I also tried setting the following:
 - `selectedItemsCount={0}`
 - `selectedItemsCount={'All'}`
 - `selectedItemsCount={items.length}`

All these options result in the checkbox being displayed.

**Comment by 0xBeycan** [comment]
Yes, unfortunately, this error should not appear when we turn off the "selectable" event logically. But it turns out.

**Comment by gerjunior** [comment]
Any new on this? I'm going through the same issue.

**Comment by toyelowo** [comment]
Could you provide a sandbox example of when you encounter the error? I'm not able to reproduce this

**Comment by toyelowo** [comment]
@ChaseRun I tried running the `Index table without checkboxes` example from the docs in this [sandbox](https://codesandbox.io/s/index-table-6201hy?file=/src/App.tsx) and didn't run into any error. Could you fork the sandbox and update with the code that encounters an error?

**Comment by renanrcrr** [comment]
@BeycanDeveloper how are you?

This is due to a Polaris version incompatibility issue.

In my case I was working with version 6.2.0 but due to this error I had to change it to version 7.0.0.

After this change is made, it will be necessary to change the location of style.css in _app.js (as was my case). If that was yours, just look in the Polaris library for this aforementioned file. Example:

@shopify/polaris/build/esm/styles.css => version 7.0.0

@shopify/polaris/dist/styles.css => version 6.2.0

I don't need to mention that it will be necessary to reinstall the library in question. =)

**Comment by oribenez** [comment]
I have the same issue, any updates on how to solve it?
I am using the newest Shopify polaris version, my app has been made with the Shopify CLI with Vite
"@shopify/polaris": "^9.11.0"

**Comment by oribenez** [comment]
I found a temporary workaround:

Edit this file '@shopify/polaris/locales/en.json', save it locally, and import en.json from the local file.

**Source:**
`import translations from "@shopify/polaris/locales/en.json";`
`<AppProvider i18n={translations} linkComponent={AppBridgeLink}>
      {children}
    </AppProvider>
`

I've just deleted this line (file: en.json):
      "a11yCheckboxSelectAllMultiple": "Select all {itemsLength} {resourceNamePlural}"

**New code:**
`import translations from "../../translations/en.json"`
`<AppProvider i18n={translations} linkComponent={AppBridgeLink}>
      {children}
    </AppProvider>
`

I hope it will help until Shopify releases an update fix 🐐

**Comment by andrew-braun** [comment]
@oribenez This worked for me; thanks!

**Comment by gsempe** [comment]
I have installed the last version and the issue is still here.
I searched in the IndexTable tests to check if there is any clue. I found one test with `selectable={false}` and I tried to copy the configuration in my own app. No chances either.

https://github.com/Shopify/polaris/blob/95fcf4ad6b684201f9dc9e3f3aff86d5c7558ffb/polaris-react/src/components/IndexTable/tests/IndexTable.test.tsx#L502-L510

The version I use:
```bash
npm list @shopify/polaris

shopify-frontend-template-react@ /Users/gsempe/source/combineorders/combine-orders/web/frontend
└── @shopify/polaris@10.48.0

```

The issue I get:

```
Uncaught Error: Error in translation for key 'Polaris.IndexProvider.a11yCheckboxSelectAllMultiple'. No replacement found for key 'itemsLength'. The following replacements were passed:
```

**Comment by SeanMythen** [comment]
I've been able to get around this error by setting a backup for the **itemCount** prop on the **IndexTable** component, by giving the itemCount an OR condition while my fetch request loads the actual count. 
Setting your second OR condition to an integer of 0 or really any other integer, null, or a string works.

The error seems to occur when itemCount is undefined while your data is being fetched.

See if that works for you [gsempe](https://github.com/gsempe)!

For example:

```
  <IndexTable
    resourceName={resourceName}
    itemCount={orders.length || 0}
    selectedItemsCount={
      allResourcesSelected ? 'All' : selectedResources.length
    }
    onSelectionChange={handleSelectionChange}
    headings={[
      { title: 'Order' },
      { title: 'Date' },
      { title: 'Customer' },
      { title: 'Total', alignment: 'end' },
      { title: 'Payment status' },
      { title: 'Fulfillment status' },
    ]}
  >
    {rowMarkup}
  </IndexTable>
```

**Comment by VijayaLakshmi210800** [comment]
> I have installed the last version and the issue is still here. I searched in the IndexTable tests to check if there is any clue. I found one test with `selectable={false}` and I tried to copy the configuration in my own app. No chances either.
> 
> https://github.com/Shopify/polaris/blob/95fcf4ad6b684201f9dc9e3f3aff86d5c7558ffb/polaris-react/src/components/IndexTable/tests/IndexTable.test.tsx#L502-L510
> 
> The version I use:
> 
> ```shell
> npm list @shopify/polaris
> 
> shopify-frontend-template-react@ /Users/gsempe/source/combineorders/combine-orders/web/frontend
> └── @shopify/polaris@10.48.0
> ```
> 
> The issue I get:
> 
> ```
> Uncaught Error: Error in translation for key 'Polaris.IndexProvider.a11yCheckboxSelectAllMultiple'. No replacement found for key 'itemsLength'. The following replacements were passed:
> ```

hey I am getting the same error says No replacement found for key 'itemsLength' let me know if it is fixed for you

**Comment by VijayaLakshmi210800** [comment]
hey any updates on this??

**Comment by valorloff** [comment]
> The error seems to occur when itemCount is undefined while your data is being fetched.

hey @SeanMythen , this is the key of problem, thank you

**Comment by SeanMythen** [comment]
> > The error seems to occur when itemCount is undefined while your data is being fetched.
> 
> hey @SeanMythen , this is the key of problem, thank you

Glad it worked for you!

**Comment by manojongraph** [comment]
I am facing the same Issue 
`Uncaught Error: Error in translation for key 'Polaris.ResourceList.a11yCheckboxSelectAllMultiple'. No replacement found for key 'itemsLength'. The following replacements were passed: '{"resourceNamePlural":"orders"}'`
    at I18n.js:24:1
    at String.replace (<anonymous>)
    at I18n.translate `(I18n.js:20:1)`
    at selectAllActionsAccessibilityLabel (ResourceList.js:185:1)
    at ResourceList (ResourceList.js:327:1)
    at renderWithHooks (react-dom.development.js:14141:1)
    at mountIndeterminateComponent (react-dom.development.js:17432:1)
    at beginWork (react-dom.development.js:18728:1)
    at beginWork$1 (react-dom.development.js:23691:1)
    at performUnitOfWork (react-dom.development.js:22963:1)

**Comment by jianhuatu** [comment]
我也出现了这个错误，排查后发现resourceName配置错误
`const resourceName = {
    singular: 'product',
    plural: 'products',
  };`
而之前我直接把resourceName指定成products。
itemCount = {products.length || 0} 这个关系不大

**Comment by jianhuatu** [comment]
我也遇到了这个问题，排查后发现resourceName配置错误。
正确的是这样：
`const resourceName = {
    singular: 'product',
    plural: 'products',
  };`
而我之前把resourceName指定成products数据。
itemCount = {products.length || 0} 关系不大。
