### ISSUE TITLE
Toast not showing in Polaris 9.0

### ISSUE THREAD

**Issue by mcjambi** [Shopify/polaris-react-archive#5218]
After upgrade to Polaris 9.0, my Toast stop working. After test 9.0 on official codesanbox at (https://codesandbox.io/s/5k5gj?module=App.js), Toast stops working also. I believe that is a bug!

I temporary fix this issue by display an empty Toast first, and then Toast is working again!
I have added: 
```
<Toast content={null} onDismiss={() => {}}  duration={100} />
```
to App.js !

**Comment by ahmed-adly-khalil** [comment]
Hello, I see this issue is closed, I have the same issue and it's blocking me from submitting my app for review, are we getting a release with the fix?

Thank you
