### ISSUE TITLE
Why the document still refers to the use ThemeProvider?

### ISSUE THREAD

**Issue by zhafed** [Shopify/polaris-react-archive#5219]
[https://polaris.shopify.com/components/navigation/top-bar](https://polaris.shopify.com/components/navigation/top-bar)

**How can see the new documention for polaris 9 updated?**

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

**Comment by berkaygurbuz** [comment]
@zhafed You can follow this [documentation](https://github.com/Shopify/polaris-react/blob/a068ebf84a098cc95512814032e4f7afafb2ac11/documentation/guides/migrating-from-v8-to-v9.md#from-themeprovider-to-customproperties) until it updates. By the way, no more `ThemeProvider` in new version. You should use `CustomProperties`.

**Comment by aaronccasanova** [comment]
As @berkaygurbuz mentioned the migration guide for v9 can be found [here](https://github.com/Shopify/polaris-react/blob/a068ebf84a098cc95512814032e4f7afafb2ac11/documentation/guides/migrating-from-v8-to-v9.md#from-themeprovider-to-customproperties). However, there is no obligation to upgrade to Polaris v9 at this time. We are currently working on the upgrade internally and plan to make a public announcement about the release in the near future.
