### ISSUE TITLE
Using Custom Styles 

### ISSUE THREAD

**Issue by berkaygurbuz** [Shopify/polaris-react-archive#5221]
## Issue summary

I am a new user of polaris-react.I want to use my custom css on components. 

## Expected behavior

For Instance, I change button background color using custom css. While using  button component another component, it's color still change but I expect it colors something different 

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number: 9
- Browser: Chrome
- Device:
- Operating System: Windows

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).
