### ISSUE TITLE
[IndexTable] Add col width prop

### ISSUE THREAD

**Issue by vanmars** [Shopify/polaris-react-archive#5223]
## Feature request summary
It would be nice to have a prop on the `<IndexTable />` component that would allow developers to set custom widths for columns.

## Rationale
Developers wouldn't have to target `th` or `td` in custom scss file.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by johnwheeler** [comment]
This would be great. Also, it appears the IndexTable first column is sticky and there's no text wrapping. When there's too much text, a horizontal scrollbar displays

**Comment by yurm04** [comment]
Thanks for the request, @vanmars . We’re not actively working on this right now, but we keep an eye on all feature requests.
I’ll close this issue for now, but we encourage everyone who wants this feature to add a 👍 to the original issue report. We’ll take your collective interest into account when we look at what to work on next. 💜

**Comment by ericute** [comment]
Any chance of this being prioritized?
