### ISSUE TITLE
Index tables: Different top and bottom corner radiuses

### ISSUE THREAD

**Issue by chelsleathley** [Shopify/polaris-react-archive#5230]
## Issue summary
Polaris sets a border-radius on "Polaris-Card" elements to var(--p-border-radius-wide), which is 8px, and then sets the bottom left and bottom right border-radius of the "Polaris-IndexTable_ScrollBarContainer" to var(--p-border-radius-base), which is 4px. This results in a different corner radius on the bottom of an index table when compared to the top corner radius.

## Expected behavior
Corner radius should be the same on all four corners.

## Actual behavior
Using the default corner radius on index tables results in a different corner radius between top corners and bottom corners of an index table, unless intentionally overridden in the code. This seems strange. Is the difference intentional?

Pages like Gift Cards do not overwrite this default:
<img width="218" alt="Screen Shot 2022-02-28 at 3 16 45 PM" src="https://user-images.githubusercontent.com/63760102/156074793-d53028c5-2478-4403-a161-726024bea59d.png">

However, pages like Products and Price Lists do:
<img width="172" alt="Screen Shot 2022-02-28 at 3 16 18 PM" src="https://user-images.githubusercontent.com/63760102/156074815-47c9bc51-5361-4369-b249-d94c7f6a479e.png">

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: ?
- Browser: Chrome
- Device: Macbook Pro
- Operating System: macOS

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

**Comment by martenbjork** [comment]
Closing the issue for now. As far as I can see, the Cards and the scrollBarContainer now use the same radius (`--border-radius-2`).
