### ISSUE TITLE
Toast is not working with polaris 9

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [Shopify/polaris-react-archive#5246]
## Issue summary
Toast is not showing in Polaris 9 

## Expected behavior
when displaying a toast, it should appear in the UI

## Actual behavior
toast doesn't show 

## Steps to reproduce the problem

try something like 

```
 {type === "toast" && message === "error" && (
        <>
          <Toast
            error={error}
            content="There was an error "
            onDismiss={() => {
              setNotification({});
            }}
            duration={3000}
          />
        </>
      )}
```

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 9
- Browser: chrome latest
- Device: mac
- Operating System: macos

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

**Comment by alex-page** [comment]
This is closed in https://github.com/Shopify/polaris-react/commit/4cd8ffab08f95015e31f4a0a31ae154c5b90a1ec. Let me know if it still persists.
