### ISSUE TITLE
Add animated spinner to Buttons

### ISSUE THREAD

**Issue by heyjoethomas** [Shopify/polaris-react-archive#5247]
## Feature request summary
When the loading state is selected, add animated loading spinner (gif).

## Rationale
This will allow designers who are building prototypes to mock up more realistic screens.

**Comment by edmacovaz** [comment]
@heyjoethomas I created [a branch for animating the button spinner](https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/branch/9U8etURxpyW3HaFKH48TT3/Polaris-Components?node-id=59391%3A20322)  . 

My only open question: is there a convention for assets that are used to build components but shouldn't be used as components themselves? It's named to be hidden from asset lists, but I'm not sure if there's already a place in the file for items like this?
