### ISSUE TITLE
How to run Storybook on Windows?

### ISSUE THREAD

**Issue by mhlozek** [Shopify/polaris-react-archive#5261]
## Issue summary

I made this steps:

1. Clone repo
2. Install packages with `yarn install`
3. Run Storybook with `yarn storybook` or `yarn dev` command

everything was ok but  Storybook app launch the browser and I get an error:

```
Couldn't find any stories in your Storybook.
- Please check your stories field of your main.js config.
- Also check the browser console and terminal for error messages.
```

Should I configure some paths?

**Comment by alex-page** [comment]
@mhlozek this sounds like an issue with storybook. What happens when you go to https://storybook.polaris.shopify.com ?

**Comment by mhlozek** [comment]
Everything is ok on https://storybook.polaris.shopify.com/

I attach log from my console in browser when running storybook locally

[localhost-1647263746785.log](https://github.com/Shopify/polaris-react/files/8245089/localhost-1647263746785.log)

**Comment by martenbjork** [comment]
I'm gonna close due to inactivity. We'll be looking into phasing out Storybook over the coming months.
