### ISSUE TITLE
polaris monorepo

### ISSUE THREAD

**Issue by romellogoodman** [Shopify/polaris-react-archive#5266]
## Summary

Polaris is now a monorepo! 🥳 🚚 

## MVP v0.0.0

Monorepo MVP PR 👉  #5306

**Configuration**

* [x] #5286
* [x] Write README.md files
  * Write a top-level README for the monorepo
  * Write a README for each package
* [x] Rename polaris-react to polaris and update links on vault, readme files, [polaris.shopify.com]

**Polaris React**

* [x] #5301
* [x] Update [changelog workflow](https://github.com/Shopify/polaris-react/blob/monorepo-mvp/.github/changelog.yml)

## Follow-Up Work

Capturing future work in order to convey the scope of the project and ensure our work has an eye towards where we are headed. Implementation for some of these areas might better be found in #5073. The tasks below solely reference them as they relate to being migrated and maintained within the monorepo.

**Monorepo Configuration**

* [x] #5300
* [x] [Create a top-level lint command for testing every workspace](#5418)
* [x] #5433
* [x] #5432
* [x] #5431
* [x] #5436 
* [x] #5437
* [x] #5438
* [x] #5439
* [x] #5440
  * Revisit the files present and prune unneeded functionality

**Polaris React**

* [x] Examine the configuration files and prune unnecessary files, example: `polaris-react/pre-commit`
* [x] #5441

**Comment by laurkim** [comment]
@romellogoodman heads up, I opened a [PR](https://github.com/Shopify/polaris/pull/5320) to address updating the `build-consumer.js` script in `polaris-react`

**Comment by sam-b-rose** [comment]
All of the follow up work items have issues tracking their progress. Closing out this issue in favor of moving tracking to those and using the [infrastructure baseline](https://github.com/orgs/Shopify/projects/2250/views/52?type=beta) board
