### ISSUE TITLE
[IndexTable] Add `loading` to promoted bulk actions

### ISSUE THREAD

**Issue by s-johnston** [Shopify/polaris-react-archive#5282]
## Feature request summary

I've seen a few use cases where having an optional `loading` prop for bulk actions on the IndexTable would be useful. For example, one bulk action I've recently modified requires a few seconds of wait time while a query loads before a modal comes up to confirm the bulk action. I have used the `disabled` state for now, but I think it would be clearer to the merchant if the bulk action had a `loading` state.

<img width="806" alt="Screen Shot 2022-03-15 at 10 30 14 AM" src="https://user-images.githubusercontent.com/39162293/158400659-e4b87af4-1038-4775-b19f-a37564ca1e92.png">

## Rationale

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).
