### ISSUE TITLE
Create FullScreenTopBar component in Polaris

### ISSUE THREAD

**Issue by AaronSpringut** [Shopify/polaris-react-archive#5288]
## Component name
FullScreenTopBar

Short intro description (try and keep to two sentences):
The bar is for use by 3p (and 1p) apps when running in FullScreenMode while embedded in the Shopify Admin. It contains a "Back" button and a customizable area where developers can add other controls. This helps provide a consistent experience (including how to leave Full Screen Mode) for merchants when apps enter Full Screen Mode.

* As a merchant, I can always see a "Back" button at the top left of the full screen bar, so that I can easily return to the main admin experience from any fullscreen app.
* As a developer, I can add the FullScreenBar to the top of my page and customize the area of the bar to the right "Back" button so I can add extra information  and controls for my fullscreen experience. 

## Examples
This pattern is currently used by a number of 1p apps, however, implementations are not always consistent. 

### Flow
![image](https://user-images.githubusercontent.com/97750621/158461925-6aeb18b4-5653-4a5f-8f77-4b272fc92fe2.png)

### Online Store 
![image](https://user-images.githubusercontent.com/97750621/158462115-758ac930-98cd-44ec-842b-0ef521ab0974.png)

###Buy button
![image](https://user-images.githubusercontent.com/97750621/158462226-f7131e9b-768c-4a74-b378-d83e86d61a03.png)

## Props

List props and type declarations:

> - **onBackClick** (optional): `() => void` – Callback when back button is  clicked

## Best practices

The FullScreenTopBar component should:

- Always be used when an embedded app enters Full Screen Mode.
- Remain at the top of the merchant's screen regardless of scroll.
- Return the user to the normal (non-fullscreen) embedded app experience when the "Back" button is clicked by using the appropriate AppBridge API. You may display a dialog that confirms whether the merchant would like to discard any unsaved work if saving is required or if leaving fullscreen will destroy a merchant's progress.

**Comment by sherisoli** [comment]
👋 Cool! Here's an example of what our full screen header experience looks like over in SFN:

<img width="1110" alt="Screen Shot 2022-03-21 at 10 37 15 AM" src="https://user-images.githubusercontent.com/16065116/159284380-955190a7-f4bd-4e9e-93da-08942c470341.png">


We have both a header and a footer and put the page actions in the footer :)

**Comment by pabmtl** [comment]
@AaronSpringut 

Hey Adam, I wanted to add a screenshot of the Notebook experience. Which will be a 1P app.

Notebooks will be in dark mode following our Polaris Viz patterns. We are wondering if we can include theming similar to what the Polaris Viz library does. Whereas consumers we can choose to show our data Visualization in light mode or dark mode

<img width="1509" alt="Screen Shot 2022-03-21 at 9 45 51 AM" src="https://user-images.githubusercontent.com/58564150/159274243-bd934bb4-6e63-41d5-bb42-b9314886d2ae.png">

**Comment by alex-page** [comment]
This shouldn't be built for different themes. It should be built with Polaris tokens and then be able to adjust based on the context.

**Comment by kyledurand** [comment]
I can help out with reviews and guidance when needed

**Comment by AaronSpringut** [comment]
Thanks Kyle! @camd is going to take the bulk of this work. He'll reach out for an intro/starting guidance.

**Comment by gil--** [comment]
![CleanShot 2022-09-09 at 11 24 17](https://user-images.githubusercontent.com/3484527/189386020-4ae068d1-cb53-4d5e-9ebf-4184c7b34eb8.gif)

Wondering if it would be possible down the road to consider matching the styles closer to the theme editor?  Maybe a simple "compact" prop?

Currently:
![CleanShot 2022-09-09 at 11 24 02](https://user-images.githubusercontent.com/3484527/189386100-125d89dd-1c5e-40da-8cac-10cc1db645f8.png)
