### ISSUE TITLE
App sub navigation unclear

### ISSUE THREAD

**Issue by lukees** [Shopify/polaris-react-archive#53]
In the current EASDK, apps can employ secondary buttons and breadcrumbs for internal app navigation:

<img width="1025" alt="screenshot 2017-05-11 09 49 21" src="https://cloud.githubusercontent.com/assets/28061273/25961431/216a22ae-362f-11e7-9b0b-020c194776c2.png">

The UI Kit seems to suggest that apps can use the admin sidebar for internal navigation items, yet the example app appears to actually be a channel undercutting the suggestion and leaving me confused 😢 

<img width="630" alt="screenshot 2017-05-11 09 51 41" src="https://cloud.githubusercontent.com/assets/28061273/25961521/709f766c-362f-11e7-8ed6-154e9dcdebf2.png">

**Comment by ry5n** [comment]
Sorry for the confusion on this—these examples are definitely misleading re: main navigation. Although channels can add items to the main nav, apps can’t (which is the current state of things in EASDK that you described).

For primary navigation in apps, the recommended approach is to use tabs on a central landing page for the app.

We’ll clarify these examples for the next release.

**Comment by uri3000** [comment]
How about sub pages or handling sub components with routing in mind?
