### ISSUE TITLE
Publishing a developer doc about custom CSS values (or tokens)

### ISSUE THREAD

**Issue by kemaltatar** [Shopify/polaris-react-archive#5304]
## Feature request summary

Developers who are not familiar with the history of updates struggle to understand what is the encouraged/efficient way to write css on project that use polaris(e.g. shopify/web) since it's not documented yet.

[This](https://github.com/Shopify/polaris-react/blob/main/documentation/guides/migrating-from-v8-to-v9.md) was a useful but it was hard to find and doesn't cover everything.

Developers could easily go off the tracks without any guidelines or documentation.

## Rationale

Documenting current CSS variables/styling guidelines will make alignment easier for current and future FEDs.

Further discussion on [this](https://shopify.slack.com/archives/C019H1T86D8/p1647516537794759) 🧵

<details>
  <summary>(Question on slack, in case slack archive deleted)</summary>

Hey folks,
Does anyone know if there is a documentation/guide for me to understand polaris sass variables/functions/mixins (or css in general) and use them effectively?
(E.g. there are some functions like spacing, focus-ring, rem, ...)
I couldn't find in [web-foundations](https://github.com/Shopify/web-foundations) or [polaris-react](https://github.com/Shopify/polaris-react).
[Polaris design doc](https://polaris.shopify.com/design/spacing#section-principles) was useful but this is more of a doc for designers rather than devs.

</details>

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by alex-page** [comment]
@kemaltatar we have this page live https://polaris.shopify.com/tokens/getting-started-with-tokens

I am going to close this issue but feel free to reopen if you think it's not resolved.
