### ISSUE TITLE
Theme provider page is not loading any content

### ISSUE THREAD

**Issue by jakerich1** [Shopify/polaris-react-archive#5338]
## Issue summary

The theme provider documentation page is not loading any content. https://polaris.shopify.com/components/structure/theme-provider

## Expected behaviour

Expecting the theme provider documentation to be displayed.

## Actual behaviour

Instead, I get the following:
<img width="700" alt="Screenshot 2022-03-24 at 14 08 44" src="https://user-images.githubusercontent.com/19859731/159934668-debb17b6-cb48-4601-9156-236566dfd86a.png">

No errors appearing in the console or network tabs.

## Steps to reproduce the problem

1. visit this live URL https://polaris.shopify.com/components/structure/theme-provider

## Specifications
- Browser: Firefox developer edition 98.0b5
- Device: MacBook Air M1 (2020)
- Operating System: MacOS Monterey 12.0.1

**Comment by kyledurand** [comment]
👋 Hey @jakerich1. We recently upgraded the styleguide from v8 to v9 where the `ThemeProvider` component was replaced by `CustomProperties`. I think our search just needs to re-index the site but I'm not sure exactly how to do that through `algolia`. I'll look into it and see if we can also fuzzy match to CustomProperties when you search for ThemeProvider cc @alex-page 

This [migration guide](https://github.com/Shopify/polaris/blob/main/documentation/guides/migrating-from-v8-to-v9.md#from-themeprovider-to-customproperties) from v8 to v9 might be able to help you with your app
