### ISSUE TITLE
[Multiselect] Native mobile designs

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#5380]

**Comment by adrianefong** [comment]
Tag component UI updated - [[Tags] Design and consistency update #37236](https://github.com/Shopify/core-issues/issues/37236)

[Tag Multiselect care package](https://docs.google.com/document/d/1o1pjpf8S0npkMyZ9ILuA2lPXAKz1--_rcyD5D9vO-9s/edit#)
