### ISSUE TITLE
Update yarn

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#5444]
dev.yml yarn version is old. This should be updated.

**Comment by BPScott** [comment]
It'd be interesting to see if using yarn 3.x is viable as it brings in a bunch of improvements to publishing across a whole workspace compared to v1.

It might be interesting to play with [`corepack`](https://nodejs.org/docs/latest-v16.x/api/corepack.html) to automate the installation of these newer versions - possibly adding corepack support to dev's initialization of the node environment.

**Comment by sam-b-rose** [comment]
Challenging question here. Would it be too wild to migrate to [pnpm](https://pnpm.io/)? I've heard numerous great thinks and performance advantages to using pnpm over yarn for optimized package management and workspace handling.

**Comment by aaronccasanova** [comment]
While we are challenging conventions, is `npm` and `npm workspaces` off the table?
