### ISSUE TITLE
In polaris-react, bump react version in peerDependencies to 18.0.0

### ISSUE THREAD

**Issue by andreas-x4149** [Shopify/polaris-react-archive#5477]
## Feature request summary

In polaris-react, bump react version in peerDependencies to 18.0.0.

## Rationale

When generating Next.js project, react version by default is 18.0.0, while in peerDependencies it's "^16.14.0 || ^17.0.0" now.  
So right now, new Next.js projects can't install & use polaris-react from the start.

**Comment by mbaumbach** [comment]
In addition to this, it would be great if both `@shopify/polaris` and `@shopify/polaris-icons` updated their TypeScript typings to remove the use of the deprecated `React.SFC` so that projects using TypeScript will also be able to adopt Polaris on React 18.

**Comment by imjuniper** [comment]
Hey there! Was just wondering if there was any update on this, as React 18 has been out for a while now, and even the `@shopify/react-testing` library supports it.
