### ISSUE TITLE
[Tokens] Color tokens - Separate rgb and alpha values

### ISSUE THREAD

**Issue by aveline** [Shopify/polaris-react-archive#5482]
Currently our color tokens use `rgba()` ex. `"background": "rgba(246, 246, 247, 1)"`

This ties the actual color value with the alpha value and lacks flexibility. We should separate the color values from the alpha value and then combine when necessary.

This would entail separating the color values ex. `"background": "246, 246, 247"` and then also generating the rgb token ex. `"background-rgb": "rgb(var(--p-background))"`

This would allow for consumers to customize the alpha value when needed ex. `color: rgba(var(--p-background), 0.5)`

The tokens should be generated in a way that allows them to be used not only for the web, but also other tools like the api and Figma.

**Comment by alex-page** [comment]
@samrose3 @heyjoethomas this could be a good addition to any color token infrastructure projects.

**Comment by sam-b-rose** [comment]
@aveline do we still think this level of color flexibility would be good to provide? We may want to provide example usages and use-cases of where this is needed or high-value.

Splitting our tokens into these separate color and alpha does increase flexibility, but also complexity and potential for greater system divergence. Happy to help explore this strategy!
