### ISSUE TITLE
Scrappy code prototype

### ISSUE THREAD

**Issue by aveline** [Shopify/polaris-react-archive#5503]
Scrappy coded prototype using storybook and existing react components

 - [ ] ~Desktop view~
 - [x] Mobile view (with native banners could be images)
 - [ ] Disable focus style for tappable elements

Enough pages to show examples of patterns from below
  - [x] #5498 
  - [x] #5499 
  - [x] #5515
  - [x] #5501

**Comment by aveline** [comment]
<img width="375" alt="native-banner-gift-cards2x" src="https://user-images.githubusercontent.com/3474483/164063378-671b89dc-5c3e-47e1-8622-ab39e938de54.png">
<img width="375" alt="native-banner-tab-bar" src="https://user-images.githubusercontent.com/3474483/164063402-bbf4ba88-1279-4f7a-a16c-0c2b9e420b40.png">

**Comment by alex-page** [comment]
@aveline closing this one as the project is done. Thanks a ton 💯
