### ISSUE TITLE
Changing font family doesn't work in CustomPropertyOverrides 

### ISSUE THREAD

**Issue by iblecher** [Shopify/polaris-react-archive#5506]
## Issue summary
In order to change the font family I tried to set the custom property `--p-font-family-sans` inside `CustomPropertyOverrides.module.scss`.

## Expected behavior
The font family should change in all the components.

## Actual behavior
The font family didn't change and remained the default one.

## Steps to reproduce the problem

1. Create a react app with Polaris 
2. Use the following `CustomPropertyOverrides.module.scss`:

```
.CustomPropertyOverrides {
  &[p-color-scheme="light"] {
    --p-font-family-sans: BatonTurboWeb, Arial, "sans-serif";
    --p-action-primary: rgba(91, 105, 195, 1);
    --p-action-primary-hovered: rgba(74, 89, 179, 1);
    --p-action-primary-pressed: rgba(62, 76, 154, 1);
    --p-action-primary-depressed: rgba(39, 48, 102, 1);
    --p-text-primary: rgba(86, 101, 192, 1);
    --p-text-primary-hovered: rgba(72, 87, 175, 1);
    --p-text-primary-pressed: rgba(60, 74, 150, 1);
    --p-surface-primary-selected: rgba(246, 246, 248, 1);
    --p-surface-primary-selected-hovered: rgba(199, 200, 214, 1);
    --p-surface-primary-selected-pressed: rgba(179, 181, 199, 1);
  }
}
```

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number: 9.4.0
- Browser: Firefox
- Device: MacBook
- Operating System: MacOS

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

**Comment by aaronccasanova** [comment]
Thank you for bringing this to our attention @iblecher! Will you share a demo/codesandbox of your issue?

**Comment by iblecher** [comment]
@aaronccasanova Sure!
Here's a link: [https://codesandbox.io/s/polaris-custome-properties-font-change-example-xtqu0f](https://codesandbox.io/s/polaris-custome-properties-font-change-example-xtqu0f)
(and thank you for responding so quickly :)

You can see that the card header (with class `Polaris-Heading`) have a computed `font-family` value of `-apple-system, BlinkMacSystemFont, "San Francisco", "Segoe UI", Roboto, "Helvetica Neue", sans-serif` instead of `BatonTurboWeb, Arial, "sans-serif`).

The weird part is that the button (with class `Polaris-Button__Text`) has the expected font family set.

**Comment by aaronccasanova** [comment]
Thanks for the codesandbox! This is occurring because elements in the system inherit `font-family: var(--p-font-family-sans)` from a global stylesheet targeting `html`, `body`, and `button` elements. However, in this case overriding the custom property only applies if a given element is included in the prior targets or if `font-family: var(--p-font-family-sans)` is redefined on the `CustomProperties` container. We will be testing both approaches and appreciate your patience as we determine the appropriate path forward.

**Comment by iblecher** [comment]
Thanks for the reply @aaronccasanova 
Can you suggest a way to change the font type in a Polaris project then?

**Comment by aaronccasanova** [comment]
Here is my [WIP upgrade PR](https://github.com/Shopify/polaris/pull/5541) for adding custom font family support to the `CustomProperties` component. We are in the process of testing the changes for visual regressions in the admin and again appreciate your patience while we validate the updates.

> Can you suggest a way to change the font type in a Polaris project then?

For the time being you can manually redefine the `font-family: var(--p-font-family-sans)` property on the `CustomPropertyOverrides` class:
https://codesandbox.io/s/polaris-custome-properties-font-change-example-forked-ozr4ny?file=/src/CustomPropertyOverrides.module.scss

**Comment by iblecher** [comment]
thank you @aaronccasanova  - you're the best!
