### ISSUE TITLE
[polaris.shopify.com] The Navigation Main Page in the docs gets infinitely bigger

### ISSUE THREAD

**Issue by bethkellyshopify** [Shopify/polaris-react-archive#5538]
## Issue summary

When I navigate to https://polaris.shopify.com/components/navigation/navigation#navigation - the page loads but the navigation example starts to infinitely expand, making it nearly impossible to read any of the content below that level (especially by scrolling to it).  I'm using iOS, with Chrome, and I've tried reloading the page and also selecting different example cases.

## Expected behavior

The page should load with the Navigation example framed in a finite, smallish size, so that the user can scroll down and read the text below it.

## Actual behavior

Infinite expansion - as seen in scroll bar and my demonstrated example of not being able to scroll below the navigation example.

    <details>
      <summary>Summary of your gif(s)</summary>
      <img src="https://user-images.githubusercontent.com/93728142/163624292-1d17c286-9c6e-40d8-b2d8-618695eb58e2.mp4" alt="Never-ending Navigation">
    </details>

## Steps to reproduce the problem

1. Load this page: https://polaris.shopify.com/components/navigation/navigation#navigation
2. Watch scroll bar expand indefinitely/infinitely

## Reduced test case

Sorry, I don't have time for this.

## Specifications
This is a documentation issue, using and iOS laptop, and Chrome.  Same problem happens on Safari.

**Comment by stewx** [comment]
I believe this is fixed now

**Comment by kyledurand** [comment]
Seems like it's resolved itself
