### ISSUE TITLE
[Layout foundations] Align Layout / Page components with 4 / 12 column grid

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris-react-archive#5553]
- [x] Page – Page should only be concerned with basic padding

**Layout**
- [x] Should handle multiple layouts within a 4 and 12 column grid
- [ ] Default to full width - **We can't do this with css grid. This will be a breaking change**
- [x] Allow halves, and thirds
- [x] Secondary should take up 4 columns and can be placed on the left or right of primary
- [x] Annotated sections should follow the rule of secondary but can only be placed on the left

![image](https://user-images.githubusercontent.com/6844391/164039739-2b3fda00-76c9-40a7-8f15-9444fa2d32ad.png)

TODO:
- [x] Explore fixing flex layout
- [x] Explore grid layouts (grid-template-columns, grid-auto-flow: row, grid-column-end)
- [x] Explore other design systems

**Comment by alex-page** [comment]
@kyledurand are you still working on this?

**Comment by kyledurand** [comment]
Yes this still needs work. I'm going to re-work https://github.com/Shopify/polaris/pull/5552 that keeps the annotated section around and ship in v11

**Comment by laurkim** [comment]
Resolved by [8387](https://github.com/Shopify/polaris/pull/8387)
