### ISSUE TITLE
changes to `CustomPropertyOverrides` are not reflected in components inside `Modals`

### ISSUE THREAD

**Issue by iblecher** [Shopify/polaris-react-archive#5585]
## Issue summary
I've used the [legacy custom properties migration](https://stackblitz.com/edit/legacy-v8-custom-props?file=README.md) to change the `primary` color of my app.
That change doesn't take affect in buttons inside `Modals`  

## Expected behavior
All elements using `primary` colors should reflect the color change.

## Actual behavior
Buttons (with `primary` set) inside `Modal` do not change their color

## Steps to reproduce the problem

1. Create a react app with Polaris 
2. Use the following `CustomPropertyOverrides.module.scss`:

```
.CustomPropertyOverrides {
  &[p-color-scheme="light"] {
    --p-action-primary: rgba(91, 105, 195, 1);
    --p-action-primary-hovered: rgba(74, 89, 179, 1);
    --p-action-primary-pressed: rgba(62, 76, 154, 1);
    --p-action-primary-depressed: rgba(39, 48, 102, 1);
    --p-text-primary: rgba(86, 101, 192, 1);
    --p-text-primary-hovered: rgba(72, 87, 175, 1);
    --p-text-primary-pressed: rgba(60, 74, 150, 1);
    --p-surface-primary-selected: rgba(246, 246, 248, 1);
    --p-surface-primary-selected-hovered: rgba(199, 200, 214, 1);
    --p-surface-primary-selected-pressed: rgba(179, 181, 199, 1);
  }
}
```

## Reduced test case
[https://codesandbox.io/s/polaris-custome-properties-font-change-example-forked-yi6nr1?file=/src/App.tsx](https://codesandbox.io/s/polaris-custome-properties-font-change-example-forked-yi6nr1?file=/src/App.tsx)

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number: 9.4.0
- Browser: Firefox
- Device: MacBook
- Operating System: MacOS

## Preview
<img width="840" alt="image" src="https://user-images.githubusercontent.com/1990343/164704603-8ac46788-c173-4bd4-8c07-2e69f81152f2.png">

**Comment by iblecher** [comment]
@aaronccasanova hi - did anyone got to go over this issue?

**Comment by BobbyAdamson** [comment]
Also having this problem

**Comment by iblecher** [comment]
@BobbyAdamson this is my current workaround:
in `App.tsx`

```
  useLayoutEffect(() => {
    const body = document.querySelector("[class*=CustomPropertyOverrides]");
    const portalsContainer = document.querySelector("#PolarisPortalsContainer");

    // apply CustomPropertyOverrides classname and color scheme to modals
    if (body && portalsContainer) {
      portalsContainer.classList.add(body.className);
      portalsContainer.setAttribute("p-color-scheme", "light");
    }
  }, []);

**Comment by BobbyAdamson** [comment]
Thanks @iblecher. I ended up just modifying the stylesheet that the migration doc spits out to apply the CSS variables to the parent elements for the main app as well as the modal containers e.g. this css selector `.customPropertyOverrides[p-color-scheme='light'] {` became this: `.Polaris-Modal-Dialog__Container, .Polaris-Frame {`

**Comment by martenbjork** [comment]
Hi friends! Closing this issue since the CustomProperties component is being deprecated in Polaris v10:

https://github.com/Shopify/polaris/blob/main/documentation/guides/migrating-from-v9-to-v10.md/#removing-customproperties
