### ISSUE TITLE
Feature request: Color picker input field?

### ISSUE THREAD

**Issue by gapipro** [Shopify/polaris-react-archive#56]
# Feature request summary
Currently there isn't a variant of input field for color picker. 

## Expected behavior

It would be ideal to have a color type of input field that renders selected color to the right side of input and it opens color picker dropdown on click.

## Actual behavior

This behaviour doesn't exist yet. Only color picker dropdown is available

## Specifications

- Polaris version: v1.0.3

**Comment by lemonmade** [comment]
Hey @gapipro, thanks for the issue. We have an issue on our internal tracker to do build something along these lines, so I'll leave this issue open and update it when we've made some progress on that front.

**Comment by JoshHighland** [comment]
I would really like this feature also. I'm not able to move to the new color picker with out this feature.

**Comment by buggy** [comment]
I think you can simulate part of that by putting a ColorPicker inside a Popover triggered from a Button.

```javascript
<Popover
    active={this.state.picker}
    sectioned={true}
    activator={<Button onClick={() => { this.setState({picker: true}); }}>Sales channels</Button>}
    onClose={() => { this.setState({ picker: false }); }}
>
    <Popover.Pane fixed>
        <Popover.Section>
            <div style={{ width: "200px", height: "200px" }}>
                <ColorPicker color={{ hue: 120, brightness: 1, saturation: 1, }} onChange={() => { }} />
            </div>
        </Popover.Section>
    </Popover.Pane>
</Popover>
```

You need to include a div set to 200x200 or it doesn't render properly.

Having said that, I haven't actually got the popover to work properly (it just stays open)

**Comment by tmlayton** [comment]
Just a reminder, we now close feature request issues and label them as `feature requests`. Please continue to upvote 👍if this is important to you. That helps us prioritize which features to work on.

https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md#feature-requests
