### ISSUE TITLE
Stylelint tests opt-in by default

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#5603]
If a new folder with scss is added it shouldn't be tested unless we add it the stylelint config. For example @shopify/polaris should be tested but adding files to polaris.shopify.com should not unless we add it.

**Comment by sam-b-rose** [comment]
@alex-page can you explain this scenario more and the rational? Curious why we shouldn't lint the site as well.

On another note, we currently we lint all packages and folders from the root. We _could_ run stylelint in parallel and lint from the root of each package. Then, if we decided to leverage a pipeline runner like Turborepo, I believe it will cache and and only run on changed files. This would also give us more fine-grain control of what is linted for each package.

**Comment by alex-page** [comment]
@martenbjork we are going to not do this for now and instead investigate individual package linting. It will be a slight inconvenience to exclude new folders as we get there.
