### ISSUE TITLE
Status badges showing incorrect color

### ISSUE THREAD

**Issue by jennipurr** [Shopify/polaris-react-archive#5612]
## Issue summary

Completed status badges are showing a teal circle icon.

## Expected behavior

The circle icon should be grey.

## Steps to reproduce the problem

1. Go to Order and Draft Order Index

## Specifications

- Are you using the React components? (Y/N): N
- Polaris version number: 
- Browser: Chrome
- Device: Mac
- Operating System: Version 100.0.4896.127

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```
<img width="351" alt="Screen Shot 2022-04-26 at 7 51 09 AM" src="https://user-images.githubusercontent.com/55846285/165318823-f8d820a2-2c45-4d60-91ce-6be6ecc29311.png">

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by chloerice** [comment]
Fixed by https://github.com/Shopify/polaris/pull/5618
