### ISSUE TITLE
[Tokens] Audit shadow tokens

### ISSUE THREAD

**Issue by heyjoethomas** [Shopify/polaris-react-archive#5632]
### Context
Polaris currently has 11 different tokens for shadow and elevation. Not only is this far more than we should need there are issues with current naming and infrastructure.

1. Naming convention is either too narrowly scoped (`--p-shadow-popover`) or so generic it doesn't make a ton of sense (`--p-shadow-layer`). Neither allows for someone to use a token with confidence because it either seems out of context or you don't know what the proper context is.
2. 5 of the tokens are not even used within Polars React while 4 are not used in Polars React or Web repos. This is a clear signal that those tokens are not providing any value. 

<img width="1437" alt="Screen Shot 2022-04-27 at 12 02 52 AM" src="https://user-images.githubusercontent.com/5749440/165444287-d4c2a7d6-c2c8-40bf-a5cd-4c0dbdca71a5.png">

### Proposal
I think a quick audit of where/how exactly the other tokens are being used would be helpful. This would then help inform a new direction for shadows. That could mean removing tokens, changing the naming convention and remapping current values.

**Comment by lgriffee** [comment]
Previous work on shadow tokens for reference: 

- https://github.com/Shopify/polaris/issues/4827#issuecomment-991393722
- https://github.com/Shopify/polaris/issues/4614

**Comment by lgriffee** [comment]
We can close this issue with #8572 shipping 🎉
