### ISSUE TITLE
Use pnpm for optimized dependency management and monorepo support

### ISSUE THREAD

**Issue by sam-b-rose** [Shopify/polaris-react-archive#5679]
[pnpm](https://github.com/pnpm/pnpm) is an alternative package manager for Node.js. It is a drop-in replacement for npm, but faster and more efficient (3 times faster – [see benchmarks](https://github.com/pnpm/node-package-manager-benchmark).

📺 [Yarn vs pnpm comparison](https://www.youtube.com/watch?v=d1E31WPR70g)

pnpm has all the additional features that Yarn has over npm:

1. **security**. Like Yarn, pnpm has a special file with all the installed packages’ checksums to verify the integrity of every installed package before its code is executed.
1. **offline mode**. pnpm saves all the downloaded package tarballs in a local registry mirror. It never makes requests when a package is available locally. With the --offline parameter, HTTP requests can be prohibited at all.
1. **speed**. pnpm is faster than npm and Yarn (both with cold and hot cache). Yarn copies files from cache whereas pnpm just links them from the global store.

**Comment by aaronccasanova** [comment]
Let's track [RFC 0042-isolated-mode.md](https://github.com/npm/rfcs/blob/main/accepted/0042-isolated-mode.md). Looks like `npm` might have a `pnpm` like installation mode on their roadmap.

**Comment by BPScott** [comment]
It'd also be interesting to see how yarn v3 holds up. Admin-web-platform would be interested in any comparison of modern package managers, as any thing learned could also be applied to our package monorepos (web-configs / quilt / sewing-kit)
