### ISSUE TITLE
[TextField] Using `multiline` causes `focused` to not focus on the `TextField`

### ISSUE THREAD

**Issue by ghost** [Shopify/polaris-react-archive#5683]
## Issue summary

When attempting to set `focused` on a `TextField` that uses `multiline`, you won't be able to focus on the text field.

## Expected behavior

When setting `focused` on a `TextField` that uses `multiline`, it should function exactly the same as a `TextField` which does not use `multiline`.

## Actual behavior

The `TextField` which has `focused` set to `true` and `multiline` set to some value, will end up with a `TextField` that isn't focused.

### Video of the cases where it works and doesn't work.
https://user-images.githubusercontent.com/73828120/166250129-85b38bc6-10e8-496c-86b6-fb451fbd948c.mov

## Steps to reproduce the problem

1. Create a `TextField` with `multiline` set to some value (example: `<TextField multiline={4} .../>`
2. Add a button component that should in turn cause `focused` on the `TextField` to be set to `True`
3. Have a TextField that isn't focused, but has a `focused` state of `true`.

## Reduced test case
The issue can be tested [here](https://codesandbox.io/s/shopify-polaris-multiline-focusing-bug-on-textfield-19odxc) (CodeSandbox).

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: `9.4.0`
- Browser: Chrome 100.0.4896.127
- Device: Macbook Pro (13-inch, 2020)
- Operating System: macOS 12.0.1

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
  System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 262.95 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.2.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.1.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Edge: 101.0.1210.32
    Firefox: 98.0.2
    Safari: 15.1
  npmPackages:
    @shopify/polaris: ^9.4.0 => 9.4.0
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
```

**Comment by felixmpaulus** [comment]
Same problem 👋🏽.
