### ISSUE TITLE
Clicking outside Popover in an IndexTable.Row does not close Popover. 

### ISSUE THREAD

**Issue by shenst1** [Shopify/polaris-react-archive#5697]
## Issue summary

When  adding a popover to a row in an `IndexTable.Row`, clicking inside the `IndexTable` but outside the `Popover` when the `Popover` is open does not close it. 

## Expected behavior

The popover should close when clicking anywhere outside the `Popover`, even inside an `IndexTable`. An example of this working is in the Products table on the products index page. The status column opens a popover and clicking outside of it when open closes the popover instead of going to the detail page for a product. 

![image](https://user-images.githubusercontent.com/3740533/166519297-b517d3b4-734c-4b5a-b248-ea02991bc58a.png)

## Actual behavior

The click inside the IndexTable performs the event bound to the IndexTable.Row instead of preventing the default and closing the popover. 

## Steps to reproduce the problem

1. Create a popover inside of an `IndexTable.Row`
```
  <IndexTable.Row  selected={selectedResources.includes(id)} position={index}>
        <IndexTable.Cell>
            <div onClick={(e) => e.stopPropagation()}>
              <SomeSelfContainedPopover
                ...props
              />
            </div>
      <IndexTable.Cell>
</IndexTable.Row>
```

2. Open the popover. 
3. Click on the row outside of the popover. 
4. The click will either check the box for the row or follow the primary link url if you have one. 

Wrapping in a `div` with `e.stopPropagation()` allows the initial click on the activator to open the popover in the `IndexTable.Row` without performing the `IndexTable.Row` 's  click event. 
However, clicking on any `IndexTable.Row` after a `Popover` is open performs the `IndexTable.Row`'s click event instead of closing it. The event never bubbles up outside of the `IndexTable` because something inside the `IndexTable` prevents click events from bubbling up outside of it. Since the event bindings for closing a `Popover` are probably on the `window`, that event binding is never reached, so the click event for the row is followed as normal. 

## Specifications

```bash
  System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 172.31 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.5.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 100.0.4896.88
    Safari: 15.4
  npmPackages:
    @shopify/polaris: 7.6.0 => 7.6.0 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 

```

**Comment by TemurbekRuziyev** [comment]
@shenst1 Hello, How did you fix this issue?

**Comment by Imran99** [comment]
Having the same issue. Is there a workaround?

**Comment by TemurbekRuziyev** [comment]
@Imran99  I did a trick, If you click to outside of table, it will be closed

`  
const onPopoverTrigger = () => {
    setPopoverActive((prevState) => !prevState);
    document.body.click();
};
`

**Comment by Imran99** [comment]
Thanks @TemurbekRuziyev I ended up having to use a combination of `document.body.click` on IndexTable.Row onClick to close active popovers and  `e.stopPropogation()` inside the popover to allow you to click items inside the active popover without dismissing it.

```ts
    <IndexTable.Row
      id={id}
      key={id}
      selected={selected}
      position={index}
      onClick={() => {
        document.body.click();
      }}
    >
```

```ts
export const IndexTableCompatible = {
  Popover: (props: PopoverProps) => {
    const { children, ...rest } = props;
    return <Popover {...rest}>
      <div onClick={e => {
        //don't close this popover when clicked inside
        e.stopPropagation();
      }}>
        {children}
      </div>
    </Popover>
  },

  Checkbox: (props: CheckboxProps) =>
    <div onClick={e => {
      //avoid laggy checkbox when clicked
      e.stopPropagation();
      //close active popovers
      document.body.click();
    }}>
      <PolarisCheckbox {...props} />
    </div>
}
```

Unsure how to reopen this issue as this is still a problem (among many others) with IndexTable.

**Comment by Imran99** [comment]
One issue I haven't been able to solve yet is that the popover is not anchored to its activator when you scroll the table horizontally.
