### ISSUE TITLE
Bar component

### ISSUE THREAD

**Issue by javisantos** [Shopify/polaris-react-archive#57]
I tried to manage the Bar using the `<EmbeddedApp>` but looks not ready yet

### Expected

```js
import { Bar } from '@shopify/polaris/embedded';

<Bar icon="url.png" />
```

### Actual behavior

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `t`

**Comment by lemonmade** [comment]
HI @javisantos, we actually changed this pretty substantially from how it works in the EASDK. Instead of a `Bar` component, you use the `Page` component (https://polaris.shopify.com/components/structure/page#navigation), and set your title, icon, primary actions, etc through there. Let me know if I can provide any more clarity on that!

**Comment by isaac** [comment]
@lemonmade do you think it might be possible to add some docs regarding how to do this with Polaris? https://help.shopify.com/api/sdks/shopify-apps/embedded-app-sdk/features#form-submission

**Comment by lemonmade** [comment]
We are working on some more comprehensive examples of apps using Polaris that I believe will address this kind of use case. We did not add any specific documentation for it because we don't want to limit people's ideas of what you can do with these components. Achieving the same thing using the React components is definitely doable (in the onAction callback of your action, find the form node and call .submit), but there are many other ways to achieve this depending on the structure of your application (one that comes to mind, again in the onAction callback: take all of the form data you have stored as state and manually submit it using something like fetch or another request library).

**Comment by chaddjohnson** [comment]
@lemonmade I apologize for bring an old issue back to life; however, it is affecting me.

I am developing an app using Polaris, and it's great. As you mentioned, the `Page` Polaris component allows users to add primary actions to the app. However, this only allows us to add actions within the iframe; for example, I've added a "Help" button here:

<img width="1427" alt="screen shot 2017-10-21 at 2 59 39 pm" src="https://user-images.githubusercontent.com/676134/31855445-225d4c3c-b671-11e7-9aa5-2f9bc208de17.png">

I see another app which uses the `ShopifyApp.Bar.initialize()` method -- which appears to be part of the old(?) Embedded SDK:

<img width="1644" alt="screen shot 2017-10-21 at 3 02 55 pm" src="https://user-images.githubusercontent.com/676134/31855482-a8dd031a-b671-11e7-8dfb-ee1213147331.png">

We would like to do the same in our app: add buttons above the iframe inside the bar. I understand Polaris does not support this.

Could we use the old(?) Embedded SDK in parallel with Polaris to add buttons to the header bar above the iframe? Or, would this violate the [app requirements](https://help.shopify.com/api/listing-in-the-app-store/app-requirements-and-success-criteria/app-review-checklist) and cause Shopify to reject our app?

Additionally, I'd like to know: is the Embedded SDK (that has the `ShopifyApp.Bar.initialize()` method) deprecated in favor of Polaris?

**Comment by lemonmade** [comment]
@chaddjohnson glad you got it sorted eventually. I've opened an issue internally to link to the embedded app documentation from both the main README and the Page component, which should help future developers. Thanks for bringing it up!

**Comment by Bardown26** [comment]
@lemonmade @chaddjohnson I am running into this issue as well and it is still not documented well. Can you explain what you have to do to get the Page attributes(breadcrumbs, title, primaryaction) to show with an embedded app?

**Comment by chaddjohnson** [comment]
@Bardown26 From my `index.js` file:

```javascript
'use strict';

import React from 'react';
import ReactDOM from 'react-dom';
import {EmbeddedApp} from '@shopify/polaris/embedded';
import queryString from 'query-string';
import App from './app';

const config = window.config;

const render = (Component) => {
    ReactDOM.render(
        <EmbeddedApp
            apiKey={config.SHOPIFY_API_KEY}
            shopOrigin={getShopOrigin()}
            forceRedirect={true}
        >
            <AppContainer>
                <Component />
            </AppContainer>
        </EmbeddedApp>,
        document.getElementById('root')
    );
};

function getShopOrigin() {
    const queryParams = queryString.parse(window.location.search);
    const shopOrigin = queryParams.shop ? `https://${queryParams.shop}` : sessionStorage.shopOrigin || undefined;

    /*
     * (Re)cache the shop origin in sessionStorage in case the user refreshes
     * on a page where the shop is unavailable as a query string parameter.
     */
    sessionStorage.shopOrigin = shopOrigin;

    return shopOrigin;
}

render(App);
```

**Comment by tmlayton** [comment]
@Bardown26 as partly shown in @chaddjohnson’s code sample, the `Page` component needs to be a descendant of `EmbeddedApp`. This tells `Page` that it should delegate to the embedded app bar. Building off of the above example, adding a `Page` as a descendant of `EmbeddedApp`:

```jsx
<EmbeddedApp
  apiKey={config.SHOPIFY_API_KEY}
  shopOrigin={getShopOrigin()}
  forceRedirect
>
  <Page
    breadcrumbs={[
      {content: 'Settings'}
    ]}
    title="General"
    primaryAction={{content: 'Save'}}
  >
    <p>content</p>
  </Page>
</EmbeddedApp>
```

will yield:

![image](https://user-images.githubusercontent.com/344839/37435653-5ef6e9cc-27a1-11e8-8075-e9bfbcae57c0.png)

**Comment by ry5n** [comment]
For those finding this issue, in Polaris 2.0 the `EmbeddedApp` component has been renamed to `AppProvider`, as it now works for non-embedded apps as well.

**Comment by chaddjohnson** [comment]
@ry5n Thanks for the update.

Do you happen to know how long v1.8 will remain compatible with Shopify? We haven't taken the time, yet, to upgrade to v2.
