### ISSUE TITLE
Small IndexTable "Select" button

### ISSUE THREAD

**Issue by sydneythomas** [Shopify/polaris-react-archive#5723]
## Issue summary

small Index Table's select functionality if buggy.

## Expected behavior

When clicking the "Select" button, the checkboxes should appear in the table, and the select button should change to show a count of what has been selected and an option to close / toggle the selectability feature off (see Resource List small view)

## Actual behavior
The Select button disappears and is replaced by nothing. The user cannot toggle off the select functionality, which is a blocker if a click event needs to be triggered by the row

[Link to video](https://user-images.githubusercontent.com/25576742/166908858-6c1b930e-e4ef-4654-986b-c0b97acfaa59.mov)

## Reduced test case

[Code sandbox linked directly from the Polaris UI page](https://codesandbox.io/s/nfrvdm?module=App.js)

## Specifications

- Are you using the React components? Yes
- Browser: Chrome
- Device: MacBook Pro (16-inch, 2019)
- Operating System: macOS Monterey 12.3.1

**Comment by ashleyww93** [comment]
This can be fixed by overriding the offending CSS:

```
.Polaris-BulkActions__Group--largeScreen {
    display: block !important;
}
```
