### ISSUE TITLE
Publish the VS Code extension to open-vsx.org too

### ISSUE THREAD

**Issue by imjuniper** [Shopify/polaris-react-archive#5724]
## Feature request summary

With the new extension being released on the VS Code Marketplace a couple of weeks ago, it would be great to also have it on [open-vsx.org](https://open-vsx.org/).

## Rationale

It would make it available to people using VSCodium, Gitpod, etc. It would make for a better experience for more developers, and it would also support open platforms.

**Comment by martenbjork** [comment]
Hi Jakob! We'll only publish the extension on the official VSCode Marketplace for now. We have to be strict when prioritizing the work / maintenance we take on and we reach a vast majority of our users through the official VSCode Marketplace. We might reconsider this down the road!
