### ISSUE TITLE
Filters is using Deprecated Sheet

### ISSUE THREAD

**Issue by meganmajewski** [Shopify/polaris-react-archive#5749]
## Issue summary

When using the `<Filters/>` component I get a deprecation notice for `<Sheet/>` 

## Expected behavior

<Filters/> should be updated to not include Sheet component.  It looks like the error message is disabled [here](https://github.com/Shopify/polaris/blob/414583de7109fca634e29fc67662797bc99df7d4/polaris-react/src/components/Filters/Filters.tsx#L27)

## Actual behavior
https://github.com/Shopify/product-reviews-sample-app/issues/63

## Reduced test case

https://github.com/Shopify/product-reviews-sample-app/blob/main/pages/products/index.js#L146

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 9.6.0
- Browser: Chrome  101.0.4951.54
- Device: M1
- Operating System: Mac

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

  System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 189.20 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Firefox Developer Edition: 97.0
    Safari: 15.4
  npmPackages:
    @shopify/polaris: ^9.6.0 => 9.6.0
    react: ^16.10.1 => 16.14.0
    react-dom: ^16.10.1 => 16.14.0
```

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by alex-page** [comment]
Thanks @meganmajewski! This is definitely something on our radar. We hope to replace the filter pattern in the future and remove the sheet entirely from the design system. For now feel free to use it.

**Comment by IlyaZha** [comment]
It's still relevant.  @shopify/polaris: 10.49.1

**Comment by alex-page** [comment]
Yep. We plan to remove this in v12 of Polaris. Thanks @zhernosekim
