### ISSUE TITLE
CustomProperties component renders duplicate custom properties to root

### ISSUE THREAD

**Issue by kurtpeters** [Shopify/polaris-react-archive#5766]
## Issue summary

Polaris CSS custom properties are rendered to the document with every [CustomProperties](https://github.com/Shopify/polaris/tree/main/polaris-react/src/components/CustomProperties) use (Below screen is of web/admin).

![10-58-505ny-w01o1](https://user-images.githubusercontent.com/11579230/167711865-4a400e2d-687c-482d-a44b-d52fde7dda74.gif)

Noticed there was a [recent change](https://github.com/Shopify/polaris/pull/5329/files#diff-ab6827ef16736166e7b5c5949c109cc24864cf4696cbc373a5ba351e9a8c9a2cR32) to fix FOUC, but the [stylesheet precheck](https://github.com/Shopify/polaris/pull/5329/files#diff-ab6827ef16736166e7b5c5949c109cc24864cf4696cbc373a5ba351e9a8c9a2cL35) was removed as part of that effort.

## Expected behavior

- `<CustomProperties />` mounts one set of custom properties per use since they're assigned to `:root`.

## Actual behavior

- `<CustomProperties />` mounts custom properties with every use, resulting in duplication.

## Steps to reproduce the problem

1. Render the CustomProperties component within or independently with AppProvider (or render two separate instances of CustomProperties).
2. Inspect with dev tools to see multiple elements with an `data-polaris-custom-properties` attribute and duplicate CSS variables assigned to the `:root`

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
  System:
    OS: Linux 5.10 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (32) x64 Intel(R) Xeon(R) CPU @ 2.80GHz
    Memory: 99.79 GB / 125.90 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  npmPackages:
    @shopify/polaris: 9.6.0 => 9.6.0 
    react: ~17.0.2 => 17.0.2 
    react-dom: ~17.0.2 => 17.0.2 
```

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by aaronccasanova** [comment]
Hello @kurtpeters 👋  Thanks for raising the issue. This is a known tradeoff and behaves similar to the previous `ThemeProvider` implementation which inlined custom properties on each containing `div`. This is a temporary solution until `CustomProperties` is updated to consume the stylesheet generated by the Polaris tokens package. Feel free to follow along here: https://github.com/Shopify/polaris/pull/5659#discussion_r861274676

**Comment by kurtpeters** [comment]
Thanks for the context, @aaronccasanova! I'll close this out since the team is currently working on a fix 👍
