### ISSUE TITLE
Dead text link on Error messages page

### ISSUE THREAD

**Issue by pcrede** [Shopify/polaris-react-archive#5768]
## Issue summary

The text link Learn more about preventing errors in the Error Messages section goes to a There's no page at this address error.

## Expected behavior

The link should take me to a page that explains more about preventing errors.

## Actual behavior

The link goes to an error page - https://polaris.shopify.com/patterns-and-guides/crafting-admin#navigation

## Steps to reproduce the problem

1. Determine what the correct page to link to is
1. Update the link to the correct page 

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by alex-page** [comment]
Thanks @pcrede this content was removed so I have also removed the link from the website.
