### ISSUE TITLE
Add nuxt.js support for fellow vue.js developers

### ISSUE THREAD

**Issue by viktorasbuivydas** [Shopify/polaris-react-archive#5813]
## Feature request summary

We all know vue.js is widely used after react.js. It would be really great to add vue.js support to this amazing project!

## Rationale

Most of the people are using polaris building shopify apps, and most of them have a laravel as a backend. It would be really helpful to add vue.js support to expand shopify app dev circle and add new people who do not have much experience working with react. It would greatly increase accessibility to a new developers with experience using vue.js.

---

🌟 I would be really happy to make all vue.js components from react.js version!

**Comment by alex-page** [comment]
Hey @viktorasbuivydas. We are investigating supporting other frameworks as we know that React isn't the best tool for all developers. This is a while away but I will close this comment and share your feedback with our team.

**Comment by neok** [comment]
any updates on this?

**Comment by juzser** [comment]
Try this guys: https://github.com/ownego/polaris-vue
