### ISSUE TITLE
Polaris icons site - throwing errors on file download

### ISSUE THREAD

**Issue by awd** [Shopify/polaris-react-archive#5816]
https://polaris-icons.shopify.com/

When clicking "Download SVG" the browser throws up an error: `Failed - no file` - and nothing is downloaded.

**Comment by alex-page** [comment]
Thanks @awd let me take a look at what is going on.

**Comment by alex-page** [comment]
Fix should be live in about ~5 minutes. If you still notice the problem let me know and re-open the issue.
