### ISSUE TITLE
Polaris components site - including large blobs of CSS

### ISSUE THREAD

**Issue by awd** [Shopify/polaris-react-archive#5817]
https://polaris.shopify.com/components/actions/button#navigation

When viewing the Polaris components, specifically the HTML markup, all components include the root css directives, and it is fairly annoying to scroll down the page for 5 miles before the actual markup is visible.

This is a regression from a fix that solved this last year, and I cannot find the PR right now.

:)

**Comment by alex-page** [comment]
Thanks @awd. We are looking to resolve this issue but we need to update how our `<CustomProperties />` component works as it is rendering out the values.

**Comment by alex-page** [comment]
This is resolved in v9.11.0 of Polaris. I am going to ship the update to polaris.shopify.com now. Thanks @awd.
