### ISSUE TITLE
Dead link in AppProvider's docs

### ISSUE THREAD

**Issue by zyriab** [Shopify/polaris-react-archive#5822]
## Issue summary

The given link to "CustomProperties" is dead. (Using a hyphen when it should not)

## Expected behavior

The link should send me to the proper page -> [https://polaris.shopify.com/components/structure/customproperties](https://polaris.shopify.com/components/structure/customproperties)

## Actual behavior

The given link is dead -> [https://polaris.shopify.com/components/structure/custom-properties#navigation](https://polaris.shopify.com/components/structure/custom-properties#navigation)

## Steps to reproduce the problem

1. Go to the AppProvider's page in Polaris' docs
2. In the dropdown menu, select 'With color scheme'

![image](https://user-images.githubusercontent.com/2111910/168769459-c0b8a61b-e040-4340-933f-130593ef787e.png)

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by alex-page** [comment]
Thanks @ZyriabDsgn. The content on the site will be updated with our next release. Appreciate you opening these issues with clear descriptions.
