### ISSUE TITLE
Improving back buttons to respect context in Orders space

### ISSUE THREAD

**Issue by ksvihar** [Shopify/polaris-react-archive#5825]
Note: We will transfer/triage this issue to the respective repo after chatting with the relevant team. 

### Context

The back button on the order detail page always takes you to the default orders index view instead of taking you to the page/filtered view you initially opened the order detail page from. What's interesting is the the next/previous buttons on the order detail page are respecting the view it was opened from while moving between different orders. So, it seems like the case where the context is being lost upon clicking the back button. Here is a [video reference](https://videobin.shopify.io/v/vJ6qeR).

You can notice this in the URLs too. The URL is updated to the default orders index URL when moving from an order detail page to the orders index view. 

The problem exists in the following pages too:

1. Orders
   - All
   - Drafts
   - Abandoned Checkout
2. Products
   - Collections
   - Gift Cards
3. Themes
   - Blog Posts
   - Navigation > URL Redirects Index

### Expected Behaviour

Merchants might navigate between order index views and order details pages multiple times for multiple reasons when performing different order related tasks. They expect us to preserve the custom view they created to view individual orders. 

### Platform
Web

### Solution/Fix
We should respect the context from which the page was opened from (Context includes - tabbed views, filters, sort, etc). For example, the navigation between products index view and product details page is functioning as expected. The back button on the product detail page is respecting the context and taking back the merchant to the view they opened it from. Note that even if the order detail page was opened in a new window/tab, the context is preserved.

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).
