### ISSUE TITLE
[Typography foundations] Prototype type components

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#5916]
## Prototype two approaches to type components:
- 1 text component
- Multiple text components

## Desired outcomes of the prototypes:

- Understand how we want to handle monospace, and how flexible
- How fluid Displays will feel on mobile
- Transitioning to a single scale and the impact on mobile
- Nesting text components?
- Overriding the default styles?
- How do we handle “positive”, “negative”, “warning” text styles? - Loop in Joe and Sam as they’re working on color

**Comment by laurkim** [comment]
Decided to move forward with single text component after feedback from user testing sessions
