### ISSUE TITLE
Tooltip components stops click event propagation

### ISSUE THREAD

**Issue by bencmilton** [Shopify/polaris-react-archive#5981]
## Issue summary
It appears that the `Tooltip` component has [logic that stops click event propagation](https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/Tooltip/Tooltip.tsx#L98) (added in https://github.com/Shopify/polaris/pull/3959). This seems to prevent the `Popover` component's default "outside click to close" behavior, as well as any other components that are listening for more global click events. If this behavior is still deemed to be the best default, perhaps we can add an `allowClickEventPropagation` prop to manually override it?

![31-21-bm1td-qhzo2](https://user-images.githubusercontent.com/9685204/171196952-228abce4-ec51-4754-b88f-618a81550f00.gif)

Related issue: https://github.com/Shopify/core-issues/issues/39160

## Expected behavior
The `Tooltip` does not stop all click event propagation

## Actual behavior
The `Tooltip` stops all click event propagation, which interferes with other components that may be listening for those events.

## Steps to reproduce the problem

See below 👇🏼 

## Reduced test case

I've made a codesandbox that [reproduces the issue here](https://codesandbox.io/s/jovial-joliot-sxrztf?file=/App.js). Just open the `Popover` and try to click on the first `Tooltip`-wrapped `Button` and notice that it does not close the `Popover`.

## Specifications

```bash
 System:
    OS: Linux 5.10 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (32) x64 Intel(R) Xeon(R) CPU @ 2.80GHz
    Memory: 68.96 GB / 125.90 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  npmPackages:
    @shopify/polaris: ^9.2.0 => 9.2.3 
    react: ~16.14.0 => 16.14.0 
    react-dom: ~16.14.0 => 16.14.0
```

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).
