### ISSUE TITLE
[Spinner] The Spinner component doesn't spin!

### ISSUE THREAD

**Issue by mbaumbach** [Shopify/polaris-react-archive#5985]
## Issue summary

The `Spinner` component no longer spins, it's just static.

## Expected behavior

The `Spinner` spins. 😜

## Actual behavior

The Spinner does not animate.

## Steps to reproduce the problem

1. Add a `Spinner` component to your page.
2. View the page.

## Reduced test case

Reproducible on this code sandbox: https://codesandbox.io/s/b6pkou?module=App.js

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 9.10.0 and 9.11.0
- Browser: Any
- Device: Any
- Operating System: Any

**Comment by mbaumbach** [comment]
From what I can tell the CSS property `p-keyframes-spin` is set as`--p-keyframes-spin:p-keyframes-spin` but the keyframes are defined in the CSS as `@keyframes Polaris-CustomProperties--pKeyframesSpin`.

**Comment by alex-page** [comment]
Thanks @mbaumbach. We are taking a look at this issue. Appreciate you reaching out. Can you confirm if this issue exists in `v9.10.0`?

My gut feeling is we moved the custom properties and forgot the keyframes.

**Comment by mbaumbach** [comment]
@alex-page Yup, I've confirmed it's happening in `v9.10.0` as well.

**Comment by alex-page** [comment]
This is fixed in v9.12.1 thanks for bringing this up so quickly @mbaumbach :legend:

**Comment by mbaumbach** [comment]
Awesome, thanks for the quick fix @alex-page!

**Comment by alex-page** [comment]
@mbaumbach sorry about the delay that npm version should now be live. Let me know if you have any issues. Feel free to open a new issue or reopen this one.

**Comment by mbaumbach** [comment]
@alex-page No worries, I was able to pull down v9.12.1 and confirmed it's fixed on my side. Thanks again!
