### ISSUE TITLE
[polaris.shopify.com refresh] Add google analytics

### ISSUE THREAD

**Issue by martenbjork** [Shopify/polaris-react-archive#5999]
- Page views
- Search terms
- Other events (icon downloads etc)

**Comment by martenbjork** [comment]
https://mariestarck.com/add-google-analytics-to-your-next-js-application-in-5-easy-steps/

**Comment by suredesigntshirts** [comment]
Glad to see GA4 added to Polaris. Thanks for this.

Unfortunately GA4 on standard Shopify is broken and I'm unable to get it fixed via contacting support. I need some devs at Shopify to look at this issue and resolve it for your customers.

Issue? Shopify's [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) HTTP Headers are blocking GA4 at Checkout. 

Full details, Google's documentation on how to fix are here:
https://github.com/Shopify/liquid/issues/1701
