### ISSUE TITLE
Tables not found in documentation

### ISSUE THREAD

**Issue by JoshHighland** [Shopify/polaris-react-archive#6]
# Issue summary

Tables are missing from "Tables and Lists" section of the component documentation - https://polaris.shopify.com/components/get-started

## Expected behavior

Tables are a critical UI component of Shopify. The name "Tables and Lists" implies tables would be included.

## Actual behavior

Table examples are missing from documentation.

**Comment by lemonmade** [comment]
Hey @JoshHighland. Thanks for the issue. We are actually moving away from Tables for most things in our admin. We'll be moving many of the things that are current tables to use the [`ResourceList` component](https://polaris.shopify.com/components/tables-and-lists/resource-list#navigation) instead. We will also be releasing a data table, meant for truly tabular data, in a future release.

I'll open an issue on our styleguide repo to discuss a potential rename of that category, as I agree that it is confusing that a category called "Tables" has no real Table component.

**Comment by JoshHighland** [comment]
Thanks for the feedback. The sketch file has tabular examples in it so it was throwing me off. I'd love to see some examples of how you are moving to ResourceLists so I can make my app match Shopify :)

**Comment by lemonmade** [comment]
We should have some more examples of specifically how to use ResourceList in the near future.

**Comment by chaddjohnson** [comment]
@lemonmade When can Shopify release data table support? We very much need this for our app.
