### ISSUE TITLE
In Safari 10.1, prefix/suffix labels in text fields rendering incorrectly

### ISSUE THREAD

**Issue by bdillon3** [Shopify/polaris-react-archive#60]
# Issue summary

In Safari 10.1 prefix/suffix on text fields rendering incorrectly. The character of the prefix or suffix is rendering low in the text field, thus expanding the height of the text field, and looking visually incorrect. 

## Expected behavior

The prefix/suffix character should be higher in the text field, and not cause the text field to distort its height. 

## Specifications

- Polaris version: 1.0.2
- React version: NA
- Browser: Safari 10.1
- Device: iMac
- Operating System: 10.12.4

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by lemonmade** [comment]
Thanks for the issue, @bdillon3. I've been able to reproduce this on my machine as well. I've added an issue to our internal issue tracker and will update this issue once we ship a fix.

**Comment by lemonmade** [comment]
Should be fixed by v1.1.0
