### ISSUE TITLE
[polaris.shopify.com refresh] Improve metadata for page previews

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#6011]
**Problem**
Sharing references to our docs is a very common use case, but our link previews provide no useful or engaging information.

![Image](https://user-images.githubusercontent.com/38329124/171657789-ac55c696-593f-43ff-a9d4-5ade7edb4ed3.png)

**Solution**
Improve the metadata so that link previews show information that is relevant to the page linked to, such as
- Title
- Image
- Page description

**Comment by romellogoodman** [comment]
Possible implementation

* https://github.com/vercel/og-image
* use puppeteer to screenshot /pages/example/$component

**Comment by martenbjork** [comment]
Shipped a first iteration here! https://github.com/Shopify/polaris/pull/6297
