### ISSUE TITLE
[Enablement] 🥗 Patterns: define, audit and organize existing Polaris patterns, and update guidelines

### ISSUE THREAD

**Issue by chloerice** [Shopify/polaris-react-archive#6032]
## MVP

We will likely have a short blurb on how we think about patterns today with a crosslink to the decision guide/perfect vs consistent content to get folks wheels turning. We'll have a doorway for folks to reach out and talk to us further. I've we're blocked for the MVP, we could potentially have a "Coming soon" illustration. 

[Join the discussion](https://github.com/Shopify/polaris/discussions/6046)

--- 
Update on June 6th:

To move forward on the pattern contribution guidance, we first need a shared definition for "patterns." Then we can look at our [existing patterns](https://polaris.shopify.com/patterns/layout) to identify which items meet the definition vs which might need to be removed or relocated.

Planned next steps:
1. author shared definition of what a Polaris pattern is - @heyjoethomas @jared-fanning 
2. sort existing Pattern documentation based on shared definition, see what patterns we have
mvp pattern contribution process based on the above outcomes/learnings

---

### Ideas

- Pattern Figma Library 
  - Folks can propose new patterns for review
  - Curated patterns there for reference with rationale and research (MVP start with 1?)
  - Good way to test this sort of pathway to contribution that we can learn from and build off of  
  
### Contribution guidance writing checklist

♟ [Content strategy](https://docs.google.com/spreadsheets/d/1EBAK21lG0DGB_xTy9DAUf58q5XjtjwasMUcO3xR9-5k/edit#gid=1966895154)
📝 [Draft doc](https://docs.google.com/document/d/1ydNQA4vFq2MWV3EtPpg87nyUoRNm5QyLOE2lMAf67MY/edit#heading=h.48z3xyj1bttx)
🛣 [Roadmap](https://www.figma.com/file/iN10sMQajPthRlTdrIqSS0/Polaris-Contribution?node-id=0%3A1)

- [ ]  1 to 2 intro sentences that talk about who contributes and what type(s) of contribution can be made. 
- [ ] A section explaining how to contribute using short, guided steps, in bullet format if possible
- [ ] A short section on why and when when in the design/development process contributor can make the contribution 
- [ ] (it may seem counterintuitive to put this after the "how two" steps, but after someone reads this content the first time, they'll want to be able to jump to the steps right away. 
- [ ] This is a dev-first approach to content that prioritizes getting the job done). If it doesn't make sense for your content flow, feel free to swap it around.
- [ ] A call to action that takes the contributor where they can take the first step to contributing
- [ ] A doorway to learn more. That could be a cross link to other types of contributions, the intro, or educational material
- [ ] A link to get help or support from the Polaris team (consider internal vs external support)

## Important decisions made:
-

**Comment by selenehinkley** [comment]
@johanstromqvist @emmaorhun Feel free to take over this issue in our backlog and edit it down to the scope of your work. It was initially created when we started the MVP contribution guidelines. We're using the Contribution project board with github issues to track all the moving pieces :)

**Comment by chloerice** [comment]
Shipped with https://github.com/Shopify/polaris/pull/6856
