### ISSUE TITLE
Decision guide aka Perfect vs Consistent

### ISSUE THREAD

**Issue by selenehinkley** [Shopify/polaris-react-archive#6042]
## Contribution guidance writing checklist

♟ [Content strategy](https://docs.google.com/spreadsheets/d/1EBAK21lG0DGB_xTy9DAUf58q5XjtjwasMUcO3xR9-5k/edit#gid=1966895154)
📝 [Draft doc](https://docs.google.com/document/d/1ydNQA4vFq2MWV3EtPpg87nyUoRNm5QyLOE2lMAf67MY/edit#heading=h.48z3xyj1bttx)
🛣 [Roadmap](https://www.figma.com/file/iN10sMQajPthRlTdrIqSS0/Polaris-Contribution?node-id=0%3A1)

@zecarlostorre's base [content that we'll be working with](https://docs.google.com/document/d/1DZE1B3favjinmYfzSdKIXjm0WaBR0q4_XQbkALkdAD0/edit#heading=h.8ic06q5po6zc)

@sarahill's current concept for visual examples:  
<img width="527" alt="Screen Shot 2022-06-03 at 12 54 07 PM" src="https://user-images.githubusercontent.com/18617698/171940900-b9d33042-0bd7-4ee4-b548-7cb9a010d5b1.png">

- [ ]  1 to 2 intro sentences that talk about who contributes and what type(s) of contribution can be made. 
- [ ] A section explaining how to contribute using short, guided steps, in bullet format if possible
- [ ] A short section on why and when when in the design/development process contributor can make the contribution 
- [ ] (it may seem counterintuitive to put this after the "how two" steps, but after someone reads this content the first time, they'll want to be able to jump to the steps right away. 
- [ ] This is a dev-first approach to content that prioritizes getting the job done). If it doesn't make sense for your content flow, feel free to swap it around.
- [ ] A call to action that takes the contributor where they can take the first step to contributing
- [ ] A doorway to learn more. That could be a cross link to other types of contributions, the intro, or educational material
- [ ] A link to get help or support from the Polaris team (consider internal vs external support)

## Important decisions made:
-

**Comment by sarahill** [comment]
Based on feedback from folks I iterated on the visuals and I'm feeling good about where they're at
[Figma file](https://www.figma.com/file/AmWrEvFtsIhX314gfqsgrx/Perfect-vs.-Consistent?node-id=63%3A9384)



![Image](https://user-images.githubusercontent.com/8629173/172698401-92564f4b-3fe9-4733-a283-8206b57599d3.png)

**Comment by chloerice** [comment]
Shipped in #6217
