### ISSUE TITLE
[Enablement] Improve the "when to make a contribution" section of the intro

### ISSUE THREAD

**Issue by selenehinkley** [Shopify/polaris-react-archive#6059]
The `when to contribute` section in the intro to the [contribution guidelines](https://docs.google.com/document/d/1ydNQA4vFq2MWV3EtPpg87nyUoRNm5QyLOE2lMAf67MY/edit?pli=1#bookmark=id.osd926oxhkg7) would benefit from a visual diagram of our contribution model to help people learn about our model at a glance. See the [model in Figma](https://www.figma.com/file/iN10sMQajPthRlTdrIqSS0/Polaris-Contribution?node-id=0%3A1).

**Comment by jjgali** [comment]
This issue has been addressed by @raquelbreternitz's PR: https://github.com/Shopify/polaris/pull/6726 

When more styling opportunities exist outside of Markdown, we'd like to revisit this "When to contribute" section to make it more visually inviting and revisit the content hierarchy, if necessary.
