### ISSUE TITLE
Dropdown in embedded app page actions

### ISSUE THREAD

**Issue by dhmacs** [Shopify/polaris-react-archive#61]
[Button objects](https://help.shopify.com/api/sdks/shopify-apps/embedded-app-sdk/methods#button-objects) in the embedded app SDK have the `type` property which lets define them as a dropdown. Reading the code it seems that this is not allowed using Polaris page actions, is this something that you are deprecating or is it just missing?

**Comment by lemonmade** [comment]
Thanks for the issue, @macs91. They are not deprecated and we do intend to add equivalent functionality to the page component in the near future. I'll leave this issue open and update it once we have something to show.

**Comment by dansundy** [comment]
I'm looking for this functionality too. Is there a workaround in the meantime?

**Comment by tmlayton** [comment]
Hi @macs91 and @dansundy apologies for the delay in getting back to this issue. A dropdown is possible using the `actionsGroups` prop which then gets delegated to `type: dropdown` when using `Page` within an embedded app.

We will be sure to update the docs so this is clear.

```jsx
<Page
  title="Products"
  actionGroups={[
    {
      title: 'Promote',
      actions: [
        {content: 'Share on Facebook', onAction: this.performFacebookShare},
      ],
    },
  ]}
>
  <p>Page content</p>
</Page>
```
