### ISSUE TITLE
[Enablement] Polaris team alignment on support processes

### ISSUE THREAD

**Issue by selenehinkley** [Shopify/polaris-react-archive#6122]
The @enablement blobby communicates and implements our support processes for the Polaris team so that responsibilities are more equally distributed and folks are clear where requests are coming from.

See the draft of the [team guide](https://docs.google.com/document/d/1_IPEZU3wTosd0UxbX_QLP-PNAI3_XCzCJPIvp09Rf44/edit#)

**Comment by chloerice** [comment]
New support rotation and guidance shipped 🚀 We now have a daily support duo of one UXer and one Developer who facilitate the #polaris Slack channel and triage in GitHub as needed. Automation iteration to operationalize support is our next step.
