### ISSUE TITLE
[Polaris website refresh] UX Review

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#6139]
Please create new issues that come out of the website review:
* tagged with `#gsd:25820`
* tagged with `Blocking public launch` if it is a blocker
* If your issue needs further discussion with the team, drop a link to the issue in the website project channel and `@` the appropriate folks to start a thread

**Comment by martenbjork** [comment]
Thanks everyone for coming to the UX review 😍 Yuraima has converted all comments into separate issues so we'll track them there.
