### ISSUE TITLE
document "EmptySearchResult"

### ISSUE THREAD

**Issue by jared-fanning** [Shopify/polaris-react-archive#6144]
## Issue summary

We should provide documentation and best practice guidance for this component.

![image](https://user-images.githubusercontent.com/57542435/173890893-e3f677dc-9779-4b8d-92a8-6bfe2975e797.png)

From @chloerice :

> We have an undocumented `EmptySearchResult` component that should document best practices for this.
> These all implement the correct pattern of telling merchants their search query (which should be referenced directly or categorically in the content rendered depending on the context) did not return any results, and instructing them what to do about it. Icons in these contexts are optional and generally only used to fill the massive space in larger content containers, like `IndexTable` or `Modal`.
> 
> 
> Searchable components also (should) include examples for when no result is found, for example `Autocomplete` and `Filters`.
> 
> 
> If I were to write some best practices for empty search results, they'd include:
> 
> - Reference the merchant's search query directly
> -- Do: No orders found tagged with "X", No tags found matching "Y"
> -- Don't: No results found
> - Offer merchants an action to take to move forward in the job to be done
> -- Do: Clear search query, Clear filters
> -- Don't: Try changing the search term)
> - Link to relevant documentation or resources merchants would benefit from if the search spans multiple features or contexts

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by MurmeltierS** [comment]
just stumbled over the `EmptySearchResult`, as it is used in the empty state example of `IndexTable`.
