### ISSUE TITLE
[Polaris website reboot] Make Top nav collapse at a smaller breakpoint

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#6154]
The top nav is collapsing at around `1400px` right now

I would expect the nav to stay open until at least `768px` and smaller.

![Image](https://user-images.githubusercontent.com/8629173/173933917-72f61cec-dca6-41cc-bab7-a92ff5fc2d2e.png)

**Comment by alex-page** [comment]
Adding blocking public launch and to "This week". This is a frustrating UX and causes the mobile menu to show way too early making the experience poor on desktop.
