### ISSUE TITLE
[Polaris website reboot] Fix large images from overflowing

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#6156]
Large images are causing side scrolling because of overflow. This is happening on multiple pages with large images:
- Home
- Getting started

![large-images](https://user-images.githubusercontent.com/8629173/173935250-4bdd9819-c207-4f88-8011-28fda3a5945a.gif)

**Comment by martenbjork** [comment]
Thanks! Closing in favour of #6233
