### ISSUE TITLE
[Polaris website reboot] Make tokens page nav responsive

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#6161]
![tokens-nav](https://user-images.githubusercontent.com/8629173/173940770-d3b8daa6-6d50-4905-9649-b1f858947255.gif)

**Comment by martenbjork** [comment]
It's not _art_, but good enough for now!

![Image](https://user-images.githubusercontent.com/875708/174398224-c4932ee3-334a-4f2a-8155-8f9109cb5374.png)

![Image](https://user-images.githubusercontent.com/875708/174398232-acbb825a-7952-49f4-b6b1-430045af7215.png)
