### ISSUE TITLE
[Polaris website reboot] Tokens table becomes hard to use below 1200px

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#6163]
Below 1200px the tokens table becomes hard to use due to:
- Content gets truncated / cut off
- Clipboard icons scale down in size

<img width="1065" alt="Screen Shot 2022-06-15 at 3 14 05 PM" src="https://user-images.githubusercontent.com/8629173/173941283-994a3af1-7c80-47fc-89e8-136a64a9dcb6.png">

<img width="627" alt="image" src="https://user-images.githubusercontent.com/8629173/173941063-edded4ef-699d-4561-9f44-a1206eb338ed.png">

**Comment by martenbjork** [comment]
![Image](https://user-images.githubusercontent.com/875708/174398599-8bf2d362-f927-419e-ac74-0dd589faaa61.png)

![Image](https://user-images.githubusercontent.com/875708/174398600-db53b4e4-b867-4603-b392-7dcf1e7a820a.png)

**Comment by sarahill** [comment]
OOO that looks so nice!
