### ISSUE TITLE
Make sure all App, App Bridge, and old content should be removed

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#6166]
* Search for the words “App bridge” and “app” to double check all the content
* rip out old mobile content
* Find all the links we references to all of this

**Comment by alex-page** [comment]
I am going to do this for the current site. If this can be easily copied across or if the new site can mimic it that would be ace. I'll tag this issue with the work.

**Comment by alex-page** [comment]
PR's good to go if `polaris-styleguide` needs updates
- [x] https://github.com/Shopify/polaris-styleguide/pull/5920
- [x] https://github.com/Shopify/polaris-styleguide/pull/5919
