### ISSUE TITLE
Sidebar navigation order fix

### ISSUE THREAD

**Issue by sampede** [Shopify/polaris-react-archive#6241]
## Issue summary
In our Polaris Components Library in Figma, the wrong navigation order is being displayed under the Product's section. 

## Expected behavior

 
<img width="240" alt="As shown in production" src="https://user-images.githubusercontent.com/68703584/174362003-3c11aaad-9f15-4252-b102-3c2ad93ead54.png">

## Actual behavior

<img width="403" alt="As shown in Polaris Component Libary in Figma" src="https://user-images.githubusercontent.com/68703584/174359634-1edf618a-b829-477d-8c52-263762de874a.png">

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by heyjoethomas** [comment]
Fix has been shipped
