### ISSUE TITLE
Add new "Active" status icon

### ISSUE THREAD

**Issue by brandonlawshop** [Shopify/polaris-react-archive#6250]
## "Active" status icon
Statuses are being used across multiple resources (e.g., price lists, products) but the current “active” status icon is designed for ‘products’ specifically. This icon is designed to be used by any resource that utilizes an "active" status.

This will help make it easier for merchants to associate the concept of setting a resource to "active" with a single icon as opposed to multiple variations, and create consistency in how the status is being represented.

<img width="463" alt="Screen Shot 2022-06-20 at 1 59 25 PM" src="https://user-images.githubusercontent.com/105386521/174656754-a61746c3-0c83-46cf-9982-7ade81b51b1f.png">

### Setting multiple price lists as "active" through bulk actions menu on price list index
A merchant bulk selects multiple price lists, taps "More actions" to bring up the bulk actions menu and can set the selected price lists to "active."
<img width="608" alt="Screen Shot 2022-06-20 at 11 49 46 AM" src="https://user-images.githubusercontent.com/105386521/174639029-2bbd2ada-8b83-4142-b0f7-a27974737b56.png">

### Setting an individual price list as "active" through status sheet in price list details page
A merchant brings up the status sheet of a price list on the details page and can set it as "active." 
<img width="574" alt="Screen Shot 2022-06-20 at 11 56 56 AM" src="https://user-images.githubusercontent.com/105386521/174640267-c7f1b9d9-4698-419d-9760-f5af01553c19.png">

## Related components

- In the examples above, the icon is paired with the current [Polaris "Compose" icon](https://polaris-icons.shopify.com/?icon=ComposeMajor&q=com) to indicate a "Draft" status.

## Links

- Figma Branch: https://www.figma.com/file/mMHFt3kEDNjLMZWowi6gnt/branch/CCao4x3o8AzbSKzsVAxuak/Polaris-Icons?node-id=6630%3A333
- SVG attached to the issue.

![status-active_major](https://user-images.githubusercontent.com/105386521/174648676-926926cb-550f-4696-9070-129194bcb3e7.svg)

**Comment by heyjoethomas** [comment]
Hey @brandonlawshop This looks really good from a design perspective. Thanks for following the specs and process. Feel free to export and open a PR to get this into the system. Reach out if you have any questions.
