### ISSUE TITLE
ResourceList shortcut actions more than one show at a time

### ISSUE THREAD

**Issue by alexdover** [Shopify/polaris-react-archive#6253]
## Issue summary

When using the ResourceList component and adding shortcut actions to each item, when these are collapsed down on smaller screens to the three dots it is possible to click on each one and they end up overlapping because any other open actions are not closed. Would it make sense to close other open action lists before opening the new one?

## Expected behavior

When clicking the dots to show the shortcut actions, any other open ones should be close.

## Actual behavior

When clicking on the dots to show shortcut actions, they can end up overlapping, as shown below:

![image](https://user-images.githubusercontent.com/1886367/174823740-21c744a2-2013-409e-9266-d80bb318f1f9.png)

Many thanks....

**Comment by szebert** [comment]
This bug is still ongoing for "@shopify/polaris": "^10.46.0"
