### ISSUE TITLE
Stepper example doesn't render in Chrome

### ISSUE THREAD

**Issue by jzazove** [Shopify/polaris-react-archive#6275]
## Issue summary
Stepper examples do not render in Chrome 

![21-03-gg2j5-38rpk](https://user-images.githubusercontent.com/588907/174910876-3afad3f7-54c1-44bc-b0b6-2e6ab416e9d0.png)

## Expected behavior
A stepper would render

## Actual behavior
the words "example tk" show up

## Steps to reproduce the problem
1. visit https://secretpolaris.shopifycloud.com/components/stepper

**Comment by BPScott** [comment]
Some components are Android and iOS only, they don't have equivalents in web polaris and thus have no web examples. Stepper is one of these - https://polaris.shopify.com/components/forms/stepper // https://github.com/Shopify/polaris/tree/main/polaris-react/src/components/Stepper

It looks like you're omiting the Android/iOS examples from other stuff so perhaps Stepper should be omitted too?
