### ISSUE TITLE
Form component page does not render

### ISSUE THREAD

**Issue by jzazove** [Shopify/polaris-react-archive#6276]
## Issue summary
Form component page does not render

## Actual behavior
Page throws an error
![21-06-51fiq-nnxi2](https://user-images.githubusercontent.com/588907/174911122-cb984cec-7357-4ba5-9534-c107438c1f78.png)

![21-07-q8vfq-r0g4p](https://user-images.githubusercontent.com/588907/174911176-a9b037bc-e496-41e4-bc38-b0a99147e313.png)

## Steps to reproduce the problem

1. visit https://secretpolaris.shopifycloud.com/components/form

**Comment by gui-santos** [comment]
I think this has been fixed by some other change



![Image](https://user-images.githubusercontent.com/6597467/175026139-644f6b36-95fc-4e30-8392-d4780ab91c82.png)
