### ISSUE TITLE
[Polaris website reboot] Update homepage copy

### ISSUE THREAD

**Issue by selenehinkley** [Shopify/polaris-react-archive#6288]
The homepage could use a more in-depth content design lens. For the launch, here's some quick-ish improvements:

**More than a UI kit.**
Polaris unifies 1,000+ people designing and building merchant experiences, so that our product feels like it’s made by one person.

 **Explore the foundations**
Our design foundations provide fundamental design elements and guidance for creating good merchant experiences.

**Components**
Components are reusable building blocks made of interface elements and styles. Piece them together, improve them, and create new ones when creating solutions for merchant problems.

**Tokens**
Tokens are repeatable design elements that can be combined creatively. Use them to unite our design decisions across merchant experiences.

**Icons**
The Polaris icon library has 400+ carefully designed icons for commerce and entrepreneurship. Use them as visual aids to help merchants complete their tasks.

FYI @yesenia-perezcruz 👀

**Comment by alex-page** [comment]
I love the components, foundations and icon adjustments you suggested @selenehinkley. I made a [PR](https://github.com/Shopify/polaris/pull/6292/files) with all of your suggestions but want to chat about some of the content.

> **More than a UI kit.**
> Polaris unifies 1,000+ people designing and building merchant experiences, so that our product feels like it’s designed by one person.

This is the first thing users will read coming to our site. Referencing a "UI Kit" then saying we are more than that feels a bit odd to me. I would expect this title and sentence to explain our unique value that we add to Shopify and it's builders. Saying "More than a UI Kit" to me doesn't get that across. I am also not a fan of putting a number on the total people building merchant experiences. That should be growing rapidly and honestly 1000 sounds quite low for a design system at Shopify scale.

> Tokens
> Tokens are repeatable design elements that can be combined creatively. Use them to unite our design decisions across merchant experiences.

I like the "unite our design decisions across merchant experiences" but the "Use them" kind of throws me off. Who uses the tokens? Are we telling people to use them?

**Comment by selenehinkley** [comment]
Great feedback! 

For the intro, let's leave it as is and we can always revisit down the road. I see that Marten updated the subcopy to the shorter version already so that's good.

For the Tokens piece, let's update it to either of these:

Option 1:
> Tokens
> Tokens are repeatable design elements that can be combined creatively. They unite our design decisions across merchant experiences.

Option 2:
> Tokens
> Tokens are repeatable design elements that can be combined creatively. They’re built-in to unite our design decisions across merchant experiences.

**I'll go into the PR and make comments and suggested edits :)**

**Comment by yesenia-perezcruz** [comment]
+1 on updating the components, foundations and icons copy before launch. Especially components because it talks about app-building. Ok to revisit the headline after launch.

**Comment by alex-page** [comment]
Reopening the issue until we update the home page headline is updated.

**Comment by dominikwilkowski** [comment]
Hey folks. I would love to see the headline of the homepage convey more context around the Admin. It's one of the most common things people are confused about.

> A starter kit for reimagining commerce.

that feels very broad and does little to fix that confusion. Polaris is only for the Admin and the Admin is huge. I don't know what it should be because there are other people much better than me when it comes to content but something along the lines of:

> The Design System for Shopifys admin

Too direct? It's just a suggestion ;)

**Comment by selenehinkley** [comment]
I don't think the core message is too direct. It's transparent would quickly solve the problem we're experiencing (app dev confusion). Like all web, we can evolve it over time if we want to change our message. Wording ideas:

### **A starter kit for Shopifolk working on admin**
_Our design system helps us work together to create a great merchant experience_

Rationale: The first sentence addresses who and what Polaris is for, concisely. The subcopy stays the same because it expands on starter kit being the design system and adds our purpose: the impact on merchants.
Normally I'm not a fan of using internal language, externally. But! Our primary audience is Shopifolk, and even if you don’t work at shopify, understanding the play on words is intuitive: Shopify-folks. It may cause pause at first, but our primary audience will feel like the system is really for them and 3p devs will have this card to address their needs (although it will be at the bottom of the homepage):

![PXL_20220624_164927340](https://user-images.githubusercontent.com/18617698/175609921-759ffa37-713f-4d35-8d46-af7e0b674774.jpg)

The stick man represents a pixel person from .dev to visually make the connection to that site. The button connects us the the dev mode we see on editions. By using those cross-experience design elements we make our cross-product experiences feel more unified (that's the hope, anyway).

---
If we want to go the more upfront route, we can use @dominikwilkowski's copy, but I'd make these tweaks:

### The design system for Shopify’s Admin
_Polaris helps us work together to create a great merchant experience_

or

### Shopify's design system for the merchant admin
_Polaris helps us work together to create a great merchant experience_

or

### Polaris
_Shopify’s admin design system for making a great merchant experience_

**Comment by yesenia-perezcruz** [comment]
**The design system for Shopify’s Admin**
Polaris helps us work together to create a great merchant experience

I like this one, but the "helps us work together" feels a bit odd, even though we have that now.

Subhead Ideas:
Design and build great merchant experiences with Polaris
Polaris provides the building blocks for great merchant experiences

**Polaris**
Shopify’s admin design system for making a great merchant experience

I like this one too.

**Comment by selenehinkley** [comment]
Presented these options at a UX Cafe and we combined the elements we liked into this:

**Shopify’s admin design system**
Polaris provides the building blocks for great merchant experiences

Here's a mock:

<img width="1210" alt="Screen Shot 2022-06-27 at 1 25 23 PM" src="https://user-images.githubusercontent.com/18617698/176007727-36017653-850f-4754-b744-bfa94988c066.png">

**Comment by dominikwilkowski** [comment]
Great work.

> Shopify’s admin design system
> Polaris provides the building blocks for great merchant experiences

That sounds good to me

**Comment by yesenia-perezcruz** [comment]
Sounds great :shipit:

**Comment by martenbjork** [comment]
I think "Shopify's admin design system" is a pile of words and a bit confusing. It sounds a bit overthought and written by committee.

My first question would be "what's an _admin design system_?". Similarly, "Volvo's _car design system_" or "Coca Cola's _can design system_" would be confusing. I would opt for a syntax based like "Shopify's design system for...".

Regardless, the stuff in this thread looks good! We shouldn't just shoehorn this into the existing front page — we should make a small overhaul of the front page based on this input (and some other ideas). Tracking that work here: https://github.com/Shopify/polaris/issues/6416

**Comment by selenehinkley** [comment]
Thanks for the fresh eyes feedback! We could pivot quickly and ship this (it's longer, but maybe we could make a type size change as a trade off for clearer wording):

Shopify's design system for the merchant admin 
Polaris provides the building blocks for great merchant experiences

I was hoping this copy could be shipped quickly (I could make a PR today), unless [6416](https://github.com/Shopify/polaris/issues/6416) is going to be turned around quickly? It would better serve our 3p dev audience to have a piece of context when they land on the site since they're dealing with more change than usual right now (the launch of the app design guidelines plus this site redesign).

**Comment by alex-page** [comment]
@selenehinkley I don't think we should rush this. The homepage needs some time to come together and I haven't read any negative feedback or confusion from the 3p dev audience. If there is any context you can share that would explain the urgency that would help?

A solution that thinks about the whole home page could make this much much better. Thinking about:
- [ ] What call to actions should be on the home page? What is missing?
- [ ] What is the first thing a user of Polaris should see and read?
- [ ] What is the first button they should click on? Where does it go?
- [ ] How do we make it clear who Polaris is built for? What it does?

This doesn't need to take a long time, it could be 1 week away. I am confident that @martenbjork and @yurm04 can take the feedback, wireframes and ideation in this issue into account and ship a truely great homepage.

**Comment by selenehinkley** [comment]
I'm all for thoughtful content design going into the homepage, which is the ideal process. I was interpreting that there was more urgency with this group based on the re-opening of this issue and Slack posts from the past couple days about devs asking if Polaris was required anymore (I think it was from the dev discord). Stoked that @martenbjork and @yurm04 are on it! Pull me in when you want to connect brains on anything! :D

**Comment by alex-page** [comment]
Thanks! Lets go for thoughtful.

> devs asking if Polaris was required anymore

Home page copy can definitely help but I see this as a bigger problem then the first sentence read on polaris.shopify.com. I think we should be intentional with the copy but solving specific problems like this is challenging as it's more then a sentence on a website.

**Comment by selenehinkley** [comment]
Absolutely! 🙌🏻

**Comment by dominikwilkowski** [comment]
I like this

> **Shopify's design system for the merchant admin**
> Polaris provides the building blocks for great merchant experiences

the problem I'm trying to solve here is the confusion that _not just 3P devs have_ around what Polaris is for. I would like us to take pride in the product we're working for and lift it up. We are working for THE merchant admin. Let's make sure everyone is clear what the admin is, 3P and 1P. The word-smithing I leave to you fine folk :)

**Comment by selenehinkley** [comment]
@dominikwilkowski, here's the new iteration. @jjgali and I aimed to explain what people can do with the system while sharing the importance of evolving it (the "why" behind contributing). We want to clarify that Polaris is for the merchant admin, but use plain language that people unfamiliar with all of our product offerings would understand.

**Build. Contribute. Evolve.**
Shape the merchant experience for Shopify’s core product, the admin.

**Comment by dominikwilkowski** [comment]
Looks perfect! Great work both!

**Comment by martenbjork** [comment]
I'm happy to ship this!

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/875708/180413030-8b5fb56f-901f-45f8-9917-e30ddcc99024.png">

The HomePage remains a confused mess that we will redesign, but for now, we should ship this if it helps our messaging.

**Comment by martenbjork** [comment]
I'm gonna close this since we have delivered what the issue says. Thanks everyone for the good discussion and final result! 🏅 

We'll keep on iterating on the copy and the home page over the coming weeks 🚀
