### ISSUE TITLE
Make heading capitalization consistent on the Polaris site

### ISSUE THREAD

**Issue by christopherclunas** [Shopify/polaris-react-archive#63]
# Issue summary

Within the Polaris guide, the advice is to "Use sentence case for all headings" (https://polaris.shopify.com/content/grammar-and-mechanics#capitalization).  However, the guide itself varies in using Init Caps and Sentence case.

## Expected behavior

All headings would use sentence case.

## Actual behavior

Mix of headings styles.  For example, the Colors section uses Init Cap style:

![image](https://cloud.githubusercontent.com/assets/24234712/26409441/9686ac94-406e-11e7-9a71-a9c98cfda0e6.png)

## Steps to Reproduce the Problem

No steps required.

## Specifications

- Polaris version: Whatever is live today.
- React version:
- Browser:
- Device:
- Operating System:

**Comment by christopherclunas** [comment]
The Colors section might be the only section that this applies to!

**Comment by allylane** [comment]
Thanks for this @christopherclunas. The rules documented only apply to the product and not to the documentation itself so I'm going to close this. Thanks for raising issues though!

**Comment by christopherclunas** [comment]
Hmmm, the intro to the section ("Grammar and mechanics"), says:

> This guide is to help designers, developers, recruiters, UX-ers, product managers, gurus—anyone who writes public-facing text for Shopify.

So it doesn't seem to be directed solely at the product interface.

**Comment by christopherclunas** [comment]
Moved to Shopify/polaris-styleguide
