### ISSUE TITLE
Popover not correctly calculating height when browser zoom is applied

### ISSUE THREAD

**Issue by MitchLillie** [Shopify/polaris-react-archive#6317]
## Issue summary

In the Web Admin, a Popover containing an Action List is not correctly calculating its height (or possibly its width as well). cc @nickpresta 

## Expected behavior

Either the line should not break or the height should be set correctly to contain the entire action item.

## Actual behavior

"About this app" is cut off, and a scrollbar is shown:

<img width="958" alt="Screen Shot 2022-06-22 at 12 28 15 PM" src="https://user-images.githubusercontent.com/5873610/175120390-fe192097-040b-4711-91c0-8f4e97e14f19.png">

## Steps to reproduce the problem

1. Zoom in one level on your browser, to 110%.
2. Set screen width to 870px (Note: You must do this directly in the browser window. Do not set the width via Chrome's device toolbar, as this will not respect the zoom level.)
3. Open any app in the admin, at `/admin/apps/foo`. 
4. Click on the horizontal dots button in the upper right corner of the page.

## Reduced test case

Visit https://bqrnvl.csb.app/ which is just a slightly modified version of the doc site. Zoom your browser to 150% and set your browser's width to 760px (though other widths also trigger it).

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 9.15.0
- Browser: Chrome Version 102.0.5005.115 (Official Build) (arm64)
- Device: MacBook Pro
- Operating System: 12.4

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).
