### ISSUE TITLE
Content pages like punctuation are not showing in search

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#6339]
Pages and their sections for Content aren't surfacing in search. Grammar and mechanics is an area where people struggled to find what they needed in the old site. It'd be a great improvement if this particular page was more searchable. 

There are some phrases and terms, like `tips` that will be less useful to surface. I screenshotted some and highlighted some examples of terms/phrases that would be important to surface compared to others—not sure how this new search works and if it's smarter or if we have to program these in. Happy to help with any metadata strategy that's needed!

FYI @jjgali & @martenbjork :)

<img width="236" alt="accessible content" src="https://user-images.githubusercontent.com/18617698/175341545-ab3aeea2-a5a5-4094-b49b-8d5e6feecd5b.png">
<img width="236" alt="actionable lang" src="https://user-images.githubusercontent.com/18617698/175341550-bc44005b-1456-4995-964e-570e8209c19a.png">
<img width="201" alt="alt text" src="https://user-images.githubusercontent.com/18617698/175341552-d2e2dabe-36fb-452b-87a4-1138e691e211.png">
<img width="234" alt="grammar" src="https://user-images.githubusercontent.com/18617698/175341554-c48c0e27-8bc3-4a46-b844-5b237fd09eb7.png">
<img width="243" alt="naming" src="https://user-images.githubusercontent.com/18617698/175341556-38bff55b-092e-459c-80dd-d2b6515bb39b.png">
<img width="192" alt="product content" src="https://user-images.githubusercontent.com/18617698/175341559-d9687106-6f5f-4c37-beeb-41d317667217.png">

**Comment by selenehinkley** [comment]
A snapshot of feedback from the survey related to this issue:
<img width="804" alt="Screen Shot 2022-07-18 at 12 39 32 PM" src="https://user-images.githubusercontent.com/18617698/179603750-4ec83cfd-8699-4d2f-be7c-9ce85b9cbb4f.png">

**Comment by martenbjork** [comment]
Thanks! 

- We're shipping improvements to the search this week. I have a PR lined up which finds content inside articles as well: https://github.com/Shopify/polaris/pull/6515
- Vocabulary: I connected with @deannatron and @LauraDiTullio today and we had a great conversation about potentially surfacing vocabulary on the Polaris site down the road.

After shipping this first iteration of the improved search, please keep sharing more feedback. This search should be amazing for everyone, regardless of discipline.

**Comment by selenehinkley** [comment]
Adding further community feedback to this issue to see if pages like grammar and mechanics can offer a more detailed search. Screenshots from #content-design-shh:

User 1: I'm having trouble finding this in polaris... do we say US or U.S.?

User 2: Here’s the Polaris link
[https://polaris.shopify.com/foundations/content/grammar-and-mechanics#:~:text=the%20placeholder%20text-,Cou[…]te%20names,-Use%20a%20nation%E2%80%99s](https://polaris.shopify.com/foundations/content/grammar-and-mechanics#:~:text=the%20placeholder%20text-,Country%2C%20province%2C%20and%20state%20names,-Use%20a%20nation%E2%80%99s)

User 1: THANK YOU! search in polaris has me :sob:
