### ISSUE TITLE
[polaris.shopify.com] Feedback (on page /components/index-table)

### ISSUE THREAD

**Issue by awd** [Shopify/polaris-react-archive#6341]
Please include HTML markup along side of the React component markup on new site.

Thx!!

**Comment by martenbjork** [comment]
Done! 😋 https://polaris.shopify.com/components/badge

<img width="722" alt="image" src="https://user-images.githubusercontent.com/875708/180400092-27ffc858-6f6c-4bf9-9d45-3de154901b44.png">
