### ISSUE TITLE
[Polaris website refresh] Feedback popup won't close

### ISSUE THREAD

**Issue by selenehinkley** [Shopify/polaris-react-archive#6342]
https://user-images.githubusercontent.com/18617698/175338512-42974030-324f-4615-9fcc-40f77f6864a6.mp4

**Comment by martenbjork** [comment]
Thanks! Just fixed in https://github.com/Shopify/polaris/pull/6340 😊

**Comment by selenehinkley** [comment]
Fixed! 🎉 https://github.com/Shopify/polaris/pull/6340
