### ISSUE TITLE
[Enablement] Add a "What is quality" section to the guidelines

### ISSUE THREAD

**Issue by selenehinkley** [Shopify/polaris-react-archive#6346]
This is a tricky one that many teams have tried to answer. Below is a sample of the resources I've found after a quick search. How can our team make a concise list or checklist of things for teams to consider when making a contribution.

Scope: should we scope this to quality for product or a contribution. Same same but different?
 
- [driving quality through feedback (Vault)](https://vault.shopify.io/pages/10116-Driving-alignment-and-design-quality-through-a-collaborative-transparent-feedback-process)
- [Improving experience quality (SFN google doc)](https://docs.google.com/document/d/1-FEljNDgj2VQG--PQmTr3y4uHOpBad2UUOduRi338uc/edit
- [Admin content quality checklist (google doc)](https://docs.google.com/document/d/1n5-l7Dtv8l-cwt8LPV7AArKXsRLHCeOuVhBH5ca_EhY/edit#heading=h.mcqqddgkeuwp)
- A mental model the Admin Quality team uses:
![Screen Shot 2022-06-13 at 5 18 55 PM](https://user-images.githubusercontent.com/18617698/175350487-e4d46885-ecfb-4396-8d06-d4312b823484.png)
- [Admin quality team emerging beliefs (google doc)](https://docs.google.com/document/d/1OoutHIQk_OAuyZ2LhKwPXrzmE01DTPQFZ7Wf6qMXCuk/edit#heading=h.ms90xoreobag)
- [UX and product principles (Vault)](https://vault.shopify.io/pages/14884-UX-Principles-and-Values)

**Comment by chloerice** [comment]
Shipped in https://github.com/Shopify/polaris/pull/6841
