### ISSUE TITLE
[Enablement] Improve the documentation contribution experience

### ISSUE THREAD

**Issue by selenehinkley** [Shopify/polaris-react-archive#6347]
From having to hand hold contributors or ship documentation for them, to creating educational materials around how to use github, our team is no stranger to the challenges with our current contribution process and tooling. The hope is we can find a tooling solution, maybe or maybe not a CMS, to reduce the friction to adding fresh ux guidance to the Polaris site. If we want to keep Polaris in sync with the UX knowledge that is surfacing while crafters improve merchant experiences, we need to reduce this barrier to contribution. For dramatic effect, here's a recent screenshot of how a new content designer feels about Github:

<img width="618" alt="Screen Shot 2022-06-23 at 9 59 50 AM" src="https://user-images.githubusercontent.com/18617698/175354246-fad16320-9444-41aa-9baf-5e097135874a.png">

This work may look into the need for **internal vs external views** on the Polaris site.

Some (not an extensive list) of training resources we've made in the past to help contributors add content to the Polaris site:
- [Git for content designers](https://vault.shopify.io/pages/6628-Git-for-content-designers) (Vault) and [slide deck](https://docs.google.com/presentation/d/1OBp4fnSwnz8PCmf3UlqnrRpGHYXIfHaxk22KXWVLgy8/edit#slide=id.g5149ff7251_0_0)
- Original [How to ship style guide changes](https://docs.google.com/presentation/d/117oXIF-ZQJvHdqAXK6r7hL0sw11ml8ZxiS-7HnqP7fU/edit#slide=id.g229d4be039_0_76) deck
- [Git 101, a non-developers story](https://docs.google.com/presentation/d/1tyc5DdlVqTDrYMbY3MszwoeJTgutzDhx7Yu2ohgLBek/edit#slide=id.p)

FYI @gui-santos :) tagged you to keep you in the loop in case there's an opportunity to collaborate on anything CMS related

**Comment by martenbjork** [comment]
+100 on this. Excited to improve this process soon!

**Comment by gui-santos** [comment]
Hey @selenehinkley 

Thanks for tagging me! I'm a big fan of using CMS for this
In my experience, having a WYSIWYG editor makes contributing easier for non-developers
There is some effort to setup of course, but IMO it pays off in the long term when you get more people from different fields writing content for your docs

Feel free to ping me any time 😄
