### ISSUE TITLE
[Enablement] Map out our editorial workflow

### ISSUE THREAD

**Issue by selenehinkley** [Shopify/polaris-react-archive#6351]
For us to keep the Polaris site fresh with emerging UX knowledge, we first need to map out our editorial workflow. Once we have a clear picture of how knowledge emerges, is identified, consolidated, and shared, then we can map out a best case scenario for how to get this content into the Polaris site (with little friction). There may be opportunity to build a case for an editorial content creator to live with UX Ops to help us identify, structure, draft, and find a home for different types of UX knowledge (foundational, vs admin-specific, vs blog worthy).

This work may look into the need for internal vs external views on the Polaris site.

This work connects closely with the [Improve the documentation contribution experience](https://github.com/Shopify/polaris/issues/6347) and [patterns definition and organization](https://github.com/Shopify/polaris/issues/6032) work.

FYI @martenbjork @jjgali @jared-fanning

**Comment by tracytees** [comment]
### "Acceptance Criteria"

1. Visually map out the current scenarios the team encounters 
2. Include timeline in the map if applicable
3. Create an "ideal world" map that includes potentials for automation, documentation, or guidance
4. Make note of the opportunities and potential issues we might face with the ideal world + current day

Everything comes back to "this is a learning opportunity" and so how to we make it as painless as possible for teams to contribute and flag issues?

**Comment by tracytees** [comment]
[Version 1 complete](https://www.figma.com/file/pu87pk9l8e0SxhNJQa2Hua/Customer-Service-Journey?node-id=488%3A13553) and awaiting feedback. Includes:

- Journey maps of previous conversations, resolutions, pain points, and opportunities
- Ideal process 
- Slackbot automation response decision tree
