### ISSUE TITLE
ResourceList not updating after data change

### ISSUE THREAD

**Issue by raphaelghub** [Shopify/polaris-react-archive#6359]
## Issue summary

Noticed a weird bug related to the ResourceList component. When the user selects an item in the list and pages to a new set of items, the data is update but the list doesn't get updated. 

Video demonstrating what is happening. 
https://screenshot.click/21-20-qm0jz-2efua.mp4

## Expected behavior
When an item is selected in the list and the user pages to a different set of items, the list should show only the new set of data not the data from the previous set. 

## Steps to reproduce the problem
https://codesandbox.io/s/shy-architecture-hrnodx?file=/App.js
1. Select an item in the list 
2. Page to the next list of items
3. You should notice that only the item at the index of the selected one on the previous page is updated
4. Clicking an item on the updated page then updates the item 

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number: 9.18.0
- Browser: Chrome
- Device: M1
- Operating System: Montery 12.4

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
      System:
    OS: Linux 5.10 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (32) x64 Intel(R) Xeon(R) CPU @ 2.80GHz
    Memory: 34.59 GB / 125.90 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
```

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by ndinhbang** [comment]
@raphaelghub add **key** prop to ResourceItem component should resolve your problem

```
function renderItem(item, _, index) {
    const { id, url, name, location } = item;
    const media = <Avatar customer size="medium" name={name} />;

    return (
      <ResourceItem
        id={id}
        key={id}
        url={url}
        media={media}
        sortOrder={index}
        accessibilityLabel={`View details for ${name}`}
      >
        <h3>
          <TextStyle variation="strong">{name}</TextStyle>
        </h3>
        <div>{location}</div>
      </ResourceItem>
    );
  }
```

**Comment by nandasiepi** [comment]
Hi team, is the above enough to solve the behaviour? I can still see it on merchant admin. 

Is there any timeline of when will this be tackled?
