### ISSUE TITLE
Using the keyboard to navigate search results doesn't work well

### ISSUE THREAD

**Issue by lemonmade** [Shopify/polaris-react-archive#6361]
## Issue summary

When using the search field on the new documentation website, attempting to use the keyboard to navigate search results yields some... interesting results:

- You can get into situations where the overlay does not scroll to reveal your active selection
- Pressing enter on a result does not dismiss the search overlay
- The tab key and left/ right keys did not do what I expected them to (both were not really used to navigate the search; to be fair, this may be expected behavior for more seasoned keyboard users, I really don't know)

Video showing these issues in action:

https://user-images.githubusercontent.com/3012583/175384254-9987f8fe-6a34-45c4-b54f-02a5268f1dc4.mov

**Comment by martenbjork** [comment]
Thanks @lemonmade! Will keep on improving this.

> You can get into situations where the overlay does not scroll to reveal your active selection

We're using a simple `scrollIntoView` call right now. Might have to update the logic for that... (maybe throttle the keydown events... 🤔)

> Pressing enter on a result does not dismiss the search overlay

I can't reproduce the error. Just to double check, are you using Chrome?

> The tab key and left/ right keys did not do what I expected them

Were you expecting them to map to the visual layout? As in: If an element is visually to the right, the right key should take me there. I'd love to add that!

**Comment by lemonmade** [comment]
> I can't reproduce the error. Just to double check, are you using Chrome?

Yeah, I am using Chrome 102. Could not reproduce in Safari or Firefox.
