### ISSUE TITLE
polaris.shopify.com/icons Desktop and mobile both start with no icon selected

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#6362]
There is a bunch of state where we have to check if it is the initial load and if anything is selected. This should probably just be simplified to encourage a user to select an icon or by default select an icon for them.

**Comment by martenbjork** [comment]
The challenge here is that...

1. On desktop we do select an icon for them
2. On mobile, that would mean showing the modal on first page load

Hence, some additional logic. Happy to revisit and clean up though! 🙌
