### ISSUE TITLE
[polaris.shopify.com] Feedback (on page /)

### ISSUE THREAD

**Issue by SomeBrujah** [Shopify/polaris-react-archive#6378]
Where is props in component?!

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by martenbjork** [comment]
We'll strongly consider adding it back! We've heard from a few folks that they want it to return. 🙌

**Comment by alex-page** [comment]
This is a duplicate of https://github.com/Shopify/polaris/issues/6371
