### ISSUE TITLE
[polaris.shopify.com] Code is not visible without clicking the Code tab

### ISSUE THREAD

**Issue by renerbaffa** [Shopify/polaris-react-archive#6381]
When checking the documentation of a component, in the old version, I could see both the code and the component preview at the same time:

<img width="880" alt="Screenshot 2022-06-24 at 11 56 51" src="https://user-images.githubusercontent.com/3033781/175512089-7a21c124-aa7e-4046-bcb4-9c5306a39393.png">

In this new version, I have to switch between the views, which makes me click around several times instead of having both info at the same time:

<img width="843" alt="Screenshot 2022-06-24 at 11 56 36" src="https://user-images.githubusercontent.com/3033781/175512290-c7dfd3e5-b947-4386-b613-ad1fc5b9d7f3.png">

I think that now it became a bit more painful to play around and understand props of the component
😕

**Comment by martenbjork** [comment]
Good call, I agree! I'll look into re-shuffling the layout 😊

**Comment by martenbjork** [comment]
Hi! The layout has now been improved to solve this 🤗

<img width="889" alt="image" src="https://user-images.githubusercontent.com/875708/180440428-c71b4e99-c25a-4c08-91df-959a30abaa02.png">

**Comment by renerbaffa** [comment]
It looks great, thanks @martenbjork!
