### ISSUE TITLE
[polaris.shopify.com] Feedback (on page /components/toast)

### ISSUE THREAD

**Issue by brokeyourbike** [Shopify/polaris-react-archive#6386]
Please include possible props like it was on the old website, this affects all components not just  `/components/toast`

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by alex-page** [comment]
Thanks @brokeyourbike. I am going to close this issue as it's a duplicate of https://github.com/Shopify/polaris/issues/6371
