### ISSUE TITLE
Grid example is squished

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#6390]
![175568153-3ec3b834-3e56-4d99-afbf-29cf10b1c8ab](https://user-images.githubusercontent.com/19199063/175571909-fb30f77b-56c1-4a63-b29d-b2e8afde0dc0.png)

**Comment by kyledurand** [comment]
Looks like the css needs to be rebuilt. I moved the Cell styles from Grid.scss to Cell.scss and the references in the styleguide are wrong. i.e. The component references `Polaris-Grid-Cell--cell_6ColumnXs` which looks correct to me, but in the css the class is actually `Polaris-Grid--grid_6ColumnMd` which would have been from the previous version of grid
