### ISSUE TITLE
[polaris.shopify.com] Feedback (on page /components/action-list)

### ISSUE THREAD

**Issue by kuipou** [Shopify/polaris-react-archive#6393]
It would be easier if we didn't have toggle between preview and code

**Comment by alex-page** [comment]
Thanks @kuipou. This is a duplicate of https://github.com/Shopify/polaris/issues/6397

**Comment by alex-page** [comment]
Moving this feedback to https://github.com/Shopify/polaris/issues/6381. Sorry!
