### ISSUE TITLE
[IndexTable] Broken in the Shopify app on Google Pixel devices

### ISSUE THREAD

**Issue by luke8086** [Shopify/polaris-react-archive#6402]
## Issue summary

We've noticed a weird rendering issue with the IndexTable component, which only affects the Shopify app on Google Pixel devices.  

Note we've also reported it to the Shopify partner support, and they pointed us here. The ticket id is #31202578

## Expected behavior

A normal table should be displayed with all the provided data. It does work correctly in all web browsers, and in the Shopify Android app on all devices we tested other than Google Pixel:

<details>
<summary>Screenshot</summary>
<img width="393" alt="Screenshot 2022-06-27 at 15 25 27" src="https://user-images.githubusercontent.com/55237178/175952659-82c389f8-5315-4e37-bb9b-e29d34dade4f.png">
</details>

## Actual behavior

In the Shopify app on Google Pixel, all the rows inside of IndexTable are displayed as if they were identical, and they randomly change while scrolling. You can see it on the following screencast, and a longer video on https://streamable.com/kazf07

<details>
  <summary>Screencast</summary>
  <img src="https://user-images.githubusercontent.com/55237178/175952387-6de69eec-8c30-4234-a69f-e9929c7b7e9c.gif" alt="Description of what the gif shows">
</details>

## Steps to reproduce the problem

Load the attached test case inside of the native Shopify app on Google Pixel devices

## Reduced test case

We've isolated the issue to the following code - https://gist.github.com/luke8086/6a6727fe4081cf8010643f23d1cf7b26

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number: 9.19
- Browser: Shopify Android v9.69, Android System WebView v101.0.4951.15
- Device: Google Pixel 6 Pro (a customer reported it on a real one, we're testing with a virtual one on app-live.browserstack.com)
- Operating System: Android 13

```bash
$ npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris
npx: installed 1 in 0.88s

  System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
    Memory: 1.43 GB / 7.76 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.22.12 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.16 - /usr/bin/npm
  npmPackages:
    @shopify/polaris: ^9.19.0 => 9.19.0 
    react: ^17.0.0 => 17.0.1 
    react-dom: ^17.0.0 => 17.0.1 
```

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).
