### ISSUE TITLE
[polaris.shopify.com] Toasts example is broken

### ISSUE THREAD

**Issue by cherrychau** [Shopify/polaris-react-archive#6406]
Toasts don't show when I click on "View toast" in the sandbox

**Comment by rajanlagah** [comment]
<img width="730" alt="Screenshot 2022-08-28 at 12 21 42 AM" src="https://user-images.githubusercontent.com/20952569/187044210-04c2c959-74bf-4869-89f3-266ec2f314e1.png">

It seems to be working @cherrychau. 
Can you check again?

**Comment by cherrychau** [comment]
@rajanlagah yes it works, thanks!
