### ISSUE TITLE
[polaris.shopify.com] Broken Tag example

### ISSUE THREAD

**Issue by st999999** [Shopify/polaris-react-archive#6408]
## Issue summary

On https://polaris.shopify.com/components/tag the "Removable tag" preview has (unintentional?) lorem ipsum that introduces a need for horizontal scrolling.

![image](https://user-images.githubusercontent.com/29904948/176002197-e235083d-86c7-4d08-b7c6-f50453694f40.png)

**Comment by chloerice** [comment]
Thanks for reporting this @st999999! Below is what the example should look like, the lorem ipsum helps illustrate that the tag can stretch to its parent's width and content that would go beyond is truncated.

<img width="770" alt="Screen Shot 2022-06-24 at 4 42 32 PM" src="https://user-images.githubusercontent.com/18447883/176008891-3e283978-d2ae-4861-8c06-e634db140f87.png">

There's a problem overall with the component example parent wrapper not having the right sizing and styles, so reports like this will help us know what to test when shipping a fix 🙏🏽
