### ISSUE TITLE
[Scrollable within a Modal]: Scrollable component "Refreshes" upon clicking <ResourceItem> within the scrollable pane

### ISSUE THREAD

**Issue by YauHei-Lam** [Shopify/polaris-react-archive#6410]
Hi, I found a bug with a the `Scrollable` component.
Here's the [CodeSandbox demo](https://codesandbox.io/s/elastic-matsumoto-18ohzd?file=/App.js) to reproduce the bug.

If you comment out `line 100` and uncomment `line 87->99`, the expected behavior of the `Scrollable` component works. However, if you put that block into it's own component and render it with in the parent, the following **buggy behaviors** occur:

1. Clicking a <Resource> Item within the scrollable pane causes the **scroll** to go all the way back up
2. Infinite scrolling doesn't work as expected, as the scroll will go all the way back up

Can we please have this fixed asap? Because otherwise, it is impossible to allow `Scrollable` to have any lifecycle hooks or logic

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).
