### ISSUE TITLE
[Link] Remove external link icon and clarify documentation

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#6413]
## Current behavior

The `Link` components `external` prop renders an external link icon to indicate the user is navigating to a page outside of the admin.

<img width="220" alt="image" src="https://user-images.githubusercontent.com/8629173/177407413-5edcdddc-3380-4316-9b68-651450f23707.png">

## Proposed changes

Based on previous audits and conversations around the icon, the proposal is to remove the external link icon. Removing the icon and updating the documentation to add clarity around external link usage and best practices for link text will add clarity for product teams and users. This is a decision that can be easily reversed if we find this hypothesis is incorrect.

### Rationale

- External links don't always need to be called out
- Words are more clear.
    - If it is a case where it's important to let the merchant know they're navigating away from the admin, you can do this through the link text itself.
    - Adding rules and logic around when and when not use the icon is a slippery slope.
- The icon adds more visual load especially when used inside a sentence or accompanied by other content

**[GitHub discussion](https://github.com/Shopify/polaris/discussions/6558)**

### Related issues:

- https://github.com/Shopify/polaris/issues/4547
- https://github.com/Shopify/polaris/issues/4756

---

# Link

### External link

Use for text links that should open in a new browser tab (or window, depending on the merchant’s browser settings). Use this only when opening a page in the same tab might disrupt the merchant’s workflow.

<img width="269" alt="image" src="https://user-images.githubusercontent.com/8629173/177416109-9a4e664e-8077-4c5b-83c2-f71a97b111e3.png">

### Open a new tab or window only when necessary

Use caution when opening a new tab or window as it can be disorienting. However, there are some cases where it does makes sense to open a new tab or window, for example, when navigating to a page outside of the Shopify admin, like a help center article.

When using an external link, use the appropriate props and labels so screen readers can recognize if a link will open in a new tab.

**Comment by emily-broughton** [comment]
Hi @sarahill , Here is the draft we can jam on: https://docs.google.com/document/d/1p0mhr5hL2tl0g9oJnD3rQRjBZZ6NNRcJBe7W6PPXXKw/edit?usp=sharing

**Comment by sarahill** [comment]
Adding a screenshot of a previous discussion around links for context. There is some brief mention of the external link icon.

![link-convo](https://user-images.githubusercontent.com/8629173/177619421-dfb8e5c9-c9a3-4293-9110-622944ced8f3.png)

**Comment by sarahill** [comment]
Another more recent convo about external links

![external-link-convo](https://user-images.githubusercontent.com/8629173/177618545-0e26b45f-25f9-4e03-8e94-3938050428b6.png)

**Comment by sarahill** [comment]
Example of a link that should open in the same tab:


![set-up-app](https://user-images.githubusercontent.com/8629173/177654048-450cd1df-5b87-43bf-bc02-2e239406bf12.gif)

**Comment by sarahill** [comment]
Created a branch in the UI Kit to remove the icon https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/branch/h5sgXvCe5dOs1q8A88xkW0/Polaris-Components?node-id=364%3A1700
