### ISSUE TITLE
[polaris.shopify.com] Content duplication removed and creation simplified

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#6428]
The goal of this work is to drastically simplify the page creation process on `polaris.shopify.com`. There should be no confusing duplicate content across the monorepo. Markdown should be understandable and have no duplication and only _for now_ `dodont` magic. Every page is created from a `markdown` file. A `page/[[slug]]` will catch routes that are not covered to render each page as markdown with different UI based on the route of the page. Or it will fall back to a generic one (like foundations and contributing).

Some pages will stay react but most should be markdown + route template. Creating a `pages/new-page.tsx` would always override the markdown approach.

Adding new `md` file automatically creates a nav item, a page and search results. No `.json` files, `.ts` files etc.

**Markdown clean up**
- [x] https://github.com/Shopify/polaris/pull/6617
- [x] https://github.com/Shopify/polaris/pull/6581
- [x] https://github.com/Shopify/polaris/pull/6681
- [x] https://github.com/Shopify/polaris/pull/6703
- [x] https://github.com/Shopify/polaris/pull/6678
- [x] https://github.com/Shopify/polaris/pull/6704
- [x] https://github.com/Shopify/polaris/pull/6679
- [x] https://github.com/Shopify/polaris/pull/6769
- [x] https://github.com/Shopify/polaris/pull/6834

**Frontmatter clean up**
- [x] https://github.com/Shopify/polaris/pull/6620
- [x] https://github.com/Shopify/polaris/pull/6619
- [x] https://github.com/Shopify/polaris/pull/6618
- [x] https://github.com/Shopify/polaris/pull/6682
- [x] https://github.com/Shopify/polaris/pull/6831
- [x] https://github.com/Shopify/polaris/pull/6832
- [x] Replace `components.json` and `foundations.json` with front matter from markdown
- Add a `description` for the bold paragraph and page metadata
- Remove duplicate markdown for `# Button` and `description`
- Adding new pages does not require editing `json`
  
**Navigation clean up**
- [x] Create markdown files for every page on the website
  - At a minimum each page should have a `title` `description` and `keywords`
- [x] Make the markdown file structure consistent with the navigation
  - `index.md` or `parent` directories with no child for missing structure
- [ ] Replace `tokensNav.ts` `navItems.ts` with an object generated from the`content` folder
  
**`<Page`, `_app`, `<Head`, `<Layout` clean up**
- [ ] Move logic from `_app.js` and move it to a `HTMLHead` component
  - Leave global styles
  - Examples no longer need if statements
  - `/ping` should be less flakey
- [x] Remove props from `Header.tsx` and move router and dark mode to it
- [x] Make the `Page` component used for every page, it should control layout, title and markdown content. Add `HTMLHead` to this
- [ ] Remove unpkg CSS version from ExamplePage

**src/pages/ clean up and simplification**
- [x] Replace `components/[component].tsx` `contributing/[doc].tsx` `foundations/[category]/[doc].tsx` and `tokens/*.tsx` with a _if there is a md file generate a page with a React template based on the route_.
  - Make markdown parser run on getStaticProps
  - Generate getStaticPaths from content dir

**Other**
- [x] https://github.com/Shopify/polaris/pull/6683
- [x] https://github.com/Shopify/polaris/pull/6680

**Tokens metadata**
- [ ] Replace `figmaColorNames.json` with generated names from token metadata (either fix Figma or update tokens)

**Comment by martenbjork** [comment]
Alex, could this be considered done?

**Comment by alex-page** [comment]
Oh gosh no. I am working on it.

**Comment by alex-page** [comment]
@martenbjork updated the issue

**Comment by martenbjork** [comment]
> Oh gosh no

Haha, OK <3
