### ISSUE TITLE
[polaris.shopify.com] New browser history entry on component `Examples` select changes

### ISSUE THREAD

**Issue by josebreijo** [Shopify/polaris-react-archive#6433]
Every time you select a different variation of a component via the `Examples` select, a new entry is added to the browser history stack. Since the URL isn't modified, I think this behavior should be removed from that functionality [(video)](https://screenshot.click/28-42-nxitn-gvzj6.mp4)

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by martenbjork** [comment]
Thanks for the bug report! I agree, this sounds stupid. Will fix!

**Comment by martenbjork** [comment]
I think this problem has been resolved thanks to some recent refactoring of the examples page. Closing the issue for now! 😋

<img width="693" alt="image" src="https://user-images.githubusercontent.com/875708/180441368-b828b58c-596b-4465-9cad-92928c4eb33a.png">
