### ISSUE TITLE
[polaris.shopify.com] Icons blocking numbered list

### ISSUE THREAD

**Issue by vladabee** [Shopify/polaris-react-archive#6448]
## Issue summary

[Content on numbered lists](https://polaris.shopify.com/foundations/content/grammar-and-mechanics#numbered) has icons overtop the numbers:
![screenshot](https://screenshot.click/28-36-1vsyr-p0fxf.png)

## Specifications

 - OS: OS Monterey 12.4
 - Browser: Chrome
 - Version: 103.0.5060.53 (Official Build) (arm64)

**Comment by martenbjork** [comment]
Thanks, we'll fix this as well! ☺️
