### ISSUE TITLE
[polaris.shopify.com] Duplicate x icons in sentences section (and missing 'Do' and 'Don't)

### ISSUE THREAD

**Issue by vladabee** [Shopify/polaris-react-archive#6449]
## Issue summary

[Sentences section](https://polaris.shopify.com/foundations/content/actionable-language#sentences) of `Actionable Language` has duplicate x icons:
![screenshot](https://screenshot.click/28-41-5s01o-06j84.png)

and is missing the `Do` and `Don't` headings

## Expected behavior

This is what other Dos & Don'ts on the page look like:
![screenshot](https://screenshot.click/29-37-rutcq-5e0lw.png)

## Specifications

- OS: OS Monterey
- Browser: Chrome
- Version: 103.0.5060.53 (Official Build) (arm64)

**Comment by martenbjork** [comment]
Odd! Thanks for reporting, will fix!
