### ISSUE TITLE
[polaris.shopify.com] Icon button names should not be subdued

### ISSUE THREAD

**Issue by chloerice** [Shopify/polaris-react-archive#6471]

**Comment by martenbjork** [comment]
From a design POV, we want the icons to stand out. The text shouldn't distract. The subdued text passes a11y requirements.

Do you still feel that this need to be changed, @chloerice ?

<img width="228" alt="image" src="https://user-images.githubusercontent.com/875708/180439767-2c4659b2-ca93-4f18-837f-4f29a05e7010.png">

**Comment by chloerice** [comment]
Hey Marten! Sorry meant to close this when the subdued color was fixed 💯

**Comment by martenbjork** [comment]
NP! 😋 Just trimming the backlog ☺️
