### ISSUE TITLE
[polaris.shopify.com] Document props for each component

### ISSUE THREAD

**Issue by bilal42011** [Shopify/polaris-react-archive#6477]
Change the docs to more readable form. Docs are unreadable no examples given like what props to pass. Make docs like react or like Material UI where each component should be of defined props which one to use , etc. Thankyou!

**Comment by martenbjork** [comment]
Hi! Thanks for the feedback! I hope you don't mind, but I updated the title of your Issue to be more specific around your ask.

We're getting a lot of feedback regarding the missing props table and will have an update for you soon. I'll close this issue as we are tracking it here: https://github.com/Shopify/polaris/issues/6371

Cheers!
