### ISSUE TITLE
[polaris.shopify.com] Feedback (please show the props on each component!)

### ISSUE THREAD

**Issue by mattie1da** [Shopify/polaris-react-archive#6479]
**Please** put the list of all the available props back into each component page! Unsure why it was removed, it was so helpful!

**Comment by martenbjork** [comment]
Hi! Thanks for the feedback! 🙌 This is very much on our radar and we'll have an update for you in the coming weeks.

I'll close this issue since we're tracking everything related to the props documentation in this issue: https://github.com/Shopify/polaris/issues/6371
