### ISSUE TITLE
Where are table examples?

### ISSUE THREAD

**Issue by ghost** [Shopify/polaris-react-archive#65]
I can't find table examples in docs. Please find a screenshot attached.

**Comment by JoshHighland** [comment]
This was brought up in issue #6 a month ago. Not sure if we are going to get tables.

**Comment by JoshHighland** [comment]
If you look at the new partner portal they are using Polaris. One issue I have with the response lists is the lack of ability to sort the columns. The sorting functionality was part all previous / current tables in the Shopify admin (outside of the new partner portal)

**Comment by JoshHighland** [comment]
*resourceList

**Comment by JoshHighland** [comment]
I take it back, the partners portal is using a "data-table". It's not in the polaris code base yet, but its for me to steal the CSS and HTML and make my own component until then.

**Comment by lemonmade** [comment]
Hey folks, as Josh mentioned, we are pointing people towards [ResourceLists](https://polaris.shopify.com/components/tables-and-lists/resource-list#navigation) to handle most of what we had been using tables for (mostly, presenting a list of resources on index views). We are working on improvements to ResourceList that will bring back the kind of filtering and sorting abilities we lose by not going with more traditional tables.

(As an aside, we will at some point be releasing a DataTable component, but this is primary meant to present more traditional tabular data, like report details. It's not really meant for presenting a list of resources).

**Comment by bakura10** [comment]
+1 for this. We have a few component that display really tabular data where ResourceList can hardly be used. It would definitely be useful to have a full-blown data table component !

**Comment by jimmyn** [comment]
@lemonmade +1 for this. Is there any progress? I'm currently thinking how to reproduce a table with "select all resources" feature, that is widely used in Shopify. So far it seems to be not possible to do it with Polaris. Any advice here?

![screen recording 2017-07-24 at 04 52 pm](https://user-images.githubusercontent.com/5391775/28526619-bc4998e0-7090-11e7-8ca3-7acbf7019a26.gif)

**Comment by charlesemarsh** [comment]
+1 This would be awesome

**Comment by embedded1** [comment]
Any update / workaround?
We need a table to show some well defined data.

**Comment by embedded1** [comment]
@JoshHighland mind sharing the custom table css?

**Comment by chaddjohnson** [comment]
@lemonmade Table support is critical. Need the ability to format things in columns. Also need filtering. It's been 6 months -- really need this ASAP.

**Comment by dfmcphee** [comment]
Following up here. We have plans to address this in version `1.9.0` some time in November.

This will include:

1. A Data Table component to be used for displaying sets of tabular data, similar to what we use in our Analytics section of the admin.

2. Enhancements to our Resource List component which will include UI for selecting items, sorting, and filtering.

**Comment by mattchidley** [comment]
@dfmcphee any update on a release date for 1.9.0?

**Comment by dfmcphee** [comment]
Another update for this. We have been doing some prioritization and planning for both 1.9 and our next major release (2.0).

Because we want to make some breaking API changes for the new version of the resource list component, we are going to hold off releasing any enhancements for it until v2.0.

I have created [milestones](https://github.com/Shopify/polaris/milestones) for 1.9 and 2.0 if you want to follow along as we make progress. We are also hoping to release a beta of 2.0 to get people trying it out before release.
