### ISSUE TITLE
V10 deprecation warnings show in V9.19

### ISSUE THREAD

**Issue by carstenlebek** [Shopify/polaris-react-archive#6504]
## Issue summary

The following warning is being printed to the terminal on every render, polluting the output.

```
Deprecation: The `CustomProperties` component has been deprecated. See the v10 migration guide for replacing dark color scheme styles. https://github.com/Shopify/polaris/blob/main/documentation/guides/migrating-from-v9-to-v10.md
```

## Expected behavior

Deprecation warnings for V10 shouldn't be printed in V9.

## Steps to reproduce the problem

1. Install Polaris V9.19.0
1. Run app

## Reduced test case

[https://codesandbox.io/s/shopify-polaris-react-typescript-playground-forked-6kvsns?file=/src/index.tsx](https://codesandbox.io/s/shopify-polaris-react-typescript-playground-forked-6kvsns?file=/src/index.tsx)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 9.19.0

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by kyledurand** [comment]
I think the idea is that we deprecate components or props one major version before their removal. This is noisy in the hopes that it gives developers a heads up that the removal is coming.

**Comment by carstenlebek** [comment]
That makes sense, but the problem here is, that the warning is showing up, even if no components are used. The AppProvider is actually the component triggering the warning. It literally makes the terminal output unusable.

**Comment by curtisburns** [comment]
Also experiencing this issue, even after looking into what I need to do to stop the warnings, there doesn't seem to be any solution. Would make sense to only show the warning if the `CustomProperties` component is actually being used as it's quite spammy otherwise, and confusing to developers new to the Shopify/Polaris ecosystem (me...).

**Comment by carstenlebek** [comment]
There is no solution to this, because the AppProvider, which you need to use Polaris is triggering the warning. Doesn't really make sense. The only solution is probably to wait for V10.

**Comment by mike-park** [comment]
Would it be possible that the warning is printed once only? As others have said, it's hard to read the console with all the spam.

**Comment by TreeOfLearning** [comment]
Wondering if there are any updates to this? Our logs are being needlessly polluted with these messages and it's making development more difficult. We expect some noise in general from Polaris, but still...
