### ISSUE TITLE
[Typography foundations] Remove existing typography components

### ISSUE THREAD

**Issue by laurkim** [Shopify/polaris-react-archive#6511]
To be done **after** token updates, new text component, and deprecation is released in the `next` branch for v11.

DisplayText, Heading, Subheading, Caption, ~TextContainer~, TextStyle, ~Label~, VisuallyHidden

**Comment by SeanyB** [comment]
Blocked by #6537.

**Comment by alex-page** [comment]
Hey @laurkim we should do this work in the `next` branch so that when we ship v11 this is a part of it.
