### ISSUE TITLE
[polaris.shopify.com] New docs layout does not have enough room for fullscreen bar

### ISSUE THREAD

**Issue by AaronSpringut** [Shopify/polaris-react-archive#6523]
## Issue summary

On the latest version of the Polaris docs site the docs for fullscreen bar compress the example rendered bar so that it does not have room to display all of its content.

## Expected behavior

The bar should render cleanly with enough space to show the content in the editable space.

## Actual behavior
Content in the editable space now overlaps:
![image](https://user-images.githubusercontent.com/97750621/177623245-ec3388d9-a163-4db7-8575-ee153f42b509.png)

**Comment by martenbjork** [comment]
Thanks for reporting! We're about to fix this. We have a few improvements lined up (#6403 among others) that should take care of this. I'll keep this issue open until it's fixed.
