### ISSUE TITLE
[polaris.shopify.com] Add installation guide/instructions to documentation site

### ISSUE THREAD

**Issue by joelzwarrington** [Shopify/polaris-react-archive#6524]
## Feature request summary

It would be nice to have a clear and concise guide to install and use Polaris - (particularly the components library)

## Rationale

We have existing documentation in a [README.md](https://github.com/Shopify/polaris/tree/main/polaris-react#using-the-react-components), but that information is lost when going to https://polaris.shopify.com/

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by martenbjork** [comment]
Thanks Joel! This is a good call. I'd love to up our "getting started" guides for all disciplines. Hope to have improvements for you soon!
