### ISSUE TITLE
[polaris.shopify.com] HTML examples of components

### ISSUE THREAD

**Issue by kirillplatonov** [Shopify/polaris-react-archive#6528]
Hey,

The new Polaris documentation looks amazing 🔥 Thanks for updating it!

However, the new version doesn't have HTML examples of components. It was important since not everyone is using react implementation of components. We have alternative implementations without React. For example, Polaris ViewComponents for Rails: https://polarisviewcomponents.org/. It's a pretty big library to create apps using server-side Rails instead of React. It would be great if you could add HTML examples to the new version of documentation 🙏 It will make the maintenance of libraries like Polaris ViewComponents easier going forward.

Kirill

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by kirillplatonov** [comment]
Thank you, guys! 👏

**Comment by martenbjork** [comment]
Thank you for the feedback, we really appreciate it! 🥳
