### ISSUE TITLE
[Collapsible] Make the close option configurable

### ISSUE THREAD

**Issue by iserioton** [Shopify/polaris-react-archive#6530]
## Rationale

It would be awesome to be able to configure the close option for Collapsible. This could be done in one of two ways:
 1. Exact toggle
 2. Popover or Modal toggle

If I want to close the collapse with the click of anywhere in the document it should be.
If I want to close the collapse, only if the click on the toggle buttons.

Give as a prop with two options:
1. exact
2. imprecise

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).
