### ISSUE TITLE
broken content in AppProvider docs

### ISSUE THREAD

**Issue by JaKXz** [Shopify/polaris-react-archive#6559]
## Issue summary

There are some content [extraction?] bugs in the [AppProvider](https://polaris.shopify.com/components/app-provider) docs, and maybe other components?

![image](https://user-images.githubusercontent.com/2642545/177873591-28b628c5-1277-47b8-ab29-d40e761172e7.png)

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by martenbjork** [comment]
Thanks for reporting! I'll fix this up!

**Comment by martenbjork** [comment]
This has now been fixed 🎉  https://polaris.shopify.com/components/app-provider
