### ISSUE TITLE
[Collapsible] animationState fails to transition on initial render

### ISSUE THREAD

**Issue by lamungu** [Shopify/polaris-react-archive#6566]
## Issue summary

When a Collapsible component is rendered, the animation state is triggered once the height is updated from 0 to its scrollHeight. The DOM, however, does not trigger the onTransitionEnd event on the div tag, since the height does not get changed outside of React. This causes the animationState to never receive the event sending it from animating to idle, and thus, any subsequent changes to the height does not get triggered.

## Examples

When users navigate to the Balance Transfer page, a `Collapsible` is initialized with the `open` prop set to true if the query parameter is set to that tab's identifier. The current behavior of the component triggers the animation of the content, but the `onTransitionEnd` does not run, leaving the div tag at a `max-height` value of 451px and an `animationState` of `animating`

### Actual Behavior

Below is shown how the overflow clips the collapsible content after it gets updated with a greater height:

https://user-images.githubusercontent.com/3449682/178003374-4efe8ff2-f7b6-4897-8efe-035e68a3beb9.mov

### Expected Behavior

Keep note that the animation works properly when the content is toggled out of its initial state

https://user-images.githubusercontent.com/3449682/178003393-7cd0451c-20c8-4985-8d52-6840f0c64ccd.mov

## Steps to reproduce the issue

1. Navigate to `/admin/shopify-balance/account/transfer?openSection=transferFundsFromBalance` on a Balance-Enabled shop
2. Trigger an error on the opened collapsible, by typing a description and pressing the Review button (shown in the videos above)

[Spin URL](https://shop9.shopify.banking-2td2.benjamin-lofo.us.spin.dev/admin/shopify-balance/account/transfer?openSection=transferFundsFromBalance)

## Reduced Test Case

_In progress of being created_

## System Information

```bash
 System:
    OS: Linux 5.10 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (32) x64 Intel(R) Xeon(R) CPU @ 2.80GHz
    Memory: 95.55 GB / 125.90 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
```

## Proposal

[A proposed approach was given in the following PR](https://github.com/Shopify/polaris/pull/6547/files), which aims at forcing the component to the `idle` state if the height of the component already matches that of the collapsible.

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by jas7457** [comment]
To add to this, the logic will cut off content if the browser gets resized before toggling the open state. For example, view [this video](https://screenshot.click/12-50-ydauc-24grd.mp4) to see the text disappear beneath the fold if you resize your browser before toggling the open state. This was done using our [codesandbox example](https://codesandbox.io/s/m5hxd3?module=App.js) in the Polaris docs for Collapsible.

After you toggle the open state, it is in a state that it can correctly resize, but will not work before.
