### ISSUE TITLE
[polaris.shopify.com] Feedback (on page /components)

### ISSUE THREAD

**Issue by Raman9937** [Shopify/polaris-react-archive#6582]
There is no docs on Props.

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by martenbjork** [comment]
Hi! Noted! It's very much on our radar and we'll have an update soon. We're tracking this issue in here: https://github.com/Shopify/polaris/issues/6371
