### ISSUE TITLE
Add a link to the next section at the bottom of each page, above the feedback section

### ISSUE THREAD

**Issue by raquelbreternitz** [Shopify/polaris-react-archive#6589]

**Comment by martenbjork** [comment]
Hi! Is this an issue for the whole site or just the contribution guidelines? Just wondering if I should add it to the back-log.

For the website in general, my 2 cents are these: We shouldn't hard code "prev" and "next" links into our markdown files. Instead, the website should make it so darn easy to move between pages that it negates the need for manual links to prev/next.

**Comment by raquelbreternitz** [comment]
Hi! Apologies, this was meant for the App Design Guidelines, not the Polaris site! I'll close this now.
