### ISSUE TITLE
Popover autofocus fix

### ISSUE THREAD

**Issue by dustinfirman** [Shopify/polaris-react-archive#6593]
## Feature request summary

The Popover component doesn't actually focus on the first node when you have something like an ActionList as the child. What happens is one of the wrapping divs of the action list gets focused instead of the first item of the list.

By changing `findFirstFocusableNode` -> `findFirstKeyboardFocusableNode` the first item will actually be focused on open. Since this is a very simple change I have tested it out and have an example before and after below.

Before: 

https://user-images.githubusercontent.com/105817582/178350252-47505f67-32bb-4d24-b6ca-4592f91f7f0b.mov

After:

https://user-images.githubusercontent.com/105817582/178350266-e30fa3e7-9101-43c2-8084-376d250e2069.mov

## Rationale

Improves accessibility of the Popover component.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by svinkle** [comment]
@dustinfirman I believe the `div` receives focus as there's no guarantee of the content type available within the popover.

@patrickracicot Is this related to the change shipped a while back?
