### ISSUE TITLE
When "Some filters disabled" search input stays active

### ISSUE THREAD

**Issue by oksanashopify** [Shopify/polaris-react-archive#6595]
## Issue summary

Discovered some behaviour in [Polaris component](https://polaris.shopify.com/components/filters), that looks like an issue. When we select  "Some filters disabled" and then go to "More filters" - "Vendor" label shows as disabled - but the search input stays active and we can perform search. 
This issue affects Products filtering in Shopify Admin. When filter by 'Collection' - 'Tagged with' filter should be disable 
Videos attached.
Polaris: 

https://user-images.githubusercontent.com/104942025/178359036-02792e7f-9bed-4468-86b4-cea9837b05ca.mov

Admin: 

https://user-images.githubusercontent.com/104942025/178359864-fa511583-2d02-49ef-8360-ce12ea577e7e.mov

## Expected behaviour

Vendor search input should be disabled

## Actual behaviour

Vendor search input active
 
Testers: @oksanashopify  and  @Stivaros

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by oksanashopify** [comment]
UPDATE: this issue does not block Admin anymore. On Admin side it was resolved with this [PR](https://github.com/Shopify/web/pull/68638)
