### ISSUE TITLE
[polaris.shopify.com] Props table feedback (IndexTable)

### ISSUE THREAD

**Issue by grahamsutton** [Shopify/polaris-react-archive#6598]
Would it be possible to add links to the following object definitions for the [IndexTable component documentation](https://polaris.shopify.com/components/index-table)?

* IndexTableHeading
* SelectionType
* MenuGroupDescriptor

**Comment by martenbjork** [comment]
Hi! Definitely! We want this props list to be fully automatic (so that it doesn't get out of date) so I just need to figure out how to improve the parsing script to include the nested types. I hope to have a PR for this in the coming weeks!

**Comment by alex-page** [comment]
This is a duplicate of https://github.com/Shopify/polaris/issues/6599
