### ISSUE TITLE
[polaris.shopify.com] Nested types missing from props table

### ISSUE THREAD

**Issue by liuzhijie1** [Shopify/polaris-react-archive#6599]
Could you tell me what have in complexAction

**Comment by alex-page** [comment]
@liuzhijie1 Thanks for reaching out. This is on our radar.

Marten mentioned this in his PR https://github.com/Shopify/polaris/pull/6584. We are going to resolve this over the coming weeks. We wanted to get this up in its current state.

From Marten's PR:
> The script assumes that props are defined using an interface called ComponentNameProps. Some components, like Avatar, uses other constructs (like union types) to define the props. The script can't yet parse these.

**Comment by chloerice** [comment]
Just an update on this issue, working on the props table is continuing in https://github.com/Shopify/polaris/pull/6757.
