### ISSUE TITLE
[polaris.shopify.com] Props table missing default value

### ISSUE THREAD

**Issue by ssc1234** [Shopify/polaris-react-archive#6601]
For props, it would be better to offer more details like the default value and all possible values for your pre-defined type so that it will be much clearer and more time-saving for developers.

**Comment by martenbjork** [comment]
Hi! I agree! 🙂 We will update the table in the coming weeks so that it contains more information about sub-types.

**Comment by alex-page** [comment]
For the missing props we are going to track that here https://github.com/Shopify/polaris/issues/6599

**Comment by martenbjork** [comment]
This has now shipped! 🚀
