### ISSUE TITLE
[polaris.shopify.com] Feedback (on page /components/checkbox)

### ISSUE THREAD

**Issue by SomeBrujah** [Shopify/polaris-react-archive#6606]
Great work❤️

**Comment by martenbjork** [comment]
Thank you!! 🥰

Closing since no action is needed, but really appreciate that you took the time to send a message! ❤️

**Comment by martenbjork** [comment]
Thank you!! 🥰

Closing since no action is needed, but really appreciate that you took the time to send a message! ❤️
