### ISSUE TITLE
variant resource picker need to have an option like show product name, as of now no product name mentioned.

### ISSUE THREAD

**Issue by G0kulRaj** [Shopify/polaris-react-archive#6622]
## Feature request summary
![image](https://user-images.githubusercontent.com/55785685/178717762-76fff7ff-1571-48d5-b7e7-744b55507d30.png)
1. Add product name to related variant in resource picker

## Makes confusion

it is really helpfull if we can show the product name along with product variant selection, as of now its making confusion to select

**Comment by Cyclodex** [comment]
No news about this? Something missing?

**Comment by martinX308** [comment]
I'm wondering how is this done on the admin > purchase_orders/ id/ edit page? there it seems that the resource picker used for adding items shows product and variants while the filter query is applied on the variant level and we also see inventory levels. How is this achieved?
