### ISSUE TITLE
[polaris.shopify.com] 404 not found at /foundations/design/polaris-is-changing

### ISSUE THREAD

**Issue by hanorahborealis** [Shopify/polaris-react-archive#6626]
Broken link found on an old Tweet.

**Comment by martenbjork** [comment]
Thanks for reporting! @alex-page, I assigned you since you have the most context on redirects.

**Comment by alex-page** [comment]
Hey @hsvanni we removed this page a long time ago. I don't think we plan to add any redirects as there is nothing that replaced that page.

If there is any additional context you can share or if you want this fixed let me know.
