### ISSUE TITLE
Index Table selectable={false} removes onClick handler

### ISSUE THREAD

**Issue by carstenlebek** [Shopify/polaris-react-archive#6629]
## Issue summary

When setting the IndexTable component to non selectable to remove the checkboxes, the onClick handler of the IndexTable.Row component stops working.

## Expected behavior

Index table rows should be a row of information, that is still clickable, even if there are no bulk actions to perform.

## Actual behavior

Index table rows don't have an onClick handler, if the table is not selectable.

## Steps to reproduce the problem

1. Add IndexTable component2. 
2. Set prop selectable to false3. 
3. Add onClick prop to IndexTable.Row 

## Reduced test case

 [CodeSandbox](https://codesandbox.io/s/shopify-polaris-react-typescript-playground-forked-u52zvg?file=/src/index.tsx)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 9.19.0

**Comment by jjgali** [comment]
Hi @carstenlebek! If I understand correctly, you'd like to have items in a table with no checkboxes, but still be clickable/linkable? If so, you might want to consider using the [data table element](https://polaris.shopify.com/components/data-table) and link the title (like in the example under "With all its elements.").

<img width="819" alt="Screen Shot 2022-08-15 at 4 42 42 PM" src="https://user-images.githubusercontent.com/77791660/184715093-8be87bc2-8a4f-4905-9623-39969df2ae60.png">

**Comment by bakura10** [comment]
Hi @jjgali.

Unfortunately, using Data Table does not offer some feature such as pagination and filtering. Can this be fixed for the IndexTable componenent ? Is there a reason why the onClick handler does not work when selectable is set to false?

Additionally, it seems that setting selectable to false impact the border between each items:

<img width="975" alt="image" src="https://user-images.githubusercontent.com/1198915/215087727-9eea31c4-f043-48cd-b9a0-8552f497951f.png">

When using selectable=true the borders properly show.

**Comment by alex-page** [comment]
Hey @bakura10 if you want to make a PR to resolve this issue in `IndexTable` I would be happy to review it. One reason for closing is there are other ways to do click events with children etc. This might not be useful for your use case.

**Comment by adearriba-fik** [comment]
Hi @alex-page, this is still an issue in @shopify/polaris version 11.10.2. 

It is an expected behavior for a user to click the row to open the details based on Shopify's native index table experience.

**Comment by adearriba-fik** [comment]
I looked at the code and found out I can recover this behaviour setting the first column as a `dataPrimaryLink`.

````
<Link 
    dataPrimaryLink
    monochrome
    removeUnderline
>
    <Text variant="bodyMd" fontWeight="bold" as="span">
        {item.order_id}
    </Text>
</Link>
````
