### ISSUE TITLE
[polaris.shopify.com] Props table feedback

### ISSUE THREAD

**Issue by artyrcheek** [Shopify/polaris-react-archive#6632]
On the Grid element 
No docs for how to have a full span element.
columnSpan doesn't seem to work
No indication of whether columns are desktop down, or mobile up

**Comment by zecarlostorre** [comment]
@kyledurand 👀

**Comment by alex-page** [comment]
This is related to the current limitations of how we have built a MVP of the component props. We have fixes coming soon. We are working on this in this issue https://github.com/Shopify/polaris/issues/6599
