### ISSUE TITLE
[polaris.shopify.com] Search box reappears after typing `Enter` to select a result

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#6638]
Reproduction Steps:
1. Open the search pop modal
2. Type a search term that returns at least one result.
3. Select a result with the keyboard and type `Enter` to select it.

Expected Results:
The modal disappears and the user is navigated to the result page.

Actual Results:
The modal disappears **briefly** and the user is navigated to the result page, but the Search modal immediately **reappears**.

Notes:
- Occurs 100% of the time.
- Tested on Chrome and Firefox.

**Comment by martenbjork** [comment]
OK, I've narrow this one down to this:

- When you press enter, the keydown event closes the modal and returns focus to the previously focused element (a11y best practice)
- The onkeyup event immediately fires on that element causing the modal to re-open

You can prove this by manually setting the focus on the dark mode switcher, then opening the global search using the `/` key. When you press enter on a result, the search will disappear (onkeydown), focus will return to the dark mode switcher, and the site will switch to light/dark mode (onkeyup).

Will ship a solution next week!

**Comment by martenbjork** [comment]
Actually, let's fix it right away. PR here: https://github.com/Shopify/polaris/pull/6736
