### ISSUE TITLE
[polaris.shopify.com] Reset breaks `<List>` component's styles

### ISSUE THREAD

**Issue by Flufd** [Shopify/polaris-react-archive#6639]
https://github.com/Shopify/polaris/blob/main/polaris.shopify.com/src/styles/globals.scss#L117

This style reset breaks the styles for the `List` component so that the bullets/numbers are not rendered.

<img width="595" alt="image" src="https://user-images.githubusercontent.com/3304890/179087170-5b14880a-1237-4361-8019-062958ec30d3.png">

<img width="570" alt="image" src="https://user-images.githubusercontent.com/3304890/179087108-9aa335ee-394e-4f91-a48a-d580f931af8e.png">

**Comment by martenbjork** [comment]
Thanks for the report, super helpful!

TLDR, if you're interested: Next.js makes global CSS available on _all_ pages, including examples. We've taken steps to separate Polaris CSS from Website CSS, but it's not enough. Short term, we'll have to come up with a fix. Longer term, we're eagerly awaiting improved layout support in Next.js: https://nextjs.org/blog/layouts-rfc
