### ISSUE TITLE
Polaris style is not applied on components

### ISSUE THREAD

**Issue by denniss** [Shopify/polaris-react-archive#6650]
## Issue summary

I am setting up a new React app (on Ruby on Rails) and I want to use the Polaris components. After following the set up, I am able to see some styles being applied but it doesn't seem that the button UI looks correct. Here's the code that I use:

Content of `./javascript/packs/ShopifyAppIndex.jsx`

```
import React from 'react'
import enTranslations from '@shopify/polaris/locales/en.json';
import {AppProvider, Page, Card, Button} from '@shopify/polaris';

class ShopifyApp extends React.Component {
    render() {
        return (
            <AppProvider i18n={enTranslations}>
                <Page title="Example app">
                    <Card sectioned>
                        <Button>Example button</Button>
                    </Card>
                    <button className="Polaris-Button">Example button</button>
                </Page>
            </AppProvider>
        );
    };
}

export default ShopifyApp
```

Content of `./javascript/packs/ShopifyAppIndex.jsx`

```
import React from 'react'
import ReactDOM from 'react-dom'
import ShopifyApp from '../components/ShopifyApp'

ReactDOM.render(
    <ShopifyApp/>,
    document.getElementById('app')
)
```

The `react_home.html`. Note that I am using the style tag because I couldn't get the 
`import '@shopify/polaris/build/esm/styles.css';` line to work.

```
<!DOCTYPE html>
<html>
<head>
  <title>Shopify</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link
    rel="stylesheet"
    href="https://unpkg.com/@shopify/polaris@9.8.0/build/esm/styles.css"
    />

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<div id="app"></div>
<%= javascript_pack_tag 'ShopifyAppIndex' %>
</body>
</html>
```

And this is what I see:

<img width="871" alt="Screen Shot 2022-07-15 at 7 58 03 AM" src="https://user-images.githubusercontent.com/385638/179250057-68e02682-fc9d-4dbe-816d-7649be445cdd.png">

I notice the following warning under the console tab. I wonder if this could be the issue:
<img width="1640" alt="Screen Shot 2022-07-15 at 8 06 56 AM" src="https://user-images.githubusercontent.com/385638/179251716-c002cbbc-846d-4fd6-ab54-c153abc15435.png">

## Actual behavior

I expect the button UI to show up.

## Steps to reproduce the problem

1. Follow the polaris set up instruction on Github documentation.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: ^9.20.0
- Browser: Chrome
- Device: Mac OSX
- Operating System: Mac OSX

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
  System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 108.08 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 8.9.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 15.5
  npmPackages:
    @shopify/polaris: ^9.20.0 => 9.20.0
    react: ^17.0.0 => 17.0.2
    react-dom: ^17.0.0 => 17.0.2
```

**Comment by martenbjork** [comment]
Hi! Thanks for reporting and sorry for the headache. To fix this, please update to a newer version of the CSS file:

https://unpkg.com/@shopify/polaris@9.20.0/build/esm/styles.css

I created a [CodeSandbox](https://codesandbox.io/s/happy-cdn-c21eff?file=/public/index.html) to reproduce your issue. I got the same results as you. By updating the CSS, the problem was fixed.

I've fixed the Readme so that it no longer references the broken CSS. 🙏
