### ISSUE TITLE
[polaris.shopify.com] "Spacing" prop on some components uses undocumented values

### ISSUE THREAD

**Issue by cgardn** [Shopify/polaris-react-archive#6651]
Components with prop `spacing?` reference a `Spacing` type, which after some digging leads me to [this section of the design guide](https://polaris.shopify.com/foundations/design/spacing#spacing-in-code), which has this reference to `stack`'s spacing prop:

> The [stack](https://polaris.shopify.com/components/stack) component can be used to arrange arbitrary components in a horizontal row or vertical stack with space in between. It accepts the same values as the Sass spacing function to control spacing between the items.

However as of v9, the spacing function was deprecated in favor of spacing tokens, per [PR #4691](https://github.com/Shopify/polaris/pull/4691/). Reviewing the PR, I found the following values for the removed spacing function:
`none` `extra-tight` `tight` `loose`

A brief test showed that the `spacing` prop on certain components (ButtonGroup, etc) still uses these other values. I'm willing to add a page or explanatory note somewhere with these values, I just wanted to make sure these are the only values, and to ask the maintainers where the best place in the docs page is for a table of these values - either on the pages where the `spacing?` prop is used or somewhere else, perhaps as a link on the `Spacing` type reference itself.

Thanks!

**Comment by cgardn** [comment]
Update: I found a spacing prop [on line 4549 of props.json](https://github.com/Shopify/polaris/blob/main/polaris.shopify.com/src/data/props.json#L4549) that explicitly writes out accepted values, would it be best to just replace instances of `type: Spacing` with `type: none | extra-tight | tight | loose` in props.json?

**Comment by martenbjork** [comment]
Hi! Thanks for the feedback! The team and I are working on fixing this. We're tracking it in #6599.

We don't want to manually maintain `props.json`. Instead we want an automatic script to go over `polaris-react` and extract these values. That will make sure the site is always correct and up to date. It will also enable us to build more advanced tooling (playgrounds!) down the road.

I'm currently figuring out how to build this stuff. I hope to ship improvements iteratively over the coming weeks 😊

**Comment by martenbjork** [comment]
I'll close this issue to avoid duplicates, but feel free to follow up if you have any questions!
