### ISSUE TITLE
[polaris.shopify.com] Issues with Data Visualizations: Horizontal bar charts content

### ISSUE THREAD

**Issue by adam-ruf-shopify-ux** [Shopify/polaris-react-archive#6652]
Page context: [Data Visualizations](https://polaris.shopify.com/foundations/design/data-visualizations#bar-positioning)

## Issue summary

ISSUE 1
"Bar positioning" is an awkward label for the content it describes: The guidance focuses on talking about how thick or thin the bars should be (i.e., sizing not positioning). Solution ideas: Combine Color and Bar Positioning to "Style", Change label to "Bar sizing"
![image](https://user-images.githubusercontent.com/108495068/179307348-89f054f8-bc9f-437b-8df8-4cca2a63625f.png)

ISSUE 2
Missing Bar sizing guidance for horizontal bar charts: Oops, we just reused the content for Vertical column charts for Horizontal bar charts, which doesn't make sense. [img 2] Solution ideas: width → height and come up with a measure, like 3x-4x space between label and bar
![image](https://user-images.githubusercontent.com/108495068/179307375-32d21b60-fd9b-4e7a-b208-c7fb3aa7c12c.png)

ISSUE 3
Missing Bar sizing images for horizontal bar charts: We have images for vertical bar charts, so I expected images for horizontal bar charts, too
![image](https://user-images.githubusercontent.com/108495068/179307450-4e884de8-3ef9-4dad-bec7-fe9a16ea015a.png)

Please LMK if you have any questions. Thank you!

**Comment by martenbjork** [comment]
Thanks for the feedback, Adam!

Ping @mirualves — did you author this content? Let me know if you want to jam on updating it!

**Comment by adam-ruf-shopify-ux** [comment]
Hey again, Marten! 🙂

Just wanted to share a couple fresh ideas about clear section labels:
- "Bar height" for horizontal bar chart section
- "Bar width" for vertical bar chart section

**Comment by mirualves** [comment]
Hi Adam! Your suggestions make sense to me. I'll let @rebecca-pasiak and @justin-rayne (our contend designers) weigh on the decision here.
