### ISSUE TITLE
Fitted SkeletonTabs Prop

### ISSUE THREAD

**Issue by gil--** [Shopify/polaris-react-archive#6654]
## Feature request summary

Can we consider adding a fitted prop (and associated styling) to the SkeletonTabs component? It would act like the normal Tabs component where the tabs are fullwidth, each taking equal spacing.

## Rationale

If a Tabs component uses fitted, having the skeleton appear similarly will reduce UI changes when the UI switches from loading to loaded.

I'm open to contributing but didn't know if something like this would be rejected?

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by laurkim** [comment]
@gil-- thanks so much for opening this issue! This is in our backlog as a feature request but we would love for you to contribute the update if you have the bandwidth.
