### ISSUE TITLE
Extend the ColorPicker component to support a textfield for a Hex color

### ISSUE THREAD

**Issue by renerbaffa** [Shopify/polaris-react-archive#6656]
## Feature request summary

Extend the ColorPicker component to support a textfield to type in a Hex color:

<img width="405" alt="Screenshot 2022-07-18 at 16 27 20" src="https://user-images.githubusercontent.com/3033781/179533640-f37f5293-852d-4145-9d0b-55c798de32e7.png">

## Rationale

Recently I had to extend Polaris' ColorPicker to make it support a textfield that merchants could copy+past a hex color from their branding color because it would be almost impossible to find a defined color using the current version from Polaris.

Out of curiosity I made a [quick search](https://grokt.shopify.io/results?q=%3CColorPicker) and found out several other projects replicating the same functionality. Here is a list of projects that extend the Color Picker to add the text field and support a text:

- online-store-web ([here](https://github.com/Shopify/online-store-web/blob/ad6920a17fd2ce82d48805e0b53311c6c3251cba/packages/%40editor/settings/ColorSetting/components/ColorPicker/ColorPicker.tsx#L52) and [here](https://github.com/Shopify/online-store-web/blob/ad6920a17fd2ce82d48805e0b53311c6c3251cba/packages/%40editor/settings/ColorSetting/components/TextPicker/TextPicker.tsx) are the implementation)
- hatchful ([here](https://github.com/Shopify/hatchful/blob/290d285ad5b512276a37247fb55f34196ffba43a/firebase/src/components/ColorPicker/ColorPicker.js#L114))
- apple-business-chat-commerce ([here](https://github.com/Shopify/apple-business-chat-commerce/blob/d5834ac7f79bd4b0695b49b3ccb74472d27e746a/app/ui/sections/Customizations/components/BrandingSectionWide/components/ColorSettingCard/ColorSettingCard.tsx#L137))
- forms ([here](https://github.com/Shopify/forms/blob/3e93af28cb89909b005089d880eb7c62ae956ee3/app/ui/components/ColorPicker/ColorPicker.tsx#L81)) -> **this is the one I implemented in my team**
- Shopify/web ([here](https://github.com/Shopify/web/blob/85adb022b7e535df4ad771f4d4fb778d712b1fb1/app/components/ColorPicker/ColorPicker.tsx#L23), [here](https://github.com/Shopify/web/blob/85adb022b7e535df4ad771f4d4fb778d712b1fb1/app/components/ColorInputField/ColorInputField.tsx#L99) and [here](https://github.com/Shopify/web/blob/85adb022b7e535df4ad771f4d4fb778d712b1fb1/app/sections/Inbox/InboxAppearance/components/ButtonStyles/components/ButtonColor/components/ColorPickerPopover/ColorPickerPopover.tsx#L97))
- email ([here](https://github.com/Shopify/email/blob/df512985fc5016872401e1cf9a09706cb04f2ceb/packages/%40shopify/online-store-editor-settings/ColorSetting/components/ColorPicker/ColorPicker.tsx#L40))
- linkpop ([here](https://github.com/Shopify/linkpop/blob/0b2dea39b40da1a31b6c108cd7e18b6ec5ab4676/web/components/ThemeSettingsForm/ColorPicker/ColorPicker.tsx#L154))
- notebooks ([here](https://github.com/Shopify/notebooks/blob/96670f63e9b199ba1b7739734a0da027270d458f/app/ui/components/Notebook/components/TextEditor/components/TiptapToolbar/components/ColorPicker/ColorPicker.tsx#L44))

It would be benefit to have this functionality built into Polaris so that we can centralize all configuration and functionalities. Getting rid of this code in all those projects listed above would be extremely helpful.

I'm happy to put up a PR that would cover that if it gets the approval it needs to become a feature

**Comment by thomassieczkowski** [comment]
👍

**Comment by thiagofm** [comment]
👍 I'd love to contribute on adding this to Polaris. The hex color functionality is so ubiquitous

**Comment by aaronccasanova** [comment]
Thanks for the request, @renerbaffa. We’re not actively working on this right now, but we’d love for it to make its way into the system. Please feel free to contribute and open a PR!

**Comment by renerbaffa** [comment]
thanks for the feedbadk @aaronccasanova. I'll try to put up a PR as soon as I get some time from my side :)

**Comment by laurkim** [comment]
Hey @renerbaffa, just doing some backlog cleanup and noticed you mentioned opening a PR when you have the time. Going to add you as an assignee to this issue 😃

**Comment by renerbaffa** [comment]
[PR is ready](https://github.com/Shopify/polaris/pull/7041) for review. Not sure if I need to assign anyone specifically to it?

**Comment by renerbaffa** [comment]
Yet another implementation of the same thing:

https://shopify.slack.com/archives/C02AW53L350/p1661937555999419?thread_ts=1661936712.235259&cid=C02AW53L350

**Comment by kyledurand** [comment]
If someone takes this on in the future please add it as a composition in `ColorPicker.stories.tsx` and not as a prop configuration to the component
