### ISSUE TITLE
[polaris.shopify.com] Transparent "Edit in CodeSandbox" button in DarkMode

### ISSUE THREAD

**Issue by zakwarsame** [Shopify/polaris-react-archive#6718]
The text color of the "Edit in CodeSandbox" button doesn't change in dark-mode but instead blends in with the background.

Lightmode:

![image showing the "Edit in CodeSandbox" button in lightmode](https://screenshot.click/21-06-92169-20756.png)

Darkmode:

![image showing the "Edit in CodeSandbox" button disappearning in darkmode](https://screenshot.click/21-59-51380-70310.png)

**Comment by martenbjork** [comment]
Thanks for reporting! I broke this earlier this morning.

This PR should fix it: https://github.com/Shopify/polaris/pull/6716 Merging soon!
