### ISSUE TITLE
Typos or corrupted content on Product Content page

### ISSUE THREAD

**Issue by tommcgathshopify** [Shopify/polaris-react-archive#6734]
## Issue summary

Hi there, the product content page looks like it was either corrupted or is full of typos. For example here in the intro paragraph:

> They’ll also give you clear, tactical thegestions designed to help you use language to craft better experiences. suggestionsnent](/components/get-started) also includes content guidelines about suggestionsnentr

And later here:

<img width="807" alt="Screenshot 2022-07-22 at 13 27 14" src="https://user-images.githubusercontent.com/109221773/180429925-6b3c11dd-17fa-43b3-97d8-0bc95f1995e9.png">

## Expected behavior

This page should be free of typos and be rewritten or reverted to an older version so that it can be understood.

## Steps to reproduce the problem

N/A as these are typos. However I looked at the content in Incognito Mode and on Safari.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number: N/A
- Browser: Chrome
- Device: MacBook Pro
- Operating System: MacOS 12.5

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by martenbjork** [comment]
Thanks for flagging! We shipped a formatting change yesterday which broke some content. Will fix!

**Comment by alex-page** [comment]
Fixed in 520dd622654f2e40f5f5788e900cc8637f971d76
