### ISSUE TITLE
[polaris.shopify.com] Investegate `dev` script that's defined in Readme

### ISSUE THREAD

**Issue by martenbjork** [Shopify/polaris-react-archive#6740]
I actually don't use this script and I've gotten reports that folks can't get it to work.

<img width="799" alt="image" src="https://user-images.githubusercontent.com/875708/180449569-6a373b87-d036-45f8-b80d-57f9b797eff2.png">

**Comment by alex-page** [comment]
03b5909c18b7c6ed54bb7639df5e3617f4767e2f fixes this for now
