### ISSUE TITLE
[IndexTable] Text field click triggers row selection on data table index

### ISSUE THREAD

**Issue by CharlyTalavera** [Shopify/polaris-react-archive#6746]
Hi! We're experiencing some issues with Index Table and TextFields React components.

## Issue summary

We're trying to use a TextField inside an IndexTable component, but there is a weird behavior.
When we try to click in the TextField input, the table row is selected. Here there is a video showing the issue:

https://user-images.githubusercontent.com/16298019/180494560-66f33ab5-9054-4b14-b2d0-edf1080c9cb8.mp4

Everytime that the user click in the input inside the index table, the row is selected.

Here there is a code sanbox that you can take a look to reproduce it: https://codesandbox.io/s/heuristic-bas-iwwxpn?file=/App.js

## Expected behavior

When the user clicks in the textfield input, the checkbox selection shouldn't be trigger.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 9.21.0
- Browser: Chrome Version 102.0.5005.61

**Comment by islam3zzat** [comment]
I think this is related to https://github.com/Shopify/polaris/issues/6117
This is a feature, I guess, that makes some functionality possible.
TextField on purpose allow events to propagate, which causes the row to get checked when it detects the click event.

You can wrap the TextField with an element and suppress the event https://codesandbox.io/s/thirsty-https-w9944m?file=/App.js

**Comment by jesstelford** [comment]
This behaving as expected (DOM events bubble up), however I can see that the behaviour is surprising.

The workaround for now is like @islam3zzat says: Manually capture the event and stop it from bubbling up.

[Here's a Polaris Sandbox version of @islam3zzat's workaround](https://polaris.shopify.com/sandbox?code=N4Igxg9gJgpiBc4IDsDOAXABGArhiAtjAE6qYC8mA2gDrKabB0MMCWU8mNIAzACwBGAdwA0zFjmIAbTt1z4ipAPT9hIMfRbIAhkVkgAstpiYAUjAKtUKUeIZSIYbelYp9AERhP0kkZgCqAMoAgraaDBDEsKScAEwADBosmLoQOMjogQAOMBn6ACSxInzx8dziAL5JjHaY7PqxAKwAbGrVDJIyXOB46IQkqEpNzWHJOnrdAKJSUrmYAPJgABYQ2qMsDt6uyPoAMhBkwcgA5jCzqH5Boeq1kdGonDyJtanpmTl53fkCJeWaFXQALoAbjokDQWGIMGskjAMAAcroTJQmJpUKwTjgpNpiPp5H1FOsslJJNounJev1SH8KqDkOCMNRXhlsrl0ABJZBZHDoPyoGDoYIENIsj4crk8wEUTB4GCBdDOGAACiogIAlHSGVhUQx%2BbMwOgYFAAErQtLEOEXcRkqSmmEW6GBM5eQ1QapLbTIKCzJ36lwoADCHpOMDoFWlss5sAAHnbzXD5YqlfiqagNWCUIziBAAO5GYgAaxwWWlKcUqAAdARtFkleIlcA6m7MOMYH5Ns5tn47gM-Mz3mzMFU6l6YNG1RQAHyYOvhTAAHijY4AKtoAEazCvG3O1NhQcjAdgAucMAswACeB6Pu8wepdRoPd4NRrjsOhFYxYBJsFQSvYauPZIGCyA5WH9ZAr1HaNAKAycb0XKDVw3GAKwDM4pEnYBWwqeclCXaMkM3NCZjgk8F3wwiUOIjDgA7cCcLwxD1yI9DSKA8imOQ1DWOAHtSAYijmKo1j4MErjqLY9iFygVgADdMEDKRWDAAsDyVGAJ3IacUPwLIAAVsyybRjk7FAlQAySpIXZcx3QAAxVgzigG92NkskcBgA9%2B1ZDJOW5dAqAxGNARgqyImQINPVONS3JJDSpxqMirK1FsYBzAA1dzoWlKgKzy7yxT8yU6TCoDkDSzK4tQQKoKlShYo8krSpYflBWFN4fPFfylXKjKsrTJrSoqUKwqUSygNwmTZPGhhcLEliSNqObOM3bcc0ktU6HTZA6ChHxiHoWdZoDHEoHGhCY0om8oXtOFESIA8bvjBEkRGthDQIAMRXQA8ywGCtZhOdAljezAlCUKyn1ddkPtQL63gPG9wdKm1XwdVBfXvKBMAAfm6YIZm4TBOChl8zTfStAeOYGkYh9jQZQTGDW2SKQwPYNvTlZ1mcDYNTlBpYYG0GSTlQA9aCSxhMBcdBZn0e7QxAId2iAxsZbl7p9i2GwlaqFypfVmB9HmKISGwb6ib1yW1bAjXuCFb7bzFS2bxCm8ZsYbM8xxIsshG5bLqEyTcJOqJSI1dQQGBixoQQKgQA7OXchAQERBAHN2GB1A45CoA)
