### ISSUE TITLE
[polaris.shopify.com] Props table feedback - Show values for complex types

### ISSUE THREAD

**Issue by mathildebuenerd** [Shopify/polaris-react-archive#6775]
## Current behavior

When looking at a prop with is a complex type like:
* a literal type
* an object

There is no preview of the possible values:

<details>
<summary>Screenshot</summary>

<img width="1281" alt="Screenshot 2022-07-27 at 15 08 00" src="https://user-images.githubusercontent.com/22640631/181254764-45efee65-c48d-4567-9afe-1ba63e929914.png">

</details>

Source: [Popover](https://polaris.shopify.com/components/popover) component.

## Expected behavior

If the prop is a literal type, I expect to see the list the of possible values (in that example: "top" | "bottom")
If the prop is an object, I expect to see all the properties and their types

**Comment by martenbjork** [comment]
Hi! This is coming very soon! Here's a preview of what we're working on: (in PR #6757)

<img width="759" alt="image" src="https://user-images.githubusercontent.com/875708/181371651-4b119a5c-d057-40bf-ac5c-e71efd197c50.png">

<img width="754" alt="image" src="https://user-images.githubusercontent.com/875708/181371426-1d37e67c-8a56-497a-9ae9-a6238d574058.png">

**Comment by martenbjork** [comment]
For house keeping purposes, I'm gonna close this issue since we're tracking this request in #6599

**Comment by mathildebuenerd** [comment]
@martenbjork Thank you, looks fantastic! 💯
