### ISSUE TITLE
[polaris.shopify.com] Props table feedback - Missing props

### ISSUE THREAD

**Issue by renerbaffa** [Shopify/polaris-react-archive#6779]
Props are missing on the list. Currently only `children``fullWidth`, `narrowWidth` and `divider` are listed, but the `Page` component accepts more than that like `primaryAction`, `title`, `secondaryActions` and others:

<img width="683" alt="Screenshot 2022-07-27 at 16 45 05" src="https://user-images.githubusercontent.com/3033781/181277214-3793601c-fc98-4e1e-89b1-3e6f319175ca.png">

**Comment by martenbjork** [comment]
Fix coming soon! WIP PR is up here: #6757

<img width="901" alt="image" src="https://user-images.githubusercontent.com/875708/181278158-f1c5416b-1e3b-4a36-b589-c067233aa9e6.png">

**Comment by AndrewMusgrave** [comment]
@alex-page Love the look of the new explorer 😍

**Comment by alex-page** [comment]
That is all @martenbjork magic!
