### ISSUE TITLE
[polaris.shopify.com] Components last in search

### ISSUE THREAD

**Issue by heyjoethomas** [Shopify/polaris-react-archive#6784]
## Issue summary
When using the new search feature on polaris.shopify.com, components are the last result in the query return. For example, if I am search for a `TextField` I have to have the entire entry filled out before I can see Components in the results field. 
<img width="1624" alt="Screen Shot 2022-07-27 at 1 03 48 PM" src="https://user-images.githubusercontent.com/5749440/181342524-9517f265-29e6-4464-ba58-b0299c3f9a39.png">

## Desired state
Since components are the backbone of the site and the system, I would expect them to be first rather than last. This would make it much easier to find the most important information via search.

**Comment by martenbjork** [comment]
Thanks for the feedback! For context, we use `Fuse.js` for the search which allows us to add searchable properties, weights and other parameters. The category that contains the top scored search result is shown first.

In this case, the token name might be weighted too heavily which renders the tokens section first.
