### ISSUE TITLE
[Typography foundations] `Text` component slack guidance

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#6796]
Create equivalent guidance for the `Text` component similar to the Figma guidance in this post: https://shopify.slack.com/archives/C03MXS2TB4J/p1658954824150649

Just a short blurb and gif for each of example shown in that slack link above if they have an equivalent. We can also add code specific ones that we think would be useful.

**Comment by sarahill** [comment]
@laurkim is this something you might have bandwidth to help out with?

**Comment by laurkim** [comment]
@sarahill of course! 👍

**Comment by laurkim** [comment]
:vscode: Alpha Text component example implementation with autocomplete for prop options
![alpha-text-component-example](https://user-images.githubusercontent.com/26749317/182885811-a577704e-f3bf-4eaf-895a-2254da78bcc4.gif)

:polaris6: Check out the new docs for the Alpha Text component on [polaris.shopify.com](http://polaris.shopify.com/) to see examples and mapping from previous Polaris typography components
[gif](https://screenshot.click/alpha-text-component-docs.gif)
