### ISSUE TITLE
Improve useIndexResourceState API for TypeScript users

### ISSUE THREAD

**Issue by tom-engineering** [Shopify/polaris-react-archive#6808]
## Feature request summary

The API for `useIndexResourceState` doesn't allow consumers to use a typed array without extending it to match the index signature:

https://codesandbox.io/s/react-typescript-forked-4vudqs?file=/src/App.tsx

On line 46, TypeScript complains:

```
Argument of type 'Customer[]' is not assignable to parameter of type '{ [key: string]: unknown; }[]'.
  Type 'Customer' is not assignable to type '{ [key: string]: unknown; }'.
    Index signature for type 'string' is missing in type 'Customer'
```

I think this can be improved by removing the index signature from `useIndexResourceState` and `ResourceIDResolver` to make the API nicer for consumers. From my brief experiment it definitely builds and tests pass:

Before:
```
type ResourceIDResolver<T extends {[key: string]: unknown}> = (
  resource: T,
) => string;

export function useIndexResourceState<T extends {[key: string]: unknown}>(
```

After:
```
type ResourceIDResolver<T> = (resource: T) => string;

export function useIndexResourceState<T>(
```

I am more than happy to create the PR for this minor improvement if I haven't completely missed something obvious.

## Rationale

It's a quality of life improvement for consumers of the library who may have to wrangle with TypeScript union types or unnecessary object spreading for what seems to be no benefit to the library.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by weeksie** [comment]
oh my god why was this closed, the type on `useIndexResourceState` is needlessly restrictive, the only thing you should care about is that you're being passed an array. It's such an easy fix.
