### ISSUE TITLE
[polaris.shopify.com] Props table feedback

### ISSUE THREAD

**Issue by camd** [Shopify/polaris-react-archive#6810]
I came to the Polaris `Page` page to see how to write up the `primaryAction` and `secondaryActions` props, but I didn't see it there.  After looking around, I found the link under `Related components` but that was not intuitive.  I feel like all props that can be set on a component should show in the Props section.

I understand the intent is likely to keep the page from getting too busy, but the current layout obscures too much (for my tastes).  Even if it were to list `primaryAction: See Page Actions` as a link, that would be great.  I feel like that is how it used to be, but can't remember for sure.

Thanks!!

**Comment by alex-page** [comment]
This is being tracked in https://github.com/Shopify/polaris/issues/6779. Thanks @camd
