### ISSUE TITLE
[polaris.shopify.com][/foundations] Performance foundations documentation

### ISSUE THREAD

**Issue by chloerice** [Shopify/polaris-react-archive#6817]
@jjgali and @raquelbreternitz are working on guidance for [what makes a quality contribution](https://docs.google.com/document/d/1YYIOZtJtHmS41r_PHYVZZ34HVT0VhfjafZnN6-uFUOM/edit#) in a resource/craft agnostic way. They'll be working on what makes a quality component contribution next, and cross-linking to the existing foundations docs that are relevant to components specifically. We have foundational documentation for a11y and i18n. Let's round out our foundations by documenting performance best practices.

**Comment by raquelbreternitz** [comment]
Wanted to add support for this and point out it would help us round out the foundation columns to be symmetrical 😉
<img width="1200" alt="Screen Shot 2022-08-02 at 1 56 02 PM" src="https://user-images.githubusercontent.com/13204374/182452467-73592b7b-6cb0-4597-8454-8988c84f1f6c.png">
