### ISSUE TITLE
[Icon]: New icon "Express checkout"

### ISSUE THREAD

**Issue by ben10code** [Shopify/polaris-react-archive#6818]
### How will these icons be used?

At Shopify Email, we are introducing a new "Express checkout" section to allow email recipients to quickly checkout via a Shop Pay checkout URL.

<img width="673" alt="Screen Shot 2022-07-29 at 11 44 23 AM" src="https://user-images.githubusercontent.com/59658889/181796018-3ba60e9d-66db-4b61-aecf-a2dca34d4896.png">

<img width="749" alt="Screen Shot 2022-07-28 at 11 12 37 AM" src="https://user-images.githubusercontent.com/59658889/181796108-e24265b8-d873-4593-abf3-322d5689c8af.png">
****

### Icon name

Express checkout

### What type of icon set?

Major (20x20)

### Icon description

**Action**: Used to denote a faster checkout process
**Wayfinding**: Used to help direct merchants to the express checkout section or template.
**Concept**: Used to represent the ability for merchants to activate a faster checkout process for buyers.
**Education**: Used to give merchants more information about the express checkout section or template. 

### Icon keywords

orders, sales, funnel

### Icon SVG code

```shell
<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_359_1801)">
<path fill-rule="evenodd" clip-rule="evenodd" d="M1 1C1 0.447715 1.44772 0 2 0H3.5C4.32843 0 5 0.671572 5 1.5V10H16.1327L17.0101 3.85858C17.0882 3.31184 17.5947 2.93195 18.1414 3.01005C18.6882 3.08816 19.0681 3.59469 18.99 4.14142L18.0513 10.7121C17.9457 11.4511 17.3128 12 16.5664 12H5V14H15C16.6569 14 18 15.3431 18 17C18 18.6569 16.6569 20 15 20C13.3431 20 12 18.6569 12 17C12 16.6494 12.0602 16.3128 12.1707 16H6.82929C6.93985 16.3128 7 16.6494 7 17C7 18.6569 5.65685 20 4 20C2.34315 20 1 18.6569 1 17C1 15.6938 1.83481 14.5825 3 14.1707V2H2C1.44772 2 1 1.55228 1 1ZM14 17C14 16.4477 14.4477 16 15 16C15.5523 16 16 16.4477 16 17C16 17.5523 15.5523 18 15 18C14.4477 18 14 17.5523 14 17ZM3 17C3 16.4477 3.44772 16 4 16C4.55228 16 5 16.4477 5 17C5 17.5523 4.55228 18 4 18C3.44772 18 3 17.5523 3 17Z" fill="#5C5F62"/>
<path d="M9 4.6129L12.9286 0.5L11.5 3.64516H14L9.35714 8L11.1429 4.6129H9Z" fill="#5C5F62" stroke="#5C5F62" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
</g>
<defs>
<clipPath id="clip0_359_1801">
<rect width="20" height="20" fill="white"/>
</clipPath>
</defs>
</svg>
```

**Comment by nblloyd** [comment]
Hi Benny!

Thanks for submitting this icon. I do have a couple questions:

1. Are there other uses for this icon outside of Shopify Email?
2. We already have several shopping cart icons, including the ["quick sale" icon](https://polaris.shopify.com/icons?icon=QuickSaleMajor). Have you seen this icon? And if so, what is the difference in functionality between your proposal for "Express checkout"?

**Comment by ben10code** [comment]
1. No, it is currently only used at Shopify Email. 
2. Actually no! Thanks for sharing. I've just talked to our UX team and we think it's a good fit. 

I will close the issue for now. Thanks so much @nblloyd !
