### ISSUE TITLE
Extraneous content/typos in Polaris naming documentation

### ISSUE THREAD

**Issue by jpat90** [Shopify/polaris-react-archive#6819]
## Issue summary

I was reading through https://polaris.shopify.com/foundations/content/naming as part of my onboarding to content design and notice a lot of typos or content that seems to have been strangely concatenated somehow. Screenshots are attached - I would have fixed this myself but in a some cases it wasn't clear was a sentence was supposed to say.

## Expected behavior

Content should be error-free

## Actual behavior

Distracting content that breaks up the guidelines and sometimes makes it hard to understand the guidance.

## Steps to reproduce the problem

1. Navigate to https://polaris.shopify.com/foundations/content/naming
2.  Read documentation and find content errors

<img width="926" alt="01-23-36uqe-swrha" src="https://user-images.githubusercontent.com/109244435/182231515-8623c8c1-14f7-44fd-8342-270af7704234.png">
<img width="900" alt="01-25-z0bco-snvsw" src="https://user-images.githubusercontent.com/109244435/182231516-a19bf1ba-d42f-4607-8d29-755ff4ff6716.png">
<img width="896" alt="01-26-lk9o9-icx74" src="https://user-images.githubusercontent.com/109244435/182231517-347e508d-67c1-4b35-b2f9-3bad0f201f78.png">
<img width="911" alt="01-26-v74rm-exmir" src="https://user-images.githubusercontent.com/109244435/182231520-a4cfc10f-3b06-4627-8303-48effa2f24a8.png">
<img width="905" alt="01-27-fnmnf-5f7yk" src="https://user-images.githubusercontent.com/109244435/182231521-cc723b67-59d7-4ca4-862d-0c0f25f54c02.png">
<img width="917" alt="01-28-7x2nj-px3ln" src="https://user-images.githubusercontent.com/109244435/182231523-1c4b7463-ec8f-4369-8cfa-aa059b31bfb8.png">
<img width="918" alt="01-29-72z1q-f8xlj" src="https://user-images.githubusercontent.com/109244435/182231525-4e0ef888-832c-425f-aa9f-dfe6930cc962.png">

<img width="921" alt="01-17-e05xc-guhna" src="https://user-images.githubusercontent.com/109244435/182231505-b6356c4d-76c7-4a5a-8614-fbf8bdab0ae5.png">
<img width="927" alt="01-18-knv29-7nfvz" src="https://user-images.githubusercontent.com/109244435/182231508-dc8b3dec-9ed8-4ee0-8eb5-593bbe9160fc.png">
<img width="906" alt="01-19-oo8wz-cmzme" src="https://user-images.githubusercontent.com/109244435/182231510-b6ba6937-e04a-45a7-aa3d-cd36613e5643.png">
<img width="912" alt="01-20-ceba9-llpj6" src="https://user-images.githubusercontent.com/109244435/182231511-860b89cf-559b-4088-b570-cda45e55c42d.png">
<img width="915" alt="01-22-if2j8-qpiva" src="https://user-images.githubusercontent.com/109244435/182231513-acf5ef66-bf8b-41c6-98e7-c0dfacc463fd.png">

**Comment by nblloyd** [comment]
@jpat90 Thanks for finding and reporting this issue! We will take a look and address the various content errors you discovered.
