### ISSUE TITLE
Updates to the video play button

### ISSUE THREAD

**Issue by gladys-ng** [Shopify/polaris-react-archive#6829]
## Feature request summary

Would it be possible to update the video play button to bring it up to date with the current design system while also providing more detailed information to merchants? The current play button is large and in some cases it impacts the visual composition of the thumbnail (see before/after below where the individual in the thumbnail is covered by the play button).

This work comes from [an issue](https://github.com/Shopify/shopify/issues/355172) (https://github.com/Shopify/shopify/issues/355172) on the quality crew project board.

**Feature details:**
- Instead of a large circular play button, the play button will be located on the bottom left of the thumbnail and display the video duration
- There is a mobile and desktop version (which differ only in text styles, `mobile/button` vs `desktop/button`)
- Hit zone for the video would still be the entire thumbnail and not just the play button

[Link to Figma file](https://github.com/Shopify/shopify/issues/355172)

<img width="1420" alt="videobutton" src="https://user-images.githubusercontent.com/50415277/182477320-7ba1b0d5-368d-480b-9ee2-b822eeb36a62.png">

## Rationale

The existing video play button hasn't been updated in awhile and looks out of place compared to the rest of the design system. It takes up a large portion of the thumbnail and in some cases can cover important visuals. The new design keeps the play button contained on the bottom left of the thumbnail and provides useful metadata about the video (i.e. duration) to merchants.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by heyjoethomas** [comment]
Hey @gladys-ng I think this makes a lot of sense. Is your team interested in making this contribution to Polaris-React?

**Comment by gladys-ng** [comment]
@heyjoethomas I'll share with team to see when we can prioritize making this contribution!

**Comment by yurm04** [comment]
Thanks @gladys-ng ! Looking forward to seeing this change make its way into the system. If you or your team need help as you're working on your contribution, please feel free to reach out in the internal #polaris channel. 

Our team has been working on creating new docs to help facilitate contributing changes to the system, if you and your team wouldn't mind having a look as you're working on this we would love any feedback!

https://polaris.shopify.com/contributing

Going to close this issue and look out for that PR in the future ✨
