### ISSUE TITLE
[polaris.shopify.com] Props table feedback

### ISSUE THREAD

**Issue by rajanlagah** [Shopify/polaris-react-archive#6835]
Not able to check all available options for each props.

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by alex-page** [comment]
This is being tracked in https://github.com/Shopify/polaris/issues/6779 thanks @rajanlagah
