### ISSUE TITLE
[polaris.shopify.com] Props table feedback

### ISSUE THREAD

**Issue by rdott** [Shopify/polaris-react-archive#6837]
When a custom type is used in the prop table, like in Stack, there is no visibility into what the custom types are:

<img width="632" alt="Screen Shot 2022-08-03 at 11 43 49 AM" src="https://user-images.githubusercontent.com/40364429/182651427-5f378787-aef5-4409-afc7-27db6565b226.png">

There is no way of seeing what `Spacing`, `Alignment` and `Distribution` are from the site.

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by alex-page** [comment]
Thanks @rdott this is being tracked in https://github.com/Shopify/polaris/issues/6779
