### ISSUE TITLE
[Enablement] Add more App Bridge info in the `What is Polaris` page

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#6863]
Guidance on App Bridge + Polaris is coming soon. Right now, the `What is Polaris` mentions App Bridge in the `Shopify apps` section but doesn't really go into details on Polaris's relationship with App Bridge. Once the App Bridge docs are finalized, let's link out to them and add in a bit more info on the `What is Polaris` page

**Comment by SeanyB** [comment]
Shopify-dev docs [Github issue](https://github.com/Shopify/shopify-dev/issues/24605) to clarify relationship between App Bridge and Polaris.
