### ISSUE TITLE
how to create custom pages in Shopify without using: templates and sections

### ISSUE THREAD

**Issue by talesf15** [Shopify/polaris-react-archive#6869]
My biggest question currently is how can I create custom description on my product pages without using page builders like Shogun, Pagefly, Gempages, etc...How can I create fully custom descriptions without these page builders?

an alternative was to create several templates, but if we have 1000 different products, it will be impossible to create all this from a template, besides it is a lot of work to use those native sections of Shopify. 

Give me some ideas!

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).
