### ISSUE TITLE
Subnavigation items not showing on mobile (regression)

### ISSUE THREAD

**Issue by bhr** [Shopify/polaris-react-archive#6870]
## Issue summary

Sub navigation items are not showing up anymore on mobile layouts (<769px) after upgrading from `@shopify/polaris`  **7.4.0** to **9.20.1**.

The screenshot below shows there's extra padding showing for the selected item ("Products") but the sub navigation items are missing.

Mobile screenshot
<img width="419" alt="mobile" src="https://user-images.githubusercontent.com/557660/183421220-97efcd70-2d88-4f38-a7a0-818421cc6a4a.png">

The behavior is still working as expected on Desktop environments (>=769px).
<img width="238" alt="desktop" src="https://user-images.githubusercontent.com/557660/183421212-e8e2650a-7f13-49d7-8434-7c9ebe96a573.png">

## Expected behavior

Sub navigation items to show up under "Products" on mobile the same way they do on on desktop.

## Actual behavior

See screenshot above.
## Steps to reproduce the problem

1. Open web app
2. Click on hamburger bar
3. Observe that current item is selected, but sub navigation items are missing

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 9.22.0
- Browser: Google Chrome 103.0.5060.134; Safari (iOS) 
- Device: Macbook; iPhone
- Operating System: macOS 12.5; 15.5

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by bhr** [comment]
After a few trial and errors found out that this was a client-side issue. 

For anyone who comes across this issue:
```
 const selected = (path: string) => {
    return path === homePath && asPath !== path ? false : undefined;
  };

  const navigationMarkup = React.useMemo(
    () => (
      <Navigation location={asPath}>
        {navigationSections.map((section) => {
          const items: NavigationItemProps[] = section.items
            .map((item) => {
              const { path, label, global, icon } = item;

              const subNavigationItems:
                | SubNavigationItem[]
                | undefined = !item.subNavigationItems
                ? undefined
                : (item.subNavigationItems
                    .map((subNavItemDefinition) => {
                      const { path, label, global } = subNavItemDefinition;

                      const url = global ? path : `/${shop}${path}`;
                      const subNavItem: SubNavigationItem = {
                        url,
                        label,
                        exactMatch: false
                      };
                      return subNavItem;
                    })
                    .filter(
                      (subNavItem) => !!subNavItem
                    ) as SubNavigationItem[]);
              const url = global ? path : `/${shop}${path}`;
              const navItem: NavigationItemProps = {
                url,
                label,
                icon,
                selected: selected(url),
                subNavigationItems: subNavigationItems,
                exactMatch: false,
                expanded: true
              };
              return navItem;
            })
            .filter((item) => !!item) as NavigationItemProps[];
          if (items.length === 0) {
            return null;
          }
          return (
            <Navigation.Section
              items={items}
              title={section.title}
              separator={section.separator}
            />
          );
        })}
      </Navigation>
    ),
    [asPath, shop, selected]
```

`selected` was missing from the hook dependencies.
