### ISSUE TITLE
[polaris.shopify.com] 404 not found at /examples/data-table-with-fixed-first-column-enabled

### ISSUE THREAD

**Issue by xynja** [Shopify/polaris-react-archive#6871]
There’s no page at this address

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by laurkim** [comment]
Thanks @xynja for reporting this issue! It looks like that example was a duplicate of the `With fixed first column` example and just needed to be cleaned up. PR to fix [here](https://github.com/Shopify/polaris/pull/6872).
