### ISSUE TITLE
[polaris.shopify.com] Date example code does not include month like example rendered

### ISSUE THREAD

**Issue by snaik-nap** [Shopify/polaris-react-archive#6879]
![Screenshot 2022-08-09 191634](https://user-images.githubusercontent.com/109160090/183665497-5949e2ed-af92-47e9-b04f-b071a585edbc.png)
Month is not visible when we copy to vscode

**Comment by alex-page** [comment]
@snaik-nap can you confirm that you are using an `AppProvider` with translations? I think the months strings come from there as they are different in other locales.
