### ISSUE TITLE
Where is the documentation for form layouts?

### ISSUE THREAD

**Issue by asacarter** [Shopify/polaris-react-archive#69]
# Issue summary

On the layout page in the documentation below it states "To lay out form fields, use the layout component.", however there is no example.

https://polaris.shopify.com/components/structure/layout

Is it possible to display two form fields (50% width each) on the same row?

## Expected behaviour

Provide an example on how to lay out form fields.

## Actual behaviour

N/A

## Steps to Reproduce the Problem

N/A

## Specifications

- Polaris version: 1.03
- React version: N/A
- Browser: N/A
- Device: N/A
- Operating System: N/A

**Comment by allanarmstrong** [comment]
I think the documentation is a bit unclear here and they're referring to the FormLayout component https://polaris.shopify.com/components/forms/form-layout. You can display two form fields in the same row with the FormLayout.Group component.

**Comment by asacarter** [comment]
Ah perfect.

It's probably an issue with the link on that page then as it links to itself rather than the form layout page.

**Comment by lemonmade** [comment]
Thanks for the issue. This should indeed be pointing to the FormLayout component, which does support the 50-50 fields you are looking to do. I've added an issue to our internal tracker and will close this one once we've shipped the fix.
