### ISSUE TITLE
[Layout foundations] Update `Columns` component docs and guidance

### ISSUE THREAD

**Issue by laurkim** [Shopify/polaris-react-archive#6906]
Update `Columns` docs

- Description
- Examples: descriptions and visuals
- Add related components section

| Update | |
|---|---|
| Description | Displays content horizontally in one or more columns with equal spacing between. |
| Default example description | By default, there are 6 columns with 16px spacing between them. |
| Spacing example description | Use the spacing prop to set the amount of space between columns. |
| Column width example description | Individual column width can be adjusted. |
| Number of columns example description | Use the columns prop to set the number and width of columns across breakpoints. |
| Related components | For more control over padding and widths, use the Box component|
| | To lay out a set of smaller components horizontally, use the Inline component |

**Before and after**

![Image](https://user-images.githubusercontent.com/99563941/195919808-6d7c877f-0957-42ed-9800-b76510802072.png)

Link to [Figma](https://www.figma.com/file/5oEi1wm73KhGLN0VS02oYm/Layout-components?node-id=2764%3A32219)

**Comment by nayeobkim** [comment]
Update `Columns` docs

- Description
- Examples: descriptions and visuals
- Add related components section

| Update | |
|---|---|
| Description | Displays content horizontally in one or more columns with equal spacing between. |
| Default example description | By default, there are 6 columns with 16px spacing between them. |
| Spacing example description | Use the spacing prop to set the amount of space between columns. |
| Column width example description | Individual column width can be adjusted. |
| Number of columns example description | Use the columns prop to set the number and width of columns across breakpoints. |
| Related components | For more control over padding and widths, use the Box component|
| | To lay out a set of smaller components horizontally, use the Inline component |

**Before and after**

![Image](https://user-images.githubusercontent.com/99563941/195919808-6d7c877f-0957-42ed-9800-b76510802072.png)

Link to [Figma](https://www.figma.com/file/5oEi1wm73KhGLN0VS02oYm/Layout-components?node-id=2764%3A32219)
