### ISSUE TITLE
It is impossible to change the values of the fields, after pressing the arrows (up, down)

### ISSUE THREAD

**Issue by logDmitriy** [Shopify/polaris-react-archive#6911]
## Issue summary
Unable to change field values if you press the (up and down) arrows quickly to change values

https://user-images.githubusercontent.com/56515300/183898821-74a08fac-c83c-41b3-a19c-d64bce8aeba0.mp4

## Expected behavior
With quick mouse clicks on the arrows (up, down) the values should be displayed as they should be  

## Actual behavior
It is impossible to change the values of the fields, after pressing the arrows (up, down)

## Steps to reproduce the problem

1. Create ->tunnel 
2. Go to ->builder
3. Add any widget (where there are these fields), in my case it was "Timer"

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number: 8.2.2
- Browser: Google Chrome, version 104.0.5112.81 (Official Build) (x86_64)
- Device: PC
- Operating System: Windows 11 Pro, version 21H2

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by laurkim** [comment]
Thanks @logDmitriy for opening this issue! We've added the bug label to track it on our backlog. If you feel comfortable submitting a PR to fix this issue, feel free!
