### ISSUE TITLE
Release v9.23.0 is breaking

### ISSUE THREAD

**Issue by weizheheng** [Shopify/polaris-react-archive#6912]
## Issue summary

Getting Failed to compile error on Release v9.23.0

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/40255418/183898585-b0390ce0-6a23-4b3b-a5d4-91bfefdebd20.png">

## Expected behavior

The page should compile without error.

## Actual behavior

Getting Failed to compile error, downgraded to v9.19.0 to make it work again.

## Steps to reproduce the problem

1. Upgrade to version v9.23.0
2. Start the server

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
 System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 109.43 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.asdf/installs/nodejs/16.15.1/bin/node
    Yarn: 1.22.10 - ~/.asdf/shims/yarn
    npm: 8.11.0 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 103.0.1
    Safari: 15.5
```

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by weizheheng** [comment]
Fixed by upgrading typescript version
