### ISSUE TITLE
[Icon]: New icon <fulfillment-fulfilled>

### ISSUE THREAD

**Issue by flaviascudeler** [Shopify/polaris-react-archive#6918]
### How will these icons be used?
The fulfillment team is working on a project to add the **delivery and the fulfill-by dates** on the orders index and the fulfillment card. This project was an excellent opportunity for us to make changes to the fulfillment card that could fit the project scope.
Adding icons next to the metafields is part of several changes the team proposes to improve the card structure and alignment, making the information displayed easier to scan.
[Delivery dates on Figma](https://www.figma.com/file/RhNCFgsmNj0yr8loz9YhdI/Delivery-Date?node-id=0%3A1)

<img width="646" alt="Screen Shot 2022-08-10 at 10 16 48 AM" src="https://user-images.githubusercontent.com/97760490/183975647-a91465cc-ca82-44bb-9c12-ea076c593ec6.png">

### Icon name

fulfillment-fulfilled

### What type of icon set?

Major (20x20)

### Icon description

**Action:** The icon is associated with the 'fulfilled' status.
**Wayfinding:** Used to improve the card structure and alignment, making the information displayed easier to scan.
**Concept:** The base (package) represents _fulfillment_.
**Education:** Used to help merchants easily check the fulfillment date on the fulfillment card.

### Icon keywords

fulfillment

### Icon SVG code

```shell
<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M11 4H19L17.1547 1.42858C16.9634 1.16232 16.6093 0.998786 16.2267 1.00001H11V4ZM9 1.00001H3.77333C3.39074 0.998786 3.03663 1.16232 2.84533 1.42858L1 4H9V1.00001ZM1 6V16.5C1 17.3284 1.67156 18 2.49997 18L8.5 18C9.5 18 10 17 10 17C10.0005 16.4658 10.0032 15.9327 10.0097 15.5C10.0097 11.9159 12.9234 9 16.5048 9H18C18 9 19 9 19 8V6H1ZM19.9983 12.7533C20.0099 12.948 19.9622 13.1412 19.8641 13.2973L16.1262 17.7568C15.8544 18.0811 15.4466 18.0811 15.1748 17.7568L13.1359 15.3243C13.0378 15.1682 12.9901 14.975 13.0017 14.7804C13.0133 14.5857 13.0834 14.4025 13.1991 14.2645C13.3147 14.1265 13.4683 14.0429 13.6314 14.0291C13.7946 14.0152 13.9565 14.0721 14.0874 14.1892L15.6505 16.0541L18.9126 12.1622C19.0435 12.0451 19.2054 11.9882 19.3686 12.002C19.5317 12.0159 19.6853 12.0995 19.8009 12.2375C19.9166 12.3755 19.9867 12.5587 19.9983 12.7533Z" fill="#8C9196"/>
</svg>
```

**Comment by joelzwarrington** [comment]
@flaviascudeler the [CalendarTickMajor](https://polaris.shopify.com/icons?icon=CalendarTickMajor) looks very similar - curious if that icon could be used for your use case.
