### ISSUE TITLE
Setup guide pattern

### ISSUE THREAD

**Issue by selenehinkley** [Shopify/polaris-react-archive#6931]
Hi @madhulikasaxena and @CatherineGroux! The Polaris team uses issues to track our work. This one will simply be added to our [Contribution board](https://github.com/orgs/Shopify/projects/2250/views/81?filterQuery=label%3AContribution) on github. 

Members of the community can join the Github [discussion](https://github.com/Shopify/polaris/discussions/6752) we created for the setup pattern, but we haven't received any postings yet. Feel free to share it if you want to start a conversation with other teams. 😃

[Working draft](https://docs.google.com/document/d/1aTfxOCt14_NAud0xZBDOA8cegtDu1QeRerrwaCqq5NM/edit#heading=h.vxkfd1cy1cdc) of the pattern guidelines.

**Comment by tracytees** [comment]
Update: Scheduled a writing session for next week and hoping to get the guideline closer to being live

**Comment by selenehinkley** [comment]
Update: Draft is coming along nicely and @madhulikasaxena and @trlionheart are pairing this week. Hope is to have a light, shippable version by next week :) Decision made to exclude the implementation details since the Home team will be implementing guides for the foreseeable future.
