### ISSUE TITLE
Resource list documentation bug

### ISSUE THREAD

**Issue by ryancreatescopy** [Shopify/polaris-react-archive#6948]
## Issue summary

The "don't" content guidelines appear outside of the `<!-- dodont -->` component. I've looked at the markdown and it seems to be formulated correctly when compared to other pages where this issue doesn't occur, e.g. Popover. Raising an issue as I'm un aware of how to fix.

<img width="804" alt="image" src="https://user-images.githubusercontent.com/40891631/184333172-b056819a-a27a-40d4-803c-edba36035eb3.png">

## Expected behavior

Content under **Don't** should render in the Don't box alongside the relevant Don't styling.

## Actual behavior
Content under **Don't** renders as regular markdown.

## Steps to reproduce the problem

1. Head to https://polaris.shopify.com/components/resource-list
1. Scroll down to content guidelines

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by ryancreatescopy** [comment]
This appears to be fixed
