### ISSUE TITLE
Empty FormLayout.Item renders unnecessary padding

### ISSUE THREAD

**Issue by lazirpascual** [Shopify/polaris-react-archive#6956]
## Issue summary
When a null or empty FormLayout.Item is passed to the FormLayout component, the FormLayout.Item is rendered with unnecessary padding.

<img width="1547" alt="image" src="https://user-images.githubusercontent.com/70488281/184469569-bf589673-398e-4f8d-9ac7-fc6844e71721.png">

## Expected behavior

The FormLayout component should not be rendering additional padding when an empty or null item is passed.

## Actual behavior

An empty or null FormLayout.Item causes unnecessary padding. However, this only seems to occur when the null FormLayout.Item is followed by a FormLayout.Group, as seen below.

<img width="377" alt="image" src="https://user-images.githubusercontent.com/70488281/184470175-ab516afc-746a-46c6-826a-4178b182fbec.png">

## Steps to reproduce the problem

1. Within a FormLayout component, include an empty/null FormLayout.Item (ie. empty div)
1. Underneath the empty item, add a FormLayout.Group
2. Inside the FormLayout.Group, add a TextField component

## Proposed Solution
Adding a style which removes the padding from an empty/null FormLayout.Item might fix this issue.

<img width="341" alt="image" src="https://user-images.githubusercontent.com/70488281/184470441-7f899c4a-94bf-4dee-9212-8adb5e6b4dde.png">

## Reduced test case

[CodeSandbox test case](https://codesandbox.io/s/shopify-polaris-react-typescript-playground-forked-qzi7lw?file=/src/index.tsx)

This can also be observed by going to my [spin instance](https://shop9.shopify.domains-vbjg.lazir-pascual.us.spin.dev/admin/settings/domains/confirm?host=test-domain-453.com) and clicking the `Edit address` link. The additional padding can be seen between the City/Province/Postal Code and Phone/Fax TextFields.

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).
