### ISSUE TITLE
[polaris.shopify.com] Components not for embedded app use should highlight their App Bridge equivalents

### ISSUE THREAD

**Issue by curtisburns** [Shopify/polaris-react-archive#6957]
Hi @chloerice 

Thanks for getting back to me on #6950

I guess my next question is, as a developer, where am I to be informed that the Polaris modal is being deprecated? I'm aware I need to use app-bridge-react because the old docs warned me about the deprecation. The App Design Guidelines, while the single source of truth, mention nothing about recommending using the app bridge react modal as opposed to the Polaris modal. Does that make sense? The current docs imply that the Polaris Modal is actually fine to use when this isn't the case. Or is it?

Am I missing something?

Thanks.

**Comment by chloerice** [comment]
Hey @curtisburns, deprecation notices eventually get removed as new major versions are released. [v5.0.0 release notes](https://github.com/Shopify/polaris/releases/tag/v5.0.0) as well as the guide for [migrating from v4 to v5](https://github.com/Shopify/polaris/blob/main/documentation/guides/migrating-from-v4-to-v5.md) detail the specifics on how Polaris and App Bridge React should be used going forward.

**Comment by curtisburns** [comment]
Thanks @chloerice. My point is that this isn't reflected in the docs. The example still shows:

```
import {Button, Modal, TextContainer} from '@shopify/polaris'
```

Is this something that should be updated?

**Comment by chloerice** [comment]
Which example are you referring to? We def should update or remove examples that don't reflect the current reality 💯

**Comment by curtisburns** [comment]
It will be the [modal page](https://polaris.shopify.com/components/modal) in the Polaris docs. This is the page that this and the original feedback is in reference to.

**Comment by chloerice** [comment]
The component examples for the Polaris `Modal` are documenting its use. App Bridge is not consumed by the Polaris React library or documented by the Polaris style guide. 

I'm going to open an issue in the App Bridge repo, as I agree there should be clear guidance on [shopify.dev](https://shopify.dev/apps/tools/app-bridge/getting-started/using-react#using-app-bridge-react-with-polaris) for when and why App Bridge components, like [Modal](https://shopify.dev/apps/tools/app-bridge/actions/modal#react), should be used in place of Polaris components.

I'll update this issue's title to reflect our need to call out/link to documentation of App Bridge equivalent components.

**Comment by chloerice** [comment]
Hey @curtisburns 👋🏽 The App Bridge documentation on [shopify.dev](https://shopify.dev/apps/tools/app-bridge) has been updated to make a clearer connection between Polaris and App Bridge. In the next couple months, we plan to merge the Polaris style guide with shopify.dev so that everything is in one place. Hopefully this and the work coming ahead will make things clearer going forward 😊 Let us know what you think!

**Comment by curtisburns** [comment]
Fantastic, thanks @chloerice. Appreciate the update, and I look forward to seeing the continued improvements you guys make!

**Comment by chloerice** [comment]
This is still an issue. As we won't be moving the style guide to shopify.dev any time soon, we should update docs for the Modal and other Polaris React components that are wrapped for use by embedded apps in AppBridge React components.
