### ISSUE TITLE
Allow ID prop for "Choice" in ChoiceList

### ISSUE THREAD

**Issue by LA1CH3** [Shopify/polaris-react-archive#6959]
## Feature request summary

Allow a `Choice` component (radio or checkbox used within `ChoiceList`) to set its own `id` attribute. Currently this is not possible and the ID value is auto-generated. 

## Rationale

`id` prop is valid for individual components like `RadioButton` or `Checkbox` but not when using them within a `ChoiceList`. This would be valuable for testing purposes and/or element tracking, such as with analytics. 

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by kyledurand** [comment]
I think this makes sense. Feel free to open a PR adding an `id` prop on `Choice` within the `ChoiceList` component. I can review for you

**Comment by LA1CH3** [comment]
@kyledurand I've opened a PR ready for review whenever you have time.
