### ISSUE TITLE
[polaris.shopify.com] Multiple list items in table of contents are active at the same time

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#6974]
Example: When any `Components` or `Content` list item is selected in the table of contents on the [Error Messages page](https://polaris.shopify.com/foundations/patterns/error-messages) all items with those names appear active.

My assumption is that identical headlines are causing this issue.

<img width="346" alt="image" src="https://user-images.githubusercontent.com/38329124/185114839-c4b1c5df-eb79-4a60-90da-61536bd28d62.png">

<img width="512" alt="image" src="https://user-images.githubusercontent.com/38329124/185115383-655682d6-5cd6-403e-97ce-24b7a7ccb1c4.png">

**Comment by martenbjork** [comment]
Thanks! Correct assumption. The id generation is naive and doesn't account for multiple, identical headlines.

I spend a few hours working on this, learned about the challenges of generating unique ids in SSR environments, flipped a table and then gave up.

I'll revisit.

**Comment by jjgali** [comment]
Hey @martenbjork! Curious if you've considered revisiting this, as I've seen it come up a few times. Recent example [here](https://github.com/Shopify/polaris/pull/8045), and there's another page I'm working on where this _could_ be an issue down the road.

**Comment by johanstromqvist** [comment]
Thanks bot! Still an issue.
