### ISSUE TITLE
IndexTable non-sense line - Mistake or intention?

### ISSUE THREAD

**Issue by juzser** [Shopify/polaris-react-archive#6988]
Hi,

I see these lines in `IndexTable.tsx` line 254 - 256: 

```
const handleIsSmallScreen = useCallback(() => {
    setSmallScreen(smallScreen);
  }, [smallScreen]);
```

Maybe I mis-understand somewhere but can the author tell me what it does please? 
Will it be fix?

**Comment by chloerice** [comment]
Hey @juzser, that method gets called whenever the window the `IndexTable` is rendered in changes size. The `smallScreen` boolean gets passed to the `BulkActions` component, and when `smallScreen` is `true` `BulkActions` are rendered so they fit on mobile devices.
