### ISSUE TITLE
Add Plain disclosure to the Polaris Figma UI Kit

### ISSUE THREAD

**Issue by idonahue** [Shopify/polaris-react-archive#6989]
## Button - Plain disclosure
Figma UI Kit does not have a **Plain disclosure button** in it. It is a component in Polaris already.

[Link](https://polaris.shopify.com/components/button)
<img width="776" alt="image" src="https://user-images.githubusercontent.com/6720319/185596695-c8517cb5-e89a-4fcf-bbfd-1e411174286a.png">

## Required components
None

**Comment by heyjoethomas** [comment]
This has shipped. Thanks for the contribution.
