### ISSUE TITLE
Selected Tab CSS Class

### ISSUE THREAD

**Issue by johnsonab** [Shopify/polaris-react-archive#7]
# Issue summary

Tabs.scss contains a misspelled CSS class for the selected tab rules. 

## Expected behavior

CSS rules on line 79 and 86 should use `Polaris-Tabs__Tab--selected` to apply the active state border to the active item.

## Actual behavior

CSS rules on line 79 and 86 are using `Polaris-Tabs__Tab-selected` which uses a single hyphen instead of a double when extending the class.

## Steps to Reproduce the Problem

Try to set the active tab when using the tab component inside of any view.

**Comment by lemonmade** [comment]
Thanks @johnsonab. This is the same issue as the one you opened [here](https://github.com/Shopify/polaris/issues/9), so I will close this one in favor of the other.
