### ISSUE TITLE
[polaris.shopify.com] Consider making `alpha` badge more warning-y

### ISSUE THREAD

**Issue by martenbjork** [Shopify/polaris-react-archive#7008]
Via @samrose3 . The current colour might not sufficiently convey the risks of using an alpha component.

The colour choice and banner design should balance these two things:

- New component! Exciting!
- Unstable component! Heads up!

<img width="1571" alt="Screen Shot 2022-08-24 at 10 01 31 AM" src="https://user-images.githubusercontent.com/875708/186470315-36825350-9872-4834-b506-7525a77a5acc.png">

**Comment by chloerice** [comment]
This has been fixed! 

| Light mode| Dark mode |
|--------|--------|
|<img width="575" alt="Screenshot 2023-06-06 at 10 17 49 PM" src="https://github.com/Shopify/polaris/assets/18447883/2e929257-c7d0-48ef-b822-18ddaaeb5f89"> |<img width="577" alt="Screenshot 2023-06-06 at 10 18 10 PM" src="https://github.com/Shopify/polaris/assets/18447883/4d135667-bdb2-4a71-98e3-278c589b7404"> |
