### ISSUE TITLE
[polaris.shopify.com] Props table feedback

### ISSUE THREAD

**Issue by vicvans20** [Shopify/polaris-react-archive#7017]
Props section is missing some props especifications like:
* breadcrumbs
* title
* subtitle
* titleMetadata
* pagination

I know the source code got examples of them, but having all the props for quick reference would be useful.

**Comment by chloerice** [comment]
Hey @vicvans20 👋🏽 Thanks for raising this! There's a fix in progress in #6757. Gonna close this as it's a duplicate of #6779.
