### ISSUE TITLE
Skeleton examples not displayed 

### ISSUE THREAD

**Issue by raphaelghub** [Shopify/polaris-react-archive#7044]
## Issue summary

The `Skeleton` examples are not being displayed in the Polaris docs: 
- [Skeleton body text](https://polaris.shopify.com/components/skeleton-body-text)
- [Skeleton display text](https://polaris.shopify.com/components/skeleton-display-text)
<img width="950" alt="29-24-7vgwk-tx08k" src="https://user-images.githubusercontent.com/9341646/187298823-b953f9d4-e569-42c0-8311-85666271d043.png">

The `div`s seem to have no `width` applied.

## Expected behavior
<img width="963" alt="Screen Shot 2022-08-29 at 17 05 44" src="https://user-images.githubusercontent.com/9341646/187298853-45e70144-4f18-431e-b5e6-25ae0f746488.png">

## Steps to reproduce the problem

1. Navigate to https://polaris.shopify.com/components/skeleton-body-text

**Comment by kyledurand** [comment]
Fixed in https://github.com/Shopify/polaris/pull/7400
