### ISSUE TITLE
[Typography foundations] [Migration] Toasts

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#7047]
**[Figma](https://www.figma.com/file/siMyneYEuULTaNSuRFZAcx/Type-migrations?node-id=29653%3A21166)**

Update `toast` message text to use `variant="bodyMd" weight="medium"`

| Before | After |
| --- | --- |
| `DisplaySmall`<img width="311" alt="Screen Shot 2022-08-30 at 8 55 51 AM" src="https://user-images.githubusercontent.com/8629173/187484329-1b69264e-a5a0-45b9-9cad-97c5c609695b.png"> | `BodyMd–medium`<img width="311" alt="image" src="https://user-images.githubusercontent.com/8629173/187487240-72064574-74a8-4e68-9108-659ae64607f5.png"> |

**Comment by sarahill** [comment]
@jameswfindlater is working on [larger toast updates](https://www.figma.com/file/wgbt21f1PZm5lrUecbB5oY/%F0%9F%8D%9E-Toast-component-rework?node-id=3%3A5). I updated the text to match their work but scoped it to just type for this migration work.

**Comment by laurkim** [comment]
[Commit](https://github.com/Shopify/polaris/pull/7530/commits/3af820e7ced289f0c28546936271448754cd7533) with updates
