### ISSUE TITLE
[Typography foundations] [Migration] Form elements

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#7048]
Figma links:
- **[Text field](https://www.figma.com/file/siMyneYEuULTaNSuRFZAcx/Type-migrations?node-id=376%3A12)**
- [Select](https://www.figma.com/file/siMyneYEuULTaNSuRFZAcx/Type-migrations?node-id=364%3A2186)
- **[Filters](https://www.figma.com/file/siMyneYEuULTaNSuRFZAcx/Type-migrations?node-id=6307%3A12)**
- **[Top bar](https://www.figma.com/file/siMyneYEuULTaNSuRFZAcx/Type-migrations?node-id=434%3A2197)**

I assume any component with an input is probably consuming `TextField` or `Select`. I'm thinking about `Filters`, any search fields, `Combobox`, etc. but correct me if that's not right.

Update any input fields like: `TextField`, `Select`:
- Desktop: variant="bodyMd"
- Mobile: variant="bodyLg" for input text, labels, inline errors, and help text remain variant="bodyMd"

| Before | After |
| --- | --- |
| <img width="363" alt="image" src="https://user-images.githubusercontent.com/8629173/187316470-a2f34288-c62d-4456-a486-c3a13596bd25.png"> | <img width="356" alt="image" src="https://user-images.githubusercontent.com/8629173/187316501-a9fe5d22-f3f0-42f0-8907-638f044e8e1e.png"> |
|![image](https://user-images.githubusercontent.com/99563941/191555675-5bf80125-4d57-4714-9ee1-480100aab782.png)|![image](https://user-images.githubusercontent.com/99563941/191555756-a49a8f8c-2e04-42d6-804c-764cdc7c29ca.png)|

**Comment by laurkim** [comment]
[Commit](https://github.com/Shopify/polaris/pull/7530/commits/6d7a9f007c66709fdccc9a3693e0a44b640d953f) with updates
