### ISSUE TITLE
[Layout foundations] Test implementing `Box` on existing Polaris components

### ISSUE THREAD

**Issue by laurkim** [Shopify/polaris-react-archive#7055]
Explore using `Box` on `Toast,` `Banner`, and `ContextualSaveBar` components.
Add support for props that `Box` is lacking based on explorations.

**Comment by alex-page** [comment]
Before we add color support, I would be curious to implement `Box` as it is across a couple of our components. There is a couple components where we need color e.g. `Toast` and `Banner`. Is there any others?

**Comment by kyledurand** [comment]
Polaris: ContextualSaveBar 
Admin: Custom modals, custom cards, popovers (global search?), global nav. 

We were also thinking about allowing more colors in the `Text` component vs adding a color prop to box though. I feel like a color prop to box would be more natural to me vs using `Text` just to get a lighter color

**Comment by laurkim** [comment]
@kyledurand I chatted with @sarahill about both approaches and we also agreed on it making more sense to add `color` to Box instead of modifying `Text` 👍

**Comment by alex-page** [comment]
I am not against `Text` having color as well. To start feel free to add it to `Box` to start though.

**Comment by alex-page** [comment]
I can imagine `success|error|warning` color being useful in hint text under a text input for example. That shouldn't need `Box`.

**Comment by laurkim** [comment]
`Text` already does have support for color, but we ended up limiting the colors to the 4 that were originally supported on the `TextStyle` component (`success`, `critical`, `warning`, and `subdued`)

**Comment by laurkim** [comment]
Closing this in favor of the [second prototype](https://github.com/Shopify/polaris/pull/7279) where we explored using `Box` in `Toast` without the `className` prop on `Box`. We preferred that prototype over this one due to the complexity that having a `className` escape hatch would introduce to the component.
