### ISSUE TITLE
[utilities] Expose useBreakpoints hook as a named export from polaris-react 

### ISSUE THREAD

**Issue by gwyneplaine** [Shopify/polaris-react-archive#7060]
## Feature request summary
Expose useBreakpoints from polaris-react as a named export. 

```jsx
import { useBreakpoints } from '@shopify/polaris-react'
```

## Rationale
While browsing through polaris.shopify.com I noticed the [`data-table` component example](https://polaris.shopify.com/components/data-table)  `with-fixed-first-columns` leverages a custom `useMedia` hook to evaluate the current breakpoint in order to ascertain whether or not to lock the first column. 

Firstly, the fact that this custom logic doesn't use our breakpoint tokens is not ideal, especially since its an example usage of one of our components on our docs site. 

Secondly, asserting on breakpoints seems like a pretty common usecase, exposing the utility that we use to do this internally is probably a good idea.  This seems like an opportunity to consolidate and reduce the risk of fragmentation in Polaris. Ship the small convenient utility to let Polaris users leverage our code for a banal usecase, and also reduce the risk of people **not** using our breakpoint tokens. 

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s :+1: upvotes to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by alex-page** [comment]
@gwyneplaine I was waiting to get an understanding of where the usage of `useBreakpoints` would be needed. It can be an anti-pattern exposing hooks for breakpoints as teams end up using it instead of CSS. We want breakpoint code to be in CSS. cc @aaronccasanova as we chatted about this a while ago.

I think this is a sensible change but just wanted to share some of the initial rationale behind this API being private.

**Comment by jesstelford** [comment]
> We want breakpoint code to be in CSS.

How do we handle the case where something should be entirely removed from / added to the DOM at certain breakpoints without being able to access the breakpoint values in JS?

Also, it appears to be [possible to access the raw breakpoint token values in JS](https://github.com/Shopify/polaris/blob/main/polaris-tokens/src/metadata.ts#L14) already, so a consumer could duplicate this hook in userland, possibly with bugs. Better to have a blessed API IMO.

**Comment by nickpresta** [comment]
We (Core Optimize) agree with @jesstelford that we'd rather have a specific, blessed way to `useMedia()` for the 5 Polaris breakpoints. I talked to @aaronccasanova about this briefly during the Polaris v10 upgrade in `web`.

The two use cases that specifically come to mind that we've hit/are hitting in `web` today:

1. We need to change a React prop in response to a media query (e.g. number of fixed columns in a data table). We can't do this with CSS at all, unless we:
2. We want to render a totally different tree of components and it would be wasteful/a performance penalty to render both trees, especially when changes in state would cause both to trees to do work. Using CSS to `display: none` one of the trees doesn't really help the "React is doing work" problem.

**Comment by alex-page** [comment]
I am not against this at all. I just want to be clear that adding this means teams will misuse it.

We don't have documentation for hooks today but I do think that documentation around this would help guide teams to use it correctly.

**Comment by aaronccasanova** [comment]
Coming to this discussion a little late (after the Polaris v10 release). I don't have much to add beyond echoing what Alex already mentioned. We intentionally kept `useBreakpoints` private to start knowing (1 there are valid use cases for applying responsive styles in JS and (2 we should have an opinion on the API.

That said, I have no objections to exposing the hook, and in fact think it's a great idea, but agree with @alex-page that we should include documentation strongly encouraging teams to apply responsive styles in CSS.

**Comment by gwyneplaine** [comment]
@aaronccasanova  awesome, thank you for your input 🙏, I'd like to merge in the PR to expose useBreakpoints first. 
Keen to have the wider conversation around that documentation piece (as well as where to document hooks and utilities on the Polaris site too), but that seems like a larger more involved piece with a few more participants 👍

**Comment by gil--** [comment]
Not sure if this is helpful but as a 3p app developer who heavily uses Polaris, I was actually looking for this hook today. My use case is mostly around compacting the UI on mobile. In my case, actual UI changes with insertion of icons or removal of some UI bits:

### Desktop
![CleanShot 2022-09-02 at 11 35 18](https://user-images.githubusercontent.com/3484527/188188190-4749568e-318a-43d2-a605-46159a1c811b.png)

### Mobile
![CleanShot 2022-09-02 at 11 40 28](https://user-images.githubusercontent.com/3484527/188190262-d7e96507-b131-42a9-b57a-cdc802116f7b.png)
