### ISSUE TITLE
[polaris.shopify.com] Feedback (on page /components/callout-card)

### ISSUE THREAD

**Issue by mrkevanlin599** [Shopify/polaris-react-archive#7065]
This is soooo much easier to find things! It's laid out beautifully. My favorite part is the search. I love how big it is and pulls in the right content. Kudos to the team on delivering tremendous value!

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by martenbjork** [comment]
Thanks @mrkevanlin599 ! ❤️ We really appreciate it! 🥹

**Comment by martenbjork** [comment]
Thanks @mrkevanlin599 ! ❤️ We really appreciate it! 🥹
