### ISSUE TITLE
Polaris docs does not list all supported values of prop

### ISSUE THREAD

**Issue by Rafi993** [Shopify/polaris-react-archive#7073]
## Issue summary

Polaris docs does not list all supported values for a prop in the doc. For example in the Text-style component https://polaris.shopify.com/components/text-style#props it says `variation` prop is of type `Variation` but I can't see what `Variant` is. Is it a enum that I need to use or a String that I need to pass? if it is a string what are its possible values ?.
I can't find this info without digging through the source

## Expected behavior

Link to the doc that has detailed about `Variation` type would really help

## Actual behavior

There is no link or explanation on the type used by the prop

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: `@shopify/polaris@10.1.0`
- Browser:
- Device:
- Operating System:

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by alex-page** [comment]
Duplicate of https://github.com/Shopify/polaris/issues/6779

**Comment by martenbjork** [comment]
Like Alex said, this is shipping in the next couple of days 🙂

https://user-images.githubusercontent.com/875708/187868084-bea3db9f-78f6-4a38-a2a4-a9e438618da9.mov
