### ISSUE TITLE
Clicking on the white area of TextField does not focus on it

### ISSUE THREAD

**Issue by renerbaffa** [Shopify/polaris-react-archive#7077]
## Issue summary

Clicking on the bottom area of a text box in the admin doesn't put the cursor focused on it.

## Expected behavior

The white part in the bottom of the TextField should also trigger the focus.

## Actual behavior

<details>
  <summary>Click on the white part of TextField does not trigger focus</summary>
  ![Image](https://user-images.githubusercontent.com/89200205/187660024-72d5a17d-62e8-4d58-a163-a092bbe3bc7a.gif)
</details>

## Steps to reproduce the problem

Render a `TextField` component with the following props and click in the white part of it in the bottom left corner:

```
maxLength={100}
showCharacterCount
multiline={1}
```

## Reduced test case

I've created a codesanbox with the exact same setup as in the project I am working on:

https://codesandbox.io/s/elated-noyce-cuyd4f

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: latest (10.1.0)
- Browser: Google Chrome
- Device: MacBook Pro
- Operating System: Mac OS

**Comment by renerbaffa** [comment]
@sarahill FYI (I was told to tag you)

**Comment by kyledurand** [comment]
For context @sarahill 

https://user-images.githubusercontent.com/6844391/187958519-e89a3fde-fede-43cf-bcbe-59ea82acf262.mp4

Should we move the character count outside of the perceived input? The easy option is to manually focus the input when the character count is clicked but I'm not sure that's the _best_ option
