### ISSUE TITLE
[polaris.shopify.com] Make it possible to explore props interactively, on the Polaris website

### ISSUE THREAD

**Issue by kylebuildsstuff** [Shopify/polaris-react-archive#7098]
Hello,

I noticed with the new docs that info that used to be there is no longer there and it makes it more difficult to use. 

Specifically, with the Stack component there used to be explanations for its spacing, alignment, and distribution props along with their available values and a a brief description of what did what. 

Without those descriptions it's hard to know whether I should use equalSpacing or fillEvenly or fill without manually trying each value myself, whereas before those values were clearly demonstrated within the docs. I find it much easier to see each variations within the demo than having to guess or trial and error every time. 

If possible could we add those explanations/demos back?

https://polaris.shopify.com/components/stack

**Comment by martenbjork** [comment]
Hi Kyle! Thanks for your feedback!

We will build a new props explorer in the coming months that will make it easy to explore the props interactively. I agree, it's great to be able to explore the props without having to get into the code.

Ps. As a stepping stone towards better usability, we're shipping an update next week that makes it easier to see which options are available for the props:

<img width="891" alt="image" src="https://user-images.githubusercontent.com/875708/188269793-9dfcc3b3-671e-4faa-84e4-26547ad66c98.png">

**Comment by carolopolo** [comment]
just made https://github.com/Shopify/polaris/issues/7151 but closing in favour of this one!
