### ISSUE TITLE
ReadMe reverences outdated css file

### ISSUE THREAD

**Issue by JoshHighland** [Shopify/polaris-react-archive#71]
# Issue summary

ReadMe should point to the latest css file (https://sdks.shopifycdn.com/polaris/1.0.3/polaris.min.css). It references https://sdks.shopifycdn.com/polaris/1.0.0/polaris.min.css

## Expected behavior

Latest version should be referenced - https://sdks.shopifycdn.com/polaris/1.0.3/polaris.min.css

## Actual behavior

Outdated version is referenced - https://sdks.shopifycdn.com/polaris/1.0.0/polaris.min.css

## Steps to Reproduce the Problem

Look at ReadMe file

## Specifications

- Polaris version: 1.0.3

**Comment by lemonmade** [comment]
Thanks for the issue, Josh. We've made a change internally that should update the version in the README to match the currently-released version. It should be fixed up once we make our next release.
