### ISSUE TITLE
[polaris.shopify.com] Add search bar to component page

### ISSUE THREAD

**Issue by Rafi993** [Shopify/polaris-react-archive#7101]
## Feature request summary
1. When you visit the page that lists all components https://polaris.shopify.com/components, there is no search bar in the page to search components. There is global search bar but it searches everything bringing other results that I may not want.
2. This feature request proposes adding search bar similar to icons page https://polaris.shopify.com/icons to search only the components

## Rationale
There should be easy for the user to search components page without resorting to global search which brings unwanted results. Local search pattern is used in icons page and should be used in components page too for consistency

**Comment by Rafi993** [comment]
Hi, if this issue is ready for dev I would really like to help.

**Comment by martenbjork** [comment]
Hi Rafi! I agree 100% with everything in this issue! 😊 I'm adding it to the backlog. We're not ready to accept external contributions for the website right now, but the offer is much appreciated! 🙏
