### ISSUE TITLE
need help use Polaris in react 18 

### ISSUE THREAD

**Issue by Sky-bits** [Shopify/polaris-react-archive#7104]
pm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.14.0 || ^17.0.0" from @shopify/polaris@9.22.0
npm ERR! node_modules/@shopify/polaris
npm ERR!   @shopify/polaris@"^9.22.0" from the root project

## Issue summary
Polaris not working with react 18

## Expected behavior
Polaris shoud be  working with react 18

## Actual behavior
not able to install 

## Steps to reproduce the problem

1. create new react project  (react v 18)
1. then try to add the Shopify 

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:  ^9.22.0",
- Browser: Chrome
- Device: HP
- Operating System: Ubuntu 

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Npm 
Paste the results here:

```bash

```

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by martenbjork** [comment]
Hi Sanjay! I don't have a timeline right now, but we hope to support React 18 soon. PR #6743 is ready for review, so hopefully it won't be too long! 🚀

**Comment by Sky-bits** [comment]
@martenbjork   Thanks for your answer 
but can i remove the peer dependency in development   mode ? 
i try with  ` --force, or --legacy-peer-deps`  but still not able to install. 
Any way to use that was good for me.
