### ISSUE TITLE
[Icon]: New icon <ShoppingBag>

### ISSUE THREAD

**Issue by sydturn** [Shopify/polaris-react-archive#7137]
### How will these icons be used?

We intend to start using this icon to represent the merchants' earnings from eligible Shopify purchases: what better way to represent Shopify purchases than the Shopify shopping bag icon?

![image](https://user-images.githubusercontent.com/18585637/189416977-41fa122c-abd3-4f19-8a0e-084693d4e77b.png)
![image](https://user-images.githubusercontent.com/18585637/189417127-f20b120d-f7eb-48b8-8d44-59bf1e9d94e4.png)

Also, the designers noticed it was offered to them as an available icon in FIGMA: 
![image](https://user-images.githubusercontent.com/18585637/189417466-4fe342e8-eb28-47a2-aac8-8953c82eab84.png)

But when I went to implement it in the codebase it noticed it wasn't available in Polaris itself: 
![image](https://user-images.githubusercontent.com/18585637/189417623-263f63bf-76d0-4442-899c-098f1e60f4a0.png)

### Icon name

ShoppingBag

### What type of icon set?

Minor (16x16)

### Icon description

Concept: Used to represent earnings from eligible Shopify purchases

### Icon keywords

shopify, purchases, rewards, shopping, bag

### Icon SVG code

```shell
<svg width="18" height="20" viewBox="0 0 18 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M12.7676 19.952L17.8948 18.6939C17.8948 18.6939 15.6873 3.95728 15.6732 3.85619C15.6592 3.75509 15.5697 3.69899 15.4955 3.69288C15.4218 3.68677 13.9782 3.6651 13.9782 3.6651C13.9782 3.6651 13.0984 2.82135 12.7676 2.50195V19.952V19.952Z" fill="#5C5F62"/>
<path d="M12.2094 2.33332C12.2083 2.33388 11.9827 2.40276 11.603 2.51885C11.5394 2.31555 11.446 2.06559 11.3127 1.81451C10.8829 1.00464 10.2534 0.576375 9.49278 0.575264C9.49165 0.575264 9.49109 0.575264 9.48996 0.575264C9.43708 0.575264 9.38476 0.580263 9.33188 0.584707C9.30938 0.558045 9.28688 0.531938 9.26325 0.506386C8.9319 0.156441 8.50716 -0.014088 7.99803 0.000909693C7.01579 0.0286831 6.03748 0.729129 5.24426 1.97338C4.68619 2.8488 4.26145 3.94863 4.14107 4.80016C3.01312 5.1451 2.22439 5.38618 2.20696 5.39173C1.63764 5.56837 1.61963 5.58559 1.54537 6.11551C1.48968 6.516 0 17.8898 0 17.8898L12.3591 20V2.30833C12.2983 2.31221 12.2437 2.32332 12.2094 2.33332ZM9.35551 3.20596C8.70124 3.40593 7.98734 3.62423 7.27119 3.84309C7.47259 3.08154 7.85458 2.32332 8.32376 1.82618C8.49816 1.64121 8.74231 1.43513 9.03147 1.31737C9.30319 1.87728 9.36226 2.66994 9.35551 3.20596ZM8.01716 0.646364C8.24781 0.641365 8.4419 0.691357 8.60786 0.799118C8.34232 0.935208 8.08579 1.13073 7.84501 1.38569C7.22113 2.0467 6.74294 3.07265 6.55223 4.0625C5.9576 4.24413 5.3759 4.42244 4.84034 4.58575C5.17844 3.02766 6.50104 0.689691 8.01716 0.646364ZM6.10612 9.5222C6.1725 10.5604 8.93865 10.787 9.09392 13.2188C9.21599 15.1319 8.0661 16.4406 6.40934 16.5439C4.42066 16.6677 3.3259 15.509 3.3259 15.509L3.74727 13.7388C3.74727 13.7388 4.84934 14.5597 5.73145 14.5047C6.30752 14.4686 6.51342 14.0059 6.4926 13.6788C6.40597 12.3245 4.15344 12.4045 4.01111 10.1793C3.89128 8.30683 5.13681 6.40935 7.88496 6.23827C8.94371 6.17217 9.48603 6.43935 9.48603 6.43935L8.85764 8.76065C8.85764 8.76065 8.15668 8.4457 7.32576 8.49736C6.10668 8.57346 6.09374 9.33223 6.10612 9.5222ZM10.0087 3.00655C10.0013 2.51552 9.94227 1.83229 9.71049 1.24183C10.4559 1.38125 10.8227 2.2139 10.978 2.71049C10.6905 2.79769 10.3631 2.89768 10.0087 3.00655Z" fill="#5C5F62"/>
</svg>
```

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by kyledurand** [comment]
Hey @sydturn we have some slight concerns with adding our brand to Polaris icons. Is there a need for this icon outside of the web repo? If not then I think we should just add it there for now. I think the main concern would be that adding the icon to this package would encourage 3p devs to use it which, according to our [guidelines](https://shopify.dev/apps/design-guidelines/visual-design#preparing-icon), is not what we want.
