### ISSUE TITLE
[Page] Top and bottom margin/padding differ in Page component

### ISSUE THREAD

**Issue by mbaumbach** [Shopify/polaris-react-archive#7163]
## Issue summary

When using the `Page` component, the top margin and bottom margin differ, with the bottom margin being very small.

## Expected behavior

The top and bottom margin are equal.

## Actual behavior

The bottom margin is much smaller than the top margin and feels like it doesn't have enough "breathing room" from the bottom of the browser.

See comparison in screenshots. Top:

![image](https://user-images.githubusercontent.com/48250/189999035-6ed10257-bdd0-45b6-a421-b69172c70f85.png)

Bottom:

![image](https://user-images.githubusercontent.com/48250/189999072-8ca07d6e-f79d-464b-920c-e8edd11037e8.png)

## Steps to reproduce the problem

1. Create a `Page` component.
2. Add enough children components to make the screen be scrollable.
3. Scroll to the bottom of the screen and notice the bottom margin is very small and differs from the top margin.

## Reduced test case

This [CodeSandbox template](https://codesandbox.io/s/shopify-polaris-react-typescript-playground-forked-1ckmy5) has a reproducible use case. You may need to resize the vertical height of your browser to get it to scroll.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 10.2.0
- Browser: Any
- Device: Any
- Operating System: Any

**Comment by mbaumbach** [comment]
Still relevant

**Comment by kyledurand** [comment]
Are you sure this isn't the intention @mbaumbach? The page component actually doesn't provide any vertical padding and what you're seeing is coming from Layout.Section. The page component is intended to be used along with page header as well which adds some spacing to the top and footer help at the bottom which also adds some spacing. 

This seems more like a pattern question. I'm really hesitant to add bottom spacing to a widely used component. Can you use [Box](https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/Box/Box.tsx) to create padding where you need it?

**Comment by mbaumbach** [comment]
@kyledurand I'm not sure, to be honest. I opened this ticket when I noticed a difference in the padding/margin on the `Page`/`Layout` component back in version 10.2.0.

I mostly notice it in our embedded apps near the bottom of the screen. Like you said it helps when you have a footer help component, but we don't always use those on every page. Perhaps the suggested pattern is to always use a footer help or there's a different pattern intended for pages that don't have a footer help. For simple pages with just Page + Layout + Cards the padding just looks off.

I can definitely understand not wanting to mess with spacing for a heavily used component. :)

**Comment by kyledurand** [comment]
There's also the pattern of having page actions down in the footer so that's another option. If not an option then I think wrapping the page in a Box component that adds paddingBlockEnd should fix it.

I'm going to close this for now. Feel free to ping me if you reopen if you need a hand
