### ISSUE TITLE
[Search] Adding highlighting & UX for empty search view

### ISSUE THREAD

**Issue by tracytees** [Shopify/polaris-react-archive#7165]
During the IA usability interviews, users stated that the empty state for the search feature on the polaris website could be improved. As well, when a user input a term, there wasn't an indication on where that term appeared
A few suggestions were to change the search user experience:
- Top searched instead of empty state
- Suggestions instead of empty state
- Add highlighting for keywords
- Have search comb through the page (e.g. “validate on submit error” is in Error Content page but doesn’t appear when searched")

**Comment by jjgali** [comment]
@martenbjork here's a good summary of the search feedback we received
