### ISSUE TITLE
Use Date Picking as north star pattern page

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#7182]
Status: This is on our roadmap and is planned to ship EOY.

A collaboration with Levon Cross in Core Optimize.

General idea:
- Levon's Date Picking work leverages the structure of our future pattern platform to publish high quality guidance
- The development of our future pattern platform leverages Levon's Date Picking work to output a north star example

**Comment by SeanyB** [comment]
Done. I'll create other issues for any smaller remaining work.
