### ISSUE TITLE
[Typography foundations] [Migration] Action list

### ISSUE THREAD

**Issue by nayeobkim** [Shopify/polaris-react-archive#7192]
**[Figma](https://www.figma.com/file/siMyneYEuULTaNSuRFZAcx/Type-migrations?node-id=254%3A440)**

With updates:
<img width="1997" alt="image" src="https://user-images.githubusercontent.com/8629173/199252936-24d34c00-6ca4-453e-871f-26ae6a518ce5.png">

- Update the top and bottom padding of Action list from 8px to 4px
- Move the divider to above section title when there are multiple sections

| Before | After |
| --- | --- |
| <img width="192" alt="image" src="https://user-images.githubusercontent.com/8629173/199084956-10badea6-692f-4ce9-8752-8cceed5e7f4e.png"> | <img width="192" alt="image" src="https://user-images.githubusercontent.com/8629173/199253042-d1d52c04-3189-4709-9275-9422b36445b8.png"> |

**Comment by laurkim** [comment]
[Commit](https://github.com/Shopify/polaris/pull/7530/commits/06a56465be802eb810683deda43cf2707a65ffd9) to apply these changes
