### ISSUE TITLE
[Typography foundations] [Migration] Description list

### ISSUE THREAD

**Issue by nayeobkim** [Shopify/polaris-react-archive#7197]
**[Figma](https://www.figma.com/file/siMyneYEuULTaNSuRFZAcx/Type-migrations?node-id=53638%3A30406)**

Update titles to HeadingSm:
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/99563941/190510255-ed0b12f1-b28c-410a-bc59-ed75f250673f.png) | ![image](https://user-images.githubusercontent.com/99563941/190510539-02e57d61-8ab7-4d99-92d5-745329cad74d.png) |

**Comment by nayeobkim** [comment]
Update titles to HeadingSm:
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/99563941/190510255-ed0b12f1-b28c-410a-bc59-ed75f250673f.png) | ![image](https://user-images.githubusercontent.com/99563941/190510539-02e57d61-8ab7-4d99-92d5-745329cad74d.png) |

**Comment by laurkim** [comment]
[Commit](https://github.com/Shopify/polaris/pull/7530/commits/9b51fce36770a027b954be72da82b819e21bdf53) with updates
