### ISSUE TITLE
[Typography foundations] [Migration] Drop zone

### ISSUE THREAD

**Issue by nayeobkim** [Shopify/polaris-react-archive#7198]

**Comment by nayeobkim** [comment]
Update the button text style to BodySm-medium

| Before | After |
| --- | --- |
|![image](https://user-images.githubusercontent.com/99563941/190518081-c987223c-4a04-4bcf-9298-ccd0fb175782.png)|![image](https://user-images.githubusercontent.com/99563941/190518119-8f53bed6-b5cb-4923-baff-481003fa1845.png)|

**Comment by sarahill** [comment]
Closing this for now. I think we can follow up as part of component quality for this
