### ISSUE TITLE
[Typography foundations] [Migration] Empty state

### ISSUE THREAD

**Issue by nayeobkim** [Shopify/polaris-react-archive#7199]

**Comment by nayeobkim** [comment]
Update the title of small Empty state to HeadingMd

| Before | After |
| --- | --- |
|![image](https://user-images.githubusercontent.com/99563941/190519528-edb1fafa-5fa4-400f-97c9-055679175e83.png)|![image](https://user-images.githubusercontent.com/99563941/190519551-02be4964-778f-4608-8b98-a651d067e892.png)|

**Comment by laurkim** [comment]
This was updated with the [PR](https://github.com/Shopify/polaris/pull/7546) to add responsive styling to the `headingLg` variant.
