### ISSUE TITLE
[Typography foundations] [Migration] Navigation

### ISSUE THREAD

**Issue by nayeobkim** [Shopify/polaris-react-archive#7205]

**Comment by nayeobkim** [comment]
Updates for small screens:
- Nav item text `BodyLg-medium` for small screens
- Section title text `HeadingSm` for small screens

| Before | After |
| --- | --- |
|![image](https://user-images.githubusercontent.com/99563941/190683272-383f515e-3983-4d4c-a88f-6885aac0d1f5.png)|![image](https://user-images.githubusercontent.com/99563941/190683322-05687001-7a1b-45cd-a792-9b64c7b5c883.png)|

**Comment by laurkim** [comment]
[Commit](https://github.com/Shopify/polaris/pull/7530/commits/3a1df3f4e33c795c9468d152955b81bb088d84b2) with updates
