### ISSUE TITLE
[Typography foundations] [Migration] Option list

### ISSUE THREAD

**Issue by nayeobkim** [Shopify/polaris-react-archive#7206]
[**Figma**](https://www.figma.com/file/siMyneYEuULTaNSuRFZAcx/Type-migrations?node-id=441%3A3720)
- Add more space above section titles when there are multiple sections. Update top padding above section title to 16px instead of 8px
- Update section title color to text-default instead of subdued
- add divider above section title (let me know if this is out of scope, we can leave off the divider if so - I basically did the same thing as action list here)

| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/99563941/190698825-70561dec-922f-426b-b56b-fbbf2a362bfb.png) | <img width="838" alt="image" src="https://user-images.githubusercontent.com/8629173/199306746-2c4e304a-90d0-4e45-a4ea-551e6b5badac.png"> |

**Comment by nayeobkim** [comment]
Update the bottom and top padding to Option list from 8px to 4px
Add dividers between sections in Option lists with sectors

| Before | After |
| --- | --- |
|![image](https://user-images.githubusercontent.com/99563941/190698825-70561dec-922f-426b-b56b-fbbf2a362bfb.png)|![image](https://user-images.githubusercontent.com/99563941/190698878-47c58e1c-8313-4100-b3e5-c5b9fb4abf34.png)|

**Comment by laurkim** [comment]
[Commit](https://github.com/Shopify/polaris/pull/7530/commits/52fbc125361abeaa91bca2fedc6db35d084026b3) with updates
