### ISSUE TITLE
Add migration to increase Layout coverage

### ISSUE THREAD

**Issue by aaronccasanova** [Shopify/polaris-react-archive#7211]
Write a new `@shopify/polaris-migrator` script to increase Layout coverage. The migration should walk the following declaration and apply passing values.
```json
{
    "z-index:",
    "display:",
    "text-align:",
    "position:",
    "align-items:",
    "align-self:",
    "justify-content:",
    "justify-self:",
    "flex:",
    "flex-shrink:",
    "flex-wrap:",
    "flex-grow:",
    "flex-basis:",
    "flex-direction:",
    "order:",
    "display:",
    "grid:",
    "grid-row-start:",
    "grid-row-end:",
    "grid-column:",
    "grid-row:",
    "grid-template:",
    "grid-template-rows:",
    "grid-template-columns:",
    "grid-template-areas:",
    "grid-auto-rows:",
    "grid-auto-columns:",
    "grid-column-end:",
    "grid-column-start:",
    "grid-area:",
    "height:",
    "width:",
    "transform:",
}
```

## Related legacy API

- [`z-index`](https://github.com/Shopify/polaris/blob/main/documentation/guides/legacy-polaris-v8-public-api.scss#L1017-L1025)

## Failing lines

Review failures and determine what is possible to migrate:
- Note values that are easily replaced
- Otherwise, discuss replacement values with team

### Data

- 👉 [`layout` failing lines grouped by property](https://github.com/Shopify/polaris-coverage-shopifycloud-com/blob/get-failing-lines/analysis/grouped-failing-lines-categorized.json#L3-L3013)
- [failing-lines-all.json](https://github.com/Shopify/polaris-coverage-shopifycloud-com/blob/get-failing-lines/analysis/failing-lines-all.json)
- [failing-lines-categorized.json](https://github.com/Shopify/polaris-coverage-shopifycloud-com/blob/get-failing-lines/analysis/failing-lines-categorized.json)
- [grouped-failing-lines-categorized.json](https://github.com/Shopify/polaris-coverage-shopifycloud-com/blob/get-failing-lines/analysis/grouped-failing-lines-categorized.json)
- [sorted-failing-lines-categorized.json](https://github.com/Shopify/polaris-coverage-shopifycloud-com/blob/get-failing-lines/analysis/sorted-failing-lines-categorized.json)

## Related PRs

- #7310

**Comment by gwyneplaine** [comment]
We now have two PRs for migrating `z-index` on web waiting review and merge. 
[The first](https://github.com/Shopify/web/pull/74918) is a variety of "safe" migrations converting standard invocations of `legacy-polaris-v8.z-index` i.e. 
```diff
- z-index: legacy-polaris-v8.z-index(content);
+ z-index: var(--p-z-1) ;
``` 

[The second](https://github.com/Shopify/web/pull/74921/) contains a variety of more complicated migrations.
Case 1 
Invocations of `legacy-polaris-v8.z-index` with the `legacy-polaris-v8.$fixed-element-stacking-order` sass map  
We know the result of these invocations, and those corresponding to a token value are converted.
```diff
- z-index: legacy-polaris-v8.z-index(modal, legacy-polaris-v8.$fixed-element-stacking-order);
+ z-index: var(--p-z-11);
```

Case 2 
Any `legacy-polaris-v8.z-index` invoked within an arithmetic expression. i.e. 
```scss
z-index: legacy-polaris-v8.z-index(content) + 1;
```

These are generally wrapped in a calc (although this may defer on a case by case basis) 
```diff 
- z-index: legacy-polaris-v8.z-index(content) + 1;
+ z-index: calc(var(--p-z-1) + 1);
```

Case 3 
Lastly, any invocations of `legacy-polaris-v8.z-index` with custom sass maps are converted to a `map.get` invocations.
These invocations have their arguments reversed, as `map.get` expects the first argument to be the sass map and the second to be the key (this is inversed in `legacy-polaris-v8.z-index`) 

```diff
- z-index: legacy-polaris-v8.z-index( search-query-container, variables.$stacking-order);
+ z-index: map.get(variables.$stacking-order, search-query-container);
```


Next steps: 

- [ ] Evaluate best steps for coupling `sass-migrator` invocation post codemod. This is to ensure that `map.get` is in scope everywhere we replace `z-index` with it. This may just be a documented additional step for codemod users. 
- [ ] Document the z-index codemod
