### ISSUE TITLE
Add migration to increase Motion coverage

### ISSUE THREAD

**Issue by lgriffee** [Shopify/polaris-react-archive#7213]
Write a new `@shopify/polaris-migrator` script to increase Motion coverage. The migration should walk the following declaration and apply passing values.
```json
{
    "@keyframes",
    "transition:",
    "transition-delay:",
    "transition-property:",
    "transition-duration:",
    "transition-timing-function:",
    "animation:",
    "animation-delay:",
    "animation-direction:",
    "animation-duration:",
    "animation-fill-mode:",
    "animation-iteration-count:",
    "animation-name:",
    "animation-play-state:",
    "animation-timing-function:",
}
```

## Failing lines

[Review failures](https://drive.google.com/file/d/1aIO3Cqafe0vvOLqsZzPGk60u8JXGhWUS/view?usp=sharing) and determine what is possible to migrate:
- Note values that are easily replaced
- Otherwise, discuss replacement values with team

### Data

- 👉 [`motion` failing lines grouped by property](https://github.com/Shopify/polaris-coverage-shopifycloud-com/blob/get-failing-lines/analysis/grouped-failing-lines-categorized.json#L5360-L5618)
- [failing-lines-all.json](https://github.com/Shopify/polaris-coverage-shopifycloud-com/blob/get-failing-lines/analysis/failing-lines-all.json)
- [failing-lines-categorized.json](https://github.com/Shopify/polaris-coverage-shopifycloud-com/blob/get-failing-lines/analysis/failing-lines-categorized.json)
- [grouped-failing-lines-categorized.json](https://github.com/Shopify/polaris-coverage-shopifycloud-com/blob/get-failing-lines/analysis/grouped-failing-lines-categorized.json)
- [sorted-failing-lines-categorized.json](https://github.com/Shopify/polaris-coverage-shopifycloud-com/blob/get-failing-lines/analysis/sorted-failing-lines-categorized.json)

**Comment by jesstelford** [comment]
Work has begun in the `migration-motion` branch.
