### ISSUE TITLE
[polaris.shopify.com] Broken color token previews in Firefox

### ISSUE THREAD

**Issue by SB3K** [Shopify/polaris-react-archive#7236]
## Issue summary

Some of the color tokens on the Polaris website seem to be incorrect when viewing on Firefox. For example, --p-border-success shows as gray and --p-border-critical shows as white.

## Expected behavior

The color sample should be correct.

## Actual behavior

See images for examples.
<img width="490" alt="image" src="https://user-images.githubusercontent.com/1351015/191346922-e7f27d98-4780-44c9-b35f-be57d9c0e2fc.png">
<img width="518" alt="image" src="https://user-images.githubusercontent.com/1351015/191346977-0bdce07b-ab52-4a9f-8950-361fa1b57535.png">

## Steps to reproduce the problem

Visit https://polaris.shopify.com/tokens/colors

## Specifications

Using Firefox on Mac.

**Comment by martenbjork** [comment]
Thanks for reporting! 🙌 Added to the backlog.
