### ISSUE TITLE
Media Query tokens can not be represented with node-sass's default precision

### ISSUE THREAD

**Issue by BPScott** [Shopify/polaris-react-archive#7237]
## Issue summary

polaris-tokens specify media query sass variables in https://unpkg.com/browse/@shopify/polaris-tokens@6.0.0/dist/scss/media-queries.scss. The down/range media queries do a thing where they get their value by doing [`ROUND_NUMBER_IN_PIXELS - 0.05`](https://github.com/Shopify/polaris/blob/2fec9611dec0a147be0be0410e955e92c025edc0/polaris-tokens/src/utilities.ts#L212-L220). For instance `$p-breakpoints-md-down: '(max-width: 47.996875em)';` comes from `(768px - 0.05px) / 16`.

These values require a precision of 6 (i.e. 6 numbers after the decimal point) to be accurately represented.

However `node-sass`'s default value for [numeric precision is 5](https://www.npmjs.com/package/node-sass#user-content-precision). This means when these values are used [in polaris-react's own css output the precision is lost](https://unpkg.com/browse/@shopify/polaris@10.3.1/build/esm/styles.css#L3467) - the compiled css is `max-width: 47.99688em`, not `max-width: 47.996875em`.

`Web` also uses the default precision, so usage of the media tokens results in lossy precision in web too.

### Expected behaviour

I'd expect that polaris-react, and other tools that use these media query tokens can use them accurately.

#### Leave the value alone, increase precision

polaris-react and any app that uses polaris-tokens should either:

- Add `precision: 10` to their sass options when compiling with sass
- Migrate to use `embedded-sass` - the modern, not-deprecated sass, that hardcodes a precision of 10

Both of these approaches require developer education, letting people know that their set up might not result in exact values, and teach them how to fix that. There is a case where `polaris-react` updates their precision, and a consuming app does not, and thus we end up with two slightly different media queries in compiled code between css from polaris and where the consumer uses the media tokens in their own css file.

#### Tweak the media tokens to be exactly representable with a precision of 5 or less.

Adjusting the [reduction](https://github.com/Shopify/polaris/blob/2fec9611dec0a147be0be0410e955e92c025edc0/polaris-tokens/src/utilities.ts#L212-L220) from `-0.05` to `-0.04` shall result in values that require at most 4 digits of precision. `$p-breakpoints-md-down: '(max-width: 47.996875em)';` would become `$p-breakpoints-md-down: '(max-width: 47.9975em)';` (math stats: 0.04px = 0.0025em aka 1/400th of an em, while 0.05px = 0.003125em)

This would allow for these numbers to be representable with node-sass's default precision. We wouldn't need to teach consumers anything. Personally I would lean towards this option. I am aware that "please adjust your media queries by 0.01px" is a very silly request.

### Ben, how the hell did you find this pettiness anyway?

@royleejr has been looking at migrating web to use `embedded-sass`. When comparing before and after build output he found that several files were changed. We tracked the change down to polaris's media queries changing from `47.99688em` to `47.996875em` etc thanks to thanks to the change in precision from node-sass to embedded-sass (from 5 to 10) causing the change in the breakpoint value precision.

**Comment by aaronccasanova** [comment]
> #### Tweak the media tokens to be exactly representable with a precision of 5 or less.
> Adjusting the [reduction](https://github.com/Shopify/polaris/blob/2fec9611dec0a147be0be0410e955e92c025edc0/polaris-tokens/src/utilities.ts#L212-L220) from -0.05 to -0.04 shall result in values that require at most 4 digits of precision[...]

I too prefer this resolution. IIRC @lgriffee and I achieved the same outcome by offsetting `down` conditions by `-0.02px` and semi-arbitrarily used `-0.05px` as a "safe" value (referencing other design systems).
