### ISSUE TITLE
[polaris.shopify.com] Props table feedback

### ISSUE THREAD

**Issue by HridyaC** [Shopify/polaris-react-archive#7246]
Hi, infinite scrolling option could be a good feature. Horizontal scrollbar should appear on same window as table. User could scroll horizontally without scrolling the page. And table needs vertical scroll with infinite scrolling. fixed no of rows will visible at first and while scrolling another set of data should appear with skelton. By this a user can view bulk data without loading whole data at first.

For reference, visit these links:

- https://codesandbox.io/s/w3w89k7x8

**Comment by martenbjork** [comment]
Thank you, we'll take this into consideration in the future, but it's not planned right now.
