### ISSUE TITLE
Example EASDK code sample issues

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris-react-archive#73]
# Issue summary

Shopify points out code like this in the docs here 

    import {EmbeddedApp, Alert, Modal} from @shopify/polaris/embedded
    import * from @shopify/polaris/embedded

Not sure why, as that code flops out with Webpack...

## Expected behavior

Webpack should compile statements like this and work. 

## Actual behavior

Webpack does not like them. It prefers:

import {EmbeddedApp, Alert, Modal} from '@shopify/polaris/embedded'

ERROR in ./app/javascript/packs/hello_react.jsx
Module build failed: SyntaxError: Unexpected token (23:40)
import {EmbeddedApp, Alert, Modal} from @shopify/polaris/embedded
------> does not like the no quotes or asterisk business...
## Steps to Reproduce the Problem

1. Paste Shopify example code into a Shopify sample project.
2. Fire up webpack-dev-server

## Specifications

- Polaris version: latest
- React version: good
- Browser: WWW
- Device: computer
- Operating System: macOS

**Comment by lemonmade** [comment]
Thanks for the issue, you're definitely right that the code is invalid. We'll get that fixed up ASAP, along with your other issue, and I'll close this issue once we've shipped the next release.

**Comment by lemonmade** [comment]
Should be fixed by v1.1.0
