### ISSUE TITLE
[IndexTable] Scrollbar doesn't appear until window is resized

### ISSUE THREAD

**Issue by lhoffbeck** [Shopify/polaris-react-archive#7307]
## Issue summary

In some cases, the IndexTable scrollbar is not initialized on pageload and only appears after the window has been resized:

https://user-images.githubusercontent.com/3619012/193130236-cbe64432-ae49-4955-934c-3700e04cf967.mp4

From sniffing the html, it seems like the issue is that the `--pc-index-table-scroll-bar-content-width` property isn't initialized until a resize happens:

**before resizing:**
<img width="1467" alt="Screen Shot 2022-09-29 at 4 02 56 PM" src="https://user-images.githubusercontent.com/3619012/193130725-67b93fbf-5abd-4deb-834d-22370b369e04.png">

**after resizing**
<img width="1569" alt="Screen Shot 2022-09-29 at 4 04 00 PM" src="https://user-images.githubusercontent.com/3619012/193130940-8b2e63a9-da12-4fb7-baf5-daae22da506c.png">

## Expected behavior
IndexTable scroll bar appears on pageload

## Actual behavior
IndexTable scroll bar doesn't appear on pageload until the window has been resized

## Steps to reproduce the problem

1. On a product details page, add a number of variant options so the index table view appears
1. Reload the page

**Comment by ghost** [comment]
This [Zendesk ticket](https://shopify.zendesk.com/agent/tickets/33206844) is related to this issue.

**Comment by jshessel-shopify** [comment]
Hey friends. I've also got a second ticket here related to this issue.

[Zendesk Ticket](https://shopify.zendesk.com/agent/tickets/33319596)

[Video capture of the behaviour](https://screenshot.click/04-22-91911-22568.webm).

**Comment by Tonks01** [comment]
Hi team, 

One more for you here:

[Internal](https://app.shopify.com/services/internal/shops/4875421)
[Ticket](https://shopify.zendesk.com/agent/tickets/33386745)

[![alt](https://screenshot.click/05-59-qs4rr-5fl5n.png)]()

Take it easy!

**Comment by angelshek** [comment]
Hi team, I got directed here by the #shopify-web team. The merchant is experiencing a scrollbar issue on the order page. 

Ticket: https://shopify.zendesk.com/agent/tickets/33413787
Internal: https://app.shopify.com/services/internal/shops/51196887206
Recording: https://screenshot.click/06-28-91136-19048.webm

**Comment by BPScott** [comment]
Looks like initialisation of the IndexTable scrollbar is part of the "support React 18 in polaris PR" which is not yet merged - https://github.com/Shopify/polaris/pull/6743/files#diff-f6cb4e5d74c6a93ab30c612e372af0addc595731b01607a4fd90cb5406cef263

**Comment by chloerice** [comment]
The fix for this bug has been shipped and released, just awaiting [upgrade in web](https://github.com/Shopify/web/pull/75145).
