### ISSUE TITLE
Add a set of marketing attribution model icons to the Polaris icon library

### ISSUE THREAD

**Issue by SereneChen-7** [Shopify/polaris-react-archive#7346]
Hey team! Our team - Marketing Insights are working on a new marketing attribution report where merchants would be able to select different attribution models. 

We're proposing to add a new set of icons for different attribution models to help merchants better understand how each model assigns credit. 

<img width="1649" alt="image" src="https://user-images.githubusercontent.com/60230287/194119874-3b59753f-789a-48de-89d0-bd0c43aa80b8.png">

Adding the link to the new branch created in Polaris icon library: https://www.figma.com/file/mMHFt3kEDNjLMZWowi6gnt/branch/jjutZi6iaUc4vQd3Vx3oSh/Polaris-Icons?node-id=6%3A567

Currently under review by @heyjoethomas 
cc @alisonmunngarcia @kyledurand

**Comment by kyledurand** [comment]
I'm assuming these were added to the UI kit but was there also a PR to add them to the `polaris-icons` package?

**Comment by heyjoethomas** [comment]
Yes these have been added to the UI Kit

**Comment by kyledurand** [comment]
Thanks Joe, do you know if anyone one is working on adding them to the codebase?

**Comment by heyjoethomas** [comment]
I don't. Sent Serene the docs for contributing to code but not sure who on
their team is going to handle it.

**Comment by kyledurand** [comment]
👍 Let me know if you need a hand with that @SereneChen-7
