### ISSUE TITLE
Index filtering & search [NEW]

### ISSUE THREAD

**Issue by davidlng** [Shopify/polaris-react-archive#7356]
## Index filtering and search (New component)

The new index filtering and search will be used as the new way of viewing indexes across Shopify. This new index pattern helps merchants focus in on the work that they're doing via a single index control bar where they can switch views, create views, sort, search, and filter.

## Examples

> ### Index filtering and search (default view)
>
> <img width="767" alt="image" src="https://user-images.githubusercontent.com/77809256/194131109-971ace1d-e583-4e28-a96d-dc68d04c744e.png">

>### Index filtering and search (search & filter view)
>
> <img width="805" alt="image" src="https://user-images.githubusercontent.com/77809256/194132430-df254ea5-f44d-46a9-94f3-b107d789cd40.png">

## Best practices

The index filtering & search component should:

- Be used in scenarios when merchants need to manage large quantities of information.
- Be used when merchants need to search & filter large amounts of information.
- Be used when merchants could have multiple views to a single table/pieces of data.

## New Subcomponents

This component will include:

### Search & filter controls (To be added into Polaris)

The search and filter controls is to be used as the control layer of the new index filtering & search experience. This control layer manages the view of the index it is attached to, giving merchants a single focused work surface for their indexes.

> **Search and filter controls**
>
> <img width="987" alt="image" src="https://user-images.githubusercontent.com/77809256/194132218-0d6eafde-25dd-47e9-9840-c7eed7170aec.png">

### Filter tags (To be added into Polaris)

Filter tags to be used in order to help merchants narrow down the information within a specific view.

> **Filter tags (in context of S&F controls)**
> <img width="770" alt="image" src="https://user-images.githubusercontent.com/77809256/194340368-cda95041-da64-4352-ba2e-4e597c2615bc.png">
>
>**Filter tags**
> <img width="573" alt="image" src="https://user-images.githubusercontent.com/77809256/194342284-a2b742bc-0fdd-43a5-a2b7-6b2620ef6050.png">

### Bulk actions bar (To be added into Polaris)

Bulk actions bar to be used when a merchant selects multiple index items at a time. 

>**Bulk actions bar**
> <img width="699" alt="image" src="https://user-images.githubusercontent.com/77809256/194134085-47ca280d-cf8f-44ff-b842-c55a4a461c45.png">

### Kanban columns (To be added into Polaris)

Kanban style columns when teams want to allow merchants to edit the ordering of the columns within their index tables.

>**Kanban columns**
> <img width="743" alt="image" src="https://user-images.githubusercontent.com/77809256/194140333-4e6f25d5-ea90-48fd-9d52-ccaab38723d2.png">

**Comment by dGoligorsky** [comment]
The sortable column header variants are the only change to the table itself 
(in `Assets/Cell/Header cell` on the `Index Table` page)

**Comment by dGoligorsky** [comment]
Hey @heyjoethomas 
Just wanting to touch base on [the Index table branch for the Polaris Admin Web UI Kit](https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/branch/DFeUKUVMNLbluFMsfqd8Mz/Polaris-Components?node-id=44707%3A19512&viewport=220%2C152%2C0.36).

@gladys-ng and @davidlng  have gotten all the updates and new bits into the branch. Covers large and small screens.
We have time set up later this week with @zakwarsame (FED on Quality Crew) to review the naming so our React and Figma component naming is aligned.

Questions:
- Wasn’t quite sure if the Bulk actions bar should be under `Assets/` (tagged you in the file.)
- Not sure how the Polaris team handles discrepancy between what's in production, and what is the latest design. For example, the updated filter badges are our path moving forward, but no code has been written to implement them yet. The rest of the Index table work is getting close to ship to production.
- Is there anything you'd recommend we do to help ensure that team's files are minimally messed up by updating to these new components?

**Comment by heyjoethomas** [comment]
1. Assets subfolder seems good to me
2. When it doubt, match prod. It just makes everything a lot easier. If you haven't even started work on it yet + code freeze & holidays it may be a while before that actually makes it out. So I would probably say leave it to match prod. However, you can keep what you have built by adding a . before the component name. That will actually hide it from being published. So making the swap when ready will be faster.
3. Since these are all net new components, I wouldn't think there is any risk. However, testing locally within the branch is always a good idea if components are being overridden to make sure things don't break.

**Comment by dGoligorsky** [comment]
Just jotting down a little status update here, cc: @gladys-ng @davidlng 

- We decided to make the index table component a bit more complete. We're including the header, which has either the view mode or the search/filter mode.
- The index table component is getting built out with multiple variant states: default, with pagination, column-reordering mode, and with bulk actions active.
- The timeline to publish these UI Kit updates can be in line with shipping the index table to production. The first cohort will launch in early December (5th?) 

## To do still—

- [x] Index table variants for bulk action mode
- [x] Index table variants for column-rearranging mode
- [x] Index table variants for mobile
- [x] Include filter badge components for the first cohort rollout (and `.` ignore the fast follow filter badges until those get to production)
- [x] Make sure all the index filtering components are built w/ autolayout and test positioning constraints
- [x] Review with @heyjoethomas 
- [ ] Celebrate 🎉
