### ISSUE TITLE
[Tag] Add ability to use different colors between states

### ISSUE THREAD

**Issue by HridyaC** [Shopify/polaris-react-archive#7383]
Tag component need  more props. To differentiate clicked/hovered/focused tag,  "color" prop needs to be implemented.

**Comment by martenbjork** [comment]
Hi! Thanks for the feedback! The polaris library typically doesn't offer the ability to change styling between states. We are more opinionated around styling. If you want to use Polaris while having more flexibility, I recommend diving into our tokens which allow you to use official Polaris color to build custom solutions. https://polaris.shopify.com/tokens/colors
