### ISSUE TITLE
TextField maxHeight is not working

### ISSUE THREAD

**Issue by teru-mi** [Shopify/polaris-react-archive#7392]
## Issue summary

TextField maxHeight is not working when multiline is true.

## Expected behavior

It should multiline and maxHeight work together.

## Actual behavior

- multilline is not 4. But looks like 2.
- maxHeight's limit is not working. I can make new lines more than 4. 
```
   <TextField
              label='Additional Description'
              maxLength={140}
              showCharacterCount
              multiline={true}
              maxHeight={4}
    />
```
<img width="663" alt="スクリーンショット 2022-10-13 17 07 39" src="https://user-images.githubusercontent.com/74748029/195539515-5a0138a2-d800-4c7b-acd3-1d1c3a70cfcb.png">

When it's without maxHeight.
```
   <TextField
              label='Additional Description'
              maxLength={140}
              showCharacterCount
              multiline={4}
    />
```
<img width="726" alt="スクリーンショット 2022-10-13 17 10 27" src="https://user-images.githubusercontent.com/74748029/195540392-27c6ac32-77d7-4cfb-b7bf-7e8a004bd136.png">

## Reduced test case

https://codesandbox.io/embed/pedantic-banach-ljejik?fontsize=14&hidenavigation=1&theme=dark

## Specifications

- Are you using the React components? (Y/N): YES
- Polaris version number: "@shopify/polaris": "^10.7.0"
- Browser: Chrome
- Device:
- Operating System:

**Comment by chloerice** [comment]
Hey @teru-mi 👋🏽 The `maxHeight` prop doesn't corrolate to the number of lines set on `multiline`, you need to pass in a CSS value (e.g., `100px`, `4rem`).
