### ISSUE TITLE
[polaris.shopify.com] Examples viewer is too small, can't render full size version of components

### ISSUE THREAD

**Issue by JeaneC** [Shopify/polaris-react-archive#7460]
On my screen size, and testing a variety of screen sizes, it will always reach the one-dimensional breakpoint on full screen for me for the examples. When I went to the codesandbox did I finally see the examples of multi-dimensional layout.

![Screen Shot 2022-10-19 at 6 30 41 PM](https://user-images.githubusercontent.com/25225547/196816871-ef5dca8d-b506-46c3-b3bd-60f1d689c598.png)

**Comment by martenbjork** [comment]
Hi! Thanks! You're right, this is a design flaw on our end. Adding to backlog!
