### ISSUE TITLE
Unblock usage of `stylelint --fix`

### ISSUE THREAD

**Issue by sam-b-rose** [Shopify/polaris-react-archive#7476]
Setup current Sass migrations to be easily portable to `stylelint-polaris` for using the `--fix` flag. 

- [x] https://github.com/Shopify/polaris/pull/7499
- [x] https://github.com/Shopify/polaris/pull/7541
- [x] https://github.com/Shopify/polaris/pull/7532
- [x] https://github.com/Shopify/polaris/pull/7543

**Comment by jesstelford** [comment]
There now exists a `createSassMigrator` factory function which gives us ~90% compatibility with `stylelint --fix`.
