### ISSUE TITLE
Add Cancel major icon and deprecate mobile icon version

### ISSUE THREAD

**Issue by anthonymenecola** [Shopify/polaris-react-archive#7490]
## Feature request summary

- [ ] Add `CancelMajor` icon version for `Cancel small` equivalent
- [ ] Rename `Cancel small` to `CancelMinor`

## Rationale

- Inconsistency in major/minor versions of the Cancel icon, as well as a legacy mobile-only version

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s :+1: upvotes to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by sarahill** [comment]
Figma branch with the update to the name is merged. Let me know when you're ready to merge in the PR and we'll publish the change in Figma. Also let me know if you need help with the PR :) Thank you!
