### ISSUE TITLE
[Icon]: New icons <Inactive location>

### ISSUE THREAD

**Issue by ShaniqueS** [Shopify/polaris-react-archive#7502]
## New Icon summary

We're merging the deactivated and active locations lists on the Locations settings page, so we're aiming to add a new icon to Polaris that can be used for locations that have been deactivated. This icon will allow merchants to easily scan and know what locations aren't in use across their store. 

_This icon is live in the admin, but we'd like to officially add it to polaris._

<img width="726" alt="Screen Shot 2022-10-25 at 11 17 29 AM" src="https://user-images.githubusercontent.com/38759914/197813773-581cc5b2-c4af-4df5-8b88-36d2fae1bdb1.png">

## Icon name
Inactive location

## What type of icon set?
Both Major and Minor

## Icon SVG code

**Inactive location Minor SVG:** 
![locations-inactive_minor](https://user-images.githubusercontent.com/38759914/197809245-8e4ddb67-6084-4bf2-9482-250cd5d0a47b.svg)

**Inactive location Major SVG:** 
![location-inactive_major](https://user-images.githubusercontent.com/38759914/197809931-df974a31-d662-402b-9fc9-9fddb6fcfe96.svg)

**Comment by rdott** [comment]
Example PR: https://github.com/Shopify/polaris/pull/7548
