### ISSUE TITLE
Help developers in VS Code with guidance for failures and warnings

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#7506]
https://github.com/Shopify/polaris/issues/7506#tasklist-block-0f890fe5-5ca4-4ffe-963a-a22fec527bb9

| VS Code Example | Website Example |
| --- | --- |
| ![Image](https://user-images.githubusercontent.com/11774595/207078652-e23b1c56-6b63-4ba8-81eb-6d836ffc84a2.png)  ![Image](https://user-images.githubusercontent.com/11774595/207079449-38744759-8af7-4040-b573-0e35e5179953.png) | ![Image](https://user-images.githubusercontent.com/11774595/207078815-5c9f18fa-84a2-4594-8fd3-b19552c6d29a.png) |

**Comment by sophschneider** [comment]
Does this mean:
* the linter error output?
* the underline popover thing in VSCode?
* the quick fix option in VSCode?
* the `--fix` option on stylelint
* the coverage site?
* links to documentation?

**Comment by sophschneider** [comment]
https://stylelint.io/developer-guide/formatters/ can help us write meaningful error message

**Comment by alex-page** [comment]
@sophschneider Added some clarity around the steps

**Comment by chloerice** [comment]
I've got a [PR](https://github.com/stylelint/stylelint/pull/6463) up in the Stylelint repo extending the [recently added](https://github.com/stylelint/stylelint/pull/6312) support for message arguments for
- declaration-property-value-disallowed-list
- declaration-property-unit-disallowed-list
- function-disallowed-list
- at-rule-disallowed-list
- property-disallowed-list

This will allow me to add helpful custom messages alongside autofixes. Will pair with @aaronccasanova to add a patch to our repo in the interim of their next release.

**Comment by sam-b-rose** [comment]
For the coverage rules where we are leveraging Stylelint built-in rules, is it possible to pass along the URL link to the Stylelint rule docs. Could we also leverage the `--fix` option for those rules? 🤔 

This applies mostly to coverage rules like`color-no-hex` and less so to more custom rules like `custom-properties-allowed-list`.

**Comment by aaronccasanova** [comment]
> Could we also leverage the `--fix` option for those rules?

Yes, support for autofixing built-in and custom rules was added here: https://github.com/stylelint/stylelint/pull/6466
