### ISSUE TITLE
Fix failures or add ignore comments in `shopify/polaris`

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#7508]
- [x] Fix or ignore `stylelint-polaris/coverage/motion` failures (0 failures)
- [ ] Fix or ignore `stylelint-polaris/coverage/depth` (4 failures)
- [ ] Fix or ignore `stylelint-polaris/coverage/mediaQueries` (7 failures)
- [ ] Fix or ignore `stylelint-polaris/coverage/spacing` (12 failures)
- [ ] Fix or ignore `stylelint-polaris/coverage/legacySass` (13 failures)
- [ ] Fix or ignore `stylelint-polaris/coverage/typography` (34 failures)
- [ ] Fix or ignore `stylelint-polaris/coverage/shape` (191 failures)
- [ ] Fix or ignore `stylelint-polaris/coverage/colors` (240 failures)
- [ ] Fix or ignore `stylelint-polaris/coverage/conventions` (249 failures)
- [ ] Fix or ignore `stylelint-polaris/coverage/layout` (1678 failures)

**Comment by qt314** [comment]
## depth
* not allowed to use `dropShadow` function
  * Solution: TODO

## mediaQueries


## spacing
* Disallowed value (—p-button-group-item-spacing, —p-choice-margin, —p-text-field-spinner-offset)
  * Solution: TODO
* Disallowed function (control-vertical-padding)
  * Solution: TODO

## legacySass

## typography
* Invalid @inlcude rule (text-break word, text-emphasis-normal, truncate, etc.)
  * Solution: TODO

## shape

## colors

## conventions

## layout

**Comment by sophschneider** [comment]
Audit of current failing rules and guidance on whether to fix or ignore: https://docs.google.com/spreadsheets/d/1TYRr_pQkTnXwHvyKEtQEhGTtYfpvKtbvOH_yavjJIF4/edit#gid=419562751
