### ISSUE TITLE
Update cron job so it can be ran any time with a commit and workflow dispatch 

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#7517]
- [x] This should fetch the latest commit from the repos in the config file
- [x] Developers should be able to run a CLI script locally to get a specific repo/commit's data
  - This CLI should be used in the workflow dispatch see screenshot below  
- [x] Developers need to be able to trigger a workflow dispatch in the `polaris-coverage-next` repository.

![Screenshot 2022-11-07 at 9 24 41 AM](https://user-images.githubusercontent.com/19199063/200374978-e4796311-cbb0-4d83-9ab0-437ffe681e0e.png)

**Comment by tmlayton** [comment]
Does this mean running for each new commit to `main` for all tracked projects? Do we want to make this change to the current site or only for the new site?

**Comment by alex-page** [comment]
@tmlayton Updated the issue description. This was super confusing before. Let me know if that is clear.

**Comment by tmlayton** [comment]
This is now closed. The get-data workflow can be run on a specific repo and branch to refresh only that repo’s data. We will also add a refresh button to each repo on the coverage site to dispatch the action from there.

<img width="353" alt="Screenshot 2022-11-16 at 10 58 28 AM" src="https://user-images.githubusercontent.com/344839/202270714-d67bde41-d92c-408d-8564-cefe7393609c.png">

For devs wanting data for a specific commit their workflow would be to: 

1. push changes to a branch 
2. push branch to remote
3. pull this project down locally
4. run `yarn get-data --repo=shopify/some-repo --branch=my-feature --clearcache`
5. run the coverage site locally
