### ISSUE TITLE
Group coverage failures for better discovery e.g. find all color issues

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#7518]
When using the code browser it would be powerful if teams could filter issues based on what they are addressing. e.g. fixing all color issues. To do this the scripts will need to group together `pass/fail/warn` of these categories and expose them to the files.

```
[filename]: {
   color: { warn: [10, 11, 12], fail:[15], pass:[3,4]}
}
```

Related: #7522

**Comment by aaronccasanova** [comment]
Consider enabling [ignoreDisables](https://stylelint.io/user-guide/configure#ignoredisables) to ensure warnings and failures are captured regardless of disable status.
