### ISSUE TITLE
Polaris icon SVGs should use currentColor in the fill attribute

### ISSUE THREAD

**Issue by joshlbaker** [Shopify/polaris-react-archive#7539]
## Issue summary

SVGs should use `currentColor` in the `fill` attribute.
This way, it can inherit the `color` value from either itself or a parent element.

Example of solution:
```html
<svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M19 2.5A1.5 1.5 0 0017.5 1h-15A1.5 1.5 0 001 2.5v15A1.5 1.5 0 002.5 19H10v-2H3.497c-.41 0-.64-.46-.4-.79l3.553-4.051c.19-.21.52-.21.72-.01L9 14l3.06-4.781a.5.5 0 01.84.02l.72 1.251A5.98 5.98 0 0116 10h3V2.5zm-11.5 2c1.1 0 2 .9 2 2s-.9 2-2 2-2-.9-2-2 .9-2 2-2zm12.207 10.793A1 1 0 0019 15h-2v-2a1 1 0 00-2 0v2h-2a1 1 0 000 2h2v2a1 1 0 102 0v-2h2a1 1 0 00.707-1.707z" fill="currentColor"/></svg>
```

## Expected behavior

Any application should be able to use Polaris icons separate from the Polaris `<Icon />` component and the color of the SVG should be applied based on the current color of the SVG element or its parent element.

## Actual behavior

When a Polaris SVG is rendered by itself it takes the hardcoded `fill` value. When passing in color, the fill overrides it.
This can be resolved by changing the fill attribute value using css but it's an additional step that shouldn't need to be taken.

## Steps to reproduce the problem

1. First step
1. Second step

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by BPScott** [comment]
The build for polaris icons strips these fills out - https://github.com/Shopify/polaris/blob/main/polaris-icons/rollup.config.mjs#L199 when publishing. Note the lack of a fill in the published artifacts:

https://unpkg.com/@shopify/polaris-icons@6.7.0/dist/svg/AbandonedCartMajor.svg
https://unpkg.com/browse/@shopify/polaris-icons@6.7.0/dist/icons/AbandonedCartMajor.svg.mjs
What does changing the fill in the source assets fix, when they are stripped out as part of packaging for production?
