### ISSUE TITLE
Consolidate @shopify/stylelint-polaris/configs/internal

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#7542]
Currently we have `coverage.js` `internal.js` and `shared.js`. *Alex thinks that* having one opinionated set of rules and not shipping loopholes for Polaris in the `internal.js` file would make our system and other platforms better.

In Polaris we have `internal.js` to allow `--pc-` custom properties. However these are sometimes misused or should just be replaced by our tokens. 

- `--pc-mt: var(--p-space-2)` is not good, the token should do the work here. Replace `--pc-mt` with `--p-space-2`
- `--pc-mt: 11px` is even worse. As it is hiding off mainline rules.

The `internal.js` file is allowing us to work around the system. We should reconsider this approach.

**Comment by aaronccasanova** [comment]
Closed by #7700
