### ISSUE TITLE
Consolidate eslint rules across monorepo

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris-react-archive#7567]
`polaris.shopify.com` uses its own version of `eslint` instead of relying on the version coming from root. 

https://github.com/Shopify/polaris/blob/main/polaris.shopify.com/package.json#L51-L52

There may be other duplications here as well, lets see what we can consolidate at the root

**Comment by aaronccasanova** [comment]
Hi stale bot! Please keep this issue open.

**Comment by aaronccasanova** [comment]
Keep open
