### ISSUE TITLE
[Typography foundations] [Migration] Card

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#7584]
[Figma](https://www.figma.com/file/siMyneYEuULTaNSuRFZAcx/Type-migrations?node-id=10%3A25)

`Card` section headings should use `heading-sm` (14px/20px)

The original intent was to use `heading-xs` but with current spacing and alignment with links that are 14px, `heading-sm` feels better.

<img width="1732" alt="image" src="https://user-images.githubusercontent.com/8629173/199105407-401f1e81-56a2-4df1-b558-5831496749d5.png">

**Comment by laurkim** [comment]
[Commit](https://github.com/Shopify/polaris/pull/7530/commits/0fb7db5d701ed94a975330bde7162b23fd14375d) with changes
