### ISSUE TITLE
Focus guidance and experience update

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#7585]
Our focus ring is misused and is overstated for the experience we are trying to provide:

| | |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/19199063/199109001-18b60aa4-aad3-4975-9bd0-3d4acb2dc7d6.png" width="300px"> | <img src="https://user-images.githubusercontent.com/19199063/199109000-0dcac557-d34e-4a56-b7e3-9703f6e8f90a.png" width="300px"> |

We should update our focus design to feel more crafted and not as intense when navigating by keyboard. See examples:
| | | |
| --- | --- |---|
| <img width="180px" src="https://user-images.githubusercontent.com/19199063/199109197-4a474af5-130a-4aeb-ac28-276bdfca458c.png"> | <img width="180px" src="https://user-images.githubusercontent.com/19199063/199109199-712f0485-e481-4ea7-837e-f107470aabeb.png"> | <img width="180px" src="https://user-images.githubusercontent.com/19199063/199109198-af0bd3a6-97f0-42f6-90b4-9ecb77c8ff1d.png"> |

The focus ring is also showing up when user are not using keyboard navigation. We should remove this as it causes confusion on the purpose of the ring and it's usage at scale.

https://github.com/Shopify/polaris/issues/7585#tasklist-block-2894fe98-7517-4f8c-be12-3fc42572929d

**Comment by jesstelford** [comment]
Beyond just the focus ring, it looks like we're trying to manually set things into the "focused" state outside of the Browser's normal algorithm. Ie; What is the second example trying to convey as the "focused" item? I can see three different things that appear to have some form of focus:

1. "Animaux et articles pour animaux de compagnie"
2. "Arts et loisirs"
3. "Recherccher des catégories d"

Only one thing can be focused at a time, so I don't understand how it's even possible to have two different focus ring styles, plus what looks like a hover-state style all at the same time 🤔

**Comment by alex-page** [comment]
Going to close this issue and focus on this deliverable first: https://github.com/Shopify/polaris/issues/9093

We can create a new issue when we are ready to change the visual style or document guidance around the focus.
