### ISSUE TITLE
[Typography foundations] [Migration] Page

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#7598]
**[Figma](https://www.figma.com/file/siMyneYEuULTaNSuRFZAcx/Type-migrations?node-id=345%3A1992)**

This might be taken care of manually but adding just in case - page title should stay the same across screen sizes. Right now it gets bigger on smaller screens.

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/8629173/199307565-6b8e6c4a-3606-4c55-9c05-264080d0e772.png">

**Comment by laurkim** [comment]
[Commit](https://github.com/Shopify/polaris/pull/7530/commits/76ebb11f542361899b174035debb2bb66978ca10) with update
