### ISSUE TITLE
[Layout foundations] Add the border width tokens to the Box component

### ISSUE THREAD

**Issue by nayeobkim** [Shopify/polaris-react-archive#7601]
Add the border width tokens 

--p-border-width-1
--p-border-width-2
--p-border-width-3

 to the Box component

Ensure that border width accepts colour tokens

**Comment by laurkim** [comment]
Here are our current border color tokens:

- border
- border-on-dark
- border-neutral-subdued
- border-hovered
- border-disabled
- border-subdued
- border-depressed
- border-shadow
- border-shadow-subdued
- border-critical
- border-critical-subdued
- border-critical-disabled
- border-warning
- border-warning-subdued
- border-highlight
- border-highlight-subdued
- border-success
- border-success-subdued

**Comment by aveline** [comment]
After discussing with @laurkim and @kyledurand we aligned on removing the shorthand border prop from box. Similar functionality will be supported by a new `Divider` component.

This will clear the way to add `borderColor` props on `Box`
