### ISSUE TITLE
[Layout foundations] Make Inline to be center aligned by default

### ISSUE THREAD

**Issue by nayeobkim** [Shopify/polaris-react-archive#7605]
Inline is top aligned by default currently, but it should be center aligned.

**Before**
![Image](https://user-images.githubusercontent.com/99563941/199335417-293d82e3-4043-4ffa-af6e-ea39c73b0d33.png)

**After** 
![Image](https://user-images.githubusercontent.com/99563941/199335207-23751f7f-6efc-4350-951b-87d435fe3db4.png)

**Comment by laurkim** [comment]
Closing, as I think this was resolved based off the default example on [Inline](https://polaris.shopify.com/components/inline).
<img width="834" alt="22-22-14br1-33cd2" src="https://user-images.githubusercontent.com/26749317/203338233-cda8d29c-90dd-408f-874f-201e3dd63eb6.png">
