### ISSUE TITLE
[Box] Should support position and interactive elements

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris-react-archive#7650]
Box should allow `position` prop to cover `relative` and `absolute` positioning. This means allowing `top` right `bottom` `left` as well.
Box should allow interactive elements. `a`, `button` maybe `textfield` `radio` `checkbox`. We should probably wait on form elements for now as they can get pretty complex. 

–OR– do we rebuild `UnstyledButton` / `UnstyledLink` with `Box`. Exploration needed

Reason for `position` is that we’ll need it for complete coverage

Reasons for allowing `a` and `button` tags is focus ring for things like tag which consists of a link beside a button: 

Here's a quick prototype of re building `Tag`

![focus](https://user-images.githubusercontent.com/6844391/200057731-7d61dc30-3c5a-4d69-8c69-423f814c69da.gif)

<details>
  <summary>Code</summary>

```jsx
<AlphaStack>
  <Tag url="/" onRemove={() => {}}>
    Polaris tag
  </Tag>
  <Inline spacing="0">
    <Box
      as="a"
      href="/"
      background="surface-neutral"
      padding="05"
      paddingInlineStart="2"
      borderRadiusStartStart="1"
      borderRadiusEndStart="1"
    >
      <Text as="span" variant="bodySm">
        Composed Tag
      </Text>
    </Box>
    <Box
      as="button"
      onClick={() => {}}
      background="surface-neutral"
      padding="05"
      borderRadiusStartEnd="1"
      borderRadiusEndEnd="1"
    >
      <Icon source={CancelSmallMinor} />
    </Box>
  </Inline>
</AlphaStack>
```
</details>

**Comment by aveline** [comment]
I do wonder about adding position to Box because that feels layout-ish and maybe we should have a layout component that could handle that?

Would the values for position always come from the system? Likely spacing tokens?

**Comment by kyledurand** [comment]
Going to close this in favour of these discussions:
https://github.com/Shopify/polaris/discussions/7733
https://github.com/Shopify/polaris/discussions/7687
