### ISSUE TITLE
data-primary-link on an UnstyledLink causes the app to navigate twice

### ISSUE THREAD

**Issue by jas7457** [Shopify/polaris-react-archive#7656]
## Issue summary

When using `data-primary-link` on the `UnstyledLink` component, it seems that navigation is being fired twice. Once for the click on the `UnstyledLink` and again for the click on the Row itself, which clicks the `UnstyledLink` manually.

This makes the history have two entries for the same link, so the user needs to use their back button twice to get back to the previous page.

Here is a [video](https://screenshot.click/07-55-9fnz6-pf1ck.mp4) showing that clicking on the row and not the link works, but when clicking on the link itself, there are two entries in the history stack.

## Expected behavior

This should only fire one click event, therefore only making one entry in the history stack.

## Actual behavior

The link is effectively clicked twice: once for the link itself, and another time due to the [code here](https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/IndexTable/components/Row/Row.tsx#L132-L134) that handles the click on the row, then clicks the link again.

## Steps to reproduce the problem

1. Create a `UnstyledLink` with `data-primary-link` on it
2. Click the link
3. Notice there are two entries in the browser state instead of one.

## Reduced test case

[Codesandbox](https://codesandbox.io/s/sharp-breeze-ewynb0?file=/SimpleIndexTableExample.js) of the issue

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: @shopify/polaris@10.10.1
- Browser: Chrome
- Device: Desktop
- Operating System: Mac

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
  System:
    OS: Linux 5.10 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (32) x64 Intel(R) Xeon(R) CPU @ 2.00GHz
    Memory: 102.71 GB / 204.46 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  npmPackages:
    @shopify/polaris: ^10.10.1 => 10.10.1 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
```

**Comment by jas7457** [comment]
Unless this was fixed by another issue, I think this is still a problem.

**Comment by jas7457** [comment]
I don't believe this was ever fixed. Reopening.

**Comment by andershagbard** [comment]
Issue still persistent in v13
