### ISSUE TITLE
Prototype interactive pattern examples on pattern pages

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#7671]
On the new pattern page we want to offer designers and developers an interactive example of a pattern. This interactive feature should:
* show an example of the pattern(s) discussed on the page
* provide code to show how the pattern is built
* Link to the Polaris components used to compose the pattern(s) together

**Questions and considerations**
* What do developers need to quickly get what they need from this page in order to start building asap?
* Can this feature be built into the existing [pattern page](https://github.com/Shopify/polaris/blob/main/polaris.shopify.com/pages/%5B...slug%5D.tsx)? (currently a catch all template)
* How will the pattern guidance content be authored? (currently using markdown)
* How will the pattern example code be authored and stored?
* Can we use playroom? Are there other tools we should explore to do the job?
* Can the example be rendered on the pattern page and interactive?
* Is there a way to have multiple pattern variants on the same pattern page e.x. single date picker vs. date range picker vs. multiple dates picker etc.

**Comment by SeanyB** [comment]
Done! 🎉 I'll create more focused Github issues for any smaller related tasks.
