### ISSUE TITLE
Prototype new pattern overview page

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#7672]
The pattern overview page is getting an overhaul in order to be clearer, more actionable, and provide discoverability of different patterns. 

**Questions and Considerations**
* How do we categorize patterns into groups on the page? What about in the left-hand nav?
* How does content on this page get authored?
* How do these patterns show up in search? Can they be further differentiated from component search results?

**Comment by SeanyB** [comment]
Prototyped and receiving positive feedback. I'll close this as Done, and I'll open more focused issues for any smaller changes/updates.
