### ISSUE TITLE
Color Picker Figma UI component doesn't visually match React component.

### ISSUE THREAD

**Issue by idonahue** [Shopify/polaris-react-archive#7681]
## Issue summary
Figma Component is visually inaccurate. The color picker area doesn't show the accurate color grade/gradient. 

## Expected behavior
<img width="172" alt="image" src="https://user-images.githubusercontent.com/6720319/200821344-87c599b5-9881-4ddf-8079-4cc669e67a6d.png">

## Actual behavior
**Standard color map**
<img width="183" alt="image" src="https://user-images.githubusercontent.com/6720319/200821409-80ab6f85-349e-4c14-a9f4-afa12f38397c.png">

**With Alpha**
<img width="527" alt="image" src="https://user-images.githubusercontent.com/6720319/200823014-7d0900f1-a5e6-4a7d-940b-4fafcacd3268.png">

## Steps to reproduce the problem

1. Look at [Polaris Figma component](https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/Polaris-Components?node-id=27579%3A730)
2. Top left is red, top right is red. Should be, top left is white, top right is red.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications
React Component: Correct
Figma Component: Incorrect
**No code change required, just Gigma component update**

**Comment by chloerice** [comment]
@sarahill do you know if this has been fixed in the UI Kit, or should we keep this open?

**Comment by sarahill** [comment]
Yep, this has been fixed. Will close. Thanks!
