### ISSUE TITLE
ActionList not displaying as it should when used within a Cards actions prop

### ISSUE THREAD

**Issue by cargix1** [Shopify/polaris-react-archive#77]
# Issue summary

<ActionList> element does not appear as it should when passed through in the actions prop of a <Card>

## Expected behavior

I'd expect to see a button with a downwards pointing caret and when clicked a menu of items would appear like shown in the [documentation](https://polaris.shopify.com/components/actions/action-list#examples). 

![screen shot 2017-06-01 at 12 03 20](https://cloud.githubusercontent.com/assets/9730290/26677112/69cd3862-46c2-11e7-8808-07d0e05bc6ab.png)

## Actual behavior

The drop down menu and button never appear instead we just get a list of links. 

![screen shot 2017-06-01 at 12 01 54](https://cloud.githubusercontent.com/assets/9730290/26677120/78e54fba-46c2-11e7-9d58-61d0be6280eb.png)

## Steps to Reproduce the Problem

1. Use the following code
```
<Card title="Card title" actions={[{content: <ActionList
  items={[
    {content: 'View'},
    {content: 'Export'},
    {content: 'Print'},
  ]}
/> }]}>
```
2. View the results in your browser

## Specifications

- Polaris version: 1.0.3
- React version: 15.4.2
- Browser: Chrome
- Device: Macbook Pro
- Operating System: Mac OS

**Comment by lemonmade** [comment]
Thanks for the issue, @cargix1. This is not currently a supported use case for card actions — the component only accepts actions with string contents, and therefore do not support any kind of dropdown/ complex HTML in the actions. I'll add a note for us to discuss this internally, and would love some more details from you on why you feel you need a dropdown instead of showing each action separately.

**Comment by cargix1** [comment]
Hey @lemonmade good to know, I thought maybe I was using the components as I wasn't meant to. 

Use case wise I was thinking it would be cool to allow merchants to quickly view, print and export a CSV of their daily pickup and delivery orders directly from my dashboard. 

<img width="387" alt="screen shot 2017-06-02 at 11 04 45" src="https://cloud.githubusercontent.com/assets/9730290/26721323/61066f70-4783-11e7-8e17-149b6cc5347a.png">

Although linking to "View orders" and then having those options works ok. Shall we close this issue?

**Comment by lemonmade** [comment]
Yup, I'll close it for now, though I've added the issue for us to discuss on our internal repo. Will post back here if we come to any decisions!
