### ISSUE TITLE
Swap bottom border and top border in styles of Figma UI Kit

### ISSUE THREAD

**Issue by idonahue** [Shopify/polaris-react-archive#7702]
## Issue summary
From a Polaris UI Figma user, can I swap the order of these dividers? 
**Currently its:**

- Bottom
- Top

<img width="242" alt="image" src="https://user-images.githubusercontent.com/6720319/201320823-a0ad68d5-d9c3-474b-8b8e-ec3b0f1b98f0.png">

I feel like it makes more sense to have these swapped. I always click bottom when I want top :sweat_smile:  I know its a little thing, but hey, we are Shopify, its the little things that count :thumbs: 

## Expected behavior

<img width="242" alt="image" src="https://user-images.githubusercontent.com/6720319/201321610-73d05267-301b-47e9-ba3e-300f4b9eebd0.png">

## Actual behavior

<img width="242" alt="image" src="https://user-images.githubusercontent.com/6720319/201320823-a0ad68d5-d9c3-474b-8b8e-ec3b0f1b98f0.png">

## Steps to reproduce the problem

1. First step
1. Second step

## Reduced test case

1. Select a Figma shape or item
2. Click "Effects" in right side panel
3. Click "+"
4. See list order under "Divider" section

## Specifications

**Polaris Figma UI Kit**

**Comment by zecarlostorre** [comment]
I made the change in the UI Library.
For the future, feel free to make a change in a branch and tag folks from the team to review.
