### ISSUE TITLE
Provide additional event handlers on TextField

### ISSUE THREAD

**Issue by GxDesign** [Shopify/polaris-react-archive#7716]
## Feature request summary

Provide onKeyPress and onInput to TextField component.

## Rationale

For the [Box Configuration project](https://vault.shopify.io/gsd/projects/30816) in SFN inbounds, we are trying to prevent negative number inputs on TextField. We can achieve this with either onInput or onKeyPress.

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s :+1: upvotes to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by GxDesign** [comment]
cc: @kathawala

**Comment by kathawala** [comment]
^ Yep, this would be a great feature to have. This issue (textfield number being able to go negative) was flagged by a designer on a project I was working on as a poor experience. Felt bad to say that the current Polaris component doesn't control for this or allow us to control this.
