### ISSUE TITLE
[Typography] [Migration] Update legacy type styles in the admin

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#7752]
[Google doc with details](https://docs.google.com/spreadsheets/d/1JbtTb7PE-PtylsjccspWjOdqrYp15Ghdi1kau8ecNEc/edit#gid=39380418)

**Comment by sarahill** [comment]
## Transfers

"Origin" and "Destination"
<img width="996" alt="Screenshot 2022-11-17 at 10 27 51 AM" src="https://user-images.githubusercontent.com/8629173/202528370-d07c9fdb-ea17-41de-87d8-03c3ef17f5e3.png">

**Comment by sarahill** [comment]
Update these section headings to use `headinSm` instead of `headingXs`

## Order details
<img width="326" alt="Screenshot 2022-11-17 at 10 16 28 AM" src="https://user-images.githubusercontent.com/8629173/202526273-60a9024b-5908-4a95-acd3-dfc5aa901ac3.png">

## Draft order details
<img width="337" alt="image" src="https://user-images.githubusercontent.com/8629173/202526943-2d74e597-2295-4ed2-a511-58814bb4a31a.png">

**Comment by sarahill** [comment]
Update these section headings to use `headinSm` instead of `headingXs`

## Customer details
<img width="345" alt="image" src="https://user-images.githubusercontent.com/8629173/202529757-2f3fd44e-ae12-4d2c-852a-b0ee49f6ac7e.png">

**Comment by sarahill** [comment]
Update these section headings to use `headinSm` instead of `headingXs`

## Product details
<img width="338" alt="Screenshot 2022-11-17 at 10 24 19 AM" src="https://user-images.githubusercontent.com/8629173/202531450-992ce9c7-8b9f-485e-823b-ed3fe6b50953.png">

**Comment by sarahill** [comment]
## Settings > Apps and sales channels
all app setting pages -> click on the app to see these pages

<img width="934" alt="image" src="https://user-images.githubusercontent.com/8629173/202538394-b687d577-c443-41c4-807f-bbd264ac0c9a.png">

**Comment by sarahill** [comment]
## Pick a plan

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/8629173/202546855-eb386a95-1be0-4170-a380-5134a8ebd55d.png">

<img width="986" alt="image" src="https://user-images.githubusercontent.com/8629173/202547223-a0f24ea0-137f-4940-9d3b-2664dc44ed4b.png">

**Comment by sarahill** [comment]
## Settings > Users and permissions > Transfer ownership

![2022-11-17 12 03 46](https://user-images.githubusercontent.com/8629173/202547799-bd003695-73d4-4839-8986-8225f17f9209.gif)

**Comment by sarahill** [comment]
## Settings > Shipping and delivery

Card section headings
"General shipping rates"
"Custom shipping rates"
"Manage delivery by location" 
"Manage pickup by location"

<img width="886" alt="image" src="https://user-images.githubusercontent.com/8629173/202549916-e0a82d2f-9376-4167-b12d-a557cc1b2121.png">

<img width="947" alt="image" src="https://user-images.githubusercontent.com/8629173/202549544-63ff97d4-bf93-4bfb-a3ed-fd196ab4d6e1.png">

**Comment by sarahill** [comment]
## Settings > Markets > Domains and languages

Table headers using legacy subheading styles

<img width="896" alt="image" src="https://user-images.githubusercontent.com/8629173/202550564-6c6d1eb9-487b-4d00-9091-e56b63c1f74c.png">

Section headings: Primary domain, domain or sudomain, subfolders

![2022-11-17 12 19 58](https://user-images.githubusercontent.com/8629173/202551361-713d1628-e642-403d-a25b-59ce85121648.gif)

**Comment by sarahill** [comment]
## Settings > Apps and sales channels

Card section headings

![2022-11-17 12 21 46](https://user-images.githubusercontent.com/8629173/202551724-9e9f80e8-5a43-45bc-a509-b84c24664570.gif)

**Comment by laurkim** [comment]
> Update these section headings to use `headinSm` instead of `headingXs`
> 
> ## Order details
> ## Draft order details

@sarahill I'm going to go these comment by comment and respond with screenshots of the fixes. Going to exclude the images you provided to minimize confusion of screenshots.

Order details customer card update:
<img width="321" alt="order-details-customer-card" src="https://user-images.githubusercontent.com/26749317/202580915-be90cf5b-57f0-4ff7-b627-4aa044cdc3f2.png">

Draft order details customer card update:
<img width="341" alt="draft-order-details-customer-card" src="https://user-images.githubusercontent.com/26749317/202580948-13cc14e7-3c1c-4f81-8295-983354f98760.png">

**Comment by laurkim** [comment]
> Update these section headings to use `headinSm` instead of `headingXs`
> 
> ## Customer details

Customer detail page customer card
<img width="338" alt="customer-details-customer-card" src="https://user-images.githubusercontent.com/26749317/202582020-18e1cefc-43b1-4074-99e2-f4ea02c55043.png">

**Comment by laurkim** [comment]
> Update these section headings to use `headinSm` instead of `headingXs`
> 
> ## Product details

Product details page product status card
<img width="339" alt="product-details-card-product-status" src="https://user-images.githubusercontent.com/26749317/202584701-3eb4c6f7-175e-4452-8ccc-8d50a402929a.png">

**Comment by laurkim** [comment]
> ## Settings > Shipping and delivery
> Card section headings "General shipping rates" "Custom shipping rates" "Manage delivery by location" "Manage pickup by location"

Settings page shipping card
<img width="894" alt="settings-shipping-shipping-card" src="https://user-images.githubusercontent.com/26749317/202586715-9e7a01a0-674f-40f2-8fcd-947f68185b58.png">

Settings page local delivery card
<img width="894" alt="settings-shipping-local-delivery-card" src="https://user-images.githubusercontent.com/26749317/202586731-439adb2c-21da-4eee-8c6a-28197c589b58.png">

Settings page local pickup card
<img width="898" alt="settings-shipping-local-pickup-card" src="https://user-images.githubusercontent.com/26749317/202586762-ef6dcd50-c7fe-45e2-b8fe-278c3b53fbad.png">

**Comment by laurkim** [comment]
> ## Settings > Users and permissions > Transfer ownership
<img width="684" alt="settings-usersnpermissions-transfer-store-ownership" src="https://user-images.githubusercontent.com/26749317/202587567-9f5a07ba-def8-4eb3-8db1-21147f8cc329.png">

The translation file has the `NEW STORE OWNER` copy as capitalized so I've left it as so, just changed the variant.

**Comment by sarahill** [comment]
@laurkim  All the above look good. I was going through all the pages and checking one more time and noticed one more odd thing.

The numbers on the [customer details page](https://admin.web.polaris-upgrade-text-migration.lo-kim.us.spin.dev/store/shop1/customers/107) are really small for some reason. See gif for comparison. It actually looks like it's using the right variant too 🤔 
<img width="648" alt="image" src="https://user-images.githubusercontent.com/8629173/202760771-a3ea2f3f-9fec-4f6b-bd28-69771e08ca57.png">
![2022-11-18 09 02 22](https://user-images.githubusercontent.com/8629173/202760798-fa6db90f-0c73-4626-a960-32787df4dc99.gif)
<img width="691" alt="image" src="https://user-images.githubusercontent.com/8629173/202761200-f0337b43-aae9-4c3d-a139-ed13400250d5.png">

**Comment by sarahill** [comment]
@laurkim One more and this should be it. I went over pages a few times.

The section heading on the skeleton loading state for the customer details page. Hard to inspect it but it looks like it's using the `headingXs` instead of `headingSm`. Other pages with this loading state look correct.
<img width="415" alt="Screenshot 2022-11-18 at 9 08 22 AM" src="https://user-images.githubusercontent.com/8629173/202762016-2ad930e3-21e2-45bc-a493-eb873eebd8c7.png">

**Comment by laurkim** [comment]
> ## Settings > Markets > Domains and languages
> Table headers using legacy subheading styles
>
> Section headings: Primary domain, domain or sudomain, subfolders

@sarahill re: [table headers](https://github.com/Shopify/web/blob/6a6a0fd6ca67f2f8b33fb9511250606fdc25b00d/app/sections/Markets/MarketDetails/components/MarketDetailsDomains/components/MarketWebPresenceLanguageSelector/MarketWebPresenceLanguageSelector.tsx#L209), those aren't using any typography components, just plain old `<th>` elements. We should probably flag that to the team that owns it.  

Settings -> Markets -> Domains and languages
![settings-domains-and-languages](https://user-images.githubusercontent.com/26749317/202780381-06233aa9-39fa-4d18-adc3-59c5e147dd12.gif)

**Comment by laurkim** [comment]
> ## Settings > Apps and sales channels
> Card section headings

Settings -> Apps -> Privacy details card
<img width="1267" alt="settings-apps-privacy-details" src="https://user-images.githubusercontent.com/26749317/202786619-bb58cce1-d22e-42ab-a627-f7a40bb63c23.png">

Settings -> Apps -> Permission details card
![settings-apps-permission-details](https://user-images.githubusercontent.com/26749317/202786639-53397d06-b3b6-421a-a46e-31959d8bfa1f.gif)

**Comment by sarahill** [comment]
## Order details

[Link](https://admin.web.migrate-typography-1.lo-kim.us.spin.dev/store/shop1/orders/1)
Additional details on notes
![Image](https://user-images.githubusercontent.com/8629173/203096606-12d908b5-3f14-4913-ad41-44a9b1fa5a9b.png)

**Comment by sarahill** [comment]
## Settings > Users and permissions > Add staff

Headings about checkbox lists:
- General
- Admission
- Online store
- Finance
- Apps and channels

<img width="787" alt="image" src="https://user-images.githubusercontent.com/8629173/203106719-d652607d-7095-480b-a9bc-c30b71e7387e.png">

**Comment by laurkim** [comment]
> ## Pick a plan

Settings -> Plan -> Pick a plan
![payments](https://user-images.githubusercontent.com/26749317/204587499-ec3304e0-5437-4ce4-939c-927f15da8499.gif)

**Comment by laurkim** [comment]
> @laurkim All the above look good. I was going through all the pages and checking one more time and noticed one more odd thing.
> 
> The numbers on the [customer details page](https://admin.web.polaris-upgrade-text-migration.lo-kim.us.spin.dev/store/shop1/customers/107) are really small for some reason. See gif for comparison. It actually looks like it's using the right variant too 🤔 

@sarahill I think it's because of the way the Text components were nested, so the inner Text component that was `bodyMd` that was originally migrated from `TextStyle` was overriding the `<Text variant="headingXl" as="h3">` styling. Just fixed 👍 
<img width="669" alt="customer-detail" src="https://user-images.githubusercontent.com/26749317/204590948-e10c8210-6dc3-4075-ab04-c04cccdf95e9.png">

**Comment by laurkim** [comment]
> @laurkim One more and this should be it. I went over pages a few times.
> 
> The section heading on the skeleton loading state for the customer details page. Hard to inspect it but it looks like it's using the `headingXs` instead of `headingSm`. Other pages with this loading state look correct.

Customer detail skeleton card
![customer-details](https://user-images.githubusercontent.com/26749317/204592278-8dd05261-f460-450d-92c4-f4ed078e10d0.gif)

**Comment by laurkim** [comment]
> ## Order details

I wasn't able to take a screenshot of this section, but I've updated this to be `headingSm`

**Comment by laurkim** [comment]
> ## Settings > Users and permissions > Add staff
> Headings about checkbox lists:
> 
> * General
> * Admission
> * Online store
> * Finance
> * Apps and channels
> 

User permissions:
<img width="846" alt="user-permissions" src="https://user-images.githubusercontent.com/26749317/204596449-b0dfd11c-8bd5-446e-8517-7a6bf6c01928.png">

Apps and channels:
<img width="882" alt="apps-and-channels" src="https://user-images.githubusercontent.com/26749317/204596482-31926869-78dc-44d4-87b4-a1c601b06511.png">

**Comment by sarahill** [comment]
Everything looks good! @laurkim thank you 👏
