### ISSUE TITLE
[Icon]: New icon paper check

### ISSUE THREAD

**Issue by kathleen-ships** [Shopify/polaris-react-archive#7776]
### How will these icons be used?

This icon will be used in the new Bill Pay feature. Both in Admin and within emails. 

### Icon name

paper-check

### What type of icon set?

Major (20x20)

### Icon description

Used for the paper-check payment method selection. We already have standard icons for credit card and bank ACH transfers. 

### Icon keywords

paper, check, payment method

### Icon author

Kathleen Robertson

### Icon SVG code

```shell
<svg>...</svg>
```

### Are there any other important details?

We have 3 suggestions here. option A is the preferred icon version from our team. 
![Check icons](https://user-images.githubusercontent.com/28788118/203095929-72a5ec78-bc4d-477e-b62d-821aa2d65420.png)

**Comment by heyjoethomas** [comment]
@kathleen-ships Can you send a Figma link so we can review the design more closely? Thanks Kathleen.

**Comment by kathleen-ships** [comment]
@heyjoethomas sure, here is the page with the 3 options: https://www.figma.com/file/GTqK5KbjfCYFf5A7Cu4AJW/Check-icon?node-id=1%3A1926&t=UGLoq8eIZeiHNvLY-1

**Comment by heyjoethomas** [comment]
Thanks. I made quick [Figma branch](https://www.figma.com/file/GTqK5KbjfCYFf5A7Cu4AJW/branch/dEPFlVmibmsIp9043aR0NP/Check-icon?node-id=0%3A1&t=FbSLEvpahqRIGRh3-11) and tweaked a couple things that better align with the design guidelines. Feel free to keep riffing.

**Comment by kathleen-ships** [comment]
@heyjoethomas I like the suggested edits you made. If your team is good with that, we'll go ahead with those. 

You'll have to remind me what the next steps are 😅

**Comment by heyjoethomas** [comment]
Once the design is done you can open a PR to get the icons into Polaris React as well as open a branch to add them to Figma. Docs are here https://polaris.shopify.com/contributing/icons. Reach out if you have questions along the way.
