### ISSUE TITLE
[Index Table] Bug: Promoted Bulk Actions and pagination cause UX problems

### ISSUE THREAD

**Issue by zaquille-oneil** [Shopify/polaris-react-archive#7864]
## Issue summary

During top-hatting for a new version of the CatalogEditor ([this ticket](https://github.com/Shopify/web/pull/78613)), I ran into some unwanted UX behaviors: https://screenshot.click/07-04-nxffj-5io07.mp4

## Expected behavior
 - If rows are selected and a user paginates, I expect bulk actions to be still available on the screen.
 - If rows are selected and a user paginates, I do not expect scrolling on the page to be affected.

## Actual behavior
 - Bulk actions disappear when rows are selected and a user paginates
 - Scroll functionality on the page breaks when rows are selected and a user paginates

## Steps to reproduce the problem

1. select some rows
2. paginate to the next page
3. (without clearing the selections) notice that the promoted bulk actions are not displayed
4. scroll down to trigger "sticky" behavior. notice that the screen jumps erratically
5. clear selections
6. re-select some rows
7. notice that promoted bulk actions now are properly displayed on the table

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: [10.15.0](https://github.com/Shopify/polaris/pull/7847)
- Browser: Google Chrome
- Device: Apple M1 Pro
- Operating System: Ventura 13.0

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by VijayaLakshmi210800** [comment]
I found that in small screens for index table the select option isnt available from 10.14 version of polaris please look into this issue

**Comment by capatina** [comment]
Yes, for some reason bulk actions were removed for ResourceList mobile view???
