### ISSUE TITLE
Please Document Token Usage

### ISSUE THREAD

**Issue by Michael-Gibbons** [Shopify/polaris-react-archive#7879]
## Feature request summary

Forgive me if this is documented elsewhere or there is a fundamental misunderstanding on my part.

I am unclear what the purpose of tokens are in Polaris, or how one would use them.

https://polaris.shopify.com/tokens 

Are these intended to be used on components? Are they CSS variables? Are they guidelines for non-react based Shopify apps that still want to adhere to Shopify's design principles?

Clarification on this would be appreciated, thanks!

**Comment by pjf1822** [comment]
Did you ever make any progress?  Im currently in the same boat. The media query documentation is a little vague

**Comment by Michael-Gibbons** [comment]
@pjf1822 Unfortunately no

**Comment by pjf1822** [comment]
just use it as a css variable.   
`background-color: var(--p-decorative-five-text)`
the media queries only  work with a scss file but the other tokens seem to work fine just in a css file as a css variable
