### ISSUE TITLE
Investigate `stylelint-polaris` rule to validate SCSS `calc()` usages

### ISSUE THREAD

**Issue by aaronccasanova** [Shopify/polaris-react-archive#7918]
Initial thoughts:
- Only allow converting to negative numbers `calc(-1 * var(--p-space-2))`
- Only allow negating specific token group custom properties
- Is there an existing rule: https://stylelint.io/user-guide/rules/
- Otherwise, what's the LOE to create our own rule

**Comment by sam-b-rose** [comment]
@aaronccasanova is this still an issue?

**Comment by aaronccasanova** [comment]
@samrose3 I believe this is something we still need to discuss as a team. I'm not aware of any Polaris guidance on `calc` usage or negating tokens. Without any rules in place `stylelint-polaris` will allow `calc(1.23 * var(--p-space-4))` when this is indeed off mainline.

**Comment by alex-page** [comment]
@aaronccasanova I agree this is important but we are going to do this as a follow up to the lighthouse project.
