### ISSUE TITLE
Resource index layout - assets

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#7932]

**Comment by johanstromqvist** [comment]
- [x] How it helps merchants
- [x] Useful to know
  - [x] Page title
  - [x] ~Common actions~
  - [x] Add button
  - [x] Set page width
- [x] Remove "Common actions" from spec
- [x] Final visual sweep: remove blur in favor of low-fi, and ensure good export


![Image](https://user-images.githubusercontent.com/38329124/212435408-137cb281-f844-4ddd-a37e-fff798b789b8.png)

**Comment by raquelbreternitz** [comment]
Just documenting here for my own reference + completion, what's needed to polish up the page title for review is:

- [x] Make page titles more clearly page titles (currently they can be interpreted as labels)
- [x] Make one of the 2 page examples a more niche secondary resource list, like shipping labels or newsletters

**Comment by raquelbreternitz** [comment]
Completed the final asset (barring feedback), placed it in the "Visual Assets" section :)

~Q: is it helpful to attach the assets here for dev review?~ 

ETA: Team has decided: 

- Figma is source of truth
- Design makes sure assets are cleaned up enough to be one-click exportable
- Images in GH are for illustrative purposes only

**Comment by johanstromqvist** [comment]
Looks good!

Two observations about the "common actions" one.
1. Builders might not make a decision about what actions are placed visibly in page header vs what's hiding in the "More actions". I believe they just dump all actions in an array of secondary actions, and they get the behavior for free.
2. The example actions are typical `detail` actions, and not/rarely found on `index`. Potentially use `import`, `export` and a generic product app action (puzzlify?).

- Let's remove it from the page entirely for now.
  - #8108 
- I'll create an issue to revisit whether we need implementation guidance around index actions
  - #8109

`Show the most common actions in the page header and place the rest under "More actions".`
![Image](https://user-images.githubusercontent.com/38329124/213578848-1dbdf9b1-ac0e-434d-bb78-cc1fc3b4e80a.png)

**Comment by raquelbreternitz** [comment]
All assets clean and done, ready for fresh eyes 👍

**Comment by johanstromqvist** [comment]
Could you drop a link to where they are at? :)

**Comment by raquelbreternitz** [comment]
Oops, yes, did that for details and forgot it here. [Figma link](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4204%3A173481&t=bEo4nRPgXZIPZwPH-1)

For reference, we agreed to start attaching the assets alongside the full page on their individual ticket pages in the Figma. That will be where you can find assets moving forward.

**Comment by johanstromqvist** [comment]
Oh, got it. Didn't realize it were those ticket numbers.

Looks great to me! Wanna make this ticket an engineering one and move it to `this week`?

**Comment by raquelbreternitz** [comment]
Addressed this with #8160 so closing this now
