### ISSUE TITLE
Resource details layout - content

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#7933]
### Primary content
- [x] Draft subtitle
- [x] Draft annotations for key pattern characteristics
- [x] Draft merchant use cases
- [x] Inventory what critical decisions builders need to make
- [x] Draft guidelines to critical decisions

### Secondary content
- [x] Sketch asset ideas
  - [x] Pattern overview
  - [x] Critical decisions
- [x] Identify and list related resources

Moved to issue https://github.com/Shopify/polaris/issues/7944
- [ ] Draft code template and component list

[Figma](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4204%3A173485&t=Kg5sYithPQzevUFl-1)

**Comment by johanstromqvist** [comment]
Ready for review. 🎉

Will review it with SME tomorrow, but critical feedback is very welcome.

[Figma: Resource detail layout – First draft, Jan 9th](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4604%3A185572&t=rYbnKEYkVfLy388e-1)

CC: @SeanyB

**Comment by johanstromqvist** [comment]
Marking this issue as done.

Creating new issues:
- [x] Create a separate issue for code templates
- [x] Schedule a final cross-pattern content review before publishing

## State of the content
[Figma](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4216%3A181657)

![Image](https://user-images.githubusercontent.com/38329124/212432098-13992316-ec82-4020-a29a-c1a70a960085.png)
