### ISSUE TITLE
Decide if legacy patterns should remain at launch and how they should integrate with others on index

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#7936]
There were some good points raised about loading states and cumulative layout shift from leaders in Slack this week. 

Basically all of the points are captured in the [loading guidelines](https://polaris.shopify.com/patterns/loading) we shipped earlier this year. 

Perhaps we should not remove that page when publishing the new ones. 

Perhaps there is a way to distinguish new patterns from old, or to link to the previous version?

**Comment by johanstromqvist** [comment]
I'll close this and refer to #8024
