### ISSUE TITLE
Create code examples: Resource details layout

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#7944]
Design tasks
~- [ ] Summarize what UI elements that should be included in template scope~
~- [ ] Summarize what content that should exemplify the merchant activity~
~- [ ] Specify any important defaults, such as `fullWidth` prop~
~- [ ] List places/decisions that might require code comments~

^ We didn't explicitly complete these, but I believe the code example on staging meets the needs. It's s simplified reproduction a product details page with skeleton content.

Remaining tasks:
- [x] Replace `actionGroups` prop with `secondaryActions` prop
- [x] Use the common object actions listed in [this comment](https://github.com/Shopify/polaris/issues/7944#issuecomment-1431727299) below

**Comment by raquelbreternitz** [comment]
As for 1. and 2., is there anything that would be different from the existing annotated cover-image? My gut feeling is that that would be a red flag, but I wanted to make sure I understood what was desired here.

![Image](https://user-images.githubusercontent.com/13204374/215587429-bbd1110d-ca29-4cd0-be9e-14d86a62c6f3.png)

**Comment by johanstromqvist** [comment]
Is there an opinion or decision about using a code example with skeleton like placeholders? It comes across as a loading state to me and I would assume builders can infer a lot of important decision-making from realistic examples, which might both speed up workflow and increase quality.

> is there anything that would be different from the existing annotated cover-image?

@raquelbreternitz Are you asking if we need to update the annotated image based on the look of the code example?

**Comment by gwyneplaine** [comment]
> Is there an opinion or decision about using a code example with skeleton like placeholders? It comes across as a loading state to me and I would assume builders can infer a lot of important decision-making from realistic examples, which might both speed up workflow and increase quality.

We discussed this in our sync earlier, and glad this isn't a blocker for MVP. Just wanted to add more detail here for future context 🎉.

The resource details layout (as shown in the cover image) includes a WYSIWYG editor. We don't have a WYSIWYG component in Polaris. This is a good example of the tension we were talking about. Its a tension between two principles we've touched on a few times now: 
* Providing useful and realistic pattern examples 
* Ensuring patterns only encapsulate Polaris components 

This also segues into the question of where the line is between providing enough guidance to admin builders, and shouldering too much engineering complexity outside of the domain of Polaris. This is good stuff though I think teasing apart this problem will help us understand what a good pattern should look like for **all** builders

**Comment by alex-page** [comment]
Can we remove the Editor buttons in the screenshots. This is a super requested Polaris feature which we cannot support. See this thread https://github.com/Shopify/polaris/issues/303

**Comment by raquelbreternitz** [comment]
> Can we remove the Editor buttons in the screenshots. This is a super requested Polaris feature which we cannot support. See this thread #303

Yup, I can smudge those out in the example images. I made an issue for it here #8336

**Comment by alex-page** [comment]
Thank you @raquelbreternitz 🙌

**Comment by johanstromqvist** [comment]
(I've updated the tasks in the first comment to include this 👇 )

The Page component typically takes the page actions in the `secondaryActions` prop, and not in an `actionGroups` prop. I believe the `secondaryActions` prop creates an action group labeled "More actions" and allows actions to show up in the page header when there's space (something the `actionGroups` don't do).

I suggest using the three commonly recurring object actions below to explicitly show where merchants expect to find these. This also aligns with the direction in #8353 which will be a fast follow.

[Sandbox link](https://polaris-staging.shopifycloud.com/sandbox?code=N4Igxg9gJgpiBcJgHoBUACA2gBQgGwEMAnASwGd1sCAXamIgOwF10AlGMiAVyLBnVjUCJPBUIBPbtXSpkAXwA6DFBgDiMBvRowo6CA3QAmAAyGAzAFpTFgIwBWdADMiEALboAFrQAOZeMmRvfGJyCzIhAHMSBgiAOjIPCG8SR3EwPG4oWMhXQJo6RjJkIg5uXhgLQWFRCwkpGXkldHQm9GAACkcuBjBqEn02Up4%2BABEYIREyABkCSS5qdoBKNtbm5sgGcPQAZQBrGDxx-RmAIwP0AF50du8XX2WLgD4VgzW3kuoeA3bVt7WAHgAQhAAB6-P5rE4EMC7CIubpQC4KEBkHiOaEVTTzIgEPDI8EQ9CuaIACRgJAiXiRIBsJVc%2BNehLWrgIIIA6iQoNQPNS7HSGUy3icIERYERWAQoCQuGRqVCyDABYLmsBYmrbkkyIpGYTkI8Cc1FgBuAlyE065ofL7XA3of5UCKKi1-E4lSVgIhcVwnWXATDAdAbOgMajwFogbAuKBcXpkZEAGnQPDwYeRgSjMeocZA6DkTG1yr61EO1Mj0EzSqZCo2UGI4gAgr1%2BpsLn7bcBbet9MHQ%2BgAOQjLjePAkMDaPvxzvoUf6MOD4ej7QAWWiIsnzre0L4ZDIJBOIhI1HEpwOYb72xgNbr6GhfQGhDOeAnU-0jbvDDDS0uz1x9AWA6HEcxzoG8m30PtFnXJk5CgwkOw3NYgw0Xs%2B3rXgPBIAA3GBnwQ5oZw-dA0LADDsJXBg1ynLcOF3fcRyPE8U37C8ryIcRQPfdAHwOXDlVfMDCK-J4b0OIh-2I0j%2BFvZsINgiEYKneDlSQkMzzGQ46F4wUCLnA5xhgcjKLwgQOGoT0m2wsMzK4GA5MJaidz3A8GIIR8zxY-RazYjjmy41yeLsiF%2BPfT8Hh-UT-3U-SfPAyDbQU518ynbwCCiBgaGbVslOVTwCDISMYEw-oZSsz1bKnZoPDygA5GAQV7azyuMuQC0JfVjP%2BABhfAvU2QMetcFtgADEE-HQGxE1cKBUxAQxnHG5xkVzOR2pyu16zwbwqu2IQYScLg8DwDkuQ8Va1vWzaqs64hdHhBhYCgethWw6kyHpEAzvOi6toIHboV2fbDuO7lPq%2Bu09j06hjn8vB0D1CrCSBUF0GFUV6GpKUirFJbUbFCUpRlOU8sVHNiQYMkKSpZFDH5HN4eMpl-ghjTocfIlWWBnlkQADlpuHQa%2BpGQRRkUxQxrDOXoHHRfofHpVlZF5RJolSXJSlqGpEw%2BfpsG7WQDafr%2BmEBcFf59cughrtFE3GYNq6bvQO6HqeiAXuRN7kRt027d%2B3aAa6IHORBhGISZ-YWYYEZyGHWYABU6ukXcAC8YFellDqWnXdbtbq8F6ihIDzwbfRGsaJqJaajGWr21qFkW0aIcWsalnNcdlyV5aJhUlrJin1epGxjG1mucrrtvG%2BRTHJaIaWG7lwnFeJnvVcpjXkUH4eQ7%2BM3c-zkfQ-Nw2-f3gFD-t62EbNn2jd2E--mvv3AaOoPTq3%2B%2BLat27uHunQXbdlF3onzeO-I%2B-0n6cyAdvZmRxI7RwkPHeq6Bk6p3dunPEdNIHAOBMLceTdp6zzxh3BeIAlbL3JmrKms1N4M0RtgzB29ASHB0OzIgaUACSDARyaCyugUaYYAAsiY3phgcC1ehoco7NyIPXMUO1xAlknhLbGGCt4H0YTAHQ4i9Z0NUQCaBUMGCMX5ro5o-xJHTxkfQORCiQBT2UcYmhod9H6GBFAcQCDpBZ0FmfX2-1IFXw-jdfxPtP6O2-s7Z6KCAGe10SA7aj8A7PxOlosOkNWbnC8WDMeMsJ62KUS3Sx4oiEKxIUvUmK9%2B7U2odncG4cYFGJZOyF%2B1J%2BHVOztkhueD7Hj3niU0h5TyGr01m03WqSI5GMyYLZxDBXHuITg40ZPib7%2BJ8Z-O%2BSzj5Th3gNTYXszYOhgCbY0vw5CLCWHIEA8YQDchgK4DgCBMAgAyGOQ48ANAgHzEAA)

![Image](https://user-images.githubusercontent.com/38329124/219104568-ab6441b8-811f-40d5-ac40-a7224fc58c3a.png)

```
secondaryActions={[
        {
          content: 'Duplicate',
          icon: DuplicateMinor,
          accessibilityLabel: 'Secondary action label',
          onAction: () => alert('Duplicate action'),
        },
        {
          content: 'Archive',
          icon: ArchiveMinor,
          accessibilityLabel: 'Secondary action label',
          onAction: () => alert('Archive action'),
        },
          {
          content: 'Delete',
          icon: DeleteMinor,
          destructive: true,
          accessibilityLabel: 'Secondary action label',
          onAction: () => alert('Delete action'),
        },
]}
```

**Comment by gwyneplaine** [comment]
remaining tasks resolved in https://github.com/Shopify/polaris/pull/8402 
and [staged](https://polaris-staging.shopifycloud.com)
