### ISSUE TITLE
Pattern detail page prototype - tweaks

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#7948]
The following are suggested changes to the overall Pattern detail page layout, which would affect all patterns.

- [x] Narrow page with to match figma prototype.
- [x] Remove the `beta` label from the patterns details pages. 
    - When we launch, these should be "ready to use" and not considered beta.
- [x] Add a 1px grey border around the variant tab "box".
- [x] Increase the size of the variant tab labels and make them **bold**.
- [x] Increase the size of the short description under each variant tab.
    - E.g. _"This enables merchants to type a specific date or pick it from a calendar."_
- [x] Remove border on **How it helps merchants** asset.
- [x] Make purple numbers under **How it helps merchant** asset use **Bold**.
- [x] Change border around live rendering and code snippet to match figma. 
    - It should be a single grey line, rather than dropshadow.
- [x] Increase size of **Useful to know** label to match Figma.

**Comment by jesstelford** [comment]
I'm going to be working from this design, let me know if there's anything more up to date: https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=3676%3A178459&t=6pLdt8Ke1L0MZ2cY-4

**Comment by jesstelford** [comment]
> Narrow page with to match figma prototype.

I've broken this out into its own issue because there are a bunch of confounding factors to consider here: https://github.com/Shopify/polaris/issues/7966

**Comment by SeanyB** [comment]
> I'm going to be working from this design, let me know if there's anything more up to date: https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=3676%3A178459&t=6pLdt8Ke1L0MZ2cY-4

Yep, that's the most up-to-date. In the new year, we'll get better at using a "working area" in Figma for design iteration and a "latest publishable version" for the hand-off from design and eng. This way, we aren't changing little details in a design as you're working from it, and it forces us to explain the changes.

**Comment by jesstelford** [comment]
> Narrow page with to match figma prototype
> the size of the Useful to know images [..] need these to be smaller. [..] could come up with a UX that makes these smaller without it being directly linked to the overall page width. - https://github.com/Shopify/polaris/issues/7966

Awesome, I can set a max width on those images so they're not gigantic on wider screens, but aren't too small on thinner ones 👍

**Comment by jesstelford** [comment]
Ok, I've set a max width, how does this feel?

**Before**

![img-width-before](https://user-images.githubusercontent.com/612020/209249205-b95f5aa4-5b1d-4bcc-975c-481936b8603c.gif)

**After**

![img-width-after](https://user-images.githubusercontent.com/612020/209249215-b7336ff2-f8e7-42d8-80c6-f5bca49db117.gif)

**Comment by jesstelford** [comment]
I've made all those changes 👍 

A note on the last one _"Increase size of Useful to know label to match Figma."_: I've bumped this up to `20px`, but that means it no longer matches the heading size across the rest of the site (it's a `h3` @ `18px`).

**Comment by jesstelford** [comment]
This is now deployed to staging.

If you're happy, feel free to close this issue 👍

**Comment by SeanyB** [comment]
Thanks, @jesstelford! There are a ton of great little improvements here.

@bernardojoaogarcia is working on a few minor design tweaks this week, for example to make the **Related resources** cards smaller / less prominent. Once they are solid, we can document any specific changes as eng tasks in a [separate issue](https://github.com/Shopify/polaris/issues/7986).

We also found a few other items this week that we'll include in that issue.
