### ISSUE TITLE
App Settings Layout - should code use Annotated Layout component?

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#7961]
I just noticed that the code example in staging for the Page Settings layout uses our core layout primitives, rather than the AnnotatedLayout component.

My assumption had been that we would use the AnnotatedLayout because it would be simpler to use and guarantee consistency.

However, when I spoke to Kyle in late December, he suggested that code example is actually better to use.

If we provide code with layout primitives, then the ADG should point exclusively to this pattern rather than the Annotated Layout component.

**Current code example:**

```
<Page
      divider
      primaryAction={{ content: "View on your store", disabled: true }}
      secondaryActions={[
        {
          content: "Duplicate",
          accessibilityLabel: "Secondary action label",
          onAction: () => alert("Duplicate action"),
        },
      ]}
    >
      <AlphaStack gap="16">
        <Columns columns={{ xs: "1fr", md: "2fr 5fr" }}>
          <Box as="section">
            <AlphaStack>
              <Text as="h3" variant="headingMd">
                InterJambs
              </Text>
              <Text as="p" variant="bodyMd">
                Interjambs are the rounded protruding bits of your puzzlie piece
              </Text>
            </AlphaStack>
          </Box>
          <AlphaCard>
            <AlphaStack fullWidth>
              <TextField label="Interjamb style" />
              <TextField label="Interjamb ratio" />
            </AlphaStack>
          </AlphaCard>
        </Columns>
        <Columns columns={{ xs: "1fr", md: "2fr 5fr" }}>
          <Box as="section">
            <AlphaStack>
              <Text as="h3" variant="headingMd">
                Dimensions
              </Text>
              <Text as="p" variant="bodyMd">
                Interjambs are the rounded protruding bits of your puzzlie piece
              </Text>
            </AlphaStack>
          </Box>
          <AlphaCard>
            <AlphaStack fullWidth>
              <TextField label="Horizontal" />
              <TextField label="Interjamb ratio" />
            </AlphaStack>
          </AlphaCard>
        </Columns>
      </AlphaStack>
    </Page>
```

**Comment by johanstromqvist** [comment]
Did we reach a conclusion on this in workplace?

**Comment by SeanyB** [comment]
> Did we reach a conclusion on this in workplace?

Not yet. We don't yet have eng alignment on whether we should use the primitives or the Layout component.

We have @aveline's [research](https://github.com/Shopify/polaris/pull/7391) on refactoring the Layout component under-the-hood to use the layout primitives.

**Comment by johanstromqvist** [comment]
We're using new Layout primitives.

[Decision log](https://vault.shopify.io/gsd/projects/30559/decisions/1318)
