### ISSUE TITLE
Pattern detail page - page width & ToC

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#7994]
Additional UI tweaks for the Pattern details page.

**Page width and ToC:**
- [x] All pages should be `776px` wide at their largest breakpoint. 
- ~[ ] The App Settings Layout pattern is currently too wide.~
- [x] The ToC should be re-added to all pattern details pages for now.
    - In the context of this project, we won't make any changes to overall page widths that affect the whole Polaris website.
- [x] Adjust left and right padding values to be `64px` ([Figma](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4622%3A191580&t=Wfh8XdUzAQkojg9N-1))
    - This should match other pages in the Polaris website.
    - Note: The figma link shows two options for negative margins for the Tab 'box', but that is covered in #8055.

**Comment by jesstelford** [comment]
I've ensured the Patterns page now matches the rest of the site for page width, padding, and ToC being visible.

A quick note on _"App Settings Layout"_; we're currently only working on the page structure in the Date pattern. Once that's complete, all the other patterns will inherit the exact same layout. For now, it's safe to ignore issues on patterns that aren't the Date.
