### ISSUE TITLE
Record Polaris mainline focus in decision log

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#8000]
"Focus on Polaris first. Admin patterns perhaps can join later with also other stakeholders and owners. We need to make sure we stay within the area we can control for now and can have the biggest impact on. Lead with that to communicate our vision and then go and fold other parts into it."

Implications on resource index layout pattern, either
1. Adopt existing global filter component to Polaris and publish old style pattern
2. Adopt new index, filter and tabs to Polaris asap, and publish new style pattern

[As discussed here](https://shopify.slack.com/archives/C036CGUL4SE/p1673033349533659)

**Comment by SeanyB** [comment]
Done
