### ISSUE TITLE
Update descriptions on pattern index page and respective pattern subtitle

### ISSUE THREAD

**Issue by nblloyd** [Shopify/polaris-react-archive#8003]
- [x] Update designs with new descriptions
- [x] Update code to be in line with the updated designs
  - [x] Pattern thumbnail on pattern index page
  - [ ] Subtitle on respective pattern detail page

| Pattern | Description |
|--------|--------|
| App settings layout | `Lets merchants scan and find groups of settings in apps` |
| Date picker | `Lets merchants select a date or a date range` |
| Resource details layout | `Lets merchants create, view, and edit resource objects` |
| Resource index layout | `Lets merchants organize and take action on resource objects` |

![Image](https://user-images.githubusercontent.com/108757674/211375828-61cdfe8b-b8a7-4585-bf95-a36878504553.png)

The patterns overview page currently uses descriptions that all start with "Makes it easy to...". We should update these to be less repetitive. Suggestion is to use the subtitle from each pattern's detail page for consistency and continuity.

**Comment by tracytees** [comment]
<img width="906" alt="Screenshot 2023-01-17 at 1 17 33 PM" src="https://user-images.githubusercontent.com/108495662/213014271-2965f01f-420f-477d-a8ef-0c9d2d4cc34f.png">

Made some edits and would love some feedback: [Figma](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4862%3A220360) @nblloyd, @johanstromqvist, @selenehinkley

**Comment by nblloyd** [comment]
@tracytees Thanks for making the update!

Is the text below each pattern consistent with the short description one would see on that pattern's detail page? I am not sure where we have the latest copy at the moment, but taking a quick look through Figma, it looks like the "App settings layout" pattern copy doesn't match exactly.

**Comment by johanstromqvist** [comment]
Thanks @tracytees!

@nblloyd the [Build review page](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=3229%3A152253) is the most recent holistic reference.

Feedback:
- Had the same thought as @nblloyd. The subtitle on each respective page is ideally the most succinct and relevant description (if it isn't, we should iterate). So try to leverage that as much as possible and create a strong connection to the page that builders might navigate to. If there's an opportunity to reuse the subtitle 1:1 then we could do that automatically, i.e. no manual work needed to create and maintain thumbnail descriptions.
- Whatever the suggested descriptions are, it would be good to have some sort of formula or reusable idea of how the descriptions are written and why. That way, we could both learn and iterate it's effectiveness, and use it for future guidance to ourselves and other authors. So rationale is interesting.

**Comment by tracytees** [comment]
<img width="964" alt="Screenshot 2023-01-18 at 11 32 15 AM" src="https://user-images.githubusercontent.com/108495662/213278227-dd9875bb-7f67-4245-bbeb-e0fb02a1fcee.png">

Thanks for the feedback @johanstromqvist and @nblloyd. I've updated the information but let me know if it's not correct. I've included a "formula" idea, which would be: 
- Mention merchant ability to... + Action
- 1 sentence
- Similar to description on specific pattern overview page

**Comment by johanstromqvist** [comment]
Do you think it would be possible to use the subtitle straight up? And make sure we continue to phrase the subtitle consistently `Lets merchants {activity}`?

**Comment by tracytees** [comment]
@johanstromqvist That could work too but I feel like having a little more variety would be nice but not a huge deal to me. Thoughts about having every subtitle to start with `Lets merchants {activity}`? @nblloyd + @selenehinkley

**Comment by johanstromqvist** [comment]
`Lets merchants {activity}` is how the subtitles are phrased currently.

@nblloyd 's initial suggestion was to use the same copy.

> Suggestion is to use the subtitle from each pattern's detail page for consistency and continuity.

It would also be a win from a maintenance POV.
> If there's an opportunity to reuse the subtitle 1:1 then we could do that automatically, i.e. no manual work needed to create and maintain thumbnail descriptions.

We would still need a quick design check what that looks like and how it might affect how we craft subtitles. I can imagine that subtitles need a max character number to make sure they stay within two rows in the thumbnail, and perhaps the subtitle can have two sentences, but it's the first one that gets pulled to the thumbnail. Things like that...

**Comment by tracytees** [comment]
Ah sorry for the misunderstanding...I was careless with reading the feedback. I've adjusted it accordingly. Every description from the details page works except for Date picking, which needed to be shortened. 

As you suspected @johanstromqvist, it's only 2 rows of text so if we craft it where the first sentence gets pulled in that could work as long as it doesn't create more complications

<img width="1359" alt="Screenshot 2023-01-19 at 3 22 00 PM" src="https://user-images.githubusercontent.com/108495662/213584066-4a8863c6-59de-4dc5-b95f-47133009adf3.png">

**Comment by johanstromqvist** [comment]
Nice! I actually like that it creates a forcing function to write very succinct subtitles.

Observations:
- The "filter" and "schedule" in date picking comes across as a bit odd without the objects of "data" and "events".
- We can probably skip the adverbs like `effectively`, `easily`, etc

**How about this?**
Lets merchants...
1. ...scan and find groups of settings in apps
2. ...select a date or a date range
3. ...create, view, and edit resource objects
4. ...organize and take action on resource objects

And if another sentence is needed in the page subtitle, that could be ok.

**Comment by tracytees** [comment]
That works, adjustments made

<img width="1361" alt="Screenshot 2023-01-19 at 3 57 29 PM" src="https://user-images.githubusercontent.com/108495662/213588336-41b111e3-5a9c-41a9-bb7b-5ddf570d5b99.png">

**Comment by johanstromqvist** [comment]
Could we get final eyes from a second person please?

@nblloyd @SeanyB @raquelbreternitz @selenehinkley 

If all good Tracy, you can check off the tasks in the first comment, edit it to add any outstanding tasks, such as updating both subtitles and thumbnail descriptions to these, and move the issue back to `this week` and ping eng.

**Comment by nblloyd** [comment]
Looks good to me. As @johanstromqvist said, let's make sure we update the subtitles on all individual pattern pages to match these as well.

**Comment by SeanyB** [comment]
Yep, looks great to me too. 😄

**Comment by raquelbreternitz** [comment]
LGTM, though "resource objects" is still a confusing/jargony-feeling phrase to me. I am putting that aside because "organize and take action on lists of things" might feel too informal?

Question...do we need to continue to repeat "Lets merchants" in these? I'm imagining a world where we have even more like 10-15 patterns and people are just skimming right past. I almost think, since we mention patterns are for merchant goals in the page subtitle, that we can eliminate the "lets merchants" phrase altogether. The pattern subtitles work as imperatives.

**Comment by johanstromqvist** [comment]
Great! Let's add issues and ideas to our backlog and roll with this for now.

Changes made:
- Updated the first comment with the design decision
- Removed the `design` label and unassigned @tracytees 
- Moved the issue to `this week`

I didn't assign an eng to it. Perhaps a code-curious designer will take it on?
