### ISSUE TITLE
[Layout foundations] Determine which components we should update as part of this project

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#8017]
Questions to answer:
- Which components have the most lines of layout code and will give us the biggest bump in layout coverage
- Batch 3: are there other components with more lines of layout code that we should prioritize?

This might have info we can use https://docs.google.com/spreadsheets/d/1UL-qtZn9punqCnx8W-nwagCjsRITjjXIOGAEKJX8z50/edit?usp=sharing

**Comment by yurm04** [comment]
I dug into finding out the components with the highest failing lines of code for layout in our scss files. 

I modified the polaris coverage site utilities to get the data. This was run against our main branch which includes the refactors for batch 1 and batch 2.

The top five components with failing layout lines are:

1. IndexTable
2. Filters
3. Navigation
4. Frame
5. ResourceList
6. ResourceItem
7. Header
8. DataTable
9. ColorPicker
10. TopBar

**Comment by sarahill** [comment]
Did some initial work on grouping the components into potentional batches.

Some of the components are pretty complex so we need to figure out our strategy for approaching these.
- Do we want to split these out in separate smaller batches?
- Tackle all the complex ones in one big batch?

@aveline is going to investigate these components a bit more and understand:
- variability (edge cases) and surface area
- if any of the components are actively being worked on (Filters)



[Figma](https://www.figma.com/file/7332pWF56f7ETMjXMFzRRZ/Layout-project-planning?node-id=48%3A70&t=IMJWiulXVwmv12TZ-4)
![Image](https://user-images.githubusercontent.com/8629173/212987782-d90150c8-55bb-4f66-945b-03d011572840.png)
