### ISSUE TITLE
Decide what to do with each of the current pattern docs when we release

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#8024]
The [current patterns](https://polaris.shopify.com/patterns) documentation contains our older style of patterns, which are longer, contain multiple examples, and don't include as much direct code guidance.

We must review each of these pages and decide what to do with them when we launch the new patterns pages.

- We don't want to lose important information on the Polaris website
- But we also don't want to risk people avoiding the new patterns pages because they see the old ones and assume the content will be similar
- We also don't want to confuse readers who look at both old and new patterns pages.

(As also mentioned in duplicate #7936)

**Comment by johanstromqvist** [comment]
## Two high level ideas
1. Leave current section as is, remove it from the IA and nav, but add a link to it in the banner on the new index page. Add critical information on old index page and each pattern page.
2. Keep the useful pages in a temporary "Archive" sub-section in the nav. Don't include them in the new index. Filter out pages that are outdated or misplaced.

I'm leaning option 2. Here's a scrappy sketch for sake of conversation. Conservative to the left and bold to the right
👇

![Image](https://user-images.githubusercontent.com/38329124/212406618-20ec4ec8-48d8-49c3-81aa-c3227799b957.png)

## Scrappy review
- Outdated or misplaced
  - [Design patterns](https://polaris.shopify.com/patterns/design-patterns) (remove until improved)
  - [Error messages](https://polaris.shopify.com/patterns/error-messages) (move to content)
  - [Help content](https://polaris.shopify.com/patterns/help-content) (move to content)
- Potentially valuable pages
  - [Loading](https://polaris.shopify.com/patterns/loading) (should be included in next set and updated)
  - [New badge](https://polaris.shopify.com/patterns/new-badge) (should be included in a broader onboarding initiative)
  - [Pickers](https://polaris.shopify.com/patterns/pickers) (should follow Date Pickers and be used in new pattern page format)
  - [Text fields](https://polaris.shopify.com/patterns/text-fields) (should likely be split in 3 parts; component docs, content docs, seed for form patterns)
  - [Page layout](https://polaris.shopify.com/patterns/page-layouts) (could potentially be removed, but has useful high level information. Could be used as a starting point for a "Layout" parent page.)

JJ did a quick audit during fall as well. @jjgali do you have a summary or artefact we could use here?

**Comment by jjgali** [comment]
> JJ did a quick audit during fall as well. @jjgali do you have a summary or artefact we could use here?

@johanstromqvist I'm not sure if this is what you're referring to, but [this audit](https://docs.google.com/spreadsheets/d/1TtmD_-_n39ov-k3TMSvDcHnCTyJz2-hU8ACvu-OWa3Q/edit?usp=sharing) preparing Polaris content for .dev is probably the most thorough breakdown I have of each existing content section. Primarily I was using this to determine what should move to .dev and what needed revamping, but hopefully my notes in the last column are of some help.

**Comment by SeanyB** [comment]
@johanstromqvist - having read the [Page layout](https://polaris.shopify.com/patterns/page-layouts) content, I think we should remove this page. Much of it is duplicated and improved by the App Settings, Resource Index, and Resource Details layout patterns. The small scale layouting content will need to be replaced by more complete examples of our new layout components - and that should live close to those components, rather than in patterns (because they will be agnostic to specific merchant workflows).

**Comment by johanstromqvist** [comment]
Decision 
- Index page
  - Move the current pattern index to polaris.shopify.io/deprecated/patterns (or equivalent)
  - Remove it from any other IA, search, and nav, but link to it from the banner on the new pattern index
  - Add an informative banner and "deprecated" label to the index
- Pattern pages  
  - Remove `Page layouts` and `Design patterns`
  - Move `Error messages` and `Help content` to `Content`
  - Keep `Loading`, `New badge`, `Pickers`, and `Text Fields` as is, but add "deprecated" label and informative banner

New issue: https://github.com/Shopify/polaris/issues/8220

![Image](https://user-images.githubusercontent.com/38329124/215665679-8550628f-925b-4971-a7d1-a17f2d54c22a.png)
