### ISSUE TITLE
Decide whether code examples on patterns pages be expanded

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#8042]
We received the following feedback on the patterns page:

> This is really cool, one observation as I play with the functional prototype (which btw is super helpful to use). On the data picker it feels like we’re selling the code short, rather than have it on part. Just something I thought when I landed on the page.
> We really wanted to make sure the code is super available, but not overshadowing why you’re using it. It’s a subtle balancing act; in previous patterns pages it was all about why. If there are strong feelings we’ve indexed too hard one way or another, we’re trying to find that balance. Want to make sure there’s a live prototype in addition to the annotation pages. Instead of just images as we have before.
> if you’re a repeat user, you’re going to say “ok, I got the pattern, let me get to the code as quickly as I can."

The current behaviour also has this workflow:

1. go to the date picking page
1. show code on the first variant
1. go to third variant
1. how code on the third variant
1. go back to the first variant
1. (i have to show code again)

Here are two initial ideas for how to address these:

#### Always show the example code. 
- This would match the behaviour of our component pages. 
- One risk is that it pushes the Useful to know content lower down, but that’s also content that’s either optional or “embedded” within the example code itself.

#### Default to showing the example code, but allow it to be collapsed. 

- If the user collapses it (or reopens it) carry that behaviour across all other pattern pages.
- This way folks who always want the code don’t need to expand it every time, while folks who never look at the code (e.g. designers) don’t get distracted by it.
- Presumably this is more work to implement, but I'm not sure how much more.

**Comment by johanstromqvist** [comment]
There are two potentially separate problems here:
1. "Selling the code short" – the visibility, availability, showing its value
2. Efficient workflow for experienced users

One thing to call out is that while these are important factors, no one has said they are the _most_ important factors. If we had presented a demo with the live preview up top and code always visible, we may have received feedback that the merchant and design matters were too hidden, and then flipped to optimize for that. With this in mind, I don't think we should discard our hypothesis that the pattern purpose and the education parts are the most important thing. Rather, think about how we can stick to our hypothesis while accounting for the factors that were called out.

I regard "Optimizing for grabbability" as a risk. For patterns to succeed they have to be used appropriately as intended. I think we should make code grabbing super easy, but not on the expense of the educational part.

I see three general opportunities
1. Make "copy code" a quick action outside the disclosed code element. That would provide easy access, improve discoverability, and save builders from a click.
2. Redesign the "show code" toggle to be more appealing and prominent. In its current state I think it _is_ selling the code short. It doesn't feel like a core feature. We should change that.
3. In the future, pattern templates should probably be available in the playroom (completely bypassing pattern docs). That would provide an efficient go-to place for code grabbers, while the docs are the go-to for appropriate usage.

I don't think it's the end of the world to show the code by default, but it's not the direction I believe in. I'd rather try to solve the problems in a way that doesn't conflict with our hypothesis, and then measure successful interactions after shipping the MVP. That said, the persisting toggle state idea is very interesting and could be used regardless of default state.

**Comment by raquelbreternitz** [comment]
This is a great conversation! 

Barring implementation issues, I do like the idea of option 2 for the future. It lets us maintain the discovery moment of the "useful to know" sections for first-time users, and then adapt to any given admin builder's needs in ongoing use of the docs.

And then ideally, it's a small usability improvement we can implement across the component docs as well, say for designers who just want to read over the best practices or developers who already know the code and want to quickly reference a component's props.

**Comment by johanstromqvist** [comment]
Three alternative ideas visualized: [Figma](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4772%3A207696&t=7x6lsO7ISJcOnJeV-1)
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/38329124/212161998-f5535ab6-bafc-4213-b547-a807f4656ee0.png">

## "Page level quick actions"
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/38329124/212162147-f60c546e-f7ab-4d1e-b97b-cdc5c3b4ce95.png">

## "Teaser"
<img width="950" alt="image" src="https://user-images.githubusercontent.com/38329124/212162180-d2fbbd3b-5e19-4bd6-bf36-7dc65d0af7c4.png">

## "Live preview quick action"
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/38329124/212162210-4cb32f8a-4ed0-4d6b-b60c-76ebdcb1a947.png">

**Comment by nblloyd** [comment]
The "teaser" option looks like a great solution to drawing more attention to the code - can we do this?

In JZ's experience, I think the solution is to remember the expanded state for the user so they don't have to constantly show the code if that is their primary objective. That way when you flip between variants, the code will remain visible if you previously expanded it.

**Comment by SeanyB** [comment]
Lots of great ideas here!

### Page level quick actions

This mixes up the logical structure of the page. This top section is likely where we would continue to add metadata to the pattern as a whole (e.g. maintainer). The code is part of the pattern itself, rather than metadata. Also, for patterns with variants, this button would need to copy different code, but it it’s placement makes it look applicable to the entire pattern page, not a specific variant.

### Teaser

This is a very compelling idea, especially if paired with remembering whether the user has expanded this and then applying that to every page they view.  We could also move the **Edit in Sandbox** button next to the Copy icon, so that the actions related to code are close together. 

It would also get rid of this button shift that we currently have:
![button shift](https://user-images.githubusercontent.com/421723/212174967-0ece9b64-e056-4ba6-8671-653bd0f368c7.gif)

### Live preview quick action

There's some risk if we put any buttons on top of the live render that for some pattern at some breakpoint, the button will cover part of the UI. This approach would also be superseded if we adopt the **Teaser** idea above.

**Comment by johanstromqvist** [comment]
Can we make a decision to pursue the "teaser" idea?

If so, we could mark this done and create a dedicated issue
- [ ] Check feasibility with Eng next week
- [ ] Refine and prototype new design
- [ ] Update the template

**Comment by SeanyB** [comment]
Yes, let's do it.
