### ISSUE TITLE
Resource list with selection and no bulk actions bottom padding issue

### ISSUE THREAD

**Issue by dsankar1** [Shopify/polaris-react-archive#8047]
## Issue summary

Resource list with selection and no bulk actions adds bottom padding when rows are selected.
Included screenshots taken from https://polaris.shopify.com/components/resource-list, "With selection and no bulk actions".

## Expected behavior

Resource list bottom padding should remain the same after a row is selected, if no bulk actions are defined.

## Actual behavior

Resource list bottom padding increases after a row is selected, even if no bulk actions are defined.

![image](https://user-images.githubusercontent.com/31108228/212229524-a017d9f2-b363-4921-b911-1d7997297075.png)

## Steps to reproduce the problem

1. Open https://polaris.shopify.com/components/resource-list
2. Select the "With selection and no bulk actions" demo
3. Select any row within the demo

## Reduced test case

https://polaris.shopify.com/components/resource-list

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 10.19.0
- Browser: Chrome 109.0.5414.75 (Official Build) (64-bit)

```bash
System:
    OS: Linux 5.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (16) x64 AMD Ryzen 7 2700 Eight-Core Processor
    Memory: 11.72 GB / 15.60 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.18.1 - /usr/bin/node
    npm: 9.1.3 - /usr/bin/npm
```

**Comment by lukashlavacka** [comment]
The examples on https://polaris.shopify.com/components/resource-item show the same problem, checking checkbox in default example results in the empty padding added under the item.
cc @Shopify/polaris-team

**Comment by alex-page** [comment]
Thanks for raising this. @lukashlavacka or @dsankar1 do either of you want to make a PR to resolve this issue?

**Comment by chloerice** [comment]
I've got a PR ready to go for this and a couple other small CSS bugs, will ship today 🚀
