### ISSUE TITLE
Schedule a final content review before publishing

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#8050]
- [ ] Find and involve both content experts and SMEs
- [ ] Compare content sections horizontally across pattern pages
  - [ ] Check if content fulfills its documented purpose
  - [ ] Check consistency across the pages
  - [ ] Update content guidelines based on observations
- [ ] Make final decision on headline naming

~We plan to publish on Wednesday Feb 1st. Schedule content review during week of 23rd–27th of Jan.
[Figma](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4806%3A225138)~

**Comment by selenehinkley** [comment]
👋 when you get to this, please update the titles to sentence case for:
- Resource Index layout ---> Resource index layout
- Resource Details layout ---> Resource details layout
 
![Image](https://user-images.githubusercontent.com/18617698/216689888-54979382-f86a-465b-9963-befb8e61ed22.png)

![Image](https://user-images.githubusercontent.com/18617698/216689950-8a3ae90a-5bce-45ea-8f3b-63ecaebc0a16.png)

**Comment by johanstromqvist** [comment]
Let's release this without a broader content review.

**Rationale**
- We did usability testing and decided the MVP is good enough to release.
- The MVP has plenty of imperfections. It's fair to expect a lot of learnings to come and lots of changes to follow. Polishing content isn't a priority right now.
- If we ship sooner, we'll provide value sooner and get feedback sooner.

I'm closing this, but could reopen if needed.

cc @SeanyB
