### ISSUE TITLE
Redesign code example feature to make copying faster

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#8052]
Problem (As discussed in issue #8042)
- We're selling the code short
- Quickly grabbing code has too many interactions

Todos
- [x] Check feasibility with Eng
- [x] Refine and prototype new design
- [x] Update the figma template
- [ ] Implement

Design Requirements
- [x] Builders can expand and collapse the code example
- [ ] ~The element's state persists across pages (if feasible)~
- [x] Builders can see that there is code inside regardless of state
- [x] Builders can access the copy button regardless of state

[Design Figma](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4904%3A231382&t=7ZUubduecj1AHMhT-1)

![Option 1](https://user-images.githubusercontent.com/107587671/214955955-faa69485-98a2-4136-9a78-23c5cbcf22ac.gif)

Engineering Requirements
- [ ] Overlay appears on top of code when in collapsed mode
- [ ] Overlay says "<eye> Show code" with a coloured background
- [ ] Clicking overlay expands the code and removes the overlay
- [ ] Expanding the code in this way also updates the **Show code** button above to say **Hide code** (stays in sync with the collapse/expand state)
- [ ] Collapsing the code with the **Hide code** button causes the overlay to reappear when hovering over the collapsed code

**Comment by jesstelford** [comment]
Yeah mate, we can do this (and I quite like this "teaser" pattern; very nice balance!).

> _The element's state persists across pages (if feasible)_

There's one possible gotchya here: There may be a brief "Flash of incorrect state"; the state of open/closed would need to be stored in the user's browser, but we have to render the page on a server first (to send the initial HTML to the browser). Very similar to the familiar "Flash of light-mode" when offering a dark mode toggle.

The steps go roughly like:

1. Server serves the initial HTML, without knowledge of what's stored in the user's browser (ie; always renders the "default" open/close state)
2. Browser receives and renders that initial HTML (ie; the user sees the default open/close state)
3. The browser then executes the JS which loads the user's preference for open/closed
4. If the user's preference differs from the default open/closed state, the page is re-rendered, which may cause a "jump" as things shift around.

There's a workaround/fix that's common with dark-mode toggles we may be able to employ here, but I wanted to raise this as a potential issue.

**Comment by johanstromqvist** [comment]
Thanks Jess!

I wonder if it's worth it. The idea is cool, but it's not essential imo.

Since the teaser idea makes copy/paste code quick and easy, the only outstanding use case is if a builder wants to inspect the code of multiple patterns and that the extra click would be frustrating. I think we might be over indexing on an edge case that may or may not be important. 

It would be better to set ourselves up to learn about these things from the MVP, i.e. start thinking about what analytics we could gather and how we might wanna survey builders.

What do you think @jesstelford? Any thoughts @SeanyB?

**Comment by SeanyB** [comment]
Super helpful context, @jesstelford. I think it's totally reasonable for us to ship without this persisting across pages for our first version. We can learn and iterate as needed.

I'll say up-front, I think we'll get some feedback internally that always fully open is more desirable than the teaser if we can't persist state across pages. But I'm comfortable shipping the teaser style without persistence and asking getting that feedback from others (1P and 3P designers & devs) before making any changes.

**Comment by bernardojoaogarcia** [comment]
First stab at this issue can be found here: https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4962%3A235756&t=BkFf6XmMBw880F6W-1 👍

**Comment by johanstromqvist** [comment]
Commented in Figma

**Comment by bernardojoaogarcia** [comment]
Thank you for the comments! I added some additional mocks to the file to address some of the questions + feedback that you had.

**Comment by bernardojoaogarcia** [comment]
@jesstelford @gwyneplaine would love to get both of your feedback regarding the feasibility of executing a change like this (Image attached) 

![Image](https://user-images.githubusercontent.com/107587671/214129204-9c978f69-b36e-45ca-b9c8-440b69449c55.png)
![Image](https://user-images.githubusercontent.com/107587671/214129203-e07e3ac1-d5f6-4d8d-9df7-a3a7dddc0c29.png)

**Comment by bernardojoaogarcia** [comment]
The intention was to make the code more accessible, which resulted in a slight change to the expand/collapse experience. Throughout my design exploration and UX feedback from @johanstromqvist, it became apparent that it was redundant to have 2 headers for the playroom section, both with different controls 1. Edit in sandbox + Show code 2. Copy code. Here is an alt option to this solution with both headers.

![Image](https://user-images.githubusercontent.com/107587671/214131263-e1238cd1-80e0-48a8-a4ea-9e159055c85e.png)
![Image](https://user-images.githubusercontent.com/107587671/214131264-543dd60c-164a-447f-9ec7-5e7688b08013.png)

**Comment by bernardojoaogarcia** [comment]
And finally, here is a mock with no labels. Labels were also intentionally added to illustrate the action. 

![Image](https://user-images.githubusercontent.com/107587671/214131798-77d6944c-ddb2-4c14-ab9c-45a823e645b6.png)
![Image](https://user-images.githubusercontent.com/107587671/214131799-012ef3d6-f8cb-4abf-8b41-5a62e231c40f.png)

**Comment by johanstromqvist** [comment]
Thanks @bernardojoaogarcia!
- I think a single merged tool bar is preferred, if feasible
- I think labels are a must for two reasons. Expand/collapse icons aren't immediately obvious, and I think it should be clear that "edit" opens the Sandbox rather than just makes the code 
- We could set the height to 2.5x line heights, to show that there's more content to be found in there.

**Comment by gwyneplaine** [comment]
No engineering blockers here that I can see. Agree with @johanstromqvist's point around labels, though the first point around obviousness could be offset by a tooltip (if we decide saving space is important here from a user experience point of view).

**Comment by jesstelford** [comment]
One clarifying question: Do you expect the user to be able to scroll the code window when in the "collapsed" state? Ie, is the expand/collapse simply changing the height of the textarea?

All looks good to me 👍

**Comment by johanstromqvist** [comment]
Thanks friends! 🙌

> Do you expect the user to be able to scroll the code window when in the "collapsed" state?

Yeah, good Q! We're discussing that [in this Figma thread](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE?node-id=4962:235765#349735757). @bernardojoaogarcia is looking into it. Just toggling the height might be a bit unconventional. I think I would expect it to be overflow hidden and some affordance signalling that. What's your take?

**Comment by johanstromqvist** [comment]
@SeanyB Once we have the design for this in place, I think we could prioritize the eng task a little lower in favour of adding pages and creating code examples. We could potentially use the existing solution and default to open until we've shipped these improvements. Thoughts?

**Comment by bernardojoaogarcia** [comment]
Some adjustments have been made to the original collapse/expand labels. "Show code" & "Hide code" are being proposed. Regarding the question around scrolling the code when the code is collapsed: Since an overlay + plain button is being proposed as a hover state, we wouldn't need to consider a scroll bar for when the code viewport is "hidden". Here is the final mock for review https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=5186%3A247717&t=beE1p57GMO805c5b-1 @johanstromqvist @SeanyB

**Comment by bernardojoaogarcia** [comment]
![Option 1](https://user-images.githubusercontent.com/107587671/214955955-faa69485-98a2-4136-9a78-23c5cbcf22ac.gif)

**Comment by johanstromqvist** [comment]
Thanks @bernardojoaogarcia! Looks great, good job!

**Comment by SeanyB** [comment]
> @SeanyB Once we have the design for this in place, I think we could prioritize the eng task a little lower in favour of adding pages and creating code examples. We could potentially use the existing solution and default to open until we've shipped these improvements. Thoughts?

I just realized that I didn't reply to this and we're still defaulting to entirely hidden code in staging right now. Let's default to open for now (I'll create a separate task) and we can take this on post-release.
