### ISSUE TITLE
Update Polaris components to only show focus state when navigating with keyboard

### ISSUE THREAD

**Issue by mrcthms** [Shopify/polaris-react-archive#8053]
We currently use a focus-ring to show a merchant which element is currently in focus. This is useful particularly for users that don't use a traditional pointer device to navigate through the admin. We currently use the `:focus` CSS selector to add these focus rings to interactive elements. 

Whilst this is an important accessibility necessity, it can leave the admin looking very busy for merchants that do use a traditional pointer device, with focus rings appearing on every interaction. 

There is a CSS selector named `:focus-visible`, which allows the browser to determine when to show the focus state depending on the input device that controls the focus state, and the element in question. This will allow us to persist the vital focus state visibility for users navigating the admin via keyboard, but will leave the admin feeling cleaner for those merchants using a mouse or other pointer device.

https://github.com/Shopify/polaris/issues/8053#tasklist-block-7640fea2-eaff-49d9-bb62-5c59ffc9de0d

**Comment by ouellettejordan** [comment]
@mrcthms is moving the work from web `web-config' repo to `web` repo. Still in progress.
