### ISSUE TITLE
Update styling of "Useful to know" cards

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#8056]
We want to adjust the design of the **Useful to know** section so that the images don't visually blend together.

- [x] Add a border to images.
- [x] Increase **vertical** margin between the images to `32px`.
- [x] ~Ensure a 1/3 to 2/3 horizontal layout between the text and images~
  - Moved to #7937

[Figma designs](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4622%3A191580&t=Wfh8XdUzAQkojg9N-1).

![Image](https://user-images.githubusercontent.com/421723/212771597-80bd6d4f-6322-42bc-a45e-d0c50d5e7a16.png)

**Comment by jesstelford** [comment]
> ~Ensure a 1/3 to 2/3 horizontal layout between the text and images.~

~How does this behave responsively? At some point, the 1/3 area for text will get too small to be readable, so we'll need to switch to a stacked layout (text above/below the image). That has the impact of making the images full width, which in turn increases their height, meaning they can take up significant vertical space on mobile, so should we limit their height in those cases to something reasonable?~

Moved to https://github.com/Shopify/polaris/issues/7937#issuecomment-1386293688

**Comment by johanstromqvist** [comment]
- [x] Borders look good 👍 
- [ ] Spacing between subsections still looks like 16px (`--p-space-4: 1rem;`)
- [x] I crossed off the 1/3 + 2/3 task from this issue


![Image](https://user-images.githubusercontent.com/38329124/214436843-6792cde5-82ed-4592-99ce-1fccf5689568.png)

**Comment by SeanyB** [comment]
The last item (Increase vertical margin between the images to 32px.) is complete
