### ISSUE TITLE
Add pattern page: Resource index layout

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#8061]
See [Figma](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4806%3A212779&t=Wfh8XdUzAQkojg9N-1) from design issue #7931.

**Comment by johanstromqvist** [comment]
Happy to review! @gwyneplaine please let me know when staging is available.

**Comment by johanstromqvist** [comment]
Beauty!
