### ISSUE TITLE
Add pattern page: Resource details layout

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#8062]
See [Figma](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4806%3A218145&t=Wfh8XdUzAQkojg9N-1) from design issue #7933.

- [x] Replace the third useful to know image asset. (cc: @raquelbreternitz)

**Comment by johanstromqvist** [comment]
Still seeing "Coming soon". Tried refreshing with cleared cache. 

![Image](https://user-images.githubusercontent.com/38329124/215192991-19f3ce9c-baf5-41c4-8831-a0eda244e456.png)

**Comment by SeanyB** [comment]
Shipped, to be available in next staging release.

**Comment by gwyneplaine** [comment]
On [staging](https://polaris-staging.shopifycloud.com/patterns/resource-details-layout) and ready for eyes @johanstromqvist

**Comment by SeanyB** [comment]
Thanks, @gwyneplaine!

- [x] I've added a [comment in Figma](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE?node-id=4806:218145#367048837) to replace the third useful to know image asset. (cc: @raquelbreternitz )

**Comment by raquelbreternitz** [comment]
Created [this PR adding the image ](https://github.com/Shopify/polaris/pull/8327)which is now ready for review.

**Comment by johanstromqvist** [comment]
I'm closing this issue. Let's create new specific issues if needed.
