### ISSUE TITLE
Consolidate pattern rendering logic into route template

### ISSUE THREAD

**Issue by jesstelford** [Shopify/polaris-react-archive#8073]
As part of the prototype, we made the decision to limit scope by only building rendering logic for the Date picker page.

We now wish to rendering more patterns using the same logic (#8061, #8062).

Actions:

- [x] Move Date Picker page to a dynamic route so it's rendered for all patterns
- [x] Extract Date Picker content into separate JSON file
- [x] Load correct JSON file based on route
- ~[ ] Validate loaded JSON with [`typebox`](https://github.com/sinclairzx81/typebox)~
- ~[ ] Replace nav / index page loading markdown with the JSON files~
- [x] Support "Single tab" usecase

**Comment by johanstromqvist** [comment]
Is there anything that needs design review here? Or is the review meant for @gwyneplaine?

**Comment by SeanyB** [comment]
Moving to done, since this is on the prototype branch.
