### ISSUE TITLE
Encourage 1P teams with existing resource details pages to update

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#8092]
As a follow up to documenting the preferred "Resource details layout" pattern, we should encourage existing 1P feature teams to adopt it. We should also provide an action plan that makes the transition easy for the team and without compromising the merchant experience.

Draft action plan (As suggested by @ry5n in #8058 )
1. Add footer actions to "More actions" in the page header. Keep duplicates in the footer. Remove `save` action if there is one.
2. After 6 weeks, remove the actions from the footer. Add a non-interruptive nudge informing merchants that the actions have moved.
3. After 6 weeks, remove the nudge.

**Comment by SeanyB** [comment]
This sounds like a good transition plan. We may want to be prescriptive about how to nudge so that all of the product / 1P app teams can implement it consistently without design cycles. Perhaps locating it where the footer actions used to be would help.
