### ISSUE TITLE
Remove one "Useful to know" item on Resource index layout page

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#8108]
- [ ] Remove the whole item with the text `Show the most common actions in the page header and place the rest under "More actions".`

This is likely not a decision that builders make.

![Image](https://user-images.githubusercontent.com/38329124/213579434-0e78fba6-7729-4be7-aa97-7f51afc5fc22.png)

**Comment by johanstromqvist** [comment]
@raquelbreternitz We should just remove this from the spec. I don't think it has been implemented yet.

**Comment by SeanyB** [comment]
I believe this is possible to control, up to a point, with the Page component API. There is an [Action Group](https://polaris.shopify.com/components/page) prop that you can use to group actions and even give them a custom name. However, at smaller sizes, Polaris automatically regroups action buttons.

**Comment by SeanyB** [comment]
Discussed in meeting - aligned on removing this item from the pattern.

**Comment by johanstromqvist** [comment]
Closing this. I believe this was removed from the design spec before the page content was implemented.
