### ISSUE TITLE
Create pattern assets template

### ISSUE THREAD

**Issue by raquelbreternitz** [Shopify/polaris-react-archive#8122]
Clean up "Visual Assets" page and create a Pattern Assets template based on the visual rules we've decided

**Comment by johanstromqvist** [comment]
Note regarding visual examples

- Default to Puzzlify when possible
- Default to generic widely applicable examples over specific recognizable ones

^ These can be debated and fleshed out, but it would be great to have any documented guidelines that we can test and update as we learn more.

**Comment by raquelbreternitz** [comment]
Thanks for note!

> * Default to Puzzlify when possible

I thought the decision was actually to only use Puzzlify for app-related content, and default to Gordie's gifts for admin content. I like keeping it more generic however.

**Comment by johanstromqvist** [comment]
True, it was! The question is what to default to when a pattern is relevant to both. Happy to debate this.

**Comment by raquelbreternitz** [comment]
I guess they could all be considered relevant to both, I think I was functioning on the assumption that it would be gordie's gifts unless obviously app related.
