### ISSUE TITLE
Revise spacing in the pattern's page - Apply larger token values

### ISSUE THREAD

**Issue by bernardojoaogarcia** [Shopify/polaris-react-archive#8137]
Review and adjust our pattern page’s spacing to reduce visual crowding. Currently, the assigned spacing tokens within the selected tab feel compressed in sections like "How it helps merchants," making the content tougher to absorb. Balance out the spacing accordingly and give it more breadth. Reference other pages within the doc site as precedent.

![Image](https://user-images.githubusercontent.com/107587671/214400706-1f3d7f2d-f5da-4aa0-9dff-94292f3d7ff5.png)

![Image](https://user-images.githubusercontent.com/107587671/214401689-761640eb-a2a9-4cc7-a640-58915943c721.png)

**Comment by johanstromqvist** [comment]
@bernardojoaogarcia, is the general recommendation here to add more space between content?
