### ISSUE TITLE
Consider whether puzzle product attributes are good examples of app settings

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#8140]
The example settings in the `app settings layout` pattern are "interjambs" and "puzzle dimensions". These are more product attributes than typical app settings, which affects the clarity of the page. We could identify simple and typical app settings, and update the assets.

- [ ] Decide if we should keep or update the assets

![Image](https://user-images.githubusercontent.com/38329124/214200104-509c15ad-a25a-4eb3-b89e-a26a000dffbd.png)

cc: @raquelbreternitz @SeanyB

**Comment by raquelbreternitz** [comment]
Great point. 

Here are some examples of app settings from random apps I have on my test store:
<img width="926" alt="Screenshot 2023-01-24 at 2 25 09 PM" src="https://user-images.githubusercontent.com/13204374/214402837-e2cfb877-1cf3-49f7-a1a3-9c08d741a945.png">
<img width="782" alt="Screenshot 2023-01-24 at 2 31 21 PM" src="https://user-images.githubusercontent.com/13204374/214402861-6f6541c5-2500-4af4-99a6-dd040d9c21b3.png">
<img width="782" alt="Screenshot 2023-01-24 at 2 32 23 PM" src="https://user-images.githubusercontent.com/13204374/214402877-a8abbd43-cb48-40a2-a0f1-23732ef6e91c.png">


Interestingly/strangely, I noticed most apps didn't have a settings subnav, at least of the random assortment I had installed — including 1P apps 🤔 POS has a different usage than I expected, and product reviews is still using the old nav. I added several of the 1P apps that pass the App Design Guidelines to try to find more examples, but still didn't find many! 

Hopefully publishing this pattern may help consolidate this, the "where to find app specific settings in the admin" user question has a lot of slightly different answers, right now.


At any rate, based on the above examples, what kinds of content lives under settings also feels somewhat open. As a merchant I imagine I could determine my puzzle dimensions + interjamb style globally in the app settings or puzzle by puzzle, depending on what I prefer or do more often. But if we want to simplify matters, we could always just change it to something more common like "Shipping return address."

**Comment by johanstromqvist** [comment]
:chefs-kiss:

> Interestingly/strangely, I noticed most apps didn't have a settings subnav

Oh true! Would be great if that was consistent, but I think it's out of scope for the page layout itself and it would probs require some sleuthing to make a viable recommendation. However, it would be very satisfying to document settings experiences as a whole at some point.

> But if we want to simplify matters, we could always just change it to something more common like "Shipping return address."

That sounds like a great route forward. Whatever is easy to recognize as a setting and that would be relevant for the story in the "Useful to know" section. Would you wanna identify a few settings and update the assets? Perhaps a lower priority until we've got the general foundation covered, considering we _could_ ship it as is.

**Comment by johanstromqvist** [comment]
Keep
