### ISSUE TITLE
Fix table of contents bug in date-picking pattern page

### ISSUE THREAD

**Issue by gwyneplaine** [Shopify/polaris-react-archive#8141]
![Image](https://user-images.githubusercontent.com/12119389/214216308-48a7bc76-16e3-4ebd-8666-562d12501bea.png)

**Comment by jesstelford** [comment]
We've looked into this: It's a timing bug that only exists on dev; The HTML ids aren't ready when the TOC generation code runs.

In production we don't have that problem because the pages are generated at build time and so the HTML will always be ready.
