### ISSUE TITLE
[IndexTable] Inconsistent bottom scroll container when resizing the page

### ISSUE THREAD

**Issue by sam-b-rose** [Shopify/polaris-react-archive#8143]
## Issue summary

The IndexTable bottom scroll container is hidden initial on render (see Orders or Products page). The IndexTable will show/hide the scroll container when horizontally resized.

## Expected behavior

The IndexTable bottom area with rounded borders should be shown on initial render. The area should also not toggle visibility on resizing of the screen.

## Actual behavior

<details>
<summary>Toggling of visibility when resizing</summary>
<img src="https://user-images.githubusercontent.com/11774595/214310188-884a6d3c-47be-477c-95a5-357f876df12d.gif" alt="The bottom border element is shown/hidden when resizing the screen">
</details>

## Steps to reproduce the problem

1. Visit the Orders page on the admin
1. Resize the window

## Reduced test case

Visit [CodeSandbox example](https://codesandbox.io/s/dr1dul?module=App.js&file=/App.js:0-446) and resize the preview window to see the bottom scroll container jump around (appear/disappear)

**Comment by jesstelford** [comment]
> The IndexTable bottom area with rounded borders should be shown on initial render.

Agreed; the borders should be rounded. We've fixed this in https://github.com/Shopify/polaris/pull/9486

> The area should also not toggle visibility on resizing of the screen.

This one is tricky; I think we have a JS resize listener which inserts the scroll container, so the browser can't know to set aside space for the scrollbar until after the page is rendered, and our JS executes / detects a viewport change. This could lead to scroll jank on smaller screens where the table is apparently fully rendered, but then the horizontal scroll container is injected which pushes everything below it down.

We could make that scroll space be always visible, but this would result in an apparent extra padding at the bottom of the table even when there's no horizontal scroll. I think that would be incorrect behaviour.

I think the behaviour of the scroll area appearing after JS calculations are complete is the correct one.

**Comment by sam-b-rose** [comment]
Agreed. Testing this again in production, the behavior seems proper. Also, confirmed the border corner are now rounded 💯 Marking this issue as closed–thanks, Jess!!
