### ISSUE TITLE
Document "Common actions" patterns

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#8164]
We're currently not offering coherent guidance on common actions and when/where/how merchants expect them. The result is more difficult decision making for builders and an inconsistent experience for merchants.

Action examples
- Add, view, edit, delete
- Next/previous
- Open/close
- Navigate to internal/external page
- Etc

Action components
- Button (group)
- Link
- Pagination
- [component]

[Component quality: buttons and links](https://docs.google.com/document/d/1vc_U-x_DnGRTgUrwHMQnmNZ1odtzME7vT1uJynoRt_w/edit)
[Admin UX – Workplace conversation](https://shopify.workplace.com/groups/1294395484626415/permalink/1309406043125359/)

![Image](https://user-images.githubusercontent.com/38329124/214911982-c72d0aac-5a5b-4be6-8f72-b1b61901a692.png)

![Image](https://user-images.githubusercontent.com/38329124/214917528-0c1efdd1-0528-4919-b09b-cea0d7c28e33.png)

**Comment by nblloyd** [comment]
@johanstromqvist Can you expand on what the common actions are in the example you shared?
