### ISSUE TITLE
Review code examples

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#8169]
### Design tasks
- [ ] Make judgement call whether the code examples make sense visually
  - [ ] App settings layout
  - [ ] Resource details layout
  - [ ] Date picking: single date
  - [ ] Date picking: date range
  - [ ] Date picking: date list

### Eng tasks
- [ ] Make judgement call whether the code examples are educational enough to move builders forward
  - [ ] App settings layout
  - [ ] Resource details layout
  - [ ] Date picking: single date
  - [ ] Date picking: date range
  - [ ] Date picking: date list
  
<details><summary>Previous thorough checklist</summary>
- Invite FEDs from Polaris and Core to test usage
- Make sure each example
  - Are on Polaris mainline
  - Throw no linting errors
  - Have the defaults we want to promote
  - Mirror the image assets
  - [Other quality checks...]
</details>

**Comment by johanstromqvist** [comment]
Renamed and simplified the review to something more quick and scrappy. @jesstelford and @gwyneplaine, please give the examples a look from a dev POV and see if they are meeting our new and looser requirements, i.e: 
❌ Not copy/pastable for production
✅ Guiding enough to learn from

**Comment by jesstelford** [comment]
All the examples earn a ✅ from me, however I'm not familiar enough with the shopify/web codebase, so might not be the best person to make the final call if that's our primary audience.

**Comment by johanstromqvist** [comment]
Thanks @jesstelford! @sophschneider, would you like to give us a browse through the code and flag anything that seems too odd?

**Comment by johanstromqvist** [comment]
Closing this as we'll revisit code documentation in the next project
