### ISSUE TITLE
Add alt text to all images in patterns pages

### ISSUE THREAD

**Issue by gwyneplaine** [Shopify/polaris-react-archive#8170]
Add the alt text from [this document](https://docs.google.com/document/d/1Yi4HX03-zAHTa_ehxlub7DYKeq3_ErT9WvQDH7GTfz0/edit) for all of the image assets in our four patterns.

- [ ] Alt text added to App settings layout
- [ ] Alt text added to Date picking
- [ ] Alt text added to Resource details layout
 - [ ] Alt text added to Resource index layout

**Comment by SeanyB** [comment]
@raquelbreternitz and @selenehinkley - just sync up on who is taking this on. I think both expressed interest.

**Comment by raquelbreternitz** [comment]
I'll be taking this on 👍

**Comment by raquelbreternitz** [comment]
For my use, list of alts needed:

- [x] Date Picker - single list
    - [x] Cover image
    - [x] Usage 1
    - [x] Usage 2

- [x] Date picker - date range
  - [x] Cover image
  - [x] Usage 1
  - [x] Usage 2
  - [x] Usage 3

- [x] Date picker - date list
  - [x] Cover image
  - [x] Usage 1
  - [x] Usage 2
  - [x] Usage 3

- [x] App Settings
  - [x] Cover image
  - [x] Usage 1
  - [x] Usage 2
  - [x] Usage 3

- [x] Resource index
  - [x] Cover image
  - [x] Usage 1
  - [x] Usage 2
  - [x] Usage 3

- [x] Resource details
  - [x] Cover image
  - [x] Usage 1
  - [x] Usage 2
  - [x] Usage 3
  - [x] Usage 4
  - [x] Usage 5
 
- [ ] Edit down to make as concise as possible

**Comment by selenehinkley** [comment]
@gwyneplaine and @SeanyB Here's the current version of @raquelbreternitz's [alt text](https://docs.google.com/document/d/1Yi4HX03-zAHTa_ehxlub7DYKeq3_ErT9WvQDH7GTfz0/edit?usp=sharing). We wanted to share early so you can see why the longer alt text format was chosen as the approach. She'll get to the edits I suggested when her power is back online.

**Comment by SeanyB** [comment]
I've provided edits and this is now ready to be implemented.

**Comment by raquelbreternitz** [comment]
~Closing as~ addressed in [this PR] (https://github.com/Shopify/polaris/pull/8335) (not closing, for future reference issues won't close until PRs are merged)
