### ISSUE TITLE
Do we want to track pattern page usage?

### ISSUE THREAD

**Issue by jesstelford** [Shopify/polaris-react-archive#8176]
We already have GA on our site which tracks page loads/views, do we want any patterns-specific events or tracking implemented?

Keep in mind that a majority of our users are builders, who often use ad blockers, so data accuracy may be an issue.

**Comment by SeanyB** [comment]
I don't think it's important/valuable to track page loads/views on the patterns pages. At best, I think we'll get vanity metrics, but they won't be a strong signal of success. And, like you said, we can't feel totally confident in the data.

**Comment by johanstromqvist** [comment]
I raised the same question in #8068.

Personally I'd be interested in most trackable interactions. Even if the data is of low quality, I think it could both let us compare values and imply trends (e.g. shitty data from March vs shitty data from April), and give us ideas of what better metrics and methods might look like. This is an assumption tho, I don't have much experience working with such data. Another assumption of mine is that it would be low effort to implement. It's not a priority.
