### ISSUE TITLE
Pattern search results need correct heading

### ISSUE THREAD

**Issue by jesstelford** [Shopify/polaris-react-archive#8178]
1. Currently showing "Foundations" instead of "Patterns":
![Image](https://user-images.githubusercontent.com/612020/214998940-24cb5a11-6294-4440-8c45-0a84f2e26cb8.png)

2. Cover image missing.

**Comment by SeanyB** [comment]
Great catch, @jesstelford.

Are there any technical challenges to this, or just work to be done? 
Any issues using the specific cover images from the Patterns overview page for the search results?

**Comment by jesstelford** [comment]
No challenges, was pretty straight foward once I understood the code powering search 👍 

https://github.com/Shopify/polaris/pull/8433

**Comment by jesstelford** [comment]
Fixed and shipped 👍 
<img width="854" alt="Screenshot 2023-02-27 at 11 15 56 am" src="https://user-images.githubusercontent.com/612020/221446361-8047b6bc-a33b-49b2-9891-afefcf5cdfdd.png">
