### ISSUE TITLE
Implement full underline on stylelint polaris in VSCode

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#8190]
Fixed by https://github.com/stylelint/vscode-stylelint/pull/358

Right now, failures in VSCode only underline the first letter of the line. This makes it hard to notice/hover over. This is because the endline isn't provided in our custom rules, there are several solutions in this stylelint issue https://github.com/stylelint/stylelint/issues/5694

![Image](https://user-images.githubusercontent.com/20652326/215148407-4ee1e761-bb4d-41ee-8ea9-440076cc192d.png)

**Comment by sophschneider** [comment]
In the stylelint issue I linked above, supposedly `selector-no-vendor-prefix` is fixed yet in my VSCode it still only underlines one char when I enable this rule.

**Comment by sophschneider** [comment]
So it looks like the problem is coming from the VSCode Stylelint plugin which is responsible for underlining failures. They actually have a PR up https://github.com/stylelint/vscode-stylelint/pull/358 that is supposed to implement it, but it hasn't been merged yet. It isn't stale, there was activity about 2 weeks ago

**Comment by sophschneider** [comment]
Once the Stylelint VSCode PR is merged, we will have to add range data (`endLine`, etc.) to our custom rule reports, then we should have full range underlines!

**Comment by BPScott** [comment]
> Once the Stylelint VSCode PR is merged, we will have to add range data (endLine, etc.) to our custom rule reports, then we should have full range underlines!

It's worth pointing out that you're free to add range data at any point. Stylelint on the command line will make use of it, and then when VSCode adds support it will be leveraged there too. You're not blocked by Stylelint VSCode here.
