### ISSUE TITLE
Add layout disable workaround on the coverage site

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#8193]
We disabled layout rules [temporarily](https://github.com/Shopify/polaris/pull/8167) but we need a workaround to still track those failures on the coverage site

**Comment by aaronccasanova** [comment]
Discussed offline and the consensus was creating a temp/draft PR, with the layout rules enabled, and using snapshot releases from that branch in the coverage site. New snapshots will only need to be created if there are changes to `stylint-polaris` and only until we re-enable the layout rules on main. I plan to kick that off today and will link the draft PR here.
