### ISSUE TITLE
Proposal: Require onChange and value properties for TextField

### ISSUE THREAD

**Issue by buggy** [Shopify/polaris-react-archive#82]
# Issue summary
`onChange` and `value` are effectively required for TextField. The only use case for not defining `onChange` is when the TextField is read only and the use case for not setting `value` is a read only text field with no value.

I think it might make sense to change the TypeScript interface definition to require those two properties.

## Expected behavior

The proposal is pretty simple. Change from

```typescript
value?: string
onChange?(value: string): void
```

to

```typescript
value: string | undefined
onChange: ((value: string) => void) | undefined
```

**Javascript:** I don't think this is a breaking change for Javascript users. The values for `props.onChange` and `props.value` are `undefined` whether you use `onChange={undefined}` and `value={undefined}` or don't provide those properties. It means that any old code should work the same.

**TypeScript:** This is a breaking change for TypeScript but the compiler should pick it up. To keep the existing behavior developers would need to add `onChange={undefined} value={undefined}` but in most cases they should be defining them anyway. The benefit is that TypeScript compatible editors will type hint that `onChange` and `value` are required (which effectively they are).

## Specifications

- Polaris version: 1.0.3
- React version: N/A
- Browser: N/A
- Device: N/A
- Operating System: N/A

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by lemonmade** [comment]
Hmm, this is a tricky one. I lean towards leaving it as-is because, as you said, a readonly (or disabled) field does not really require an `onChange`, and actually requiring one means that consumers will sometimes need to do `onChange={undefined}`, which satisfies the type checker but kind of muddies intent.

**Comment by buggy** [comment]
While it is a little thorny I lean towards optimizing for the most common use case. The number of times I need a read only text field is very small compared to the number of times I need a regular text field.

For a Javascript developer it will make no difference. They can continue not providing it.

This proposal only impacts people using TypeScript who want a read only input field. IMHO if you're using TypeScript then you've already decided that a little bit of extra code to get type checking and intellisense in the IDE is worth it.

To provide some context, I only thought about this after reporting a bug about text fields not working properly because it wasn't clear that you need to implement `onChange` and `value` to allow people to type in them. Implementing them solves that but it's different to regular inputs that use `defaultValue` or `defaultChecked`.

Another solution might be to change the documentation so that `value` and `onChange` appear in the example code unless `readOnly` is true although I don't find it as useful as having intellisense support.

**Comment by lemonmade** [comment]
I'm going to open this issue up on our internal repo to discuss. You make some good points, I still feel not 100% on it thought. Will update here once we've talked it through.

**Comment by dfmcphee** [comment]
Thanks for the suggestion @buggy. We decided to go ahead with this change. It is now part of the v2 beta.
