### ISSUE TITLE
Remove current pattern index from site IA

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#8220]
Based on the decision from #8024 

Design tasks
- [x] Write copy for the banner on the new pattern index
- [x] Write copy for the banner on the old pattern index
- [x] Find appropriate location for legacy/deprecated content (site-wide)

Eng tasks
- [x] Move the current index to new location index and remove it from general IA, nav, search, etc
- [x] Update the new pattern index banner copy and link to the new location for old index
- [x] Remove `Page layouts` and `Design patterns` pages
- [x] Move `Error messages` and `Help content` pages to the `Content` section
- [x] Add "legacy" label and informative banner to `Loading`, `New badge`, `Pickers`, and `Text Fields` pages
- [ ] Complete fast-follow tasks in [this comment](https://github.com/Shopify/polaris/issues/8220#issuecomment-1442238819)

**Comment by selenehinkley** [comment]
Sharing the [working doc](https://docs.google.com/document/d/1V2PA1HAOfPG8QZ4d3zwesq8fCk4rZiEiF1F48DdGMgU/edit) of the banner, old index page badge, and URL approaches. 

Decisions that appear to be made so far (sharing for visibility and aligment):
- hierarchy for the new index page banner copy is aligned on and the first draft is in decent shape (going to take another editing pass before asking for final feedback)
- use the `Legacy` badge on the old index page (instead of `Deprecated`) and scrap the banner for this page as the legacy badge communicates the same message in a concise way
- no need to add banners to each of the legacy pattern pages
- URL format: 'polaris.shopify.io/patterns/legacy/[pattern name]'

*convos and rationale provided in the [working doc](https://docs.google.com/document/d/1V2PA1HAOfPG8QZ4d3zwesq8fCk4rZiEiF1F48DdGMgU/edit)

cc: @johanstromqvist @nblloyd @SeanyB @gwyneplaine @jesstelford

**Comment by johanstromqvist** [comment]
Thanks Selene! ✨ 

> use the Legacy badge on the old index page (instead of Deprecated) and scrap the banner for this page as the legacy badge communicates the same message in a concise way

I think it would still be very useful to include a banner that clarifies what legacy means in this context and what to expect. Although, we can skip the idea to place banners on each respective pattern page. What do you think?

**Comment by selenehinkley** [comment]
Sounds good to me, @johanstromqvist! We'll scrap having one for each of the legacy pattern pages, but keep the one for the legacy index page. Here's the copy I'm proposing for both banners (based on the exploration in the [working doc](https://docs.google.com/document/d/1V2PA1HAOfPG8QZ4d3zwesq8fCk4rZiEiF1F48DdGMgU/edit
)): 

**Pattern index page (new):**
The documentation of Shopify admin patterns is now consistent, scannable, and includes code guidance. [Join the discussions](https://github.com/Shopify/polaris/discussions?discussions_q=label%3APattern) around patterns. Explore the [legacy patterns documentation](_link to the legacy patterns index_).

**Pattern index page (legacy):**
These patterns still have useful UX guidance, but don't follow the [new documentation format](_link to new patterns page index_) or include code guidance.

**Comment by gwyneplaine** [comment]
Pending decision around whether or not to remove design-patterns and page-layout pattern pages without fallbacks. 
https://github.com/Shopify/polaris/pull/8339#issuecomment-1430477740

**Comment by SeanyB** [comment]
>> Sean: let's remove them both
>
>Jess: Agreed 100% - their content is out dated and we don't want folks stumbling on it and getting confused!
>
>> Sean: I'm not concerned if the URLs result in 404s
>
> Jess proposal: Have the pages 404 (good to indicate "This thing is gone" rather than redirecting to the index page where they might still hunt for the "Page layouts" pattern and get frustrated), and also include a note that it's been removed + link to either the new page-based layouts, or to the pattern index page.
>
> That way, we catch anyone who has bookmarked it, or if there's a latent link from shopify.dev, a blog post, or google, etc, and redirect them to where they probably want to go to find the latest info. Nothing more frustrating than 404s IMO.

Let's rip the band-aid off here and just use our existing 404 page without adding any redirects. Anything we can do to help us release this sooner so that we can unpack some of the more complex decisions for future patterns.

**Comment by jesstelford** [comment]
Ok, we've implemented the 404 strategy 👍

**Comment by johanstromqvist** [comment]
- [x] Update the index page banner copy to: `Our pattern documentation is evolving. [Join the discussions]() to make it better. The [legacy patterns documentation]() can still be used.`
- [x] Change the legacy index page banner from `deprecated` to `legacy`
  - [x] Background color `--surface-information`
  - [x] Headline: `Legacy`
  - [x] Body: `The guidance in the legacy patterns is still accurate and useful.`

**Comment by johanstromqvist** [comment]
@raquelbreternitz I think the type of banner we're using is residue from prototyping days. We wanna use the standard doc site banner, eh?



![Image](https://user-images.githubusercontent.com/38329124/221028546-bd532ea8-d40f-41a8-8ce1-b6d37e210156.png)



![Image](https://user-images.githubusercontent.com/38329124/221028236-f2eacbc8-71eb-4cc7-8f45-2f13c7295914.png)



![Image](https://user-images.githubusercontent.com/38329124/221028294-a93ffbe4-0c2a-4610-9ff8-52e4183d9a1a.png)



![Image](https://user-images.githubusercontent.com/38329124/221028330-b9545f93-4ed6-4c2c-8856-e15f9cef1cbf.png)

**Comment by raquelbreternitz** [comment]
> We wanna use the standard doc site banner, eh?

The standard doc site banner adds a label + badge; do we want to use that? Would we be alpha/beta?
To be honest, though I know it diverges a tiny bit stylistically, I kind of prefer the banner as is  😅 loose preference though
