### ISSUE TITLE
Decide whether to include real content in code examples or leave them "blank"

### ISSUE THREAD

**Issue by raquelbreternitz** [Shopify/polaris-react-archive#8227]
Thinking about #7942  and #7944 (and likely the rest) in the context of writing alt text for all the images. 

It would be helpful to ensure the code examples have the same content as the design examples, so that I don't need to describe the content in the alt text as thoroughly where it's relevant. For ex., under Resource Details, we show the example of the "Cliffs of Abandon Art Print" to give an example of how a merchant might fill out primary content in the first column. (This isn't a perfect example because it's fairly intuitive without the example content, but I suspect there will be cases in the future where it's much less so.)

Alternatively, we can choose to match the cover image for all of them, and let builders infer from the UI alone. That adds a bit of burden on the alt text, but has the advantage of being much simpler.

**Pros:** 
- match Polaris components, which include content examples
- lighten burden on alt text as screen-reader users can reference the Playroom example
- gives more real-feeling content and better shows pattern usage by example

**Cons:**
- not all the usage images are using the same base example, so we'd have to choose one and detail any departure
- we'd likely want to match the graphic content to the code content, which may force a few redraws

**Comment by jesstelford** [comment]
A personal pet-peeve (but not a hill I'm willing to die on) is "real content" in examples / templates. When I copy code, I mostly just want the structure, not all the extra bits and pieces that go along with it, because I'm going to delete all that anyway, so it's just adding extra work for me.

Having said that though, I agree that the demos often look a bit bare / boring without real content, so... 🤷

**Comment by raquelbreternitz** [comment]
> When I copy code, I mostly just want the structure, not all the extra bits and pieces that go along with it

Great point. Would it be too out of scope / wild to have the "copy" function copy clean code, but the display to include content?

**Comment by johanstromqvist** [comment]
Makes sense that we'd wanna minimize efforts for builders, as long as it's easy for them to make decisions that render consistent merchant experiences. I would assume that reusing examples across the static guidelines and the code example would make the guidance clearer and the code more likely to be used as intended, but that's very much an assumption.

**Comment by nblloyd** [comment]
@jesstelford How much extra code does real content add to our examples? On the one hand, I can see how annoying it is to have to scrub out the unnecessary bits when you copy it over. But on the other hand, it would be nice to show how to implement the visual examples we provide in the docs exactly as shown.

**Comment by johanstromqvist** [comment]
We've come across similar tension between "clear concepts" and "nimble workflow" in a few places. I addressed it in [this comment](https://github.com/Shopify/polaris/issues/7942#issuecomment-1412975059) in #7942. TLDR: suggesting that comprehensibility is more important than speed in context of patterns, but eager to debate that.

**Comment by johanstromqvist** [comment]
Code examples will get a closer holistic look. I'm referencing this conversation in [this issue](https://github.com/Shopify/polaris/issues/8333) and closing this one.
