### ISSUE TITLE
[IndexTable] `loading` prop is not working properly

### ISSUE THREAD

**Issue by yurii-lubynets** [Shopify/polaris-react-archive#8230]
## Issue summary

The index table has a `loading` prop to display LoadingIndicator. It works fine the first time `loading={true}` and after switching to `false` and then again `true` -> LoadingIndicator is not rendered at all.

## Expected behavior
`loading={true}` -> LoadingIndicator is displayed
`loading={false}` -> LoadingIndicator is NOT displayed
`loading={true}` -> LoadingIndicator is displayed

## Actual behavior
`loading={true}` -> LoadingIndicator is displayed
`loading={false}` -> LoadingIndicator is NOT displayed
`loading={true}` -> LoadingIndicator is NOT displayed

## Steps to reproduce the problem

1. Open the page with IndexTable and `loading={true}`
2. Set `loading={false}`
3. Set `loading={true}` and there is no LoadingIndicator

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 10.0.0
- Browser: Chrome Version 108.0.5359.124 (Official Build) (x86_64)

**Comment by jas7457** [comment]
I noticed this as well. It seems [it worked](https://codesandbox.io/s/async-water-nh4t6v?file=/package.json) in 10.16.1 but [broke](https://codesandbox.io/s/laughing-thunder-vtrxiw?file=/package.json) in 10.17.0

**Comment by yurii-lubynets** [comment]
@jas7457 thank you a lot. It helps in my case as well.

**Comment by jas7457** [comment]
@yurii-lubynets I believe this is still broken in the latest versions of Polaris. Should this actually be closed, or still open until a fix in the latest is added?

**Comment by yurii-lubynets** [comment]
@jas7457 let's keep it as open until a fix is added in the latest release version
