### ISSUE TITLE
Maintain a two-column layout on desktop screen sizes

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#8248]
Issue following the viewport discussion in #7966 

Summary
- The page width, nav and ToC are causing the content column to be narrow
- The narrow viewport width often causes polaris small breakpoint to trigger inside it
- The small breakpoint shows single column layouts, which is different from what images, content and rationale demonstrate
- ~The viewport height sometimes cause rendered elements to collapse vertically, which is uncommon in product and not good for demonstration purposes~ Height related issues moved to [#8345](https://github.com/Shopify/polaris/issues/8345)

Eng tasks
- [ ] Implement [proposed design solution](https://github.com/Shopify/polaris/issues/8248#issuecomment-1416389145)

**Comment by johanstromqvist** [comment]
Snippets from #7966 

> Short term
> Go with what's easiest to build and has the least implications on the general page experience. Our bet is that this is the zoomable iframe solution. This approach is hacky and does come with UX tradeoffs. We think we can mitigate and accept some of those in the short term, given that we revisit the purpose and design of the site/page/code feature later.
> 
> Long term
> Revisit this problem when we have learned more about different pattern needs in general and the code feature specifically. When we do revisit it, we should probably address the width of the content column, which is a site-wide root problem, and take a critical look at the nav and ToC. The Tailwind Awesome demo is an amazing reference, and imo the most interesting direction. It's just a matter of timing.

Ideas:

[Tailwind Awesome inspired](https://www.tailwindawesome.com/resources/astro-boilerplate/demo)
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/38329124/216451566-216b039c-396e-4017-8586-038be7613bba.png">

iFrame zoom
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/38329124/216452122-2093cbfa-be04-4fef-a689-f2c1a910827a.png">

Overflow
<img width="606" alt="image" src="https://user-images.githubusercontent.com/38329124/216452280-d2bf8345-1226-49c3-8801-300926cbb41b.png">

**Comment by johanstromqvist** [comment]
Approach 1
- Reduce site-wide padding to `1.25rem/20px` and gap to `2.5rem/40px`
- These are the same values as shopify.dev
- This provides enough space for `md` breakpoint to remain unchanged from `1098px` window width and up, including when ToC appears

Approach 2
- Keep padding and gap as is, but don't let ToC appear until there is space for both `md` breakpoint _and_ ToC
- This would increase the doc site breakpoint from `1400px` to `1550px`

### Reference
On shopify.dev:
- the ToC width is `277px`
- the padding around both content column and ToC is `20px`
- the max column width is `911px`

![image](https://user-images.githubusercontent.com/38329124/216665569-e2b31009-ffec-4c01-90a1-8576b822b1f2.png)

![image](https://user-images.githubusercontent.com/38329124/216665592-835b0579-f430-420a-a57d-20da5e38c8ad.png)

**Comment by johanstromqvist** [comment]
## Design proposal (approach 3)
- Site-wide reduction of padding `1.25rem` and gap `2.5rem` (matches shopify.dev)
- Site-wide max width to content column `776px`

### Rationale
- More effective space usage on small screen sizes, and same space usage on large screen sizes
- The viewport triggers `md` breakpoint sooner; at `1098px` instead of `1186px`
- Doc site breakpoint don't shrink the content width when the ToC appears
- The `md` breakpoint persists from `1098px` window width and up, instead of being reduced to `s` at `1400px`

### Before
![](https://screenshot.click/03-58-k170m-g58g6.gif)

### After
![](https://screenshot.click/03-40-nuvqa-m1u6j.gif)

Changes in prototype
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/38329124/216708469-d26e1149-ea61-4161-80b5-e727fb54fd68.png">

**Comment by johanstromqvist** [comment]
@jesstelford & @gwyneplaine, please check out the suggestion above and let me know what you think.

The outstanding question is regarding viewport height. How is that currently set? Any thoughts on how it should be set? Two observations on height related issues this far:
1. The range picker gets scrollable overflow due to low viewport height
2. Layout viewports can get quite tall (which might not be a problem at all)

**Comment by jesstelford** [comment]
Site-wide padding change is a great option: Ticks most of the boxes with minimal effort 👍

> How is [viewport height] currently set?

On initial load, the iframe is resized to be 100% height of the rendered example. The height then stays the same until the page is reloaded. This means if you resize your browser, the height will _not_ change to accomodate the new height of the example. There's also an edge case where if content is rendered _after_ initial load (eg; clicking to open a modal, etc) which changes the height, the iframe will not be resized.

We might be able to cook up something to detect changes to the page width and update the height as the browser is resized, however this wont fix the edge case where rendering _after_ initial load changes the height. I'm not sure how to handle that 🤔

**Comment by johanstromqvist** [comment]
Moved height related issues to [#8345](https://github.com/Shopify/polaris/issues/8345) (backlog)

**Comment by SeanyB** [comment]
@gwyneplaine - I see this moved into **Ready for review**, but there aren't changes on staging yet. Is #8338 the PR that adds the adjustments to left and right padding and TOC behaviour?

**Comment by johanstromqvist** [comment]
Seems to be live on staging now 👍 

These two fixes look great:
- Updated Page styles to reduce gap from 5rem to 2.5rem
- Update Container styles to reduce horizontal padding from 4rem to 1.5rem

Another proposed change was to limit the max-width to `776px` and justify the content `center` at breakpoints below `1400px`. Were those changes missed or discussed somewhere? AFAIK they might still be needed, sorry if they were unclear.

### Context
Currently, the content width only surpasses `776px` at `$breakpointDesktopSmall` before the ToC appears. Beyond that breakpoint the max width is `776px`. As the content width increases between `777px` and `1399px` window widths, the content width causes line lengths to become very long and images to be blown up in scale.

![Image](https://user-images.githubusercontent.com/38329124/219190326-cc8680b1-125f-4aed-9158-7bbba4a8bace.png)

![Image](https://user-images.githubusercontent.com/38329124/219191067-f55b65bd-7c4f-43f5-9f69-dc4c54a2738e.png)

**Comment by jesstelford** [comment]
Good catch! Fixed in https://github.com/Shopify/polaris/pull/8399

**Comment by johanstromqvist** [comment]
Sorry that I didn't think ahead and make this clear earlier, but the width cap fix was intended for the "editorial" page type. That's where we come across the issues with line lengths and massive images. As is, #8399 also caps the width of index pages and "sell pages", which leads to ineffective use of space and some odd looks.

Pages the width cap changes shouldn't apply to:
- [ ] [Home](https://polaris.shopify.com/)
- [ ] [What's new](https://polaris.shopify.com/whats-new)
- [ ] Index pages
  - [ ] [Foundations](https://polaris.shopify.com/foundations)
  - [ ] [Design](https://polaris.shopify.com/design)
  - [ ] [Content](https://polaris.shopify.com/content)
  - [ ] [Patterns](https://polaris.shopify.com/patterns)
  - [ ] [Components](https://polaris.shopify.com/components)
  - [ ] [Tokens](https://polaris.shopify.com/tokens)
  - [ ] [Icons](https://polaris.shopify.com/icons)
  - [ ] [Tools](https://polaris.shopify.com/tools)

(I _thiiink_ this is a complete list)

👇 Examples of pages that should use the available width (with whatever our current logic is)
| 💁 Yay | 🙅 Nay |
|--------|--------|
| <img width="695" alt="image" src="https://user-images.githubusercontent.com/38329124/219492410-765057a4-d19f-4828-989d-c0e1e69a9803.png"> | <img width="697" alt="image" src="https://user-images.githubusercontent.com/38329124/219492663-c955c8c5-1d63-45b8-9043-41033df1342d.png"> |
| <img width="698" alt="image" src="https://user-images.githubusercontent.com/38329124/219493174-bb5c31bd-9ac6-4db5-8c55-26f584cde350.png"> | <img width="699" alt="image" src="https://user-images.githubusercontent.com/38329124/219492847-cb2724a8-2e7b-4687-aefa-4436621c1cb9.png"> |
| <img width="697" alt="image" src="https://user-images.githubusercontent.com/38329124/219493501-193b9898-a5ee-4fb9-8daf-3fa45c3f30f5.png"> | <img width="699" alt="image" src="https://user-images.githubusercontent.com/38329124/219493375-d7b6d93f-96c1-4162-b8d8-6add00591895.png"> |

**Comment by jesstelford** [comment]
Ah, ok, thanks for clarifying!

Here's a PR with a fix: https://github.com/Shopify/polaris/pull/8432

**Comment by jesstelford** [comment]
Separate to the fixed width column, the changed page padding means tokens now have enough space to show 4 per row @ 1400px:

| Prod | Patterns branch |
|--------|--------|
| ![tokens-before](https://user-images.githubusercontent.com/612020/219984525-32b8471f-d4fd-45ed-8fa5-6f2d066233f2.png) | ![tokens-after](https://user-images.githubusercontent.com/612020/219984540-2cf9c38f-162f-4933-808a-425280951a8f.png) |

Is this ok? Or should we make it a fixed width column too?

**Comment by johanstromqvist** [comment]
Yes, I think that's a good use of space in general.

However, the tokens index switch to a table view from at >1400, so the four items per row is only effective between 1396px and 1400px. I don't see any big concerns with this, but I thought I'd call it out in case there's any messy breakpoints leading to that.

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/38329124/220782587-8dbcd917-35b5-4563-bdae-eeb8f76559b2.png">

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/38329124/220782638-28d8fbb8-eab0-4a3e-a65f-1351b06e73ce.png">

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/38329124/220782713-a2d65670-42ba-401e-ad92-395637ed6abc.png">
