### ISSUE TITLE
Box with content is too wide in undismissable Banner 

### ISSUE THREAD

**Issue by mhlozek** [Shopify/polaris-react-archive#8264]
When I use Banner component with long text and disable the hide option, then Box component with text is too wide and overflow from Banner component.

(I think there is a problem with `min-width: 100%;` definition in the css of Bleed component)

![image](https://user-images.githubusercontent.com/2743172/216661482-17b15265-5390-4c08-8be6-022170f8e889.png)

**Comment by laurkim** [comment]
Hi @mhlozek 👋 

Thanks for creating this issue! The issue with inner content width has been fixed in [this](https://github.com/Shopify/polaris/pull/8256) PR and should be available in the newest release of `@shopify/polaris` we just shipped. The fix should be on version 10.26.0.

**Comment by mhlozek** [comment]
Great, thank you!
