### ISSUE TITLE
Accessible and inclusive language guidance

### ISSUE THREAD

**Issue by freshyill** [Shopify/polaris-react-archive#8274]
Hi Shopify people,

I'm a big fan of the work you're doing on Polaris, but I came across content guidance in your Accessible and Inclusive language documentation that I don't think is accurate. The guidance says:

> **Low-hanging fruit**
> This metaphor refers to the lynching of Black people, and shouldn’t be used.

I don't see evidence that this is correct. This [blog post](https://languagelog.ldc.upenn.edu/nll/?p=1778) from University of Pennsylvania linguist Mark Liberman examines the history of the expression, which dates to at least 1627, but it includes no history as a reference to. lynching. I suspect that someone has confused the term "low-hanging fruit" with the song "[Strange Fruit](https://en.wikipedia.org/wiki/Strange_Fruit)" (Wikipedia link, potentially disturbing content). I hope you'll consider reviewing this guidance.

**Comment by nikk-ca** [comment]
Thanks @freshyill. Just noticed this issue myself.

See also:
- https://www.merriam-webster.com/dictionary/low-hanging%20fruit#word-history
- http://www.theinclusionsolution.me/words-and-phrases-that-sting-black-marble-and-low-hanging-fruit/
