### ISSUE TITLE
Latest version of Polaris is not rendering ResourceList correctly when importing CSS

### ISSUE THREAD

**Issue by IonicaBizau** [Shopify/polaris-react-archive#8303]
## Issue summary

We are importing the `polaris` library in our React app, and functionality works fine, but the CSS is simply broken. The [Resource List](https://polaris.shopify.com/components/resource-list) component is simply not rendering as expected...

## Expected behavior

<img width="649" alt="image" src="https://user-images.githubusercontent.com/2864371/218335506-ff4e8426-cb33-4d06-8d55-b6ffaf138d8e.png">

## Actual behavior

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/2864371/218335489-1eaa74ff-d77c-4a4e-8717-1d66f519f92c.png">

I am getting warnings like this in the console:

```shell
warn  variable --pc-range-slider-progress-lower is undefined and used without a fallback
...
```

Any ideas why the UI would look broken like this? I simply copied the code from the docs...

**Comment by IonicaBizau** [comment]
For example, `--pc-inline-block-align` has no value being set in the build CSS file (esm/styles.css). Where is it supposed to come from?

<img width="481" alt="image" src="https://user-images.githubusercontent.com/2864371/218335714-97a7fd42-a509-4366-b282-65f8c614121d.png">

**Comment by alex-page** [comment]
@IonicaBizau I have passed this issue onto the team who shipped some recent changes to the `ResourceList`. Can you confirm if using an older version `v10.23.0` has this issue?

**Comment by IonicaBizau** [comment]
@alex-page Thank you very much. I debugged a little bit the problem to find the source of the `undefined` values and found that these are coming from the CSS processor (which was replacing the variables in the bundle). I disabled replacing of the variables and now that part works.

However, there still some inconsistency:


❌   **v10.27.2** — Broken padding:

<img width="971" alt="image" src="https://user-images.githubusercontent.com/2864371/218380616-bb99a9fb-182e-4876-afec-881616527ed1.png">



✅  **v10.23.0** — Looks as expected:

<img width="967" alt="Screenshot 2023-02-13 at 06 45 05" src="https://user-images.githubusercontent.com/2864371/218380749-1bf1e46e-2311-4f9e-93eb-ecc0c2d8255c.png">

----

This is how the `.Polaris-Box` looks in the broken version (it is missing the horizontal padding):

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/2864371/218380953-3f1e65c7-d741-4c0d-9265-e45fee8f0584.png">

**Comment by IonicaBizau** [comment]
And this is how it looks the modal using v10.23.0:

<img width="649" alt="image" src="https://user-images.githubusercontent.com/2864371/218382989-dbea3d29-6916-4ad0-92ef-c71c3c184e28.png">

And looks great when copying the styles from Edit Sandbox (modal):

<img width="731" alt="image" src="https://user-images.githubusercontent.com/2864371/218383541-86bfd406-d9ab-4bc3-94de-46a75fe9c845.png">

**Comment by kyledurand** [comment]
Can you reproduce this in a codesandbox and link to this issue @IonicaBizau? 
It's really difficult to see what's happening here from the screenshots and I'd like to dig deeper into this

It would help to know more about your project as well. What version of react you're using along with the rest of the stack. If you could link to that as well it would help

**Comment by IonicaBizau** [comment]
@kyledurand Sorry for the late reply. After upgrading to `10.32.0`, things got better overall (the other components seem to be fine), but ResourceList is still a bit funny — there is no margin after the checkboxes:

<img width="153" alt="image" src="https://user-images.githubusercontent.com/2864371/222659313-05916445-e4ba-4c47-94a9-71e0cd62bdbc.png">

**Comment by IonicaBizau** [comment]
The stack itself is a bit complex. I use `browserify` for bundling the JavaScript (namely React files) and [postcss](`https://github.com/postcss) to process the CSS.

**Comment by kyledurand** [comment]
Looks like the checkbox has the correct left spacing now. Since you're using postcss and this appears to be an issue with our usage of css `gap` would you be able to try this [gap polyfill](https://github.com/gavinmcfarland/flex-gap-polyfill) and let us know if that fixes it? I'd be surprised if it does since postcss shouldn't be running within your node_modules folder but maybe there's a configuration issue
