### ISSUE TITLE
Remove support for react 16 and 17 in next major

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#8331]

**Comment by BPScott** [comment]
Dropping support for React v16 and v17, would allow us to begin using the [`useId` hook](https://beta.reactjs.org/reference/react/useId) for producing IDs in place of the existing and flawed [`useUniqueId`](https://github.com/Shopify/polaris/tree/main/polaris-react/src/utilities/unique-id).

Replacing usage of `useUniqueId` with `useId` would allow us to finally close the long-standing issue #1761, which details the shortcomings of `useUniqueId`.

**Comment by alex-page** [comment]
@BPScott I have made a new issue to track useId https://github.com/Shopify/polaris/issues/8395
