### ISSUE TITLE
Revisit the purpose and technical constraints of code examples

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#8333]
The code example feature raises a few recurring questions that are both practical and existential in nature. These need to be considered and explored together and in more depth.

| Recurring topic | Comment | Visual |
|--------|--------|--------|
| **Real content or placeholders** | For example, the resource details pattern could be populated with real content that exemplifies a typical page, or with skeleton content which is easier to build and maintain. As discussed in #7944.  | ![Image](https://user-images.githubusercontent.com/38329124/218611947-d3e8d117-0cbd-417b-90b3-eb18b7ca13a1.png) |
| **Realistic or generic scenarios** | For example, the resource index pattern could show Products which would be more recognizable, or something imaginary that's more widely applicable especially in apps. What has more value to builders? | ![Image](https://user-images.githubusercontent.com/38329124/218612854-4eb21484-f3c1-4248-8dbf-f2a0fd1407d9.png) |
| **Simple or exemplifying content** | For example, the app settings layout could provide only barebones page layout which might require less gutting, or include a variety of typical form components that showcase proper in-card layouts that demonstrate and ensure more good practices. | ![Image](https://user-images.githubusercontent.com/38329124/218612694-17e21719-e442-43bc-bf79-bbc16a54a52a.png) |
| **Visually accurate examples or clean code** | For example, adding containers and/or styling that ensure that the date picker renders in a way that is recognizable from the admin, aligns better with the page narrative and is easier to understand, or provides as clean code as possible to be faster to work with. As discussed in [this comment](https://github.com/Shopify/polaris/issues/7942#issuecomment-1412975059). | Visual tba |
| **Cost vs benefit** | We need to balance how much time are we investing in creating and maintaining code examples, vs how much time are we saving builders and increasing quality for merchants? | n/a | 
| **Polaris only or multiple sources:** | What code we could and should include in code examples. For example, the date range picker in the admin has code from `web`, utilizes [helpers](https://github.com/Shopify/quilt), and i18n, which currently isn't compatible with playroom and our on-page render. | n/a |

**Comment by johanstromqvist** [comment]
Comment in Slack by @jesstelford 

> There's an open question here around *how complete* the code examples should be.
> 
> :one: On one hand, we can provide code chunks with obvious `/* Add your specific business logic here */` comments. A paint-by-numbers so to speak.
> 
> **Pros**:
> 
> -   Enables us to build and iterate on code examples quicker without aiming for support of every possible usecase.
> -   Similarly; Keeps the example generic enough that any builder can see the parts that are already implemented and not need to touch them.
> -   Makes it unmistakably clear to builders where they need to apply their specific logic.
> 
> **Cons**:
> 
> -   The rendered example doesn't match 1:1 the design in the screenshots (arguably, this will *always* be the case as the designs are lightly stylised and have highlighting, etc, on them)
> 
> :two: On the other hand, we can provide *complete* code chunks which are ready to copy+paste directly into Admin or a 3P app without any changes, and everything looks perfect.
> 
> **Pros**:
> 
> -   The rendered example is a closer match to the design in the screenshots
> -   A Builder can interact with / get a feel for the example *as it would look in the Admin* before copying the code
> 
> **Cons**
> 
> -   We need to spin our wheels getting it perfect for all possible use cases lest a builder blindly copy+paste the code without modification ([likely!](https://www.goodreads.com/en/book/show/29437996))
> -   Not easy to implement all features with the Playroom tool we have currently (ie; can't use Shopify's date formatting library `@shopify/dates`)
> -   Example code becomes *massive*, making it unclear to Builders where they are allowed to / should be adding custom business logic
> -   At this point, a "Pattern" is no different than a "Component"; the code is expected to be used as-is without modification. So why isn't it just a Polaris component?
> 
> ---
> 
> **My suggestion**: Examples with blanks that the Builder can fill in.
> 
> It doesn't match 1:1 with the images, but that's exactly why we have the images and guidance text etc. It gives builders exactly what they need (the structure and hard opinions we have for the pattern) and nothing more (superfluous markup, library imports, styling, etc). And it makes our lives easier when creating the code examples for each pattern.

**Comment by JeremyLudwigDev** [comment]
One other consideration I haven't seen mentioned: in the case of the `DatePicker` we made the decision to move the component to the global components folder so that it could be reused across the admin. When it comes to admin builders, it would be our preference for other teams to use the component directly, rather than build their own version of it based on a code sample. That way if/when we make changes or improvements to the component, those patterns will stay in sync.

Obviously that doesn't apply to 1P or 3P app builders, which, I suppose, is where the code examples would come into play.

**Comment by johanstromqvist** [comment]
> it would be our preference for other teams to use the component directly

💯 agree @JeremyLudwigDev! We'd wanna make it easy for builders to implement the right component(s) that renders a unified merchant experience. Not create something similar. What would we need to do to be able to offer that component directly?

**Comment by JeremyLudwigDev** [comment]
If I'm understanding your question correctly, within the admin it's just a question of importing the component with it's simple API:

```tsx
import {DatePicker} from 'components/AnalyticsDatePicker'

const ExampleComponent = () => {
  const [reportingPeriod, setReportingPeriod] = useState<DatePeriod>({
    since: new Date(),
    until: new Date(),
  });

  const handleChange = (newReportingPeriod: DatePeriod) => {
    setReportingPeriod(newReportingPeriod);
  };

  return (
    <DatePicker
      quickPicks={exampleQuickPicks}
      datePeriod={reportingPeriod}
      onChange={handleChange}
    />
  );
};
```
Inasmuch as the audience for the Patterns page is admin builders, would it make sense to direct them to that component explicitly?

The tricky part I suppose is how best to enforce the pattern outside of web. If we don't want the whole component to live in Polaris then I guess a code sample is the best bet.

A couple of other thoughts: if I were an app developer and I was trying to implement the DatePicker pattern, I don't think I would necessarily expect the code sample to exactly reproduce the pattern. I think I would expect to have to implement some of the interactions between the components and things like date formatting myself, but use the pattern as a spring board. If I just cut and paste the example and got a whole working component, I think I would wonder why I couldn't just import the component directly?

Also, in our initial discussions at the start of the project, @LevonCross had expressed a desire for a better date text field input and had some great examples of inputs that had better keyboard control, validation etc. If we did build something like that in Polaris, it seems to me that would take care of many of the sticky parts of implementing this pattern outside of the context of web.

Not sure any of that's useful, just my two cents!

**Comment by johanstromqvist** [comment]
Related issues:
[#8227 – Decide whether to include real content in code examples or leave them "blank"](https://github.com/Shopify/polaris/issues/8227) 
[#8177 – How might we document the code in the examples for each variant?](https://github.com/Shopify/polaris/issues/8177)
