### ISSUE TITLE
Always default code to visible on patterns pages

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#8370]
We have a design ready to made code easier to copy, without opening the entire code window. This is captured in this [issue #8052](https://github.com/Shopify/polaris/issues/8#8052 

However, in the interest of minimizing scope for this initial release, while still responding to feedback about making the code obvious to users, let's default the code window to **open** for all patterns pages.

- [ ] When opening a patterns page, the code is visible and the **Hide code** button is showing.
- [ ] If a user hides the code for a pattern, then moves to a different pattern, the code is visible in the different pattern and the **Hide code** button is showing.
- [ ] If a user hides the code for a pattern variant, then moves to a different pattern variant, I'm comfortable doing whatever is most straightforward from an Eng perspective.
    - Either the different variant has the code visible with **Hide code** button showing.
    - OR, the different variant has the code hidden with the **Show code** button showing.

**Comment by jesstelford** [comment]
Fixed in #8412 

When browsing between variants, it will retain the open/close state. Then, when navigating between patterns, the code is forced into the Open state.

**Comment by jesstelford** [comment]
Shipped to prod.
