### ISSUE TITLE
Add links to patterns on relevant component pages

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#8372]
Design tasks
- [x] Track down work that's been done
- [x] Decide what pages that are relevant
- [x] Write simple copy
- [x] Add links
- [x] Potentially add issues to backlog to revisit if short term solution is very scrappy

Eng tasks
- [x] Implement the links

**Comment by raquelbreternitz** [comment]
- [x] create update banner
- [x] add date picking to date picker
- [x] add resource details to page
- [x] add app settings to page
