### ISSUE TITLE
Convert pattern links on component pages to thumbnails

### ISSUE THREAD

**Issue by raquelbreternitz** [Shopify/polaris-react-archive#8390]

**Comment by johanstromqvist** [comment]
Added the `design` label. I assume we'd want to reuse the same thumbnails from index and search, but it's probably helpful to see what that should look like.

**Comment by raquelbreternitz** [comment]
This was in the original prototype like so, repeating the index/search thumbnail:



![Image](https://user-images.githubusercontent.com/13204374/222000817-ea56e485-bbea-416e-bd3d-e0664e131be5.png)



Let me know if you think we need to do any additional design work ahead of implementation @johanstromqvist.
