### ISSUE TITLE
HTML TextField input width is 50%

### ISSUE THREAD

**Issue by limoniapps** [Shopify/polaris-react-archive#84]
When I create a TextField using HTML the input field has 50% of the expected width.
The "Polaris-TextField__Backdrop" has the correct width, but the input field itslef, with class "Polaris-TextField__Input" has only 50% of the width of the backdrop.

## Steps to Reproduce the Problem

1. Create a page based on the html of the example available here: https://github.com/Shopify/polaris/blob/master/examples/cdn-styles/index.html 
2. Check the 'email' and 'how did you hear about us' fields 

## Specifications

- Polaris version: v1.0.3
- React version: N/A
- Browser: Chrome 58.0.3029.110 (64-bit)
- Device: Desktop
- Operating System: Windows 10

**Comment by lemonmade** [comment]
I am unable to reproduce this. Do you get the same thing in other browsers (Firefox, Edge)? I'd also love to get a screenshot from your machine inspecting the node that has the `Polaris-TextField__Input` class so I can see the bounding box for it.

**Comment by bartcoppens** [comment]
Fixed. Wasn't a Polaris bug. Overlooked another css file that was loaded by the framework I leverage.
