### ISSUE TITLE
Create two parallel CI steps for Stylelint in Shopify/Web

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#8409]
### Discussed in https://github.com/Shopify/polaris/discussions/8392

<div type='discussions-op-text'>

<sup>Originally posted by **sophschneider** January 30, 2023</sup>
Right now, Shopify/web's CI fails stylelint on both warnings and errors. This doesn't allow us to tier warnings and failures from Stylelint Polaris. Having warnings could allow us to nudge developers to fix coverage problems without blocking them which would be useful for rules like layout.

In VSCode we would use the joint config so that all errors and warnings are shown in there. On CI, we could run one step with the basic shopify/web stylelint config and one step with the stylelint polaris config. We could even modify our Polaris step to not report warnings at all in the CI so it doesn't get noisy and the warning experience would only be in VSCode.

**Comment by sam-b-rose** [comment]
@sophschneider can we consider this closed since we've merged https://github.com/Shopify/web/pull/84361 ?
