### ISSUE TITLE
ActionList suffix has unexpected margin on the left when being wrapped

### ISSUE THREAD

**Issue by duprasa** [Shopify/polaris-react-archive#8459]
## Issue summary

I'm working on a component that uses up a lot of horizontal space and occasionally wraps the actionList suffix.
![image](https://user-images.githubusercontent.com/4052969/220740131-492b183e-e312-4cdb-bf06-b83a960ce58f.png)

We would like it if left margin wasn't visible and if the badge could remain aligned with the content, currently we don't have control over this

## Expected behavior

suffix and content are left aligned when wrapped 
![image](https://user-images.githubusercontent.com/4052969/220741063-8857f026-2701-40ae-aa5d-d7707111a1a8.png)

## Actual behavior
There is a margin on the left of the suffix
![image](https://user-images.githubusercontent.com/4052969/220740131-492b183e-e312-4cdb-bf06-b83a960ce58f.png)

## Steps to reproduce the problem

1. Create an action list component where one of the items has both `content` and `suffix` filled example
```
        <ActionList
          items={[
            {
              content: "Charge American Express •••• 0005",
              suffix: <Badge>Selected at checkout</Badge>
            },
            {
              content: "Charge Mastercard •••• 4444"
            }
          ]}
        />
```
2. Add this component into a context that has limited width like `<div style={{ width: "300px"><ActionList ...></div>`

## Reduced test case

https://codesandbox.io/s/boring-moon-vbmcy5?file=/App.js

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 10.28.2
- Browser: Chrome
- Device: Macbook M1
- Operating System: OSX

**Comment by Ipriyankrajai** [comment]
The reason for this is when parents width is less than child's width so it is breaking content into next line due to flex-warp
property. Moreover, suffix component is give padding instead using css property gap.
We can fix this issue by using gap property instead of using padding-left.

I would like to solve this issue as my first open source contribution.

**Comment by duprasa** [comment]
thats awesome to hear @Ipriyankrajai, thanks for picking this up 😄
