### ISSUE TITLE
Re-activating the sheets component

### ISSUE THREAD

**Issue by kiara-stewart** [Shopify/polaris-react-archive#8463]
## Sheets Component

A sheet is a large container that enters from the edge of the screen when triggered by the merchant. It’s used to provide merchants with actions and information contextual to the page. It doesn’t interrupt their flow like a modal.

Sheets provide an opportunity to let merchants dig into more detail on their current task, or access information for their current task in a different way. Although merchants may be able to see content in the sheet and the main page content at the same time, they should only be expected to interact with one or the other at any given time.

### Current State
Images from merchant stores: https://docs.google.com/document/d/17HqOM9tCQEd9kcJnnUqKZIazmL2vEpzMNq7u7Bj2WhY/edit?usp=sharing

Throughout Shopify, we use modal overlays to quickly display information without navigating the merchant to another page. Unfortunately, in some cases, the implementation of these modal overlays has led to increased cognitive strain and errors for our merchants. Here’s why:

**We obscure contextually relevant information.**

✏️Can you answer the following questions:
- 1. How many entries are on the current page?
- 2. What was their original search? 
- 3. What entries did they select?

**We don’t provide a way for merchants to recognize, diagnose, and recover from errors.**

✏️Can you answer the following questions:
- 1. How will merchants edit their original search?
- 2. How will merchants recognize if they’ve selected the wrong entry?
- 3. When will merchants recognize that they’ve selected the wrong entry? 

### Future State

We use the sheet component to show contextually relevant information. 

![Right](https://user-images.githubusercontent.com/107505516/220749815-03e723cc-719c-4061-a047-d315d657d4b8.png)

</div></b>

## Props

List props and type declarations:

> - Everything will remain how listed: https://polaris.shopify.com/components/deprecated/sheet

## Best practices

The sheet component should:

- Include a heading that summarizes the actions and information in the sheet, for example, More filters
- Be openable through clear actions, like a link or button
- Be close-able through clear actions, like Done, the [X] button, and the esc key
- Include information and actions contextual to the current task
- Not block merchants from completing their task, like a modal would
- Not open from within another sheet (only one sheet can be open at a time)
- Preserve its state—the settings and actions won’t reset when it’s closed

The sheet component is best used in cases where the merchant **needs to see elements behind it**, and for that reason it uses a transparent backdrop. The backdrop is a full screen overlay which closes its parent component when pressed.

## Content guidelines

Link to image: https://docs.google.com/document/d/17HqOM9tCQEd9kcJnnUqKZIazmL2vEpzMNq7u7Bj2WhY/edit?usp=sharing

## Related components
- To offer an action that doesn't require context, use the [modal component](https://polaris.shopify.com/components/overlays/modal)
- To present a small amount of content or a menu of actions in a non-blocking overlay, use the [popover component](https://polaris.shopify.com/components/overlays/popover)

**Comment by kiara-stewart** [comment]
I just want to take the time to reiterate:

1. This would be easy to implement because it's not net new. https://polaris.shopify.com/components/deprecated/sheet 
2. Related components do not provide enough merchant visibility.

**Comment by kjbrum** [comment]
Have there been any discussions around re-adding the `Sheet` component outside of this PR? Custom Data is looking to add functionality that will require more complex UI/UX on resources pages and would love to be able to explore using a `Sheet` instead of a modal or something else.

**Comment by kiara-stewart** [comment]
As far as I know, there haven't been any official discussions, @kjbrum. However, I have noticed it in a few iterations throughout the org for projects scheduled to be released in Q3/Q4.
