### ISSUE TITLE
Combine Box, Inline, AlphaStack?

### ISSUE THREAD

**Issue by nikk-ca** [Shopify/polaris-react-archive#8481]
Box, Inline and AlphaStack could all be combined into a single component by adding these properties to Box:
- `flex`: any valid [`flex-flow`](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-flow) value (handles `reverseOrder` and `wrap` properties)
- `gap`
- `align`: `'stretch' | 'start' | 'center' | 'end'`
- `distribute`: `'stretch' | 'start' | 'center' | 'end' | 'space-between' | 'space-around' | 'space-evenly'`

**Comment by alex-page** [comment]
I agree that these properties should be added to `Box`. I don't think they should be combined into a single component.

I would like those components to be built with `Box` and still exist separately as it's useful for documentation and learning parts of the system quickly.

**Comment by kyledurand** [comment]
Box already does a lot, maybe too much. We're trying to create simple, purposeful layout components where each component is clear in what it does and there's not much if any overlap between them

**Comment by alex-page** [comment]
IMO `Box` isn't a layout component it's an infrastructure component for accessing tokens. I agree with your concern and wouldn't expect anything to change today.
