### ISSUE TITLE
[Urgent] Finish that puzzle

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#8488]
- [x] Find that darn edge piece
- [x] Do the rest
- [ ] Develop comms plan for bragging

![Image](https://user-images.githubusercontent.com/38329124/221051094-b8f4d6c1-97bd-4bc2-b6fd-98696b08f058.png)

**Comment by raquelbreternitz** [comment]
CODE RED COMPLETE

<img width="1226" alt="Screenshot 2023-02-23 at 5 29 59 PM" src="https://user-images.githubusercontent.com/13204374/221054972-321ac530-f6b9-4e6c-8ace-4adc4049bbac.png">

**Comment by johanstromqvist** [comment]
GJ team! Marking this done. 🎉

**Comment by alex-page** [comment]
🙌

**Comment by martenbjork** [comment]
I don't know what happened here, but I strongly approve ❤️
