### ISSUE TITLE
Selection Checkboxes Hidden on ResourceList Component when Rendered on Mobile Devices with Selectable Props set to True

### ISSUE THREAD

**Issue by ekiilu** [Shopify/polaris-react-archive#8502]
## Issue summary

Currently, when the ResourceList component is rendered on mobile devices with the selectable props set to true, the selection checkboxes are hidden. This issue is causing inconvenience to the end-users who are unable to select the desired items on mobile devices.

## Expected behavior
The selection checkboxes should be visible and functional on all devices, including mobile devices, when the selectable props are set to true.

## Actual behavior

The selection checkboxes are hidden on mobile devices when the selectable props are set to true.

## Steps to reproduce the problem

1. Visit [Resource list example](https://polaris.shopify.com/examples/resource-list-with-multiselect#) From your mobile phone. The checkbox are hidden.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number: 10.31.0
- Browser: Chrome
- Device: Mobile phone
- Operating System: Android

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by capatina** [comment]
Yes, this seems to be a strange regression. Bulk actions are currently hidden / unavailable on mobile - can we please get them back?

**Comment by boronine** [comment]
We are also dealing with this issue since upgrading Polaris

**Comment by hey-servicify** [comment]
Same here.

**Comment by Malek-Mohamed** [comment]
This issue still exists on version ^12.0.2, any plan to fix it?

**Comment by JoeCMorgan** [comment]
This is still any issue... So frustrating seeing actual bug reports closed with no explanation or fix.
