### ISSUE TITLE
`Text` component requires me to duplicate parent component styles instead of cascading

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#8516]
## Issue summary

When trying to right align typography inside an IndexTable heading I have to provide the following properties:
- `variant`
- `color`
- `fontWeight`
- `as`
- `alignment`

## Expected behavior

I should only have to provide `alignment` as I want to follow the parents cascading styles that set `fontWeight` `color` and `fontSize` and for the element to default to a `span` or `p`.

## Actual behavior

See this PR: https://github.com/Shopify/polaris/pull/8448

Repeat a lot of code and output more CSS then is needed because I am forced to use properties in the component.

**Comment by aaronccasanova** [comment]
One possible solution to this issue could be to introduce a [variantMap](https://github.com/mui/material-ui/blob/835e53eac76266ce37145a82365765190afc8709/packages/mui-material/src/Typography/Typography.js#L62-L74) and an `inherit` variant to the `Text` component. Essentially, the `variantMap` would map the `variant` prop to a set of predefined HTML elements, which reduces the need to set the `as` prop for each `Text` instance. Then, we could use the `inherit` variant to set the remaining style props to inherit (reducing the need to specify them individually) e.g.

Before:
```tsx
function App() {
  return (
    <Text as="h3" variant="heading" color="primary" fontWeight="bold">
      ...
      <Text as="span" variant="heading" color="primary" fontWeight="bold" align="right">...</Text>
    </Text>
  )
}
```
After:
```tsx
function App() {
  return (
    <Text variant="heading" color="primary" fontWeight="bold">
      ...
      <Text variant="inherit" align="right">...</Text>
    </Text>
  )
}
```

**Comment by alex-page** [comment]
I was assuming `variant` would become optional and would inherit by default with no added CSS.
