### ISSUE TITLE
Layout problems with useMedia hook

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris-react-archive#8524]
https://github.com/Shopify/web/pull/84187/files#diff-c9654d4d5201ccab1ef0b8834f6bc808d62bd4e30488f523006faa5fa22e790dR230

https://github.com/Shopify/web/pull/84187/files#diff-5bfc27c9121dc7ac0837a3caaffc2a1c433dcaae27b808aea0637804b9807f59R3

https://github.com/Shopify/web/pull/84187/files#diff-f4fb919fbc9e9937de6cae49d5133bb801fd4413060595742a08321bff0ad038R39

https://github.com/Shopify/web/blob/ea010f936692eac64250b55076e48cabe3358dc5/app/sections/Billing/AccountPricing/AccountPricing.tsx#LL113C35-L113C65

Make sure nothing breaks on `admin/settings/account/plan`

**Comment by alex-page** [comment]
@kyledurand does this PR need to be a part of v11?

**Comment by kyledurand** [comment]
Nope, removed the label
