### ISSUE TITLE
Setup Shopify/polaris on local system.

### ISSUE THREAD

**Issue by Ipriyankrajai** [Shopify/polaris-react-archive#8527]
## Issue summary
When I clone the repo and run yarn in the root workspace it throws an error "**ERROR** Failed to apply the patch for package playroom".

## Expected behavior
It should install all the dependencies in the local system.

## Actual behavior
It throws an error "**ERROR** Failed to apply the patch for package playroom".
![image](https://user-images.githubusercontent.com/32142351/222041542-d0099381-a86e-4574-9346-a870a2f8aecb.png)

## Steps to reproduce the problem

1. Fork the repo (Main branch) (Note: make sure your branch is up to date with Shopify/polaris:main.)
2. Clone the Repo to your local system.
3.  Run CMD yarn && yarn build. 

## Specifications

- Are you using the React components? (Y/N):Y
- Polaris version number: Latest
- Browser: Chrome
- Device: Dell Inspiron 
- Operating System: Windows 11

**Comment by kyledurand** [comment]
Thanks for raising this @Ipriyankrajai I've been able to reproduce this on my non-shopify machine. We're looking into it.

**Comment by Ipriyankrajai** [comment]
> Thanks for raising this @Ipriyankrajai I've been able to reproduce this on my non-shopify machine. We're looking into it. 

I tried it on Linux system its working fine. But im facing this issue on windows system.

@kyledurand did you try it on windows system?

**Comment by gwyneplaine** [comment]
@Ipriyankrajai hello we've merged a fix to main that resolves the issue on a test windows machine, can you verify that the fix also works for you?

**Comment by Ipriyankrajai** [comment]
@gwyneplaine I was able to install all the dependencies by `yarn`. But when I create a build it throws an error "Error: ENOENT: no such file or directory, open '/E:/Personal/Github/polaris/polaris-tokens/package.json'".
![image](https://user-images.githubusercontent.com/32142351/222327707-5758a3aa-c258-41c9-98d7-115c6feff966.png)

**Comment by gwyneplaine** [comment]
Interesting, thanks for updating @Ipriyankrajai, we're looking into it

**Comment by gwyneplaine** [comment]
Update on this @Ipriyankrajai , we're working through a fix to get build working on Windows machines in #8544. 

We're presently waiting on the [following change](https://github.com/Shopify/polaris/pull/8203) that removes a problematic dependency for windows to be released with [v11](https://github.com/Shopify/polaris/tree/v11-major) before we can move forward with the fix for Windows

I'll keep you updated as we move through these tasks, thank you for your patience 🙏

**Comment by Ipriyankrajai** [comment]
@gwyneplaine thank you for the update😊.
