### ISSUE TITLE
Uncaught SyntaxError when importing LegacyCard

### ISSUE THREAD

**Issue by Turokhunter** [Shopify/polaris-react-archive#8552]
## Issue summary

I'm getting an uncaught syntax error when importing legacyCard.

## Expected behavior

The example code and the import to work.

## Actual behavior

Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@shopify_polaris.js?v=693f885d' does not provide an export named 'LegacyCard' (at datatable.jsx:3:3)

## Steps to reproduce the problem

1. Install the new app: npm init @shopify/app@latest
2. name the project and select node
3. enter the folder, run "npm run dev"
4. Setup app
5. Copy code from the example here: https://polaris.shopify.com/components/tables/index-table 
6. executing the code fails with the error mentioned above

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? Y:
- Polaris version number: "@shopify/polaris": "^9.11.0"
- Browser: Chrome
- Device: MacBook Pro (16-inch, 2019)
- Operating System: Mac OS Monterey version 12.6

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:
System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 3.39 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 19.5.0 - ~/.nvm/versions/node/v19.5.0/bin/node
    Yarn: 1.22.19 - ~/Dropbox/Work/menu-creatorv3-app/node_modules/.bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v19.5.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 109.0.1
    Safari: 16.1

```bash

```

**Comment by chrischu5** [comment]
Pretty sure you have to bump your major version up to v10 for that component to work. I ran into the same issue and upgraded to the latest version of Polaris and it worked. 

Having said that, does the [Polaris](https://polaris.shopify.com/) documentation page have a way of selecting different versions of the package? If not, that seems confusing for new app developers who get set up using the Shopify CLI with Polaris v9 when the latest v10 introduces new components, etc.

**Comment by Turokhunter** [comment]
I believe you are correct. I ended up rewriting it with the functions for 9v. But that is really bad when two pieces of documentation are desynced from each other.  I'm pretty sure that the build an app example is 9v while all Polaris doc is v10.  

I also agree that Polaris documentation should have versioning when all other documents(GraphQL, REST) already have the ability to switch package versions.
