### ISSUE TITLE
[Layout training] Create intro video

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#8563]
* What are the topics covered in the video?
* video script
* record
* edit
* post to the new Layout resource page

**Comment by tracytees** [comment]
Script and outline [in progress](https://docs.google.com/document/d/1teq1t-CCqQXcQ1RUgcLViby0hebbgyVzUlIyt2vYKAo/edit?usp=sharing)

**Comment by tracytees** [comment]
Slides complete and needing to implement feedback. Once that is complete, this task will be paused until we complete the layout resource page itself
[Slides are here](https://docs.google.com/presentation/d/18zYcEkHGBKVKZUJaxsAmlWuB3Kvvjz6WygcmGZ1opg8/edit?usp=sharing)

**Comment by jjgali** [comment]
Update: Finishing this up for @tracytees and will resume work when I return on Monday April 17.

**Comment by jjgali** [comment]
After reviewing the assets we've already produced for layout, including the layout documentation and the workshops, we've determined that the layout video isn't necessary at this time.
