### ISSUE TITLE
[Layout training] How do we include long-form content + code + dynamic example?

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#8566]
Our layout training page should:
* have long-form written content for explaining layout topics
* include code examples of building admin UI with layout primitives (with step by step guidance?)
* Have an intro video to explain some of the key concepts

Open questions:
* How do we do all of this on one page without technically re-inventing the wheel, overwhelming our users, and creating a content management nightmare? 
* What can we reuse from the site easily? 
* What should be net new on the site because it needs to be _meaningfully different_ from what we currently offer?

**Comment by jjgali** [comment]
>How do we do all of this on one page without technically re-inventing the wheel, overwhelming our users, and creating a content management nightmare?

The TOC should help with this, but we can order in such a way that the most relevant information starts at the beginning. Be it principles, assets, examples, etc. 

>What can we reuse from the site easily?

I like the visual + code examples that exist on the new patterns pages. Maybe we can tweak these slightly so they're less template-y (new word alert 🚨) and more like examples.

>What should be net new on the site because it needs to be meaningfully different from what we currently offer?

TBD on this for me. I think we'll know once we get the documentation in a good place. But I'm assuming embedded video will be kind of new / not commonplace. Also, potentially sectioning out the video to be peppered throughout the documentation, like @tracytees had suggested.
