### ISSUE TITLE
[Layout training] Schedule and prepare an interactive layout workshop

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#8567]
Hosted by Jess when his schedule allows for it

* Where should this event be held to make it most interactive? (google meet?)
* Set the agenda/script for the workshop
* How will this workshop go? ex. everyone build the same thing and then share? Jess shares screen and drives while everyone else directs him with the code (like a giant pair programming session)? something else?
* Choose the piece of admin UI that we'll be building together
* Create the final version of the polaris sandbox to share out
* Share out the resources and survey

**Comment by jjgali** [comment]
Started a [workshop playbook draft](https://docs.google.com/document/d/1yBDThPFwZNouUtmGlgcmXWtu3nnjw8mdaNPnqhK0KF8/edit?usp=sharing)—just linking here so we can add to it and iterate based on future workshops.
