### ISSUE TITLE
Update depth token naming conventions

### ISSUE THREAD

**Issue by heyjoethomas** [Shopify/polaris-react-archive#8571]
## Issue summary

Migrate old depth tokens to new/semantically named conventions that better follow Polaris standards. 

Old tokens should be mapped to new. All mappings are in [this Figma file](https://www.figma.com/file/Z5cnrNV7Ild1pGSOM5bRSC/New-Polaris-Shadow-Tokens?node-id=148%3A50776&t=CZA7A9DIaerRS1Qb-11)

**Comment by lgriffee** [comment]
Closed via https://github.com/Shopify/polaris/pull/8601 and https://github.com/Shopify/web/pull/85942
