### ISSUE TITLE
AlphaStack stretching children even without fullWidth

### ISSUE THREAD

**Issue by Guuz** [Shopify/polaris-react-archive#8579]
Today me and @IrinaLipovaya tried to build this piece of UI with all the new Polaris layout components that are in alpha.
<img width="546" alt="image" src="https://user-images.githubusercontent.com/810327/223477452-6c6ce74d-a876-4c14-8769-577ae7f26e65.png">

We ran into something that feels strange to us. It might be a bug. If not perhaps this feedback is useful to the Polaris team as we as developer do not understand this behaviour.

Our first simplified approach: [Sandbox link](https://polaris.shopify.com/sandbox?code=N4Igxg9gJgpiBcIA8BBANgBwBYEMDKALjmANYAEA5jhgLwA6IALAwHx0B2ZZqmuAwjgBOUNpy7cAKjAAeBMjgDO9EFgBMDMgDchASxzsCyrDBxQd7CgFkorAcLKQDMA0gD0U2aK5v02HHZEOcSDJGTlFZQwNSDQIQWUFAFcAIyhEmBsQFgAZOJgAWzIdDCTCqAhYwTIFHXD8mAIAGgcIdgUYMAIGxKrTYp0FMHMKMhg0WoA6MgAFMbRnLoUAR3SyfJxpHXzEhTIMOYWYZdWjuXaoeXGVhom3DwIvMhCkACFEggJWsjMFHGT5i4YQRbIQATxYeBS%2BVqbjeH1aoh8vHwRFIohAjRABGM9QUCAA2iBYmAcPN4M4QABdTEAdx0UGxePg%2BIA7AA2AAcjQAjIxGAAGSkAXyAA)
```tsx
<AlphaStack gap="4">
  <AlphaCard>
    <Text as="h2" variant="headingMd">Card content</Text>
  </AlphaCard>
   
  <Text as="p" color="subdued">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque maximus pellentesque est sed aliquet.</Text>
  
  <Button disabled primary>Submit</Button>
</AlphaStack>
```
This results in a stretched button. Even though neither the `Button` nor the `AlphaStack` has the `fullWidth` enabled. We tried setting it to `false` explicitly to no avail.

We managed to do it this way: [Sandbox link](https://polaris.shopify.com/sandbox?code=N4Igxg9gJgpiBcIA8BBANgBwBYEMDKALjmANYAEA5jhgLwA6IALAwHx0B2ZZqmuAwjgBOUNpy7cAKjAAeBMjgDO9EFgBMDMgDchASxzsCyrDBxQd7CgFkorAcLKQDMA0gD0U2aK5v02HHZEOcSDJGTlFZQwNSDQIQWUFAFcAIyhEmBsQFgAZOJgAWzIdDCTCqAhYwTIFHXD8mAIAGgcIdgUYMAIGxKrTYp0FMHMKMhg0WoA6MgAFMbRnLoUAR3SyfJxpHXzEhTIMOYWYZdWjuXaoeXGVhom3DwIvMhCkAEl2cfYYS50KdmVnTKPbwAIUSBAIrTIZgUOGS8wuGEEWyEAE8WHgUvlam5QeDWo83G8PjBRD5ePgiKRRCBGiACMZ6goEABtECxMA4ebwZwgAC6tIA7jooPSmfBmQB2ABsAA5GgBGRiMAAMvIAvkA)
```tsx
<AlphaStack gap="4">
  <AlphaCard>
    <Text as="h2" variant="headingMd">Card content</Text>
  </AlphaCard>
   
  <Text as="p" color="subdued">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque maximus pellentesque est sed aliquet.</Text>
  
  <Inline align="end">
    <Button disabled primary>Submit</Button>
  </Inline>
</AlphaStack>
```

We probably need the `Inline` anyway to move the button to the right side. But also adding a `Box` around the `Button` fixes the full width issue. So the behaviour is unexpected to us.

Hope this helps! Happy to hear your thoughts :)

**Comment by aveline** [comment]
Hi @Guuz, thanks for opening this issue.

Stack uses `flex` under the hood and by default flex will stretch children to fill the container which is why the button gets stretched. When you wrap it in `Inline` or a `Box`, that becomes the flex child which is stretched and button can revert back to its intended size.

`Inline` is the intended way to manage horizontal alignment so that looks good to me.

Thanks for the feedback that `fullWidth` was confusing, it was originally added when we were aligning `start` by default, but can probably be removed now.

**Comment by Guuz** [comment]
I see this PR now as well: https://github.com/Shopify/polaris/pull/8582
If `fullWidth` gets removed from AlphaStack and the intended behaviour is to have it's children stretched (and the docs show this) i think all confusion would be cleared up in the future! :) Happy to help!
