### ISSUE TITLE
Feature Request: Shared CDN heavy-weight bundle

### ISSUE THREAD

**Issue by aschmoe** [Shopify/polaris-react-archive#86]
# Issue summary

Been porting apps over to React to take advantage of upcoming (already happened?) Polaris updates, seems like it would be relatively trivial to bundle-split shared react libraries for embedded apps, etc.

Likely inclusions

react-dom
core-js (or other polyfills)
react
prop-types

Perhaps ~100kb gzipped is not worth the effort but thought I would see if this was on your radar... or if you're already doing this.

Thanks,
Alex

**Comment by lemonmade** [comment]
This is an interesting idea. I'll open up an issue for us to take a look at this in the future. My main concern here is the versioning story: we'd be locking you in to a set of versions and potentially standing in the way of partners getting certain updates that might be useful to their particular apps.

I think all of these have a CDN-hosted version that could be used in apps. It would potentially be different between apps, but would potentially be the same as other sites, so the caching story is probably mostly a wash. I am curious what your thoughts are on simply using those instead.

**Comment by aschmoe** [comment]
I was thinking that if Shopify's UI was "eating its own dogfood" with the Polaris component library and anticipating app developers to follow suit, there would clearly be some overlap that could be useful to cache.  Barring major React version changes in Polaris this would be unlikely to cause too much headache for app developers.

But looks like you're not using React on the Shopify admin pages (yet), so perhaps this is all down the road.

Cheers

**Comment by ry5n** [comment]
This is still an interesting idea, and we’re still tracking this in our backlog. However, we haven’t been able to move it to the top of the stack to actively explore, so I’d like to close it for now.

However, **we encourage everyone who wants this feature to add a 👍** to the original issue report. We’ll take your collective interest into account when we look at what to work on next.
