### ISSUE TITLE
Textfield Multiline is not bubbling focus to Popover [Includes MR]

### ISSUE THREAD

**Issue by shawngrona** [Shopify/polaris-react-archive#8618]
## Issue summary
Textfield Multiline is not bubbling focus to Popover

If you have a multiline text field on the same page as a popover it does not bubble up the focus event for that multiline textfield to the popover for close.  A common example of this is if you had a Datepicker wrapped in Popover with Textfield for results and another multiline textfield on the same form.  

I've created a minimum reproduction here: https://codesandbox.io/s/mr-polaris-popover-close-multiline-text-field-forked-3e8699 

FYI I noticed some related changes to fix a bug with focus on multiline in [this PR](https://github.com/Shopify/polaris/pull/6955)

## Expected behavior

Expected: When you have an open popover and you click a multiline textfield, the popover closes

## Actual behavior

Actual: The popover does not close when clicking the multiline textfield

## Steps to reproduce the problem

Using the [minimum reproduction](https://codesandbox.io/s/mr-polaris-popover-close-multiline-text-field-forked-3e8699)
1. Click the textfield labeled 'On Date' to trigger the popover to open
2. Click the textfield labeled 'Single Line' to trigger the popover to close
3. Click the textfield labeled 'On Date' again to trigger the popover to open
4. Click the textfield labeled 'Mulitline' 

Expected: the popover closes

## Reduced test case

https://codesandbox.io/s/mr-polaris-popover-close-multiline-text-field-forked-3e8699

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 10.35.0
- Browser: Chrome
- Device: Macbook Pro
- Operating System: Mac Ventura 13.2.1

**Comment by schmitty42** [comment]
+1

**Comment by ryanwabraham** [comment]
+1

**Comment by shawngrona** [comment]
Hi any update here?

**Comment by shawngrona** [comment]
still relevant
