### ISSUE TITLE
[Layout training] Write a TL;DR/cheatsheet for the Layout training page

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#8632]
Can we distill the most important points in the training page into a TL;DR section up top for easy scanning? Similar to https://polaris.shopify.com/contributing/working-with-the-polaris-team

**Comment by jjgali** [comment]
I feel like at this point, we don't really need this. The page reads really well, is brief, and contains lots of great visuals! Gonna close this out but feel free to re-open if you think otherwise @yurm04
