### ISSUE TITLE
[polaris.shopify.com] Missing a `/` in the link to edit docs page

### ISSUE THREAD

**Issue by kassiwin** [Shopify/polaris-react-archive#8669]
## Issue summary
The `Edit this page` link at the bottom of the documentation page leads to a 404. Noticed that there is a missing `/`in the URL.

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/26141092/225381259-082e3b79-5570-4e01-a80f-46ed0b6e47c9.png">

## Expected behavior
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/26141092/225381770-c09d88e7-32d0-4ee9-baa0-a3f7df771ea5.png">

## Actual behavior
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/26141092/225381582-201d719b-bba9-4394-a4a6-6adc1cb6e638.png">

## Steps to reproduce the problem

1. Go to https://polaris.shopify.com/components/lists/option-list for instance.
2. Scroll to the bottom of the page and click on [Edit this page](https://github.com/Shopify/polaris/tree/mainpolaris.shopify.com/content/components/lists/option-list.md)

**Comment by SMAKSS** [comment]
This is an unexpected occurrence, but we are once again witnessing the presence of a missing `/` in the path. We inadvertently overrode the `editPageLinkPath` instances while attempting to resolve a [build-related](https://github.com/Shopify/polaris/pull/11113) issue. However, we neglected to rectify the actual `editPageLinkPath` instances.

@alex-page @kyledurand

**Comment by SMAKSS** [comment]
Implemented a fix on #13982.
