### ISSUE TITLE
[Index table] Rows can be selectable even when they are disabled

### ISSUE THREAD

**Issue by JulienHe** [Shopify/polaris-react-archive#8729]
## Issue summary

You can select a row inside an index table even if the row is disabled by selecting the `all` row checkbox in the heading.

## Expected behavior

When a row is disabled, it should never be possible to select it. This can lead to behavior where merchants / anyone can do actions on row that should they should not be able to.

## Actual behavior

The current Index table row can receive the props `disabled` that is a boolean.
The behavior is the following: `A boolean property indicating whether the row should be disabled`

Which mean that the style is different as the row is subdued and interaction on it like `onClick` are disabled.
You cannot select the row either, and this is the behavior we want.

While you cannot select the row by selecting it directly, there is a workaround where you can select that row even when it's not possible, as it's disabled. When you are selecting all rows in the list with the main checkbox in the heading, you can bypass the disabled row props.

[Video](https://screenshot.click/22-40-1m1o4-havnj.mp4)
[CodeSandbox](https://codesandbox.io/s/nostalgic-sun-tgzdye?file=/App.tsx)

## Steps to reproduce the problem

1. Use the indextable
2. Add row and make one `disabled`
3. Select the row by clicking on the main checkbox in the heading, like in the [video](https://screenshot.click/22-40-1m1o4-havnj.mp4)

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 10
- Browser: Chrome Version 111.0.5563.110
- Device: Apple M1 Pro
- Operating System: Mac os 13.2.1

**Comment by Subhan-Tariq** [comment]
Hello
I got the solution To prevent row selection when a button within a row is clicked in a Polaris index table, you can use the onRowClicked event listener and add a preventDefault() call. 

import {
  IndexTable,
  LegacyCard,
  useIndexResourceState,
  Text,
  Badge,
  useBreakpoints,
} from '@shopify/polaris';
import React from 'react';

function SimpleIndexTableExample() {
  const orders = [
    {
      id: '1020',
      order: '#1020',
      date: 'Jul 20 at 4:34pm',
      customer: 'Jaydon Stanton',
      total: '$969.44',
      paymentStatus: <Badge progress="complete">Paid</Badge>,
      fulfillmentStatus: <Badge progress="incomplete">Unfulfilled</Badge>,
    },
    {
      id: '1019',
      order: '#1019',
      date: 'Jul 20 at 3:46pm',
      customer: 'Ruben Westerfelt',
      total: '$701.19',
      paymentStatus: <Badge progress="partiallyComplete">Partially paid</Badge>,
      fulfillmentStatus: <Badge progress="incomplete">Unfulfilled</Badge>,
    },
    {
      id: '1018',
      order: '#1018',
      date: 'Jul 20 at 3.44pm',
      customer: 'Leo Carder',
      total: '$798.24',
      paymentStatus: <Badge progress="complete">Paid</Badge>,
      fulfillmentStatus: <Badge progress="incomplete">Unfulfilled</Badge>,
    },
  ];
  const resourceName = {
    singular: 'order',
    plural: 'orders',
  };

  const {selectedResources, allResourcesSelected, handleSelectionChange} =
    useIndexResourceState(orders);

  const rowMarkup = orders.map(
    (
      {id, order, date, customer, total, paymentStatus, fulfillmentStatus},
      index,
    ) => (
      <IndexTable.Row
// DO this 
        onClick={() => event.preventDefault()}
        id={id}
        key={id}
        selected={selectedResources.includes(id)}
        position={index}
      >
        <IndexTable.Cell>
          <Text variant="bodyMd" fontWeight="bold" as="span">
            {order}
          </Text>
        </IndexTable.Cell>
        <IndexTable.Cell>{date}</IndexTable.Cell>
        <IndexTable.Cell>{customer}</IndexTable.Cell>
        <IndexTable.Cell>
          <Text as="span" alignment="end" numeric>
            {total}
          </Text>
        </IndexTable.Cell>
        <IndexTable.Cell>{paymentStatus}</IndexTable.Cell>
        <IndexTable.Cell>{fulfillmentStatus}</IndexTable.Cell>
      </IndexTable.Row>
    ),
  );

  return (
    <LegacyCard>
      <IndexTable
        condensed={useBreakpoints().smDown}
        resourceName={resourceName}
        itemCount={orders.length}
        selectedItemsCount={
          allResourcesSelected ? 'All' : selectedResources.length
        }
        onSelectionChange={handleSelectionChange}
        headings={[
          {title: 'Order'},
          {title: 'Date'},
          {title: 'Customer'},
          {title: 'Total', alignment: 'end'},
          {title: 'Payment status'},
          {title: 'Fulfillment status'},
        ]}
      >
        {rowMarkup}
      </IndexTable>
    </LegacyCard>
  );
}

**Comment by Subhan-Tariq** [comment]
Hello Everyone

Attach onClick={() => event.preventDefault()} to IndexTable.Row:
This prevents the default row selection behavior when inner elements (like buttons) are clicked.

<IndexTable.Row
  onClick={() => event.preventDefault()} // Prevent row selection on any click within the row
  id={id}
  key={id}
  selected={selectedResources.includes(id)}
  position={index}
>
  {/* ... table cell content ... */}
</IndexTable.Row>

![Screenshot_1](https://github.com/Shopify/polaris/assets/153935988/3259a729-341c-4655-88b2-63a95b6bad96)
