### ISSUE TITLE
When using ResourceList in a Modal, Bulk actions popover overlaps Modal Footer, so that the buttons in Footer are not clickable

### ISSUE THREAD

**Issue by iamphonghg** [Shopify/polaris-react-archive#8784]
## Issue summary

When using ResourceList as content in a Modal, the Bulk actions popover overlaps the Modal footer, so that the buttons in the footer are not clickable.

## Expected behavior

The bulk actions popover should be fixed above the footer.

## Actual behavior

The bulk actions popover overlaps the footer and the buttons in the footer are not clickable.
This is the photo of the issue, I took it by using Lightshot: https://prnt.sc/jh4-XzQQmBUf

- Are you using the React components? (Y/N): Yes
- Polaris version number: 10.15.0
- Browser: All browser 
- Device: All device
- Operating System: All OS

**Comment by chloerice** [comment]
Hey @iamphonghg 👋🏽 The `BulkActions` shouldn't be used in a `Modal`. You can add the "Delete" action you have to the `Modal` footer by passing the markup into the `footerContent` prop.

**Comment by chloerice** [comment]
Closing this as the bulk actions are no longer a floating overlay, they now render in the index table header.
