### ISSUE TITLE
'motion' is not exported from '@shopify/polaris-tokens'

### ISSUE THREAD

**Issue by sabiriiui** [Shopify/polaris-react-archive#8820]
## Issue summary

I have upgraded @shopify/polaris to latest version (10.40.0) and run few migration scripts. my code is being compiled locally But while making build from production it gives following error 
Attempted import error: 'motion' is not exported from '@shopify/polaris-tokens' (imported as 'motion').

This is internal error from Shopify/Polaris as I'm not using shopify/polaris-tokens locally.

![image](https://user-images.githubusercontent.com/16346134/229042092-ab0f1139-3046-46af-ad84-2fe1a40de5c3.png)

## Expected behavior
Currently my build is failing because of above error, there shouldn't be any error from Polaris internal components 

## Specifications

- Are you using the React components? (Y/N): YES
- Polaris version number: 10.40.0
- Browser: Chrome
- Device: AWS
- Operating System: AWS

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by tryrushio** [comment]
+1 for this
