### ISSUE TITLE
[Prototype] Setup package.json for `/polaris-patterns`

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#8847]
The [prototype branch](https://github.com/Shopify/polaris/pull/8819/files) has a `package.json`, but its mostly copied over from `polaris-react`. Lets think through key dependencies like `polaris-react` and `typescript` and how we want to set them up to benefit from changesets

**Comment by jesstelford** [comment]
Open question: Does changesets auto bump `peerDependencies` like it does for `dependencies`? _Update_: **Yes**, it does!

If so, we should list `@shopify/polaris` as a `peerDependency` of `polaris-patterns`. Reasoning:
1. If incompatible versions are installed, the dev will get yelled at by yarn/npm
2. If incompatible versions are installed, their website should break in obvious ways (typescript failures, etc)
