### ISSUE TITLE
Improve search on polaris.shopify.com to include results from Content > Grammar and mechanics

### ISSUE THREAD

**Issue by emilykeefe** [Shopify/polaris-react-archive#8860]
## Feature request summary

Today, the search on polaris.shopify.com doesn't show the best results for certain content searches. I don't know why this is (Is it an IA issue? Should we ensure that section titles are indexed on subpages? etc) but I suggest we fix this.

For example, if you want to find documentation and guidelines for formatting dates and numbers, doing a search won't deliver the page that actually contains that information: https://polaris.shopify.com/content/grammar-and-mechanics#dates--numbers--and-measurements

Here is a video: https://drive.google.com/file/d/1LtOeqdhOXzzF37Y2fIuQ9dzJY7VlccXB/view?usp=sharing

## Rationale

As a content designer, I've been asked many times "Where do I find [x grammatical guideline]?" and while the answer is in Polaris, our teammates are having trouble finding the information they need. Having these results appear in search would help designers and engineers write better, and consistent content. The answer is there, we just need to make it easier to search for.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s :+1: upvotes to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by mandrsn** [comment]
Yes!!!! I agree - the search needs improvement!

**Comment by pcrede** [comment]
I'd appreciate this too!
