### ISSUE TITLE
No visual difference between Publish and Purchase Theme buttons

### ISSUE THREAD

**Issue by StephenBrownski** [Shopify/polaris-react-archive#89]
# Issue summary

"Purchase Theme" button should use a different button colour than the default action.

## Expected behaviour

Purchase button should be visually distinct from default actions. This is suggested in the 'Accessibility' section of the Polaris docs.
https://polaris.shopify.com/visuals/colors#accessibility
![image](https://user-images.githubusercontent.com/4060866/26951470-748660f2-4c5e-11e7-8110-c2485cb1eb76.png)

## Actual behaviour

On my dev store, I have one un-purchased theme from the theme store. Normally, in place of a 'Publish' button, there was a green 'Purchase' button.

Now, the 'Purchase' button uses the same colour as a primary button, and so there's no visual distinction between the two. This means it's not really possible at a glance to tell the difference between a theme you own, and a theme you are only previewing.

If you blur the theme index page, it's impossible to tell what theme is 'different' from the rest:
https://screenshot.click/08-19-loe2v-8erq8.jpg

If you use the colours (briefly) suggested in the polaris docs, it looks like this:
https://screenshot.click/08-25-vd0x0-ea5py.jpg

Now I'm not sure that this should necessarily use that green, as it's not 'completing' a purchase, but rather initiating one. I think though this could be a good case for including a secondary button style, using some other colour found in the palette.

**Comment by ry5n** [comment]
Thanks for logging this @StephenBrownski. We’re looking into a couple options to resolve the confusion. I think right now we’d prefer to improve the themes index within the Shopify admin rather than re-introduce the green button style in Polaris. Either way, I’ll leave this issue open until we’ve resolved it.

**Comment by ry5n** [comment]
The themes index has been redesigned, and no longer has this issue. (With Polaris, there should be just one primary button per screen, and green is no longer used to denote a purchase button.)
