### ISSUE TITLE
[Prototype] Add DateList to polaris-patterns

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#8926]
https://polaris.shopify.com/patterns/date-picking/date-list
look for a similar existing component
add stories and tests
attempt README, prototype what kind of info we should include

**Comment by gwyneplaine** [comment]
There's a similar existing component, but it conflates **a lot** of product specific use-cases that I don't think we should add as part of the MVP (as they don't specifically align with guidance we've provided).  I've opted for a refined version of what we have in our date-list pattern.
