### ISSUE TITLE
[Prototype] Add DateRange to polaris-patterns

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#8927]
https://polaris.shopify.com/patterns/date-picking/date-range
find similar one in Admin to copy over
make sure there are stories and tests
prototype what the README should look like

**Comment by gwyneplaine** [comment]
## Painpoints so far: 
* Converting legacy-polaris-v8 usages to appropriate styles and components in Polaris.
  * Do we want to allow legacy-polaris-v8 style usage in the polaris-patterns workspace? 
* Do we want migration to polaris-patterns to be a forcing function for conforming to polaris guidelines? For example: 
  *  `$breakpoint-desktop-max` is 1399px, the closest equivalent in polaris is `$p-breakpoint-xl-down` which is  <=1439px, which has ramifications.
* Ensuring we aren't importing private packages, which usually means inlining code that varies from: 
  * Complex useful hooks and functions 
  * noops and trivial typescript types.

**Comment by gwyneplaine** [comment]
* Some of these sass styles should be converted to polaris primitives. 
* Seems like any conversion will likely require UX input.

**Comment by sophschneider** [comment]
@gwyneplaine are you cool if I close this issue? In light of descoping DatePicking from our prototype due to its complexity that you discovered here

**Comment by gwyneplaine** [comment]
yeah lets close this 👍
