### ISSUE TITLE
JSX support for `styles-replace-custom-property`

### ISSUE THREAD

**Issue by schonert** [Shopify/polaris-react-archive#8928]
## Issue summary
The style migrations do not migrate component props or styled-components. 

## Expected behavior
We'd expect migrations that impact a lot of different components to not only update CSS files. But also Polaris component props, inline styles and styled-components.
**Polaris Components**
```jsx
// Before
<Box background="surface-subdued"></Box>

// After
<Box background="bg-subdued"></Box>
```
**Inline styles**
```jsx
// Before
<div style={{ backgroundColor: 'var(--p-surface-subdued)' }}></div>

// After
<div style={{ backgroundColor: 'var(--p-color-bg-subdued)' }}></div>
```

**Styled Components**
```jsx
const StyledContainer = styled.div({
  // Before
  backgroundColor:  'var(--p-surface-subdued)',
  // After
  backgroundColor: 'var(--p-color-bg-subdued)',
})

const StyledContainer = styled.div`
  // Before
  background-color: var(--p-surface-subdued);
  // After
  background-color: var(--p-color-bg-subdued);
`

```

## Actual behavior

```bash
$ npx @shopify/polaris-migrator v11-styles-replace-custom-property-color src --dry
  ...
  src/features/billing/components/BillingPage.tsx Transformation error (<css input>:1:10: Unknown word)
  CssSyntaxError: <css input>:1:10: Unknown word
  ...
  All done. 
  Results: 
  357 errors
  13 unmodified
  0 skipped
  0 ok
```

## Steps to reproduce the problem

1. npx @shopify/polaris-migrator v11-styles-replace-custom-property-color src --dry

## Reduced test case
Can't get codesandbox to convert into Cloud space to run the terminal. Please let me know if you'd like me to give it a second go.

## Specifications

```bash
  System:
    OS: macOS 13.3
    CPU: (12) arm64 Apple M2 Pro
    Memory: 79.59 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.asdf/installs/nodejs/18.14.2/bin/node
    Yarn: 1.22.19 - ~/Projects/pixify/pixify/node_modules/.bin/yarn
    npm: 9.5.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Brave Browser: 111.1.49.128
    Firefox: 111.0.1
    Safari: 16.4
  npmPackages:
    @shopify/polaris: ^10.38.0 => 10.42.1 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
```

**Comment by schonert** [comment]
@alex-page any documentation or guidelines on how the Porlaris team expects Shopify App devs to keep up with all the breaking changes coming our direction? This seems to just be one of many

**Comment by alex-page** [comment]
We currently don't support these approaches and migrations for them. Understand this is going to be a friction point for developers building in this way. I'll share the feedback with the team but I can't promise this will be resolved any time soon.

**Comment by schonert** [comment]
Thanks for getting back to me. No plans for supporting Polaris components either? Not sure how we are expected to use Polaris to follow along upgrade path without this friction?

**Comment by alex-page** [comment]
We definitely want to add more flexibility and are exploring the possibilities of a `style` property. This is going to be a while away though. Trying to keep expectations real and also understand this is a pain point for teams that use Polaris + css in js.

**Comment by schonert** [comment]
This is not just the `style` and css-in-js - this is migrating your own components. For instance:
```
// Before
<Box background="surface-subdued"></Box>

// After
<Box background="bg-subdued"></Box>
```

**Comment by schonert** [comment]
Also - I'm not sure where I can find all the new properties and where to stay updated on changes like this.

**Comment by alex-page** [comment]
We have a migration for property changes. I don't know if we documented all of the mappings specifically for the Box component. But the token mappings exist and you can use the property migration to update those.

We just shipped v11 to NPM so you can now see documentation here: https://github.com/Shopify/polaris/blob/main/documentation/guides/migrating-from-v10-to-v11.md
