### ISSUE TITLE
Cards missing bottom border radius when children have horizontal scrollbar

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#8933]
**Raised by:** @ouellettejordan @sainihas @WillsonSmith @mattkubej
**Slack thread:** https://shopify.slack.com/archives/C4Y8N30KD/p1680721907344049

In Settings > Metafields and Settings > Custom Data there are `IndexTables` that horizontally scroll. The radius can re-appear when the scroll bar appears when playing with the browser width it seems.

Next steps:
- [ ] Investigate why horiztonal scrolling cards (like IndexTables in settings) have no bottom border radius
- [ ] Ship fix

![screenshot_2023-04-05_at_3 10 40_pm](https://user-images.githubusercontent.com/19199063/231349615-67e3eba2-85d2-41a3-806c-a5c9e2fef731.png)

![screenshot_2023-04-05_at_11 44 38_am](https://user-images.githubusercontent.com/19199063/231349687-16cf4f6d-63fa-4cc7-af23-c1844fd7d03c.png)

**Comment by martenbjork** [comment]
Possibly related: https://github.com/Shopify/shopify/issues/410640

**Comment by alex-page** [comment]
Yes that is the same issue. I see there are no assignees there. So whoever picks this up should also assign themselves on the admin quality wins issue as well.

**Comment by alex-page** [comment]
Closed by https://github.com/Shopify/web/pull/89356
