### ISSUE TITLE
[Prototype] Update storybook

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#8958]
Update storybook in both `polaris-react` and `polaris-patterns`

**Comment by sophschneider** [comment]
I updated `polaris-patterns` storybook in https://github.com/Shopify/polaris/pull/8965 but now the CI node 14 check is failing because storybook 7 requires that node is 16 or higher. Is there a way we can fix this? We don't need storybook for this CI step

![Image](https://user-images.githubusercontent.com/20652326/232885491-d77b0528-1678-4f9c-9e59-a8451b9a792c.png)

**Comment by sophschneider** [comment]
adding this to the storybook `main.js` config allows it to use the babel config at the root of the repo:
```
  babel: (config) => {
    return {
      ...config,
      rootMode: 'upward',
    };
  },
```

**Comment by jesstelford** [comment]
Node v14 support is being dropped with Polaris v11, which is imminent 🎉 

I've combined @qwynplaine & my previous work with the above work, and got a Draft PR ready that migrates to Storybook v7 with Vite as the builder - just needs Polaris v11 to ship first: https://github.com/Shopify/polaris/pull/9019
