### ISSUE TITLE
[polaris.shopify.com] 404 not found at /components/layout-and-structure/inline

### ISSUE THREAD

**Issue by artyrcheek** [Shopify/polaris-react-archive#8982]
Inline component is missing

**Comment by mhlozek** [comment]
I think it has been renamed to HorizontalStack component #8939 
https://polaris.shopify.com/components/layout-and-structure/horizontal-stack

**Comment by kyledurand** [comment]
Thanks @mhlozek you are correct. We hope to be done with naming changes as we align with other component libraries across the Shopify org
