### ISSUE TITLE
CSS Class Issue.

### ISSUE THREAD

**Issue by johnsonab** [Shopify/polaris-react-archive#9]
# Issue summary

The `Polaris-ResourceList__Item--persistActions` class suggested in the docs for the ResourceList component does not match the CSS class in the styles.scss file that's generated.

## Expected behavior

CSS should use `Polaris-ResourceList__Item--persistActions`

## Actual behavior

CSS is using `Polaris-ResourceList__Item-persistActions`.

## Steps to Reproduce the Problem

Try to implement a ResourceList item with actions and it will not show the actions since the CSS to unhide the element never gets applied. 

## Specifications
- Polaris version: 1.0.0

**Comment by lemonmade** [comment]
Thanks for the issue, @johnsonab. I've added this to our internal issue tracker to resolve in our next release. I'll close this issue once it's resolved.

**Comment by johnsonab** [comment]
Hey @lemonmade. I'm finding this same problem in several areas. The compiled CSS using a single hyphens instead of double hyphens on the modifier. 

Right: `.Polaris-Some__Item--active`

Wrong: `.Polaris-Some__Item-active`

Not sure this is a problem in your compiling that is fixed globally or if I should submit issues for each I find?

**Comment by ry5n** [comment]
@johnsonab Yeah, this was a global thing–we’ve corrected it now in our development repo. You should see this fixed across the board in the next release.

**Comment by johnsonab** [comment]
@ry5n great, thanks for the clarification!
