### ISSUE TITLE
Alignment of icons incorrect when using as prefix value of TextField

### ISSUE THREAD

**Issue by cargix1** [Shopify/polaris-react-archive#90]
# Issue summary

The vertical alignment of an Icon component is incorrect when using as prefix value of TextField. The color of the icon also looks to be incorrect. 

## Expected behavior

I'd expect the search icon to appear like it does within the Shopify orders screen. 

<img width="305" alt="screen shot 2017-06-10 at 21 15 49" src="https://user-images.githubusercontent.com/9730290/27005984-00b0b66c-4e22-11e7-8df6-79d76b4bceb7.png">

## Actual behavior

The icon is dark black rather then the grey color and positioned too close to the top of the textfield.

<img width="671" alt="screen shot 2017-06-10 at 21 14 30" src="https://user-images.githubusercontent.com/9730290/27005989-0e35f61c-4e22-11e7-990c-d9fef9d5f41b.png">

## Steps to Reproduce the Problem

```
<TextField type="search" placeholder="Search ..." prefix={
  <Icon source="search"></Icon>
}></TextField>
```

## Specifications

- Polaris version: 1.0.3
- React version: 15.4.2
- Browser: Chrome
- Device: Macbook Pro
- Operating System: Mac OS Sierra

**Comment by lemonmade** [comment]
Thanks for the issue, @cargix1. I think this is the same issue as https://github.com/Shopify/polaris/issues/60, so I’ll close this one in favour of that issue.
