### ISSUE TITLE
[IndexTable] Inconsistent styling between sticky row and non-sticky row

### ISSUE THREAD

**Issue by mattkubej** [Shopify/polaris-react-archive#9027]
## Issue summary

The sticky row of the Index Table does not match the non-sticky row of the Index Table.

Within Admin, this appears to only occur on initial render of the Index Table, but if you navigate away and come back to the page, then the issue no longer exists.

https://user-images.githubusercontent.com/86790511/233195283-2681dbda-156d-423e-baeb-1b31bfb5cd1f.mp4

## Expected behavior

Sticky row matches the styling of the non-sticky row

## Actual behavior

Differing widths and alignment of column headers

## Steps to reproduce the problem

1. Create an IndexTable with a large number of rows, so that you can trigger the sticky header
2. Scroll down just as the sticky header enables and it overlaps the the non-sticky header

## Reduced test case

Reproducible within the "With Bulk Actions and Selection Across Pages" IndexTable story

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 10.43.0
- Browser: Chrome
- Device: MacBook Pro
- Operating System: macOS

**Comment by sam-b-rose** [comment]
https://github.com/Shopify/polaris/pull/9119 seems to possibly fix this issue. The PR does fix the ["With Bulk Actions and Selection Across Pages" example](https://5d559397bae39100201eedc1-rjawhhlnzz.chromatic.com/?path=/story/all-components-indextable--with-bulk-actions-and-selection-across-pages) in Storybook, and it appears to fix the issue when visiting the [spin link](https://admin.web.sticky-index-table.sam-rose.us.spin.dev/store/shop1/products?selectedView=all).

**Comment by mattkubej** [comment]
> #9119 seems to possibly fix this issue. The PR does fix the ["With Bulk Actions and Selection Across Pages" example](https://5d559397bae39100201eedc1-rjawhhlnzz.chromatic.com/?path=/story/all-components-indextable--with-bulk-actions-and-selection-across-pages) in Storybook, and it appears to fix the issue when visiting the [spin link](https://admin.web.sticky-index-table.sam-rose.us.spin.dev/store/shop1/products?selectedView=all).

How are you testing? I think I'm still seeing the issue with the spin instance you linked

https://user-images.githubusercontent.com/86790511/235169454-63034880-413b-4011-ae6d-03b1650d17eb.mp4

**Comment by sam-b-rose** [comment]
> How are you testing? I think I'm still seeing the issue with the spin instance you linked

~~Interesting, I am not able to reproduce 🤔  this isn't happening for me on page load or after navigating away and them back.~~

It is still happening, just inconsistently. 😢 disregard #9119 as a potential fix. Will keep investigating 🔍

**Comment by hrdwdmrbl** [comment]
This bug is actually at LEAST old as Polaris version 7 since I'm still on that and I get it too!

**Comment by hoangthach1402** [comment]
it still bug on win with vue 

![Image](https://github.com/user-attachments/assets/90c5fb3a-9432-479c-84fe-a59501886399)

.Polaris-IndexTable__StickyTableHeader--isSticky visibility : toggle when i scroll down
