### ISSUE TITLE
UI Kit enhancements

### ISSUE THREAD

**Issue by heyjoethomas** [Shopify/polaris-react-archive#9032]
Needed enhancements to UI Kit to better serve designers.
- [ ] Add ReadMe/Getting started to set context for file
- [ ] Organize icons to increase discoverability and legibility
- [x] #9131
- [ ] Create admin views library/section for full screen mocks/templates
- [ ] Add common admin components/compositions
- [ ] Add utilities page with things like cursors, slots and image placeholders
- [ ] Update change log to make it easier to maintain and document who made changes
- [ ] Add anatomy section to components
- [ ] Polaris pattern components
- [ ] Remove/deprecate unused icons

**Comment by bernardojoaogarcia** [comment]
Metadata as in Description + Tags? @heyjoethomas

**Comment by bernardojoaogarcia** [comment]
What do you think of adding the new Pattern components to the UI Kit? i.e. Date picking (Single date, Date range, Date list)

**Comment by heyjoethomas** [comment]
> Metadata as in Description + Tags? @heyjoethomas

Yes to help make search and discovery better.
