### ISSUE TITLE
[Prototype][Discussion] Form a decision about dependencies for our new library

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#9038]
will we let consumers install anything? what are our boundaries. ui tools vs. shopify quilt tools vs. external libraries

**Comment by gwyneplaine** [comment]
Starting point for us to continue this discussion / solidify opinions [here](https://docs.google.com/document/d/1Ox2g0VLaEBK8P_Rwqt1ciOMFbFA_r9vElyChLF6kLvs/edit?usp=sharing)
