### ISSUE TITLE
Popover remains open after setting active to false

### ISSUE THREAD

**Issue by krystalcampioni** [Shopify/polaris-react-archive#9050]
## Issue summary

----
### What are you trying to accomplish?

There seems to be an issue where the popovers do not disapear after setting the `active` prop to `false`

https://user-images.githubusercontent.com/4037781/233699168-37191119-16d4-4098-82c5-842d83da1454.mov

The issue seems to come from the `<PopoverOverlay>` component. The component receives `active` as `false` correctly through props, but does not update the `transitionStatus` to `exited`; it remains as `entered`.

![Screenshot 2023-04-21 at 1 27 42 PM](https://user-images.githubusercontent.com/4037781/233699443-f25f025f-5b9b-4072-80f5-21987bd40456.png)
----
## Expected behavior

setting `active` to `false` should unmount the popover

## Actual behavior

setting `active` to `false` sometimes maintains the popover visible

## Steps to reproduce the problem
Hover/leave repeatedly on the button to trigger the activation. Sometimes, even though active is false, the popover remains visible

## Reduced test case

https://codesandbox.io/s/dreamy-cherry-v0dr8d?file=/App.tsx

## Specifications

```bash
  System:
    OS: Linux 5.10 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (32) x64 Intel(R) Xeon(R) CPU @ 2.80GHz
    Memory: 158.43 GB / 251.90 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  npmPackages:
    @shopify/polaris: ^10.45.0 => 10.45.0 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 

```

**Comment by heyjoethomas** [comment]
Thanks for reporting. This issue has been resolved.
