### ISSUE TITLE
Ugly border appeared while rendering Text field with verticalContent

### ISSUE THREAD

**Issue by jessehao** [Shopify/polaris-react-archive#9061]
## Issue summary

Ugly border appeared while rendering **Text field** with `verticalContent`
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/5467890/233817341-220b93ce-b04a-4037-9e8e-1ebbe0d3d3d2.png">

**Comment by moraleslevi** [comment]
This seems to be caused by `overflow: scroll` drawing unnecessary empty scrollbars around the `TextField`.
