### ISSUE TITLE
LegacyFilters

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#9069]
Either
- [ ] Remove the LegacyFilters component in v11
- [x] Deprecate the LegacyFilters component (not legacy) it is being removed in the next breaking version

**Comment by laurkim** [comment]
I'll make a PR to remove LegacyFilters in v11 and move the component to the admin 👍

**Comment by alex-page** [comment]
Thank you @laurkim!

**Comment by laurkim** [comment]
Pivoted to instead deprecate LegacyFilters and remove it in a subsequent major release.
