### ISSUE TITLE
v11 tokens page is not renderimg

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#9071]

**Comment by laurkim** [comment]
The tokens page loads for me locally after building off latest version of v11. It could have been an issue of needing to build the tokens package when we were going through the style guide

![25-55-2vgna-iy77c](https://user-images.githubusercontent.com/26749317/234268860-9276dd6f-c732-47fd-bf3d-e566fffb3bbe.png)

**Comment by lgriffee** [comment]
Closed by: #8374
