### ISSUE TITLE
Navigation Component menu doesn't toggle in mobile

### ISSUE THREAD

**Issue by ctrlaltdylan** [Shopify/polaris-react-archive#9114]
## Issue summary

The `<Navigation>` component does not toggle in mobile.

## Expected behavior

I expect the menu to be toggle-able in mobile views.

## Actual behavior

Clicking the menu button is unresponsive, the `onClick` handler is never called.

![CleanShot 2023-04-27 at 16 14 18](https://user-images.githubusercontent.com/2694734/234980722-6272af66-6218-4b73-9c7a-4370a07560dc.gif)

## Steps to reproduce the problem

1. Integrate AppBridge & Polaris
1. Create a `<Frame>` component with a `<Navigation>` prop with at least one link.
1. Open the app in mobile view
1. Attempt to open the Navigation menu

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number: 10.11.0
- Browser: Chrome
- Device: iPhone
- Operating System: iOS

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by kyledurand** [comment]
The Frame doesn't manage its own state for the mobile menu. Instead there are callbacks within the Frame and TopBar for consumers to make use of. Checkout the details page we have set up in storybook on how to get this working: https://github.com/Shopify/polaris/blob/main/polaris-react/playground/DetailsPage.tsx#L61

**Comment by kyledurand** [comment]
Going to close this for now. Feel free to reopen if you're still stuck @ctrlaltdylan
