### ISSUE TITLE
Regression in IndexTable on mobile prevents rows from being clickable

### ISSUE THREAD

**Issue by thetrevorharmon** [Shopify/polaris-react-archive#9142]
## Issue summary

[This PR](https://github.com/Shopify/polaris/pull/8776#event-8935702601) introduced a change that prevents rows from being selectable on mobile, in order to prevent the checkbox associated with bulk actions from being shown. The change had the side effect of preventing _any_ clicking of the row on mobile, which means that the user cannot click on a row and drill down to a detail page. In [the docs](https://polaris.shopify.com/components/tables/index-table), it says that one of the purposes of an index table is to help merchants "navigate to a full-page representation of [the row]", so I would term this as a bug.

## Expected behavior

`onClick` events passed to `IndexTable.Row` are fired.

## Actual behavior

`onClick` events passed to `IndexTable.Row` are **not** fired.

## Steps to reproduce the problem

I have a working example [here](https://codesandbox.io/s/lingering-hill-rh0rme?file=/App.tsx). You can use the button to toggle the `condensed` property. 

- When it is not condensed, clicking a row shows an alert to the user.
- When it is condensed, the alert is not shown.

<details>
<summary>Code of example</summary>

```jsx
import {
  IndexTable,
  LegacyCard,
  useIndexResourceState,
  Text,
  Badge,
  Button,
  Stack
} from "@shopify/polaris";
import React from "react";

function SimpleIndexTableExample() {
  const [isCondensed, setIsCondensed] = React.useState(false);

  const orders = [
    {
      id: "1020",
      order: "#1020",
      date: "Jul 20 at 4:34pm",
      customer: "Jaydon Stanton",
      total: "$969.44",
      paymentStatus: <Badge progress="complete">Paid</Badge>,
      fulfillmentStatus: <Badge progress="incomplete">Unfulfilled</Badge>
    },
    {
      id: "1019",
      order: "#1019",
      date: "Jul 20 at 3:46pm",
      customer: "Ruben Westerfelt",
      total: "$701.19",
      paymentStatus: <Badge progress="partiallyComplete">Partially paid</Badge>,
      fulfillmentStatus: <Badge progress="incomplete">Unfulfilled</Badge>
    },
    {
      id: "1018",
      order: "#1018",
      date: "Jul 20 at 3.44pm",
      customer: "Leo Carder",
      total: "$798.24",
      paymentStatus: <Badge progress="complete">Paid</Badge>,
      fulfillmentStatus: <Badge progress="incomplete">Unfulfilled</Badge>
    }
  ];
  const resourceName = {
    singular: "order",
    plural: "orders"
  };

  const {
    selectedResources,
    allResourcesSelected,
    handleSelectionChange
  } = useIndexResourceState(orders);

  const rowMarkup = orders.map(
    (
      { id, order, date, customer, total, paymentStatus, fulfillmentStatus },
      index
    ) => (
      <IndexTable.Row
        id={id}
        key={id}
        selected={selectedResources.includes(id)}
        position={index}
        onClick={() => alert("Clicked on IndexTable Row")}
      >
        <IndexTable.Cell>
          <Text variant="bodyMd" fontWeight="bold" as="span">
            {order}
          </Text>
        </IndexTable.Cell>
        <IndexTable.Cell>{date}</IndexTable.Cell>
        <IndexTable.Cell>{customer}</IndexTable.Cell>
        <IndexTable.Cell>{total}</IndexTable.Cell>
        <IndexTable.Cell>{paymentStatus}</IndexTable.Cell>
        <IndexTable.Cell>{fulfillmentStatus}</IndexTable.Cell>
      </IndexTable.Row>
    )
  );

  return (
    <LegacyCard>
      <Stack vertical>
        <Button onClick={() => setIsCondensed((condensed) => !condensed)}>
          Table is {isCondensed ? "condensed" : "expanded"}
        </Button>
        <IndexTable
          resourceName={resourceName}
          itemCount={orders.length}
          selectedItemsCount={
            allResourcesSelected ? "All" : selectedResources.length
          }
          condensed={isCondensed}
          selectable={true}
          onSelectionChange={handleSelectionChange}
          headings={[
            { title: "Order" },
            { title: "Date" },
            { title: "Customer" },
            { title: "Total", alignment: "end" },
            { title: "Payment status" },
            { title: "Fulfillment status" }
          ]}
        >
          {rowMarkup}
        </IndexTable>
      </Stack>
    </LegacyCard>
  );
}

export default SimpleIndexTableExample;
```
</details>

## Reduced test case

https://codesandbox.io/s/lingering-hill-rh0rme?file=/App.tsx:0-3056

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 10.45.0
- Browser: Chrome
- Device: MacBook
- Operating System: MacOS

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash
  System:
    OS: Linux 5.10 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (32) x64 Intel(R) Xeon(R) CPU @ 2.80GHz
    Memory: 160.38 GB / 251.90 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  npmPackages:
    @shopify/polaris: ^10.42.1 => 10.45.0 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
```

**Comment by chloerice** [comment]
Hey @thetrevorharmon  👋🏽 I'm unable to replicate this, I can navigate from my test store and locally. Is there a particular index that isn't working? The [reduced test case sandbox](https://codesandbox.io/s/lingering-hill-rh0rme?file=/App.tsx:0-3056) linked doesn't have any links in the row markup to trigger row click navigation. Here's a [sandbox](https://codesandbox.io/s/indextable-condensed-navigation-jkvzuo?file=/ListPage.tsx) showing how to do that.

**Comment by jesstelford** [comment]
@thetrevorharmon I'm going to close this one as it looks like it's fixed by https://github.com/Shopify/notebooks/pull/3352?
