### ISSUE TITLE
[Prototype] Create rough implementation of AppSettingsLayout and ResourceDetailsLayout

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#9157]
We need a rough implementation of [app settings layout](https://polaris.shopify.com/patterns/resource-index-layout) and resource details layout (https://polaris.shopify.com/patterns/resource-details-layout).

* We could potentially just use the Polaris `Layout` component for now for both, and then still include the compositional implantation on the doc site.
* We could also potentially create a [compositional component](https://epicreact.dev/one-react-mistake-thats-slowing-you-down/) to make these layouts as extendable as possible

They will both need tests and a story as well.

**Comment by johanstromqvist** [comment]
Are these implementations the components that will live in `polaris-patterns` and the ones that will get code documentation on the doc site?

Not sure it applies here, but when we've discussed using `Layout` component vs primitives in the past, we've said that we want to be future looking in the patter docs. So I'm assuming we would want a new pattern component that consumes primitives – is that right?

**Comment by johanstromqvist** [comment]
Lots of useful context and opinions in the team's exploration of rebuilding `Layout` with primitives: https://github.com/Shopify/polaris/pull/7391
