### ISSUE TITLE
Organize pattern "variants" as discrete pattern pages

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#9183]
Simplify the patterns IA by removing the concept of "variants" from the pattern pages and organize current variants as discrete pattern pages.

Brief rationale:
- Current "variants" are already discrete UI elements with their own complete UX guidance, resources, and code documentation (soon). They are essentially complete pages, only related by the type of activity it is.
- The variant tabs are unconventional and make the IA complex (my bad). Imagine adding code documentation and other features (such as Figma resources) to each date picking pattern.
- The visual design of the tabs was a necessity to make it clear what content the tabs control. However, it adds visual noise to the page and subdues the content.

![Image](https://github.com/Shopify/polaris/assets/38329124/4e714bb3-0d44-4afb-884e-8633a9b7c3fc)

|   | Pattern index | Pattern page |
|--------|--------|--------|
| Before | ![Image](https://github.com/Shopify/polaris/assets/38329124/2b458561-17ab-44bd-a5c8-d6ea40761e6a) | ![Image](https://github.com/Shopify/polaris/assets/38329124/015d58df-23aa-49da-a496-2fa5db7b8caf) |
| After | ![Image](https://github.com/Shopify/polaris/assets/38329124/89ace908-c15d-4821-afe6-1d02cf25e152) | ![Image](https://github.com/Shopify/polaris/assets/38329124/de5fa51b-23bf-4bc0-bbbd-7af55e662c9d) |

## Design TODO
- [ ] Create thumbnail assets
- [ ] Write page subtitles
- [ ] Write related resources

## Engineering TODO
- [x] Remove variant logic from polaris.shopify.com patterns section
- [x] Remove tab component
- [x] Move date picker pages to top level (siblings with AppSettingsLayout and ResourceDetailsLayout)

**Comment by sophschneider** [comment]
@johanstromqvist What about the parent Date picker page with all the content outside of the tabbed view?

**Comment by sophschneider** [comment]
Just talked to Johan, the above design is a stepping stone to rework what we currently have and eventually work towards this IA

![Image](https://github.com/Shopify/polaris/assets/20652326/69593ec1-e22b-4572-a9b7-6daa0aeeede0)
