### ISSUE TITLE
Text Field When used as currency . (dot) is not working

### ISSUE THREAD

**Issue by swathign-sbdinc** [Shopify/polaris-react-archive#9193]
## Issue summary

Im currently using Mui text Field for my currency input 

- I want to enter number with decimal values for example , 123.45 (which is not currently working)
- Sanbox for the same :  https://codesandbox.io/s/amazing-hoover-lsdqm3?file=/demo.tsx:242-371 (Please check the console on dot entry number goes away)
- Here Whenever i'm typing it is not allowing decimal values as input
- I have added type=number as per the documentation
- When the **Intl.NumberFormat** is used for formating currency inputs 
- whenever I have typed any number it is getting formated(it may include dot) if we add dot again whole number goes away

Expected Output: 
input : **1234.12**
output: For EURO: **1.234,12**

expected output: 
https://jsfiddle.net/yqd75es3/3/

**Comment by martenbjork** [comment]
This is the Polaris repo, not the MUI repo.
