### ISSUE TITLE
[polaris.shopify.com] Feedback (on /components/selection-and-input/index-filters)

### ISSUE THREAD

**Issue by AshD91** [Shopify/polaris-react-archive#9208]
I created project as per this doc https://shopify.dev/docs/apps/getting-started/create 
& added this code in my web/frontend/pages/pagename.jsx file, following error is throwing 
![Screenshot from 2023-05-15 15-08-22](https://github.com/Shopify/polaris/assets/25473981/3f6b7007-d9c9-4fa7-9997-148011195fc5)

**Comment by chloerice** [comment]
Hey @AshD91 👋🏽 Since you're not using TypeScript, I think the TypeScript syntax used in the style guide example might be what's causing this type import to throw.

**Comment by AshD91** [comment]
> Hey @AshD91 👋🏽 Since you're not using TypeScript, I think the TypeScript syntax used in the style guide example might be what's causing this type import to throw.

yehh...I think so, its .jsx file
can you provide me the ref link where I can find jsx with polaries...or any other option

**Comment by chloerice** [comment]
Shopify's internal tech stack uses TypeScript React, so the examples are built with TypeScript. You can convert the TSX to JSX in your terminal using `tsc`:

```bash
npx tsc --jsx preserve -t es2020 --outDir <path> --noEmit false
```
