### ISSUE TITLE
[Button and Link quality][Products]Links that require manual updates

### ISSUE THREAD

**Issue by nayeobkim** [Shopify/polaris-react-archive#9213]
### Products

[Google doc audit](https://docs.google.com/document/d/1AycSekG0n_3w67wZ6cKOEPawwPhix2ssO7EK7O8Ckv4/edit?usp=sharing)

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-af10759e-7fff-f7c4-4330-8f4f53d9c9ac"><div dir="ltr" style="margin-left:0pt;" align="left">

Product details | Underline | Notes |  
-- | -- | -- | --
Product organization card | Add |   | ![Image](https://github.com/Shopify/polaris/assets/99563941/282626e3-ff78-46f4-940a-b5b03dffebc9) | 
Variant details |   |   |  
Variant name card | Remove | Not sure why we need this link though. As the Back button seems to be doing the same. | ![Image](https://github.com/Shopify/polaris/assets/99563941/0014e3a6-b4f8-4858-b585-73c1bc48987e) | 
Options card | Remove |   | ![Image](https://github.com/Shopify/polaris/assets/99563941/2e07f7d2-707c-4e00-b4fa-f4bce6300625) |
Gift card details | | |  
Gift card details card | Remove |   | ![Image](https://github.com/Shopify/polaris/assets/99563941/17d74d43-2043-40fc-ae01-e605f997630e) |

</div><br /></b>

**Comment by aveline** [comment]
Also removed `Link` underlines on these two cards

|Before|After|
|---|---|
|<img width="651" alt="Screenshot 2023-05-17 at 7 25 52 AM" src="https://github.com/Shopify/polaris/assets/3474483/ed0fe150-055e-4bc8-b7b9-1c81d1d16ec5">|<img width="513" alt="Screenshot 2023-05-17 at 7 46 29 AM" src="https://github.com/Shopify/polaris/assets/3474483/f2408ed4-19de-475d-aaa5-ab043cca7050">
