### ISSUE TITLE
[polaris.shopify.com] Feedback (on /components/navigation/tabs)

### ISSUE THREAD

**Issue by teocorona** [Shopify/polaris-react-archive#9337]
I don't know if this is a bug or a missing explanation in the docs but the new Tabs  doesn't work as expected in small screens.
When I resize the screen in my proyect or in the codesandbox example, the tab content hides, it seems to work well in the merchant dashboard.
I will appreciate any hint on this.
(my first issue here, hope I'm not messing out)
<img width="656" alt="Captura de pantalla 2023-05-31 a la(s) 5 57 56 p m" src="https://github.com/Shopify/polaris/assets/12520967/9d1b7658-a8fb-4c03-ae15-f14a582542e3">
<img width="559" alt="Captura de pantalla 2023-05-31 a la(s) 5 58 17 p m" src="https://github.com/Shopify/polaris/assets/12520967/ac1cce4d-46d9-4712-bc43-87959ebe5b07">

**Comment by teocorona** [comment]
Own proyect: "@shopify/polaris": "^10.47.1",
Codesandbox: "@shopify/polaris": "latest",

**Comment by teocorona** [comment]
so after exploring the dom and styles I found a workaround with simple css
```
.Polaris-AlphaTabs__Outer{
  height: auto;
}
```
not closing beacause this (imo) seems a bug that needs to be solved

**Comment by gitlexa** [comment]
The same issue is observed in version 11.1.2.

In the browser logs:
```
Warning: Prop `className` did not match. Server: "Polaris-Text--root Polaris-Text--bodySm Polaris-Text--semibold" Client: "Polaris-Text--root Polaris-Text--bodyMd Polaris-Text--semibold"
```

New temporary solution fix:
```
.Polaris-Tabs__Outer{
  height: auto;
}
