### ISSUE TITLE
[Icon]: Update icon FolderMajor

### ISSUE THREAD

**Issue by augiethehuman** [Shopify/polaris-react-archive#9358]
### Why are you proposing this update?

The folders appear unusually tall relative to the other icons, making it difficult to discern their shape due to the disproportionate dimensions.

### Icon name

FolderMajor

### What type of icon set?

Major (20x20)

### Icon SVG code

```shell
<svg>...</svg>
```

### Are there any other important details?

I've noticed some icons hug 20x20, while others are 18x18, any reason for this specifically?

**Comment by heyjoethomas** [comment]
Icons may have different heights to create optical alignment and weight. An icon with a square base shape will appear bigger than a circle base shape if they are both 20x20. To compensate for this, the square base icon will usually be shrunk down a pixel or two so it is optically the same visual size and weight.
