### ISSUE TITLE
[IndexTable] Extra space below index table on Firefox

### ISSUE THREAD

**Issue by dustinfirman** [Shopify/polaris-react-archive#9362]
## Issue summary

On Firefox, the `IndexTable` component shows a space for the scrollbar at the bottom of the index table. This is show even if there is no horizontal scrolling needed. 
## Expected behavior

The space for the scrollbar should only show if the table overflows in the x direction.

## Actual behavior

Space for the scrollbar is rendered below the table, even when it doesn't overflow. The screenshot shows an example in the Shopify web admin

![Screenshot 2023-06-02 at 1 43 27 PM](https://github.com/Shopify/polaris/assets/105817582/30eb6fd7-8517-4a49-8d6e-4f6ef4cc1355)

## Steps to reproduce the problem

1. Open a Firefox browser
2. Go to a page that renders an index table, for example https://polaris.shopify.com/components/tables/index-table

## Reduced test case

Seems to show on every index table in Firefox.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 10.49.1
- Browser: Firefox
- Device: Desktop
- Operating System: MacOS 13.4

**Comment by chloerice** [comment]
This is no longer reproducible.
