### ISSUE TITLE
Figma UIKit missing shadow tokens that are available on polaris.shopify.com

### ISSUE THREAD

**Issue by Rawdreen** [Shopify/polaris-react-archive#9378]
**UI Kit Shadows & elevations page doesn't have followings:**
--p-shadow-inset-lg;
--p-shadow-inset-sm;
--p-shadow-none;
--p-shadow-xs;
--p-shadow-lg;

Side notes:
1. It would be great to have versioning for the UI Kit, similar to how it's done in the Ant Design System UI Kit
2. I mentioned that everything related to tokens in the documentation has changed, but the UI Kit does not reflect these changes. It would be great if you could provide at least the `tokens.json` file, so that users can import the tokens as styles into their Figma project files.

**Comment by alex-page** [comment]
Thanks for opening the issue. We are pretty jam packed right now but I will pass on this feedback to the designers.

1. Agree that we need better versioning for the UIKit this is something we are working on
2. The tokens JSON files live here: https://unpkg.com/browse/@shopify/polaris-tokens@7.0.0/dist/json/

**Comment by alex-page** [comment]
The shadows currently show the shadows we want to document publicly. Going to close this issue https://polaris.shopify.com/tokens/shadow
