### ISSUE TITLE
Is "Polaris Summer Edition" intended as next version of Polaris?

### ISSUE THREAD

**Issue by mhlozek** [Shopify/polaris-react-archive#9427]
Hi there,
I noticed in the closed commits that you are preparing "Summer Edition" of Polaris. 

https://5d559397bae39100201eedc1-igjebaymjw.chromatic.com/?path=/story/playground--details-page&globals=polarisSummerEditions2023:true

There are many design changes - buttons, border-radius, modified colors etc. Some of the changes are quite "drastic", such as the design of submit buttons, colors in the main navigation...

Is this planned as the next version of Polaris, which will replace the current one or should it be only a temporary change during the summer?

**Comment by chloerice** [comment]
Hey @mhlozek, these styles are a work in progress. We appreciate your excitement about the latest changes you see here on GitHub and look forward to sharing more when we're ready.
