### ISSUE TITLE
[polaris.shopify.com] Feedback (on /tokens/color)

### ISSUE THREAD

**Issue by readikus** [Shopify/polaris-react-archive#9480]
Needs intro tutorial to tokens + examples of how to use them.

https://polaris.shopify.com/ has a top level item to link to Tokens, but this route doesn't provide any details of what they are/how to use them.

**Comment by aryankeluskar** [comment]
I am fixing the issue by adding a small guide on using tokens.
My guide will be in accordance with the README of Polaris Tokens as https://github.com/Shopify/polaris/tree/main/polaris-tokens#installation

**Comment by aryankeluskar** [comment]
Apart from my summary, I am providing the link (https://github.com/Shopify/polaris/tree/main/polaris-tokens#installation) as well

**Comment by aryankeluskar** [comment]
### Before: <br>
 ![image](https://github.com/Shopify/polaris/assets/80093392/d7717710-83c6-47d3-891a-49c93582e1c1)

### After: <br>
 ![image](https://github.com/Shopify/polaris/assets/80093392/da68b105-4c4e-45e4-bd8f-b49c766e8804)
![image](https://github.com/Shopify/polaris/assets/80093392/7377e5cf-cf24-489c-aec0-6e8fae4843c1)
![image](https://github.com/Shopify/polaris/assets/80093392/6dfa5623-9d30-4848-a168-9263ce183755)
