### ISSUE TITLE
Content is not visible in tabs on screens with max-width 48rem in the new Card component

### ISSUE THREAD

**Issue by stacy-22** [Shopify/polaris-react-archive#9534]
## Issue summary

There is a bug in [Card](https://polaris.shopify.com/components/layout-and-structure/card) component. When I resize the screen, the content under the tabs becomes invisible because the height for that content is `3.5rem`. 
<img src="https://screenshot.click/26-43-0sd8y-3rypa.png">

## Expected behavior
The tabs content in the [Card](https://polaris.shopify.com/components/layout-and-structure/card) component is visible on all screens. 

## Actual behavior
https://screenshot.click/26-43-0sd8y-3rypa.png
As you can notice on the video, I have to add a custom class and rewrite height with `height: inherit`. 

## Steps to reproduce the problem

1. Create a [Card](https://polaris.shopify.com/components/layout-and-structure/card) with tabs inside
2. Add content for tabs with height more than `3.5rem`
3. Resize the screen

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications
<img src="https://screenshot.click/26-49-mhw5p-j6fz4.png">

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by ibwidhi** [comment]
Refer to this [page](https://github.com/Shopify/polaris/issues/9337)

**Comment by stacy-22** [comment]
Will close as it a duplicate of https://github.com/Shopify/polaris/issues/9337
