### ISSUE TITLE
How can I view the historical version of the document?

### ISSUE THREAD

**Issue by bithaolee** [Shopify/polaris-react-archive#9587]
How can I view the historical version of the document? https://polaris.shopify.com can only look at the latest version of the document, the latest version of the polaris is dependent on react18, I was using a low version of the Polaris, I refer to historical version of the document to solve a bug, but couldn't find it.

**Comment by bafna-hitesh** [comment]
Here you can see the changes in all the historical versions. 
https://github.com/Shopify/polaris/tree/main/documentation/guides
