### ISSUE TITLE
[IndexTable] Sticky header is misaligned when selectable=false 

### ISSUE THREAD

**Issue by karrocon** [Shopify/polaris-react-archive#9591]
## Issue summary
Widths of the headings are not computed as they should when `selectable={false}`. 

## Expected behavior
Sticky header should have the same column distribution as in the normal header.

## Actual behavior
![indextable-stickyheader-issue](https://github.com/Shopify/polaris/assets/7526777/b62126db-f92f-4351-b849-2d42b59a4722)

## Steps to reproduce the problem
1. Scroll down so that the sticky header is shown

## Reduced test case
[Code sandbox](https://codesandbox.io/s/compassionate-goldstine-xrwcnh?file=/App.tsx)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: Latest
- Browser: Chrome 114.0.5735.198
- Device: MacBook Pro M1
- Operating System: Ventura 13.4.1

**Comment by VeeGLZ** [comment]
Same problem but even more misaligned.
