### ISSUE TITLE
Tabs Component & newViewAccessibilityLabel prop not working

### ISSUE THREAD

**Issue by NTXAggie** [Shopify/polaris-react-archive#9608]
## Issue summary

I am trying to use the Tabs Component, but not for 'views'. So I wanted to use the `newViewAccessibilityLabel` attribute to change the text when adding a new tab (as per the docs: https://polaris.shopify.com/components/navigation/tabs). I did not get it to change anything, and tried forking your sandbox from the above link without luck as well. 

## Expected behavior

If I add `newViewAccessibilityLabel="Add New Schedule"` to a <Tabs> component, I would expect it to update the text on the button tooltip, as described in the docs.

## Actual behavior

Nothing changes, it ignores the property.

## Steps to reproduce the problem

1. Integrate a <Tabs> Component into a react app.
2. Add the `canCreateNewView` attribute to the component to show the + button at the end of the tabs
3. Now add the `newViewAccessibilityLabel` to the component and see that nothing changes.

## Reduced test case

https://codesandbox.io/s/laughing-einstein-3qdrhz?file=/App.tsx 

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number: "latest" (11.3.1)
- Browser: Chrome
- Device: Desktop
- Operating System: Windows 10

**Comment by StefanoDiLegami** [comment]
I have the same issue. 
We need a way to change the default text of the canCreateNewView Modal and Popover, to be able to use it in a different context.
