### ISSUE TITLE
padding improvements to <Box />

### ISSUE THREAD

**Issue by m4thieulavoie** [Shopify/polaris-react-archive#9629]
## Feature request summary

I'd like to propose the introduction of a few additional padding features to `Box`

 - introduce `paddingInline` and `paddingBlock` props
 - allow for `padding` to accept two values like in native CSS (e.g. `padding="1 2"`)

## Rationale

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s :+1: upvotes to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by raphaelghub** [comment]
💯! Would also be great if we had the same for `margin`s and `border`s also: (e.g. margin="1 2" , border="1 solid red")
