### ISSUE TITLE
Embedded App: Page Actions and Breadcrumbs opening in new window

### ISSUE THREAD

**Issue by cgenevier** [Shopify/polaris-react-archive#97]
# Issue summary

When adding a Page with primary actions, secondary actions, and breadcrumbs, the URL is always opened in a new window instead of within the app. Note that this issue is also mentioned in [this comment](https://github.com/Shopify/polaris/issues/67#issuecomment-308246155).

## Expected behavior

With the sample code below, I would expect that the target for the actions (specifically the "Do Something" button and the "Dashboard" breadcrumb) would be set to 'app' by default, or at least allow for a way to explicitly specify the target.

```
<EmbeddedApp apiKey={this.state.shopify_api_key} shopOrigin={this.state.shopify_shop}>
  <Page
     title="My Sample Page"
     primaryAction={{
     content: 'Do Something',
     url: '/do-something'
     }}
     breadcrumbs={[{content: 'Dashboard', url: "/dashboard"}]}
  >
  </Page>
</EmbeddedApp>
```

## Actual behavior

Instead, a new window is opened pointing to the URL.

## Steps to Reproduce the Problem

1. Create an embedded app using the above code

## Specifications

- Polaris version: 1.0.3
- React version: 15.5.4
- Browser: Any
- Device: Any
- Operating System: Any

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by lemonmade** [comment]
Should be addressed by v1.1.1 (we will automatically infer whether to open in Shopify or in the iframe based on the `url` property of the object you pass in).
