### ISSUE TITLE
[SkeletonBodyText] [HorizontalStack] Allow item to fill remaining horizontal space

### ISSUE THREAD

**Issue by andy-schneidr** [Shopify/polaris-react-archive#9703]
## Issue summary

With `HorizontalStack`, there's no built-in way to have an element fill the available space. A common place this problem arises is when using `SkeletonBodyText`, which has no width defined for all but the last line.

[Slack thread regarding SkeletonBodyText](https://shopify.slack.com/archives/C4Y8N30KD/p1689115584328399)

## Expected behavior

With LegacyStack, it was possible to use `<LegacyStack.Item fill>`, which would allow an item to fill the remaining available space.

As far as a solution/definition of done, three potential solutions might be:
1. Implement something analogous to `<HorizontalStack.Item fill>` (or [InlineStack](https://github.com/Shopify/ui-api-design/pull/108)?)
2. Implement <SkeletonBodyText> as a single wrapper (with `max-width: 100%`, or something) containing the individual SkeletonBodyText lines
3. Implement some generic reusable component with `width: "100%", flex: "1 1 auto"` which could be utilized in cases like this

## Actual behavior

Without some kind of container to use in a `HorizontalStack` that provides `width`, components like `SkeletonBodyText` with no width do not appear correctly:
![image](https://github.com/Shopify/polaris/assets/107708248/d9204d31-bd2f-4635-aa21-b3423ab30e5b)

- SkeletonBodyWidth has a width of 0, except for the last line, so only the last line appears in the last case ☝️ 

## Steps to reproduce the problem

As an example, create a skeleton for an image next to some text:
```
<HorizontalStack wrap={false} blockAlign={"start"} gap="4">
  <SkeletonThumbnail size="small" />
  <SkeletonBodyText lines={3} />
</HorizontalStack>
```

## Reduced test case

https://codesandbox.io/s/agitated-neco-vxdm8z?file=/App.tsx

## Specifications

- Are you using the React components? (Y/N): Yes
- Polaris version number: "latest" (11.5.3)
- Browser: Chrome
- Device: MacBook Pro 14"
- Operating System: macOS 13.4.1 (22F82)

**Comment by jesstelford** [comment]
I think #2 is the correct approach: Wrap it in a block element to give it the correct flow direction.

Setting a default width is good.
