### ISSUE TITLE
Bug in ColorPicker

### ISSUE THREAD

**Issue by zappingseb** [Shopify/polaris-react-archive#9709]
## Fix Brightness bug in ColorPicker

The HSL values the ColorPicker returns are wrong.

The brightness scale of the current ColorPicker is going from 0 to 100 independent of the `saturation` value. This is not the case for a proper colorpicker. The colorpicker always selects brightness from 0-100. That's not the way users use color pickers.

## Rationale

A ColorPicker works like this:

Saturation 100%, Max Brightness 50%

![image](https://github.com/Shopify/polaris/assets/13066661/76b9cfff-8aa6-4ccf-9943-62b52e6153b5)

Saturation 0%, Max Brightness 100%

![image](https://github.com/Shopify/polaris/assets/13066661/2bbcb91a-cb20-4ae1-b6da-d52eeeef8362)

## Please change

Please simply change your brightness value to:

``
new.brightness = old.brightness - ((old.saturation) / 2)
```

**Comment by tommypepsi** [comment]
Just got the same issue, I managed to get the correct brightness by doing a similar formula:
```javascript
// Temporary fix for brightness not being set correctly
const brightnessAdjustPercent = 1 - (0.5 * color.saturation);
const brightness = color.brightness * brightnessAdjustPercent;
```

I'm guessing it's doing the same thing but that's how my brain managed to figure it out 😅

**Comment by Wilhemmda** [comment]
> Just got the same issue, I managed to get the correct brightness by doing a similar formula:
> 
> ```js
> // Temporary fix for brightness not being set correctly
> const brightnessAdjustPercent = 1 - (0.5 * color.saturation);
> const brightness = color.brightness * brightnessAdjustPercent;
> ```
> 
> I'm guessing it's doing the same thing but that's how my brain managed to figure it out 😅

This is working better!! Thanks!!
