### ISSUE TITLE
[Icon]: New icon map

### ISSUE THREAD

**Issue by rachelng** [Shopify/polaris-react-archive#9780]
### How will these icons be used?

[Figma link for updated map icon](https://www.figma.com/file/yhTOfzr3lXrDnLbwiUDZPR/Analytics-%2B-Polaris-uplift?type=design&node-id=2191-125750&mode=design&t=RsOtWt47SRHOnzrl-4)

This icon is used in `Analytics > Live view` to switch between the globe view vs the map view. The current map view icon is in the style of gen 2 and was not previously added to the library. 

![map-2](https://github.com/Shopify/polaris/assets/6186705/8a43cc70-2fea-46dc-8b47-ce7a51cf9599)

### Icon name

map

### What type of icon set?

Major (20x20)

### Icon description

Action: switch to map view

### Icon keywords

map

### Icon author

Rachel Ng, Adam Perron

### Icon SVG code

```shell
<svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M5.25 2.71429L1.59848 1.14935C1.43351 1.07865 1.25 1.19966 1.25 1.37914V11.1209C1.25 11.2209 1.3096 11.3113 1.40152 11.3507L5.25 13M5.25 2.71429V13M5.25 2.71429L9 1M5.25 13L9 11.2857M9 1L12.6039 2.64752C12.6929 2.68819 12.75 2.77704 12.75 2.87488V12.6108C12.75 12.7929 12.5616 12.9139 12.3961 12.8382L9 11.2857M9 1V11.2857" stroke="black" stroke-width="1.5" stroke-linejoin="round"/>
</svg>
```

**Comment by pbojinov** [comment]
Should we submit this icon to the [polaris-icons](https://github.com/Shopify/polaris/tree/main/polaris-icons/icons) repo?
