### ISSUE TITLE
Modular css/scss imports 

### ISSUE THREAD

**Issue by danieljoffe** [Shopify/polaris-react-archive#9838]
## Feature request summary

According to the current documentation, one must import the entire [Polaris.css file](https://github.com/Shopify/polaris/tree/main/polaris-react#usage-1) into the project. This is fine if we're using all the components available. I've bee looking all over the documentation and reviewed the library in the node_modules folder to make sure I wasn't missing anything but I can't find a modular approach to importing the component styles. 

## Rationale

Say I'm only using a `Page`, `Layout`, `Text`, and `VeritcalStack` on one page, I shouldn't have to load the entire compiled polaris.css file to style the page. Current approach is not allowing for tailored pages on my current app. 

I've used purge CSS approaches to get rid of extra classes but it's not the best approach as the tool removes too much or not enough styling.

---

If I'm missing any clues on how to do this please provides details to make it obvious to others as well.
Thank you

Current stack
```.json
"next": "^13.4.10"
"@shopify/polaris": "^11.9.0",
```

**Comment by panzerdp** [comment]
Currently I have a few simple forms embedded into Shopify admin, but Polaris forces me to download the entire Polaris CSS. It would be great to have a more modular approach and pick only the necessary CSS.

Reducing the CSS size is also important because Shopify measures the core web vitals of embedded apps. Including the whole CSS increases the LCP.

**Comment by jesstelford** [comment]
The `build/esnext` folder contains modular CSS exports. You can [see them here](https://unpkg.com/browse/@shopify/polaris/build/esnext/) (eg; [see `Avatar.css`](https://unpkg.com/browse/@shopify/polaris@12.21.0/build/esnext/components/Avatar/Avatar.css)).

If your build tool is configured to use the `esnext` entry point as [defined in the Polaris `package.json`](https://github.com/Shopify/polaris/blob/9c24a465c5e001e148bde335bf6319e924f4b1d6/polaris-react/package.json#L40), and your build tool is able to compile the modern JS syntax, your bundles should only include CSS for the components you're importing.
