### ISSUE TITLE
Support for embed components

### ISSUE THREAD

**Issue by m4thieulavoie** [Shopify/polaris-react-archive#9876]
## Feature request summary

In many scenarios, we would like to be able to attach floating popovers around nested Polaris components. One example is for the bulk actions of the index table

![image](https://github.com/Shopify/polaris/assets/7046505/7633a292-a478-457b-bb32-bbadee92b25b)

## Rationale

It's very hard to add floating items given that we do not have any way to hook ourselves on nested Polaris components. We would like either
 - to be able to attach Popovers to bulk actions
 - [preferred approach] to be able to attach any component to any nested Polaris component we as a consumer don't have access to

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s :+1: upvotes to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by YashfaIjaz** [comment]
Needed
