### ISSUE TITLE
Polaris Tabs taking attention from Textfields.

### ISSUE THREAD

**Issue by pjf1822** [Shopify/polaris-react-archive#9888]
Im having this new issue since i have updated my @shopify/polaris package to "^11.10.2".  When i load this particular page and type into one of the two textfields everything is fine. but the moment i click on the form below using <Tabs> and go back to the textfields i cant type more than one letter without the attention of the of the page jumping to focus on one of the tabs.it outlines it blue.  
"react": "^18.2.0"
im on chrome on mac but i am having the same problem when i give it a go in firefox

**Comment by mbaumbach** [comment]
Possibly related: https://github.com/Shopify/polaris/issues/9736

**Comment by pjf1822** [comment]
ill check it out thanks Marc
