### ISSUE TITLE
Polaris API alignment

### ISSUE THREAD

**Issue by sam-b-rose** [Shopify/polaris-react-archive#9898]
TL;DR: Polaris components need simpler, more consistent component prop APIs so 1P and 3P admin builders can ship faster and more intuitively. The UI API Design Working Group aligned on improved component APIs across Shopify UI libraries that we’ll ship in Polaris v12 to prevent unwanted style variants and provide a consistent developer experience.
```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/polaris/issues/9914
```

**Comment by kyledurand** [comment]
https://github.com/Shopify/polaris/issues/9914
