### ISSUE TITLE
[TextField] Consolidate se23 logic and styles

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#9972]

**Comment by jesstelford** [comment]
As part of this work, we should leverage the change made in https://github.com/Shopify/polaris/pull/10081 to replace the hard-coded `min-height` with `min-height: control-height()`:

https://github.com/Shopify/polaris/blob/23c1391aa694526ce467c74de7c19d330f03ea67/polaris-react/src/components/TextField/TextField.scss#L199

See context in this comment: https://github.com/Shopify/polaris/pull/10081#pullrequestreview-1583731529
