### ISSUE TITLE
TextContainer - Delete deprecated component

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#9996]

**Comment by yurm04** [comment]
`TextContainer` was slated to be deprecated a few months back. Can we delete it instead? There's a migration PR open that I shipped and then got reverted due to issues with regressions. We could take another stab at the migration

web migration https://github.com/Shopify/web/pull/84360
polaris migration script https://github.com/Shopify/polaris/pull/8424

**Comment by yurm04** [comment]
opted to delete this component rather than migrate the props

**Comment by yurm04** [comment]
Dependency on `VerticalStack` https://github.com/Shopify/polaris/issues/9984 let's wait until it's renamed to `BlockStack` before deleting/migrating in our own codebase ex. https://github.com/Shopify/polaris/blob/1d82a3b122fc1d47a14d978d180f3e9e5d5359e2/polaris-react/src/components/Banner/Banner.stories.tsx#L141-L152

**Comment by kyledurand** [comment]
[Closing due to complications](https://github.com/Shopify/polaris/pull/10433#issuecomment-1720132386)
